### ISSUE TITLE
_dataSeeder.SeedAsync  error

### ISSUE THREAD

**Issue by 312977** [abpframework/abp#10000]
```
var tenant = await _tenantManager.CreateAsync(input.Name);
await _tenantRepository.InsertAsync(tenant, false, new CancellationToken());
using (CurrentTenant.Change(tenant.Id, tenant.Name))
{

    await _dataSeeder.SeedAsync(new DataSeedContext(tenant.Id)
   .WithProperty("AdminEmail", input.Phone + "@test.com")
   .WithProperty("AdminPassword", input.Phone));
}
```
get full error log below.   the  exception  no message,

```
System.Exception
   at Test.IdentityServer.IdentityServerDataSeedContributor.ChangeAdminDefaultPassWord() in D:\Code\SiYuan\XiaoYuanZhuShouNew\src\Test.Domain\IdentityServer\IdentityServerDataSeedContributor.cs:line 78
   at Test.IdentityServer.IdentityServerDataSeedContributor.SeedAsync(DataSeedContext context) in D:\Code\SiYuan\XiaoYuanZhuShouNew\src\Test.Domain\IdentityServer\IdentityServerDataSeedContributor.cs:line 66
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Test.Api.PlatformAdmin.Tenants.TenantsAppService.CreateAsync(CreateTenantDto input) in D:\Code\SiYuan\XiaoYuanZhuShouNew\src\Test.Application\Api\PlatformAdmin\Tenants\TenantsAppService.cs:line 78
   at lambda_method1671(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-09-10 00:18:54.792 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2021-09-10 00:18:54.800 +08:00 [INF] Executed action Test.Api.PlatformAdmin.Tenants.TenantsAppService.CreateAsync (Test.Application) in 2229.4787ms
```

**Comment by ebicoglu** [comment]
you got the 10.000 issue number :)

**Comment by 312977** [comment]
haha

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by 312977** [comment]
ABP Framework version  4.4.0

**Comment by 312977** [comment]
the exception meesage is enmpty

**Comment by 312977** [comment]
i  fix it  becauce ,the seed user password not valid.the exception message is not corect
