### ISSUE TITLE
Volo.Abp.Data.DataFilter.IsEnabled<TFilter>() reference not set to an instance of an object

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#10090]
Microservice pro template after upgrade from 4.4.0 to 4.4.2 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Data.DataFilter.IsEnabled[TFilter]() in D:\Github\hitasp\abp\framework\src\Volo.Abp.Data\Volo\Abp\Data\DataFilter.cs:line 39
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.get_IsSoftDeleteFilterEnabled() in D:\Github\hitasp\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 43
   at lambda_method1482(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Volo.Abp.LanguageManagement.EntityFrameworkCore.EfCoreLanguageRepository.GetListByIsEnabledAsync(Boolean isEnabled, CancellationToken cancellationToken) in D:\Github\hitasp\abp-pro\language-management\src\Volo.Abp.LanguageManagement.EntityFrameworkCore\Volo\Abp\LanguageManagement\EntityFrameworkCore\EfCoreLanguageRepository.cs:line 26
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in D:\Github\hitasp\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 24
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\hitasp\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 43
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in D:\Github\hitasp\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAsyncAbpInterceptorAdapter.cs:line 29
   at Volo.Abp.LanguageManagement.DatabaseLanguageProvider.<GetLanguagesAsync>b__14_0() in D:\Github\hitasp\abp-pro\language-management\src\Volo.Abp.LanguageManagement.Domain\Volo\Abp\LanguageManagement\DatabaseLanguageProvider.cs:line 37
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token) in D:\Github\hitasp\abp\framework\src\Volo.Abp.Caching\Volo\Abp\Caching\DistributedCache.cs:line 509
   at Volo.Abp.LanguageManagement.DatabaseLanguageProvider.GetLanguagesAsync() in D:\Github\hitasp\abp-pro\language-management\src\Volo.Abp.LanguageManagement.Domain\Volo\Abp\LanguageManagement\DatabaseLanguageProvider.cs:line 35
   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync() in D:\Github\hitasp\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\RequestLocalization\DefaultAbpRequestLocalizationOptionsProvider.cs:line 49
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\Github\hitasp\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\RequestLocalization\AbpRequestLocalizationMiddleware.cs:line 28
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by hitaspdotnet** [comment]
This because local installed of dotnet core 6 SDK 
Add global sdk target config to resolve

**Comment by niubanjin** [comment]
why
