### ISSUE TITLE
ModelStateValidator does not intercept error if the error happens in the item from collection of DTO objects inside another DTO object

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#10143]
**ABP 4.3.0 / Angular / EF Core**

I've overridden `ModelStateValidator` to format error message for nested scenarios:

```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IModelStateValidator))]
    public class AbxModelStateValidator : ModelStateValidator
    {
        public override void Validate(ModelStateDictionary modelState)
        {
            var validationResult = new AbpValidationResult();

            base.AddErrors(validationResult, modelState);

            if (validationResult.Errors.Any())
            {
                throw new BusinessException(
                    DomainErrorCodes.InvalidInput,
                    validationResult.Errors.Select(x => x.ErrorMessage).Aggregate((prev, next) => $"{prev}, {next}"));
            }
        }
    }
```

However, when I have DTO object containing collection of another DTO objects and the object from the collection has validation error:

    public class LawCreateUpdateDto
    {
        public List<LawDetailCreateUpdateDto> Laws { get; set; }
    }

 `ModelStateValidator` does not intercept such validation error for some reason. And I'm getting such exception stack:

> [18:23:20 ERR] Volo.Abp.Validation.AbpValidationException: Method arguments are not valid! See ValidationErrors for details.
>    at Volo.Abp.Validation.MethodInvocationValidator.ThrowValidationError(MethodInvocationValidationContext context)
>    at Volo.Abp.Validation.MethodInvocationValidator.Validate(MethodInvocationValidationContext context)
>    at Volo.Abp.Validation.ValidationInterceptor.Validate(IAbpMethodInvocation invocation)
>    at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
>    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
>    at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
>    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
>    at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
>    at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
>    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
>    at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at AbxEps.Fines.Controllers.Laws.LawController.UpdateAsync(Int32 lawId, LawCreateUpdateDto input) in C:\CT\AbxEps.Fines\aspnet-core\src\AbxEps.Fines.HttpApi\Laws\LawController.cs:line 65
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> Volo.Abp.Validation.AbpValidationException: Method arguments are not valid! See ValidationErrors for details.
>    at Volo.Abp.Validation.MethodInvocationValidator.ThrowValidationError(MethodInvocationValidationContext context)
>    at Volo.Abp.Validation.MethodInvocationValidator.Validate(MethodInvocationValidationContext context)
>    at Volo.Abp.Validation.ValidationInterceptor.Validate(IAbpMethodInvocation invocation)
>    at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)

I want to be able to intercept various validation errors in the same place.

**Comment by alexandis** [comment]
I've resolved the issue myself. I suggest to change message in your code too, removing hard-coded message: "Method arguments are not valid! See ValidationErrors for details."

```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IMethodInvocationValidator))]
    public class AbxMethodInvocationValidator : MethodInvocationValidator
    {
        public AbxMethodInvocationValidator(IObjectValidator objectValidator) : base(objectValidator) { }

        protected override void ThrowValidationError(MethodInvocationValidationContext context)
        {
            if (context.Errors.Any())
            {
                throw new BusinessException(
                    DomainErrorCodes.InvalidInput,
                    context.Errors.Select(x => x.ErrorMessage).Aggregate((prev, next) => $"{prev}, {next}"));
            }
        }
    }
```
