### ISSUE TITLE
Bug on the feature management dialog

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10301]
I tried with ABP version 5.0.0-beta.1, but can be a problem with 4.x too (please you try it). If so, please fix it in rel-4.4 branch and then we merge to dev.

I have two feature definitions:

````csharp
using MtDemo.Localization;
using Volo.Abp.Features;
using Volo.Abp.Localization;
using Volo.Abp.Validation.StringValues;

namespace MtDemo
{
    public class MyFeatureDefinitionProvider : FeatureDefinitionProvider
    {
        public override void Define(IFeatureDefinitionContext context)
        {
            var myGroup = context.AddGroup("MyApp");
            
            myGroup.AddFeature(
                "MyApp.StockManagement",
                defaultValue: "false",
                displayName: L("StockManagement"),
                isVisibleToClients: true,
                valueType: new ToggleStringValueType());
            
            myGroup.AddFeature(
                "MyApp.MaxProductCount", 
                defaultValue: "100",
                displayName: L("MaxProductCount"),
                valueType: new FreeTextStringValueType(
                    new NumericValueValidator()));
        }

        private ILocalizableString L(string name)
        {
            return LocalizableString.Create<MtDemoResource>(name);
        }
    }
}
````

That creates a good UI:

![image](https://user-images.githubusercontent.com/1210527/136975648-8a8cbdfc-6e57-4155-9f94-c63ec772fc7a.png)

However, it throws exception when I try to save it with a value other than `0`:

![image](https://user-images.githubusercontent.com/1210527/136975425-b15aa4d6-a20e-45d7-865f-cfa8b09e2014.png)

The stacktrace:

````
2021-10-12 17:31:10.233 +03:00 [WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": "Volo.Abp.FeatureManagement:InvalidFeatureValue",
  "message": "Maximum allowed number of products feature value is not valid!",
  "details": null,
  "data": {
    "0": "Maximum allowed number of products"
  },
  "validationErrors": null
}

2021-10-12 17:31:10.233 +03:00 [WRN] Exception of type 'Volo.Abp.FeatureManagement.FeatureValueInvalidException' was thrown.
Volo.Abp.FeatureManagement.FeatureValueInvalidException: Exception of type 'Volo.Abp.FeatureManagement.FeatureValueInvalidException' was thrown.
   at Volo.Abp.FeatureManagement.FeatureManager.SetAsync(String name, String value, String providerName, String providerKey, Boolean forceToSet)
   at Volo.Abp.FeatureManagement.FeatureAppService.UpdateAsync(String providerName, String providerKey, UpdateFeaturesDto input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.FeatureManagement.Web.Pages.FeatureManagement.FeatureManagementModal.OnPostAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
2021-10-12 17:31:10.233 +03:00 [WRN] Code:Volo.Abp.FeatureManagement:InvalidFeatureValue
2021-10-12 17:31:10.234 +03:00 [WRN] Details:
2021-10-12 17:31:10.234 +03:00 [WRN] ---------- Exception Data ----------
0 = Maximum allowed number of products
````

**Comment by realLiangshiwei** [comment]
I think should set the minimum and maximum, because the default value is 0

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/StringValues/NumericValueValidator.cs#L9-L19

```csharp
myGroup.AddFeature(
                "MyApp.MaxProductCount", 
                defaultValue: "100",
                displayName: L("MaxProductCount"),
                valueType: new FreeTextStringValueType(
                    new NumericValueValidator(0, 99999)));   //Specify minimum and maximum
```

**Comment by realLiangshiwei** [comment]
It would be better if we use the min value and max value of int as default values, we can enhance it
