### ISSUE TITLE
Could not replace C# class of the view component

### ISSUE THREAD

**Issue by ertugrulbakidal** [abpframework/abp#10343]
* ABP Framework version: 4.4
* User Interface: MVC
* Database provider: EF Core

I am able to replace AccountProfilePasswordManagementGroup's Html and js by creating the same folder structure in my project but I'd like to replace AccountProfilePasswordManagementGroupViewComponent c# class itself and don't know how to replace it. From Abp documentation "If you need, you can also replace the code behind c# class of the component just using the dependency injection system.".

1. I've tried to replace only  AccountProfilePasswordManagementGroupViewComponent.cs with MyAccountProfilePasswordManagementGroupViewComponent.cs 

src/TestStore.Web/Pages/Account/Components/ProfileManagementGroup/Password/MyAccountProfilePasswordManagementGroupViewComponent.cs
```
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Volo.Abp.Account.Web.Pages.Account.Components.ProfileManagementGroup.Password;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Auditing;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Identity;
using Volo.Abp.Validation;

namespace TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(AccountProfilePasswordManagementGroupViewComponent))]
    public class MyAccountProfilePasswordManagementGroupViewComponent : AbpViewComponent
    {
        private readonly IProfileAppService _profileAppService;
        private readonly ILogger<MyAccountProfilePasswordManagementGroupViewComponent> _logger;

        public MyAccountProfilePasswordManagementGroupViewComponent(
            IProfileAppService profileAppService, ILogger<MyAccountProfilePasswordManagementGroupViewComponent> logger)
        {
            _profileAppService = profileAppService;
            _logger = logger;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            _logger.LogWarning("MyAccountProfilePasswordManagementGroupViewComponent::InvokeAsync called");
            var user = await _profileAppService.GetAsync();

            var model = new ChangePasswordInfoModel
            {
                HideOldPasswordInput = !user.HasPassword
            };

            return View("~/Pages/Account/Components/ProfileManagementGroup/Password/Default.cshtml", model);
        }
        
        public class ChangePasswordInfoModel
        {
            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:CurrentPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string CurrentPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPasswordConfirm")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPasswordConfirm { get; set; }

            public bool HideOldPasswordInput { get; set; }
        }
    }
    
    
}
```

The stacktrace:
```
C:\Users\ertug\AppData\Local\JetBrains\Installations\Rider212\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe --mode=client --frontend-port=15532 --plugins=C:\Users\ertug\AppData\Local\JetBrains\Installations\Rider212\plugins\rider-unity\dotnetDebuggerWorker
[11:59:13 INF] Starting web host.
[11:59:17 FTL] Host terminated unexpectedly!
System.ArgumentException: The type 'TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password.MyAccountProfilePasswordManagementGroupViewComponent' is not assignable to service 'Volo.Abp.Account.Web.Pages.Account
.Components.ProfileManagementGroup.Password.AccountProfilePasswordManagementGroupViewComponent'.
   at Autofac.Builder.RegistrationBuilder.CreateRegistration(Guid id, RegistrationData data, IInstanceActivator activator, IResolvePipelineBuilder pipelineBuilder, Service[] services, IComponentRegistration target)
   at Autofac.Builder.RegistrationBuilder.CreateRegistration[TLimit,TActivatorData,TSingleRegistrationStyle](IRegistrationBuilder`3 builder)
   at Autofac.Builder.RegistrationBuilder.RegisterSingleComponent[TLimit,TActivatorData,TSingleRegistrationStyle](IComponentRegistryBuilder cr, IRegistrationBuilder`3 builder)
   at Autofac.RegistrationExtensions.<>c__DisplayClass39_0.<RegisterType>b__0(IComponentRegistryBuilder cr)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```
2. I've tried to replace the view component completely.
src/TestStore.Web/Pages/Account/Components/ProfileManagementGroup/Password/MyAccountProfilePasswordManagementGroupViewComponent.cs

![folder_structure](https://user-images.githubusercontent.com/40223108/137625759-0d2008c8-36d8-423e-8f21-ef26c683ffd6.png)

```
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Volo.Abp.Account.Web.Pages.Account.Components.ProfileManagementGroup.Password;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Auditing;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Identity;
using Volo.Abp.Validation;

namespace TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password
{
    public class MyAccountProfilePasswordManagementGroupViewComponent : AbpViewComponent
    {
        private readonly IProfileAppService _profileAppService;
        private readonly ILogger<MyAccountProfilePasswordManagementGroupViewComponent> _logger;

        public MyAccountProfilePasswordManagementGroupViewComponent(
            IProfileAppService profileAppService, ILogger<MyAccountProfilePasswordManagementGroupViewComponent> logger)
        {
            _profileAppService = profileAppService;
            _logger = logger;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            _logger.LogWarning("MyAccountProfilePasswordManagementGroupViewComponent::InvokeAsync called");
            var user = await _profileAppService.GetAsync();

            var model = new ChangePasswordInfoModel
            {
                HideOldPasswordInput = !user.HasPassword
            };

            return View("~/Pages/Account/Components/ProfileManagementGroup/Password/Default.cshtml", model);
        }
        
        public class ChangePasswordInfoModel
        {
            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:CurrentPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string CurrentPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPasswordConfirm")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPasswordConfirm { get; set; }

            public bool HideOldPasswordInput { get; set; }
        }
    }
    
    
}
```
src/TestStore.Web/Pages/Account/Components/ProfileManagementGroup/Password/Default.cshtml
```
@using Volo.Abp.Account.Localization
@using Volo.Abp.Users
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<AccountResource> L
@inject ICurrentUser CurrentUser
@model TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password.MyAccountProfilePasswordManagementGroupViewComponent.ChangePasswordInfoModel

<h4>@L["ChangePassword"]</h4><hr/>
<form id="ChangePasswordForm">
    @if (!Model.HideOldPasswordInput)
    {
        <abp-input asp-for="CurrentPassword"/>
    }
    <abp-input asp-for="NewPassword"/>
    <abp-input asp-for="NewPasswordConfirm"/>
    <abp-button type="submit" button-type="Primary" text="@L["Submit"].Value"/>
</form>

```
The stacktrace:
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Volo.Abp.Account.Web.Pages.Account.Components.ProfileManagementGroup.Password.AccountProfilePasswordManagementGroupViewComponent+ChangePasswordInfoModel', but this ViewDataDictionary instance requires a model item of type 'TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password.MyAccountProfilePasswordManagementGroupViewComponent+ChangePasswordInfoModel'.

```
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, object model, Type declaredModelType)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<TModel>..ctor(ViewDataDictionary source)
lambda_method2338(Closure , ViewDataDictionary )
Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(object page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, object arguments)
Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, object arguments)
AspNetCore.Pages_Account_Manage+<>c__DisplayClass14_0+<<ExecuteAsync>b__7>d.MoveNext()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(bool useCachedResult, HtmlEncoder encoder)
Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Tab.AbpTabTagHelperService.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
AspNetCore.Pages_Account_Manage.<ExecuteAsync>b__14_6()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(bool useCachedResult, HtmlEncoder encoder)
Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Tab.AbpTabsTagHelperService.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
AspNetCore.Pages_Account_Manage.<ExecuteAsync>b__14_5()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Pages_Account_Manage.<ExecuteAsync>b__14_2()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Pages_Account_Manage.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension+<>c__DisplayClass0_0+<<UseJwtTokenMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```

**Comment by iyilm4z** [comment]
> The type 'TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password.MyAccountProfilePasswordManagementGroupViewComponent' is not assignable to service 'Volo.Abp.Account.Web.Pages.Account
.Components.ProfileManagementGroup.Password.AccountProfilePasswordManagementGroupViewComponent.

This means that you should inherit MyAccountProfilePasswordManagementGroupViewComponent from AccountProfilePasswordManagementGroupViewComponent.

Did you test it?

**Comment by ertugrulbakidal** [comment]
Well, I can not see any benefit inheriting from AccountProfilePasswordManagementGroupViewComponent as InvokeAsync is not virtual, so I can not override it:

```
public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _profileAppService.GetAsync();

            var model = new ChangePasswordInfoModel
            {
                HideOldPasswordInput = !user.HasPassword
            };

            return View("~/Pages/Account/Components/ProfileManagementGroup/Password/Default.cshtml", model);
        }
```
However, I've just tried for you :)

```
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Volo.Abp.Account.Web.Pages.Account.Components.ProfileManagementGroup.Password;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Auditing;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Identity;
using Volo.Abp.Validation;

namespace TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(AccountProfilePasswordManagementGroupViewComponent))]
    public class MyAccountProfilePasswordManagementGroupViewComponent : AccountProfilePasswordManagementGroupViewComponent
    {
        public MyAccountProfilePasswordManagementGroupViewComponent(IProfileAppService profileAppService) : base(profileAppService)
        {
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {

            var model = new ChangePasswordInfoModel
            {
            };

            return View("~/Pages/Account/Components/ProfileManagementGroup/Password/Default.cshtml", model);
        }
        
        
        public class ChangePasswordInfoModel
        {
            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:CurrentPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string CurrentPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPassword")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPassword { get; set; }

            [Required]
            [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxPasswordLength))]
            [Display(Name = "DisplayName:NewPasswordConfirm")]
            [DataType(DataType.Password)]
            [DisableAuditing]
            public string NewPasswordConfirm { get; set; }

            public bool HideOldPasswordInput { get; set; }
        }
    }
    
    
}
```

The stack trace:

InvalidOperationException: View component 'TestStore.Web.Pages.Account.Components.ProfileManagementGroup.Password.MyAccountProfilePasswordManagementGroupViewComponent' must have exactly one public method named 'InvokeAsync' or 'Invoke'.
```
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorProvider.FindMethod(Type componentType)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorProvider.CreateDescriptor(TypeInfo typeInfo)
System.Linq.Enumerable+SelectListIterator<TSource, TResult>.ToArray()
System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorCollectionProvider.GetViewComponents()
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorCollectionProvider.get_ViewComponents()
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.SelectComponent(Type componentType)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(Type componentType, object arguments)
Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, object arguments)
AspNetCore.Themes_Basic_Layouts_Application+<>c__DisplayClass13_0+<<ExecuteAsync>b__0>d.MoveNext()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Themes_Basic_Layouts_Application.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension+<>c__DisplayClass0_0+<<UseJwtTokenMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by iyilm4z** [comment]
Yes you are right the InvokeAsync method is not virtual but it should be virtual imho. I can make a pr for this but without inheriting from it also should work according to the doc. I'll check it.

**Comment by iyilm4z** [comment]
I've tested the case on my local environment and i came across with the same errors. Then i've wanted to read more docs and i found [this doc](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller) showing how to replace a controller. At the end of that doc there is the explanation below. 

> Overriding Other Classes
Overriding controllers, framework services, view component classes and any other type of classes registered to dependency injection can be overridden just like the examples above.

We applied exactly the same thing that is said on the doc. So i can say that there might be a bug related to DI system. So i'll check tests to be sure.

**Comment by ertugrulbakidal** [comment]
Any progress @iyilm4z

**Comment by iyilm4z** [comment]
@ertugrulbaki27 [AbpAspNetCoreMvcConventionalRegistrar_Tests](https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.AspNetCore.Mvc.Tests/Volo/Abp/AspNetCore/Mvc/DependencyInjection/AbpAspNetCoreMvcConventionalRegistrar_Tests.cs) doesn't contain a test method covers your case. However there may be a test at somewhere else that also covers your case. Even though that i wanted to write one but i coulnd't have time yet.

**Comment by iyilm4z** [comment]
@ertugrulbaki27 most probably i found a DI bug. I'll fix it.

**Comment by ertugrulbakidal** [comment]
@iyilm4z Great, thank you :)
