### ISSUE TITLE
ConsoleTestApp Exception

### ISSUE THREAD

**Issue by cld0815** [abpframework/abp#10440]
* Your **ABP Framework version**.
5.0.0-beta.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
blazor-server
* Your database provider(EF Core/MongoDB)
postgresql
* Exception message and **stack trace** if available (check the logs).
![%PHNLBJ2@2ACP( L3`KF~ME](https://user-images.githubusercontent.com/30192550/138831035-e5dff8b1-c0e4-45ec-877c-9074802bb64b.png)

   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.get_ClientProxyApiDescriptionFinder()
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.BuildHttpProxyClientProxyContext(String methodName, ClientProxyRequestTypeValue arguments)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__29`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Identity.ClientProxies.ProfileClientProxy.<GetAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at test.HttpApi.Client.ConsoleTestApp.ClientDemoService.<RunAsync>d__2.MoveNext() in F:\test\test\test.HttpApi.Client.ConsoleTestApp\ClientDemoService.cs:line 19

* Steps needed to **reproduce** the problem.
abp new test --ui blazor-server -dbms postgresql  --no-random-port --preview
run test.DbMigrator
run test.Blazor
run test.HttpApi.Client.ConsoleTestApp

**Comment by realLiangshiwei** [comment]
Hi,

See https://github.com/abpframework/abp/pull/10441

**Comment by cld0815** [comment]
Thanks
