### ISSUE TITLE
Angular unit testing

### ISSUE THREAD

**Issue by alireza-brz** [abpframework/abp#10515]
### Angular unit testing (Bug)

ABP version: 4.4.2
Interface: Angular

I have a problem with unit testing 

I'm getting this error 

`        TypeError: Cannot read properties of undefined (reading 'Default')
        error properties: Object({ longStack: 'TypeError: Cannot read properties of undefined (reading 'Default')
            at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:339:1
            at EnvironmentService.getApiUrl (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:355:1)
            at MockRestService.getApiFromStore (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:375:1)
            at MockRestService.request (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:384:1)
            at ClientService.getList (http://localhost:9876/_karma_webpack_/webpack:/src/app/proxy/clients/client.service.ts:37:22)
            at clientStreamCreator (http://localhost:9876/_karma_webpack_/webpack:/src/app/modules/contact/create-contact/create-contact.component.ts:262:6)
            at SwitchMapSubscriber.project (http://localhost ...
        TypeError: Cannot read properties of undefined (reading 'Default')
            at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:339:1
            at EnvironmentService.getApiUrl (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:355:1)
            at MockRestService.getApiFromStore (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:375:1)
            at MockRestService.request (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:384:1)
            at ClientService.getList (http://localhost:9876/_karma_webpack_/webpack:/src/app/proxy/clients/client.service.ts:37:22)
            at clientStreamCreator (http://localhost:9876/_karma_webpack_/webpack:/src/app/modules/contact/create-contact/create-contact.component.ts:262:6)
            at SwitchMapSubscriber.project (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:3613:42)
            at SwitchMapSubscriber._next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/operators/switchMap.js:28:1)
            at SwitchMapSubscriber.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:1)
            at ReplaySubject.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/Subject.js:39:1)
            at ____________________Elapsed_15_ms__At__Thu_Nov_04_2021_04_56_56_GMT_0330__Iran_Standard_Time_ (http://localhost)
            at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:105:1)
            at ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:386:1)
            at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:283:1)
            at ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:386:1)
            at Zone.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:221:1)
            at Zone.scheduleMacroTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:244:1)
            at scheduleMacroTaskWithCurrentZone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:679:1)
         at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:2585:1
`  

This is my test file 

            import { ComponentFixture, TestBed } from '@angular/core/testing';
            import { CreateContactComponent } from './create-contact.component';
            import { ClientDto, ClientService } from '@proxy/clients';
            import { BehaviorSubject } from 'rxjs';
            import { CoreTestingModule } from '@abp/ng.core/testing';
            import { ReactiveFormsModule } from '@angular/forms';
            import { ContactDto, ContactService, CreateContactDto } from '@proxy/contacts';

          const list$ = new BehaviorSubject<{
	          items: ClientDto[];
	          totalCount: number;
          }>({
	          items: [
		          {
			          id: 'some id',
			          tradingName: 'my company',
			          legalName: 'display name',
			          type: 1,
			          creditLimit: 1,
			          status: 1
		          }
	          ],
	          totalCount: 1
          });
          
          const contact$ = new BehaviorSubject<ContactDto>({
	          id: 'asda',
	          displayName: 'asdasd',
	          companyName: 'asdasd',
	          lastName: 'qweqwe',
	          mobile: 'qweqwe',
	          title: 'qweqwe',
	          reference: 'qweqwe',
	          firstName: 'qweqwe'
          });
          
          describe('CreateContactComponent', () => {
	          let component: CreateContactComponent;
	          let fixture: ComponentFixture<CreateContactComponent>;
          
	          beforeEach(async () => {
		          await TestBed.configureTestingModule({
			          declarations: [CreateContactComponent],
			          imports: [
				          CoreTestingModule.withConfig(),
				          ReactiveFormsModule,
		          
			          ],
			          providers: [
				          {
					          provider: ClientService,
					          useValue: {
						          getList: () => list$
					          }
				          },
				          {
					          provider: ContactService,
					          useValue: {
						          create: () => contact$
					          }
				          }
			          ]
		          }).compileComponents();
	          });
          
	          beforeEach(() => {
		          fixture = TestBed.createComponent(CreateContactComponent);
		          component = fixture.componentInstance;
		          fixture.detectChanges();
	          });
          
	          it('should create', () => {
		          expect(component).toBeTruthy();
	          });
          });

**Comment by mmblc** [comment]
I'm also having this issue with a similar test file. Walking through the code, it looks like the internal store has no state value and the mapToApiUrl function is accessing a null value. 

Is something supposed to be passed to .withConfig() to make this work? I tried passing my environment file and it has the same issue. The documentation is not clear on this.

**Comment by mahmut-gundogdu** [comment]
Hi .  I saw some missing mock-service in angular.  We have talked with the Angular team and we will handle the issues in 5.3. For a now I have created an example that works with the current version. You can check this  https://gist.github.com/mahmut-gundogdu/d300cedc226992bd5410f85265fd386d

here you can check the status of fix https://github.com/abpframework/abp/issues/12844
