### ISSUE TITLE
`abp bundle` command not working 

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#10640]
Version: `5.0.0-rc.1` or `5.0.0-beta.**`

Error message: 
```
[09:27:11 ERR] Not found: _content/Volo.Abp.AspNetCore.Components.WebAssembly.Theming/libs/bootstrap/css/bootstrap.min.css
Volo.Abp.AbpException: Not found: _content/Volo.Abp.AspNetCore.Components.WebAssembly.Theming/libs/bootstrap/css/bootstrap.min.css
   at Volo.Abp.Cli.Bundling.BundlerBase.BundleFiles(BundleOptions options, List`1 bundleDefinitions) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlerBase.cs:line 91
   at Volo.Abp.Cli.Bundling.BundlerBase.Bundle(BundleOptions options, BundleContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlerBase.cs:line 38
   at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 84
   at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 43
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 161
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 69
```

**My steps**
1. `abp new Blazr56dsf -t app --mobile none --database-provider mongodb -u blazor -csf --preview` 
2. `cd **/**.Blazor`
3. `abp bundle -f`

**Comment by EngincanV** [comment]
I've encountered the same error. After I run the `dotnet build /graphBuild` command on my root directory and then run the `abp bundle` command again on the Blazor project directory, it's bundled successfully.

**Comment by maliming** [comment]
Yes, You have to build the project before run `abp bundle` command.

**Comment by berkansasmaz** [comment]
Ok, but still not working for me. I already tried the build, we even tried it with @EngincanV, but it still didn't work for me.

Maybe it's due to the operating system, I don't know, if ping comes from users, we will reopen the issue. By the way, the `-f` flag already gets build first, also, it says you need to get build first when you just run `bundle` command without getting build anyway.

**Comment by cotur** [comment]
@berkansasmaz be careful about the bootstrap packages. 

I had same error then I recognized I forgot to upgrade my boostrap5 related blazor nuget packages.

**Comment by mehmetuken** [comment]
abp new Test.Project -t app -u blazor -dbms PostgreSQL
cd src/Test.Project.Blazor
abp bundle -f


```
[13:52:16 ERR] Not found: _content/Volo.Abp.AspNetCore.Components.WebAssembly.Theming/libs/bootstrap/css/bootstrap.min.css
Volo.Abp.AbpException: Not found: _content/Volo.Abp.AspNetCore.Components.WebAssembly.Theming/libs/bootstrap/css/bootstrap.min.css
```

**Comment by berkansasmaz** [comment]
Hi @mehmetuken, maybe this bug is OS-specific. Could you please write which operating system you are using?

**Comment by mehmetuken** [comment]
Hi @berkansasmaz, my os is macOS Monterey.

**Comment by berkansasmaz** [comment]
Thank you for your answer. I am using the same OS so I think the error is OS-specific.

I will deal with this issue.
