### ISSUE TITLE
BlobContainer MIN.IO error when try to download

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10788]
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

On my solution I use BlobContainer to store documents on a MIN.IO server.

I am still able to upload and delete files on the server, however it doesn't work when I try to upload, it was working well on version 4.4.3.

For information, if I put a path which do not exists, I get null returned, so no error.

`var tmp = await _blobContainer.GetOrNullAsync(myPath);`

I get this message:

System.NotSupportedException: ' The ReadAsync method cannot be called when another read operation is pending.'

With details:
```
System.NotSupportedException
  HResult=0x80131515
  Message= The ReadAsync method cannot be called when another read operation is pending.
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__186`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnection.<FillAsync>d__97.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<CopyToContentLengthAsync>d__107.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.<CompleteCopyToAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Volo.Abp.BlobStoring.BlobProviderBase.<TryCopyToMemoryStreamAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.BlobStoring.Minio.MinioBlobProvider.<GetOrNullAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.BlobStoring.BlobContainer.<GetOrNullAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kwork.StaffApp.FileManagement.FileManagementAppService.<DownloadStaffFileAsync>d__9.MoveNext() in D:\Source\App5RC\aspnet-core\src\******App.Application\FileManagement\FileManagementAppService.cs:line 138
```

**Comment by JadynWong** [comment]
Hi @cbaille ,can you replace `MinioBlobProvider.cs` with #10727. 

```csharp
[Dependency(ServiceLifetime.Transient, ReplaceServices = true)]
[ExposeServices(typeof(MinioBlobProvider), typeof(IBlobProvider))]
public class FixMinioBlobProvider: MinioBlobProvider
{
        public FixMinioBlobProvider(
            IMinioBlobNameCalculator minioBlobNameCalculator,
            IBlobNormalizeNamingService blobNormalizeNamingService)
            : base(minioBlobNameCalculator, blobNormalizeNamingService)
        {
        }
        
        public override async Task<Stream> GetOrNullAsync(BlobProviderGetArgs args)
        {
            var blobName = MinioBlobNameCalculator.Calculate(args);
            var client = GetMinioClient(args);
            var containerName = GetContainerName(args);

            if (!await BlobExistsAsync(client, containerName, blobName))
            {
                return null;
            }

            var memoryStream = new MemoryStream();
            await client.GetObjectAsync(containerName, blobName, (stream) =>
            {
                if (stream != null)
                {
                    stream.CopyTo(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);
                }
                else
                {
                    memoryStream = null;
                }
            });

            return memoryStream;
        }
}

```

**Comment by cbaille** [comment]
I added the source of the abp dev branch framework instead of the package for "Volo.Abp.BlobStoring.Minio" and it works now.

Thanks
