### ISSUE TITLE
Can’t get dotnet ef update database to work on Mac 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1083]
The error reports that appsettings.json is missing

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by vnetonline** [comment]
1. Create Template at abp.io 
2. Open Terminal  
3. Navigate to _YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations folder
4 Run the command "dotnet ef database update" and you shall see the below error



_YourUserName_-MBP:_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations _YourUserName_$ dotnet ef database update
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/Users/_YourUserName_/Development/_YourCompanyName_/Projects/_YourProjectName_/src/_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations/appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at _YourCompanyName.YourProjectName_.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.BuildConfiguration() in /Users/_YourUserName_/Development/_YourCompanyName_/Projects/_YourProjectName_/src/_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/SoftwareMigrationsDbContextFactory.cs:line 26
   at _YourCompanyName.YourProjectName_.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.CreateDbContext(String[] args) in /Users/_YourUserName_/Development/_YourCompanyName_/Projects/_YourProjectName_/src/_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/SoftwareMigrationsDbContextFactory.cs:line 12
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/Users/_YourUserName_/Development/_YourCompanyName_/Projects/_YourProjectName_/src/_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations/appsettings.json'.
_YourUserName_-MBP:_YourCompanyName.YourProjectName_.EntityFrameworkCore.DbMigrations _YourUserName_

**Comment by maliming** [comment]
Please specify the startup project parameters.
```
dotnet ef database update -s ..\YourCompanyName.YourProjectName.Web\YourCompanyName.YourProjectName.Web.csproj
```

**Comment by vnetonline** [comment]
Okay very new to this command line stuff sorry for my ignorance

I am getting the below error now

YourUserName-MBP:YourCompanyName.YourProjectName.EntityFrameworkCore.DbMigrations YourUserName$ dotnet ef database update -s ..\YourCompanyName.YourProjectName.Web\YourCompanyName.YourProjectName.Web.csproj
MSBUILD : error MSB1009: Project file does not exist.
Switch: ..YourCompanyName.YourProjectNameYourCompanyName.YourProjectName.Web.csproj
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
YourUserName-MBP:YourCompanyName.YourProjectName.EntityFrameworkCore.DbMigrations YourUserName$ dotnet ef database update -s ..\YourCompanyName.YourProjectName.Web\YourCompanyName.YourProjectName.Web.csproj

**Comment by maliming** [comment]
**Project file does not exist.**

`dotnet ef database update -s ` Your web project path.

**Comment by vnetonline** [comment]
Thanks for you help maliming

wrong slashes correct command as follows

YourUserName-MBP:YourCompanyName.YourProjectName.EntityFrameworkCore.DbMigrations YourUserName$ dotnet ef database update -s ../YourCompanyName.YourProjectName.Web/YourCompanyName.YourProjectName.Web.csproj
Applying migration '20190402131334_Initial'.
Done.
YourUserName-MBP:YourCompanyName.YourProjectName.EntityFrameworkCore.DbMigrations YourUserName$
