### ISSUE TITLE
"entityObj should be an entity" when creating entities from third party libraries

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1086]
I am trying to integrate OpenIddict with my application but it fails to add entities on seed to the database as it conflicts with Abp's entity change listeners:

```
System.ArgumentException: 'entityObj should be an entity and implement the 'Volo.Abp.Domain.Entities.IEntity, Volo.Abp.Ddd.Domain, Version=0.16.0.0, Culture=neutral, PublicKeyToken=null' interface!'
   at Volo.Abp.Domain.Entities.Events.Distributed.EntityToEtoMapper.Map(Object entityObj) in D:\Github\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Events\Distributed\EntityToEtoMapper.cs:line 31
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.TriggerEntityCreatedEventOnUowCompletedAsync(Object entity) in D:\Github\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Events\EntityChangeEventHelper.cs:line 56
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.TriggerEntityChangeEvents(List`1 changedEntities) in D:\Github\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Events\EntityChangeEventHelper.cs:line 97
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.TriggerEventsInternalAsync(EntityChangeReport changeReport) in D:\Github\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Events\EntityChangeEventHelper.cs:line 85
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.TriggerEventsAsync(EntityChangeReport changeReport) in D:\Github\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Events\EntityChangeEventHelper.cs:line 39
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 139
   at OpenIddict.Core.OpenIddictApplicationManager`1.CreateAsync(TApplication application, String secret, CancellationToken cancellationToken)
   at OpenIddict.Core.OpenIddictApplicationManager`1.CreateAsync(OpenIddictApplicationDescriptor descriptor, CancellationToken cancellationToken)
   at XXXXX.XXXXXXX.OpenIddictDataSeeder.SeedAsync()
   at XXXXX.XXXXXXX.Host.AppModule.<>c__DisplayClass3_0.<<SeedDatabase>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at XXXXX.XXXXXX.Host.AppModule.SeedDatabase(ApplicationInitializationContext context)
```

Related code:

OpenIddictDataSeeder:
```cs
public async Task SeedAsync()
{
     if (await _openIddictApplicationManager.FindByClientIdAsync(OpenIddictClientId) == null)
     {
         var host = _configurationAccessor.Configuration["Host"];
         var descriptor = new OpenIddictApplicationDescriptor
         {
              ClientId = OpenIddictClientId,
              DisplayName = "displayname",
              PostLogoutRedirectUris = { new Uri($"{host}signout-oidc") },
              RedirectUris = { new Uri($"{host}signin-oidc") },
              Permissions =
              {
                  OpenIddictConstants.Permissions.Endpoints.Authorization,
                  OpenIddictConstants.Permissions.Endpoints.Token,
                  OpenIddictConstants.Permissions.GrantTypes.Implicit,
                  OpenIddictConstants.Permissions.GrantTypes.RefreshToken,
                  OpenIddictConstants.Permissions.Scopes.Email,
                  OpenIddictConstants.Permissions.Scopes.Profile,
                  OpenIddictConstants.Permissions.Scopes.Roles
              }
          };

          await _openIddictApplicationManager.CreateAsync(descriptor);
     }
}
```

DbContextModelCreatingExtensions:
```cs
public static void ConfigureXXXXX(this ModelBuilder builder)
{
     Check.NotNull(builder, nameof(builder));
     builder.UseOpenIddict();
     
     /* Configure other entities */
     ...
}
```

Note: the entity still gets created on database so this issue only occurs on first startup, after that, since the data got created, it won't cause the exception anymore.

**Comment by Trojaner** [comment]
Edit: This appears to be a duplicate of #1080 and appears to be fixed already by https://github.com/abpframework/abp/commit/6ba0ad6618e89f9f5c50cc4140d3f0b111abdd3a and https://github.com/abpframework/abp/commit/230821750b7c54d296652f2f9d962efa63791281
