### ISSUE TITLE
Startup Template (Tiered), .IdentityServer and .Web not working when hosted in Google Cloud Run using Docker Images

### ISSUE THREAD

**Issue by RoflLmao1** [abpframework/abp#10891]
Details:
* ABP Framework version: 4.4.4
* User Interface: MVC / Razor Pages
* Database Provider: EF Core
* Project Type: Application
* DBMS: MySQL

I created a sample solution using the '[Get Started](https://abp.io/get-started)' template provided, setup the MySQL database (by running '**.DbMigrator**' project) and the Redis database required, and then updated the appsettings.json files for '**.HttpApi.Host**', '**.IdentityServer**' and '**.Web**' projects.

When tested while running locally, everything works fine as expected:
* Swagger API works
* Identity server login works
* Web project able to login, logout, navigate and maintain data in default menus

Then, I started hosting the projects in Google Cloud Run by generating a Docker Image each from their respective build files that were built into the 'Release' folder, and then copied into the 'Release\publish' via the command `dotnet publish -c Release`. The commands in the Dockerfile is as follows (All are same except for the entrypoint):

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base

COPY bin/Release/net5.0/publish/ App/
WORKDIR /App
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "Sample.<HttpApi.Host/IdentityServer/Web>.dll"]
```

I added **Environment Variables** to the services to replace the respective _Connection Strings_ and _URLs_. The MySQL and Redis databases are also both hosted somewhere accessible to the Google Cloud Run services. The **'.DbMigrator'** project was also run to setup the tables and seed for the hosted MySQL database (values in appsettings.json are updated to point to the links of the hosted services).

The 3 projects were successfully hosted from the Docker images generated, and I proceeded to test them using the links provided. However, there were some issues in the services hosted using **'.IdentityServer**' and **'.Web**':

1. **.IdentityServer** - Login does not work. Whenever I login (using the default '**admin**' user), it will just redirect back to the main page without updating to the 'LoggedIn' state.
The **'AbpSecurityLogs**' shows a 'LoginSucceeded' action, meaning the login was successful, but the UI did not register the login.

2. **.Web** - The first page of the website loads, but when I tried to enter the '_/Account/Login_' link, it just throws an **HTTP 500** error by showing the following message:

> [500] Error!
> An internal error occurred during your request!

Is there anything I am missing here when performing the deployments, when generating the Docker Images, or some other steps?
Thanks in advance

**Comment by berkansasmaz** [comment]
If you haven't already, you can check [this article](https://blog.antosubash.com/posts/abp-deploy-with-docker).

**Comment by RoflLmao1** [comment]
Thanks for the link. I added the 'same site cookies' fix provided, and it seems to have solved the issue at the '**.IdentityServer**' project regarding the login.

However, the issue at the '**.Web** project still persists.

**Comment by berkansasmaz** [comment]
There could be many reasons for this. For example, if you do not set `ASPNETCORE_ENVIRONMENT` to `Production` after publishing the `*.Web` project, it will not work. 

Can you send the logs of the `*.Web` project so that I can diagnose it fully?

**Comment by RoflLmao1** [comment]
The setting for `ASPNETCORE_ENVIRONMENT` is currently set to `Production`. I tried setting it to `Development`, and the build can't even start up altogether.

May I know which environment variables to set to enable more detailed logging for the website for the ABP framework?

From my understanding, the '**/Account/Login**' page seems to be redirecting to the '**.Identity.Server**'s login page and then redirecting back once login is successful. It seems the hosted build have an issue on this portion whereby it failed to redirect due to some issues.

**Comment by berkansasmaz** [comment]
You can see the configurations related to `logging` in `Program.cs` in `MyProjectName.IdentityServer`, `MyProjectName.HttpApi.Host` and `MyProjectName.Web` projects.

On the other hand, I'm assuming you add the following two lines to the `MyProjectName.IdentityServer`, `MyProjectName.HttpApi.Host` and `MyProjectName.Web` projects.

```charp
context.Services.AddSameSiteCookiePolicy();
```
```charp
app.UseCookiePolicy();
```

If not, please add as mentioned in [this article](https://blog.antosubash.com/posts/abp-deploy-with-docker).

I don't know if you need to change the configurations related to the log, but you can find log records in `**/Logs` folder for each executable project.

It would be great if you could share the relevant `log` records and what happens to the `cookie` when it is redirected to the `MyProjectName.Web` project after login.

**Comment by RoflLmao1** [comment]
I modified the logs, and finally got the exception message showing up. It seems there is an issue with an address that seems to be getting the '**System.String**' type name of an internal variable/property/field instead of the value stored. Please do note that the following exception starts from the bottom to the top (due to the logs being exported in this style)

```
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
 ---> System.ArgumentException: IDX20108: The address specified 'System.String' is not valid as per HTTPS scheme. Please specify an https address for security reasons. If you want to test with http address, set the RequireHttps property  on IDocumentRetriever to false. (Parameter 'address')

```

There seems to be no more logs linked to this exception, as the other logs after this indicates a redirect to an Error controller. Is this suffice to know the cause of the issue?

Just an extra note, I did not set the Environment Variables for the following value, thus it would be using the default value shown below. Maybe this is the cause for the above?

**.IdentityServer**
- "RedirectAllowedUrls": "http://localhost:4200,https://localhost:44307"

**Comment by berkansasmaz** [comment]
I got it, thank you very much for the detailed explanations 😊

The problem does not seem to be related to ABP, I think you can solve it by looking [here](https://github.com/IdentityServer/IdentityServer4/issues/4645#issuecomment-656719245).

**Comment by RoflLmao1** [comment]
Thanks for that. The original issues pertaining to the login seems to be working now, but it is now failing due to another error.
When the POST request is sent to '**/signin-oidc**' of the **.Web** project, it seems to throw the following error:

```
Request starting HTTP/1.1 POST http://<domain>/signin-oidc application/x-www-form-urlencoded 1945
'.AspNetCore.Correlation.wEOJe_ht9t7z2MYUCbAWuDWAIqdoEbGDLhloRQEYsVs' cookie not found.
Error from RemoteAuthentication: Correlation failed..
An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
 --- End of inner exception stack trace ---
 at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
 at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

FYI, I tried setting up the exact same startup template, but this time without using the **Tiered** structure. After applying all the fixes above, the whole website seems to be working fine similar to how it behaved on localhost.
