### ISSUE TITLE
An error was reported passing a parameter of type ReferenceReadStream to ApplicationService

### ISSUE THREAD

**Issue by tianxin8206** [abpframework/abp#10963]
* Your **ABP Framework version**. 4.4.4
* Your database provider(EF Core/MongoDB) EFCore
* Exception message and **stack trace** if available (check the logs).
```
System.Reflection.TargetInvocationException: Property accessor 'ReadTimeout' on object 'Microsoft.AspNetCore.Http.ReferenceReadStream' threw the following exception:'Timeouts are not supported on this stream.'
 ---> System.InvalidOperationException: Timeouts are not supported on this stream.
   at System.IO.Stream.get_ReadTimeout()
   --- End of inner exception stack trace ---
   at System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component)
   at Volo.Abp.Validation.DataAnnotationObjectValidationContributor.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth)
   at Volo.Abp.Validation.DataAnnotationObjectValidationContributor.AddErrors(ObjectValidationContext context)
   at Volo.Abp.Validation.ObjectValidator.GetErrors(Object validatingObject, String name, Boolean allowNull)
   at Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(IAbpValidationResult context, ParameterInfo parameterInfo, Object parameterValue)
   at Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(MethodInvocationValidationContext context)
   at Volo.Abp.Validation.MethodInvocationValidator.Validate(MethodInvocationValidationContext context)
   at Volo.Abp.Validation.ValidationInterceptor.Validate(IAbpMethodInvocation invocation)
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
```
* Steps needed to **reproduce** the problem.
My code:
```C#
public class WpsController
{

	private readonly IWpsAppService _wpsService;

	public WpsController(IWpsAppService service)
	{
		_wpsService = service;
	}

	public async Task<IActionResult> FileSaveAsync([Required] IFormFile file)
	{
		var fileId = GetFileId();
		var saveResponse = await _wpsService.FileSaveAsync(fileId, file.OpenReadStream(), file.FileName, file.Length);
		return Ok(saveResponse);
	}
}

public class WpsAppService : ApplicationService, IWpsAppService
{
	public async Task<WpsSaveResponseDto> FileSaveAsync(Guid fileId, Stream fileStream, string fileName, long length)
	{
		var (url, version) = await _manager.SaveVersionAsync(fileId, fileStream, fileName, length);
		url = $"{_options.Obs.ObsUrl}{url.TrimStart('/')}";

		return new WpsSaveResponseDto(new WpsFile(fileId.ToString(), fileName, version, length, url));
	}
}
```

**Comment by maliming** [comment]
Please try to use `IRemoteStreamContent` to replace the `IFormFile ` and `fileStream`.
