### ISSUE TITLE
datatable.net-bs5 issue after migrating to abp v5.0 and .net 6.0

### ISSUE THREAD

**Issue by ammadislam1996** [abpframework/abp#10988]
Kindly help me resolve this issue. i have installed this package through nuget and npm but nothing worked. 

An exception was thrown attempting to execute the error handler.
Volo.Abp.AbpException: Could not find the bundle file '/libs/datatables.net-bs5/css/dataTables.bootstrap5.css' for the bundle 'Basic.Global'!
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Pages_Shared__Layout.<>c__DisplayClass13_0.<<ExecuteAsync>b__0>d.MoveNext() in E:\Work\FinancialsAe\FinancialsAce\src\FinancialsAce.Blazor.Server\Pages\Shared\_Layout.cshtml:line 45
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Pages_Shared__Layout.ExecuteAsync() in E:\Work\FinancialsAe\FinancialsAce\src\FinancialsAce.Blazor.Server\Pages\Shared\_Layout.cshtml:line 27
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

**Comment by ammadislam1996** [comment]
@bnymncoskuner sir kindly help

**Comment by iyilm4z** [comment]
Hi @ammadislam1996, could you please make sure the style file **dataTables.bootstrap5.css** exists at _/libs/datatables.net-bs5/css/dataTables.bootstrap5.css_ path?

**Comment by realLiangshiwei** [comment]
Try `abp install-libs`

https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-5-0-MVC.md#use-install-libs-by-default

**Comment by ammadislam1996** [comment]
> Hi @ammadislam1996, could you please make sure the style file **dataTables.bootstrap5.css** exists at _/libs/datatables.net-bs5/css/dataTables.bootstrap5.css_ path?

@iyilm4z no sir it has dataTable.bootstrap4.css

**Comment by EngincanV** [comment]
Hi @ammadislam1996, can you run the `abp install-libs` command as @realLiangshiwei mentioned. Then in your libs folder, **datatables.net-bs5** folder will be created.

**Comment by ammadislam1996** [comment]
@realLiangshiwei @EngincanV Thank you so much sir. That fixed the issue
