### ISSUE TITLE
settingProvider.GetAllAsync  

### ISSUE THREAD

**Issue by laosandegudai** [abpframework/abp#11042]
https://github.com/abpframework/abp/blob/7bab6b76560e573c2634ca7c22f73a957f6868f7/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManagementStore.cs#L124

`            var settings= await _settingProvider.GetAllAsync(new string[] { "key1","key2" });
`
### It would throw exception,as 

`System.ArgumentException: names can not be null or empty! (Parameter 'names')
   at Volo.Abp.Check.NotNullOrEmpty[T](ICollection`1 value, String parameterName)
   at Volo.Abp.SettingManagement.SettingManagementStore.GetListAsync(String[] names, String providerName, String providerKey)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Settings.SettingProvider.GetAllAsync(String[] names)`

### I looked at the code and saw the logic. Why check the parameters instead of just returning?

https://github.com/abpframework/abp/blob/7bab6b76560e573c2634ca7c22f73a957f6868f7/framework/src/Volo.Abp.Settings/Volo/Abp/Settings/SettingProvider.cs#L75

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by laosandegudai** [comment]
ABP Framework version:4.4.2 
But the latest version still has this problem
`var settings= await _settingProvider.GetAllAsync(new string[] { "key1","key2" });`
这两个设置在相同的ISettingValueProvider，两个设置保存一次，保存是为了让他们同时存在数据库，然后在获取的时候就会出现异常
`System.ArgumentException: names can not be null or empty! (Parameter 'names') at Volo.Abp.Check.NotNullOrEmpty[T](ICollection1 value, String parameterName)
at Volo.Abp.SettingManagement.SettingManagementStore.GetListAsync(String[] names, String providerName, String providerKey)
at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue1.ProceedAsync() at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func3 proceed) at Volo.Abp.Settings.SettingProvider.GetAllAsync(String[] names)`

出现这个异常的原因我认为是以下代码造成的，

https://github.com/abpframework/abp/blob/7bab6b76560e573c2634ca7c22f73a957f6868f7/framework/src/Volo.Abp.Settings/Volo/Abp/Settings/SettingProvider.cs#L75
![image](https://user-images.githubusercontent.com/17979159/147245659-a979a9f3-caa1-45dd-b4e8-cd71fb3e5545.png)
上图的代码会导致在获取到自己的设置数据后删除names，在遍历ISettingValueProvider时会导致后面的names为空集合，下面的代码会检查names然后抛出异常。



https://github.com/abpframework/abp/blob/7bab6b76560e573c2634ca7c22f73a957f6868f7/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManagementStore.cs#L124
