### ISSUE TITLE
Autofac.Core.DependencyResolutionException: Cannot resolve parameter...

### ISSUE THREAD

**Issue by afresh** [abpframework/abp#11236]
ABP Framework version: 5.0.1
Database provider: EF Core.

Error:
``` log
2022-01-08 15:38:01.321 +08:00 [INF] Request starting HTTP/2 GET https://localhost:44357/api/bills - -
2022-01-08 15:38:01.323 +08:00 [INF] Executing endpoint 'Yms.BillService.Bills.BillController.GetListAsync (Yms.BillService.HttpApi)'
2022-01-08 15:38:01.341 +08:00 [INF] Route matched with {area = "bill", action = "GetList", controller = "Bill", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[Yms.BillService.Bills.BillDto]] GetListAsync(Yms.BillService.Bills.GetBillsInput) on controller Yms.BillService.Bills.BillController (Yms.BillService.HttpApi).
2022-01-08 15:38:01.361 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {
    "ActivatorChain": "Yms.BillService.Bills.BillController"
  },
  "validationErrors": null
}

2022-01-08 15:38:01.362 +08:00 [ERR] An exception was thrown while activating Yms.BillService.Bills.BillController.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Yms.BillService.Bills.BillController.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Yms.BillService.Bills.BillController' can be invoked with the available services and parameters:
Cannot resolve parameter 'Yms.BillService.Bills.IBillAppService billAppService' of constructor 'Void .ctor(Yms.BillService.Bills.IBillAppService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-01-08 15:38:01.363 +08:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Yms.BillService.Bills.BillController

2022-01-08 15:38:01.374 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2022-01-08 15:38:01.377 +08:00 [INF] Executed action Yms.BillService.Bills.BillController.GetListAsync (Yms.BillService.HttpApi) in 36.0717ms
2022-01-08 15:38:01.377 +08:00 [INF] Executed endpoint 'Yms.BillService.Bills.BillController.GetListAsync (Yms.BillService.HttpApi)'
2022-01-08 15:38:01.377 +08:00 [INF] Request finished HTTP/2 GET https://localhost:44357/api/bills - - - 500 - application/json;+charset=utf-8 56.4738ms
```

`IBillAppService.cs`

``` CSharp
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace Yms.BillService.Bills
{
    public interface  IBillAppService: IApplicationService
    {
        Task<BillDto> GetAsync(string id);

        Task<PagedResultDto<BillDto>> GetListAsync(GetBillsInput input);

        Task<BillDto> CreateAsync(BillCreateDto input);

        Task<BillDto> UpdateAsync(string id, BillUpdateDto input);

        Task DeleteAsync(string id);
    }
}
```

`BillAppService.cs`

``` CSharp
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Users;
using Yms.BillService.Permissions;
using Yms.SchoolService.Schools;

namespace Yms.BillService.Bills
{
    [Authorize(BillServicePermissions.Bills.Default)]
    public class BillAppService : ApplicationService, IBillAppService
    {
        private readonly BillManager _billManager;
        private readonly IBillRepository BillRepository;
        private readonly ICurrentUser _currentUser;
        private readonly ISchoolAppService _schoolAppService;

        public BillAppService(BillManager billManager, IBillRepository billRepository, ICurrentUser currentUser, ISchoolAppService schoolAppService)
        {
            _billManager = billManager;
            BillRepository = billRepository;
            _currentUser = currentUser;
            _schoolAppService = schoolAppService;
        }

        public async Task<BillDto> GetAsync(string id)
        {
            return ObjectMapper.Map<Bill, BillDto>(
                await _billManager.GetAsync(id, _currentUser.TenantId)
            );
        }

        public async Task<PagedResultDto<BillDto>> GetListAsync(GetBillsInput input)
        {
            using (CurrentTenant.Change(_currentUser.TenantId))
            {
                var count = await BillRepository.GetCountAsync(input.Filter);
                var list = await BillRepository.GetListAsync(input.Sorting, input.MaxResultCount, input.SkipCount, input.Filter);

                return new PagedResultDto<BillDto>(
                    count,
                    ObjectMapper.Map<List<Bill>, List<BillDto>>(list)
                );
            }
        }

        [Authorize(BillServicePermissions.Bills.Create)]
        public async Task<BillDto> CreateAsync(BillCreateDto input)
        {
            var bill = new Bill(
                Bill.CreateBillId(),
                input.IdentityUserId,
                input.IdentityUserName,
                input.IdentityUserAvatar,
                input.TransactionTime,
                input.TransactionType,
                input.BusinessType,
                input.TransactionWay,
                input.TransactionAmount,
                input.BalanceBeforeTransaction,
                input.BalanceAfterTransaction,
                input.LinkOrderNo,
                input.LinkDeviceNo,
                input.OuterId,
                CurrentTenant.Id
            );

            var schoolDto = await _schoolAppService.GetByCodeAsync(input.SchoolCode);
            if (schoolDto == null)
            {
                throw new BusinessException(BillServiceErrorCodes.SchoolCodeIsWrong);
            }

            await _billManager.CreateAsync(bill, input.SchoolCode, schoolDto.Name);

            return ObjectMapper.Map<Bill, BillDto>(bill);
        }

        [Authorize(BillServicePermissions.Bills.Update)]
        public async Task<BillDto> UpdateAsync(string id, BillUpdateDto input)
        {
            throw new NotImplementedException();
        }

        [Authorize(BillServicePermissions.Bills.Delete)]
        public async Task DeleteAsync(string id)
        {
            throw new NotImplementedException();
        }
    }
}
```

`BillController.cs`

``` CSharp
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace Yms.BillService.Bills
{
    [Area(BillServiceRemoteServiceConsts.ModuleName)]
    [RemoteService(Name = BillServiceRemoteServiceConsts.RemoteServiceName)]
    [Route("api/bills")]
    public class BillController : BillServiceController, IBillAppService
    {
        private readonly IBillAppService _billAppService;

        public BillController(IBillAppService billAppService)
        {
            _billAppService = billAppService;
        }

        [HttpGet]
        [Route("")]
        public Task<PagedResultDto<BillDto>> GetListAsync(GetBillsInput input)
        {
            return _billAppService.GetListAsync(input);
        }

        [HttpGet]
        [Route("{id}")]
        public Task<BillDto> GetAsync(string id)
        {
            return _billAppService.GetAsync(id);
        }

        [HttpPost]
        public Task<BillDto> CreateAsync(BillCreateDto input)
        {
            return _billAppService.CreateAsync(input);
        }

        [HttpPut]
        [Route("{id}")]
        public Task<BillDto> UpdateAsync(string id, BillUpdateDto input)
        {
            return _billAppService.UpdateAsync(id, input);
        }

        [HttpDelete]
        public Task DeleteAsync(string id)
        {
            return _billAppService.DeleteAsync(id);
        }
    }
}
```

`BillServiceController.cs`

``` CSharp
using Yms.BillService.Localization;
using Volo.Abp.AspNetCore.Mvc;

namespace Yms.BillService
{
    public abstract class BillServiceController : AbpControllerBase
    {
        protected BillServiceController()
        {
            LocalizationResource = typeof(BillServiceResource);
        }
    }
}
```

`BillServiceHttpApiModule.cs`

``` CSharp
using Localization.Resources.AbpUi;
using Microsoft.Extensions.DependencyInjection;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Localization;
using Volo.Abp.Modularity;
using Yms.BillService.Localization;

namespace Yms.BillService
{
    [DependsOn(
        typeof(BillServiceApplicationContractsModule),
        typeof(AbpAspNetCoreMvcModule))]
    public class BillServiceHttpApiModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IMvcBuilder>(mvcBuilder =>
            {
                mvcBuilder.AddApplicationPartIfNotExists(typeof(BillServiceHttpApiModule).Assembly);
            });
        }

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpLocalizationOptions>(options =>
            {
                options.Resources
                    .Get<BillServiceResource>()
                    .AddBaseTypes(typeof(AbpUiResource));
            });
        }
    }
}
```

**What else is missing?**

**Comment by maliming** [comment]
Are you using the TIERED project?

**Comment by afresh** [comment]
> Are you using the TIERED project?

@maliming Hi, I don't know about the TIERED projects. This project is based on the `eShopOnAbp`.

**Comment by maliming** [comment]
Check your HttpApiClient module.

**Comment by afresh** [comment]
@maliming What exactly should I check?

`BillServiceHttpApiClientModule.cs`

``` CSharp
using Microsoft.Extensions.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Modularity;
using Volo.Abp.VirtualFileSystem;

namespace Yms.BillService
{
    [DependsOn(
        typeof(BillServiceApplicationContractsModule),
        typeof(AbpHttpClientModule))]
    public class BillServiceHttpApiClientModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddHttpClientProxies(
                typeof(BillServiceApplicationContractsModule).Assembly,
                BillServiceRemoteServiceConsts.RemoteServiceName
            );

            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<BillServiceHttpApiClientModule>();
            });

        }
    }
}
```

**Comment by afresh** [comment]
Or `SchoolServiceHttpApiClientModule.cs` ?

``` CSharp
using Microsoft.Extensions.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Modularity;
using Volo.Abp.VirtualFileSystem;

namespace Yms.SchoolService
{
    [DependsOn(
        typeof(SchoolServiceApplicationContractsModule),
        typeof(AbpHttpClientModule))]
    public class SchoolServiceHttpApiClientModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddHttpClientProxies(
                typeof(SchoolServiceApplicationContractsModule).Assembly,
                SchoolServiceRemoteServiceConsts.RemoteServiceName
            );

            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<SchoolServiceHttpApiClientModule>();
            });

        }
    }
}
```

**Comment by afresh** [comment]
Thanks @maliming ! I found the reason.

``` CSharp
    [DependsOn(
        typeof(YmsSharedHostingMicroservicesModule),
        typeof(YmsSharedHostingGatewaysModule),
        //typeof(BillServiceApplicationContractsModule), //--
        typeof(BillServiceApplicationModule), //++
        typeof(BillServiceEntityFrameworkCoreModule),
        typeof(BillServiceHttpApiModule),
        typeof(AbpHttpClientIdentityModelModule)
    )]
    public class BillServiceHttpApiHostModule : AbpModule
    {

    }
```
