### ISSUE TITLE
System.NullReferenceException while C # Static Client Proxy Generation

### ISSUE THREAD

**Issue by riccardodangelo** [abpframework/abp#11279]
ABP Version 5.0.1
Volo.abp.cli 5.0, 5.0.1
MVC UI
EF Core

STACK EXCEPTION
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateClientProxyGeneratedFileAsync(GenerateProxyArgs args, ControllerApiDescriptionModel controllerApiDescription, String clientProxyName, String appServiceTypeName, String appServiceTypeFullName, String rootNamespace, String folder) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerator.cs:line 177
   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateClientProxyFileAsync(GenerateProxyArgs args, ControllerApiDescriptionModel controllerApiDescription) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerato   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateProxyAsync(GenerateProxyArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerator.cs:line 86

If I run the command: `abp generate-proxy -t js -m identity -u https://localhost:44344` all works fine and the command generates the JS scripts:
![image](https://user-images.githubusercontent.com/90219053/149018235-e1d37d43-5f67-4990-8ba9-d53f8cb4d6f2.png)

If I run the c# syntax ( `abp generate-proxy --type csharp  --url https://localhost:44344`) the previous exception appens and will generate only a parzial class:
![image](https://user-images.githubusercontent.com/90219053/149018758-5b43d386-f0d8-4957-8614-05d26fe295b1.png)

The same appens even with Identity module.

My project was upgraded from 4.4 version

**Comment by realLiangshiwei** [comment]
Can you share a project to reproduce?

**Comment by riccardodangelo** [comment]
Do you mean the service project? The client side project could be any, right? In this case, I'll try with an empty project in which I'll try to generate a static proxy. If I'll reproduce the issue I'll put the service project online and I'll try to reproduce and share it.

**Comment by realLiangshiwei** [comment]
Ok, thanks.

**Comment by riccardodangelo** [comment]
I created an empty test client project and updated to abp.cli 5.1. I get the same exception (CSharpServiceProxyGenerator.cs:line 177 instead of 175 see below).
Next I ran the command to another service project. And all worked. So, the problem is in my service project.
If you agree, I'll share it ASAP on github.

**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.0.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
PS C:\Users\ric\source\repos\ClientProxTest\src\ClientProxTest.HttpApi.Client> abp generate-proxy --type csharp --url https://localhost:44344
[10:15:07 INF] ABP CLI (https://abp.io)
[10:15:08 INF] Version 5.1.0 (Stable)
[10:15:09 INF] Create ClientProxies\ZoneClientProxy.cs
[10:15:09 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateClientProxyGeneratedFileAsync(GenerateProxyArgs args, ControllerApiDescriptionModel controllerApiDescription, String clientProxyName, String appServiceTypeName, String appServiceTypeFullName, String rootNamespace, String folder) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerator.cs:line 175
   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateClientProxyFileAsync(GenerateProxyArgs args, ControllerApiDescriptionModel controllerApiDescription) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerator.cs:line 143
   at Volo.Abp.Cli.ServiceProxying.CSharp.CSharpServiceProxyGenerator.GenerateProxyAsync(GenerateProxyArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ServiceProxying\CSharp\CSharpServiceProxyGenerator.cs:line 84
   at Volo.Abp.Cli.Commands.ProxyCommandBase`1.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\work   at Volo.Abp.Cli.Commands.ProxyCommandBase`   at Volo.Abp.Cli.Commands.ProxyCommandBase`1.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\ProxyCommandBase.cs:line 56
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 161
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 69

**Comment by realLiangshiwei** [comment]
ok, please.

**Comment by riccardodangelo** [comment]
https://github.com/riccardodangelo/testforclientproxy.git

**Comment by realLiangshiwei** [comment]
Hi,

https://github.com/riccardodangelo/testforclientproxy/blob/master/src/Edisonweb.Mooveland.Web/Edisonweb.Mooveland.Web.csproj

You need to make sure your project upgrade to ABP 5.0

**Comment by riccardodangelo** [comment]
You are right. Solved!! 
Static Client Proxy Generation is a new feature starting from ABP 5, so we need to have the same ABP version for either client proxy side and service project. 
Thanks a Lot!
