### ISSUE TITLE
System.Security.Cryptography.CryptographicException: The key contents do not contain a PEM, the content is malformed, or the key does not match the certificate

### ISSUE THREAD

**Issue by theiosdevguy** [abpframework/abp#11336]
Hello ABP Team,

After upgrading from 5.0.0-beta3 to 5.1.1 , I started getting below error when executing `dotnet ef database update`

> The key contents do not contain a PEM, the content is malformed, or the key does not match the certificate.

Full error trace below:

```
Build started...
Build succeeded.
System.Security.Cryptography.CryptographicException: The key contents do not contain a PEM, the content is malformed, or the key does not match the certificate.
   at System.Security.Cryptography.X509Certificates.X509Certificate2.ExtractKeyFromPem[TAlg](ReadOnlySpan`1 keyPem, String[] labels, Func`1 factory, Func`2 import)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile(String certPemFilePath, String keyPemFilePath)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|193_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.UnpooledConnectorSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

It runs fine with 5.0.0-beta3.

Same error occurs with sample project downloaded from https://abp.io/get-started

Please suggest. Thanks.

**Comment by maliming** [comment]
What is the connection string?

**Comment by theiosdevguy** [comment]
> What is the connection string?

```
  "ConnectionStrings": {
    "Default": "Host=localhost;Port=5432;Database=mydatabase;User ID=username;Password=password;"
  },
```

**Comment by maliming** [comment]
I think it has something to do with your environment.

**Comment by theiosdevguy** [comment]
> I think it has something to do with your environment.

Ok. Just an FYI, I tried using a RDS instance connection string too and I had same results. What surprises is that if I downgrade ABP to 5.0.0-beta3 which uses npgsql 6.0.0-rc1, it starts to work again.

Any suggestions which environment config could cause this?

**Comment by EngincanV** [comment]
Your problem can be caused because of SSL Mode. The default SSL mode in v6.0+ is `Prefer`.
> Prefer mode:  I don't care about encryption, but I wish to pay the overhead of encryption if the server supports it.
https://www.npgsql.org/doc/security.html#encryption-ssltls

You can try to set SSL Mode as `Disable`, the default mode prior to v6.0 was **Disable**.
