### ISSUE TITLE
How to use repository in my custom blazor page

### ISSUE THREAD

**Issue by shawn-show** [abpframework/abp#11423]
I build an abp vnext blazor server project.
Now I want to create a user-defined page, and I couldn't connect to the DB with repository. That's my code.
WarehouseOperation.razor

``` csharp
@page "/PDA/WarehouseOperation"
@using TSTM.AGV
 
@inject AGVPointService _pointService
<MudGrid Class="ma-3">
    <MudItem xs="12">
        <MudTabs @bind-ActivePanelIndex="_activePanelIndex">
            <MudTabPanel Text="送到产线">
                <MudTextField T="string" @bind-Value="_pointCode" OnKeyPress="KeyPress"></MudTextField>
            </MudTabPanel>
            <MudTabPanel Text="Tab Two">
                <MudText>Content Two</MudText>
            </MudTabPanel>
            <MudTabPanel Text="Tab Three">
                <MudText>Content Three</MudText>
            </MudTabPanel>
            <MudTabPanel Text="Tab Disabled" Disabled="true">
                <MudText>Content Disabled</MudText>
            </MudTabPanel>
        </MudTabs>
    </MudItem>
</MudGrid>
```
WarehouseOperation.razor.cs
```csharp
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using System;
using System.Threading.Tasks;
using TSTM.AGV;
using Volo.Abp.Domain.Repositories;

namespace TSTM.Blazor.PDA
{
    public partial class WarehouseOperation
    {
        private string _pointCode;
        private int _activePanelIndex;
        [Inject]
        private ISnackbar _snackbar { get; set; }
        [Inject]
        private IRepository<AGVPoint, Guid> _repository { get; set; }
        public async Task KeyPress(KeyboardEventArgs eventArgs)
        {
            if (eventArgs.Key == "Enter")
            {
                var pointAG = await _repository.FirstOrDefaultAsync(p => p.Code == _pointCode);
                if (pointAG == null)
                {
                    _snackbar.Add("Error", Severity.Error);
                }
            }
        }
    }
}
```
and the expection is 
```
[13:13:18 ERR] Unhandled exception in circuit 'CSzOOWosK-34a-4-Mg-ATyNm_up4AqBAcsQgD37hIec'.
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'TSTMDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Volo.Abp.EntityFrameworkCore.EfCoreAsyncQueryableProvider.CanExecute[T](IQueryable`1 queryable)
   at Volo.Abp.Linq.AsyncQueryableExecuter.<>c__DisplayClass4_0`1.<FindProvider>b__0(IAsyncQueryableProvider p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Volo.Abp.Linq.AsyncQueryableExecuter.FindProvider[T](IQueryable`1 queryable)
   at Volo.Abp.Linq.AsyncQueryableExecuter.FirstOrDefaultAsync[T](IQueryable`1 queryable, Expression`1 predicate, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.RepositoryAsyncExtensions.FirstOrDefaultAsync[T](IReadOnlyRepository`1 repository, Expression`1 predicate, CancellationToken cancellationToken)
   at TSTM.Blazor.PDA.WarehouseOperation.KeyPress(KeyboardEventArgs eventArgs) in C:\Project\ZSIS\agv\zsis_agv_plant1_tstm\src\TSTM.Blazor\PDA\WarehouseOperation.razor.cs:line 23
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.TaskExtensions.AndForget(Task task)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

**Comment by maliming** [comment]
Try to begin a unit of work.

```cs
using (var uow = _unitOfWorkManager.Begin())
{
    var pointAG = await _repository.FirstOrDefaultAsync(p => p.Code == _pointCode);
    if (pointAG == null)
    {
        _snackbar.Add("Error", Severity.Error);
    }
    await uow.CompleteAsync();
}
```

**Comment by shawn-show** [comment]
Amazing it work! Thank you very much!
