### ISSUE TITLE
Cant seed data of entity with pre-defined events and eto mapping

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#11480]
* Your **ABP Framework version**: 5.1.2
* Your database provider: EF Core

If you try to seed data for entities that are active in AbpDistributedEntityEventOptions ( with automatic published events ) and have an EtoMapping it throw the following exception: AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.
```
Mapping types:
Object -> DefinitionEto
System.Object -> ***.DataSystem.Definition.DefinitionEto
   at lambda_method2159(Closure , Object , DefinitionEto , ResolutionContext )
   at Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider.Map[TSource,TDestination](Object source)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.AutoMap[TSource,TDestination](Object source)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.Map[TSource,TDestination](TSource source)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Volo.Abp.ObjectMapping.ObjectMapperExtensions.Map(IObjectMapper objectMapper, Type sourceType, Type destinationType, Object source)
   at Volo.Abp.Domain.Entities.Events.Distributed.EntityToEtoMapper.Map(Object entityObj)
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.PublishEntityCreatedEvent(Object entity)
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.PublishEventsForTrackedEntity(EntityEntry entry)
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ChangeTracker_Tracked(Object sender, EntityTrackedEventArgs e)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.OnTracked(InternalEntityEntry internalEntityEntry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.FireStateChanged(EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 node, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraphAsync(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRangeAsync(IEnumerable`1 entities, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.InsertManyAsync(IEnumerable`1 entities, Boolean autoSave, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at ***.DataSystem.Definition.DefinitionSeeder.SeedAsync(DataSeedContext context) in ***.Domain\DataSystem\Definition\DefinitionSeeder.cs:line 66
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at ***.Data.DbMigrationService.SeedDataAsync(Tenant tenant) in ***.Domain\Data\DbMigrationService.cs:line 103
   at ***.Data.DbMigrationService.MigrateAsync() in ***.Domain\Data\DbMigrationService.cs:line 53
   at ***.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in ***.DbMigrator\DbMigratorHostedService.cs:line 33
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ***.DbMigrator.Program.Main(String[] args) in ***.DbMigrator\Program.cs:line 30
   at ***.DbMigrator.Program.<Main>(String[] args)
```

configuration in DomainModule:
```
Configure<AbpDistributedEntityEventOptions>( options =>
{
      options.AutoEventSelectors.Add<DataDefinition>();
      options.EtoMappings.Add<DataDefinition, DefinitionEto>();
      [...]
}
```

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/151272041-f74fc19e-2609-40a8-8b34-4437ba6a9339.png)

**Comment by puschie286** [comment]
@maliming

thanks - it works with the AutoMap attribute

looks like the following conditions have to be met:
* Is not added to EtoMapping
* Eto have to inhert EntityEto
