### ISSUE TITLE
Remote HTTP Request: Failed to fetch 

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#11550]
Hi, I´m getting this error very periodically here and there and the only thing I need to do is to navigate from the page and come back to it. I started noticing this first sometime after 5.0 but I thought it was just connected to local development and me running VS 2022 latest preview 

Now I´m thinking that this is connected somehow to dynamic proxies and am wondering if this might be fixed with using the new [Static Proxies](https://blog.abp.io/abp/ABP-IO-Platform-5.0-RC-1-Has-Been-Released)? 

Or is this something completely unrelated?

![image](https://user-images.githubusercontent.com/2386572/153183627-15486497-5fa3-4685-b30b-7819e062d84e.png)

* Your **ABP Framework version**. 5.13
* Your **User Interface** Blazor WASM
* Your database provider: EF Core

**Comment by realLiangshiwei** [comment]
Hi,

Please discuss it here: https://support.abp.io/QA/Questions/2209/Bugs--Issues-v5X. PS: please provide steps to reproduce.

**Comment by sturlath** [comment]
Just added it [https://support.abp.io/QA/Questions/2209/Bugs--Issues-v5X#answer-5d16e131-cb98-199d-0ed8-3a01f4fe9f47](https://support.abp.io/QA/Questions/2209/Bugs--Issues-v5X#answer-5d16e131-cb98-199d-0ed8-3a01f4fe9f47) there also.

And sorry I can´t replicate this atm but I will try to gather more information on this next time it happens and update the questions.

**Comment by MichalCadecky** [comment]
I can confirm this. It is also happening to us as well. No real steps to reproduce, seems very random. Same version, same configuration (Blazor WASM). Sometimes page refresh works, sometimes it does not.

I have a feeling this might be connected to other problem we have with previous version 4 - we are getting almost everytime and error while trying to fetch the `blazor.boot.json`. Same thing, I was not able to investigate the cause.

**Comment by sturlath** [comment]
I got this again and now I managed to get some extra information and screenshots.
This was locally but has happened on my Azure testing environment. 
Visual Studio was running and debugger attached but I could not F5 anything without getting errors so just totally broken, just like on Azure when that happened.

```
global.js?_v=637728566081963529:10 
        
       System.AggregateException: One or more errors occurred. (An error occurred during the ABP remote HTTP request. (TypeError: Failed to fetch) See the inner exception for details.)
 ---> Volo.Abp.Http.Client.AbpRemoteCallException: An error occurred during the ABP remote HTTP request. (TypeError: Failed to fetch) See the inner exception for details.
 ---> System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> System.Runtime.InteropServices.JavaScript.JSException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Components.Web.AbpBlazorClientHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Components.Web.AbpBlazorClientHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__32[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   --- End of inner exception stack trace ---
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__32[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__31`1[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__29`1[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies.AbpApplicationConfigurationClientProxy.GetAsync()
   at Volo.Abp.AspNetCore.Components.WebAssembly.WebAssemblyCachedApplicationConfigurationClient.InitializeAsync()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.AbpWebAssemblyHostBuilderExtensions.InitializeModulesAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.AbpWebAssemblyHostBuilderExtensions.InitializeApplicationAsync(IAbpApplicationWithExternalServiceProvider application, IServiceProvider serviceProvider)
   at BSR.Beinni.Blazor.Program.Main(String[] args) in C:\Dev\IBeinni\aspnet-core\src\BSR.Beinni.Blazor\Program.cs:line 28
   --- End of inner exception stack trace ---
```

![image](https://user-images.githubusercontent.com/2386572/154796522-1cf5e977-1f84-43cd-9c5e-05a79184b4cf.png)
![image](https://user-images.githubusercontent.com/2386572/154796616-b5b56017-ac5d-4df3-8ca4-faac8286317b.png)

The paths there are 
https://localhost:44307/_framework/aspnetcore-browser-refresh.js
https://localhost:44353/api/abp/application-configuration?api-version=1.0
https://localhost:44307/global.js?_v=637728566081963529

**Comment by sturlath** [comment]
@realLiangshiwei I figured out what this is!

If you log into **two** browser tabs and **log out from one** and then try to execute some database action in the other you get this error.

Shouldn´t you just be redirected to the login page and asked to login again?

**Comment by realLiangshiwei** [comment]
Hi @sturlath 
Thanks for the information, I will check it.

**Comment by realLiangshiwei** [comment]
I think there is no problem:

![image](https://user-images.githubusercontent.com/16813853/165051468-ae4575f7-2ff9-4388-8798-bb4cb06b5c8b.png)

**Comment by sturlath** [comment]
OK I see that I get Unauthorized and then directly Failed to fetch but then the debugger seems to have lost its connection to VS. But this can happen even when the debugger is connected. I'll keep an eye out and report back if I find out anything more.

**Comment by omer-repo** [comment]
I have this problem only in web server. The method is working in local, but give this error on Windows Server IIS. Is there any news about this issue?

Edit: I had found my reason and it will be good to write reason here. 
https://www.ryadel.com/en/error-405-methods-not-allowed-asp-net-core-put-delete-requests/
It was occuring only in update and delete requests. So I think my reason is different from Sturla's case.
