### ISSUE TITLE
Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by ydemir** [abpframework/abp#11570]
I keep getting this Autofac.Core.DependencyResolutionException with new modules. I don't know what I am doing wrong. Below is my stack trace-:

[12:59:46 ERR] An exception was thrown while activating Castle.Proxies.FaturaAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.FaturaAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.FaturaAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'KarayYazilim.OnMuhasebe.Faturalar.IFaturaRepository faturaRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], KarayYazilim.OnMuhasebe.Faturalar.IFaturaRepository, KarayYazilim.OnMuhasebe.Faturalar.FaturaManager, KarayYazilim.OnMuhasebe.Faturalar.FaturaHareketManager)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass35_0.<OnPreparing>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CoreEventMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[12:59:46 ERR] ---------- Exception Data ----------
ActivatorChain = Castle.Proxies.FaturaAppServiceProxy

[12:59:46 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[12:59:46 INF] Executed action KarayYazilim.OnMuhasebe.Faturalar.FaturaAppService.CreateAsync (KarayYazilim.OnMuhasebe.Application) in 78.3591ms
[12:59:46 INF] Executed endpoint 'KarayYazilim.OnMuhasebe.Faturalar.FaturaAppService.CreateAsync (KarayYazilim.OnMuhasebe.Application)'
[12:59:46 INF] Request finished HTTP/2 POST https://localhost:44313/api/app/fatura application/json 1062 - 500 - application/json;+charset=utf-8 101.7553ms

AppService

```
public class FaturaAppService : OnMuhasebeAppService, IFaturaAppService
{
    private readonly IFaturaRepository _faturaRepository;
    private readonly FaturaManager _faturaManager;
    private readonly FaturaHareketManager _faturaHareketManager;

    public FaturaAppService(IFaturaRepository faturaRepository, FaturaManager faturaManager,
        FaturaHareketManager faturaHareketManager)
    {
        _faturaRepository = faturaRepository;
        _faturaManager = faturaManager;
        _faturaHareketManager = faturaHareketManager;
    }
```

Interface 

```
public interface IFaturaAppService:ICrudAppService<SelectFaturaDto,ListFaturaDto,FaturaListParameterDto,CreateFaturaDto,UpdateFaturaDto,FaturaNoParameterDto>
{
}
```

**Comment by realLiangshiwei** [comment]
`Cannot resolve parameter 'KarayYazilim.OnMuhasebe.Faturalar.IFaturaRepository faturaRepository' of constructor`

It seems, can't resolve IFaturaRepository, you should check your code and also check the document: https://docs.abp.io/en/abp/latest/Dependency-Injection

**Comment by ydemir** [comment]
@realLiangshiwei 

[Exception picture](https://www.hizliresim.com/am0ad70)

You see in the picture above. I was getting this error because I didn't add the IFaturaRepository interface to the related class. How do I find this, it is very difficult to find this error.

i solved this problem. thanks.
