### ISSUE TITLE
demo authserver.host 500

### ISSUE THREAD

**Issue by 312977** [abpframework/abp#11589]
when startup  authserver.host  :  the page show  500 error

the log is:      **Could not find the bundle file '/libs/bootstrap/js/bootstrap.enable.tooltips.everywhere.js' for the bundle 'Basic.Global'!**     how  to fix it   thank

onnection ID "18230571306091282446", Request ID "8000000f-0003-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Volo.Abp.AbpException: **Could not find the bundle file '/libs/bootstrap/js/bootstrap.enable.tooltips.everywhere.js' for the bundle 'Basic.Global'!**
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Themes_Basic_Layouts_Application.<>c__DisplayClass13_0.<<ExecuteAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---

**Comment by realLiangshiwei** [comment]
Microservice Demo is no longer active, You can check the [eShopOnAbp](https://github.com/abpframework/eShopOnAbp) now.
