### ISSUE TITLE
AngularUI @swimlane Node Modules Directory

### ISSUE THREAD

**Issue by serdarkaracay** [abpframework/abp#11627]
Hi All,
Abp Community 5.1.3, AngularUI and Db Mongo.

Angular folder in  npm install and then npm start or yarn start  output log below.

cat /private/var/folders/bk/6rl2rxq5197gtmxqd8zcp8g80000gn/T/ng-zgUsKb/angular-errors.log 
[error] Error: ENOENT: no such file or directory, lstat '/*/angular/node_modules/@swimlane'
    at Object.realpathSync (node:fs:2488:7)
    at resolveGlobalStyles (/*/angular/node_modules/@angular-devkit/build-angular/src/webpack/configs/styles.js:56:31)
    at getStylesConfig (/*/angular/node_modules/@angular-devkit/build-angular/src/webpack/configs/styles.js:88:70)
    at /*/angular/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js:133:43
    at /*/angular/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:72:16
    at generateWebpackConfig (/*/angular/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:61:40)
    at async generateBrowserWebpackConfigFromContext (/*/angular/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:123:20)
    at async generateI18nBrowserWebpackConfigFromContext (/*/angular/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:70:20)
    at async setup (/*/angular/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js:130:47)

npm list --depth=0  hasnt any error exception 
── @abp/ng.account@5.1.3
├── @abp/ng.components@5.1.3
├── @abp/ng.core@5.1.3
├── @abp/ng.identity@5.1.3
├── @abp/ng.schematics@5.1.3
├── @abp/ng.setting-management@5.1.3
├── @abp/ng.tenant-management@5.1.3
├── @abp/ng.theme.basic@5.1.3
├── @abp/ng.theme.shared@5.1.3
├── @angular-devkit/build-angular@13.1.4
├── @angular-eslint/builder@13.0.1
├── @angular-eslint/eslint-plugin-template@13.0.1
├── @angular-eslint/eslint-plugin@13.0.1
├── @angular-eslint/schematics@13.0.1
├── @angular-eslint/template-parser@13.0.1
├── @angular/animations@13.1.3
├── @angular/cli@13.1.4
├── @angular/common@13.1.3
├── @angular/compiler-cli@13.1.3
├── @angular/compiler@13.1.3
├── @angular/core@13.1.3
├── @angular/forms@13.1.3
├── @angular/language-service@13.1.3
├── @angular/localize@13.1.3
├── @angular/platform-browser-dynamic@13.1.3
├── @angular/platform-browser@13.1.3
├── @angular/router@13.1.3
├── @types/jasmine@3.6.11
├── @types/node@12.20.46
├── @typescript-eslint/eslint-plugin@5.3.0
├── @typescript-eslint/parser@5.3.0
├── eslint@8.9.0
├── jasmine-core@3.7.1
├── karma-chrome-launcher@3.1.0
├── karma-coverage@2.1.1
├── karma-jasmine-html-reporter@1.7.0
├── karma-jasmine@4.0.1
├── karma@6.3.16
├── ng-packagr@13.2.1
├── rxjs@6.6.7
├── tslib@2.3.1
├── typescript@4.5.5
└── zone.js@0.11.4

manuel yarn add @swimlane/ngx-datatable
I tried and then a lot of diff errors.

**Comment by ChrisMir** [comment]
Bumped against the same issue with the quickstart tutorial. After restarting the tutorial and using yarn instead of npm, everything seems working fine.
