### ISSUE TITLE
sqlite error in initial state

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#11695]
**This is Error :** 

```
[16:20:39 INF] Started database migrations...
[16:20:39 INF] Migrating schema for host database...
Unhandled exception. System.ArgumentException: Connection string keyword 'database' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at POS.EntityFrameworkCore.EntityFrameworkCorePOSDbSchemaMigrator.MigrateAsync() in MyProject.EntityFrameworkCore/EntityFrameworkCore/EntityFrameworkCorePOSDbSchemaMigrator.cs:line 29
   at POS.Data.POSDbMigrationService.MigrateDatabaseSchemaAsync(Tenant tenant) in MyProject.Domain/Data/POSDbMigrationService.cs:line 95
   at POS.Data.POSDbMigrationService.MigrateAsync() in MyProject.Domain/Data/POSDbMigrationService.cs:line 52
   at POS.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in MyProject.DbMigrator/DbMigratorHostedService.cs:line 34
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at POS.DbMigrator.Program.Main(String[] args) in MyProject.DbMigrator/Program.cs:line 30
   at POS.DbMigrator.Program.<Main>(String[] args)
```

**This is what I did :**

1.  Download the project template from https://abp.io/get-started with sqlite 
2.  run `dotnet ef migrations add InitialCreate` at EFCore Directory
3.  run DbMigrator
4.  Got this error

**Comment by EngincanV** [comment]
Hi @KaungZawHtet, can you share your connection string?

**Comment by KaungZawHtet** [comment]
```
  "ConnectionStrings": {
    "Default":  "Database=MyDb.db;"
  },
```

**Comment by EngincanV** [comment]
You can change the connection string to an absolute path, like `Data Source=D:\\project\\MyDb\\MyDb.db`. It's a known problem thanks for reporting.

**Comment by KaungZawHtet** [comment]
Previous Sqlite Proj don't need to be absolute path.

```
  "ConnectionStrings": {
    "Default": "Server=localhost;Port=3306;Database=BookStore;Uid=root;"
  },
```

**Comment by EngincanV** [comment]
> Previous Sqlite Proj don't need to be absolute path.
> 
> ```
>   "ConnectionStrings": {
>     "Default": "Server=localhost;Port=3306;Database=BookStore;Uid=root;"
>   },
> ```

Please see https://github.com/aspnet/Microsoft.Data.Sqlite/issues/406#issuecomment-324689331
