### ISSUE TITLE
AutoMapper error for My Modules

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#11726]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**. 5.1.3
* Your database provider(EF Core)
* Exception message and **stack trace** if available (check the logs).
```
[17:38:52 INF] Starting IdentityServer4 version 4.1.2+997a6cdd643e46cd5762b710c4ddc43574cbec2e
[17:38:52 FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Acme.XProject.XProjectHttpApiHostModule, Acme.XProject.HttpApi.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: An exception was thrown while activating Volo.Abp.IdentityServer.Grants.PersistedGrantStore -> Volo.Abp.ObjectMapping.DefaultObjectMapper`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]] -> ?:Volo.Abp.AutoMapper.IMapperAccessor -> ?:Volo.Abp.AutoMapper.MapperAccessor.. See the inner exception for details.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.IdentityServer.Grants.PersistedGrantStore 
-> Volo.Abp.ObjectMapping.DefaultObjectMapper`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]] -> ?:Volo.Abp.AutoMapper.IMapperAccessor -> ?:Volo.Abp.AutoMapper.MapperAccessor.
 ---> AutoMapper.AutoMapperConfigurationException:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
============================================================================
CityCreateDto -> City (Destination member list)
Acme.XProject.Address.Cities.CityCreateDto -> Acme.XProject.Address.Cities.City (Destination member list)

Unmapped properties:
Districts
============================================================================
CityUpdateDto -> City (Destination member list)
Acme.XProject.Address.Cities.CityUpdateDto -> Acme.XProject.Address.Cities.City (Destination member list)

Unmapped properties:
Districts

   at Volo.Abp.AutoMapper.AbpAutoMapperModule.<>c__DisplayClass2_1.<CreateMappings>g__ValidateAll|2(IConfigurationProvider config)
   at Volo.Abp.AutoMapper.AbpAutoMapperModule.CreateMappings(IServiceProvider serviceProvider)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass3_0.<Register>b__0(IComponentContext context, IEnumerable`1 
parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)        
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)  
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.TestService(IServiceProvider serviceProvider, Type service, ILogger logger, String message, Boolean doThrow)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app, IdentityServerMiddlewareOptions options)
   at Acme.XProject.XProjectHttpApiHostModule.OnApplicationInitialization(ApplicationInitializationContext context) in C:\Users\myuser\repos\Acme.XProject\aspnet-core\src\Acme.XProject.HttpApi.Host\XCargoHttpApiHostModule.cs:line 314
   at Volo.Abp.Modularity.AbpModule.OnApplicationInitializationAsync(ApplicationInitializationContext context)
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.InitializeAsync(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModulesAsync()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.InitializeAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplicationAsync(IApplicationBuilder app)
   at Acme.XProject.Program.Main(String[] args) in C:\Users\myuser\repos\Acme.XProject\aspnet-core\src\Acme.XProject.HttpApi.Host\Program.cs:line 41
```
- create a new Solution
- create add new module(Address) and add my main solution
- create City entity and run (runs successfully)
- create District entity and I add new property in Citys `public virtual List<District> Districts { get; set; }`
- Add mappings in AddressApplicationAutoMapperProfile:

```
public AddressApplicationAutoMapperProfile()
    {
        /* You can configure your AutoMapper mapping configuration here.
         * Alternatively, you can split your mapping configurations
         * into multiple profile classes for a better organization. */

        CreateMap<CityCreateDto, City>().IgnoreFullAuditedObjectProperties().Ignore(x => x.ExtraProperties).Ignore(x => x.ConcurrencyStamp).Ignore(x => x.Id);
        CreateMap<CityUpdateDto, City>().IgnoreFullAuditedObjectProperties().Ignore(x => x.ExtraProperties).Ignore(x => x.ConcurrencyStamp).Ignore(x => x.Id);
        CreateMap<City, CityDto>();

        CreateMap<DistrictCreateDto, District>().Ignore(x => x.Id);
        CreateMap<DistrictUpdateDto, District>().Ignore(x => x.Id);
        CreateMap<District, DistrictDto>();
        CreateMap<DistrictWithNavigationProperties, DistrictWithNavigationPropertiesDto>();
        CreateMap<City, LookupDto<int>>().ForMember(dest => dest.DisplayName, opt => opt.MapFrom(src => src.Name));
    }
```

- Add options.AddMaps into XProjectApplicationModule (main project)

 ```
 [DependsOn(typeof(AddressApplicationModule))]
    public class XProjectApplicationModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        Configure<AbpAutoMapperOptions>(options =>
        {
            options.AddMaps<XProjectApplicationModule>();
            options.AddMaps<AddressApplicationModule>(); -->add this line
        });
    }
}
 ```

if I clone all `CreateMap` lines from `AddressApplicationAutoMapperProfile` (module) into `XProjectApplicationAutoMapperProfile`(main) error gones away.

**Comment by AdemAygun** [comment]
If I add `.Ignore(x=>x.Districts)` errors gone away

```
        CreateMap<CityCreateDto, City>().IgnoreFullAuditedObjectProperties().Ignore(x=>x.Districts).Ignore(x => x.ExtraProperties).Ignore(x => x.ConcurrencyStamp).Ignore(x => x.Id);
        CreateMap<CityUpdateDto, City>().IgnoreFullAuditedObjectProperties().Ignore(x=>x.Districts).Ignore(x => x.ExtraProperties).Ignore(x => x.ConcurrencyStamp).Ignore(x => x.Id);


```

**Comment by ivansager** [comment]
I am facing the same issue after upgrading to ABP v8 and automapper 12.

System.ArgumentException: Incorrect number of arguments supplied for call to method WasteBirthCertificateChain get_Item(Int32)' (Parameter 'property')

I am not sure yet how to debug this issue but I suspect it happens in
CreateMap<WasteBirthCertificateChain, WasteBirthCertificateInput>().ReverseMap().ForMember(x => x.Id, a => a.Ignore());

[@AdemAygun mentioned a .Ignore takes a parameter in the constructor but I do not seem to have that with the current version

**Comment by AnonymousDotNet** [comment]
> I am facing the same issue after upgrading to ABP v8 and automapper 12.
> 
> System.ArgumentException: Incorrect number of arguments supplied for call to method WasteBirthCertificateChain get_Item(Int32)' (Parameter 'property')
> 
> I am not sure yet how to debug this issue but I suspect it happens in CreateMap<WasteBirthCertificateChain, WasteBirthCertificateInput>().ReverseMap().ForMember(x => x.Id, a => a.Ignore());
> 
> [@AdemAygun mentioned a .Ignore takes a parameter in the constructor but I do not seem to have that with the current version

@maliming I also encountered a similar problem after creating a new entity class, but I tried the above method and it still didn't solve it, can you help solve it? Please

**Comment by maliming** [comment]
@AnonymousDotNet Please create a new issue and share code & steps.

**Comment by AnonymousDotNet** [comment]
> @AnonymousDotNet Please create a new issue and share code & steps.

I solved it because when I created the mapping, my application layer and domain layer had the same mapping.
But the wrong cause of the prompt has bothered me for quite some time.  : (

**Comment by AnonymousDotNet** [comment]
> @AnonymousDotNet Please create a new issue and share code & steps.

@maliming I solved it because when I created the mapping, my application layer and domain layer had the same mapping.
But the wrong cause of the prompt has bothered me for quite some time.  : (
