### ISSUE TITLE
Angular: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by charleszh-dev** [abpframework/abp#11735]
I want to use [Angular Universal](https://angular.io/guide/universal) for server side rendering for abp's angular project, I set it up according to the [official angular documentation](https://angular.io/guide/universal) and then I solved the localstorage problem according to [an answer on StackOverflow](https://stackoverflow.com/a/57781883/12231536).

Running yarn dev:ssr and opening the page, I get the error message(some paths are replaced with `***`):

```
ReferenceError: document is not defined
    at Object.AppendToHead (***\dist\***\server\main.js:101810:28)
    at Object.AppendStyleToHead (***\dist\***\server\main.js:102399:59)
    at Object.factory (***\dist\***\server\main.js:109658:91)
    at R3Injector.hydrate (***\dist\***\server\main.js:161018:35)
    at R3Injector.get (***\dist\***\server\main.js:160834:33)
    at injectInjectorOnly (***\dist\***\server\main.js:154324:33)
    at ɵɵinject (***\dist\***\server\main.js:154328:61)
    at injectArgs (***\dist\***\server\main.js:154408:23)
    at Object.factory (***\dist\***\server\main.js:161109:52)
    at R3Injector.hydrate (***\***\server\main.js:161018:35)
...
```

After checking the dist\***\server\main.js file, I guessed that this problem might be caused by using the document element in [DOM_STRATEGY](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/strategies/dom.strategy.ts).

Any help is appreciated. Thanks.

**Comment by charleszh-dev** [comment]
ping?

**Comment by hillin** [comment]
A slight bump, this made angular universal unusable.

**Comment by charleszh-dev** [comment]
Hi, @muhammedaltug @EngincanV 
Any suggestions for using Angular Universal?
