### ISSUE TITLE
Error when setting JobPollPeriod

### ISSUE THREAD

**Issue by jaxe1234** [abpframework/abp#11828]
ABP Version: 5.1.4
Database Provider: EF Core

An error occurs when I try to set the job poll period of in the AbpBackgroundJobWorkerOptions.

`Configure<AbpBackgroundJobWorkerOptions>(options =>
            {
                options.JobPollPeriod = TimeSpan.FromHours(5).Milliseconds;
            });`

The error is *Period should be set before starting the timer!*
I have tried doing the Configure in different places in the ConfigureServices of my module.

Stack Trace:
Volo.Abp.AbpInitializationException
  HResult=0x80131500
  Message=An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule, Volo.Abp.BackgroundJobs, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null: Period should be set before starting the timer!. See the inner exception for details.
  Source=Volo.Abp.Core
  StackTrace:
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app)
   at Bewo.SustainPlatform.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory, IRecurringJobManager recurringJobManager) in D:\source\SustainPlatform\aspnet-core\src\Bewo.SustainPlatform.HttpApi.Host\Startup.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.WebTools.BrowserLink.Net.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
AbpException: Period should be set before starting the timer!

**Comment by realLiangshiwei** [comment]
`TotalMilliseconds` instead of `Milliseconds`
