### ISSUE TITLE
Blazor-Server fails to start: Could not load type 'Blazorise.Color' from assembly 'Volo.Abp.BlazoriseUI' due to value type mismatch

### ISSUE THREAD

**Issue by Enissay** [abpframework/abp#11930]
* Your **ABP Framework version**.
Version 5.1.4 (Stable)
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Blazor-Server
* Your database provider(EF Core/MongoDB)
Ef Core
* Exception message and **stack trace** if available (check the logs).
```bash
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/ - -
[22:53:15 INF] Executing endpoint '/_Host'
[22:53:15 INF] Route matched with {page = "/_Host", action = "", controller = "", area = ""}. Executing page /_Host
[22:53:15 INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
[22:53:15 INF] Executing an implicit handler method - ModelState is Valid
[22:53:15 INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
[22:53:15 DBG] Added bundle 'Blazor.BasicTheme.Global' to the page in 0,43 ms.
[22:53:15 DBG] Added bundle 'Blazor.BasicTheme.Global' to the page in 0,11 ms.
[22:53:15 INF] Executed page /_Host in 3.2766ms
[22:53:15 INF] Executed endpoint '/_Host'
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/ - - - 200 - text/html;+charset=utf-8 4.8081ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/libs/bootstrap/css/bootstrap.css?_v=637827988079382692 - -
[22:53:15 INF] The file /libs/bootstrap/css/bootstrap.css was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/libs/bootstrap/css/bootstrap.css?_v=637827988079382692 - - - 304 - text/css 0.9002ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/libs/@fortawesome/fontawesome-free/css/all.css?_v=637827988079142694 - -
[22:53:15 INF] The file /libs/@fortawesome/fontawesome-free/css/all.css was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/libs/@fortawesome/fontawesome-free/css/all.css?_v=637827988079142694 - - - 304 - text/css 0.2426ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/libs/@fortawesome/fontawesome-free/css/v4-shims.css?_v=637827988079142694 - -
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_content/Blazorise/blazorise.css?_v=637823478180000000 - -
[22:53:15 INF] The file /libs/@fortawesome/fontawesome-free/css/v4-shims.css was not modified
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css?_v=637823478160000000 - -
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/libs/@fortawesome/fontawesome-free/css/v4-shims.css?_v=637827988079142694 - - - 304 - text/css 0.2130ms
[22:53:15 INF] The file /_content/Blazorise/blazorise.css was not modified
[22:53:15 INF] The file /_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_content/Blazorise/blazorise.css?_v=637823478180000000 - - - 304 - text/css 0.3603ms
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_content/Blazorise.Bootstrap5/blazorise.bootstrap5.css?_v=637823478160000000 - - - 304 - text/css 0.3082ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_content/Blazorise.Snackbar/blazorise.snackbar.css?_v=637710290740000000 - -
[22:53:15 INF] The file /_content/Blazorise.Snackbar/blazorise.snackbar.css was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_content/Blazorise.Snackbar/blazorise.snackbar.css?_v=637710290740000000 - - - 304 - text/css 0.1780ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_content/Volo.Abp.AspNetCore.Components.Web.BasicTheme/libs/abp/css/theme.css?_v=637816543540000000 - -
[22:53:15 INF] The file /_content/Volo.Abp.AspNetCore.Components.Web.BasicTheme/libs/abp/css/theme.css was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_content/Volo.Abp.AspNetCore.Components.Web.BasicTheme/libs/abp/css/theme.css?_v=637816543540000000 - - - 304 - text/css 0.2052ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/blazor-global-styles.css?_v=637827988079142694 - -
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/InfinityBoox.Blazor.styles.css?_v=637828038816680324 - -
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_framework/blazor.server.js?_v=637778212340000000 - -
[22:53:15 INF] The file /blazor-global-styles.css was not modified
[22:53:15 INF] The file /InfinityBoox.Blazor.styles.css was not modified
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_content/Volo.Abp.AspNetCore.Components.Web/libs/abp/js/abp.js?_v=637816543460000000 - -
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/blazor-global-styles.css?_v=637827988079142694 - - - 304 - text/css 0.1533ms
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/InfinityBoox.Blazor.styles.css?_v=637828038816680324 - - - 304 - text/css 0.1658ms
[22:53:15 INF] The file /_framework/blazor.server.js was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_framework/blazor.server.js?_v=637778212340000000 - - - 304 - application/javascript 0.2222ms
[22:53:15 INF] The file /_content/Volo.Abp.AspNetCore.Components.Web/libs/abp/js/abp.js was not modified
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_content/Volo.Abp.AspNetCore.Components.Web/libs/abp/js/abp.js?_v=637816543460000000 - - - 304 - application/javascript 0.3974ms
[22:53:15 INF] Request starting HTTP/2 GET https://localhost:41333/_blazor/initializers - -
[22:53:15 INF] Executing endpoint 'Blazor initializers'
[22:53:15 INF] Executed endpoint 'Blazor initializers'
[22:53:15 INF] Request finished HTTP/2 GET https://localhost:41333/_blazor/initializers - - - 200 - application/json;+charset=utf-8 1.2483ms
[22:53:15 INF] Request starting HTTP/2 POST https://localhost:41333/_blazor/negotiate?negotiateVersion=1 text/plain;charset=UTF-8 0
[22:53:15 INF] Executing endpoint '/_blazor/negotiate'
[22:53:15 INF] Executed endpoint '/_blazor/negotiate'
[22:53:15 INF] Request finished HTTP/2 POST https://localhost:41333/_blazor/negotiate?negotiateVersion=1 text/plain;charset=UTF-8 0 - 200 316 application/json 2.3569ms
[22:53:16 INF] Request starting HTTP/1.1 GET https://localhost:41333/_blazor?id=juK2r3501_VHImz7FBtuDg - -
[22:53:16 INF] Executing endpoint '/_blazor'
[22:53:16 INF] Request starting HTTP/2 GET https://localhost:41333/favicon.ico - -
[22:53:16 INF] The file /favicon.ico was not modified
[22:53:16 INF] Request finished HTTP/2 GET https://localhost:41333/favicon.ico - - - 304 - image/x-icon 0.3489ms
[22:53:16 WRN] Unhandled exception rendering component: Could not load type 'Blazorise.Color' from assembly 'Volo.Abp.BlazoriseUI, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
System.TypeLoadException: Could not load type 'Blazorise.Color' from assembly 'Volo.Abp.BlazoriseUI, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
   at Volo.Abp.AspNetCore.Components.Web.BasicTheme.Themes.Basic.MainLayout.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
[22:53:16 ERR] Unhandled exception in circuit 'PHm8A_E8i9iEwjr3M0Iu-ibYSV4jdct6pih_CaU4eFI'.
System.TypeLoadException: Could not load type 'Blazorise.Color' from assembly 'Volo.Abp.BlazoriseUI, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
   at Volo.Abp.AspNetCore.Components.Web.BasicTheme.Themes.Basic.MainLayout.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
[22:53:16 INF] Executed endpoint '/_blazor'
[22:53:16 INF] Request finished HTTP/1.1 GET https://localhost:41333/_blazor?id=juK2r3501_VHImz7FBtuDg - - - 101 - - 16.5065ms
```
* Steps needed to **reproduce** the problem.
1. create a template `abp new InfinityBoox --template app --ui blazor-server --tiered --database-provider ef --database-management-system PostgreSQL --create-solution-folder`
2. Adapt appsettings connection string
3. initialize DB from DbMigrator
4. Run projects in order: IdServer, ApiHost, Blazor
5. Blazor fails with the above error

It's worth noting that I have created a project using the same steps a few weeks ago and everything worked fine!

**Comment by maliming** [comment]
Unable reproduce.

You can run `abp clean` and re-try.

![image](https://user-images.githubusercontent.com/6908465/158087223-f6a4f269-0cd9-4f0e-b0ee-a17361f87040.png)

**Comment by clinically-au** [comment]
Make sure you're not using Blazorise v1.0. It is not supported in 5.1.4 (need to wait for 5.2)

I'm pretty sure that's the error I got when I tried that.

**Comment by Enissay** [comment]
> Make sure you're not using Blazorise v1.0. It is not supported in 5.1.4 (need to wait for 5.2)

I have restarted the project 3 times and was still having the same issue... And that was it!!
It was using Balorize `1.0.1` by default, when I manually downgraded to the next old version `0.9.5.1`, it worked!

Thank you <3

Thank you @maliming for the time as well <3
