### ISSUE TITLE
How to commit transactions in a application service.

### ISSUE THREAD

**Issue by tianxin8206** [abpframework/abp#12069]
* Your **ABP Framework version**. 5.1.3
* Your database provider(EF Core/MongoDB) efcore

I need to commit transactions in application service. What should I do?

**Comment by berkansasmaz** [comment]
See https://docs.abp.io/en/abp/latest/Unit-Of-Work#savechangesasync

```
       await UnitOfWorkManager.Current.CompleteAsync();
```

**Comment by tianxin8206** [comment]
Thank you.I tried it ,but UnitOfWorkManager.Current.SaveChangesAsync didn't solve my exception.
Detail message:
```
[18:37:30 ERR] An error occurred using a transaction.
[18:37:30 WRN] An exception occurred, but response has already started!
[18:37:30 ERR] An unhandled exception has occurred while executing the request.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity
activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 15
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line
264
   at MySqlConnector.MySqlTransaction.CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlTransaction.cs:line 3
6
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at ShardingCore.EFCores.ShardingRelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.EntityFrameworkCore.EfCoreTransactionApi.CommitAsync()
   at Volo.Abp.Uow.UnitOfWork.CommitTransactionsAsync()
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at JYLink.EADP.Cloud.Middlewares.AkSkAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at JYLink.EADP.Cloud.Middlewares.CurrentOrganizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy p
olicy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Exception location:[EfCoreTransactionApi.CommitAsync](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Uow/EntityFrameworkCore/EfCoreTransactionApi.cs#L41)

CancellationTokenProvider.Token value is false.

I used the feign client to request webapi, and the feign client got the response and disconnected the HTTP connection. But I found that my program request was not completed. Http has been disconnected, CancellationTokenProvider.Token value became false, and the transaction commit failure. I'm not sure how to solve this problem. What do you suggest?

**Comment by berkansasmaz** [comment]
Thanks for sharing the log, but it doesn't seem to be enough for me to understand the problem. Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can better assist you.

**Comment by tianxin8206** [comment]
I created a new project.I ported the code to the new project,but I found that the new project didn't implement [EfCoreTransactionApi.CommitAsync](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Uow/EntityFrameworkCore/EfCoreTransactionApi.cs#L41).Under what circumstances will the CommitAsync method be executed?

**Comment by berkansasmaz** [comment]
https://docs.abp.io/en/abp/latest/Unit-Of-Work#conventions
> If you call a [repository](https://docs.abp.io/en/abp/latest/Repositories) method and there is no UOW started yet, it automatically begins a new transactional UOW that involves all the operations done in the repository method and **commits the transaction if the repository method doesn't throw any exception**. The repository method doesn't know about UOW or transaction at all. It just works on a regular database objects

**Comment by tianxin8206** [comment]
Thank you very much for your help.
