### ISSUE TITLE
Abp Suite [5.2.0-rc.2] Define property: Enum missing

### ISSUE THREAD

**Issue by h4r7w3l1** [abpframework/abp#12065]
* Your version: **5.2.0-rc.2**.
* Your User Interface **MVC**
* Your database provider: **EF Core**
* Exception message and **stack trace** if available (check the logs).

```
[02:33:40 ERR] Build started...
Build failed. Use dotnet build to see the errors.

[02:33:40 WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "Error occurred on DB migration step! Make sure the project is compiled and working. Command output: Build started...\r\nBuild failed. Use dotnet build to see the errors.\r\n",
  "details": null,
  "data": {},
  "validationErrors": null
}

[02:33:40 WRN] Error occurred on DB migration step! Make sure the project is compiled and working. Command output: Build started...
Build failed. Use dotnet build to see the errors.

Volo.Abp.UserFriendlyException: Error occurred on DB migration step! Make sure the project is compiled and working. Command output: Build started...
Build failed. Use dotnet build to see the errors.

   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Commands.DbMigrationCommand.ExecuteAsync(CrudPageCommandOptions options)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.CommandManager.ExecuteAllAsync(CrudPageCommandOptions options)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Commands.CrudPageGenerator.GenerateAsync(EntityModel entity, Solution solution)
   at Volo.Abp.Suite.Controllers.CrudPageGeneratorController.SaveAndGenerateEntityAsync(Guid solutionId, EntityModel entity)
   at lambda_method1967(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[02:33:40 WRN] Code:
[02:33:40 WRN] Details:
```
![Fix VS](https://tlgur.online/d/1fGBcdOI)

* Steps needed to **reproduce** the problem.

Model in suite with [**Enum** object](https://gist.github.com/h4r7w3l1/6de6694d6a0fad157953d06d79fd43e0)

Simple class ENUM of course exactly created in Domain solution.
Missing using's generate when use Enum type in Abp Suite. On version 5.1.4 that's works fine!

**Comment by yekalkan** [comment]
Fixed. Thank you for reporting.
