### ISSUE TITLE
EShopOnAbp Redis Cache Problem

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#12150]
When I try to start administration service and identity service using visual studio. it throws redis Error.
I tried to clear the cookie but it still doesnt work.

[12:37:26 WRN] ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
   at Volo.Abp.Caching.StackExchangeRedis.AbpRedisCache.SetManyAsync(IEnumerable`1 items, DistributedCacheEntryOptions options, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.<>c__DisplayClass54_0.<<SetManyAsync>g__SetRealCache|0>d.MoveNext()

**Comment by slarkerino** [comment]
Problem Solved. I guess it is because using redis server on local **windows** machine. And the version of redis is too low. When I changed to remote redis server on my linux machine it works fine
