### ISSUE TITLE
Forms module not creating tables

### ISSUE THREAD

**Issue by Mikmak50** [abpframework/abp#12209]
ABP version: 5.2.0 Commercial
User interface: MVC
Database: EF Core
Issue: Adding Forms module using ABP Suite does not create tables the database causing the following issue:

2022-04-07 18:41:55.149 +02:00 [DBG] Found in the cache: pn:R,pk:admin,n:Forms.Form
2022-04-07 18:41:55.263 +02:00 [ERR] Failed executing DbCommand (10ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT [f].[Id], [f].[CanEditResponse], [f].[ConcurrencyStamp], [f].[CreationTime], [f].[CreatorId], [f].[DeleterId], [f].[DeletionTime], [f].[Description], [f].[ExtraProperties], [f].[HasLimitOneResponsePerUser], [f].[IsAcceptingResponses], [f].[IsCollectingEmail], [f].[IsDeleted], [f].[IsQuiz], [f].[LastModificationTime], [f].[LastModifierId], [f].[RequiresLogin], [f].[TenantId], [f].[Title]
FROM [FrmForms] AS [f]
WHERE ((@__ef_filter__p_0 = CAST(1 AS bit)) OR ([f].[IsDeleted] = CAST(0 AS bit))) AND ((@__ef_filter__p_1 = CAST(1 AS bit)) OR [f].[TenantId] IS NULL)
ORDER BY [f].[LastModificationTime] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
2022-04-07 18:41:55.320 +02:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Forms.EntityFrameworkCore.FormsDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'FrmForms'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:5f1a8f00-c78e-4ad2-a66b-149f08f1b49b
Error Number:208,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'FrmForms'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
ClientConnectionId:5f1a8f00-c78e-4ad2-a66b-149f08f1b49b
Error Number:208,State:1,Class:16
2022-04-07 18:41:55.358 +02:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{

**Comment by maliming** [comment]
hi

Please create question on https://support.abp.io/QA/Questions/New
