### ISSUE TITLE
Settings is not reading in MVC / Razor Pages

### ISSUE THREAD

**Issue by ahmadmasoum** [abpframework/abp#12283]
* Your **ABP Framework version** : 5.14
* Your **User Interface** type: MVC
* Your database provider: EF Core
* Exception message and **stack trace** if available (check the logs).  No exception message 
* Steps needed to **reproduce** the problem.

I Added a new setting to already existing CarSharingSettingDefinitionProvider
```c#
context.Add(new SettingDefinition(CarSharingSettings.BaseCurrency, "USD", new LocalizableString(typeof(CurrencyResource), "USD"), null, true));
```

I can read the value in the backend 
but when I try to read the value in frontend I get undefined 
```javascript
        var baseCurrency = abp.setting.get("CarSharing.BaseCurrency");
```

and I checked the AbpSettings table in the database and the value wasn't saved there.

I'm I missing something?

**Comment by realLiangshiwei** [comment]
There are different setting keys

![image](https://user-images.githubusercontent.com/16813853/163717423-f22cf631-9239-4f4b-bc08-935cd67be21e.png)

**Comment by ahmadmasoum** [comment]
No the are the same i double checked 
![image](https://user-images.githubusercontent.com/72628109/163720743-b9269fde-6859-4fff-be95-423104a52ff3.png)
![image](https://user-images.githubusercontent.com/72628109/163720801-61596d94-95a1-4b60-832b-468bd8feb1c6.png)

**Comment by realLiangshiwei** [comment]
> IsVisibleToClients: A boolean value indicates that whether this setting value is available in the client side or not. **Default value is false** to prevent accidently publishing an internal critical setting value.

https://docs.abp.io/en/abp/latest/Settings#settingdefinition

**Comment by ahmadmasoum** [comment]
Its already set to true
> ```c#
> context.Add(new SettingDefinition(CarSharingSettings.BaseCurrency, "USD", new LocalizableString(typeof(CurrencyResource), "USD"), null, true));
> ```

**Comment by realLiangshiwei** [comment]
Can not reproduce the problem, can you provide full steps to reproduce?

![image](https://user-images.githubusercontent.com/16813853/163780795-a6ca2134-5e31-4670-839d-30cb668b0386.png)

**Comment by ahmadmasoum** [comment]
I added `SettingDefinition` in the default `SettingDefinitionProvider` class created with the project 

![image](https://user-images.githubusercontent.com/72628109/163783998-28d49cdc-9524-4f7f-903d-1707460aec1d.png)

I run the DbMigrator and started the project 

I get the value in App service 
![image](https://user-images.githubusercontent.com/72628109/163784590-cfc76578-9ff4-4783-85c2-87f2f237411e.png)

But i don't get it in fronend 
![image](https://user-images.githubusercontent.com/72628109/163784926-5ed5d1e1-78ff-4da2-95bc-59d407c58147.png)

**Comment by ahmadmasoum** [comment]
I Tried adding the settings in appsettings json file
```json
  "Settings": {
    "CarSharing.Test": "Test Value",
  }
```
Called it 
```c#
await _settingProvider.GetOrNullAsync("CarSharing.Test");
```

And got this error

```
2022-04-18 15:16:53.272 +03:00 [ERR] Undefined setting: CarSharing.Test
Volo.Abp.AbpException: Undefined setting: CarSharing.Test
   at Volo.Abp.Settings.SettingDefinitionManager.Get(String name)
   at Volo.Abp.Settings.SettingProvider.GetOrNullAsync(String name)
   at GCU365.CarSharing.SupportedCurrencies.SupportedCurrenciesAppService.GetListAsync(GetSupportedCurrenciesInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method2909(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**Comment by realLiangshiwei** [comment]
>I Tried adding the settings in appsettings json file 

It's a setting value provider, but you need to define a setting first.

See https://docs.abp.io/en/abp/latest/Settings#defining-settings.

Also, you need to make sure the Startup project has a reference to `..SettingDefinitionProvider`

**Comment by D4ngeresque** [comment]
I ran into this issue myself and it looks like it is caused by the fact that it is using the setting definitions available to your Web project (which by default won't include the setting definitions in your Domain project because it doesn't reference the Domain project), but the remote setting values that it gets through the web API via [RemoteSettingProvider](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.Mvc.Client.Common/Volo/Abp/AspNetCore/Mvc/Client/RemoteSettingProvider.cs) which is the web project's default implementation of ISettingProvider. I would almost consider this a bug since this either requires adding a reference to the Domain project and then registering it's setting providers like so:

```
    public class BookStoreMvcWebModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            ...

            context.Services.Configure<AbpSettingOptions>(options =>
            {
                options.DefinitionProviders.AddIfNotContains(typeof(BookStoreMvcSettingDefinitionProvider));
            });
            context.Services.AddTransient<BookStoreMvcSettingDefinitionProvider>();
        }
        ...
    }
```

... or creating a duplicate setting definition in your web project, neither of which seem ideal. 

The behavior that causes this can be seen in [AbpApplicationConfigurationAppService](https://github.com/abpframework/abp/blob/5a8b46839700c458f9b5c1b710f4c2e532c4c383/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationAppService.cs).GetSettingConfigAsync()

I'm not sure what the best solution to this would be. Moving the setting definitions to some further down module in the template, like Domain.Shared, so they are visible to the web project, or moving [ApplicationConfigurationScriptController](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationScriptController.cs) out of MVC to the web API where it has access to the setting definitions. Both have their advantages and disadvantages...

Regardless, this is definitely a departure from the documentation which makes no mention of any extra steps needed to get the client side settings working.
