### ISSUE TITLE
EfCoreIdentityUserRepository.GetRoleNamesAsync throws ArgumentNullException during Seeding.

### ISSUE THREAD

**Issue by hellfirehd** [abpframework/abp#12496]
**ABP Framework Version:** 5.2.1

**Database Provider:** EF Core -> PostgreSql && EF Core -> SqlServer

## Steps needed to **reproduce** the problem.

* Create a new module

```powershell
abp new "Ezrie.AuthService" -t module --no-ui -d ef -dbms PostgreSQL --no-random-port -csf -o "services"
abp add-module "Volo.Identity" -s "services\Ezrie.AuthService\Ezrie.AuthService.sln" --skip-db-migrations
abp add-module "Volo.IdentityServer" -s "services\Ezrie.AuthService\Ezrie.AuthService.sln" --skip-db-migrations
abp add-module "Volo.PermissionManagement" -s "services\Ezrie.AuthService\Ezrie.AuthService.sln" --skip-db-migrations
```

* Add missing `<PackageReference />` and `using` statements to `AuthServiceDomainModule` and `AuthServiceHttpApiModule`.

* Ensure MultiTenancy is Enabled.

* Ensure `AuthServiceDbContext` implements all the things:

```cSharp
[ReplaceDbContext(typeof(IIdentityDbContext))]
[ReplaceDbContext(typeof(IIdentityServerDbContext))]
[ReplaceDbContext(typeof(IPermissionManagementDbContext))]
[ConnectionStringName(AuthServiceDbProperties.ConnectionStringName)]
public class AuthServiceDbContext : AbpDbContext<AuthServiceDbContext>,
	IAuthServiceDbContext,
	IIdentityDbContext,
	IIdentityServerDbContext,
	IPermissionManagementDbContext
{
	/* Add DbSet for each Aggregate Root here. Example:
     * public DbSet<Question> Questions { get; set; }
     */

	public AuthServiceDbContext(DbContextOptions<AuthServiceDbContext> options)
		: base(options)
	{

	}

	public DbSet<IdentityUser> Users { get; }
	
	// SNIP
	
	public DbSet<PermissionGrant> PermissionGrants { get; }

	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);

		builder.ConfigureAuthService();
		builder.ConfigureIdentity();
		builder.ConfigureIdentityServer();
		builder.ConfigurePermissionManagement();
	}
}
```

* Add a migration.

* Update existing DbMigrator to depend on `AuthServiceApplicationContractsModule` and `AuthServiceEntityFrameworkCoreModule`.

* Execute the DbMigrator.

* Enjoy the exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'inner')
   at System.Linq.Queryable.Join[TOuter,TInner,TKey,TResult](IQueryable`1 outer, IEnumerable`1 inner, Expression`1 outerKeySelector, Expression`1 innerKeySelector, Expression`1 resultSelector)
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.GetRoleNamesAsync(Guid id, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Identity.IdentityUserStore.GetRolesAsync(IdentityUser user, CancellationToken cancellationToken)
   at Volo.Abp.Identity.IdentityUserStore.IsInRoleAsync(IdentityUser user, String normalizedRoleName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.AddToRoleAsync(TUser user, String role)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Identity.IdentityDataSeeder.SeedAsync(String adminEmail, String adminPassword, Nullable`1 tenantId)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Ezrie.DbMigrator.DbMigratorService.SeedDataAsync(Tenant tenant, CancellationToken cancellationToken) in D:\Source\Ezrie\shared\Ezrie.DbMigrator\DbMigrator\DbMigratorService.cs:line 147
   at Ezrie.DbMigrator.DbMigratorService.MigrateHostAsync(CancellationToken cancellationToken) in D:\Source\Ezrie\shared\Ezrie.DbMigrator\DbMigrator\DbMigratorService.cs:line 69
   at Ezrie.DbMigrator.DbMigratorService.MigrateAsync(CancellationToken cancellationToken) in D:\Source\Ezrie\shared\Ezrie.DbMigrator\DbMigrator\DbMigratorService.cs:line 60
   at Ezrie.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in D:\Source\Ezrie\shared\Ezrie.DbMigrator\DbMigrator\DbMigratorHostedService.cs:line 48
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Ezrie.Program.Main(String[] args) in D:\Source\Ezrie\shared\Ezrie.DbMigrator\Program.cs:line 34
```

**Comment by maliming** [comment]
Please try to reproduce the problem with minimal code and steps.

**Comment by hellfirehd** [comment]
This minimal code throws the `ArgumentNullException: Value cannot be null. (Parameter 'inner')` when seeding is executed:

```csharp
[DependsOn(
	typeof(AuthServiceDomainModule),
	typeof(AbpEntityFrameworkCoreModule),
	typeof(AbpIdentityEntityFrameworkCoreModule)
)]
public class AuthServiceEntityFrameworkCoreModule : AbpModule
{
}

[ReplaceDbContext(typeof(IIdentityDbContext))]
[ConnectionStringName(AuthServiceDbProperties.ConnectionStringName)]
public class AuthServiceDbContext : AbpDbContext<AuthServiceDbContext>, IIdentityDbContext
{
	/* Add DbSet for each Aggregate Root here. Example:
     * public DbSet<Question> Questions { get; set; }
     */

	public AuthServiceDbContext(DbContextOptions<AuthServiceDbContext> options)
		: base(options)
	{

	}

	public DbSet<IdentityUser> Users { get; }
	public DbSet<IdentityRole> Roles { get; }
	public DbSet<IdentityClaimType> ClaimTypes { get; }
	public DbSet<OrganizationUnit> OrganizationUnits { get; }
	public DbSet<IdentitySecurityLog> SecurityLogs { get; }
	public DbSet<IdentityLinkUser> LinkUsers { get; }

	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);

		builder.ConfigureIdentity();
	}
}
```

**Comment by maliming** [comment]
Try to add `set` to all `DbSet`.

`public DbSet<IdentityUser> Users { get; set;}`

**Comment by hellfirehd** [comment]
That appears to have solved it. Thank you!
