### ISSUE TITLE
Blazor App template code error when calling WebAssemblyHostBuilder.CreateDefault

### ISSUE THREAD

**Issue by nicewk** [abpframework/abp#12552]
When run   Blazor project first time, got following error message on browser console window. 
The solution generate by cli and without any new code to it.
     
       System.AggregateException: One or more errors occurred. (An error occurred during the ABP remote HTTP request. (TypeError: Failed to fetch) See the inner exception for details.)
 ---> Volo.Abp.Http.Client.AbpRemoteCallException: An error occurred during the ABP remote HTTP request. (TypeError: Failed to fetch) See the inner exception for details.
 ---> System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> System.Runtime.InteropServices.JavaScript.JSException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Components.Web.AbpBlazorClientHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Components.Web.AbpBlazorClientHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__34[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   --- End of inner exception stack trace ---
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__34[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__33`1[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__31`1[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto, Volo.Abp.AspNetCore.Mvc.Contracts, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies.AbpApplicationConfigurationClientProxy.GetAsync()
   at Volo.Abp.AspNetCore.Components.WebAssembly.WebAssemblyCachedApplicationConfigurationClient.InitializeAsync()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.AbpWebAssemblyHostBuilderExtensions.InitializeModulesAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.AbpWebAssemblyHostBuilderExtensions.InitializeApplicationAsync(IAbpApplicationWithExternalServiceProvider application, IServiceProvider serviceProvider)
   at KiddoBell.Blazor.Program.Main(String[] args) in D:\Labs\KiddoBell\src\KiddoBell.Blazor\Program.cs:line 19
   --- End of inner exception stack trace ---

**Comment by maliming** [comment]
You need to run the API or Identity Server first.

**Comment by nicewk** [comment]
Thanks, @maliming, I did run the API first. But after single step debug, the issue disappeared.
