### ISSUE TITLE
ABP Audit Log - GetCancellationToken NullReferenceException While Inserting Log In Database

### ISSUE THREAD

**Issue by rajgog** [abpframework/abp#12711]
I am using the ABP community version and implemented audit logs. I see the below error while accessing endpoints exposed by my API / controller.
**ABP version: 5.2.2**
**DB provider for audit logs: EF Core / Postgres SQL**
**Packages used: Volo.Abp.AuditLogging.EntityFrameworkCore, Volo.Abp.EntityFrameworkCore.PostgreSql**

This is what my service host module dependency structure looks like;
```
[DependsOn(
    typeof(AbpSwashbuckleModule),
    typeof(AbpEntityFrameworkCorePostgreSqlModule),
    typeof(AbpAuditLoggingEntityFrameworkCoreModule),
    typeof(MyServiceApplicationModule),
    typeof(MyServiceHttpApiModule))]
public class MyServiceHostModule : AbpModule
```

This is what my OnApplicationInitialization and ConfigureServices methods of the module look like;

```
public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
    var app = context.GetApplicationBuilder();
    app.UseCorrelationId();
    app.UseStaticFiles();
    app.UseRouting();
    app.UseSwagger();
    app.UseAuditing();
    app.UseConfiguredEndpoints();
    var option = new RewriteOptions();
    option.AddRedirect("^$", "swagger");
    app.UseRewriter(option);
}

public override void ConfigureServices(ServiceConfigurationContext context)
{
    var services = context.Services;

    services.AddAbpSwaggerGen(options =>
    {
        options.SwaggerDoc("v1", new OpenApiInfo { Title = "MyService.API V1", Version = "v1" });
        options.DocInclusionPredicate((docName, description) => true);
        options.CustomSchemaIds(type => type.FullName);
        options.HideAbpEndpoints();
    });

    Configure<AbpDbContextOptions>(options =>
    {
        options.UseNpgsql();
    });

    Configure<AbpAuditingOptions>(options =>
    {
        options.HideErrors = false;
        options.IsEnabledForGetRequests = true;
        options.ApplicationName = "MyServiceName";
    });
}
```

**Stack trace:**
      Connection id "0HMHSIHHOGO2J", Request id "0HMHSIHHOGO2J:00000002": An unhandled exception was thrown by the application.

      System.NullReferenceException: Object reference not set to an instance of an object.

         at Volo.Abp.Domain.Repositories.BasicRepositoryBase`1.get_CancellationTokenProvider()

         at Volo.Abp.Domain.Repositories.BasicRepositoryBase`1.GetCancellationToken(CancellationToken preferredValue)

         at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.InsertAsync(TEntity entity, Boolean autoSave, CancellationToken cancellationToken)

         at Volo.Abp.AuditLogging.AuditingStore.SaveLogAsync(AuditLogInfo auditInfo)

         at Volo.Abp.AuditLogging.AuditingStore.SaveAsync(AuditLogInfo auditInfo)

         at Volo.Abp.Auditing.AuditingManager.SaveAsync(DisposableSaveHandle saveHandle)

         at Volo.Abp.Auditing.AuditingManager.DisposableSaveHandle.SaveAsync()

         at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

      --- End of stack trace from previous location ---

         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

         at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

      --- End of stack trace from previous location ---

         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by maliming** [comment]
hi

Did you use the Autofac module in your project?

**Comment by rajgog** [comment]
Hello @maliming,
No, I haven't used the Autofac module.

**Comment by maliming** [comment]
Please use it https://docs.abp.io/en/abp/latest/Autofac-Integration

**Comment by rajgog** [comment]
Sorry, but why is it required to use? Is it necessary to make audit logs work?
Also, integrating audit logs doc doesn’t mention anything about it.

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Dependency-Injection#property-injection

**Comment by rajgog** [comment]
Ahh i see it here,

`While ABP has no core dependency to any 3rd-party DI provider, it's required to use a provider that supports dynamic proxying and some other advanced features to make some ABP features properly work. Startup templates come with Autofac installed. See [Autofac integration](https://docs.abp.io/en/abp/latest/Autofac-Integration) document for more information.`

Let me try adding autofac and i will update you back. Thanks.

**Comment by rajgog** [comment]
Adding autofac resolved the issue. It seems autofac is a mandatory 3rd-party DI provider that needs to be added in dependency for many of abp features to work. Thanks @maliming
