### ISSUE TITLE
When use SqLite, It's throw a exception:ArgumentException: Keyword not supported: 'version'. 

### ISSUE THREAD

**Issue by Fisher-Joe** [abpframework/abp#1276]
```
System.ArgumentException: Keyword not supported: 'version'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction()
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextWithTransaction(IUnitOfWork unitOfWork) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\Uow\EntityFrameworkCore\UnitOfWorkDbContextProvider.cs:line 83
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContext(IUnitOfWork unitOfWork, String connectionStringName, String connectionString) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\Uow\EntityFrameworkCore\UnitOfWorkDbContextProvider.cs:line 51
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.<>c__DisplayClass3_0.<GetDbContext>b__0() in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\Uow\EntityFrameworkCore\UnitOfWorkDbContextProvider.cs:line 42
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory) in D:\Github\abp\framework\src\Volo.Abp.Core\System\Collections\Generic\AbpDictionaryExtensions.cs:line 101
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContext() in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\Uow\EntityFrameworkCore\UnitOfWorkDbContextProvider.cs:line 40
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.get_DbSet() in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\Domain\Repositories\EntityFrameworkCore\EfCoreRepository.cs:line 20
   at Volo.Abp.IdentityServer.Clients.ClientRepository.FindByCliendIdAsync(String clientId, Boolean includeDetails, CancellationToken cancellationToken) in D:\Github\abp\modules\identityserver\src\Volo.Abp.IdentityServer.EntityFrameworkCore\Volo\Abp\IdentityServer\Clients\ClientRepository.cs:line 26
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86

```

**Comment by maliming** [comment]
What is the recurring step?

**Comment by Fisher-Joe** [comment]
Yes.
I create a project in https://abp.io/Templates and use SqLite.

**Comment by maliming** [comment]
So, What is your sqlite connection string?

**Comment by Fisher-Joe** [comment]
Data Source=c:\mydb.db;Version=3;Pooling=True;Max Pool Size=100;

**Comment by ismcagdas** [comment]
Did you try to remove version from your connection string ? It seems like it is not supported as the original message says: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/406#issuecomment-324689331

**Comment by Fisher-Joe** [comment]
Data Source=c:\mydb.db
