### ISSUE TITLE
Host terminated unexpectedly!

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#12814]
```c#
PM> add-migration Add_RivetDie_Entity
Build started...
Build succeeded.
[11:04:33 INF] Starting web host.
[11:04:35 FTL] Host terminated unexpectedly!
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Jee.SmartManufacturing.Biw.Srd.Web.Program.Main(String[] args) in D:\sources\SmartManufacturing-Srd\src\Jee.SmartManufacturing.Biw.Srd.Web\Program.cs:line 38
To undo this action, use Remove-Migration.
PM> 
```

**Comment by JadynWong** [comment]
It does not affect your migration generation.

https://github.com/dotnet/runtime/issues/60600
