### ISSUE TITLE
System.InvalidOperationException: Navigation property 'Claims' on entity of type 'IdentityUser' cannot be loaded because the entity is not being tracked. Navigation properties can only be loaded for tracked entities.

### ISSUE THREAD

**Issue by gaojianzhuang** [abpframework/abp#12810]
* ABP Framework version: 3.3.2.
* User Interface Razor Pages
* EF Core
* Exception message and **stack trace** if available (check the logs).

```
2022-05-30 22:57:15.271 +08:00 [INF] Entity Framework Core 3.1.25 initialized 'IdentityDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: using lazy-loading proxies 
2022-05-30 22:57:15.287 +08:00 [ERR] Connection id "0HMI29IMUFHVL", Request id "0HMI29IMUFHVL:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Navigation property 'Claims' on entity of type 'IdentityUser' cannot be loaded because the entity is not being tracked. Navigation properties can only be loaded for tracked entities.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.LoadAsync(INavigation navigation, InternalEntityEntry entry, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.EnsureCollectionLoadedAsync[TProperty](TEntity entity, Expression`1 propertyExpression, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.RepositoryExtensions.EnsureCollectionLoadedAsync[TEntity,TKey,TProperty](IBasicRepository`2 repository, TEntity entity, Expression`1 propertyExpression, CancellationToken cancellationToken)
   at Volo.Abp.Identity.IdentityUserStore.GetClaimsAsync(IdentityUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.GetClaimsAsync(TUser user)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`2.GenerateClaimsAsync(TUser user)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at Volo.Abp.Identity.AbpUserClaimsPrincipalFactory.CreateAsync(IdentityUser user)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at IdentityServer4.AspNetIdentity.UserClaimsFactory`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.SignInManager`1.CreateUserPrincipalAsync(TUser user)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator`1.SecurityStampVerified(TUser user, CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator`1.ValidateAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Dxp.AspNetCore.Authentication.IdentitiesAuthenticationMiddleware.Invoke(HttpContext context) in D:\MyProjects\x-zhengzhou-hkg\src\framework\AspNetCore\Dxp.AspNetCore.Mvc\Dxp\AspNetCore\Authentication\IdentitiesAuthenticationMiddleware.cs:line 59
   at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.ExecuteWithFilterAsync(IHttpSocketAdapter injectScriptSocket, String requestId, HttpContext httpContext)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

* Steps needed to **reproduce** the problem.
```
context.Services
                .AddAuthentication(o =>
                {
                    o.DefaultScheme = IdentityConstants.ApplicationScheme;
                    o.DefaultSignInScheme = IdentityConstants.ApplicationScheme;
                })
                .AddCookie(GmsAccountConstants.MemberAuthenticationScheme, option =>
                {
                    option.Cookie.Name = "MemberAuth";
                    option.LoginPath = new PathString("/Member/Account/Login");
                    option.ExpireTimeSpan = TimeSpan.FromMinutes(144000);
                    option.AccessDeniedPath = "/Member/Account/AccessDenied";
                    option.LogoutPath = "/Member/Account/Logout";
                })
                .AddIdentityCookies(a =>
                {
                    a.ApplicationCookie.Configure(opt =>
                    {
                        opt.Cookie.Name = "AdminAuth";
                        opt.LoginPath = "/Admin/Account/Login";
                        opt.LogoutPath = "/Admin/Account/Logout";
                        opt.AccessDeniedPath = "/Admin/Account/AccessDenied";
                    });
                });
```
Always I clear my local cookie, it works fine again. but after the session time out, the error will occour again.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpSecurityStampValidator.cs#L13
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpIdentityAspNetCoreModule.cs#L26-L28

**Comment by gaojianzhuang** [comment]
> https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpSecurityStampValidator.cs#L13
> 
> 
> https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpIdentityAspNetCoreModule.cs#L26-L28

Thanks. You mean the "AbpSecurityStampValidator" class cause this issue, right?

**Comment by gaojianzhuang** [comment]
Thanks so much. It works fine for me. I have added these codes in the identity project.
