### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/@fortawesome/fontawesome-free/css/all.css' for the bundle 'Blazor.LeptonTheme.Global'!

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#12966]
* Your **ABP Framework version**: 5.2.2 (Stable)
* Your **User Interface**: Blazor-Server
* Your database provider(EF Core/MongoDB): EF Core

To reproduce:

1. Create a new solution with Abp Suite. Use the following settings:
    - Template type: Application template
    - UI framework: Blazor Server
    - Mobile: None
    - Database provider: Entity Framework Core
    - Database management system: SQLServer
    - Public web site: No
    - Separated tenant schema: Yes
    - Tiered: No
    - Preview version: Yes / No (tried both)
2. Execute _abp install-libs_ in Blazor project
3. Start Blazor App

Stack Trace:

> **Volo.Abp.AbpException: Could not find the bundle file '/libs/@fortawesome/fontawesome-free/css/all.css' for the bundle 'Blazor.LeptonTheme.Global'!**
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AbpTemp.Blazor.Pages._Pages__Host.<ExecuteAsync>b__16_0() in D:\Projects\Concurrent\CONAG_AbpPlayground\Source\AbpTemp\src\AbpTemp.Blazor\Pages\_Host.cshtml:line 20
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AbpTemp.Blazor.Pages._Pages__Host.ExecuteAsync() in D:\Projects\Concurrent\CONAG_AbpPlayground\Source\AbpTemp\src\AbpTemp.Blazor\Pages\_Host.cshtml:line 13
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I compared the solution with another (working) one that I did not generate via AbpSuite but downloaded for free (basic theme). There were some additional libs installed, which were not installed in the commercial version. For example, the following libs are present in the working solution and are missing in this faulty solution:
- @fortawesome
- abp
- bootstrap
- datatables.net
- jquery-form
- ...

I then added the two lines of the basic theme in the package.json in addition to the lepton theme. Then the appropriate libs were loaded and I could run the application correctly.
```
{
  "version": "1.0.0",
  "name": "my-app",
  "private": true,
  "dependencies": {
    **"@abp/aspnetcore.mvc.ui.theme.basic": "^5.2.2",
    "@abp/aspnetcore.components.server.basictheme": "^5.2.2",**
    "@volo/abp.aspnetcore.mvc.ui.theme.lepton": "^5.2.2",
    "@volo/abp.aspnetcore.components.server.leptontheme": "^5.2.2",
    "@volo/cms-kit-pro.admin": "^5.2.2",
    "@volo/account": "^5.2.2"
  }
}
```

**Comment by realLiangshiwei** [comment]
There is no problem when I use the ABP suite to create a new project.

![image](https://user-images.githubusercontent.com/16813853/173035621-957fd588-e528-4688-aa00-b003e8386211.png)

**Comment by maliming** [comment]
> Execute abp install-libs in Blazor project

What's the command output?

**Comment by ageiter** [comment]
Now this is interesting... I just ran the command again, but now yarn was used and not npm. And with yarn all libs are loaded correctly too. 

Who decides if npm or yarn is used?

**Comment by realLiangshiwei** [comment]
If you are installed both NPM and Yarn, we will use yarn to restore packages first.

https://github.com/abpframework/abp/blob/6df284811992ea279727281a1befe0975b0d12a0/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/LIbs/InstallLibsService.cs#L81-L90

**Comment by ageiter** [comment]
This was the output with npm:

> PM> abp install-libs
[10:57:20 INF] ABP CLI (https://abp.io)
[10:57:20 INF] Version 5.2.2 (Stable)
[10:57:21 INF] Found 1 projects.
[10:57:21 INF] ...\AbpTemp\src\AbpTemp.Blazor
[10:57:21 INF] Running npm install on ...\AbpTemp\src\AbpTemp.Blazor
abp : npm WARN bootstrap@5.1.3 requires a peer of @popperjs/core@^2.10.2 but none is installed. You must install peer dependencies yourself.
At line:1 char:1
+ abp install-libs
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN bootst...ncies yourself.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm WARN bootstrap@5.1.3 requires a peer of @popperjs/core@^2.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 528 packages in 1.338s

11 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (1 low, 6 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by maliming** [comment]
Please install the `yarn` and re-run the command.

https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable

**Comment by ageiter** [comment]
Thank you, yes that works. 

But would be probably useful, if this would also work with npm, if that is to be supported further.
