### ISSUE TITLE
Unhandled exception when changing language (LeptonXLite with SyncfusionBlazor)

### ISSUE THREAD

**Issue by cld0815** [abpframework/abp#13015]
ABP Framework version : 5.3.0
UI : Blazor Server / LeptonXLite Theme (1.0.0-beta.2)

In default, It run normally.
but when I add [SyncfusionBlazor](https://www.syncfusion.com/blazor-components) as below
public override void ConfigureServices(ServiceConfigurationContext context)
{
        ...
        ConfigureMenu(context);
        context.Services.AddSyncfusionBlazor(); // add this
}

Exception occurred when change language:

[21:58:32 WRN] Unhandled exception rendering component: 'RemoteNavigationManager' has not been initialized.
System.InvalidOperationException: 'RemoteNavigationManager' has not been initialized.
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
   at Microsoft.AspNetCore.Components.NavigationManager.get_Uri()
   at Volo.Abp.AspNetCore.Components.Server.LeptonXLiteTheme.Languages.LanguageBlazorServerManager.ChangeAsync(LanguageInfo newLanguage)
   at Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite.Toolbar.LanguageSwitchComponent.<>c__DisplayClass5_0.<BuildRenderTree>b__0()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
[21:58:32 ERR] Unhandled exception in circuit 'eNaRliVmLEjI39KZIwLFYyAJNp72OMlt7PrI_EewliY'.
System.InvalidOperationException: 'RemoteNavigationManager' has not been initialized.
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
   at Microsoft.AspNetCore.Components.NavigationManager.get_Uri()
   at Volo.Abp.AspNetCore.Components.Server.LeptonXLiteTheme.Languages.LanguageBlazorServerManager.ChangeAsync(LanguageInfo newLanguage)
   at Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite.Toolbar.LanguageSwitchComponent.<>c__DisplayClass5_0.<BuildRenderTree>b__0()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)

**Comment by cld0815** [comment]
same exception found in github : 
https://github.com/jspuij/TwokaB/issues/31

**Comment by cld0815** [comment]
Can anyone help me?

**Comment by cld0815** [comment]
help

**Comment by jcruzram** [comment]
Same issue in version 6.0.0-rc.1

ABP Framework version : 6.0.0-rc.1
UI : Blazor Server / LeptonXLite Theme (1.0.0-rc.1)

I tried it with the basic theme and it works fine. The error occurs only with the Lepton theme (LeptonXLite in my case) and syncfusion versions 19.x.x, 20.x.x

To reproduce the error:
dotnet tool update Volo.Abp.Cli -g --version 6.0.0-rc.1
abp new Acme.BookStore -u blazor-server --preview
run migrations
Add syncfusion.blazor.Grid Nuget package
add @using Syncfusion.Blazor to _imports.razor file
add
context.Services.AddSyncfusionBlazor();
in ConfigureServicesmethod of BlazorModule class
Run the application, login and try another language.
