### ISSUE TITLE
adding lepton theme with source code Cannot find builder "@angular-devkit/build-angular:tslint"

### ISSUE THREAD

**Issue by dontboyle** [abpframework/abp#13038]
Repro Steps:

Create new project:
dotnet tool uninstall -g Volo.Abp.Cli
dotnet tool install -g Volo.Abp.Cli --version 5.1.3

abp new TestProject -t app-pro -u angular -m none --database-provider ef -csf --version 5.1.3

abp add-package @volo/abp.ng.theme.lepton --with-source-code --version 5.1.3

open angular project via cmd line /angular folder and run:
- yarn / npm install
- ng lint

An unhandled exception occurred: Cannot find builder "@angular-devkit/build-angular:tslint".
See "C:........\angular-errors.log" for further details.

File:

[error] Error: Cannot find builder "@angular-devkit/build-angular:tslint".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder \node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:125:19)
    at LintCommand.runSingleTarget angular\node_modules\@angular\cli\models\architect-command.js:245:53)
    at async LintCommand.runArchitectTarget \angular\node_modules\@angular\cli\models\architect-command.js:290:31)
    at async LintCommand.run \angular\node_modules\@angular\cli\models\architect-command.js:236:16)
    at async LintCommand.validateAndRun \angular\node_modules\@angular\cli\models\command.js:136:22)
    at async runCommand \angular\node_modules\@angular\cli\models\command-runner.js:224:24)
    at async default_1 \angular\node_modules\@angular\cli\lib\cli\index.js:70:31)

Tried things like: https://stackoverflow.com/questions/50333003/could-not-find-module-angular-devkit-build-angular/53437950 
without success

**Comment by dontboyle** [comment]
To get lint working right:

`abp add-package @volo/abp.ng.theme.lepton --with-source-code --version 5.1.3`
`ng add @angular-eslint/schematics`

 *RUN EVEN THOUGH ABOVE CMD SAYS IT IS GOING TO RUN IT*

`ng g @angular-eslint/schematics:convert-tslint-to-eslint volo-abp.ng.theme.lepton`
`No`
`Yes`

`ng lint`
