### ISSUE TITLE
Adding account module "replace package with source code" throws error

### ISSUE THREAD

**Issue by dontboyle** [abpframework/abp#13124]
New Project created via abp suite (v 5.3.0). Enterprise License.

Installing each module by clicking "yes" on every popup.

Unsuccessful module installs:
**Account**/**SaaS**                                                                             - Replace package with sourcecode
**Payment**/**Chat**/**File Management**/**CMS Kit**/**Forms**/**Twilio SMS**   - Add as Project

Could not find a class derived from AbpModule in the project c:\src\EF\aspnet-core\src\EF.Application\EF.Application.csproj

Example error from Account Module:

`
 Determining projects to restore...
  Writing C:\Users\Don\AppData\Local\Temp\tmp1198.tmp
info : Adding PackageReference for package 'Volo.Abp.Account.Pro.Admin.Application' into project 'c:\src\EF\aspnet-core\src\EF.Application\EF.Application.csproj'.
info : Restoring packages for c:\src\EF\aspnet-core\src\EF.Application\EF.Application.csproj...
info : Package 'Volo.Abp.Account.Pro.Admin.Application' is compatible with all the specified frameworks in project 'c:\src\EF\aspnet-core\src\EF.Application\EF.Application.csproj'.
error: Value cannot be null. (Parameter 'path1')

Usage: NuGet.CommandLine.XPlat.dll package add [options]

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --package               Id of the package to be added.
  --version               Version of the package to be added.
  -d|--dg-file            Path to the dependency graph file to be used to restore preview and compatibility check.
  -p|--project            Path to the project file.
  -f|--framework          Frameworks for which the package reference should be added.
  -n|--no-restore         Do not perform restore preview and compatibility check. The added package reference will be unconditional.
  -s|--source             Specifies NuGet package sources to use during the restore.
  --package-directory     Directory to restore packages in.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  --prerelease            Allows prerelease packages to be installed.
[11:21:40 ERR] Error occured while adding the module Volo.Account.Prowith source-code to the solution "5fc2e13e-48e3-4699-aee7-3dbd3af26ea6".. Volo.Abp.Cli.CliUsageException: Could not find a class derived from AbpModule in the project c:\src\EF\aspnet-core\src\EF.Application\EF.Application.csproj
   at Volo.Abp.Cli.ProjectModification.ProjectNugetPackageAdder.AddAsPackageReference(String projectFile, NugetPackageInfo package, String version, Boolean useDotnetCliToInstall) in D:\ci\Jenkins\workspace\abp-commercial-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs:line 300
   at Volo.Abp.Cli.ProjectModification.ProjectNugetPackageAdder.AddAsync(String solutionFile, String projectFile, NugetPackageInfo package, String version, Boolean useDotnetCliToInstall, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile) in D:\ci\Jenkins\workspace\abp-commercial-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs:line 114
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddNugetAndNpmReferences(ModuleWithMastersInfo module, String[] projectFiles, Boolean useDotnetCliToInstall) in D:\ci\Jenkins\workspace\abp-commercial-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 548
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddAsync(String solutionFile, String moduleName, String version, Boolean skipDbMigrations, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-commercial-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 105
   at Volo.Abp.Cli.Commands.AddModuleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-commercial-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\AddModuleCommand.cs:line 68
   at Volo.Abp.Suite.Controllers.AbpSuiteController.AddModuleAsync(AddModuleInput input)
`

For very custom websites, can just add a way to add packages/source code during project creation?
This would of course work too, but seems has been broken since 5.1 for me. (have not tested prior to 5.1)

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/
