### ISSUE TITLE
Can not create project template using the latest Volo.Abp.Cli(0.18.0-preview20190619)

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1324]
Error message:

 Remote server returns error! HTTP status code: NotFound
System.Exception: Remote server returns error! HTTP status code: NotFound
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetLatestTemplateVersionAsync(String name) in /var/lib/jenkins/workspace/abp.io-nightly/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/AbpIoTemplateStore.cs:line 96
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetAsync(String name, DatabaseProvider databaseProvider, String projectName, String version) in /var/lib/jenkins/workspace/abp.io-nightly/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/AbpIoTemplateStore.cs:line 46
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args) in /var/lib/jenkins/workspace/abp.io-nightly/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/ProjectBuilder.cs:line 39
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in /var/lib/jenkins/workspace/abp.io-nightly/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/NewCommand.cs:line 38
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in /var/lib/jenkins/workspace/abp.io-nightly/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/CliService.cs:line 57

**Comment by maliming** [comment]
The 0.18.0 version of the website has not been officially published.
