### ISSUE TITLE
Error in Blazor PWA when published (Azure) but not Locally

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#13284]
I have followed the [Blazor PWA guide ](https://docs.abp.io/en/abp/latest/UI/Blazor/Pwa-Configuration) in details and can get the **install button** when debugging on localhost.

But when I release the app I don´t get the install button but what I get is this error

```
Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:22:54
    at async onInstall (service-worker.js:22:5)
(anonymous) @ service-worker.js:22
```

pointing to this error in the published service-worker.js

![image](https://user-images.githubusercontent.com/2386572/178345739-29f66f62-0b77-4a36-819b-90674b394055.png)

 I know that localhost uses `service-worker.js` code but when published the code from `service-worker.published.js` is used and it seems to be pointing to some issue with the content of my service-worker-assets.js but I can´t figure it out by looking at it.

Here is my service-worker-assets.js (had to change the ending to log so I could upload it)
[service-worker-assets.log](https://github.com/abpframework/abp/files/9087133/service-worker-assets.log)

Do you have any idea what this might be  @EngincanV (since you did the docs)? 

p.s
I´m adding try/catch over that code to hopefully get more error details. 

* **ABP Framework version** 5.3.1
* **User Interface** Blazor
* **Separate IdentityServer**

**Comment by sturlath** [comment]
OK I don´t know what happened but with this change (added try catch log) everything seems to have started to work 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/2386572/178354934-9d42ee58-b09f-4dba-91f4-70d4b0c57cbe.png">

There is no error log in the console so it must have kicked off some browser reset I guess...  so if people have this issue it might be enough to 'touch' the `service-worker.published.js` file. I´m at least closing this for now.
