### ISSUE TITLE
MVC template and other project unit tests are error under netcoreapp2.2

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1333]
If you change the TargetFramework of the unit test project from netcoreapp2.0 to netcoreapp2.2, an error will occur.

Recurring this problem is very simple.
Such as the Identity module.

The build project will have a warning:
```
Build succeeded.
                                                                                                                                                                                            t
C:\Program Files\dotnet\sdk\2.2.202\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Linq.Dynamic.Core" that could no\Vt be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [***\modules\identity\test\Volo.Abp.Identity.MongoDB.Tests\Volo.Abp.Identity.MongoDB.Tests.csproj]                                                                                                                                                  t
C:\Program Files\dotnet\sdk\2.2.202\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Linq.Dynamic.Core" that could norkt be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [***\modules\identity\test\Volo.Abp.Identity.EntityFrameworkCore.Tests\Volo.Abp.Identity.EntityFrameworkCore.Tests.csproj]                                                                                                                          t
C:\Program Files\dotnet\sdk\2.2.202\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Linq.Dynamic.Core" that could noVot be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [***\modules\identity\test\Volo.Abp.Identity.Domain.Tests\Volo.Abp.Identity.Domain.Tests.csproj]                                                                                                                                                    o
Volo\Abp\Identity\Distributed_User_Change_Event_Tests.cs(31,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator tp.o await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [***\modules\identity\test\Volo.Abp.Identity.Domain.Tests\Volo.Abp.Identity.Domain.Tests.csproj]                                                                                                                                                           t
C:\Program Files\dotnet\sdk\2.2.202\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "System.Linq.Dynamic.Core" that could noest be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [***\modules\identity\test\Volo.Abp.Identity.Application.Tests\Volo.Abp.Identity.Application.Tests.csproj]
    5 Warning(s)
    0 Error(s)
```

Running the unit test project will have errors:

**System.IO.FileNotFoundException : Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.17.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.**

```
[xUnit.net 00:00:04.58]     Volo.Abp.Identity.EntityFrameworkCore.IdentityUserRepository_Tests.GetListAsync [FAIL]
Failed   Volo.Abp.Identity.EntityFrameworkCore.IdentityUserRepository_Tests.GetListAsync
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.17.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
Stack Trace:
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, String filter, Boolean includeDetails, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, String filter, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.Proxies.Invocations.IIdentityUserRepository_GetListAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync() in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapter.cs:line 55
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in ***\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 46
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 82
   at Volo.Abp.Identity.IdentityUserRepository_Tests`1.GetListAsync() in ***\modules\identity\test\Volo.Abp.Identity.TestBase\Volo\Abp\Identity\IdentityUserRepository_Tests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:04.70]     Volo.Abp.Identity.EntityFrameworkCore.IdentityRoleRepository_Tests.GetListAsync [FAIL]
Failed   Volo.Abp.Identity.EntityFrameworkCore.IdentityRoleRepository_Tests.GetListAsync
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.17.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
Stack Trace:
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityRoleRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, Boolean includeDetails, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityRoleRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.Proxies.Invocations.IIdentityRoleRepository_GetListAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync() in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapter.cs:line 55
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in ***\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 46
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 82
   at Volo.Abp.Identity.IdentityRoleRepository_Tests`1.GetListAsync() in ***\modules\identity\test\Volo.Abp.Identity.TestBase\Volo\Abp\Identity\IdentityRoleRepository_Tests.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.06]     Volo.Abp.Identity.MongoDB.IdentityRoleRepository_Tests.GetListAsync [FAIL]
Failed   Volo.Abp.Identity.MongoDB.IdentityRoleRepository_Tests.GetListAsync
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.17.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
Stack Trace:
   at Volo.Abp.Identity.MongoDB.MongoIdentityRoleRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, Boolean includeDetails, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Volo.Abp.Identity.MongoDB.MongoIdentityRoleRepository.GetListAsync(String sorting, Int32 maxResultCount, Int32 skipCount, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.Proxies.Invocations.IIdentityRoleRepository_GetListAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync() in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapter.cs:line 55
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in ***\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 46
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in ***\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 82
   at Volo.Abp.Identity.IdentityRoleRepository_Tests`1.GetListAsync() in ***\modules\identity\test\Volo.Abp.Identity.TestBase\Volo\Abp\Identity\IdentityRoleRepository_Tests.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by hikalkan** [comment]
This may be related to https://github.com/StefH/System.Linq.Dynamic.Core/issues/278

**Comment by hikalkan** [comment]
I will downgrade to 1.0.16.

**Comment by StefH** [comment]
A new NuGet version 1.0.18 is uploaded which fixes this issue.

Issue was maybe related to https://stackoverflow.com/questions/52866794/why-doesnt-directory-build-props-work-when-building-a-solution-using-visual-stu
