### ISSUE TITLE
Mongo group by then select first in each group

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13349]
ABP v5.3

```c#
public async Task<ListResultDto<EquipmentOeeDto>> GetListAsync(EquipmentOeeGetListInput input)
{
    var queryable = (await _equipmentOeeRepository.GetMongoQueryableAsync())
        .Where(!input.DeviceType.IsNullOrWhiteSpace(), x => x.DeviceType == input.DeviceType);

    var query = from o in queryable
        group o by new {o.TenantName, o.DeviceType, o.Version}
        into grp
        select grp.OrderByDescending(x => x.Version).First();

    return new ListResultDto<EquipmentOeeDto>(
        ObjectMapper.Map<List<EquipmentOee>, List<EquipmentOeeDto>>(
            await AsyncExecuter.ToListAsync(query)
        )
    );
}
```

```c#
[16:57:14 ERR] The method OrderByDescending is not supported in the expression tree: {document}.OrderByDescending(x => x.Version).
System.NotSupportedException: The method OrderByDescending is not supported in the expression tree: {document}.OrderByDescending(x => x.Version).
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.Bind(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindPipeline(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.Bind(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.EmbeddedPipeline.EmbeddedPipelineBinder.Bind(Expression node, IBindingContext parent)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.BindEmbeddedPipeline(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.Visit(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.Bind(Expression node, IBindingContext context, Boolean isClientSideProjection)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBindingContext.Bind(Expression node, Boolean isClientSideProjection)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBindingContext.Bind(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.MethodCallBinders.SelectBinder.Bind(PipelineExpression pipeline, PipelineBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.MethodInfoMethodCallBinder`1.Bind(PipelineExpression pipeline, TBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.Bind(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.PipelineBinder.Bind(Expression node, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Prepare(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Translate(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryableImpl`2.ToCursorAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Jee.Biw.ExpertDatabase.EquipmentOeeAppService.GetListAsync(EquipmentOeeGetListInput input) in E:\jee-cn\Im-App-Services\aspnet-core\src\modules\ExpertDatabase\Jee.Biw.ExpertDatabase.Application\EquipmentOeeAppService.cs:lin
e 30
   at lambda_method1582(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by realLiangshiwei** [comment]
**The method OrderByDescending is not supported in the expression tree: {document}.OrderByDescending(x => x.Version).**

This has nothing to do with ABP, you can check the MongoDB document: https://mongodb.github.io/mongo-csharp-driver/2.17/
