### ISSUE TITLE
Having issues while running ehopApp/PublicWeb application, throwing Badgateway exception.

### ISSUE THREAD

**Issue by qaiser-comm-it** [abpframework/abp#13360]
I have pulled the EshopApp application and trying to run by following the documentation posted here:

https://github.com/abpframework/eShopOnAbp

Here everything is running perfectly only PublicWeb is having issues, everytime I am running it, throws Badgateway exception.

Please look into this and provide the solution? 

![Screenshot (43)](https://user-images.githubusercontent.com/99240665/180222885-29b4a058-9f4a-4a76-bb6b-0a4e0fc99dc7.png)

**Comment by realLiangshiwei** [comment]
What's the error log?

And, did you run the `WebPublicGateway` project?

**Comment by qaiser-comm-it** [comment]
Yes, WebpublicGateway is running at port 44373 and below is the log


2022-07-21 19:03:37.029 +05:30 [INF] Starting EShopOnAbp.PublicWeb.
2022-07-21 19:03:41.247 +05:30 [INF] Loaded ABP modules:
2022-07-21 19:03:41.248 +05:30 [INF] - EShopOnAbp.PublicWeb.EShopOnAbpPublicWebModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.Caching.StackExchangeRedis.AbpCachingStackExchangeRedisModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.Caching.AbpCachingModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Threading.AbpThreadingModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Serialization.AbpSerializationModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Uow.AbpUnitOfWorkModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Data.AbpDataModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.Validation.AbpValidationAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Security.AbpSecurityModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Json.AbpJsonModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Timing.AbpTimingModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.Localization.AbpLocalizationModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.Settings.AbpSettingsModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.EventBus.RabbitMq.AbpEventBusRabbitMqModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.EventBus.AbpEventBusModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Guids.AbpGuidsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.RabbitMQ.AbpRabbitMqModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.AspNetCore.Mvc.Client.AbpAspNetCoreMvcClientModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.AspNetCore.Mvc.Client.AbpAspNetCoreMvcClientCommonModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Http.Client.AbpHttpClientModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Http.AbpHttpModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.Http.AbpHttpAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.Minify.AbpMinifyModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Castle.AbpCastleCoreModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Validation.AbpValidationModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Application.AbpDddApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.Auditing.AbpAuditingContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Authorization.AbpAuthorizationModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Features.AbpFeaturesModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.AspNetCore.Authentication.OpenIdConnect.AbpAspNetCoreAuthenticationOpenIdConnectModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.AspNetCore.Authentication.OAuth.AbpAspNetCoreAuthenticationOAuthModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.Http.Client.IdentityModel.Web.AbpHttpClientIdentityModelWebModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.Http.Client.IdentityModel.AbpHttpClientIdentityModelModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.IdentityModel.AbpIdentityModelModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.AbpAspNetCoreMvcUiBasicThemeModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.AbpAspNetCoreMvcUiThemeSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.AbpAspNetCoreMvcUiBootstrapModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.AspNetCore.Mvc.UI.AbpAspNetCoreMvcUiModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.AspNetCore.AbpAspNetCoreModule
2022-07-21 19:03:41.248 +05:30 [INF]               - Volo.Abp.Auditing.AbpAuditingModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.UI.Navigation.AbpUiNavigationModule
2022-07-21 19:03:41.248 +05:30 [INF]               - Volo.Abp.UI.AbpUiModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2022-07-21 19:03:41.248 +05:30 [INF]             - Volo.Abp.Application.AbpDddApplicationModule
2022-07-21 19:03:41.248 +05:30 [INF]               - Volo.Abp.Domain.AbpDddDomainModule
2022-07-21 19:03:41.248 +05:30 [INF]                 - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2022-07-21 19:03:41.248 +05:30 [INF]                 - Volo.Abp.Specifications.AbpSpecificationsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Packages.AbpAspNetCoreMvcUiPackagesModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingAbstractionsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpAspNetCoreMvcUiWidgetsModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.Account.AbpAccountHttpApiClientModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.Account.AbpAccountApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Identity.AbpIdentityDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.Users.AbpUsersDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.Users.AbpUsersAbstractionModule
2022-07-21 19:03:41.248 +05:30 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]           - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.Shared.Hosting.AspNetCore.EShopOnAbpSharedHostingAspNetCoreModule
2022-07-21 19:03:41.248 +05:30 [INF]     - EShopOnAbp.Shared.Hosting.EShopOnAbpSharedHostingModule
2022-07-21 19:03:41.248 +05:30 [INF]       - Volo.Abp.Autofac.AbpAutofacModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.Swashbuckle.AbpSwashbuckleModule
2022-07-21 19:03:41.248 +05:30 [INF]     - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.EShopOnAbpSharedLocalizationModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.CatalogService.CatalogServiceHttpApiClientModule
2022-07-21 19:03:41.248 +05:30 [INF]     - EShopOnAbp.CatalogService.CatalogServiceApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]       - EShopOnAbp.CatalogService.CatalogServiceDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]         - EShopOnAbp.OrderingService.OrderingServiceDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]           - EShopOnAbp.PaymentService.PaymentServiceDomainSharedModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.BasketService.BasketServiceContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.OrderingService.OrderingServiceHttpApiClientModule
2022-07-21 19:03:41.248 +05:30 [INF]     - EShopOnAbp.OrderingService.OrderingServiceApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.AspNetCore.SignalR.AbpAspNetCoreSignalRModule
2022-07-21 19:03:41.248 +05:30 [INF]   - EShopOnAbp.PaymentService.PaymentServiceHttpApiClientModule
2022-07-21 19:03:41.248 +05:30 [INF]     - EShopOnAbp.PaymentService.PaymentServiceApplicationContractsModule
2022-07-21 19:03:41.248 +05:30 [INF]   - Volo.Abp.AutoMapper.AbpAutoMapperModule
2022-07-21 19:03:41.960 +05:30 [INF] Loading proxy data from config.
2022-07-21 19:03:42.043 +05:30 [DBG] Destination 'destination1' has been added.
2022-07-21 19:03:42.058 +05:30 [DBG] New client created for cluster 'cluster1'.
2022-07-21 19:03:42.059 +05:30 [DBG] Cluster 'cluster1' has been added.
2022-07-21 19:03:42.068 +05:30 [DBG] Route 'route1' has been added.
2022-07-21 19:03:42.074 +05:30 [INF] Initialized all ABP modules.
2022-07-21 19:03:42.383 +05:30 [INF] Application started. Press Ctrl+C to shut down.
2022-07-21 19:03:42.390 +05:30 [INF] Hosting environment: Development
2022-07-21 19:03:42.390 +05:30 [INF] Content root path: E:\_Projects\eShopOnAbp\apps\public-web\src\EShopOnAbp.PublicWeb\
2022-07-21 19:03:42.406 +05:30 [INF] Request starting HTTP/2 GET https://localhost:44335/ - -
2022-07-21 19:03:52.406 +05:30 [WRN] Could not find IdentityClientConfiguration for AbpMvcClient. Either define a configuration for AbpMvcClient or set a default configuration.
2022-07-21 19:03:52.417 +05:30 [INF] Start processing HTTP request GET "https://localhost:44373/api/abp/application-configuration?api-version=1.0"
2022-07-21 19:03:52.418 +05:30 [INF] Sending HTTP request GET "https://localhost:44373/api/abp/application-configuration?api-version=1.0"
2022-07-21 19:03:52.613 +05:30 [INF] Received HTTP response headers after 190.885ms - 502
2022-07-21 19:03:52.614 +05:30 [INF] End processing HTTP request after 203.2064ms - 502
2022-07-21 19:03:52.629 +05:30 [ERR] An unhandled exception has occurred while executing the request.
Volo.Abp.Http.Client.AbpRemoteCallException: Bad Gateway
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync(ClientProxyRequestContext requestContext)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync[T](ClientProxyRequestContext requestContext)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync[T](String methodName, ClientProxyRequestTypeValue arguments)
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies.AbpApplicationConfigurationClientProxy.GetAsync()
   at Volo.Abp.AspNetCore.Mvc.Client.MvcCachedApplicationConfigurationClient.<GetAsync>b__14_0()
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)
   at Volo.Abp.AspNetCore.Mvc.Client.MvcCachedApplicationConfigurationClient.GetAsync()
   at Volo.Abp.AspNetCore.Mvc.Client.RemoteLanguageProvider.GetLanguagesAsync()
   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync()
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-07-21 19:03:52.789 +05:30 [INF] Request finished HTTP/2 GET https://localhost:44335/ - - - 500 - text/html;+charset=utf-8 10382.4851ms
2022-07-21 19:03:52.833 +05:30 [INF] Request starting HTTP/2 GET https://localhost:44335/_framework/aspnetcore-browser-refresh.js - -
2022-07-21 19:03:52.848 +05:30 [INF] Request finished HTTP/2 GET https://localhost:44335/_framework/aspnetcore-browser-refresh.js - - - 200 11998 application/javascript;+charset=utf-8 13.8819ms

**Comment by qaiser-comm-it** [comment]
All the other services are running through TYE, only this publicweb is giving bad gateway exception
