### ISSUE TITLE
An internal error occurred during your request! returned instead of user friendly exception message

### ISSUE THREAD

**Issue by pepearreola** [abpframework/abp#13413]
When throwing a user friendly exception from a plain function in appservice, the error message returned is _An internal error occurred during your request!_ instead of the error message inside the user friendly exception.

The problem is that the framework is throwing a **DidNotCallCompleteMethodExceptionMessage** exception

* Framework version **Abp 7.2.1**.
* Database provider **EF Core**
* Exception message and stack trace.

_Abp.AbpException: Did not call Complete method of a unit of work.
   at Abp.Domain.Uow.InnerUnitOfWorkCompleteHandle.Dispose() in \abp\Abp\Domain\Uow\InnerUnitOfWorkCompleteHandle.cs:line 47
   at Abp.AspNetCore.Mvc.Uow.AbpUowActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in \abp\Abp.AspNetCore\AspNetCore\Mvc\Uow\AbpUowActionFilter.cs:line 51
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)_

* Steps needed to **reproduce** the problem.

- Use the following function into an appService 

```
public class TestAppService: AppServiceExtended
    {
        public void DoSomething()
        {
            throw new UserFriendlyException("whatever");
        }
    }
```
When calling the function DoSomething, the developer expects to get the following exception:

{
    "result": null,
    "targetUrl": null,
    "success": false,
    "error": {
        "code": 0,
        "message": **"whatever"**,
        "details": null,
        "validationErrors": null
    },
    "unAuthorizedRequest": false,
    "__abp": true
}

But the following exception is returned instead:

{
    "result": null,
    "targetUrl": null,
    "success": false,
    "error": {
        "code": 0,
        "message": **"An internal error occurred during your request!",**
        "details": null,
        "validationErrors": null
    },
    "unAuthorizedRequest": false,
    "__abp": true
}

**Comment by pepearreola** [comment]
moving to aspnetboilerplate repo
