### ISSUE TITLE
can not return a dictionary 

### ISSUE THREAD

**Issue by Qlimax2009** [abpframework/abp#13552]
ABP：5.1.4

I return a dictionary  value  `Dictionary<emun, List<Dto>> `  in my APPservice，it made the following error
```
System.NotSupportedException: The type 'UIH.Rt.Emr.Enums.ConfigurablePropertyName' is not a supported dictionary key using converter of type 'Volo.Abp.Json.SystemTextJson.JsonConverters.AbpStringToEnumConverter`1[UIH.Rt.Emr.Enums.ConfigurablePropertyName]'. The unsupported member type is located on type 'System.Collections.Generic.List`1[UIH.Rt.Emr.ConfigurableProperty.Dto.ConfigurablePropertyDto]'. Path: $.
 ---> System.NotSupportedException: The type 'UIH.Rt.Emr.Enums.ConfigurablePropertyName' is not a supported dictionary key using converter of type 'Volo.Abp.Json.SystemTextJson.JsonConverters.AbpStringToEnumConverter`1[UIH.Rt.Emr.Enums.ConfigurablePropertyName]'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyNameCore(Utf8JsonWriter writer, T value, JsonSerializerOptions options, Boolean isWritingExtensionDataProperty)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
```

Whether the return value `Dictionary<emun, List<Dto>> `  in this format is not supported？

**Comment by maliming** [comment]
This is related to `System.Text.Json` not abp. Try to without abp.

**Comment by maliming** [comment]
hi

Please share some code to reproduce?

**Comment by Qlimax2009** [comment]
> hi
> 
> Please share some code to reproduce?

```
 public class ConfigurablePropertyAppService : EmrAppService, IConfigurablePropertyAppService
{
       public virtual async Task<Dictionary<ConfigurablePropertyName, List<ConfigurablePropertyDto>>> GetAsync()
        {
            var result = new Dictionary<ConfigurablePropertyName, List<ConfigurablePropertyDto>>();
            ...
            return result;
        }
}

public enum ConfigurablePropertyName
{
...
}
```

**Comment by maliming** [comment]
Can you try that in asp net core without abp?

**Comment by Qlimax2009** [comment]
> 

There were no errors in asp net core without abp, 
it cause by the `AbpStringToEnumConverter`
