### ISSUE TITLE
Couldn't get resource at '*.cs.json' error

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#13699]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**. 5.3.3
* Your **User Interface** type (Angular)
* Your database provider(EF Core)
* Exception message and **stack trace** if available (check the logs).
* 2022-08-11 14:09:48.066 +03:00 [ERR] Couldn't get resource at 'MyCompany.MyProject.MyModule.Localization.MyModule.cs.json'.
System.InvalidOperationException: Couldn't get resource at 'MyCompany.MyProject.MyModule.Localization.MyModule.cs.json'.
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo.GetManifestResourceStream()
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo.CreateReadStream()
   at Volo.Abp.Localization.VirtualFiles.VirtualFileLocalizationResourceContributorBase.CreateDictionaryFromFile(IFileInfo file)
   at Volo.Abp.Localization.VirtualFiles.VirtualFileLocalizationResourceContributorBase.CreateDictionaries()
   at Volo.Abp.Localization.VirtualFiles.VirtualFileLocalizationResourceContributorBase.GetDictionaries()
   at Volo.Abp.Localization.VirtualFiles.VirtualFileLocalizationResourceContributorBase.Fill(String cultureName, Dictionary`2 dictionary)
   at Volo.Abp.Localization.LocalizationResourceContributorList.Fill(String cultureName, Dictionary`2 dictionary)
   at Volo.Abp.Localization.AbpDictionaryBasedStringLocalizer.GetAllStrings(String cultureName, Boolean includeParentCultures, Boolean includeBaseLocalizers)
   at Microsoft.Extensions.Localization.StringLocalizer`1.GetAllStrings(Boolean includeParentCultures)
   at Microsoft.Extensions.Localization.StringLocalizerExtensions.GetAllStrings(IStringLocalizer stringLocalizer)
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationAppService.GetLocalizationConfigAsync()
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationAppService.GetAsync()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync()
   at lambda_method3369(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

* Steps needed to **reproduce** the problem.

![image](https://user-images.githubusercontent.com/13360669/184650217-62770a26-3f1d-4773-a288-cd2259a9e8b1.png)

MyCompany.MyProject.MyModule.Domain.Shared.csproj:

```
<ItemGroup>
    <EmbeddedResource Include="Localization\MyModule\*.json" />
    <Content Remove="Localization\MyModule\*.json" />
  </ItemGroup>
```

I got this error. After I run delete_bin_obj.bat and rebuild sometimes project runs without errors. Sometimes problem exists

**Comment by maliming** [comment]
>  I run delete_bin_obj.bat 

Why are you doing this?

**Comment by AdemAygun** [comment]
no particular reason , I wanted to try to fix the error. nowadays error has gone

**Comment by CaglarMacha** [comment]
.
