### ISSUE TITLE
reloadOnChange (always true) in ConfigurationHelper should be configurable through AbpConfigurationBuilderOptions

### ISSUE THREAD

**Issue by personball** [abpframework/abp#13726]
ABP Framework version: ALL 
User Interface: None
Database provider: Not Related
Exception message(from docker build, with `RUN dotnet test`):
```
System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
```
Stack trace(from docker build, with `RUN dotnet test`):

```
Stack Trace:
     at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Configuration.ConfigurationHelper.BuildConfiguration(AbpConfigurationBuilderOptions options, Action`1 builderAction)
   at Volo.Abp.Internal.InternalServiceCollectionExtensions.AddCoreAbpServices(IServiceCollection services, IAbpApplication abpApplication, AbpApplicationCreationOptions applicationCreationOptions)
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.Testing.AbpIntegratedTest`1..ctor()
   at DangQu.PT.PermissionManage.PermissionManageTestBase`1..ctor()
   at DangQu.PT.PermissionManage.PermissionManageDomainTestBase..ctor() in /src/test/DangQu.PT.PermissionManage.Domain.Tests/PermissionManageDomainTestBase.cs:line 16
   at DangQu.PT.PermissionManage.ApplicationPermissionResolvers.Decorators.DataFilterFeatureLimitResolverDecorator_Tests..ctor() in /src/test/DangQu.PT.PermissionManage.Domain.Tests/ApplicationPermissionResolvers/Decorators/DataFilterFeatureLimitResolverDecorator_Tests.cs:line 22
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
```

Steps needed to **reproduce** the problem:

My Scenario Description

I have almost 300 unit-tests in my xxxx.Domain.Tests.   
When I run dotnet test locally (not in docker) , all tests passed.  
When I push my code to main branch and trigger CI/CD on jenkins (It runs tests in docker build), It only pass 102 tests, and throw exception as above.  

As we trace the code, found this line:

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Microsoft/Extensions/Configuration/ConfigurationHelper.cs#L21

Suggestions：`reloadOnChange` (always true) in ConfigurationHelper should be configurable through AbpConfigurationBuilderOptions

PS: It's hard to fix this limit in docker build, follow this http://blog.travisgosselin.com/configured-user-limit-inotify-instances/

**Comment by roc916** [comment]
See: https://github.com/dotnet/aspnetcore/issues/8449#issuecomment-512275929

My Github Workflows Configure:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/12685126/185288306-a2ab7101-ea0f-4725-a474-e388054ab52a.png">

**Comment by personball** [comment]
> See: [dotnet/aspnetcore#8449 (comment)](https://github.com/dotnet/aspnetcore/issues/8449#issuecomment-512275929)
> 
> My Github Workflows Configure: <img alt="image" width="797" src="https://user-images.githubusercontent.com/12685126/185288306-a2ab7101-ea0f-4725-a474-e388054ab52a.png">

I have tried, not work.

base abp default template dockerfile, all attempts below failed:

- try update  `/etc/sysctl.conf` 
- try run `sysctl -p`
- try`sudo`
- try `ENV  DOTNET_USE_POLLING_FILE_WATCHER=1`
- try update `/etc/security/limits.conf`

see https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.HttpApi.Host/Dockerfile#L5

PS: change base image for this dockerfile may not an option for me.
