### ISSUE TITLE
How to give Authorization on AsyncPeriodicBackgroundWorker / BackgroundWorker ?

### ISSUE THREAD

**Issue by GillesFr06** [abpframework/abp#13800]
Hello,

**apb.io 5.1 (soon 5.3)
Blazor Server
EF Core, MySQL 8**

I've created a AsyncPeriodicBackgroundWorkerBase worker : https://docs.abp.io/en/abp/latest/Background-Workers

And registered it :
```
	context.ServiceProvider
		.GetRequiredService<IBackgroundWorkerManager>()
		.AddAsync(context.ServiceProvider.GetRequiredService<EvenementWorker>());
```

It is launched every 10 seconds :
```
public EvenementWorker(AbpAsyncTimer timer, IServiceScopeFactory serviceScopeFactory) : base(timer, serviceScopeFactory)
{
	Timer.Period = 10000;  // 10 secondes
}
```

It works.

But when I access to my Database through my AppService :

```
protected async override Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
{
	Logger.LogTrace("Worker Evenement début");

	// Resolve dependencies
	IEvenementAppService eventRepository = workerContext.ServiceProvider.GetRequiredService<IEvenementAppService>();

	// Do the work
	List<EvenementDto> ListeEvent = await eventRepository.GetListEventAFaireAsync(DateTime.Now, 10);

	Logger.LogTrace("Worker Evenement fin");
}
```

I have an Authorization error :

2022-08-23 18:40:01.667 +02:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
2022-08-23 18:40:01.687 +02:00 [WRN] Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
Volo.Abp.Authorization.AbpAuthorizationException: Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper, IUnitOfWorkManager unitOfWorkManager)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper, IUnitOfWorkManager unitOfWorkManager)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Courtisan.Blazor.Workers.EvenementWorker.DoWorkAsync(PeriodicBackgroundWorkerContext workerContext) in C:\Users\Administrateur\source\repos\Courtisan\src\Courtisan.Blazor\Workers\EvenementWorker.cs:line 47
   at Volo.Abp.BackgroundWorkers.AsyncPeriodicBackgroundWorkerBase.DoWorkAsync()

I tried to decorate with [AllowAnonymous], it doesn't solve the problem.

**What do I have to do to give credential to the worker so it can access to my database through the AppService ?
Or to remove the Authorization control for that worker ?**

Thanks,
Gilles

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/3743#issuecomment-619526683

**Comment by GillesFr06** [comment]
Hello,

Thanks for your answer.
Before posting, I've already seen those threads.

I understand the fact to no put business logic in app service.
And to move that in another place.
I've already done/test it.

But in that new class, If it's instantiated from razor page, the injection works.
`	[Inject] protected IEmailSender emailSender { get; set; }`
If I create it from the background worker, the injection doesn't work and emailSender is null.

So I have to problems :

1 - If I call an AppService from a background worker, it doesn't work because the caller has no credential.
How to give it credentials ?
Ok, a worker shouldn't call an AppService which is supposed to be dedicated to UI.
So I should create another service elsewhere, domain for example.

2 - If I create a new service elsewhere, the injection of emailSender is null, so that service is not usable.
Do you have an exemple code for that service, and how to instantiate/register/use it ?

I've already followed : https://docs.abp.io/en/abp/latest/Emailing
Again, _emailSender is null.

**What do I want to do ? Having a background worker, making a SELECT in a database table, sending an email, and updating a record in a database table.**

Many thanks,
Gilles

**Comment by GillesFr06** [comment]
For those who could have the same problem.
How I solve it (and I will probably improve it).

The [Inject] at the top of the class is not working.
I resolve the injection just before using it, inside the worker.
Example :
```
	IEmailSender emailSender = this.ServiceProvider.GetRequiredService<IEmailSender>();
	await emailSender.SendAsync(msg);

```
or
```
	IRepository<Evenement, Guid> eventRepository = this.ServiceProvider.GetRequiredService<IRepository<Evenement, Guid>>();
	var output = await eventRepository.UpdateAsync(input, autoSave: true);

```
To avoid the error "Cannot access a disposed object", I've decorated :
```
	[UnitOfWork]
	protected async override Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)

```
that last point was a nightmare to solve.
What helped me : https://stackoverflow.com/questions/50149302/how-to-open-database-connection-in-a-backgroundjob-in-abp-application/50153210#50153210

Hope this can help someone else.
