### ISSUE TITLE
Cannot resolve parameter Volo.Abp.Domain.Repositories.IRepository`2

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1384]
Try out this API:
![image](https://user-images.githubusercontent.com/30018771/60227890-82157600-98c3-11e9-87ee-e4523aa30618.png)
And then get 500 error.
In my use, it works well in version 0.17, but 0.18+.

HttpApi.Host logs:
```
2019-06-27 09:15:12.158 +08:00 [INF] Request starting HTTP/2.0 GET https://localhost:44326/api/app/factory  
2019-06-27 09:15:12.158 +08:00 [DBG] AuthenticationScheme: Bearer was not authenticated.
2019-06-27 09:15:12.202 +08:00 [INF] Route matched with {action = "GetListAsync", controller = "Factory", area = ""}. Executing action MyProject.Factories.FactoryAppService.GetListAsync (MyProject.Application)
2019-06-27 09:15:12.243 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
2019-06-27 09:15:12.248 +08:00 [ERR] {
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "validationErrors": null
}
2019-06-27 09:15:12.252 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.FactoryAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.FactoryAppServiceProxy. ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.FactoryAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[MyProject.Factories.Factory,System.Guid] repository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Domain.Repositories.IRepository`2[MyProject.Factories.Factory,System.Guid], Volo.Abp.MultiTenancy.ICurrentTenant)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 160
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 118
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 136
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 85
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 83
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in C:\projects\autofac\src\Autofac\ResolutionExtensions.cs:line 1041
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\ResolutionExtensions.cs:line 871
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
2019-06-27 09:15:12.392 +08:00 [ERR] ---------- Exception Data ----------
2019-06-27 09:15:12.393 +08:00 [ERR] ActivatorChain = Castle.Proxies.FactoryAppServiceProxy
2019-06-27 09:15:12.395 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2019-06-27 09:15:12.406 +08:00 [INF] Executed action MyProject.Factories.FactoryAppService.GetListAsync (MyProject.Application) in 204.2716ms
2019-06-27 09:15:12.407 +08:00 [INF] Request finished in 248.8397ms 500 application/json; charset=utf-8

```
FactoryAppService:
```
using System;
using System.Threading.Tasks;
using MyProject.Factories.Dtos;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.MultiTenancy;

namespace MyProject.Factories
{
    //[Authorize("MyProject.Administration.FactoryManagement")]
    public class FactoryAppService : AsyncCrudAppService<Factory, FactoryDto, Guid, PagedAndSortedResultRequestDto, CreateUpdateFactoryDto, CreateUpdateFactoryDto>, IFactoryAppService
    {
        private readonly ICurrentTenant _currentTenant;

        public FactoryAppService(
            IRepository<Factory, Guid> repository,
            ICurrentTenant currentTenant) : base(repository)
        {
            _currentTenant = currentTenant;
        }

        //[Authorize("MyProject.Administration.FactoryManagement.SetFactory")]
        public override Task<FactoryDto> CreateAsync(CreateUpdateFactoryDto input)
        {
            return base.CreateAsync(input);
        }

        [Authorize("MyProject.Administration.FactoryManagement.SetFactory")]
        public override Task<FactoryDto> UpdateAsync(Guid id, CreateUpdateFactoryDto input)
        {
            return base.UpdateAsync(id, input);
        }

        [Authorize("MyProject.Administration.FactoryManagement.SetFactory")]
        public override Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
        }
    }
}
```

**Comment by maliming** [comment]
Put the Factory entity into the DbContext.

**Comment by gdlcf88** [comment]
Forgot to add DbSet when I upgraded the abp framework. I am a fool.
