### ISSUE TITLE
aliyun blob container throw a weird exception when calling ExistsAsync api

### ISSUE THREAD

**Issue by wallee85** [abpframework/abp#13925]
i use the aliyun blob container for my image storage.i use the following code logic to complete a blob deletion:
`if (await AdvertisementImageContainer.ExistsAsync(eventData.BlobName))
            {
                await AdvertisementImageContainer.DeleteAsync(eventData.BlobName);
            }`

so firstly i  check if the blob exactly exists,if true,then i delete the blob.
what i've done is ensuring there's no any exception thrown during the database transaction completion.
but ` await AdvertisementImageContainer.ExistsAsync(eventData.BlobName)`  throw the exception when blob doesn't exists..
so is it a bug?

**ABP Framework version**:5.3.2
**User Interface**:mvc
**Database provider(EF Core/MongoDB)**:EF Core
Exception message and **stack trace** if available (check the logs):
[10:20:56 ERR] Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at Aliyun.OSS.Common.Communication.ServiceResponse.EnsureSuccessful()
   at Aliyun.OSS.Common.Handlers.ErrorResponseHandler.ErrorHandle(ServiceResponse response)
   at Aliyun.OSS.Common.Handlers.ErrorResponseHandler.Handle(ServiceResponse response)
   at Aliyun.OSS.Common.Communication.ServiceClient.HandleResponse(ServiceResponse response, IEnumerable`1 handlers)
   at Aliyun.OSS.Common.Communication.ServiceClient.Send(ServiceRequest request, ExecutionContext context)
   at Aliyun.OSS.Common.Communication.RetryableServiceClient.SendImpl(ServiceRequest request, ExecutionContext context, Int32 retryTimes)
   at Aliyun.OSS.Common.Communication.RetryableServiceClient.Send(ServiceRequest request, ExecutionContext context)
   at Aliyun.OSS.Commands.OssCommand.Execute()
   at Aliyun.OSS.OssClient.DoesObjectExist(String bucketName, String key)
   at Volo.Abp.BlobStoring.Aliyun.AliyunBlobProvider.BlobExists(IOss ossClient, String containerName, String blobName)
   at Volo.Abp.BlobStoring.Aliyun.AliyunBlobProvider.ExistsAsync(BlobProviderExistsArgs args)
   at Volo.Abp.BlobStoring.BlobContainer.ExistsAsync(String name, CancellationToken cancellationToken)
   at Boc.CarOnline.EventHandlers.AdvertisementDeletedEventHandler.HandleEventAsync(AdvertisementDeletedEvent eventData) in D:\WorkSpace\卡部线上看车\server\src\Boc.CarOnline.Backgrounds\EventHandlers\AdvertisementDeletedEventHandler.cs:line 22
   at Volo.Abp.EventBus.EventHandlerInvoker.InvokeAsync(IEventHandler eventHandler, Object eventData, Type eventType)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions, InboxConfig inboxConfig)
   at System.AbpExceptionExtensions.ReThrow(Exception exception)
   at Volo.Abp.EventBus.EventBusBase.ThrowOriginalExceptions(Type eventType, List`1 exceptions)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(LocalEventMessage localEventMessage)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishToEventBusAsync(Type eventType, Object eventData)
   at Volo.Abp.EventBus.EventBusBase.PublishAsync(Type eventType, Object eventData, Boolean onUnitOfWorkComplete)
   at Volo.Abp.EventBus.UnitOfWorkEventPublisher.PublishLocalEventsAsync(IEnumerable`1 localEvents)
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

**Comment by maliming** [comment]
hi

You can debug the `AliyunBlobProvider` to check the parameters.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlobStoring.Aliyun/Volo/Abp/BlobStoring/Aliyun/AliyunBlobProvider.cs#L100

**Comment by wallee85** [comment]
thank  you for your prompt reply!
i tested this agin and found it's my falt,this issure can be closed
