### ISSUE TITLE
abp new MauiBookStore -t maui -o MauiBookStore throws error in Version 6.0.0-rc.4 (Prerelease)

### ISSUE THREAD

**Issue by BartVHoey** [abpframework/abp#13994]
C:\>abp new MauiBookStore -t maui -o MauiBookStore
[08:04:10 INF] ABP CLI (https://abp.io)
[08:04:10 INF] Version 6.0.0-rc.4 (Prerelease)
[08:04:10 INF] Creating your project...
[08:04:10 INF] Project name: MauiBookStore
[08:04:10 INF] Template: maui
[08:04:10 INF] Output folder: C:\MauiBookStore
[08:04:11 INF] Downloading template: maui, version: 5.3.4
Error occured while downloading source-code from https://abp.io/api/download/template/ : StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Mon, 12 Sep 2022 06:04:12 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-cache,no-store
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.-6OvtTX3HwI=CfDJ8LLQt0moM0FFpUJR0ZfQsV6ChYQuCSuosAfvRhpAprx5QQPOwwkec0Kxe9QJaUt-RSI4vuds82aUvAqEnnFqtfjzkJtblnQlq1jhfiXma_11-ni2iuTeVWHBypyrFXMhiwr9wpyFX5tVrykrT0t2YJM; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8LLQt0moM0FFpUJR0ZfQsV6vjk11iURPpZZed-jhbm5LZrYkwXAwoYtXBCFOSjIX2WatGsAE-zcGkK1fM92awR0a5oQy8fxbhvpkm44enIpwAHfM6NbntdfHPRu6UKrC7RdD02KM32mJUEoffqByego; expires=Thu, 09 Sep 2032 06:04:12 GMT; path=/; secure; samesite=none
  Strict-Transport-Security: max-age=2592000
  X-Frame-Options: SAMEORIGIN
  X-Powered-By: ARR/3.0
  X-Powered-By: ASP.NET
  CF-Cache-Status: DYNAMIC
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=l%2F8vzDR5qUf4Csa7tiScXzFAWCN1lmf%2BsWvEPl3EEfS0cJJy7K9Ief8k%2B%2FUbA80VWe622n2zv2vwODjQU9eXYCdulCp5EKhrVgvEkwtFG3Kv7FHWpuB9YQ%3D%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 749671baa86a6d7d-MUC
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
[08:04:12 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializerProvider.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\SystemTextJson\AbpSystemTextJsonSerializerProvider.cs:line 35
   at Volo.Abp.Json.AbpHybridJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\AbpHybridJsonSerializer.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 254
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 120
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 66
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 90
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 161
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 69

**Comment by maliming** [comment]
hi

`abp new MauiBookStore -t maui -o MauiBookStore --preview`
