### ISSUE TITLE
Entity 'XXX' has a global query filter defined and is the required end of a relationship with the entity 'XXX'

### ISSUE THREAD

**Issue by abdullahshaqaliah** [abpframework/abp#14120]
ABP Framework version：5.3.0
Hi
I get this warning
```
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentGenre'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentImage'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentLabel'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentPromotion'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentProperty'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentSinger'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentSupplier'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonImage'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonPromotion'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'Serie'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Genre' has a global query filter defined and is the required end of a relationship with the entity 'GenreTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'GroupOfCountries' has a global query filter defined and is the required end of a relationship with the entity 'CountryGroupOfCountries'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'People' has a global query filter defined and is the required end of a relationship with the entity 'PeopleTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Genre' has a global query filter defined and is the required end of a relationship with the entity 'PlayListGenre'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'PlayList' has a global query filter defined and is the required end of a relationship with the entity 'PlayListLabel'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'PlayList' has a global query filter defined and is the required end of a relationship with the entity 'PlayListTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:20:24.506 +03:00 [WRN] Entity 'Singer' has a global query filter defined and is the required end of a relationship with the entity 'SingerTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
```

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by abdullahshaqaliah** [comment]
```
  protected virtual bool IsActiveFilterEnabled => DataFilter?.IsEnabled<IIsActive>() ?? false;
    protected virtual bool IsApprovedFilterEnabled => DataFilter?.IsEnabled<IIsApproved>() ?? false;
    
protected override bool ShouldFilterEntity<TEntity>(IMutableEntityType entityType)
    {
        if (typeof(IIsActive).IsAssignableFrom(typeof(TEntity)))
        {
            return true;
        }

        if (typeof(IIsApproved).IsAssignableFrom(typeof(TEntity)))
        {
            return true;
        }

        return base.ShouldFilterEntity<TEntity>(entityType);
    }

    protected override Expression<Func<TEntity, bool>> CreateFilterExpression<TEntity>()
    {
        var expression = base.CreateFilterExpression<TEntity>();

        if (typeof(IIsActive).IsAssignableFrom(typeof(TEntity)))
        {
            Expression<Func<TEntity, bool>> isActiveFilter =
                e => !IsActiveFilterEnabled || EF.Property<bool>(e,nameof(IIsActive.IsActive));
            expression = expression == null
                ? isActiveFilter
                : CombineExpressions(expression, isActiveFilter);
        }



        if (typeof(IIsApproved).IsAssignableFrom(typeof(TEntity)))
        {
            Expression<Func<TEntity, bool>> isApprovedFilter =
                e => !IsApprovedFilterEnabled || EF.Property<bool>(e, nameof(IIsApproved.IsApproved));
            expression = expression == null
                ? isApprovedFilter
                : CombineExpressions(expression, isApprovedFilter);
        }

        return expression;
    }



public class Content : FullAuditedEntity<Guid>, IIsActive, IIsApproved, IMultiLingualEntity<ContentProperty>
{
    public bool IsActive { get; set; }

    public bool IsApproved { get; set; }

    public bool IsComingSoon { get; set; }

    public bool IsGroupOfCountryRestricted { get; set; }

    public bool IsOrginal { get; set; }

    public bool IsFree { get; set; }

    public int ReleaseYear { get; set; }

    public DateTime? LicenseStart { get; set; }

    public DateTime? LicenseEnd { get; set; }

    public bool IsLicenseNeed { get; set; }

    public DateTime PublishDate { get; set; }

    public int ContentTypeId { get; set; }

    public ContentType ContentType { get; set; }

    public int LabelInicatorId { get; set; }

    public LabelIndecator LabelIndecator { get; set; }

    public int MaturityRatingId { get; set; }

    public MaturityRating MaturityRating { get; set; }


    public ICollection<ContentImage> Images { get; set; }

    public ICollection<ContentPromotion> Promotions { get; set; }

    public ICollection<ContentProperty> Translations { get; set; }

    public ICollection<ContentLabel> Labels { get; set; }

    public ICollection<ContentGenre> Genres { get; set; }
    public ICollection<ContentSupplier> Suppliers { get; set; }
    public ICollection<ContentSinger> Singers { get; set; }


    public Serie Series { get; set; }

    public void SetId(Guid id)
    {
        Id = id;
    }


}
public abstract class ContentEntityRelation<TKey> : Entity<TKey>, IContentEntityRelation
{
    public Guid ContentId { get; set; }
    public Content Content { get; set; }


}

public abstract class ContentEntityRelation : ContentEntityRelation<int>
{

}
public class Serie : ContentEntityRelation
{
    public int SeasonsCount { get; set; }
    public ICollection<Season> Seasons { get; set; }


}
public class ContentProperty :Entity<int>, IEntityTranslation<Content,Guid>
{
    public string Value { get; set; }
    public string Language { get; set; }
    public int PropertyId { get; set; }

    public Property property { get; set; }
    public Content Core { get ; set; }
    public Guid CoreId { get; set; }
}
public class ContentConfiguration : IEntityTypeConfiguration<Content>
{
    public void Configure(EntityTypeBuilder<Content> builder)
    {
        builder.ToTable(CMSServiceDbProperties.DbTablePrefix + "Contents", CMSServiceDbProperties.DbSchema);
        builder.CMSServiceConfigureByConvention();

        builder
                .HasOne(t => t.Series)
                .WithOne(t => t.Content)
                .HasForeignKey<Serie>(x => x.ContentId)
                .IsRequired();

        builder
                .HasOne(t => t.LabelIndecator)
                .WithMany(t => t.Contents)
                .HasForeignKey(t => t.LabelInicatorId)
                .IsRequired();


        builder
                .HasOne(t => t.MaturityRating)
                .WithMany(t => t.Contents)
                .HasForeignKey(t => t.MaturityRatingId)
                .IsRequired();

        builder
                .HasOne(t => t.ContentType)
                .WithMany(t => t.Contents)
                .HasForeignKey(t => t.ContentTypeId)
                .IsRequired();

    }
}
```

2022-09-26 07:39:42.516 +03:00 [INF] Starting TenTime.CMSService.HttpApi.Host.
2022-09-26 07:39:45.821 +03:00 [INF] Loaded ABP modules:
2022-09-26 07:39:45.823 +03:00 [INF] - TenTime.CMSService.CMSServiceHttpApiHostModule
2022-09-26 07:39:45.823 +03:00 [INF]   - TenTime.Shared.Hosting.Settings.Microservices.TenTimeSharedHostingSettingsMicroservicesModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.Shared.Hosting.Settings.TenTimeSharedHostingSettingsModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.Shared.Hosting.AspNetCore.TenTimeSharedHostingAspNetCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]         - TenTime.Shared.Hosting.TenTimeSharedHostingModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.Autofac.AbpAutofacModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.Castle.AbpCastleCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.Data.AbpDataModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Validation.AbpValidationAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.Uow.AbpUnitOfWorkModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.Swashbuckle.AbpSwashbuckleModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.AspNetCore.AbpAspNetCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Auditing.AbpAuditingModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Json.AbpJsonModule
2022-09-26 07:39:45.823 +03:00 [INF]                   - Volo.Abp.Timing.AbpTimingModule
2022-09-26 07:39:45.823 +03:00 [INF]                     - Volo.Abp.Localization.AbpLocalizationModule
2022-09-26 07:39:45.823 +03:00 [INF]                       - Volo.Abp.Settings.AbpSettingsModule
2022-09-26 07:39:45.823 +03:00 [INF]                         - Volo.Abp.Security.AbpSecurityModule
2022-09-26 07:39:45.823 +03:00 [INF]                         - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Threading.AbpThreadingModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Auditing.AbpAuditingContractsModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Http.AbpHttpModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Http.AbpHttpAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Minify.AbpMinifyModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Authorization.AbpAuthorizationModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Validation.AbpValidationModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Application.AbpDddApplicationContractsModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.UI.Navigation.AbpUiNavigationModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.UI.AbpUiModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.Application.AbpDddApplicationModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Domain.AbpDddDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.EventBus.AbpEventBusModule
2022-09-26 07:39:45.823 +03:00 [INF]                   - Volo.Abp.Guids.AbpGuidsModule
2022-09-26 07:39:45.823 +03:00 [INF]                   - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
2022-09-26 07:39:45.823 +03:00 [INF]                   - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2022-09-26 07:39:45.823 +03:00 [INF]                 - Volo.Abp.Specifications.AbpSpecificationsModule
2022-09-26 07:39:45.823 +03:00 [INF]               - Volo.Abp.Features.AbpFeaturesModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.Caching.StackExchangeRedis.AbpCachingStackExchangeRedisModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.Caching.AbpCachingModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.Serialization.AbpSerializationModule
2022-09-26 07:39:45.823 +03:00 [INF]     - Volo.Abp.BackgroundJobs.RabbitMQ.AbpBackgroundJobsRabbitMqModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.RabbitMQ.AbpRabbitMqModule
2022-09-26 07:39:45.823 +03:00 [INF]     - Volo.Abp.EventBus.RabbitMq.AbpEventBusRabbitMqModule
2022-09-26 07:39:45.823 +03:00 [INF]     - Volo.Abp.DistributedLocking.AbpDistributedLockingModule
2022-09-26 07:39:45.823 +03:00 [INF]   - TenTime.CMSService.CMSServiceHttpApiModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.CMSService.CMSServiceApplicationContractsModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.CMSService.CMSServiceDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]   - TenTime.CMSService.CMSServiceApplicationModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.CMSService.CMSServiceDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.MultiLingual.Domain.TenTimeMultiLingualDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.MultiLingual.AutoMapper.TenTimeMultiLingualAutoMapperModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.AutoMapper.AbpAutoMapperModule
2022-09-26 07:39:45.823 +03:00 [INF]   - TenTime.CMSService.EntityFrameworkCore.CMSServiceEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.Dapper.PostgreSql.TenTimeDapperPostgreSqlModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.EntityFrameworkCore.PostgreSql.TenTimeEntityFrameworkCorePostgreSqlModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.EntityFrameworkCore.PostgreSql.AbpEntityFrameworkCorePostgreSqlModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.Dapper.TenTimeDapperModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.Dapper.AbpDapperModule
2022-09-26 07:39:45.823 +03:00 [INF]         - TenTime.Dapper.TenTimeDapperSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]     - TenTime.AdministrationService.EntityFrameworkCore.AdministrationServiceEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]       - TenTime.AdministrationService.AdministrationServiceDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.Identity.AbpIdentityDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.Users.AbpUsersDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]             - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.PermissionManagement.IdentityServer.AbpPermissionManagementDomainIdentityServerModule
2022-09-26 07:39:45.823 +03:00 [INF]           - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]     - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
2022-09-26 07:39:45.823 +03:00 [INF]       - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
2022-09-26 07:39:45.823 +03:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
2022-09-26 07:39:46.510 +03:00 [INF] Lock is acquired for db migration and seeding on database named: CMSService...
2022-09-26 07:39:48.146 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentGenre'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.146 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentImage'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.146 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentLabel'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.146 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentPromotion'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentProperty'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentSinger'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'ContentSupplier'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonImage'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonPromotion'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Season' has a global query filter defined and is the required end of a relationship with the entity 'SeasonTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Content' has a global query filter defined and is the required end of a relationship with the entity 'Serie'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Genre' has a global query filter defined and is the required end of a relationship with the entity 'GenreTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'GroupOfCountries' has a global query filter defined and is the required end of a relationship with the entity 'CountryGroupOfCountries'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'People' has a global query filter defined and is the required end of a relationship with the entity 'PeopleTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Genre' has a global query filter defined and is the required end of a relationship with the entity 'PlayListGenre'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'PlayList' has a global query filter defined and is the required end of a relationship with the entity 'PlayListLabel'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'PlayList' has a global query filter defined and is the required end of a relationship with the entity 'PlayListTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:48.147 +03:00 [WRN] Entity 'Singer' has a global query filter defined and is the required end of a relationship with the entity 'SingerTranslation'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2022-09-26 07:39:52.308 +03:00 [INF] Lock is released for db migration and seeding on database named: CMSService...
2022-09-26 07:39:52.323 +03:00 [INF] Initialized all ABP modules.
2022-09-26 07:39:52.435 +03:00 [INF] Application started. Press Ctrl+C to shut down.
2022-09-26 07:39:52.435 +03:00 [INF] Hosting environment: Development
2022-09-26 07:39:52.435 +03:00 [INF] Content root path: F:\TenTimeWork\Applications\cms_service\src\TenTime.CMSService.HttpApi.Host\
2022-09-26 07:39:52.466 +03:00 [INF] Request starting HTTP/2 GET https://localhost:44354/ - -
2022-09-26 07:39:52.900 +03:00 [WRN] ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
   at Volo.Abp.Caching.StackExchangeRedis.AbpRedisCache.SetManyAsync(IEnumerable`1 items, DistributedCacheEntryOptions options, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.<>c__DisplayClass54_0.<<SetManyAsync>g__SetRealCache|0>d.MoveNext()
2022-09-26 07:39:53.022 +03:00 [WRN] ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
   at Volo.Abp.Caching.StackExchangeRedis.AbpRedisCache.SetManyAsync(IEnumerable`1 items, DistributedCacheEntryOptions options, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.<>c__DisplayClass54_0.<<SetManyAsync>g__SetRealCache|0>d.MoveNext()
2022-09-26 07:39:53.178 +03:00 [INF] Executing endpoint 'TenTime.CMSService.Controllers.HomeController.Index (TenTime.CMSService.HttpApi.Host)'
2022-09-26 07:39:53.201 +03:00 [INF] Route matched with {action = "Index", controller = "Home", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult Index() on controller TenTime.CMSService.Controllers.HomeController (TenTime.CMSService.HttpApi.Host).
2022-09-26 07:39:53.239 +03:00 [INF] Executing RedirectResult, redirecting to /swagger.
2022-09-26 07:39:53.244 +03:00 [INF] Executed action TenTime.CMSService.Controllers.HomeController.Index (TenTime.CMSService.HttpApi.Host) in 38.6303ms
2022-09-26 07:39:53.244 +03:00 [INF] Executed endpoint 'TenTime.CMSService.Controllers.HomeController.Index (TenTime.CMSService.HttpApi.Host)'
2022-09-26 07:39:53.281 +03:00 [INF] Request starting HTTP/2 GET https://localhost:44354/swagger/index.html - -
2022-09-26 07:39:53.408 +03:00 [INF] Request finished HTTP/2 GET https://localhost:44354/ - - - 302 - - 943.5702ms
2022-09-26 07:39:53.559 +03:00 [INF] Request finished HTTP/2 GET https://localhost:44354/swagger/index.html - - - 200 - text/html;charset=utf-8 270.7120ms
2022-09-26 07:39:53.559 +03:00 [INF] Request starting HTTP/2 GET https://localhost:44354/_framework/aspnetcore-browser-refresh.js - -
2022-09-26 07:39:53.565 +03:00 [INF] Request finished HTTP/2 GET https://localhost:44354/_framework/aspnetcore-browser-refresh.js - - - 200 12032 application/javascript;+charset=utf-8 5.2044ms
2022-09-26 07:39:53.568 +03:00 [INF] Request starting HTTP/2 GET https://localhost:44354/_vs/browserLink - -
2022-09-26 07:39:53.603 +03:00 [INF] Request finished HTTP/2 GET https://localhost:44354/_vs/browserLink - - - 200 - text/javascript;+charset=UTF-8 34.3234ms
2022-09-26 07:39:53.804 +03:00 [INF] Request starting HTTP/2 GET https://localhost:44354/swagger/v1/swagger.json - -
2022-09-26 07:39:54.577 +03:00 [INF] Request finished HTTP/2 GET https://localhost:44354/swagger/v1/swagger.json - - - 200 - application/json;charset=utf-8 772.5003ms

```

**Comment by abdullahshaqaliah** [comment]
Hi
Maybe it will be related with this issue
https://github.com/abpframework/abp/issues/7482

**Comment by maliming** [comment]
Hi

I think this is related to EF Core instead of abp.

 See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
