### ISSUE TITLE
IdentityModel discovery endpoint missing policies

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#14184]
**Problem:**
On Kubernetes deployment, server-to-server communication requests for the discovery endpoint should be internal requests without HTTPS. Since [IdentityModelAuthenticationService](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.IdentityModel/Volo/Abp/IdentityModel/IdentityModelAuthenticationService.cs#L150-L153) only uses requireHttps  option for document discovery causes **issuer name validation error** as below.

```txt
[10:10:22 INF] Request starting HTTP/1.1 GET http://eshop-st-administration/api/permission-management/permissions?providerName=U&providerKey=3a069a90-9224-65cf-096d-e55da51af8f8 - -
[10:10:22 INF] CORS policy execution failed.
[10:10:22 INF] Request origin https://eshop-st-web does not have permission to access the resource.
[10:10:22 INF] Executing endpoint 'Volo.Abp.PermissionManagement.PermissionsController.GetAsync (Volo.Abp.PermissionManagement.HttpApi)'
[10:10:22 INF] Route matched with {area = "permissionManagement", action = "Get", controller = "Permissions", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.PermissionManagement.GetPermissionListResultDto] GetAsync(System.String, System.String) on controller Volo.Abp.PermissionManagement.PermissionsController (Volo.Abp.PermissionManagement.HttpApi).
[10:10:22 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}
[10:10:22 ERR] Could not retrieve the OpenId Connect discovery document! ErrorType: PolicyViolation. Error: Issuer name does not match authority: https://eshop-st-authserver
Volo.Abp.AbpException: Could not retrieve the OpenId Connect discovery document! ErrorType: PolicyViolation. Error: Issuer name does not match authority: https://eshop-st-authserver
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetDiscoveryResponse(IdentityClientConfiguration configuration)
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.CreateClientCredentialsTokenRequestAsync(IdentityClientConfiguration configuration)
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetTokenResponse(IdentityClientConfiguration configuration)
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetAccessTokenAsync(IdentityClientConfiguration configuration)
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetAccessTokenOrNullAsync(String identityClientName)
   at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.TryAuthenticateAsync(HttpClient client, String identityClientName)
   at Volo.Abp.Http.Client.IdentityModel.IdentityModelRemoteServiceHttpClientAuthenticator.Authenticate(RemoteServiceHttpClientAuthenticateContext context)
```

We should add other policy options like `ValidateIssuerName` and `ValidateEndpoints`.

**Comment by leonkosak** [comment]
Is this issue somehow related to: https://stackoverflow.com/questions/74457621/openiddict-in-abp-framework-deploy-in-containerized-environment-k8s
?
