### ISSUE TITLE
Use IServiceScopeFactory instead of IHybridServiceScopeFactory for event bus caused the unit test to fail.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1426]
This change(https://github.com/abpframework/abp/commit/f719bda32f9b0469684d02e045d87eeabd2a833c) caused the unit test to fail.

https://github.com/abpframework/abp/blob/c4ced2dea956dc9afadc07b21d8ba6628b0f36ca/modules/identity/test/Volo.Abp.Identity.Application.Tests/Volo/Abp/Identity/IdentityUserAppService_Tests.cs#L56

```
System.ObjectDisposedException : Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag) in C:\projects\autofac\src\Autofac\Core\Lifetime\LifetimeScope.cs:line 133
   at Autofac.Extensions.DependencyInjection.AutofacServiceScopeFactory.CreateScope() in d:\Github\volo\abp\framework\src\Volo.Abp.Autofac\Autofac\Extensions\DependencyInjection\AutofacServiceScopeFactory.cs:line 62
   at Volo.Abp.EventBus.IocEventHandlerFactory.GetHandler() in d:\Github\volo\abp\framework\src\Volo.Abp.EventBus\Volo\Abp\EventBus\IocEventHandlerFactory.cs:line 31
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions) in d:\Github\volo\abp\framework\src\Volo.Abp.EventBus\Volo\Abp\EventBus\EventBusBase.cs:line 159
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData, List`1 exceptions) in d:\Github\volo\abp\framework\src\Volo.Abp.EventBus\Volo\Abp\EventBus\EventBusBase.cs:line 113
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(Type eventType, Object eventData) in d:\Github\volo\abp\framework\src\Volo.Abp.EventBus\Volo\Abp\EventBus\Local\LocalEventBus.cs:line 122
   at Volo.Abp.Uow.UnitOfWork.OnCompletedAsync() in d:\Github\volo\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 244
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken) in d:\Github\volo\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 135
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in d:\Github\volo\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in d:\Github\volo\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 82
   at Volo.Abp.Identity.IdentityUserAppService_Tests.CreateAsync() in D:\Github\volo\abp\modules\identity\test\Volo.Abp.Identity.Application.Tests\Volo\Abp\Identity\IdentityUserAppService_Tests.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by hikalkan** [comment]
I will check it. Thanks @maliming

**Comment by hikalkan** [comment]
I don't think this is related to IHybridServiceScopeFactory change, because it is just a plain wrapper for the IServiceScopeFactory for non-web apps.

I can be related to my refactor to reduce singletons.

This is the point before this commit: https://github.com/abpframework/abp/tree/63baeaa874b222bf61c19518bb681bff751f39e7

Can you create a temporary branch (like this:)

![image](https://user-images.githubusercontent.com/1210527/60609468-65e56d80-9dca-11e9-9055-8ca7ec795fe2.png)

Then test if it still fails. If it does not fail, do it also for the commit https://github.com/abpframework/abp/tree/f719bda32f9b0469684d02e045d87eeabd2a833c

This will take your time, but no easy way to understand it, because using IServiceScopeFactory instead of IHybridServiceScopeFactory is a true decision :)

**Comment by maliming** [comment]
Ok, I will try to find the reason.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/commit/3b2dae6f490cd6147c3271afd9f97cf48794b85f#diff-54cb9e5a1eb37d585e4ceac47cc21a00L7

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkManager.cs#L100

UnitOfWorkManager seems to have the same problem.

**Comment by hikalkan** [comment]
>If the life cycle of LocalDistributedEventBus is SIingleton(ISingletonDependency) then there will be no problem.

Fixed it. Thank you for finding this.

>UnitOfWorkManager seems to have the same problem.

Did you find any problem (a failing test or another one) about this?

**Comment by hikalkan** [comment]
OK, I fixed both. Thanks for finding these.
