### ISSUE TITLE
Localization Tests are broken

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#14290]
```
[xUnit.net 00:00:13.00]     Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_Without_Parents [FAIL] - Volo.Abp.Data.Tests.dll (net6.0)

  Failed Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_With_Inheritance [567 ms]
  Error Message:
Test run for C:\GitHub\abp\framework\test\Volo.Abp.Authorization.Tests\bin\Debug\net6.0\Volo.Abp.Authorization.Tests.dll (.NETCoreApp,Version=v6.0)
   Shouldly.ShouldAssertException : localizedStrings
    should contain an element satisfying the condition
(((ls.Name == "SeeYou") && (ls.Value == "See you")) && (ls.ResourceNotFound == false))
    but does not
  Stack Trace:
Microsoft (R) Test Execution Command Line Tool Version 17.3.0 (x64)     at Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_With_Inheritance() in C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\AbpLocalization_Tests.cs:line 329

Copyright (c) Microsoft Corporation.  All rights reserved.

  Failed Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_Without_Inheritance [27 ms]
  Error Message:
   Shouldly.ShouldAssertException : localizedStrings
    should contain an element satisfying the condition
(((ls.Name == "SeeYou") && (ls.Value == "See you")) && (ls.ResourceNotFound == false))
    but does not
Starting test execution, please wait...  Stack Trace:

     at Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_Without_Inheritance() in C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\AbpLocalization_Tests.cs:line 356
A total of 1 test files matched the specified pattern.
  Failed Volo.Abp.Localization.AbpLocalization_Tests.Should_Get_Extension_Texts [29 ms]
  Error Message:
   Shouldly.ShouldAssertException : _localizer["SeeYou"].Value
    should be
"See you"
    but was
"Görüsürüz"
    difference
Difference     |  |    |    |    |    |    |    |    |    |
               | \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/  \|/
Index          | 0    1    2    3    4    5    6    7    8
Expected Value | S    e    e    \s   y    o    u
Actual Value   | G    ö    r    ü    s    ü    r    ü    z
Expected Code  | 83   101  101  32   121  111  117
Actual Code    | 71   246  114  252  351  252  114  252  122
  Stack Trace:
     at Volo.Abp.Localization.AbpLocalization_Tests.Should_Get_Extension_Texts() in C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\AbpLocalization_Tests.cs:line 88
  Failed Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_Without_Parents [19 ms]
  Error Message:
   Shouldly.ShouldAssertException : localizedStrings
    should not contain an element satisfying the condition
(ls.Name == "FortyTwo")
    but does
  Stack Trace:
     at Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_Without_Parents() in C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\AbpLocalization_Tests.cs:line 281
[xUnit.net 00:00:13.06]     Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_With_Parents [FAIL]
  Failed Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_With_Parents [19 ms]
  Error Message:
   Shouldly.ShouldAssertException : localizedStrings
    should contain an element satisfying the condition
(((ls.Name == "FortyTwo") && (ls.Value == "Forty Two")) && (ls.ResourceNotFound == false))
    but does not
  Stack Trace:
     at Volo.Abp.Localization.AbpLocalization_Tests.GetAllStrings_With_Parents() in C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\AbpLocalization_Tests.cs:line 243

Attachments:
  C:\GitHub\abp\framework\test\Volo.Abp.Localization.Tests\TestResults\385bfbf0-f5c6-4ef7-b412-e2d8aebccd79\coverage.cobertura.xml
Failed!  - Failed:     5, Passed:    17, Skipped:     0, Total:    22, Duration: 5 s - Volo.Abp.Localization.Tests.dll (net6.0)
Test run for C:\GitHub\abp\framework\test\Volo.Abp.AspNetCore.Authentication.OAuth.Tests\bin\Debug\net6.0\Volo.Abp.AspNetCore.Authentication.OAuth.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.
```

![image](https://user-images.githubusercontent.com/23705418/195035072-7609f97c-626d-40c5-9c44-1e3f6c84cb56.png)

_Originally posted by @enisn in https://github.com/abpframework/abp/issues/14284#issuecomment-1274278012_

**Comment by enisn** [comment]
This is a stale issue. In the latest commit, there is no problem.
