### ISSUE TITLE
Fresh ABP 6.0 - Azure publish failures

### ISSUE THREAD

**Issue by aicreed** [abpframework/abp#14312]
UI: Blazor WASM
Version: 6.0
Database: Entity Framework

Good afternoon,

I have created a fresh ABP 6.0 project and have attempted to deploy it according to the following guide: 

https://abpioazuredevopsblazor.azurewebsites.net/

The HttpApi.Host however fails to start, and when I attempt to run it manually on the Azure server, I get the following error message: 

```
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule, Volo.Abp.OpenIddict.AspNetCore, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate(X500DistinguishedName subject)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate()
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.<>c__DisplayClass1_0.<AddOpenIddictServer>b__0(OpenIddictServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action`1 configuration)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.AddOpenIddictServer(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
   at Test.Project.Program.Main(String[] args) in C:\Users\ICSS-LAP\Downloads\Project\src\Test.Project.HttpApi.Host\Program.cs:line 35
```
Note that the project runs and functions perfectly locally, this error only shows when running the application on Azure. I should also note that this error appears on both the fresh project I created from the ABP website, and our own project. Could you perhaps advise on updated documentation for publishing to Azure in case I have missed anything?

**Comment by sharmawaiaman** [comment]
Hello this is already resolved.

https://support.abp.io/QA/Questions/3537/OpenIddict-WindowsCryptographicException-Access-is-denied

**Comment by kevinchalet** [comment]
@maliming hey.

I suspect this is going to be a very common source of pain (I received a similar report [here](https://github.com/openiddict/openiddict-core/issues/976#issuecomment-1275006043) and another one by email). I updated the OpenIddict documentation to mention more clearly that these extensions are not expected to work on IIS/Azure App Services, but I guess this point should be covered in ABP's documentation too to make sure folks are aware of this limitation.

Cheers.

**Comment by maliming** [comment]
Thanks @kevinchalet. I will mention that in abp document.

**Comment by kevinchalet** [comment]
@maliming @hikalkan hey 😃 

FYI I received another report earlier today, so it's likely folks keep being impacted, despite the documentation being updated (and clear, at least IMHO). To make the user experience a bit better, could/should the logic in ABP vNext be tweaked?

Two potential options that could help:
  - Use `IHostEnvironment.EnvironmentName`/`IsDevelopment()` to only set `AddDevelopmentEncryptionAndSigningCertificate` to `true` on dev and throw an exception with a message containing a URL pointing to the ABP docs in every other case (before OpenIddict kicks in and says the credentials are missing).
  - Use `IHostEnvironment.EnvironmentName`/`IsDevelopment()` to only set `AddDevelopmentEncryptionAndSigningCertificate` to `true` on dev and use in-memory RSA keys in every other case, as they _generally_ cause less issues on prod' environments than RSA keys embedded in X.509 certificates (see https://github.com/OrchardCMS/OrchardCore/blob/20f1db5f719a78b098fd29f2bfaa1a29399353f6/src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdServerService.cs#L596-L618 for additional details).

The second option is more convenient, but since keys wouldn't be synchronized in web farms, it would certainly lead to other questions, like "why aren't my tokens considered valid on my other server instances?"

Cheers.

**Comment by maliming** [comment]
hi @kevinchalet

I will confirm that. 👍
