### ISSUE TITLE
How to intercept through attributes

### ISSUE THREAD

**Issue by mnhjftihllr6995** [abpframework/abp#14378]
version : 6.0.0
intercept Work on all visual Method

``` c#

public class EventInterceptor : AbpInterceptor, ITransientDependency
{
    public ILogger<EventInterceptor> Logger { get; set; }
    public EventInterceptor()
    {
        Logger = NullLogger<EventInterceptor>.Instance;
    }
    public override async Task InterceptAsync(IAbpMethodInvocation invocation)
    {
            Logger.LogInformation("call：{0}，Argument：{1}", invocation.Method.Name,
                string.Join(",", invocation.ArgumentsDictionary.Select(t => $"{t.Key}:{t.Value ?? ""}")));
            await invocation.ProceedAsync();
    }
}

public static class EventInterceptorRegistrar
{
    public static void RegisterIfNeeded(IOnServiceRegistredContext context)
    {
        if (ShouldIntercept(context.ImplementationType))
        {
            context.Interceptors.TryAdd<EventInterceptor>();
        }
    }
    private static bool ShouldIntercept(Type type)
    {
        return !DynamicProxyIgnoreTypes.Contains(type) &&
               (type.IsDefined(typeof(EventLogAttribute), true) ||
                type
                .GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                .Any(methodInfo => methodInfo.IsDefined(typeof(EventLogAttribute), true)));
    }
}
[AttributeUsage(AttributeTargets.Method)]
public class EventLogAttribute:Attribute
{
   
}

public class HelloWorldService :  ITransientDependency
{
    public ILogger<HelloWorldService> Logger { get; set; }

    public HelloWorldService()
    {
        Logger = NullLogger<HelloWorldService>.Instance;
    }

    [EventLog]
    public virtual void FuncA()
    {
    }
    
    public virtual void FuncB()
    {
    }

    public Task SayHelloAsync()
    {
        FuncA();
        FuncB();
        return Task.CompletedTask;
    }
}


```
Output
``` bash
[15:29:54 INF] Initialized all ABP modules.
[15:29:54 INF] call：FuncA，Argument：
[15:29:54 INF] call：FuncB，Argument：
```
Therefore, throw an error when I want to inherit an external library with virtual methods

```c#
public class HelloWorldService :UserControl,  ITransientDependency
{
    public ILogger<HelloWorldService> Logger { get; set; }

    public HelloWorldService()
    {
        Logger = NullLogger<HelloWorldService>.Instance;
    }
    [UnitOfWork]
    public virtual Task SayHelloAsync()
    {
        
        return Task.CompletedTask;
    }
}
```
error
```bash
[15:40:06 FTL] Host terminated unexpectedly!
System.TypeLoadException: Method 'AfterControlRemoved' on type 'Castle.Proxies.HelloWorldServiceProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is overriding a method that is not visible from that assembly.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
```

**Comment by mnhjftihllr6995** [comment]
my test code
https://github.com/mnhjftihllr6995/interceptTest

**Comment by amerina** [comment]
Because you inhert from UserControl，“AfterControlRemoved” method in UserControl is internal,which is not allowed

**Comment by mnhjftihllr6995** [comment]
> Because you inhert from UserControl，“AfterControlRemoved” method in UserControl is internal,which is not allowed

Yes, but I only want to proxy  SayHelloAsync   Using attributes
