### ISSUE TITLE
Scriban Render Problem

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#14383]
![image](https://user-images.githubusercontent.com/64414348/195097036-e951b51b-1379-4058-ab69-7edd76ba3777.png)

Related Logs : 
https://kibana.abp.io/app/discover#/doc/748cdad0-d437-11eb-8f5f-21a75cbc40e1/filebeat-abpio-2022.10.11?id=PiDZxoMBDKZxd70_TI7r

```
at Scriban.Functions.DateTimeFunctions.Invoke(TemplateContext context, ScriptNode callerContext, ScriptArray arguments, ScriptBlockStatement blockStatement)
   at Scriban.Functions.DateTimeFunctions.InvokeAsync(TemplateContext context, ScriptNode callerContext, ScriptArray arguments, ScriptBlockStatement blockStatement)
   at Scriban.Syntax.ScriptFunctionCall.CallAsync(TemplateContext context, ScriptNode callerContext, Object functionObject, Boolean processPipeArguments, IReadOnlyList`1 arguments)
   at Scriban.Syntax.ScriptFunctionCall.EvaluateAsync(TemplateContext context)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode)
   at Scriban.Syntax.ScriptPipeCall.EvaluateAsync(TemplateContext context)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode)
   at Scriban.Syntax.ScriptExpressionStatement.EvaluateAsync(TemplateContext context)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode)
   at Scriban.Syntax.ScriptBlockStatement.EvaluateAsync(TemplateContext context)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode)
   at Scriban.Syntax.ScriptPage.EvaluateAsync(TemplateContext context)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.TemplateContext.EvaluateAsync(ScriptNode scriptNode)
   at Scriban.Template.EvaluateAndRenderAsync(TemplateContext context, Boolean render)
   at Scriban.Template.RenderAsync(TemplateContext context)
   at Scriban.Template.RenderAsync(Object model, MemberRenamerDelegate memberRenamer, MemberFilterDelegate memberFilter)
   at Volo.Docs.HtmlConverting.ScribanDocumentSectionRenderer.RenderAsync(String document, DocumentRenderParameters parameters, List`1 partialTemplates) in /var/lib/jenkins/workspace/abp.io-build/abp/modules/docs/src/Volo.Docs.Web/HtmlConverting/ScribanDocumentSectionRenderer.cs:line 45
   at Volo.Docs.Pages.Documents.Project.IndexModel.ConvertDocumentContentToHtmlAsync() in /var/lib/jenkins/workspace/abp.io-build/abp/modules/docs/src/Volo.Docs.Web/Pages/Documents/Project/Index.cshtml.cs:line 519
```

**Comment by ebicoglu** [comment]
Update Scriban library

**Comment by ebicoglu** [comment]
Fix the problematic documentation manually
