### ISSUE TITLE
eShopOnAbp: PublicWeb application error loop on CmsUserSync when CmskitService is offline

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#14420]
![image](https://user-images.githubusercontent.com/25867/197317379-635227d7-1fb1-4cda-a78d-052259eea736.png)

When the user is updated outside of the application (as in [db migrator](https://github.com/abpframework/eShopOnAbp/blob/gterdem/keycloak_integration/shared/EShopOnAbp.Keycloak.DbMigrator/KeycloakDataSeeder.cs#L223-L244)), RabbitMq publishes `UserUpdatedEto` which couldn't be handled.
![image](https://user-images.githubusercontent.com/25867/197317448-398ba202-0447-4a3c-8c4b-ea5e4f60b6b3.png)

Whenever the PublicWeb application starts, it causes error loop.

Stacktrace:
```txt
2022-10-21 23:17:40.948 -04:00 [INF]   - Volo.Abp.AutoMapper.AbpAutoMapperModule
2022-10-21 23:17:40.948 -04:00 [INF]   - EShopOnAbp.CmskitService.CmskitServiceHttpApiClientModule
2022-10-21 23:17:40.948 -04:00 [INF]     - EShopOnAbp.CmskitService.CmskitServiceApplicationContractsModule
2022-10-21 23:17:40.948 -04:00 [INF]       - EShopOnAbp.CmskitService.CmskitServiceDomainSharedModule
2022-10-21 23:17:40.948 -04:00 [INF]         - Volo.CmsKit.CmsKitDomainSharedModule
2022-10-21 23:17:40.948 -04:00 [INF]       - Volo.CmsKit.CmsKitApplicationContractsModule
2022-10-21 23:17:40.948 -04:00 [INF]         - Volo.CmsKit.Public.CmsKitPublicApplicationContractsModule
2022-10-21 23:17:40.948 -04:00 [INF]           - Volo.CmsKit.CmsKitCommonApplicationContractsModule
2022-10-21 23:17:40.948 -04:00 [INF]         - Volo.CmsKit.Admin.CmsKitAdminApplicationContractsModule
2022-10-21 23:17:40.948 -04:00 [INF]     - Volo.CmsKit.CmsKitHttpApiClientModule
2022-10-21 23:17:40.948 -04:00 [INF]       - Volo.CmsKit.Admin.CmsKitAdminHttpApiClientModule
2022-10-21 23:17:40.948 -04:00 [INF]         - Volo.CmsKit.CmsKitCommonHttpApiClientModule
2022-10-21 23:17:40.948 -04:00 [INF]       - Volo.CmsKit.Public.CmsKitPublicHttpApiClientModule
2022-10-21 23:17:40.948 -04:00 [INF]   - Volo.CmsKit.CmsKitDomainModule
2022-10-21 23:17:40.948 -04:00 [INF]     - Volo.Abp.Users.AbpUsersDomainModule
2022-10-21 23:17:40.948 -04:00 [INF]     - Volo.Abp.BlobStoring.AbpBlobStoringModule
2022-10-21 23:17:40.948 -04:00 [INF]   - Volo.CmsKit.Public.Web.CmsKitPublicWebModule
2022-10-21 23:17:40.948 -04:00 [INF]     - Volo.CmsKit.Web.CmsKitCommonWebModule
2022-10-21 23:17:41.484 -04:00 [ERR] An exception was thrown while activating Volo.CmsKit.Users.CmsUserSynchronizer.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.CmsKit.Users.CmsUserSynchronizer.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.CmsKit.Users.CmsUserSynchronizer' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.CmsKit.Users.ICmsUserRepository userRepository' of constructor 'Void .ctor(Volo.CmsKit.Users.ICmsUserRepository, Volo.CmsKit.Users.ICmsUserLookupService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.EventBus.IocEventHandlerFactory.GetHandler()
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions, InboxConfig inboxConfig)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData, List`1 exceptions, InboxConfig inboxConfig)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData)
   at Volo.Abp.EventBus.RabbitMq.RabbitMqDistributedEventBus.ProcessEventAsync(IModel channel, BasicDeliverEventArgs ea)
   at Volo.Abp.RabbitMQ.RabbitMqMessageConsumer.HandleIncomingMessageAsync(Object sender, BasicDeliverEventArgs basicDeliverEventArgs)
2022-10-21 23:17:41.486 -04:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Volo.CmsKit.Users.CmsUserSynchronizer

2022-10-21 23:17:41.489 -04:00 [ERR] An exception was thrown while activating Volo.CmsKit.Users.CmsUserSynchronizer.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.CmsKit.Users.CmsUserSynchronizer.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.CmsKit.Users.CmsUserSynchronizer' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.CmsKit.Users.ICmsUserRepository userRepository' of constructor 'Void .ctor(Volo.CmsKit.Users.ICmsUserRepository, Volo.CmsKit.Users.ICmsUserLookupService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.EventBus.IocEventHandlerFactory.GetHandler()
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions, InboxConfig inboxConfig)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData, List`1 exceptions, InboxConfig inboxConfig)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData)
   at Volo.Abp.EventBus.RabbitMq.RabbitMqDistributedEventBus.ProcessEventAsync(IModel channel, BasicDeliverEventArgs ea)
   at Volo.Abp.RabbitMQ.RabbitMqMessageConsumer.HandleIncomingMessageAsync(Object sender, BasicDeliverEventArgs basicDeliverEventArgs)
2022-10-21 23:17:41.489 -04:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Volo.CmsKit.Users.CmsUserSynchronizer
```

**Comment by gterdem** [comment]
https://github.com/abpframework/eShopOnAbp/blob/4907ff795ab0c8eeca29f50934cbed1d2a66303c/apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs#L73

Causes this error whenever a user is updated.
I have no idea why this is here.. @malikmasis?

**Comment by malikmasis** [comment]
> https://github.com/abpframework/eShopOnAbp/blob/4907ff795ab0c8eeca29f50934cbed1d2a66303c/apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs#L73
> 
> Causes this error whenever a user is updated. I have no idea why this is here.. @malikmasis?

You're right, no need for it. https://github.com/abpframework/eShopOnAbp/pull/139
