### ISSUE TITLE
The navigation 'IdentityUser.Claims' cannot be loaded because the entity is not being tracked. Navigations can only be loaded for tracked entities.

### ISSUE THREAD

**Issue by sahvey** [abpframework/abp#14432]
**ABP Framework version. 6.0.0**

I cloned your sample bookstore project prepared with wpf.

I added the **_AbpIdentityAspNetCoreModule_** reference I marked below to the **_BookStoreWpfModule_** class of the project I cloned.

![Abp_1](https://user-images.githubusercontent.com/46441777/197509561-b789a8aa-4f58-49b6-86ec-4dac49845452.jpg)

I have injected **_AbpSignInManager_** in **_MainWindow_**. Then I added the code I marked below to the click event of the button I added, and when I run the project and try to login, I get the exception shown below.

![Abp_2](https://user-images.githubusercontent.com/46441777/197509727-21bc4b71-42bc-4903-be27-e62d502380f7.jpg)

![Abp_3](https://user-images.githubusercontent.com/46441777/197509789-5db6b8c7-c3c0-45ee-b9c5-252c107db368.jpg)

I've reviewed previously asked questions similar to this error. However, none of the suggested solutions solved my problem.

When an unregistered user information is entered in SignInManager Database, it works smoothly and returns Failed. However, when a registered user enters and the login is successful, I get the above exception.

**Comment by maliming** [comment]
HI

Can you try using the `SignInManager ` in a unit of work?

https://docs.abp.io/en/abp/latest/Unit-Of-Work

**Comment by sahvey** [comment]
@maliming 
I did not fully understand your answer. Could you give a small example?

**Comment by maliming** [comment]
```cs
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Uow;

namespace AbpDemo
{
    public class MyService : ITransientDependency
    {
        private readonly IUnitOfWorkManager _unitOfWorkManager;

        public MyService(IUnitOfWorkManager unitOfWorkManager)
        {
            _unitOfWorkManager = unitOfWorkManager;
        }
        
        public virtual async Task FooAsync()
        {
            using (var uow = _unitOfWorkManager.Begin(
                requiresNew: true, isTransactional: false
            ))
            {
                //...


                SignInManager.Sign....
                await uow.CompleteAsync();
            }
        }
    }
}

```

**Comment by sahvey** [comment]
@maliming 
I got httpcontext exception.
![Abp_4](https://user-images.githubusercontent.com/46441777/197538798-7816ec91-1900-4ccf-8489-e5dd22a69fe4.jpg)

**Comment by maliming** [comment]
hi

Full exception stack, Thanks

**Comment by sahvey** [comment]
@maliming 
I am not getting any clear error.

 at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.<LoadAsync>d__11.MoveNext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<EnsureCollectionLoadedAsync>d__35`1.MoveNext()
   at Volo.Abp.Domain.Repositories.RepositoryExtensions.<EnsureCollectionLoadedAsync>d__0`3.MoveNext()
   at Volo.Abp.Identity.IdentityUserStore.<GetClaimsAsync>d__44.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<GetClaimsAsync>d__104.MoveNext()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__14`1.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.<ProceedAsync>d__7.MoveNext()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__2.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.<GenerateClaimsAsync>d__10.MoveNext()
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`2.<GenerateClaimsAsync>d__5.MoveNext()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__14`1.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.<ProceedAsync>d__7.MoveNext()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__2.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.<CreateAsync>d__9.MoveNext()
   at Volo.Abp.Identity.AbpUserClaimsPrincipalFactory.<CreateAsync>d__7.MoveNext()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__14`1.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.<ProceedAsync>d__7.MoveNext()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__2.MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   at Volo.Abp.IdentityServer.AspNetIdentity.AbpUserClaimsFactory`1.<CreateAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<CreateUserPrincipalAsync>d__26.MoveNext()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<SignInWithClaimsAsync>d__33.MoveNext()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<SignInOrTwoFactorAsync>d__58.MoveNext()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__38.MoveNext()
   at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__39.MoveNext()
   at Volo.Abp.Identity.AspNetCore.AbpSignInManager.<PasswordSignInAsync>d__4.MoveNext()

**Comment by sahvey** [comment]
@maliming 
I am using your sample project. I made almost no changes. You should get a similar error if you use the same project. However, if you want, I can share the project with you.

**Comment by sahvey** [comment]
@maliming 
It doesn't add any [ERR] records to the log.txt file either.

**Comment by sahvey** [comment]
@maliming 
I am sharing the sample project with you below.

[abp-wpf.zip](https://github.com/abpframework/abp/files/9853798/abp-wpf.zip)

**Comment by maliming** [comment]
hi

The `SignInManager` is designed for the web application. I think you can't use it in wpf


```cs
System.InvalidOperationException: HttpContext must not be null.
   at Microsoft.AspNetCore.Identity.SignInManager`1.get_Context()
   at Microsoft.AspNetCore.Identity.SignInManager`1.SignInWithClaimsAsync(TUser user, AuthenticationProperties authenticationProperties, IEnumerable`1 additionalClaims)
   at Microsoft.AspNetCore.Identity.SignInManager`1.SignInOrTwoFactorAsync(TUser user, Boolean isPersistent, String loginProvider, Boolean bypassTwoFactor)
   at Microsoft.AspNetCore.Identity.SignInManager`1.PasswordSignInAsync(TUser user, String password, Boolean isPersistent, Boolean lockoutOnFailure)
   at Microsoft.AspNetCore.Identity.SignInManager`1.PasswordSignInAsync(String userName, String password, Boolean isPersistent, Boolean lockoutOnFailure)
   at Volo.Abp.Identity.AspNetCore.AbpSignInManager.PasswordSignInAsync(String userName, String password, Boolean isPersistent, Boolean lockoutOnFailure)
   at Acme.BookStore.Wpf.Views.MainWindow.Login() in C:\Users\malim\Desktop\abp-wpf\src\Acme.BookStore.Wpf\Views\MainWindow.xaml.cs:line 68
```
