### ISSUE TITLE
The entity type 'ExtraPropertyDictionary' requires a primary key to be defined.

### ISSUE THREAD

**Issue by fietiger** [abpframework/abp#14498]
* **ABP Framework version** :  6.0.
*  **User Interface** :    MVC 
* Database provider:EF Core /PostgreSQL 15.0
* Exception message and **stack trace**

``` Bash
[18:28:51 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "data": {},
  "validationErrors": null
}
[18:28:51 ERR] The entity type 'ExtraPropertyDictionary' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
System.InvalidOperationException: The entity type 'ExtraPropertyDictionary' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.NpgsqlModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.Initialize(AbpEfCoreDbContextInitializationContext initializationContext)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetDbSetAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetQueryableAsync()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Application.Services.AbstractKeyReadOnlyAppService`5.CreateFilteredQueryAsync(TGetListInput input)
   at Volo.Abp.Application.Services.AbstractKeyReadOnlyAppService`5.GetListAsync(TGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1422(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
```

* Steps needed to **reproduce** the problem.
I want to make a table to recored something atatched to a user.
In a module project.
In the Domain project of the module project define an entity such as following:
``` C#
    public class MachineAuth : FullAuditedEntity<Guid>
    {
        public Guid UserId { get; set; }    
        public int AuthorityLevel { get; set; }
    }
```
In EntityFrameworkCore project of the modle project add code like this:
``` C# 
        builder.Entity<MachineAuth>(b =>
        {
            b.ToTable(PwrLinearityDbProperties.DbTablePrefix + "_MachineAuths",
                PwrLinearityDbProperties.DbSchema);
            b.ConfigureByConvention(); //auto configure for the base class props
            b.HasOne<IdentityUser>().WithMany().HasForeignKey(b => b.UserId);
        });
```
I have added `Volo.Abp.Identity.Domain` package to access `IdentityUser`.
In Application.Contracts project define Dtos.
``` C#
    public class CreateUpdateMachineAuthDto
    {
        [Required]
        public Guid UserId { get; set; }

        [Required]
        public int AuthorityLevel { get; set; }

    }

    public class MachineAuthDto:FullAuditedEntityDto<Guid>
    {
        public Guid UserId { get; set; }
        
        public int AuthorityLevel { get; set; }
    }
```
Then interface of service:
``` C#
    public interface IMachineAuthService:
        ICrudAppService< //Defines CRUD methods
            MachineAuthDto, //Used to show books
            Guid, //Primary key of the book entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting
            CreateUpdateMachineAuthDto> //Used to create/update 
    , IApplicationService
    {

    }
```
And then in Application project
``` C#
    public class MachineAuthService :
    CrudAppService<
        MachineAuth, 
        MachineAuthDto, 
        Guid, 
        PagedAndSortedResultRequestDto, 
        CreateUpdateMachineAuthDto>, 
    IMachineAuthService 
    {
        public MachineAuthService(IRepository<MachineAuth, Guid> repository) : base(repository)
        {

        }
    }
```
Then in HttpApi project
``` C#
[Area(PwrLinearityRemoteServiceConsts.ModuleName)]
    [RemoteService(Name = PwrLinearityRemoteServiceConsts.RemoteServiceName)]
    [Route("api/Laser/MachineAuth")]
    public class MachineAuthController : PwrLinearityController, IMachineAuthService
    {

        private readonly IMachineAuthService _machineAuthService;

        public MachineAuthController(IMachineAuthService sampleAppService)
        {
            _machineAuthService = sampleAppService;
        }
        [HttpPost]
        public Task<MachineAuthDto> CreateAsync(CreateUpdateMachineAuthDto input)
        {
            return _machineAuthService.CreateAsync(input);
        }

        [HttpDelete]
        [Route("{id}")]
        public Task DeleteAsync(Guid id)
        {
            return _machineAuthService.DeleteAsync(id);
        }
        [HttpGet]
        [Route("{id}")]
        public Task<MachineAuthDto> GetAsync(Guid id)
        {
            return _machineAuthService.GetAsync(id);
        }
        [HttpGet]

        public Task<PagedResultDto<MachineAuthDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return _machineAuthService.GetListAsync(input);
        }
        [HttpPut]
        [Route("{id}")]
        public Task<MachineAuthDto> UpdateAsync(Guid id, CreateUpdateMachineAuthDto input)
        {
            return _machineAuthService.UpdateAsync(id, input);
        }
    }
```
Run Auth Server and HttpApi.Host of the Main project. Swagger interface will show.
But when I tried to trig `Task<PagedResultDto<MachineAuthDto>> GetListAsync(PagedAndSortedResultRequestDto input)` on swagger page. Error ocurred.

**Comment by maliming** [comment]
Please share a project that uses SqlServer.

**Comment by fietiger** [comment]
> Please share a project that uses SqlServer.

Thanks for reply.I have tried to add same entity to main app project . Every thing seems ok.
I will prepare a project that uses SqlServer.

**Comment by fietiger** [comment]
I found my way to  fix this while preparing a project that uses SqlServer.
1. Add `Volo.Abp.Identity.EntityFrameworkCore`  to `EntityFrameworkCore`  project of the module.
2. Call `builder.ConfigureIdentity();` first. The `OnModelCreating` in EntityFrameworkCore  project of the module like this.
``` C# 
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.ConfigureIdentity();
        builder.ConfigurePwrLinearity();
    }
```
