### ISSUE TITLE
7.0.0-rc1 LocalizationResourceExtensions.AddVirtualJson System.MissingMethodException

### ISSUE THREAD

**Issue by jprodriguez-nbs** [abpframework/abp#14654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using 7.0.0-rc1, after updating all libraries from a .net 6 and volo abp 6.0.1 application to .net 7 and volo abp 7.0.0.-rc1, the following exception happens:

`Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module o16a.Web.o16aWebModule, o16a.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: An exception was thrown while activating OcppWebSocketManager.OcppMessageHandler -> o16a.Operation.EvrsEventManager -> Microsoft.Extensions.Localization.StringLocalizer`1[[o16a.Localization.o16aResource, o16a.Domain.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Localization.AbpStringLocalizerFactory.. See the inner exception for details.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating OcppWebSocketManager.OcppMessageHandler -> o16a.Operation.EvrsEventManager -> Microsoft.Extensions.Localization.StringLocalizer`1[[o16a.Localization.o16aResource, o16a.Domain.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Localization.AbpStringLocalizerFactory.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Localization.ResourceManagerStringLocalizerFactory, Microsoft.Extensions.Options.IOptions`1[Volo.Abp.Localization.AbpLocalizationOptions], System.IServiceProvider, Volo.Abp.Localization.External.IExternalLocalizationStore)' on type 'AbpStringLocalizerFactory'.
 ---> System.MissingMethodException: Method not found: 'Volo.Abp.Localization.LocalizationResource Volo.Abp.Localization.LocalizationResourceExtensions.AddVirtualJson(Volo.Abp.Localization.LocalizationResource, System.String)'.
   at Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule.<>c.<ConfigureServices>b__1_1(AbpLocalizationOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Volo.Abp.Localization.AbpStringLocalizerFactory..ctor(ResourceManagerStringLocalizerFactory innerFactory, IOptions`1 abpLocalizationOptions, IServiceProvider serviceProvider, IExternalLocalizationStore externalLocalizationStore)
   at lambda_method1739(Closure, Object[])
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass12_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)   at o16a.Web.o16aWebModule.OnApplicationInitialization(ApplicationInitializationContext context) in D:\evrs_git\o16a\aspnet-core\src\o16a.Web\o16aWebModule.cs:line 559
   at Volo.Abp.Modularity.AbpModule.OnApplicationInitializationAsync(ApplicationInitializationContext context)
   at o16a.Web.o16aWebModule.<>n__0(ApplicationInitializationContext context)
   at o16a.Web.o16aWebModule.OnApplicationInitializationAsync(ApplicationInitializationContext context) in D:\evrs_git\o16a\aspnet-core\src\o16a.Web\o16aWebModule.cs:line 589
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.InitializeAsync(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModulesAsync()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.InitializeAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplicationAsync(IApplicationBuilder app)
   at o16a.Web.Program.Main(String[] args) in D:\evrs_git\o16a\aspnet-core\src\o16a.Web\Program.cs:line 65`

### Version

7.0.0-rc1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

The application is based on the samples and was working fine in .net 6.0 volo.abp 6.0.1
The only change has been:

- target .net 7
- Update ms libraries to 7.0.0
- Update volo.abp libraries to 7.0.0-rc.1

I have not update LeptonXLite, it is using 1.0.0

**Comment by maliming** [comment]
> I have not update LeptonXLite, it is using 1.0.0

Can you try to update it too?

**Comment by muhlisatac** [comment]
[same issue here](https://github.com/abpframework/abp/issues/14649)
