### ISSUE TITLE
Using abp DbMigrator configure DbContext OwnsMany to create database and seed data has System.InvalidOperationException

### ISSUE THREAD

**Issue by zyknow** [abpframework/abp#14689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

owned entity containing DateTime properties,run DbMigrator project got exception,
use PostgreSql db,and also test mysql,it has same exception

i create the recurrence  repository for this exception : https://github.com/zyknow/AbpDbTemp

this is console detail
``` cs
[14:54:01 INF] Creating initial migration...
[14:54:02 INF] ABP CLI (https://abp.io)
[14:54:02 INF] Creating initial migrations...
[14:54:07 INF] Initial migrations are created.
[14:54:11 INF] Started database migrations...
[14:54:11 INF] Migrating schema for host database...
Unhandled exception. System.InvalidOperationException: The entity type 'LibraryPath' cannot be configured as owned because it has already been configured as a non-owned. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.  See https://aka.ms/efcore-docs-owned for more information.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.CanSetIsOwned(Boolean owned, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalForeignKeyBuilder.IsOwnership(Nullable`1 ownership, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasOwnership(TypeIdentity& targetEntityType, MemberIdentity& navigation, Nullable`1 inverse, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasOwnership(TypeIdentity& typeIdentity, MemberIdentity navigation, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsManyBuilder[TRelatedEntity](TypeIdentity ownedType, MemberIdentity navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsMany[TRelatedEntity](Expression`1 navigationExpression, Action`1 buildAction)
   at AbpDbTemp.EntityFrameworkCore.AbpDbTempDbContext.<>c.<OnModelCreating>b__37_0(EntityTypeBuilder`1 b) in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.EntityFrameworkCore\EntityFrameworkCore\AbpDbTempDbContext.cs:line 94
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at AbpDbTemp.EntityFrameworkCore.AbpDbTempDbContext.OnModelCreating(ModelBuilder builder) in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.EntityFrameworkCore\EntityFrameworkCore\AbpDbTempDbContext.cs:line 90
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.MigrateAsync(DatabaseFacade databaseFacade, CancellationToken cancellationToken)
   at AbpDbTemp.EntityFrameworkCore.EntityFrameworkCoreAbpDbTempDbSchemaMigrator.MigrateAsync() in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.EntityFrameworkCore\EntityFrameworkCore\EntityFrameworkCoreAbpDbTempDbSchemaMigrator.cs:line 29
   at AbpDbTemp.Data.AbpDbTempDbMigrationService.MigrateDatabaseSchemaAsync(Tenant tenant) in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.Domain\Data\AbpDbTempDbMigrationService.cs:line 95
   at AbpDbTemp.Data.AbpDbTempDbMigrationService.MigrateAsync() in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.Domain\Data\AbpDbTempDbMigrationService.cs:line 52
   at AbpDbTemp.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.DbMigrator\DbMigratorHostedService.cs:line 34
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at AbpDbTemp.DbMigrator.Program.Main(String[] args) in F:\ZyProject\Abp\AbpDbTemp\src\AbpDbTemp.DbMigrator\Program.cs:line 30
   at AbpDbTemp.DbMigrator.Program.<Main>(String[] args)
```

### Reproduction Steps

domain
---
`agg.root`
```cs
public class Library : FullAuditedAggregateRoot<Guid>
{
    public string Title { get; set; }
    public LibraryType LibraryType { get; set; }
    public bool AllUserAllow { get; set; }
    public ICollection<LibraryPath> LibraryPaths { get; set; }

}
```

`owned entity`
```cs
public class LibraryPath
{
    public string DirPath { get; set; }
    public DateTime? LastModifyTime { get; set; } // comment this line ,run DbMigrator project can success
}
```

`DbContext`
```cs
public class AbpCalDbContext :
    AbpDbContext<AbpCalDbContext>,
    IIdentityProDbContext,
    ISaasDbContext
{
    /* Add DbSet properties for your Aggregate Roots / Entities here. */

    #region Entities from the modules

    /* Notice: We only implemented IIdentityProDbContext and ISaasDbContext
     * and replaced them for this DbContext. This allows you to perform JOIN
     * queries for the entities of these modules over the repositories easily. You
     * typically don't need that for other modules. But, if you need, you can
     * implement the DbContext interface of the needed module and use ReplaceDbContext
     * attribute just like IIdentityProDbContext and ISaasDbContext.
     *
     * More info: Replacing a DbContext of a module ensures that the related module
     * uses this DbContext on runtime. Otherwise, it will use its own DbContext class.
     */

    // Identity
    public DbSet<IdentityUser> Users { get; set; }
    public DbSet<IdentityRole> Roles { get; set; }
    public DbSet<IdentityClaimType> ClaimTypes { get; set; }
    public DbSet<OrganizationUnit> OrganizationUnits { get; set; }
    public DbSet<IdentitySecurityLog> SecurityLogs { get; set; }
    public DbSet<IdentityLinkUser> LinkUsers { get; set; }

    // SaaS
    public DbSet<Tenant> Tenants { get; set; }
    public DbSet<Edition> Editions { get; set; }
    public DbSet<TenantConnectionString> TenantConnectionStrings { get; set; }

    #endregion
    // Heavens Feel
    public DbSet<Library> Libraries { get; set; }
    public AbpCalDbContext(DbContextOptions<AbpCalDbContext> options)
        : base(options)
    {

    }
    public static class HeavensFeelConsts
    {
        public const string DbTablePrefix = "App_";

        public const string DbSchema = null;
    }
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        /* Include modules to your migration db context */

        builder.ConfigurePermissionManagement();
        builder.ConfigureSettingManagement();
        builder.ConfigureBackgroundJobs();
        builder.ConfigureAuditLogging();
        builder.ConfigureIdentityPro();
        builder.ConfigureOpenIddict();
        builder.ConfigureFeatureManagement();
        builder.ConfigureLanguageManagement();
        builder.ConfigureSaas();
        builder.ConfigureTextTemplateManagement();
        builder.ConfigureBlobStoring();
        builder.ConfigureGdpr();

        /* Configure your own tables/entities inside here */

        //builder.Entity<YourEntity>(b =>
        //{
        //    b.ToTable(AbpCalConsts.DbTablePrefix + "YourEntities", AbpCalConsts.DbSchema);
        //    b.ConfigureByConvention(); //auto configure for the base class props
        //    //...
        //});

        if (builder.IsHostDatabase())
        {
            builder.Entity<Library>(b =>
            {
                b.ToTable(HeavensFeelConsts.DbTablePrefix + "Libraries", HeavensFeelConsts.DbSchema);
                b.ConfigureByConvention();
                b.OwnsMany(f => f.LibraryPaths, fr =>
                {
                    fr.ToTable(HeavensFeelConsts.DbTablePrefix + "LibraryPaths", HeavensFeelConsts.DbSchema);
                    fr.Property<int>("Id");
                    fr.HasKey("Id");
                });
            });
        }
    }
}
```

### Expected behavior

DbMigrator success Migrate

### Actual behavior

i got this System.InvalidOperationException

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

How about this?

```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Owned<LibraryPath>();

    base.OnModelCreating(modelBuilder);

    builder.Entity<Library>(b =>
    {
        b.ToTable(HeavensFeelConsts.DbTablePrefix + "Libraries", HeavensFeelConsts.DbSchema);
        b.ConfigureByConvention();
        b.OwnsMany(f => f.LibraryPaths, fr =>
        {
            fr.ToTable(HeavensFeelConsts.DbTablePrefix + "LibraryPaths", HeavensFeelConsts.DbSchema);
            fr.Property<int>("Id");
            fr.HasKey("Id");
        });
    });
}


```

**Comment by zyknow** [comment]
> hi
> 
> How about this?
> 
> ```cs
> protected override void OnModelCreating(ModelBuilder modelBuilder)
> {
>     modelBuilder.Owned<LibraryPaths>();
> 
>     base.OnModelCreating(modelBuilder);
> 
>     builder.Entity<Library>(b =>
>     {
>         b.ToTable(HeavensFeelConsts.DbTablePrefix + "Libraries", HeavensFeelConsts.DbSchema);
>         b.ConfigureByConvention();
>         b.OwnsMany(f => f.LibraryPaths, fr =>
>         {
>             fr.ToTable(HeavensFeelConsts.DbTablePrefix + "LibraryPaths", HeavensFeelConsts.DbSchema);
>             fr.Property<int>("Id");
>             fr.HasKey("Id");
>         });
>     });
> }
> ```
yes,this code can success,what it's problem?

**Comment by maliming** [comment]
`modelBuilder.Owned<LibraryPaths>();` is the key.

**Comment by zyknow** [comment]
> 

ok ,thanks

**Comment by zyknow** [comment]
@maliming 
i remove the `base.OnModelCreating(builder)` method and builder.Owned<LibraryPath>(),also can success running by DbMigrator,what is the happened for `base.OnModelCreating(builder)`, couldbe  cause by abp converter ？
![image](https://user-images.githubusercontent.com/49929368/202130222-cb4a24ae-febd-4c52-a896-a9aa3b8741e6.png)
