### ISSUE TITLE
[Commercial/Suite] AppService template is missing reference to Abp.Volo.Caching causes AppService & Tests to fail

### ISSUE THREAD

**Issue by gpl-ajackson** [abpframework/abp#14830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When generating an entity/page with Suite the generated AppService is missing a package reference to Abp.Volo.Caching required for the declaration:
`private readonly IDistributedCache<DepotExcelDownloadTokenCacheItem, string> _excelDownloadTokenCache;`

Fixing this error by adding the package allows the AppService to run successfully, but the tests fail with a DI resolution failure:

`Autofac.Core.DependencyResolutionException: An exception was thrown while activating CloudBiz.DepotModule.Depots.DepotsAppService.

Autofac.Core.DependencyResolutionException
An exception was thrown while activating CloudBiz.DepotModule.Depots.DepotsAppService.
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Volo.Abp.AbpTestBaseWithServiceProvider.GetRequiredService[T]()
   at CloudBiz.DepotModule.Depots.DepotsAppServiceTests..ctor() in /Users/ashjackson/Git/CloudBiz_Dev/CloudBiz/aspnet-core/modules/CloudBiz.DepotModule/test/CloudBiz.DepotModule.Application.Tests/Depots/DepotApplicationTests.cs:line 17
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

Autofac.Core.DependencyResolutionException
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'CloudBiz.DepotModule.Depots.DepotsAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Caching.IDistributedCache`2[CloudBiz.DepotModule.Depots.DepotExcelDownloadTokenCacheItem,System.String] excelDownloadTokenCache' of constructor 'Void .ctor(CloudBiz.DepotModule.Depots.IDepotRepository, CloudBiz.DepotModule.Depots.DepotManager, Volo.Abp.Caching.IDistributedCache`2[CloudBiz.DepotModule.Depots.DepotExcelDownloadTokenCacheItem,System.String])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass12_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.<>c__DisplayClass8_0`3.<EnableInterfaceInterceptors>b__1(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
`

### Reproduction Steps

- Generate new project with pro application template.
- Use Suite to generate an AggigrateRoot entity with Excel Download option.
- Observe compilation error due to missing package.
- Add Abp.Volo.Caching package to application project.
- Observe project compiles & runs.
- Observe that tests fail.

### Expected behavior

Package reference to Abp.Volo.Caching should be added to all projects where needed.

### Actual behavior

Package is not added.

### Version

6.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

macOS

**Comment by realLiangshiwei** [comment]
Hi,

I will create an internal issue for this. we don't talk about Commercial here,thanks. : )

> Add Abp.Volo.Caching package to application project.

You may need to add `[DependsOn(typeof(AbpCachingModule))]` to your module class.
