### ISSUE TITLE
Problem with creating the project using the -tiered option

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1491]
Guys I am having a issue when I create the ABP Webapplication Project using the ABP CLI V0.18.1 I am getting the following error when running the Db Migrator I am not getting this error every single time but every 2nd project i create has this error 

````
18:16:55 ERR] Invalid object name 'AbpBackgroundJobs'.
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'AbpBackgroundJobs'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
   at Volo.Abp.BackgroundJobs.EntityFrameworkCore.EfCoreBackgroundJobRepository.GetWaitingListAsync(Int32 maxResultCount) in D:\github\abp\modules\background-jobs\src\Volo.Abp.BackgroundJobs.EntityFrameworkCore\Volo\Abp\BackgroundJobs\EntityFrameworkCore\EfCoreBackgroundJobRepository.cs:line 27
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Abp.BackgroundJobs.BackgroundJobStore.GetWaitingJobsAsync(Int32 maxResultCount) in D:\github\abp\modules\background-jobs\src\Volo.Abp.BackgroundJobs.Domain\Volo\Abp\BackgroundJobs\BackgroundJobStore.cs:line 38
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at Volo.Abp.BackgroundJobs.BackgroundJobWorker.DoWork() in D:\github\abp\framework\src\Volo.Abp.BackgroundJobs\Volo\Abp\BackgroundJobs\BackgroundJobWorker.cs:line 42
   at Volo.Abp.BackgroundWorkers.PeriodicBackgroundWorkerBase.Timer_Elapsed(Object sender, EventArgs e) in D:\github\abp\framework\src\Volo.Abp.BackgroundWorkers\Volo\Abp\BackgroundWorkers\PeriodicBackgroundWorkerBase.cs:line 42
ClientConnectionId:d25a5efa-6e9d-4182-b130-47d3a6c61571
Error Number:208,State:1,Class:16
[18:16:55 ERR] ---------- Exception Data ----------
[18:16:55 ERR] HelpLink.ProdName = Microsoft SQL Server
[18:16:55 ERR] HelpLink.ProdVer = 14.00.2027
[18:16:55 ERR] HelpLink.EvtSrc = MSSQLServer
[18:16:55 ERR] HelpLink.EvtID = 208
[18:16:55 ERR] HelpLink.BaseHelpUrl = http://go.microsoft.com/fwlink
[18:16:56 ERR] HelpLink.LinkId = 20476
[18:16:56 INF] Executing database seed...
[18:17:02 INF] Successfully completed database migrations.
````

C:\Program Files\dotnet\dotnet.exe (process 464) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

**Comment by vnetonline** [comment]
if i build the solution before running the DbMigrator project it works. So this error only occurs when You run the Solution without building first.

there must be some dependency which causes it to fail the first time around

**Comment by hikalkan** [comment]
Hmmm.. it seems we should disable background jobs for the dbmigrator project. @maliming can you handle it?

**Comment by maliming** [comment]
I will disable the background job. 

@vnetonline But I can't reproduce your question. Can you provide detailed recurring steps?

**Comment by vnetonline** [comment]
Steps to reproduce

1. create new web application project using the ABP CLI with -tiered option 
2. Set Db Migrator project as default
3. Press Play without Building the project.

This should give you the result below, if you can't reproduce i will record video for you and send it via a link.

**Comment by maliming** [comment]
@vnetonline  Still can't reproduce.
![123](https://user-images.githubusercontent.com/6908465/61574808-40a96c80-aaf7-11e9-91b5-8ffcd0aadbff.gif)

**Comment by vnetonline** [comment]
run it in Debug mode without building 

also let me know how you created this Gif and i will do the same on my environment and attach it here

**Comment by maliming** [comment]
> run it in Debug mode without building

Not quite understand. You can use ScreenToGif to record the screen.

https://www.screentogif.com/

**Comment by vnetonline** [comment]
@maliming here is the recording on a new solution created using ABP CLI with the following command 

`abp new Acme.BookStore - tiered`

![Problem_with_AbpBackgroundJobs](https://user-images.githubusercontent.com/15242923/61575724-b111b700-ab12-11e9-8472-e5079b4f4add.gif)

**Comment by maliming** [comment]
hi @vnetonline 

I think that disabling background jobs won't solve your problem. Can you try it?
```
public override void ConfigureServices(ServiceConfigurationContext context)
{
	Configure<BackgroundJobOptions>(options => options.IsJobExecutionEnabled = false);
}
```

**Comment by vnetonline** [comment]
Which file is this method in ?

**Comment by maliming** [comment]
`MyProjectNameDbMigratorModule.cs` DbMigratorModule

**Comment by maliming** [comment]
@vnetonline How is the result?

**Comment by vnetonline** [comment]
disabling the job seems to work

**Comment by vnetonline** [comment]
@maliming any advise?

**Comment by maliming** [comment]
I will disable background jobs in the migration project in the template.
