### ISSUE TITLE
No connection is active/available to service this operation

### ISSUE THREAD

**Issue by abdullahshaqaliah** [abpframework/abp#14993]
ABP Framework version 5.3.3

Hi
When application running i get the following errors
```
2022-12-07 14:03:39.352 +02:00 [ERR] No connection is active/available to service this operation: SET AbpInbox_Default, mc: 1/1/0, mgr: 10 of 10 available, clientName: S92-205-24-250, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), v: 2.2.4.27433
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SET AbpInbox_Default, mc: 1/1/0, mgr: 10 of 10 available, clientName: S92-205-24-250, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), v: 2.2.4.27433
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2760
--- End of stack trace from previous location ---
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.WaitForAcquireAsync(IReadOnlyDictionary`2 tryAcquireTasks) in /_/DistributedLock.Redis/RedLock/RedLockAcquire.cs:line 144
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.TryAcquireAsync() in /_/DistributedLock.Redis/RedLock/RedLockAcquire.cs:line 60
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.TryAcquireAsync()
   at Medallion.Threading.Redis.RedisDistributedLock.TryAcquireAsync(CancellationToken cancellationToken) in /_/DistributedLock.Redis/RedisDistributedLock.cs:line 73
   at Medallion.Threading.Internal.BusyWaitHelper.WaitAsync[TState,TResult](TState state, Func`3 tryGetValue, TimeoutValue timeout, TimeoutValue minSleepTime, TimeoutValue maxSleepTime, CancellationToken cancellationToken) in /_/DistributedLock.Core/Internal/BusyWaitHelper.cs:line 29
   at Medallion.Threading.Internal.Helpers.Convert[TDerived,TBase](ValueTask`1 task, ValueTaskConversion _) in /_/DistributedLock.Core/Internal/Helpers.cs:line 24
   at Volo.Abp.DistributedLocking.MedallionAbpDistributedLock.TryAcquireAsync(String name, TimeSpan timeout, CancellationToken cancellationToken)
   at Volo.Abp.EventBus.Boxes.InboxProcessor.RunAsync()
   at Volo.Abp.EventBus.Boxes.InboxProcessor.TimerOnElapsed(AbpAsyncTimer arg)
   at Volo.Abp.Threading.AbpAsyncTimer.Timer_Elapsed()
2022-12-07 14:03:39.352 +02:00 [ERR] ---------- Exception Data ----------
Redis-Multiplexer-Connects = 1/1/0
Redis-Manager = 10 of 10 available
Redis-Client-Name = S92-205-24-250
Redis-ThreadPool-IO-Completion = (Busy=0,Free=1000,Min=4,Max=1000)
Redis-ThreadPool-Workers = (Busy=3,Free=32764,Min=4,Max=32767)
Redis-Busy-Workers = 3
Redis-Version = 2.2.4.27433
redis-command = SET AbpInbox_Default
request-sent-status = WaitingToBeSent

2022-12-07 14:03:40.690 +02:00 [FTL] AuthServer.Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnPostApplicationInitializationModuleLifecycleContributor phase of the module Horizon.Academic.AcademicHttpApiHostModule, Horizon.Academic.HttpApi.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: No connection is active/available to service this operation: SET Migration_Academic, mc: 1/1/0, mgr: 10 of 10 available, clientName: S92-205-24-250, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), v: 2.2.4.27433. See the inner exception for details.
 ---> StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SET Migration_Academic, mc: 1/1/0, mgr: 10 of 10 available, clientName: S92-205-24-250, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), v: 2.2.4.27433
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2760
--- End of stack trace from previous location ---
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.WaitForAcquireAsync(IReadOnlyDictionary`2 tryAcquireTasks) in /_/DistributedLock.Redis/RedLock/RedLockAcquire.cs:line 144
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.TryAcquireAsync() in /_/DistributedLock.Redis/RedLock/RedLockAcquire.cs:line 60
   at Medallion.Threading.Redis.RedLock.RedLockAcquire.TryAcquireAsync()
   at Medallion.Threading.Redis.RedisDistributedLock.TryAcquireAsync(CancellationToken cancellationToken) in /_/DistributedLock.Redis/RedisDistributedLock.cs:line 73
   at Medallion.Threading.Internal.BusyWaitHelper.WaitAsync[TState,TResult](TState state, Func`3 tryGetValue, TimeoutValue timeout, TimeoutValue minSleepTime, TimeoutValue maxSleepTime, CancellationToken cancellationToken) in /_/DistributedLock.Core/Internal/BusyWaitHelper.cs:line 29
   at Medallion.Threading.Internal.Helpers.Convert[TDerived,TBase](ValueTask`1 task, ValueTaskConversion _) in /_/DistributedLock.Core/Internal/Helpers.cs:line 24
   at Volo.Abp.DistributedLocking.MedallionAbpDistributedLock.TryAcquireAsync(String name, TimeSpan timeout, CancellationToken cancellationToken)
   at Horizon.Shared.Hosting.Microservices.DbMigrations.EfCore.PendingEfCoreMigrationsChecker`1.LockAndApplyDatabaseMigrationsAsync() in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\EfCore\PendingEfCoreMigrationsChecker.cs:line 45
   at Horizon.Shared.Hosting.Microservices.DbMigrations.PendingMigrationsCheckerBase.TryAsync(Func`1 task, Int32 retryCount) in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\PendingMigrationsCheckerBase.cs:line 13
   at Horizon.Shared.Hosting.Microservices.DbMigrations.PendingMigrationsCheckerBase.TryAsync(Func`1 task, Int32 retryCount) in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\PendingMigrationsCheckerBase.cs:line 21
   at Horizon.Shared.Hosting.Microservices.DbMigrations.PendingMigrationsCheckerBase.TryAsync(Func`1 task, Int32 retryCount) in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\PendingMigrationsCheckerBase.cs:line 28
   at Horizon.Shared.Hosting.Microservices.DbMigrations.PendingMigrationsCheckerBase.TryAsync(Func`1 task, Int32 retryCount) in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\PendingMigrationsCheckerBase.cs:line 28
   at Horizon.Shared.Hosting.Microservices.DbMigrations.EfCore.PendingEfCoreMigrationsChecker`1.CheckAndApplyDatabaseMigrationsAsync() in F:\vs\Web\HorizonFramework\src\BuildingBlocks\Horizon.Shared.Hosting.Microservices\DbMigrations\EfCore\PendingEfCoreMigrationsChecker.cs:line 40
   at Horizon.Academic.AcademicHttpApiHostModule.OnPostApplicationInitializationAsync(ApplicationInitializationContext context) in F:\vs\Web\HorizonFramework\src\MicroServices\Horizon.Academic.HttpApi.Host\AcademicHttpApiHostModule.cs:line 76
   at Volo.Abp.Modularity.OnPostApplicationInitializationModuleLifecycleContributor.InitializeAsync(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModulesAsync()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.InitializeAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplicationAsync(IApplicationBuilder app)
   at Horizon.Academic.Program.Main(String[] args) in F:\vs\Web\HorizonFramework\src\MicroServices\Horizon.Academic.HttpApi.Host\Program.cs:line 44
```

**Comment by maliming** [comment]
hi

Is your Redis server available?

Can you try to clear the Redis cache?

**Comment by abdullahshaqaliah** [comment]
Hi
Yes its available 
But when restart the Redis the application will be working again but this issue always happen.
The os is widnows 2019 standrad

**Comment by maliming** [comment]
This sounds like an environment issue.
