### ISSUE TITLE
Volo.Abp.AbpintializationException - Volo.Abp.Dapper related

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#15143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am migrating a 3.1 version to 5.3, but after i completed copying the files, dbmigrator and host project cannot run and keep getting below errors:

	StackTrace	"   at Volo.Abp.Modularity.ModuleManager.<InitializeModulesAsync>d__4.MoveNext()\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Volo.Abp.AbpApplicationBase.<InitializeModulesAsync>d__19.MoveNext()\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Volo.Abp.AbpApplicationWithInternalServiceProvider.<InitializeAsync>d__7.MoveNext()\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task…	string

### Reproduction Steps

I took a day to add code step by step, finally found the wired issue:

when adding  Volo.Abp.Dapper into entityframeworkCore project, the error will occur.
1) using cli create a empty project
     abp new xxx-u angular --version 5.3.0
2) init migrations
3) add  nuget reference Volo.Abo.Dapper into EntityFrameworkCore 
4) run migrator project to create database

### Expected behavior

no errors

### Actual behavior

exception happens

### Known Workarounds

no

### Version

5.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

[aspnet-core.zip](https://github.com/abpframework/abp/files/10243949/aspnet-core.zip)

attached an error pirjhect

**Comment by maliming** [comment]
Please share the full error logs. The logs you're shared it incomplete.

**Comment by evenlee** [comment]
Hi @maliming I've attached a demo project in the of my post, I just find a workaround to ignore the error, which is downgrade the abp dapper package to 5.3, below is the error if we use newest version:
     2022-12-16 16:25:25.187 +08:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule, Volo.Abp.BackgroundJobs, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null: Method not found: 'System.Threading.Tasks.Task`1<Volo.Abp.ApplicationInitializationContext> Volo.Abp.BackgroundWorkers.BackgroundWorkersApplicationInitializationContextExtensions.AddBackgroundWorkerAsync(Volo.Abp.ApplicationInitializationContext)'.. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Volo.Abp.ApplicationInitializationContext> Volo.Abp.BackgroundWorkers.BackgroundWorkersApplicationInitializationContextExtensions.AddBackgroundWorkerAsync(Volo.Abp.ApplicationInitializationContext)'.
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule.OnApplicationInitializationAsync(ApplicationInitializationContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule.OnApplicationInitializationAsync(ApplicationInitializationContext context)
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.InitializeAsync(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModulesAsync()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.InitializeAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplicationAsync(IApplicationBuilder app)
   at SmartScan.API.Program.Main(String[] args) in /Volumes/Data/aspnet-core/src/SmartScan.API.HttpApi.Host/Program.cs:line 37
