### ISSUE TITLE
Is it bug in single-layered framework ?

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#15163]
I add `DataSeederContributor` into the entity folder and run `dotnet ef database update` but data seeding does not work and 
I don't find data seeding info on the single-layered framework. Most are about the layered framework.

**Comment by washyn** [comment]
The data seed only works when you run the migration project.

**Comment by maliming** [comment]
> I don't find data seeding info on the single-layered framework. Most are about the layered framework.

https://github.com/abpframework/abp/blob/dev/templates/app-nolayers/aspnet-core/MyCompanyName.MyProjectName.Mvc/Program.cs#L53

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/6908465/208799791-347bd2a1-0ce1-42ab-b05e-a52ef28619dc.png">

**Comment by KaungZawHtet** [comment]
abp version = 7.0.0-rc.4
os = mac
dotnet version = 7.0.101
Database = MySql
Database Name = BookStore

Even though migration is successful, this error is always shown. (Database Name is BookStore)

```
[17:23:23 ERR] An error occurred using the connection to database 'BookStore' on server 'localhost'.
[17:23:23 ERR] Unknown database 'BookStore'
MySqlConnector.MySqlException (0x80004005): Unknown database 'BookStore'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 962
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 568
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 386
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 97
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 127
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 923
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 422
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextWithTransactionAsync(IUnitOfWork unitOfWork)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetDbSetAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetListAsync(Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.FeatureManagement.StaticFeatureSaver.UpdateChangedFeatureGroupsAsync(IEnumerable`1 featureGroupRecords)
   at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
   at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
   at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule.<>c__DisplayClass6_0.<<SaveStaticFeaturesToDatabaseAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
[17:23:23 ERR] ---------- Exception Data ----------
Server Error Code = 1049
SqlState = 42000
```

**Comment by washyn** [comment]
when you use mysql you have to create the database manually and the command will run the migration to create the database

**Comment by KaungZawHtet** [comment]
@washyn I don't get your point. Actually, I think, the database doesn't need to be created manually. What's happening here is that the migration command automatically created the database by showing this error.

**Comment by washyn** [comment]
In mysql you have to create the database manually, the migrations will create only the tables, I don't know if it is different in more recent versions

**Comment by Simcon** [comment]
I use Postgres and see a similar error. This is in 7 rc5 with the no layers app. The database gets created successfully but the error is confusing.

![image](https://user-images.githubusercontent.com/1893351/209188896-94c6d9a5-a19b-4546-9750-513b36f2081b.png)

**Comment by maliming** [comment]
hi

I will confirm that.

**Comment by maliming** [comment]
hi

Please try to migrate by `dotnet run --migrate-database`


The application needs to connect to a database. Run the following command in the `MyCompanyName.MyProjectName` directory:

````bash
dotnet run --migrate-database
````

https://github.com/abpframework/abp/pull/13985

**Comment by KaungZawHtet** [comment]
yes, error happens

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/15208 will resolve the problem.
