### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 (Bad Request) When the uploaded file exceeds 130M

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the uploaded file exceeds 130M . The system send a error:
Failed to load resource: the server responded with a status of 400 (Bad Request) 
But it is normal when the uploaded file 120M. My upload code as following:
```cs
public async Task<IActionResult> OnPostAsync()
        {
            string uniqueFileName = null;
            if (UploadFileDto.File != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, UploadFilePath);
                uniqueFileName =  UploadFileDto.File.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await UploadFileDto.File.CopyToAsync(fileStream);
                }
            }
            return Page();
        }
web.config as following:
<configuration>
<system.web>
        <httpRuntime maxRequestLength="1048576" />
   </system.web>
   <system.webServer>
     <security>
       <requestFiltering removeServerHeader="true">
          <requestLimits maxAllowedContentLength="1073741824" />
       </requestFiltering>
     </security>
   </system.webServer>
</configuration>
```

### Version

6.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please try without IIS.

https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0

**Comment by xiaoyuer1015** [comment]
> 
Thanks! 
But Our APP has been published to IIS.Is there any other solution？

**Comment by maliming** [comment]
> Failed to load resource: the server responded with a status of 400 (Bad Request)

What's the full error log?

**Comment by maliming** [comment]
> Failed to load resource: the server responded with a status of 400 (Bad Request)

What's the full error log?

**Comment by maliming** [comment]
> Failed to load resource: the server responded with a status of 400 (Bad Request)

What's the full error log?

**Comment by xiaoyuer1015** [comment]
```cs
2022-12-27 16:02:04.186 +08:00 [INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 16:02:04.186 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Uploads/UploadFile - - - 200 - text/html;+charset=utf-8 6.0666ms
2022-12-27 16:02:13.747 +08:00 [INF] Request starting HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundaryiPFEk79SE478Ypx8 140860369
2022-12-27 16:02:14.747 +08:00 [WRN] System.IO.InvalidDataException: Multipart body length limit 134217728 exceeded.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.MultiTenancy.FormTenantResolveContributor.GetTenantIdOrNameFromHttpContextOrNullAsync(ITenantResolveContext context, HttpContext httpContext)
   at Volo.Abp.AspNetCore.MultiTenancy.HttpTenantResolveContributorBase.ResolveFromHttpContextAsync(ITenantResolveContext context, HttpContext httpContext)
   at Volo.Abp.AspNetCore.MultiTenancy.HttpTenantResolveContributorBase.ResolveAsync(ITenantResolveContext context)
2022-12-27 16:02:14.747 +08:00 [INF] Executing endpoint '/Uploads/UploadFile'
2022-12-27 16:02:14.747 +08:00 [INF] Route matched with {page = "/Uploads/UploadFile", controller = "", area = "", action = ""}. Executing page /Uploads/UploadFile
2022-12-27 16:02:14.748 +08:00 [INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2022-12-27 16:02:14.748 +08:00 [INF] Antiforgery token validation failed. Unable to read the antiforgery request token from the posted form.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: Unable to read the antiforgery request token from the posted form.
 ---> System.IO.InvalidDataException: Multipart body length limit 134217728 exceeded.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
2022-12-27 16:02:14.748 +08:00 [INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
2022-12-27 16:02:14.748 +08:00 [INF] Executing StatusCodeResult, setting HTTP status code 400
2022-12-27 16:02:14.748 +08:00 [INF] Executed page /Uploads/UploadFile in 0.547ms
2022-12-27 16:02:14.748 +08:00 [INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 16:02:14.758 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/Error?httpStatusCode=400 - -
2022-12-27 16:02:14.760 +08:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:02:14.761 +08:00 [INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
2022-12-27 16:02:14.761 +08:00 [INF] Executing ViewResult, running view ~/Views/Error/Default.cshtml.
2022-12-27 16:02:14.763 +08:00 [INF] Request finished HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundaryiPFEk79SE478Ypx8 140860369 - 302 - - 1016.4303ms
2022-12-27 16:02:14.769 +08:00 [INF] Executed ViewResult - view ~/Views/Error/Default.cshtml executed in 7.8165ms.
2022-12-27 16:02:14.769 +08:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 8.6707ms
2022-12-27 16:02:14.769 +08:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:02:14.770 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Error?httpStatusCode=400 - - - 400 - text/html;+charset=utf-8 11.5478ms
2022-12-27 16:02:19.110 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css?_v=638077247332078832 - -
2022-12-27 16:02:19.111 +08:00 [INF] The file /__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css was not modified
2022-12-27 16:02:19.111 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css?_v=638077247332078832 - - - 304 - text/css 0.7258ms
2022-12-27 16:02:19.417 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/__bundles/toastr.js.map - -
2022-12-27 16:02:19.421 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/__bundles/toastr.js.map - - - 302 - - 3.9465ms
2022-12-27 16:02:19.422 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/Error?httpStatusCode=404 - -
2022-12-27 16:02:19.425 +08:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:02:19.426 +08:00 [INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
2022-12-27 16:02:19.427 +08:00 [INF] Executing ViewResult, running view ~/Views/Error/Default.cshtml.
2022-12-27 16:02:19.441 +08:00 [INF] Executed ViewResult - view ~/Views/Error/Default.cshtml executed in 14.206ms.
2022-12-27 16:02:19.441 +08:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 15.5309ms
2022-12-27 16:02:19.441 +08:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:02:19.442 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Error?httpStatusCode=404 - - - 404 - text/html;+charset=utf-8 19.7778ms

```

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/12336

**Comment by xiaoyuer1015** [comment]
I modified them according to your advice. But the bug is the same before. Is there something wrong with my modification？
the code as following:
 [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
        public class MyRequestSizeLimitAttribute : Attribute
        {
            public long Bytes { get; set; }

            public MyRequestSizeLimitAttribute(long bytes)
            {
                Bytes = bytes;
            }
        }

        [MyRequestSizeLimit(314572800)]
        public async Task<IActionResult> OnPostAsync()
        {
            string uniqueFileName = null;
            if (UploadFileDto.File != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, UploadFilePath);           
                uniqueFileName =  UploadFileDto.File.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await UploadFileDto.File.CopyToAsync(fileStream);
                }
            }
            return Page();
        }

**Comment by maliming** [comment]
Did you add the below code?

```cs
app.Use(async (httpContext, next) =>
{
    var endpoint = httpContext.GetEndpoint();
    var requestSizeLimitAttribute = endpoint?.Metadata.GetMetadata<MyRequestSizeLimitAttribute>();
    if (requestSizeLimitAttribute != null)
    {
        var maxRequestBodySizeFeature = httpContext.Features.Get<IHttpMaxRequestBodySizeFeature>();
        if (maxRequestBodySizeFeature != null)
        {
            maxRequestBodySizeFeature.MaxRequestBodySize = requestSizeLimitAttribute.Bytes;
        }
    }

    await next();
});
```

**Comment by xiaoyuer1015** [comment]
```cs
2022-12-27 16:33:29.125 +08:00 [INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 16:33:29.125 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Uploads/UploadFile - - - 200 - text/html;+charset=utf-8 18.5596ms
2022-12-27 16:33:37.509 +08:00 [INF] Request starting HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundarymBDq8XXfOANJ6v73 140860369
2022-12-27 16:33:38.286 +08:00 [WRN] System.IO.InvalidDataException: Multipart body length limit 134217728 exceeded.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.MultiTenancy.FormTenantResolveContributor.GetTenantIdOrNameFromHttpContextOrNullAsync(ITenantResolveContext context, HttpContext httpContext)
   at Volo.Abp.AspNetCore.MultiTenancy.HttpTenantResolveContributorBase.ResolveFromHttpContextAsync(ITenantResolveContext context, HttpContext httpContext)
   at Volo.Abp.AspNetCore.MultiTenancy.HttpTenantResolveContributorBase.ResolveAsync(ITenantResolveContext context)
2022-12-27 16:33:38.290 +08:00 [INF] Executing endpoint '/Uploads/UploadFile'
2022-12-27 16:33:38.290 +08:00 [INF] Route matched with {page = "/Uploads/UploadFile", controller = "", area = "", action = ""}. Executing page /Uploads/UploadFile
2022-12-27 16:33:38.290 +08:00 [INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2022-12-27 16:33:38.291 +08:00 [INF] Antiforgery token validation failed. Unable to read the antiforgery request token from the posted form.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: Unable to read the antiforgery request token from the posted form.
 ---> System.IO.InvalidDataException: Multipart body length limit 134217728 exceeded.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
2022-12-27 16:33:38.292 +08:00 [INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
2022-12-27 16:33:38.295 +08:00 [INF] Executing StatusCodeResult, setting HTTP status code 400
2022-12-27 16:33:38.296 +08:00 [INF] Executed page /Uploads/UploadFile in 5.6896ms
2022-12-27 16:33:38.296 +08:00 [INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 16:33:38.308 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/Error?httpStatusCode=400 - -
2022-12-27 16:33:38.309 +08:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:33:38.310 +08:00 [INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
2022-12-27 16:33:38.311 +08:00 [INF] Executing ViewResult, running view ~/Views/Error/Default.cshtml.
2022-12-27 16:33:38.313 +08:00 [INF] Request finished HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundarymBDq8XXfOANJ6v73 140860369 - 302 - - 804.0932ms
2022-12-27 16:33:38.319 +08:00 [INF] Executed ViewResult - view ~/Views/Error/Default.cshtml executed in 7.993ms.
2022-12-27 16:33:38.319 +08:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 9.1271ms
2022-12-27 16:33:38.319 +08:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:33:38.319 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Error?httpStatusCode=400 - - - 400 - text/html;+charset=utf-8 11.5685ms
2022-12-27 16:33:44.503 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css?_v=638077267970267831 - -
2022-12-27 16:33:44.504 +08:00 [INF] The file /__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css was not modified
2022-12-27 16:33:44.505 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/__bundles/LeptonXLite.Global.86BAF79B403556AB521761BF0380A67D.css?_v=638077267970267831 - - - 304 - text/css 1.8208ms
2022-12-27 16:33:44.700 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/__bundles/toastr.js.map - -
2022-12-27 16:33:44.706 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/__bundles/toastr.js.map - - - 302 - - 5.9966ms
2022-12-27 16:33:44.708 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost/Error?httpStatusCode=404 - -
2022-12-27 16:33:44.712 +08:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:33:44.712 +08:00 [INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
2022-12-27 16:33:44.714 +08:00 [INF] Executing ViewResult, running view ~/Views/Error/Default.cshtml.
2022-12-27 16:33:44.727 +08:00 [INF] Executed ViewResult - view ~/Views/Error/Default.cshtml executed in 13.0369ms.
2022-12-27 16:33:44.727 +08:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 15.1659ms
2022-12-27 16:33:44.727 +08:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2022-12-27 16:33:44.728 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Error?httpStatusCode=404 - - - 404 - text/html;+charset=utf-8 19.7960ms
```

**Comment by xiaoyuer1015** [comment]
> 
Thanks！
where do I put these code?

**Comment by xiaoyuer1015** [comment]
The following log show that uploadting the 124M file is OK!I don't know the reason.Very strange.
[INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 21:42:03.897 +08:00 [INF] Request finished HTTP/1.1 GET http://localhost/Uploads/UploadFile - - - 200 - text/html;+charset=utf-8 8.8543ms
2022-12-27 21:42:11.786 +08:00 [INF] Request starting HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundaryn8aABAbGIS6zIJ3p 127556579
2022-12-27 21:42:12.495 +08:00 [INF] Executing endpoint '/Uploads/UploadFile'
2022-12-27 21:42:12.495 +08:00 [INF] Route matched with {page = "/Uploads/UploadFile", controller = "", area = "", action = ""}. Executing page /Uploads/UploadFile
2022-12-27 21:42:12.495 +08:00 [INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2022-12-27 21:42:12.496 +08:00 [INF] Executing handler method Yokogawa.InfoSystem.Web.Pages.Uploads.UploadFileModel.OnPostAsync - ModelState is "Valid"
2022-12-27 21:42:12.585 +08:00 [INF] Executed handler method OnPostAsync, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2022-12-27 21:42:12.586 +08:00 [INF] Executed page /Uploads/UploadFile in 90.5472ms
2022-12-27 21:42:12.586 +08:00 [INF] Executed endpoint '/Uploads/UploadFile'
2022-12-27 21:42:12.605 +08:00 [INF] Request finished HTTP/1.1 POST http://localhost/Uploads/UploadFile multipart/form-data;+boundary=----WebKitFormBoundaryn8aABAbGIS6zIJ3p 127556579 - 200 - text/html;+charset=utf-8 819.5559ms

**Comment by maliming** [comment]
hi

Add code to your web host module.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/6908465/209743414-889be917-729e-4a1f-b359-57ba37868e50.png">

**Comment by xiaoyuer1015** [comment]
It means that the MultiTenancyConsts must be true?

**Comment by maliming** [comment]
Can you share a simple project?

**Comment by xiaoyuer1015** [comment]
Please Ref [Github AbpFileActionsDemo](https://github.com/rainmakerho/AbpFileActionsDemo)
I developed it based on it. Thank you!

**Comment by maliming** [comment]
Please test these code in your AbpGileActiomnsDemo project.

https://github.com/abpframework/abp/issues/12336#issuecomment-1108171660

**Comment by xiaoyuer1015** [comment]
I tried. It's the same as before.  :(

**Comment by maliming** [comment]
how can I reproduce the problem by using your AbpGileActiomnsDemo project?
Please share full steps.

**Comment by xiaoyuer1015** [comment]
> how can I reproduce the problem by using your AbpGileActiomnsDemo project? Please share full steps.

Thank you.
The upload file cannot exceed 128M. 
The problem is Solved. This is Multipart body length limit problem of Microsoft .net core. 
Please refer to https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0#upload-large-files-with-streaming
