### ISSUE TITLE
Initial impressions, bugs and feedback

### ISSUE THREAD

**Issue by Allann** [abpframework/abp#15279]
I used the details outlined in [Getting Started](https://abp.io/get-started) and chose the following settings:

* **ABP Framework version** - ABP CLI 7.0.0-rc.6
* **User Interface** type - Blazor WebAssembly
* database provider - EF Core - SQLite

`abp new Club -u blazor -dbms SQLite`

# Issues
## Included packages
```
➤ YN0000: ┌ Resolution step
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0032: │ nan@npm:2.17.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0002: │ @abp/bootstrap@npm:6.0.2 doesn't provide @popperjs/core (p8820a), requested by bootstrap
➤ YN0002: │ @abp/jquery-validation@npm:6.0.2 doesn't provide jquery (pbf8f5), requested by jquery-validation
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 13s 658ms
➤ YN0000: Done with warnings in 18s 979ms
```
Is it possible to update the templates so that a new user does not have to attempt to fix these issues?
## Error during Blazor Build steps
```
Building....:  (1/1)L:\club\src\Club.Blazor\Club.Blazor.csproj
Executing...: dotnet build L:\club\src\Club.Blazor\Club.Blazor.csproj
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored L:\club\src\Club.Application.Contracts\Club.Application.Contracts.csproj (in 803 ms).
  Restored L:\club\src\Club.HttpApi.Client\Club.HttpApi.Client.csproj (in 1.19 sec).
  Restored L:\club\src\Club.Blazor\Club.Blazor.csproj (in 3.9 sec).
  1 of 4 projects are up-to-date for restore.
  Club.Domain.Shared -> L:\club\src\Club.Domain.Shared\bin\Debug\netstandard2.0\Club.Domain.Shared.dll
  Club.Application.Contracts -> L:\club\src\Club.Application.Contracts\bin\Debug\netstandard2.0\Club.Application.Contracts.dll
  Club.HttpApi.Client -> L:\club\src\Club.HttpApi.Client\bin\Debug\netstandard2.0\Club.HttpApi.Client.dll
  Club.Blazor -> L:\club\src\Club.Blazor\bin\Debug\net6.0\Club.Blazor.dll
  Club.Blazor (Blazor output) -> L:\club\src\Club.Blazor\bin\Debug\net6.0\wwwroot

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.37
[17:29:10 ERR] Unable to load one or more of the requested types.
Method 'get_IsDynamic' in type 'Volo.Abp.AspNetCore.Mvc.Client.RemoteLocalizationContributor' from assembly 'Volo.Abp.AspNetCore.Mvc.Client.Common, Version=6.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IsDynamic' in type 'Volo.Abp.AspNetCore.Mvc.Client.RemoteLocalizationContributor' from assembly 'Volo.Abp.AspNetCore.Mvc.Client.Common, Version=6.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Volo.Abp.Cli.Bundling.BundlingService.FindBundleContributorsRecursively(Type module, Int32 level, List`1 bundleDefinitions) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 244
   at Volo.Abp.Cli.Bundling.BundlingService.FindBundleContributorsRecursively(Type module, Int32 level, List`1 bundleDefinitions) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 284
   at Volo.Abp.Cli.Bundling.BundlingService.FindBundleContributorsRecursively(Type module, Int32 level, List`1 bundleDefinitions) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 284
   at Volo.Abp.Cli.Bundling.BundlingService.FindBundleContributorsRecursively(Type module, Int32 level, List`1 bundleDefinitions) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 284
   at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild, String projectType) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 71
   at Volo.Abp.Cli.Commands.ProjectCreationCommandBase.RunBundleForBlazorWasmOrMauiBlazorTemplateAsync(ProjectBuildArgs projectArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\ProjectCreationCommandBase.cs:line 435
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 114
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 168
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 76
System.TypeLoadException: Method 'get_IsDynamic' in type 'Volo.Abp.AspNetCore.Mvc.Client.RemoteLocalizationContributor' from assembly 'Volo.Abp.AspNetCore.Mvc.Client.Common, Version=6.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
This one is a little more worrying as I haven't even had a chance to open the solution and I already have an error.  How am I going to have any confidence in the remaining Getting Started tutorial if I can't even perform the first one without error?

## Package Vulnerabilities
I continued and opening the solution in Rider (I don't use Visual Studio).  The first thing Rider did was to inform me of 10 vulnerabilities (1 low, 9 high) in the packages included.   

## DB Migrator
This worked and having it as the startup project was nice.  Well done.

## Running HOST
This also worked and showed the Swagger page.  Well done.

## Running Blazor Client
This also worked and showed the expected client.  Couple suggestions:
- Replacements
  - Have the `ProjectName` above the menu replaced with the name provided when the solution was created.  
  - Don't include the technology (e.g. .Blazor) on the browser tab title.  Club would have been better IMO since that was the name I chose.  Users don't care about technology.
- Error
  - according to the doco when using the abo cli I didn't need to run `bundle` so I did but when I clicked the **Login** link I received the following exception which I assume is due to the failed step and error above (since attempting the bundle step produces the same error):
```
An unhandled exception occurred while processing the request.
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'LeptonXLite.Global'!
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)
```

**Comment by onurpicakci** [comment]
Can you run `abp install-libs` in the project solution?

**Comment by realLiangshiwei** [comment]
Hi,

>　ABP Framework version - ABP CLI 7.0.0-rc.6
>   `abp new Club -u blazor -dbms SQLite`

You are using the ABP CLI RC version,  please try:  `abp new Club -u blazor -dbms SQLite --preview` or downgrade your CLI version

**Comment by Allann** [comment]
Thank you both for the quick response.  I shelved the original version and tried again from an empty folder with the --preview option.  This appears to go better with no obvious errors shown.  I must be doing something wrong since most others can get this working...
However, upon trying to Login I am presented with the following error:
```
Volo.Abp.AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'LeptonXLite.Global'!
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Themes_LeptonXLite_Layouts_Account.<>c__DisplayClass19_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCoreGeneratedDocument.Themes_LeptonXLite_Layouts_Account.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpOpenIddictMiddlewareExtension.<>c__DisplayClass0_0.<<UseAbpOpenIddictValidation>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
I found this a little strange since I was doing blazor and not mvc.  So I thought I'd try MVC and deleted the previous effort, and tried again.  using `abp new Club -dbms SQLite --preview` this time and it too generated without a hitch, migration too worked fine, but alas, was met with the same error.

So attempt 3 using the Basic Theme: 
```
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!
```

Finally, here is the output from the Blazor install, @onurpicakci  I was under the impression that was already done as can be seen by the YARN console messages.  But jsut in case I went back and tried Blazor again and included that step with no perceivable difference.
```
L:\Club-v2>abp new Club -u blazor -dbms SQLite --preview
[21:51:27 INF] ABP CLI 7.0.0-rc.6
[21:51:27 INF] Creating your project...
[21:51:27 INF] Project name: Club
[21:51:27 INF] Preview: yes
[21:51:27 INF] DBMS: SQLite
[21:51:27 INF] UI Framework: Blazor
[21:51:27 INF] Output folder: L:\Club-v2
[21:51:30 INF] Using cached template: app, version: 7.0.0-rc.6
[21:51:30 INF] Theme: LeptonXLite
[21:51:31 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[21:51:32 INF] 'Club' has been successfully created to 'L:\Club-v2'
[21:51:32 INF] Creating initial migrations...
[21:51:38 INF] Initial migrations are created.
[21:51:38 INF] Installing client-side packages...
[21:51:40 INF] Found 1 projects.
[21:51:40 INF] L:\Club-v2\src\Club.HttpApi.Host
[21:51:40 INF] Running Yarn on L:\Club-v2\src\Club.HttpApi.Host
➤ YN0000: ┌ Resolution step
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0032: │ nan@npm:2.17.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0002: │ @abp/bootstrap@npm:7.0.0-rc.6 doesn't provide @popperjs/core (pcc77e), requested by bootstrap
➤ YN0002: │ @abp/jquery-validation@npm:7.0.0-rc.6 doesn't provide jquery (p994b0), requested by jquery-validation
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 9s 768ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ y18n@npm:3.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:5.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:7.1.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 1ms
➤ YN0000: ┌ Link step
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 433ms
➤ YN0000: Done with warnings in 12s 258ms
[21:51:52 INF] Generating bundles for Blazor Wasm...
Building....:  (1/1)L:\Club-v2\src\Club.Blazor\Club.Blazor.csproj
Executing...: dotnet build L:\Club-v2\src\Club.Blazor\Club.Blazor.csproj
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored L:\Club-v2\src\Club.Application.Contracts\Club.Application.Contracts.csproj (in 836 ms).
  Restored L:\Club-v2\src\Club.HttpApi.Client\Club.HttpApi.Client.csproj (in 982 ms).
  Restored L:\Club-v2\src\Club.Blazor\Club.Blazor.csproj (in 3.58 sec).
  1 of 4 projects are up-to-date for restore.
  Club.Domain.Shared -> L:\Club-v2\src\Club.Domain.Shared\bin\Debug\netstandard2.0\Club.Domain.Shared.dll
  Club.Application.Contracts -> L:\Club-v2\src\Club.Application.Contracts\bin\Debug\netstandard2.0\Club.Application.Contracts.dll
  Club.HttpApi.Client -> L:\Club-v2\src\Club.HttpApi.Client\bin\Debug\netstandard2.0\Club.HttpApi.Client.dll
L:\Club-v2\src\Club.Blazor\Menus\ClubMenuContributor.cs(60,13): warning CS0162: Unreachable code detected [L:\Club-v2\src\Club.Blazor\Club.Blazor.csproj]
  Club.Blazor -> L:\Club-v2\src\Club.Blazor\bin\Debug\net7.0\Club.Blazor.dll
  Club.Blazor (Blazor output) -> L:\Club-v2\src\Club.Blazor\bin\Debug\net7.0\wwwroot

Build succeeded.

L:\Club-v2\src\Club.Blazor\Menus\ClubMenuContributor.cs(60,13): warning CS0162: Unreachable code detected [L:\Club-v2\src\Club.Blazor\Club.Blazor.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.69
[21:52:02 INF] Generating style bundle...
[21:52:02 INF] Style bundle has been generated successfully.
[21:52:02 INF] Generating script bundle...
[21:52:02 INF] Script bundle has been generated successfully.
[21:52:02 INF] Script and style references in the index.html file have been updated.
```

**Comment by Allann** [comment]
Example of the Basic theme MVC generation:
```
L:\Club-v2>abp new Club -dbms SQLite --preview --theme basic
[21:54:09 INF] ABP CLI 7.0.0-rc.6
[21:54:09 INF] Creating your project...
[21:54:09 INF] Project name: Club
[21:54:09 INF] Preview: yes
[21:54:10 INF] DBMS: SQLite
[21:54:10 INF] Output folder: L:\Club-v2
[21:54:11 INF] Using cached template: app, version: 7.0.0-rc.6
[21:54:11 INF] Theme: Basic
[21:54:11 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[21:54:11 INF] 'Club' has been successfully created to 'L:\Club-v2'
➤ YN0000: ┌ Resolution step
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0032: │ nan@npm:2.17.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0002: │ @abp/bootstrap@npm:6.0.2 doesn't provide @popperjs/core (p8820a), requested by bootstrap
➤ YN0002: │ @abp/jquery-validation@npm:6.0.2 doesn't provide jquery (pbf8f5), requested by jquery-validation
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 7s 505ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ y18n@npm:3.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:5.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:7.1.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 20ms
➤ YN0000: ┌ Link step
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 370ms
➤ YN0000: Done with warnings in 9s 945ms
[21:54:25 INF] Creating initial migrations...
[21:54:31 INF] Initial migrations are created.
[21:54:31 INF] Installing client-side packages...
[21:54:32 INF] Found 1 projects.
[21:54:32 INF] L:\Club-v2\src\Club.Web
[21:54:33 INF] Running Yarn on L:\Club-v2\src\Club.Web
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @abp/bootstrap@npm:6.0.2 doesn't provide @popperjs/core (p8820a), requested by bootstrap
➤ YN0002: │ @abp/jquery-validation@npm:6.0.2 doesn't provide jquery (pbf8f5), requested by jquery-validation
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 310ms

L:\Club-v2>abp install-libs
[22:02:42 INF] ABP CLI 7.0.0-rc.6
[22:02:43 INF] Found 1 projects.
[22:02:43 INF] L:\Club-v2\src\Club.Web
[22:02:43 INF] Running Yarn on L:\Club-v2\src\Club.Web
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @abp/bootstrap@npm:6.0.2 doesn't provide @popperjs/core (p8820a), requested by bootstrap
➤ YN0002: │ @abp/jquery-validation@npm:6.0.2 doesn't provide jquery (pbf8f5), requested by jquery-validation
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 278ms
```

**Comment by realLiangshiwei** [comment]
See:https://github.com/abpframework/abp/issues/14784

**Comment by Allann** [comment]
Thanks but I can't downgrade YARN, this is not a solution, I rely on it for my actual work.  I also don't want to create yet another VM just so I can try ABP, that seems a little counter productive to me.  Would it not be easier to fix the actual dependencies in ABP since it's still a release candidate?  Currently no-one (I assumed it was only me) can create a new project to try this out.

Btw, I came here due to the sponsorship provided and the mentions of Nick Chapsas think this has to be good.  But I'm thinking I'll go back to working with Orchard Core as this has not been a very simple process.  I'd love to give this a proper go when it's resolved though as it does sound awesome and if I can get it working there will more than likely be a commerical licence in the works.

**Comment by realLiangshiwei** [comment]
Hi,

If you want to use the latest version of YARN, you can check this: https://yarnpkg.com/getting-started/migration#step-by-step

That's all you need to do:

* Add [nodeLinker: node-modules](https://yarnpkg.com/configuration/yarnrc#nodeLinker) in your `.yarnrc.yml` file.
