### ISSUE TITLE
Using DigitalOcean Spaces in Volo.Abp.BlobStoring.Aws

### ISSUE THREAD

**Issue by ghulamostafa** [abpframework/abp#15280]
### Discussed in https://github.com/abpframework/abp/discussions/15277

<div type='discussions-op-text'>

<sup>Originally posted by **ghulamostafa** December 31, 2022</sup>
How can I use the package `Volo.Abp.BlobStoring.Aws` for storing media in DigitalOcean spaces? It supports other SDKs but I would like to know if there is a way I can use the from ABP.</div>

**Comment by realLiangshiwei** [comment]
Hi,

I think you can directly use it, It is compatible with S3API.
https://docs.digitalocean.com/products/spaces/reference/s3-sdk-examples
https://docs.abp.io/en/abp/latest/Blob-Storing-Aws

**Comment by ghulamostafa** [comment]
When I use the AWS Blob Storing from ABP and set the region as 
`Aws.Region = "https://fra1.digitaloceanspaces.com";`
I get the following error:
```
System.ArgumentException: Invalid region endpoint provided
   at Amazon.Internal.RegionEndpointProviderV3.GetNonstandardRegionEndpoint(String regionName)
   at Amazon.Internal.RegionEndpointProviderV3.GetRegionEndpoint(String regionName)
   at Amazon.RegionEndpoint.GetEndpoint(String systemName, String displayName)
   at Volo.Abp.BlobStoring.Aws.DefaultAmazonS3ClientFactory.GetAmazonS3Client(AwsBlobProviderConfiguration configuration)
   at Volo.Abp.BlobStoring.Aws.AwsBlobProvider.GetAmazonS3Client(BlobProviderArgs args)
   at Volo.Abp.BlobStoring.Aws.AwsBlobProvider.SaveAsync(BlobProviderSaveArgs args)
   at Volo.Abp.BlobStoring.BlobContainer.SaveAsync(String name, Stream stream, Boolean overrideExisting, CancellationToken cancellationToken)
   at Volo.Abp.BlobStoring.BlobContainerExtensions.SaveAsync(IBlobContainer container, String name, Byte[] bytes, Boolean overrideExisting, CancellationToken cancellationToken)
```

**Comment by realLiangshiwei** [comment]
You can try this:

```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAmazonS3ClientFactory))]
public class MyDefaultAmazonS3ClientFactory :DefaultAmazonS3ClientFactory
{
    public MyDefaultAmazonS3ClientFactory(IDistributedCache<AwsTemporaryCredentialsCacheItem> cache, IStringEncryptionService stringEncryptionService) : base(cache, stringEncryptionService)
    {
    }

    public override Task<AmazonS3Client> GetAmazonS3Client(AwsBlobProviderConfiguration configuration)
    {
        var config = new AmazonS3Config() { ServiceURL = configuration.Region };

        return Task.FromResult(new AmazonS3Client(configuration.AccessKeyId, configuration.SecretAccessKey, config));
    }
}
```

**Comment by ghulamostafa** [comment]
Thank you. It really helps.

**Comment by oliwerhelsen** [comment]
Hi guys,

@ghulamostafa i'm new to this framework. Just wonder where did you add this file or codesnippet to make it work with digitalocean spaces?

Best regards.

**Comment by ghulamostafa** [comment]
If you are using Blazor, then in your `<Solution>.Blazor` project, there would a `<Solution>BlazorModule.cs` file. Inside this file, you have to add method similar to this:
```csharp
private void ConfigureBlobStorageFile(ServiceConfigurationContext context, IConfiguration configuration)
    {
        context.Services.Configure<AbpBlobStoringOptions>(options =>
        {
            options.Containers.ConfigureDefault(container =>
            {
                container.UseAws(Aws =>
                {
                    Aws.AccessKeyId = configuration["DigitalOcean:AccessKeyId"];
                    Aws.SecretAccessKey = configuration["DigitalOcean:SecretAccessKey"];
                    Aws.UseCredentials = false;
                    Aws.Name = configuration["DigitalOcean:BucketName"];
                    Aws.Policy = "policy";
                    Aws.DurationSeconds = 1800;
                    Aws.ContainerName = configuration["DigitalOcean:BucketName"];
                });
            });
        });
    }
```

Where the configuration values can be either hardcoded or kept inside the `appsettings.json` file.

You have to call this method from `ConfigureServices` method of the same class.

Then in your `<Solution>.Application` project, create a service class. For example `DigitalOceanSpaceService` and paste the following:

```csharp
[RemoteService(IsEnabled = false)]
public class DigitalOceanSpaceService : ApplicationService, IDigitalOceanSpaceService
{
    private readonly IConfiguration _configuration;
    private readonly IAmazonS3 _s3Client;

    public DigitalOceanSpaceService(IConfiguration configuration)
    {
        _configuration = configuration;
        _s3Client = new AmazonS3Client(
            _configuration["DigitalOcean:AccessKeyId"],
            _configuration["DigitalOcean:SecretAccessKey"],
            new AmazonS3Config() { ServiceURL = _configuration["DigitalOcean:ServiceUrl"] });
    }

    public static string GeneratePreSignedURL(string objectPath)
    {

        if (string.IsNullOrEmpty(objectPath))
        {
            return "";
        }
        var s3Client = new AmazonS3Client(
            "<keys>",
            "<keys>",
            new AmazonS3Config() { ServiceURL = "https://fra1.digitaloceanspaces.com" });
        string urlString = "";
        try
        {
            urlString = s3Client.GetPreSignedURL(new GetPreSignedUrlRequest
            {
                BucketName = "<your-bucket-name>",
                Key = objectPath,
                Expires = DateTime.Now.AddDays(1)
            });
        }
        catch (AmazonS3Exception e)
        {
            Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
        }
        catch (Exception e)
        {
            Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
        }
        return urlString;
    }
}
```

Let me know if it helps.
