### ISSUE TITLE
error trying to install Blogging module using ABP CLI

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1548]
Steps to Reproduce

1. Create new web project using ABP CLI `"abp new  ACME.Software"`
2. Run DBMigrator by setting it to Default Stratup project
3. Run ABP CLI command "`abp add-module Volo.Blogging`"

```
log  : Restore completed in 48.91 sec for C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.Web\Amazing.Software.Web.csproj.
[15:49:16 INF] Successfully installed.
[15:49:18 INF] Installing '@abp/blogging' package to the project 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.Web\package.json'...
[15:49:19 INF] yarn add @abp/blogging
yarn add v1.16.0
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[15:49:36 INF] gulp
[15:49:52] Using gulpfile ~\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.Web\gulpfile.js
[15:49:53] Starting 'default'...
[15:50:07] Finished 'default' after 14 s
Your startup project 'Amazing.Software.EntityFrameworkCore.DbMigrations' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
Your startup project 'Amazing.Software.EntityFrameworkCore.DbMigrations' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

**Comment by maliming** [comment]
Your startup project 'Amazing.Software.EntityFrameworkCore.DbMigrations' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

**Comment by maliming** [comment]
I think we can refer to this package by default in the template.

**Comment by vnetonline** [comment]
Can you tell me how i can do this @maliming

**Comment by maliming** [comment]
@vnetonline  see: https://github.com/abpframework/abp/pull/1550/files

**Comment by vnetonline** [comment]
Still not working even if I add the reference into the project.

Because DB migrator has version 2.2.4 I had to install this version of the package and even then i get the following error 

```
[18:47:43 INF] Installing '@abp/blogging' package to the project 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.Web\package.json'...
[18:47:43 INF] yarn add @abp/blogging
yarn add v1.16.0
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[18:47:47 INF] gulp
[18:47:48] Using gulpfile ~\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.Web\gulpfile.js
[18:47:48] Starting 'default'...
[18:47:50] Finished 'default' after 1.81 s
Your startup project 'Amazing.Software.EntityFrameworkCore.DbMigrations' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
Your startup project 'Amazing.Software.EntityFrameworkCore.DbMigrations' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

**Comment by maliming** [comment]
Can you completely modify your project based on the above PR?

![image](https://user-images.githubusercontent.com/6908465/62115117-75cd7000-b2ea-11e9-8e99-ded65cf6c698.png)

**Comment by vnetonline** [comment]
yup i just did i am using the default template 

now i am getting 

```
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Amazing.Software.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.BuildConfiguration() in C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\SoftwareMigrationsDbContextFactory.cs:line 28
   at Amazing.Software.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.CreateDbContext(String[] args) in C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\SoftwareMigrationsDbContextFactory.cs:line 14
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\appsettings.json'.
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Amazing.Software.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.BuildConfiguration() in C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\SoftwareMigrationsDbContextFactory.cs:line 28
   at Amazing.Software.EntityFrameworkCore.SoftwareMigrationsDbContextFactory.CreateDbContext(String[] args) in C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\SoftwareMigrationsDbContextFactory.cs:line 14
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software\src\Amazing.Software.EntityFrameworkCore.DbMigrations\appsettings.json'.

C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Software>

















































```

**Comment by maliming** [comment]
Please follow https://github.com/abpframework/abp/pull/1553
