### ISSUE TITLE
Unhandled exception creating first module of tutorial

### ISSUE THREAD

**Issue by jlgarcia-vs** [abpframework/abp#15493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading abp cli to 7.0.1 version from 7.0.0, I can't create angular modules in the application.

### Reproduction Steps

After upgrading abp community to 7.0.1 version, I can't create angular modules in the application.

Just create a new project with:

`abp new Vs.Projects -u angular`

After the generations is finished, I try to create an angular module in angular directory with:

`yarn ng g m project --module app --routing --route projects`

After some seconds, I always receive the next error:

**An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
See "C:\Users\xxxxxx\AppData\Local\Temp\ng-Uz7lKL\angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

I've tried to uninstall abp cli and reinstall, but with the same result.

Complete error from log file:

[error] TypeError: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
    at GenerateCommandModule.getSchematics (D:\Development\Repositories\Vs.Projects\angular\node_modules\@angular\cli\src\commands\generate\cli.js:141:29)
    at getSchematics.next (<anonymous>)
    at GenerateCommandModule.getSchematicsToRegister (D:\Development\Repositories\Vs.Projects\angular\node_modules\@angular\cli\src\commands\generate\cli.js:158:76)
    at async GenerateCommandModule.builder (D:\Development\Repositories\Vs.Projects\angular\node_modules\@angular\cli\src\commands\generate\cli.js:35:55)
    at async runCommand (D:\Development\Repositories\Vs.Projects\angular\node_modules\@angular\cli\src\command-builder\command-runner.js:113:5)
    at async default_1 (D:\Development\Repositories\Vs.Projects\angular\node_modules\@angular\cli\lib\cli\index.js:70:16)

### Expected behavior

Create a simple angular module.

### Actual behavior

Error received:

An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
See "C:\Users\jlgar\AppData\Local\Temp\ng-Uz7lKL\angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

7.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by 15937823** [comment]
I also encountered the same problem, unable to create new components

**Comment by bariscanyilmaz** [comment]
Hi @jlgarcia-vs and @15937823 This issue solved by angular 15.1.3 update. Related issue angular/angular-cli#24586
