### ISSUE TITLE
[Blazor] First web access throw exception

### ISSUE THREAD

**Issue by nebula2** [abpframework/abp#15676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When first visiting a blazor (server) site in release, it *sometimes* happens that an exception is thrown and the page needs to be reloaded in order to function again.

At the moment I am not able to reproduce this consistently.

This issue is eventually related to #11703

Additional information:

logs
```text
2023-02-12 16:54:42 W TID:43 Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.myGQm0KxfC()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2023-02-12 16:54:42 E TID:43 Unhandled exception in circuit 'X3x_816hpKnSpoX77lZrPHS-S8ncjLBSR8uwc61Go5Y'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.myGQm0KxfC()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2023-02-12 16:54:42 W TID:43 Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
2023-02-12 16:54:42 W TID:43 Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.Navigation.MainSiderbar.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
2023-02-12 16:54:42 E TID:43 Unhandled exception in circuit 'X3x_816hpKnSpoX77lZrPHS-S8ncjLBSR8uwc61Go5Y'.
System.AggregateException: Exceptions were encountered while disposing components. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.Navigation.MainSiderbar.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)<---

2023-02-12 16:54:42 W TID:43 Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.dOOQkmPgOb()
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2023-02-12 16:54:42 E TID:43 Unhandled exception in circuit 'X3x_816hpKnSpoX77lZrPHS-S8ncjLBSR8uwc61Go5Y'.
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.dOOQkmPgOb()
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

browser console
```text
Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:3 
        
       Uncaught ReferenceError: $ is not defined
    at HTMLDocument.n (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:3:42)
Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1 
        
       [2023-02-12T16:54:42.720Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Components.Web.LeptonTheme.Components.ApplicationLayout.MainHeader.MainHeader.myGQm0KxfC()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
log @ Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1
Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1 [2023-02-12T16:54:42.721Z] Information: Connection disconnected.
Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1 
        
       Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at Nt.send (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:54577)
    at Ft._sendMessage (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:71300)
    at Ft._sendWithProtocol (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:71341)
    at Ft.send (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:71449)
    at Object.endInvokeJSFromDotNet (Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:134972)
    at Blazor.LeptonTheme.Global.085DD25D3AB73CD5E34A8656B14D77DE.js?_v=638118151655650127:1:3573
/Error?httpStatusCode=404:1 
       
Failed to load resource: the server responded with a status of 404 ()
```

### Reproduction Steps

TODO

### Expected behavior

Page loads normally

### Actual behavior

Somewhere in the process, a NullReferenceException is occuring and things go brr.

### Version

7.0.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

### Other information

- blazor project is hosted daemonized with nginx reverse proxy.
- postresql
- Same issue occured on abp version 6.0.2

**Comment by maliming** [comment]
Since it cannot be reproduced, there is nothing we can do about it now.
