### ISSUE TITLE
CLI - Error when running "abp update" (but "dotnet tool update -g Volo.Abp.Cli" works)

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#15711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP CLI 7.0.1 command `abp update` generates an error

Related to this issue:  #8095

### Reproduction Steps

Run `abp update` from the CLI

### Expected behavior

Should update without error

### Actual behavior

Generates the following error:

```
[11:42:16 ERR] Access to the path 'C:\WINDOWS\system32\LogFiles\WMI\RtBackup' is denied.
System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\LogFiles\WMI\RtBackup' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Volo.Abp.Cli.Commands.UpdateCommand.UpdateNugetPackages(CommandLineArgs commandLineArgs, String directory, String version) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 65
   at Volo.Abp.Cli.Commands.UpdateCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 44
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 168
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 76
```

### Regression?

It has worked before on ABP 6.*

### Known Workarounds

Run `dotnet tool update -g Volo.Abp.Cli`

### Version

7.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please run `abp update` command in your project folder.

**Comment by rqx110** [comment]
use `abp cli update`,  not `abp update`

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/CLI#cli

**Comment by tinonetic** [comment]
> hi
> 
> Please run `abp update` command in your project folder.

Then this documentation needs to be corrected: [ABP UPDATE Command](https://docs.abp.io/en/abp/latest/Upgrading#:~:text=Run%20this%20command%20in%20the%20terminal%20while%20you%20are%20in%20the%20root%20folder%20of%20your%20solution.)

![image](https://user-images.githubusercontent.com/8109147/219849213-e810e4e0-eb9a-416a-8ff9-8d1882220a38.png)
