### ISSUE TITLE
Cannot resolve parameter Indo.Assignments.IAssignmentRepository assignmentRepository

### ISSUE THREAD

**Issue by jpayne0061** [abpframework/abp#15745]
My app is having an issue resolving this interface at runtime. I cannot seem to figure it out.

Logs:

```
2023-02-19 07:37:48.245 -05:00 [ERR] An exception was thrown while activating Castle.Proxies.AssignmentAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.AssignmentAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Castle.Proxies.AssignmentAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Indo.Assignments.IAssignmentRepository assignmentRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Indo.Assignments.IAssignmentRepository, Indo.Assignments.AssignmentManager)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-02-19 07:37:48.246 -05:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Castle.Proxies.AssignmentAppServiceProxy

2023-02-19 07:37:48.246 -05:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2023-02-19 07:37:48.247 -05:00 [INF] Executed action Indo.Assignments.AssignmentAppService.GetListAsync (Indo.Application) in 5.7148ms
2023-02-19 07:37:48.247 -05:00 [INF] Executed endpoint 'Indo.Assignments.AssignmentAppService.GetListAsync (Indo.Application)'
2023-02-19 07:37:48.247 -05:00 [INF] Request finished HTTP/2 GET https://localhost:44323/api/app/assignment application/json - - 500 - application/json;+charset=utf-8 13.6546ms
2023-02-19 07:37:48.337 -05:00 [INF] Request starting HTTP/2 GET https://localhost:44323/themes/images/favicon.ico - -
2023-02-19 07:37:48.339 -05:00 [INF] Sending file. Request path: '/themes/images/favicon.ico'. Physical path: 'N/A'
2023-02-19 07:37:48.341 -05:00 [INF] Request finished HTTP/2 GET https://localhost:44323/themes/images/favicon.ico - - - 200 1150 image/x-icon 4.1549ms
```

App Service:

```
using Indo.Bookings;
using Indo.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;

namespace Indo.Assignments
{
    public class AssignmentAppService : IndoAppService, IAssignmentAppService
    {
        private readonly IAssignmentRepository _assignmentRepository;
        private readonly AssignmentManager _assignmentManager;

        public AssignmentAppService(IAssignmentRepository assignmentRepository, AssignmentManager assignmentManager)
        {
            _assignmentRepository = assignmentRepository;
            this._assignmentManager = assignmentManager;
        }

        public async Task<AssignmentDto> GetAsync(int id)
        {
            var obj = await _assignmentRepository.GetAsync(id);
            return ObjectMapper.Map<Assignment, AssignmentDto>(obj);
        }
        public async Task<List<AssignmentDto>> GetListAsync()
        {
            var queryable = await _assignmentRepository.GetQueryableAsync();
            var query = from booking in queryable
                        select new { booking };
            var queryResult = await AsyncExecuter.ToListAsync(query);
            var dtos = queryResult.Select(x =>
            {
                var dto = ObjectMapper.Map<Assignment, AssignmentDto>(x.booking);
                return dto;
            }).ToList();
            return dtos;
        }

        public async Task<AssignmentDto> CreateAsync(AssignmentDto input)
        {
            var obj = await _assignmentManager.CreateAsync(input.LicensePlaneNumber,
                input.CreationTime,
                input.DateImounded,
                input.Id);

            obj.LicensePlaneNumber = input.LicensePlaneNumber;
            obj.ClientReferenceId = input.ClientReferenceId;
            obj.DateImounded = input.DateImounded;
            obj.TowedAddress = input.TowedAddress;

            await _assignmentRepository.InsertAsync(obj);

            return ObjectMapper.Map<Assignment, AssignmentDto>(obj);
        }
        public async Task UpdateAsync(int id, AssignmentDto input)
        {
            var obj = await _assignmentRepository.GetAsync(id);

            obj.LicensePlaneNumber = input.LicensePlaneNumber;
            obj.ClientReferenceId = input.ClientReferenceId;
            obj.DateImounded = input.DateImounded;
            obj.TowedAddress  = input.TowedAddress;

            await _assignmentRepository.UpdateAsync(obj);
        }
        public async Task DeleteAsync(int id)
        {
            await _assignmentRepository.DeleteAsync(id);
        }
    }
}
```
App Service Interface:

```
using Indo.Bookings;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace Indo.Assignments
{
    public interface IAssignmentAppService : IApplicationService
    {
        Task<AssignmentDto> GetAsync(int id);

        Task<List<AssignmentDto>> GetListAsync();

        Task<AssignmentDto> CreateAsync(AssignmentDto input);

        Task UpdateAsync(int id, AssignmentDto input);

        Task DeleteAsync(int id);

    }
}

```

Domain model:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Volo.Abp.Domain.Entities.Auditing;

namespace Indo.Assignments
{
    public class Assignment : FullAuditedAggregateRoot<int>
    {
        public string LicensePlaneNumber { get; set; }
        public DateTime DateImounded { get; set; }
        public string TowedAddress { get; set; }
        public string ClientReferenceId { get; set; }

        protected Assignment()
        {

        }

        internal Assignment(int id, string licensePlaneNumber, DateTime dateImounded, string towedAddress, string clientReferenceId) :
            base(id)
        {
            LicensePlaneNumber = licensePlaneNumber;
            DateImounded = dateImounded;
            TowedAddress = towedAddress;
            ClientReferenceId = clientReferenceId;
        }

    }
}

```
Repository:

```
using Indo.Bookings;
using Indo.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

namespace Indo.Assignments
{
    public class EfCoreAssignmentsRepository : EfCoreRepository<IndoDbContext, Assignment, int>,
            IAssignmentRepository
    {
        public EfCoreAssignmentsRepository(IDbContextProvider<IndoDbContext> dbContextProvider)
            : base(dbContextProvider)
        {

        }
    }
}

```

Db context:

```
public DbSet<Assignment> Assignments { get; set; }  
```

**Comment by maliming** [comment]
hi

Please share the code of your `EntityFrameworkCore` module.

**Comment by jpayne0061** [comment]
hi, thanks, Here it is:

```
using Microsoft.EntityFrameworkCore;
using Indo.Users;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore.Modeling;
using Volo.Abp.Identity;
using Volo.Abp.Users.EntityFrameworkCore;
using Indo.Assignments;

namespace Indo.EntityFrameworkCore
{
    /* This is your actual DbContext used on runtime.
     * It includes only your entities.
     * It does not include entities of the used modules, because each module has already
     * its own DbContext class. If you want to share some database tables with the used modules,
     * just create a structure like done for AppUser.
     *
     * Don't use this DbContext for database migrations since it does not contain tables of the
     * used modules (as explained above). See IndoMigrationsDbContext for migrations.
     */
    [ConnectionStringName("Default")]
    public class IndoDbContext : AbpDbContext<IndoDbContext>
    {
        public DbSet<Assignment> Assignments { get; set; }  
        public DbSet<AppUser> Users { get; set; }

        /* Add DbSet properties for your Aggregate Roots / Entities here.
         * Also map them inside IndoDbContextModelCreatingExtensions.ConfigureIndo
         */

        public IndoDbContext(DbContextOptions<IndoDbContext> options)
            : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            /* Configure the shared tables (with included modules) here */

            builder.Entity<AppUser>(b =>
            {
                b.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users"); //Sharing the same table "AbpUsers" with the IdentityUser
                
                b.ConfigureByConvention();
                b.ConfigureAbpUser();

                /* Configure mappings for your additional properties
                 * Also see the IndoEfCoreEntityExtensionMappings class
                 */
            });

            /* Configure your own tables/entities inside the ConfigureIndo method */

            builder.ConfigureIndo();
        }
    }
}

```

**Comment by maliming** [comment]
hi

I mean the EF Core module instead of `DbContex`.

You can upload your project to GitHub as well.

**Comment by jpayne0061** [comment]
@maliming  hey, you can ignore. I'm closing this issue. 

I was considering using ABP framework for a project, but its just too abstracted and magical for me to work with. I've been spending a lot of time getting anything to work.

Thank you for your help.
