### ISSUE TITLE
Host terminated unexpectedly!

### ISSUE THREAD

**Issue by ydemir** [abpframework/abp#15744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp new [projectName] -u blazor-server

dotnet 7
abp cli 7.0.1

PM> Add-Migration first
Build started...
Build succeeded.
[01:03:46 INF] Starting web host.
[01:03:52 FTL] Host terminated unexpectedly!
Microsoft.Extensions.Hosting.HostAbortedException: The host was aborted.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.ThrowHostAborted()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at HaydeSoft.Languo.Blazor.Program.Main(String[] args) in C:\projects\src\[ProjectName].Blazor\Program.cs:line 36
To undo this action, use Remove-Migration.
PM> 

### Version

7.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

We fixed it in 7.1. You can change your `Program` code.

https://github.com/abpframework/abp/pull/14935
