### ISSUE TITLE
 "SaasEditions" already exists error for multiple dbContext in EntityFrameworkCoreTestModule 

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#15743]
* Your **ABP Framework version**. 5.3.3
* Your database provider : EF Core
* Exception message and **stack trace** if available (check the logs).
```
 SQLite Error 1: 'table "SaasEditions" already exists'.
  at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at MyCompany.ABC.EntityFrameworkCore.ABCEntityFrameworkCoreTestModule.CreateDatabaseAndGetConnection() in
```

* Steps needed to **reproduce** the problem.

- Create a new DbContext and move `ConfigureSaas()` in second dbcontext;

Please **write in English**.

I have two [Dbcontext ](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#fixing-the-tests)and run without error. But I cannot run test. and I got error : `Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'table "SaasEditions" already exists`

```
public class MyFirsDbContext :  AbpDbContext<MyFirsDbContext>,IHasEventInbox, IHasEventOutbox, IServicePriceDbContext
//IIdentityProDbContext,
//ISaasDbContext
{

}
```

```
[ReplaceDbContext(typeof(IIdentityProDbContext))]
[ReplaceDbContext(typeof(ISaasDbContext))]
[ConnectionStringName("Second")]
public class MySecondDbContext :AbpDbContext<MySecondDbContext>, IIdentityProDbContext, ISaasDbContext
{
 ...
    // SaaS
    public DbSet<Tenant> Tenants { get; set; }
    public DbSet<Edition> Editions { get; set; }
 ...
}
```

![image](https://user-images.githubusercontent.com/13360669/219879899-f056bf1a-aa24-463c-a223-7c909070df2c.png)

**Comment by maliming** [comment]
You can get help about ABP commercial at https://support.abp.io/
