### ISSUE TITLE
How to disable LocalEventBus in integration tests?

### ISSUE THREAD

**Issue by namtab00** [abpframework/abp#15951]
I'm trying to disable all local event bus handlers when running tests.

I cannot figure out how to replace the registration for `ILocalEventBus `to `NullLocalEventBus.Instance`

I've tried:

```csharp
public class MyApplicationTestModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        // disable local event bus
        context.Services.Replace(ServiceDescriptor.Singleton<ILocalEventBus, NullLocalEventBus>());
    }
}
```

but when running tests I'm getting:

```
Autofac.Core.Activators.Reflection.NoConstructorsFoundException
No accessible constructors were found for the type 'Volo.Abp.EventBus.Local.NullLocalEventBus'.
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.GetDefaultPublicConstructors(Type type)
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.FindConstructors(Type targetType)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ConfigurePipeline(IComponentRegistryServices componentRegistryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices)
   at Autofac.Core.Registration.ComponentRegistryBuilder.Build()
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionCommonExtensions.BuildServiceProviderFromFactory[TContainerBuilder](IServiceCollection services, Action`1 builderAction)
```

How do I **replace** the registration for `ILocalEventBus` (I'm guessing with lifetime singleton) to `NullLocalEventBus.Instance` ?

**Comment by maliming** [comment]
hi

```cs
// disable local event bus
context.Services.Replace(ServiceDescriptor.Singleton<ILocalEventBus>(NullLocalEventBus.Instance));
```
