### ISSUE TITLE
In a Docker container: Unable to configure HTTPS endpoint.

### ISSUE THREAD

**Issue by afresh** [abpframework/abp#16015]
**ABP Framework version**: 6.0.2
**Database provider(EF Core/MongoDB)**: EF Core
**Exception message** and **stack trace**:

```log
2023-03-20 19:31:25.681 +08:00 [INF] Starting IdentityServer4 version 4.1.2+997a6cdd643e46cd5762b710c4ddc43574cbec2e
2023-03-20 19:31:26.016 +08:00 [INF] Using the default authentication scheme Identity.Application for IdentityServer
2023-03-20 19:31:26.187 +08:00 [INF] Initialized all ABP modules.
2023-03-20 19:31:26.264 +08:00 [FTL] OneCard.IdentityServer terminated unexpectedly!
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at OneCard.Program.Main(String[] args) in /src/services/OneCard.IdentityServer/Program.cs:line 40
```

**Environment in Docker**:

* ASPNETCORE_ENVIRONMENT: "Production"
* ASPNETCORE_URLS: "https://+:443"

**In a development environment, ABP runs right. But how to set certificate in Docker's linux container?**

```csharp
    public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        var hostingEnvironment = context.Services.GetHostingEnvironment();

        if (!hostingEnvironment.IsDevelopment())
        {
            //var configuration = context.Services.GetConfiguration();

            PreConfigure<AbpIdentityServerBuilderOptions>(options =>
            {
                options.AddDeveloperSigningCredential = false;
            });

            PreConfigure<IIdentityServerBuilder>(builder =>
            {
                builder.AddSigningCredential(GetSigningCertificate(hostingEnvironment));
            });
        }
    }
```

Is it related to the above code?

**Comment by gterdem** [comment]
You can generate self-signed certificate using dotnet tool like:

`dotnet dev-certs https -v -ep myfile.pfx -p MY_PASSWORD`

Then you need to pass the **kestrel environment**, file with path and the password:
- Kestrel_Certificates_Default_Path: "filepath/myfile.pfx"
- Kestrel_Certificates_Default_Password: "MY_PASSWORD"

**Comment by afresh** [comment]
@gterdem Thank you very much! That solved my problem.

> You can generate self-signed certificate using dotnet tool like:
> 
> `dotnet dev-certs https -v -ep myfile.pfx -p MY_PASSWORD`
> 
> Then you need to pass the **kestrel environment**, file with path and the password:
> 
> * Kestrel_Certificates_Default_Path: "filepath/myfile.pfx"
> * Kestrel_Certificates_Default_Password: "MY_PASSWORD"

And kestrel environment in `appsettings.json` should be:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "cert.pem",
        "KeyPath": "key.pem"
      }
    }
  }
}
```

So, in `docker-compose.yml`, it should be:

* Kestrel__Certificates__Default__Path: "filepath/myfile.pfx"
* Kestrel__Certificates__Default__Password: "MY_PASSWORD"
