### ISSUE TITLE
BookStore-Modular Error in MongoDB!

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#16070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run the `Acme.BookStore.BookManagement.Web.Unified` project with `MongoDB` as the data storage, I encountered an error while trying to get a list of books, which seems to be caused by the Join operation. How should I handle this?

![image](https://user-images.githubusercontent.com/24971860/227470488-c1ea702d-1fdf-4f1d-966c-7f6347045aa9.png)

```csharp
[16:27:48 ERR] Expression of type 'System.Collections.Generic.IEnumerable`1[Acme.BookStore.BookManagement.Authors.Author]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author]' of method 'System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author] Where[Author](System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author], System.Linq.Expressions.Expression`1[System.Func`2[Acme.BookStore.BookManagement.Authors.Author,System.Boolean]])' (Parameter 'arg0')
System.ArgumentException: Expression of type 'System.Collections.Generic.IEnumerable`1[Acme.BookStore.BookManagement.Authors.Author]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author]' of method 'System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author] Where[Author](System.Linq.IQueryable`1[Acme.BookStore.BookManagement.Authors.Author], System.Linq.Expressions.Expression`1[System.Func`2[Acme.BookStore.BookManagement.Authors.Author,System.Boolean]])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.MethodCallExpression.Update(Expression object, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.BindEmbeddedPipeline(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.SerializationBinder.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.MethodCallBinders.JoinBinder.Bind(PipelineExpression pipeline, PipelineBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.MethodInfoMethodCallBinder`1.Bind(PipelineExpression pipeline, TBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindPipeline(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindPipeline(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindPipeline(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.PipelineBinder.Bind(Expression node, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Prepare(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Translate(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryableImpl`2.ToCursorAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Acme.BookStore.BookManagement.Books.BookAppService.GetListAsync(PagedAndSortedResultRequestDto input) in E:\github\abp-samples\BookStore-Modular\modules\book-management\src\Acme.BookStore.BookManagement.Application\Books\BookAppService.cs:line 82   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method2132(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Reproduction Steps

1. clone repository from github
2. switch data access to mongodb
3. run Unified project
4. login and open `book` page to get book list
5. Error occuring!

### Version

The lastest version

### User Interface

MVC

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi, you can try this:

```csharp
public async override Task<PagedResultDto<BookDto>>  GetListAsync(PagedAndSortedResultRequestDto input)
  {
      //Set a default sorting, if not provided
      if (input.Sorting.IsNullOrWhiteSpace())
      {
          input.Sorting = nameof(Book.Name);
      }

      //Get the IQueryable<Book> from the repository
      var queryable = await Repository.GetQueryableAsync();

      //Get the books
      var books = await AsyncExecuter.ToListAsync(
          queryable
              .OrderBy(input.Sorting)
              .Skip(input.SkipCount)
              .Take(input.MaxResultCount)
      );

      //Convert to DTOs
      var bookDtos = ObjectMapper.Map<List<Book>, List<BookDto>>(books);

      //Get a lookup dictionary for the related authors
      var authorDictionary = await GetAuthorDictionaryAsync(books);

      //Set AuthorName for the DTOs
      bookDtos.ForEach(bookDto => bookDto.AuthorName =
                       authorDictionary[bookDto.AuthorId].Name);

      //Get the total count with another query (required for the paging)
      var totalCount = await Repository.GetCountAsync();

      return new PagedResultDto<BookDto>(
          totalCount,
          bookDtos
      );
  }

private async Task<Dictionary<Guid, Author>> GetAuthorDictionaryAsync(List<Book> books)
{
    var authorIds = books
        .Select(b => b.AuthorId)
        .Distinct()
        .ToArray();

    var queryable = await _authorRepository.GetQueryableAsync();

    var authors = await AsyncExecuter.ToListAsync(
        queryable.Where(a => authorIds.Contains(a.Id))
    );

    return authors.ToDictionary(x => x.Id, x => x);
}
```
