### ISSUE TITLE
cli need to connect network,it download any file from where?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#1608]
Today I try to use abp cli,but got an error at below ,until I use a proxy in powershell.
abp cli need a network connecting ?
It download file from where?
Can it to be used locally?
Exclude the "new" commnad, is there any other command need network connecting?

``` powershell
PS D:\source\repos\Acme.BookStore> abp new Acme.BookStore
[14:58:49 INF] ABP CLI (https://abp.io)
[14:58:49 INF] Version 0.18.1 (Stable channel)
[14:58:55 INF] Creating a new project...
[14:58:55 INF] Project name: Acme.BookStore
[14:58:59 INF] Downloading template: mvc, version: 0.18.1
[14:59:07 ERR] Error while copying content to a stream.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, '与服务器的连接意 外终止'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)
   at System.Net.Http.NoWriteNoSeekStreamContent.<>c.<SerializeToStreamAsync>b__4_0(Task t, Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.DownloadTemplateFileContentAsync(TemplateDownloadInputDto input) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 110
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetAsync(String name, DatabaseProvider databaseProvider, String projectName, String version) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 63
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ProjectBuilder.cs:line 39
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 39
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 56
```

**Comment by maliming** [comment]
It depends on the speed and stability of your network connection to the abp.io server.
