### ISSUE TITLE
JsonException Err

### ISSUE THREAD

**Issue by snlyazilim** [abpframework/abp#16116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

2023-03-29 00:05:44.742 +03:00 [ERR] The JSON value could not be converted to Volo.Abp.Data.ExtraPropertyDictionary. Path: $ | LineNumber: 0 | BytePositionInLine: 2.
System.Text.Json.JsonException: The JSON value could not be converted to Volo.Abp.Data.ExtraPropertyDictionary. Path: $ | LineNumber: 0 | BytePositionInLine: 2.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.EntityFrameworkCore.ValueConverters.ExtraPropertiesValueConverter.DeserializeObject(String extraPropertiesAsJson, Type entityType)
   at lambda_method2858(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at SNLYazilim.OnMuhasebe.Commons.EFCoreCommonRepository`1.GetPagedListAsync[TKey](Int32 skipCount, Int32 maxResultCount, Expression`1 predicate, Expression`1 orderBy, Expression`1[] includesProperties)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at SNLYazilim.OnMuhasebe.Bankalar.BankaAppService.GetListAsync(BankaListParameterDto input) in D:\Projeler\src\SNLYazilim.OnMuhasebe.Application\Bankalar\BankaAppService.cs:line 26
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper, IUnitOfWorkManager unitOfWorkManager)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper, IUnitOfWorkManager unitOfWorkManager)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method2758(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Version

7.1.0

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
**Reproduction Steps**

**Comment by snlyazilim** [comment]
Hi

**......./Domain/Foos**

```
public class Foo: FullAuditedAggregateRoot<Guid>
    {
        public string Property1 { get; set; }
        public string Property2{ get; set; }
        public Guid? Too1Id { get; set; }
        public Guid? Too2Id { get; set; }
        public string Property3{ get; set; }
        public bool Property4{ get; set; }

        public Too Too1 { get; set; }
        public Too Too2 { get; set; }
    }

public interface IFooRepository : ICommonRepository<Foo>
    {
    }
```

**....../Domain/Commons**

```
public interface ICommonRepository<TEntity> : IRepository<TEntity, Guid>
        where TEntity : class, IEntity<Guid>
    {
        Task<TEntity> GetAsync(object id, Expression<Func<TEntity, bool>> predicate = null, params Expression<Func<TEntity, object>>[] includesProperties);
        Task<TEntity> GetAsync(Expression<Func<TEntity, bool>> predicate = null, params Expression<Func<TEntity, object>>[] includesProperties);
        Task<TEntity> GetAsync(object id, Expression<Func<TEntity, bool>> predicate = null);
        Task<List<TEntity>> GetPagedListAsync<TKey>(int skipCount, int maxResultCount, Expression<Func<TEntity, bool>> predicate = null, Expression<Func<TEntity, TKey>> orderBy = null,
            params Expression<Func<TEntity, object>>[] includesProperties);
        Task<List<TEntity>> GetPagedListAsync<TKey>(int skipCount, int maxResultCount, Expression<Func<TEntity, bool>> predicate = null, Expression<Func<TEntity, TKey>> orderBy = null);
        Task<List<TEntity>> GetPagedLastListAsync<TKey>(int skipCount, int maxResultCount, Expression<Func<TEntity, bool>> predicate = null, Expression<Func<TEntity, TKey>> orderBy = null,
          params Expression<Func<TEntity, object>>[] includesProperties);
        Task<string> GetCodeAsync(Expression<Func<TEntity, string>> propertySelecetor, Expression<Func<TEntity, bool>> predicate = null);
        Task<IList<TEntity>> FromSQLRawAsync(string sql, params object[] parameters);
        Task<bool> AnyAsync(Expression<Func<TEntity, bool>> predicate = null);
    }
}
```

**......../EntityFrameworkCore/Commons**

```
public class EFCoreCommonRepository<TEntity> : EfCoreRepository<AppDbContext, TEntity, Guid>, ICommonRepository<TEntity>
        where TEntity : class, IEntity<Guid>
    {

 public async Task<List<TEntity>> GetPagedListAsync<TKey>(int skipCount, int maxResultCount, Expression<Func<TEntity, bool>> predicate = null,
            Expression<Func<TEntity, TKey>> orderBy = null, params Expression<Func<TEntity, object>>[] includesProperties)
        {
            var queryable = await WithDetailsAsync(includesProperties);
            if (predicate != null)
                queryable = queryable.Where(predicate);

            if (orderBy != null)
                queryable = queryable.OrderBy(orderBy);

            return await queryable.Skip(skipCount).Take(maxResultCount).ToListAsync();

        }
}
```

**....../EntityFrameworkCore/Foos**

```
 public class EFCoreFooRepository : EFCoreCommonRepository<Foo>, IFooRepository
    {
        public EFCoreFooRepository(IDbContextProvider<AppDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }
```



I AppDbContext Added `Public DbSet<Foo> Foos {get;set;}`

**....../Application.Contracts**

```
public interface IFooAppService : ICrudAppService<SelectFooDto, ListFooDto, FooListParameterDto, CreateFooDto, UpdateFooDto, CodeParameterDto>
{

}

```

SelectFooDto ---> inheritance EntityDto<Guid>
ListFooDto --->  inheritance EntityDto<Guid>
FooListParameterDto -->inheritances PagedResultRequestDto, IEntityDto, IDurum
CreateFooDto ---> IEntityDto
UpdateFooDto ---> IEntityDto
CodeParameterDto ---> IEntityDto

**....../Application/Foos**

```

public class FooAppService : ...AppService, IFooAppService
{
private readonly IFooRepository _foorepository;

 public FooAppService (IFooRepository foorepository)
    {
        _foorepository = foorepository;
     }

 public virtual async Task<PagedResultDto<ListFooDto>> GetListAsync(FooListParameterDto input)
    {
        var entities = await _foorepository .GetPagedListAsync(input.SkipCount, input.MaxResultCount,
            x => x.Property4== input.Property4,
            x => x.Property1,
            x => x.Too1 , x => x.Too2);

        var totalCount = await _foorepository.CountAsync(b => b.Durum == input.Durum);

        return new PagedResultDto<ListFooDto>(totalCount, ObjectMapper.Map<List<Foo>, List<ListFooDto>>(entities));
    }

}

```

**AutoMapper Profile**

```

   CreateMap<Foo, SelectFooDto>()
           .ForMember(x => x.Too1Name, opt => opt.MapFrom(x => x.Too1.Name))
           .ForMember(x => x.Too2Name, opt => opt.MapFrom(x => x.Too2.Name));
        CreateMap<Foo, ListFooDto>()
           .ForMember(x => x.Too1Name, opt => opt.MapFrom(x => x.Too1.Name))
           .ForMember(x => x.Too2Name, opt => opt.MapFrom(x => x.Too2.Name));

        CreateMap<CreateFooDto, Foo>();
        CreateMap<UpdateFooDto, Foo>();
        CreateMap<SelectFooDto, CreateFooDto>();
        CreateMap<SelectFooDto, UpdateFooDto>();
```

**I am getting the error I mentioned above via Swagger**

**Comment by maliming** [comment]
I can't reproduce the problem with the code your shared.
