### ISSUE TITLE
elsa dashboard get method 404

### ISSUE THREAD

**Issue by aihui109** [abpframework/abp#16201]
abp 7.11 is not compatible with the elsa workflow dashboard(version 2.11) in the previous way, prompting https://localhost:44340/v1/elsaAuthentication/userinfo GET 404 ，abp 7.0.3 does not have this problem
![image](https://user-images.githubusercontent.com/37268088/230554907-1750256a-b416-4d1a-a6f5-9d46b5ee1179.png)

**Comment by maliming** [comment]
Exception message and stack trace if available (check the logs).
Steps needed to reproduce the problem.

**Comment by aihui109** [comment]
thinks, here is  stack trace:

```
[10:19:50 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}
[10:19:50 ERR] Error mapping types.
Mapping types:
List`1 -> IList`1
System.Collections.Generic.List`1[[Elsa.Models.WorkflowDefinition, Elsa.Abstractions, Version=2.10.2.2, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IList`1[[Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel, Elsa.Server.Api, Version=2.10.2.2, Culture=neutral, PublicKeyToken=null]]
AutoMapper.AutoMapperMappingException: Error mapping types.
Mapping types:
List`1 -> IList`1
System.Collections.Generic.List`1[[Elsa.Models.WorkflowDefinition, Elsa.Abstractions, Version=2.10.2.2, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IList`1[[Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel, Elsa.Server.Api, Version=2.10.2.2, Culture=neutral, PublicKeyToken=null]]
 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.
Mapping types:
WorkflowDefinition -> WorkflowDefinitionSummaryModel
Elsa.Models.WorkflowDefinition -> Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel
   at lambda_method3052(Closure, WorkflowDefinition, WorkflowDefinitionSummaryModel, ResolutionContext)
   at lambda_method3051(Closure, Object, IList`1, ResolutionContext)
   --- End of inner exception stack trace ---
   at lambda_method3051(Closure, Object, IList`1, ResolutionContext)
   at Elsa.Server.Api.Endpoints.WorkflowDefinitions.List.Handle(String ids, String searchTerm, Nullable`1 orderBy, Nullable`1 sortBy, Nullable`1 page, Nullable`1 pageSize, Nullable`1 version, CancellationToken cancellationToken)
   at lambda_method3041(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

It looks like an ELSA bug, but the problem disappears by rolling back ABP to 7.0.3。

**Comment by maliming** [comment]
You can try to add these mapper profiles.

https://github.com/search?q=repo%3Aelsa-workflows%2Felsa-core%20AutoMapperProfile&type=code

```
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.
Mapping types:
WorkflowDefinition -> WorkflowDefinitionSummaryModel
Elsa.Models.WorkflowDefinition -> Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel
  
```
