### ISSUE TITLE
nginx iis deploy  UnitWork RollBack

### ISSUE THREAD

**Issue by laosandegudai** [abpframework/abp#16209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction Steps

My program works fine locally, but not when deployed to a server.

nginx(https domain)=>IIS(http 80)=>abp,These are two different servers.
When I made a direct request from the iis server, the application was fine, but when I accessed it from the Internet through nginx, even though the http returned 200 and the data was modified, the application encountered an error and rolled back the data, causing the data update to fail.

nginx(https domain)=>abp(http 80),No host IIs.
When I deploy abp directly instead of host iis, it works with nginx.

### Description

Although 200 is returned on each request, UnitWork rolls back

```cs
[15:30:31 WRN] An exception occurred, but response has already started!
[15:30:31 ERR] Connection ID "18374686494167138418", Request ID "80000073-0003-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.EntityFrameworkCore.EfCoreTransactionApi.CommitAsync()
   at Volo.Abp.Uow.UnitOfWork.CommitTransactionsAsync() in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 374
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 164
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Uow\AbpUnitOfWorkMiddleware.cs:line 40
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\ExceptionHandling\AbpExceptionHandlingMiddleware.cs:line 34
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\ExceptionHandling\AbpExceptionHandlingMiddleware.cs:line 44
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore.MultiTenancy\Volo\Abp\AspNetCore\MultiTenancy\MultiTenancyMiddleware.cs:line 81
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Tracing\AbpCorrelationIdMiddleware.cs:line 27
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in E:\Develop\Codes\Sources\web\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\RequestLocalization\AbpRequestLocalizationMiddleware.cs:line 51
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

### Version

5.3.5

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> TaskCanceledException: A task was canceled.

This seems related to the caller.

**Comment by laosandegudai** [comment]
> > TaskCanceledException: A task was canceled.
> 
> This seems related to the caller.

Yes, I can see that. The same application works with SelfHost, but not with IIS hosting.
The client has received a return of 200, but the transaction is interrupted at this time, and the database is rolled back directly, which is not consistent with the result received by the client (200).

**Comment by maliming** [comment]
> The client has received a return of 200, but the transaction is interrupted at this time, and the database is rolled back directly, which is not consistent with the result received by the client (200).

This is fixed in the new version.

**Comment by laosandegudai** [comment]
> > The client has received a return of 200, but the transaction is interrupted at this time, and the database is rolled back directly, which is not consistent with the result received by the client (200).
> 
> This is fixed in the new version.

Thanks a lot. Is there a solution or idea to this problem? Because this problem has been bothering me for many days.

**Comment by berkansasmaz** [comment]
> > The client has received a return of 200, but the transaction is interrupted at this time, and the database is rolled back directly, which is not consistent with the result received by the client (200).
> 
> This is fixed in the new version.

@maliming Is there a workaround or linked PR on this?

**Comment by maliming** [comment]
@laosandegudai 

Please try with the latest version, and create a new issue if the problem still exists.

**Comment by yukinami** [comment]
I'm facing the problem with verison 8.1.1.  May I ask what exactly the proplem is?

**Comment by encasahealth** [comment]
I'm facing the same issue with krakend (as a proxy) and an ABP 9.2.2 backend.   Is there something I can check to troubleshoot the issue further?

**Comment by maliming** [comment]
hi @encasahealth 

Please create a new issue and share the debug logs.

https://abp.io/support/questions/8622/How-to-enable-Debug-logs-for-troubleshoot-problems

Thanks
