### ISSUE TITLE
`Authorize` attribute not able to use with `SignalRHub` for SignalR Hub

### ISSUE THREAD

**Issue by quannv108** [abpframework/abp#16217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Authorize` attribute not able to use with `SignalRHub` for SignalR Hub

### Reproduction Steps

create a hub with `Authorize` attribute and another attribute, ex: `SignalRHub` from https://www.nuget.org/packages/SignalRSwaggerGen#release-body-tab
example: 
```CSharp
[Authorize]
[SignalRHub] // enable this cause problem
public class MainHub : AbpHub
{}
```

### Expected behavior

2 attribute can be used at the same time without any problems

### Actual behavior

Exception message and stack trace if available.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Castle.DynamicProxy.Internal.AttributeUtil.GetArguments(IList`1 constructorArguments)
   at Castle.DynamicProxy.Internal.AttributeUtil.ReadAttributeValue(CustomAttributeTypedArgument argument)
   at Castle.DynamicProxy.Internal.AttributeUtil.GetArguments(IList`1 constructorArguments, Type[]& constructorArgTypes, Object[]& constructorArgs)
   at Castle.DynamicProxy.Internal.AttributeUtil.CreateInfo(CustomAttributeData attribute)
   at Castle.DynamicProxy.Internal.AttributeUtil.GetNonInheritableAttributes(MemberInfo member)+MoveNext()
   at Castle.DynamicProxy.Contributors.NonInheritableAttributesContributor.Generate(ClassEmitter emitter)
   at Castle.DynamicProxy.Generators.BaseClassProxyGenerator.GenerateType(String name, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass13_0.<GetProxyType>b__0(CacheKey cacheKey)
   at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetProxyType()
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.EnableClassInterceptors[TLimit,TConcreteReflectionActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registration, ProxyGenerationOptions options, Type[] additionalInterfaces)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.EnableClassInterceptors[TLimit,TConcreteReflectionActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registration)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.AddInterceptors[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, ServiceRegistrationActionList serviceRegistrationActionList, Type serviceType, IEnumerable`1 interceptors)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.InvokeRegistrationActions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, ServiceRegistrationActionList registrationActionList, Type serviceType, Type implementationType)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.ConfigureAbpConventions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, IModuleContainer moduleContainer, ServiceRegistrationActionList registrationActionList)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Register(ContainerBuilder builder, IServiceCollection services, Object lifetimeScopeTagForSingletons)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(ContainerBuilder builder, IServiceCollection services, Object lifetimeScopeTagForSingletons)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(ContainerBuilder builder, IServiceCollection services)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ServiceProviderFactoryAdapter`1.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.<>c__DisplayClass21_0`1.<ConfigureContainer>b__0()
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()

```

### Known Workarounds

```CSharp
[SignalRHub]
public interface IMainHubClient
{
}

[Authorize]
public class MainHub : AbpHub<IMainHubClient>
{
}
```

### Version

7.1.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Try to add `<PackageReference Include="Castle.Core" Version="5.1.1" />` to your project.
