### ISSUE TITLE
LeptonXLite 2.2.0 causing crash

### ISSUE THREAD

**Issue by xorinzor** [abpframework/abp#16478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Similar to https://support.abp.io/QA/Questions/4886/VoloAbpAbpInitializationException-720-rc1

After updating from 2.1.0 to 2.2.0 (via `abp update`) starting the webserver results in:

```
Volo.Abp.AbpInitializationException: An error occurred during PreConfigureServicesAsync phase of the module Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule, Volo.Abp.BackgroundJobs.Abstractions, Version=7.1.1.0, Culture=
neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'Void Microsoft.Extensions.DependencyInjection.ServiceCollectionRegistrationActionExtensions.OnRegistred(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Acti
on`1<Volo.Abp.DependencyInjection.IOnServiceRegistredContext>)'.
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule.RegisterJobs(IServiceCollection services)
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule.PreConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.PreConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
```

### Reproduction Steps

Update LeptonXLite from 2.1.0 to 2.2.0

### Expected behavior

Not crashing

### Actual behavior

Crashing

### Regression?

Reverting to previous version works.

### Known Workarounds

Reverting to 2.1.0

### Version

7.1.1

### User Interface

Not sure

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

The LeptonXLite is based on ABP7.2, you should upgrade your ABP version.

**Comment by xorinzor** [comment]
I used `abp update` from the root of my project, because I wanted to update to 7.2, but aside from updating the theme, it didn't really update any packages.

Output was all 7.1.1 packages were up to date.

Even after updating the cli to 7.2 I got this result.

Won't be able to re-check this until after 1,5 weeks unfortunately.

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem.

* `abp new TestApp -v 7.1.1`
* `abp update`

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/16813853/236184735-5348f12e-d8fa-4a6f-950c-d4f2c8ce36ef.png">
