### ISSUE TITLE
Using HTTP dynamic clients presents a dependency injection problem

### ISSUE THREAD

**Issue by iiiixxl** [abpframework/abp#16527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use http dynamic client to make a remote call, I get a dependency injection error, according to the error log to locate "AbpCamelCasePropertyNamesContractResolver", because it uses lazy loading to get "AbpDateTimeConverter", I don't understand why there is a problem at runtime, the specific error message I will fill in the issue

### Actual behavior

System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ThrowDisposedException()
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Volo.Abp.Json.Newtonsoft.AbpCamelCasePropertyNamesContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization)

### Known Workarounds

After I identified the problem, I tried to overwrite the definition of "CamelCasePropertyNamesContractResolver" and "AbpNewtonsoftJsonSerializer" in my project, and then re-observed for 2 days, and there were no more errors, which I think is not the best method. Whether lazy loading should not be used in "AbpCamelCasePropertyNamesContractResolver" to get "AbpDateTimeconverter"？

### Version

7.0.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by iiiixxl** [comment]
I look at the code on the latest dev branch and it seems that this bug has been fixed，Remove Lazy and he will work normally, but the reason is not very clear
