### ISSUE TITLE
Invalid value for key Integrated Security

### ISSUE THREAD

**Issue by ericardezp** [abpframework/abp#16522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,

I've created a new solution with ABP CLI version 7.2.1 with command: 
`abp new Template.Applicaiton -u angular --separate-identity-server --theme basic -csf`

I have established .DbMigrator as a startup project and changed the default connection string:
```
"ConnectionStrings": {
    "Default": "Server=localhost;Database=TemplateDB;User Id=user;password=password;Trusted_Connection=False;MultipleActiveResultSets=true;"
  }

```
Why, I've always got an error message **Invalid value for key Integrated Security**

Stack error:
  ```
 at Microsoft.Data.Common.DbConnectionOptions.ConvertValueToIntegratedSecurityInternal(String stringValue)
   at Microsoft.Data.Common.DbConnectionOptions.ConvertValueToIntegratedSecurity()
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__66.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.<ExistsAsync>d__24.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<MigrateAsync>d__15.MoveNext()
   at HEB.Template.EntityFrameworkCore.EntityFrameworkCoreTemplateDbSchemaMigrator.<MigrateAsync>d__2.MoveNext() in ...EntityFrameworkCore\EntityFrameworkCore\EntityFrameworkCoreTemplateDbSchemaMigrator.cs:line 29
   at HEB.Template.Data.TemplateDbMigrationService.<MigrateDatabaseSchemaAsync>d__10.MoveNext() in ...Domain\Data\TemplateDbMigrationService.cs:line 95
   at HEB.Template.Data.TemplateDbMigrationService.<MigrateAsync>d__9.MoveNext() in ...Domain\Data\TemplateDbMigrationService.cs:line 52
   at HEB.Template.DbMigrator.DbMigratorHostedService.<StartAsync>d__3.MoveNext() in ...DbMigrator\DbMigratorHostedService.cs:line 36
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at HEB.Template.DbMigrator.Program.<Main>d__0.MoveNext() in ...DbMigrator\Program.cs:line 30

```
How can I fix this error?
Thanks

### Reproduction Steps

Create new solution with ABP CLI command:
`abp new Template.Applicaiton -u angular --separate-identity-server --theme basic -csf`

I have established .DbMigrator as a startup project and changed the default connection string:
```
"ConnectionStrings": {
    "Default": "Server=localhost;Database=TemplateDB;User Id=user;password=password;Trusted_Connection=False;MultipleActiveResultSets=true;"
  }

```

### Expected behavior

Seed the database

### Actual behavior

Invalid value for key Integrated Security

### Version

ABP CLI 7.2.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

It must be use the wrong connection string. Please debug it to see the real connection string.
