### ISSUE TITLE
Project Creation using CLI Error

### ISSUE THREAD

**Issue by mh-mazen** [abpframework/abp#1654]
### Command:
`abp new Acme.BookStore -u angular `

### Error:
**[15:21:20 INF] ABP CLI (https://abp.io)
[15:21:21 INF] Version 0.19.0 (Stable channel)
[15:21:34 INF] Creating a new project...
[15:21:34 INF] Project name: Acme.BookStore                                                                                            [15:21:47 INF] Downloading template: app, version: 0.19.0
[15:22:00 ERR] Error while copying content to a stream.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abnormally'.
   --- End of inner exception stack trace ---                                                                                             at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)       at System.Net.Http.NoWriteNoSeekStreamContent.<>c.<SerializeToStreamAsync>b__4_0(Task t, Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---                                                              at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)                                                        --- End of stack trace from previous location where exception was thrown ---                                                              at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)                            --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.DownloadTemplateFileContentAsync(TemplateDownloadInputDto input) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 105
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetAsync(String name, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 61
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 45
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55**

**Comment by hikalkan** [comment]
Just tried and it is working. Can you try again?

````
PS C:\Temp\cli-tests-2> abp new Acme.BookStore -u angular
[17:32:28 INF] ABP CLI (https://abp.io)
[17:32:29 INF] Version 0.19.0 (Stable channel)
[17:32:30 WRN] Unable to retrieve the latest version
[17:32:30 WRN] Remote server returns error! HTTP status code: Forbidden
[17:32:30 INF] Creating a new project...
[17:32:30 INF] Project name: Acme.BookStore
[17:32:30 INF] Downloading template: app, version: 0.19.0
[17:32:46 INF] Check the documentation of this template: https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[17:32:47 INF] Successfully created the project 'Acme.BookStore'
[17:32:47 INF] The output folder is: 'C:\Temp\cli-tests-2'
PS C:\Temp\cli-tests-2>
````

**Comment by tburnettastute** [comment]
19-Aug @ 9:50 America/NewYork, I get the same exception when I run

`abp new Acme.BookStore -u angular`

**Comment by tburnettastute** [comment]
I deleted %HOMEPATH%\.abp this morning and tried again.  I got the same exception.  After ~5 min, I tried a couple more times, eventually it worked.

I wonder if your host/hosting provider has idle'd out your server process and I have to kick it a few times before it is ready to handle downloads?

I'll try again, early (TZ: America/New_York) tomorrow morning.

**Comment by hikalkan** [comment]
Thanks for the additional info. Web site is fairly active and it is hard to go to sleep, but we check & make the idle timeout longer.

**Comment by mh-mazen** [comment]
Thank you all for your replays , its working for me now , mostly as described by @hikalkan
