### ISSUE TITLE
Share table and colum with new organization entity got error

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#16836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i new an entity with follow
`public class ZionOrganizationUnit : FullAuditedAggregateRoot<Guid>, IMultiTenant, IHasEntityVersion`
and configured in entityframeworkcore project run got error:
`2023-06-14 15:43:17 [ERR] [Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] [82776] [25] - 'OrganizationUnit.DeletionTime' and 'ZionOrganizationUnit.DeletionTime' are both mapped to column 'DeletionTime' in 'AbpOrganizationUnits', but are configured to use differing provider types ('DateTime' and 'DateTime?').
System.InvalidOperationException: 'OrganizationUnit.DeletionTime' and 'ZionOrganizationUnit.DeletionTime' are both mapped to column 'DeletionTime' in 'AbpOrganizationUnits', but are configured to use differing provider types ('DateTime' and 'DateTime?').
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateCompatible(IProperty property, IProperty duplicateProperty, String columnName, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)`

      builder.Entity<ZionOrganizationUnit>(b =>
        {
            b.ToTable("AbpOrganizationUnits", BasicDbProperties.DbSchema);
            b.ConfigureByConvention();
            b.HasKey(t => t.Id);
            b.Property(t => t.DisplayName).HasColumnName(nameof(ZionOrganizationUnit.DisplayName));
            b.Property(t => t.Code).HasColumnName(nameof(ZionOrganizationUnit.Code));

            b.Property(t => t.TypeCode).HasMaxLength(32).HasColumnName(nameof(ZionOrganizationUnit.TypeCode));
            b.Property(t => t.EntityVersion).HasColumnName(nameof(ZionOrganizationUnit.EntityVersion));
            b.Property(t => t.ParentId).HasColumnName(nameof(ZionOrganizationUnit.ParentId));

            //b.Property(t => t.DeletionTime).HasColumnName(nameof(ZionOrganizationUnit.DeletionTime)).HasColumnType("datetime").IsRequired(false);

            //string s1 = b.Property(t => t.DeletionTime).Metadata.ClrType.ToString();
            //string s = b.Property(t => t.DeletionTime).Metadata.GetRelationalTypeMapping().StoreType; //.SetProviderClrType(typeof(Nullable<DateTime>));

            b.HasOne<OrganizationUnit>().WithOne().HasForeignKey<ZionOrganizationUnit>(t => t.Id);
           
        });

the ZionOrganizationUnit enttiy has the same properties  as OrganizationUnit with no changes
why the error shows one is nullable datetime and the other is not?

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

does it is a bug in efcore 7.x ? I'v shearched a lot. but got the similar errors。
may be related to this   https://github.com/dotnet/efcore/issues/29531

**Comment by CAH-FlyChen** [comment]
upgrade efcore to 7.07 error goes away.
