### ISSUE TITLE
Host terminated unexpectedly after upgrading from 7.2.3 to 7.3.0

### ISSUE THREAD

**Issue by nankingcigar** [abpframework/abp#17113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

2023-07-14 07:00:29.990 +08:00 [INF] Starting TuoFan.Base.HttpApi.Host.
2023-07-14 07:00:32.070 +08:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule, Volo.Abp.AspNetCore.Mvc, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
Exception Info:
Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
System.TypeLoadException: Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Volo.Abp.MultiTenancy.TenantConfiguration' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.0.0, Culture=neutral, PublicKeyToken=null'.
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
   at TuoFan.Base.HttpApi.Host.Program.Main(String[] args) in D:\p\tf\template\school\Template_School\src\api\host\TuoFan.Base.HttpApi.Host\Program.cs:line 54

### Version

7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information
7.2.3 startup log messages:

2023-07-14 06:59:58.521 +08:00 [INF] Starting TuoFan.Base.HttpApi.Host.
2023-07-14 07:00:00.465 +08:00 [INF] Loaded ABP modules:
2023-07-14 07:00:00.466 +08:00 [INF] - TuoFan.Base.HttpApi.Host.BaseHttpApiHostModule
2023-07-14 07:00:00.466 +08:00 [INF]   - TuoFan.Base.HttpApi.BaseHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]     - TuoFan.Base.Application.Contracts.BaseApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - TuoFan.Base.Domain.Shared.BaseDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Validation.AbpValidationModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Validation.AbpValidationAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Localization.AbpLocalizationModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Settings.AbpSettingsModule
2023-07-14 07:00:00.466 +08:00 [INF]                 - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]                 - Volo.Abp.Security.AbpSecurityModule
2023-07-14 07:00:00.466 +08:00 [INF]                 - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2023-07-14 07:00:00.466 +08:00 [INF]                   - Volo.Abp.Data.AbpDataModule
2023-07-14 07:00:00.466 +08:00 [INF]                     - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2023-07-14 07:00:00.466 +08:00 [INF]                     - Volo.Abp.Uow.AbpUnitOfWorkModule
2023-07-14 07:00:00.466 +08:00 [INF]                     - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Threading.AbpThreadingModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Json.SystemTextJson.AbpJsonSystemTextJsonModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Json.AbpJsonAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Timing.AbpTimingModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.Identity.AbpIdentityDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Users.AbpUsersDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Features.AbpFeaturesModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.OpenIddict.AbpOpenIddictDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]       - TuoFan.School.Authorization.SchoolAuthorizationModule
2023-07-14 07:00:00.466 +08:00 [INF]         - TuoFan.School.Security.SchoolSecurityModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Chao.Abp.Authorization.ChaoAbpAuthorizationModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Authorization.AbpAuthorizationModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Account.AbpAccountApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Users.AbpUsersAbstractionModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.EventBus.AbpEventBusModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Json.AbpJsonModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Guids.AbpGuidsModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Application.AbpDddApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Auditing.AbpAuditingContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.SettingManagement.AbpSettingManagementApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]     - TuoFan.School.AspNetCore.Mvc.SchoolAspNetCoreMvcModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Chao.Abp.AspNetCore.Mvc.ChaoAbpAspNetCoreMvcModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.AspNetCore.AbpAspNetCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Auditing.AbpAuditingModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Http.AbpHttpModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Http.AbpHttpAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Minify.AbpMinifyModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.UI.Navigation.AbpUiNavigationModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.UI.AbpUiModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.Application.AbpDddApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.Domain.AbpDddDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Specifications.AbpSpecificationsModule
2023-07-14 07:00:00.466 +08:00 [INF]               - Volo.Abp.Caching.AbpCachingModule
2023-07-14 07:00:00.466 +08:00 [INF]                 - Volo.Abp.Serialization.AbpSerializationModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Chao.Abp.Json.ChaoAbpJsonModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Chao.Abp.Timing.ChaoAbpTimingModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Chao.Abp.Ddd.Domain.ChaoAbpDddDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Chao.Abp.ResultHandling.ChaoAbpResultHandlingModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Chao.Abp.ExceptionHandling.ChaoAbpExceptionHandlingModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Chao.Abp.Data.ChaoAbpDataModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Chao.Abp.MultiTenancy.ChaoAbpMultiTenancyModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Account.AbpAccountHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Identity.AbpIdentityHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.PermissionManagement.HttpApi.AbpPermissionManagementHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.SettingManagement.AbpSettingManagementHttpApiModule
2023-07-14 07:00:00.466 +08:00 [INF]   - TuoFan.Base.Application.BaseApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]     - TuoFan.Base.Domain.BaseDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - TuoFan.School.Auditing.SchoolAuditingModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Chao.Abp.AuditLogging.Domain.ChaoAbpAuditLoggingDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Chao.Abp.TenantManagement.Domain.ChaoAbpTenantManagementDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.AutoMapper.AbpAutoMapperModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Identity.AbpIdentityDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.Users.AbpUsersDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.OpenIddict.AbpOpenIddictDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.PermissionManagement.OpenIddict.AbpPermissionManagementDomainOpenIddictModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Emailing.AbpEmailingModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.TextTemplating.AbpTextTemplatingModule
2023-07-14 07:00:00.466 +08:00 [INF]           - Volo.Abp.TextTemplating.Scriban.AbpTextTemplatingScribanModule
2023-07-14 07:00:00.466 +08:00 [INF]             - Volo.Abp.TextTemplating.AbpTextTemplatingCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Account.AbpAccountApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Identity.AbpIdentityApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.TenantManagement.AbpTenantManagementApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.SettingManagement.AbpSettingManagementApplicationModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.AspNetCore.SignalR.AbpAspNetCoreSignalRModule
2023-07-14 07:00:00.466 +08:00 [INF]   - TuoFan.Base.EntityFrameworkCore.BaseEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Chao.Abp.EntityFrameworkCore.ChaoAbpEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Users.EntityFrameworkCore.AbpUsersEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.OpenIddict.EntityFrameworkCore.AbpOpenIddictEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.EntityFrameworkCore.SqlServer.AbpEntityFrameworkCoreSqlServerModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.FeatureManagement.EntityFrameworkCore.AbpFeatureManagementEntityFrameworkCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Chao.Abp.AspNetCore.Mvc.UI.ChaoAbpAspNetCoreMvcUiModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.AspNetCore.Mvc.UI.AbpAspNetCoreMvcUiModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Chao.Abp.Swashbuckle.ChaoAbpSwashbuckleModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Swashbuckle.AbpSwashbuckleModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.Autofac.AbpAutofacModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Castle.AbpCastleCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.Caching.StackExchangeRedis.AbpCachingStackExchangeRedisModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite.AbpAspNetCoreMvcUiLeptonXLiteThemeModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.AbpAspNetCoreMvcUiThemeSharedModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.AbpAspNetCoreMvcUiBootstrapModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Packages.AbpAspNetCoreMvcUiPackagesModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingAbstractionsModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpAspNetCoreMvcUiWidgetsModule
2023-07-14 07:00:00.466 +08:00 [INF]         - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.Account.Web.AbpAccountWebOpenIddictModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.Account.Web.AbpAccountWebModule
2023-07-14 07:00:00.466 +08:00 [INF]       - Volo.Abp.Identity.AspNetCore.AbpIdentityAspNetCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.BackgroundJobs.RabbitMQ.AbpBackgroundJobsRabbitMqModule
2023-07-14 07:00:00.466 +08:00 [INF]     - Volo.Abp.RabbitMQ.AbpRabbitMqModule
2023-07-14 07:00:00.466 +08:00 [INF]   - Volo.Abp.EventBus.RabbitMq.AbpEventBusRabbitMqModule
2023-07-14 07:00:00.523 +08:00 [DBG] Started background worker: Volo.Abp.BackgroundJobs.BackgroundJobWorker
2023-07-14 07:00:00.530 +08:00 [DBG] Started background worker: Volo.Abp.OpenIddict.Tokens.TokenCleanupBackgroundWorker
2023-07-14 07:00:00.592 +08:00 [DBG] RabbitMQ Queue 'AbpBackgroundJobs.Volo.Abp.Emailing.BackgroundEmailSendingJobArgs' has 0 messages and 0 consumers.
2023-07-14 07:00:00.765 +08:00 [INF] User profile is available. Using 'C:\Users\chao.yang\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2023-07-14 07:00:00.874 +08:00 [INF] Initialized all ABP modules.
2023-07-14 07:00:00.945 +08:00 [INF] Now listening on: https://localhost:44362
2023-07-14 07:00:00.945 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2023-07-14 07:00:00.945 +08:00 [INF] Hosting environment: Development
2023-07-14 07:00:00.945 +08:00 [INF] Content root path: D:\p\tf\template\school\Template_School\src\api\host\TuoFan.Base.HttpApi.Host

**Comment by maliming** [comment]
Please create a new template and compare the code. especially the csproj files.

**Comment by nankingcigar** [comment]
@maliming any other alternative solution?

**Comment by maliming** [comment]
You can change your Lepton package version same as the new template project.

**Comment by nankingcigar** [comment]
Thanks, 
Update Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite from
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" Version="2.2.*-*" />
to 
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" Version="2.3.*-*" />.

**Comment by hieunvh** [comment]
I have same problem:
Host terminated unexpectedly!
System.TypeLoadException: Could not load type 'Volo.Abp.MultiTenancy.ITenantConfigurationProvider' from assembly 'Volo.Abp.MultiTenancy, Version=7.3.3.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
--------------

**Comment by ayannch** [comment]
> 谢谢， 将 Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite 从 更新 为 。
thank you

**Comment by ayannch** [comment]
> 谢谢， 将 Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite 从 更新 为 。

    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" Version="3.3.*-*" />
