### ISSUE TITLE
An exception occurs when using JSRuntime.InvokeAsync<byte[]>("readByteArray") in BlazorServer.

### ISSUE THREAD

**Issue by haoxj0823** [abpframework/abp#17160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using JSRuntime.InvokeAsync<byte[]>("readByteArray") in BlazorServer, the following exception occurs:

```
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: JSON serialization is attempting to deserialize an unexpected byte array.. See InnerException for more details.
---> System.Text.Json.JsonException: JSON serialization is attempting to deserialize an unexpected byte array.
at Microsoft.JSInterop.Infrastructure.ByteArrayJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
--- End of inner exception stack trace ---
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
```

In TargetFramework 7.0 and ABP 7.3.0, it is an exception, in TargetFramework 6.0 and ABP 6.0.3, it is normal, but in TargetFramework 7.0 and ABP 6.0.3, it is an exception.

The BlazorServer template provided by ABP also has the same problem. I used the BlazorServer template provided by dotnet and used ABP in the smallest way, only referencing the Volo.Abp.Autofac package, and the problem is the same.

TestProject URL https://github.com/haoxj0823/BlazorServerTestProject

### Version

7.3.0

### User Interface

Blazor Server

### Database Provider

None/Others

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

How about without abp?

**Comment by haoxj0823** [comment]
> hi
> 
> How about without abp?

When the code related to ABP is commented out, it can work correctly.

```
using BlazorServerTestProject;
using BlazorServerTestProject.Data;
using Volo.Abp;

var builder = WebApplication.CreateBuilder(args);

// Abp
// builder.Host.UseAutofac();
// builder.Services.AddApplication<BlazorServerModule>();

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
```

TestProject URL https://github.com/haoxj0823/BlazorServerTestProject

**Comment by maliming** [comment]
Your test code gets 404 error first.

`GET https://localhost:7258/pages/index.razor.js net::ERR_ABORTED 404 (Not Found)`
