### ISSUE TITLE
abp cli tool update error

### ISSUE THREAD

**Issue by v2codes** [abpframework/abp#17190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run command "abp update" to upgrade Abp modules from "v7.3.0-rc.1" to "v7.3.0", I get the error below.

`PS F:\SampleService> abp update
ABP CLI 7.3.0
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.GetLatestVersionFromMyGet(String packageId) 
in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 281
at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.UpdateSolutionAsync(String solutionPath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, Boolean checkAll, String version) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 42
at Volo.Abp.Cli.Commands.UpdateCommand.UpdateNugetPackages(CommandLineArgs commandLineArgs, String directory, String version) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 80
at Volo.Abp.Cli.Commands.UpdateCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 44
at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 169
at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 77`

How to fix this? 
Thanks for your help.

**Comment by maliming** [comment]
This is myget.org problem. You can upgrade the versions manually.

**Comment by LuisPignataro** [comment]
Same problem upgrading from 7.1 to 7.2 or 7.3

Error:
AppData\Local\Temp\4e16213c-af4a-4e65-881b-51fe0ad11704\restore.csproj : error NU1301: No se puede
 cargar el índice de servicio para el origen https://www.myget.org/F/blazorise/api/v3/index.json.

**Comment by maliming** [comment]
You can remove the myget from your nuget sources.

**Comment by v2codes** [comment]
> myget.org



> This is myget.org problem. You can upgrade the versions manually.

Yeah, I did it manually.
