### ISSUE TITLE
ABP CLI Error

### ISSUE THREAD

**Issue by ekangal** [abpframework/abp#1722]
Why is the reason for the following error?

`abp new Acme.IssueManagement -t mvc-module --no-ui

[14:47:25 INF] ABP CLI (https://abp.io)
[14:47:26 INF] Version 0.19.0 (Stable channel)
[14:47:26 INF] Creating a new project...
[14:47:26 INF] Project name: Acme.IssueManagement
[14:47:26 ERR] There is no template found with given name: mvc-module
System.Exception: There is no template found with given name: mvc-module
   at Volo.Abp.Cli.ProjectBuilding.TemplateInfoProvider.Get(String name) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateInfoProvider.cs:line 27
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args)
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 45
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55`

**Comment by maliming** [comment]
`mvc-module` has been renamed to `module`

Please check the latest CLI documentation.

https://docs.abp.io/en/abp/latest/CLI

**Comment by ekangal** [comment]
The document below is old.

https://docs.abp.io/en/abp/latest/Startup-Templates/Module

**Comment by maliming** [comment]
I updated the documentation.
https://github.com/abpframework/abp/commit/e6bb45aff3d28e91c77aa138f2111cc4184c3f45
