### ISSUE TITLE
CmsKit - BlogDto mapping error on MongoDB

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#17285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
[14:36:36 ERR] Error mapping types.

Mapping types:
List`1 -> List`1
System.Collections.Generic.List`1[[Volo.CmsKit.Blogs.Blog, Volo.CmsKit.Domain, Version=7.3.1.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Volo.CmsKit.Admin.Blogs.BlogDto, Volo.CmsKit.Admin.Application.Contracts, Version=7.3.1.0, Culture=neutral, PublicKeyToken=null]]
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
List`1 -> List`1
System.Collections.Generic.List`1[[Volo.CmsKit.Blogs.Blog, Volo.CmsKit.Domain, Version=7.3.1.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Volo.CmsKit.Admin.Blogs.BlogDto, Volo.CmsKit.Admin.Application.Contracts, Version=7.3.1.0, Culture=neutral, PublicKeyToken=null]]
 ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Blog -> BlogDto
Volo.CmsKit.Blogs.Blog -> Volo.CmsKit.Admin.Blogs.BlogDto

Type Map configuration:
Blog -> BlogDto
Volo.CmsKit.Blogs.Blog -> Volo.CmsKit.Admin.Blogs.BlogDto

Destination Member:
ExtraProperties
```

### Version

7.3.1

### User Interface

MVC

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by enisn** [comment]
`ExtraProperties` field does not exist in BsonDocument when it's empty. If I add at least 1 ExtraProperty, everything works as expected

**Comment by enisn** [comment]
It happens for all CmsKit entities on MongoDB
```
 Exceptions:
  - Error mapping types.

Mapping types:
BlogFeature -> BlogFeatureCacheItem
Volo.CmsKit.Blogs.BlogFeature -> Volo.CmsKit.Blogs.BlogFeatureCacheItem

Type Map configuration:
BlogFeature -> BlogFeatureCacheItem
Volo.CmsKit.Blogs.BlogFeature -> Volo.CmsKit.Blogs.BlogFeatureCacheItem

Destination Member:
ExtraProperties

    AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
BlogFeature -> BlogFeatureCacheItem
Volo.CmsKit.Blogs.BlogFeature -> Volo.CmsKit.Blogs.BlogFeatureCacheItem

Type Map configuration:
BlogFeature -> BlogFeatureCacheItem
Volo.CmsKit.Blogs.BlogFeature -> Volo.CmsKit.Blogs.BlogFeatureCacheItem

Destination Member:
ExtraProperties

 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'sourceDictionary')
   at Volo.Abp.Check.NotNull[T](T value, String parameterName)
   at Volo.Abp.ObjectExtending.ExtensibleObjectMapper.MapExtraPropertiesTo(Type sourceType, Type destinationType, Dictionary`2 sourceDictionary, Dictionary`2 destinationDictionary, Nullable`1 definitionChecks, String[] ignoredProperties)     
   at Volo.Abp.ObjectExtending.ExtensibleObjectMapper.MapExtraPropertiesTo[TSource,TDestination](Dictionary`2 sourceDictionary, Dictionary`2 destinationDictionary, Nullable`1 definitionChecks, String[] ignoredProperties)
   at AutoMapper.AbpAutoMapperExtensibleDtoExtensions.<>c__DisplayClass0_0`2.<MapExtraProperties>b__5(TSource source, TDestination destination, ExtraPropertyDictionary extraProps)
   at lambda_method2900(Closure, Object, BlogFeatureCacheItem, ResolutionContext)
   --- End of inner exception stack trace ---
   at lambda_method2900(Closure, Object, BlogFeatureCacheItem, ResolutionContext)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.Map[TSource,TDestination](TSource source)
   at Volo.CmsKit.Blogs.BlogFeatureAppService.GetOrDefaultFromRepositoryAsync(Guid blogId, String featureName)
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)
   at Volo.CmsKit.Blogs.BlogFeatureAppService.GetOrDefaultAsync(Guid blogId, String featureName)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper, IUnitOfWorkManager unitOfWorkManager)

**Comment by enisn** [comment]
In the database, ExtraProperties field is `null` and it is restored as `null` into entity by **Mongo.Driver**
