### ISSUE TITLE
NetTopologySuite spatial service is not registered.

### ISSUE THREAD

**Issue by zizoumurat** [abpframework/abp#17353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,

I have use Devart.Data.Oracle.EFCore 10.1.151.7. 

I get "NetTopologySuite spatial service is not registered." error on insert/update

### Version

7.3 (latest)

### User Interface

MVC

### Database Provider

EF Core (Default)

**Comment by maliming** [comment]
* Exception message and stack trace if available (check the logs).
* Steps needed to reproduce the problem.

**Comment by visualsoft-consulting** [comment]
Hi,

I get the exception too. My StackTrace:

```
at Devart.Common.Entity.EntitySpatialServices.b()
   at Devart.Common.Entity.cr.d(IColumnModification A_0)
   at Devart.Data.Oracle.Entity.an.b0(IColumnModification A_0)
   at Devart.Common.Entity.cq.e()
   at Devart.Common.Entity.cq.Complete(Boolean moreBatchesExpected)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateCommandBatches(IEnumerable`1 commandSet, Boolean moreCommandSets, Boolean assertColumnModification, ParameterNameGenerator parameterNameGenerator)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IList`1 entries, IUpdateAdapter updateAdapter)+MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

Exception Message: NetTopologySuite spatial service is not registered.
Exception Source: Devart.Data.Oracle.Entity.EFCore

In my C# class:
```
            Context.Update(entity);
            int result = await Context.SaveChangesAsync(cancellationToken);
```

I am using:
Microsoft.EntityFrameworkCore 7.0.10
Devart.Data.Oracle.EFCore 10.1.151.7

Thank you!

**Comment by zizoumurat** [comment]
hi @visualsoft-consulting 

add "Devart.Data.Oracle.EFCore.NetTopologySuite" package and add UseNetTopologySuite() method in this line : 

c.UseOracle(b =>
                        {
                            b.UseNetTopologySuite();
                        });

**Comment by visualsoft-consulting** [comment]
Hi @zizoumurat,

thank you! But I do not understand, why I have to add an unnecessary dependency/package. It should work without the Topology Package.
