### ISSUE TITLE
UI Login redirect not working

### ISSUE THREAD

**Issue by cgdif** [abpframework/abp#17550]
*  **CLI 7.3.1**.
* **Angular** 
* EF Core

logs.txt
`
**Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2023-09-04 08:56:38.090 +00:00 [INF] Executing handler method Volo.Abp.Account.Web.Pages.Account.LoginModel.OnPostAsync - ModelState is "Valid"
2023-09-04 08:56:38.889 +00:00 [INF] Application is shutting down...
2023-09-04 08:56:40.744 +00:00 [INF] AuthenticationScheme: Identity.Application signed in.
2023-09-04 08:56:43.561 +00:00 [INF] Executed handler method OnPostAsync, returned result Microsoft.AspNetCore.Mvc.RedirectResult.
2023-09-04 08:56:43.562 +00:00 [INF] Executing RedirectResult, redirecting to /connect/authorize?response_type=code&client_id=dbt_App&state=bVZXQVc2cjIzNVNmZUR3NXpMeTREaTNFRXl4NG1pZWRkRjY2Zk9rZjRlVE5x&redirect_uri=http%3A%2F%2Fcgdbtapp.azurewebsites.net&scope=openid%20offline_access%20dbt&code_challenge=BgescYxRJejLvs0I5W0SPqvXpJprxUeEzipRwgBSLIM&code_challenge_method=S256&nonce=bVZXQVc2cjIzNVNmZUR3NXpMeTREaTNFRXl4NG1pZWRkRjY2Zk9rZjRlVE5x&culture=en&ui-culture=en.
2023-09-04 08:56:43.562 +00:00 [INF] Executed page /Account/Login in 5489.4786ms
2023-09-04 08:56:43.562 +00:00 [INF] Executed endpoint '/Account/Login'
2023-09-04 08:56:44.320 +00:00 [FTL] Host terminated unexpectedly!
System.AggregateException: One or more hosted services failed to stop. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 38**`

**Comment by cgdif** [comment]
![image](https://github.com/abpframework/abp/assets/117594282/ae9c5af4-30ee-4a82-8949-e65a46227b69)

**Comment by cgdif** [comment]
`2023-09-04 10:08:09.336 +00:00 [INF] Executed endpoint '/Account/Login'
2023-09-04 10:08:25.702 +00:00 [ERR] An error occurred using the connection to database 'cgdbt' on server 'tcp:xxxx'.
2023-09-04 10:08:25.813 +00:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.BackgroundJobs.EntityFrameworkCore.BackgroundJobsDbContext'.
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.)`

**Comment by mahmut-gundogdu** [comment]
error  message describe "An error occurred using the connection to database 'cgdbt' on server 'tcp:xxxx'" You have connection issue. it is not realted UI
