### ISSUE TITLE
After restarting Auth Server , IDX10501: Signature validation failed. Unable to match key

### ISSUE THREAD

**Issue by ertugrulbakidal** [abpframework/abp#17661]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Hi,
I have Auth app, API and Angular for back office. I have client apps (asp.net core razor). Moreover all apps are containerized by Docker. I dont have any issues for login from client apps. The user is redirected to Auth app, after successful login, it's redirected to client app. Everything works but when i do a new deployment, accordingly new docker container is created for Auth server. When "docker compose -f docker-compose.yml -f docker-compose.staging.yml pull  && docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d" is run in github actions, the auth app docker container is restarted. Then when i try to login from client app I get the error below and the user is not logged in. but after this error if i try to login again from client app, it works fine. So this occurs only first time when i try to login from client app.

Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: '77D9E3F9CBA02E26AC96E6277FB1DCE43D16FAA2'.
Number of keys in TokenValidationParameters: '0'.
Number of keys in Configuration: '2'.
Exceptions caught:
'[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
at Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, Nullable1 notBefore, Nullable1 expires, String kid, TokenValidationParameters validationParameters, BaseConfiguration configuration, StringBuilder exceptionStrings, Int32 numKeysInConfiguration, Int32 numKeysInTokenValidationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
2023-09-18 10:12:05.938 +01:00 [INF] Error from RemoteAuthentication: IDX10501: Signature validation failed. Unable to match key:
kid: '77D9E3F9CBA02E26AC96E6277FB1DCE43D16FAA2'.
Number of keys in TokenValidationParameters: '0'.
Number of keys in Configuration: '2'.
Exceptions caught:
'[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'..
2023-09-18 10:12:05.939 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: '77D9E3F9CBA02E26AC96E6277FB1DCE43D16FAA2'.
Number of keys in TokenValidationParameters: '0'.
Number of keys in Configuration: '2'.
Exceptions caught:
'[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
at Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, Nullable1 notBefore, Nullable1 expires, String kid, TokenValidationParameters validationParameters, BaseConfiguration configuration, StringBuilder exceptionStrings, Int32 numKeysInConfiguration, Int32 numKeysInTokenValidationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
--- End of inner exception stack trace ---
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at ERestaurant.Web.Middlewares.RobotsMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Restaurant1/Restaurant1/src/ERestaurant.Web/Middlewares/RobotsMiddleware.cs:line 59
at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<b__1>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

### Version

7.3.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by maliming** [comment]
> For more details, see https://aka.ms/IdentityModel/PII

**Comment by ertugrulbakidal** [comment]
After IdentityModelEventSource.ShowPII = true;

2023-09-19 14:52:40.355 +01:00 [ERR] Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'A960B7BF5306A564BDE96D645781C1C279C60C1B'. 
Number of keys in TokenValidationParameters: '0'. 
Number of keys in Configuration: '2'. 
Exceptions caught:
 ''. 
token: '{"alg":"RS256","kid":"A960B7BF5306A564BDE96D645781C1C279C60C1B","x5t":"qWC3v1MGpWS96W1kV4HBwnnGDBs","typ":"JWT"}.{"sub":"3a0db76d-3cd1-03ce-c4a5-05c528fed065","preferred_username":"restaurant1_user5","email":"restaurant1_user5@gmail.com","tenantid":"3a0db688-1635-60a0-1ab5-8865e6f8c386","unique_name":"restaurant1_user5","oi_au_id":"3a0db76d-3df7-1593-70bb-b6530645ca59","azp":"ERestaurant_Web_Client1","nonce":"638307283375506116.MTk2MzQyYTEtNTM1ZC00MTg5LTgxNTItNDM4M2NkYWM0MGQxMjdlYzc2ZjktMjk3YS00NjJjLTlhM2ItMDlmMzdjMTY4NWJh","c_hash":"csbgE0MsxnTNYq6VsvHs5A","oi_tkn_id":"3a0dbfe3-c123-a4bd-9297-0fffee869678","aud":"ERestaurant_Web_Client1","exp":1695132759,"iss":"https://staging-auth.dalepos.com/","iat":1695131559}'.
   at Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, Nullable`1 notBefore, Nullable`1 expires, String kid, TokenValidationParameters validationParameters, BaseConfiguration configuration, StringBuilder exceptionStrings, Int32 numKeysInConfiguration, Int32 numKeysInTokenValidationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
2023-09-19 14:52:40.359 +01:00 [INF] Error from RemoteAuthentication: IDX10501: Signature validation failed. Unable to match key: 
kid: 'A960B7BF5306A564BDE96D645781C1C279C60C1B'. 
Number of keys in TokenValidationParameters: '0'. 
Number of keys in Configuration: '2'. 
Exceptions caught:
 ''. 
token: '{"alg":"RS256","kid":"A960B7BF5306A564BDE96D645781C1C279C60C1B","x5t":"qWC3v1MGpWS96W1kV4HBwnnGDBs","typ":"JWT"}.{"sub":"3a0db76d-3cd1-03ce-c4a5-05c528fed065","preferred_username":"restaurant1_user5","email":"restaurant1_user5@gmail.com","tenantid":"3a0db688-1635-60a0-1ab5-8865e6f8c386","unique_name":"restaurant1_user5","oi_au_id":"3a0db76d-3df7-1593-70bb-b6530645ca59","azp":"ERestaurant_Web_Client1","nonce":"638307283375506116.MTk2MzQyYTEtNTM1ZC00MTg5LTgxNTItNDM4M2NkYWM0MGQxMjdlYzc2ZjktMjk3YS00NjJjLTlhM2ItMDlmMzdjMTY4NWJh","c_hash":"csbgE0MsxnTNYq6VsvHs5A","oi_tkn_id":"3a0dbfe3-c123-a4bd-9297-0fffee869678","aud":"ERestaurant_Web_Client1","exp":1695132759,"iss":"https://staging-auth.dalepos.com/","iat":1695131559}'..
2023-09-19 14:52:40.363 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'A960B7BF5306A564BDE96D645781C1C279C60C1B'. 
Number of keys in TokenValidationParameters: '0'. 
Number of keys in Configuration: '2'. 
Exceptions caught:
 ''. 
token: '{"alg":"RS256","kid":"A960B7BF5306A564BDE96D645781C1C279C60C1B","x5t":"qWC3v1MGpWS96W1kV4HBwnnGDBs","typ":"JWT"}.{"sub":"3a0db76d-3cd1-03ce-c4a5-05c528fed065","preferred_username":"restaurant1_user5","email":"restaurant1_user5@gmail.com","tenantid":"3a0db688-1635-60a0-1ab5-8865e6f8c386","unique_name":"restaurant1_user5","oi_au_id":"3a0db76d-3df7-1593-70bb-b6530645ca59","azp":"ERestaurant_Web_Client1","nonce":"638307283375506116.MTk2MzQyYTEtNTM1ZC00MTg5LTgxNTItNDM4M2NkYWM0MGQxMjdlYzc2ZjktMjk3YS00NjJjLTlhM2ItMDlmMzdjMTY4NWJh","c_hash":"csbgE0MsxnTNYq6VsvHs5A","oi_tkn_id":"3a0dbfe3-c123-a4bd-9297-0fffee869678","aud":"ERestaurant_Web_Client1","exp":1695132759,"iss":"https://staging-auth.dalepos.com/","iat":1695131559}'.
   at Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, Nullable`1 notBefore, Nullable`1 expires, String kid, TokenValidationParameters validationParameters, BaseConfiguration configuration, StringBuilder exceptionStrings, Int32 numKeysInConfiguration, Int32 numKeysInTokenValidationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at ERestaurant.Web.Middlewares.RobotsMiddleware.InvokeAsync(HttpContext context) in F:\GithubWorkspace\DalOnlineOrder\clients\client1\src\ERestaurant.Web\Middlewares\RobotsMiddleware.cs:line 59
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

![auth_issue](https://github.com/abpframework/abp/assets/40223108/189a91c6-91d9-46f5-9510-b69e2e1d368c)
