### ISSUE TITLE
Error when generating code in ABP Suite

### ISSUE THREAD

**Issue by vinhlam1412** [abpframework/abp#17955]
* ABP Framework version: 7.4.0.
* ABP Suite version: 7.4.0.
* User Interface: Blazor
* Database provider: EF Core
* Exception message:
2023-10-23 14:33:02.094 +07:00 [INF] 1/9 - EntityGenerateCommand started...
2023-10-23 14:33:04.117 +07:00 [INF] 1/9 - EntityGenerateCommand completed.                    | Duration: 2019 ms.
2023-10-23 14:33:04.117 +07:00 [INF] 2/9 - RepositoryCommand started...
2023-10-23 14:33:04.246 +07:00 [INF] 2/9 - RepositoryCommand completed.                        | Duration: 128 ms.
2023-10-23 14:33:04.246 +07:00 [INF] 3/9 - ManagerCommand started...
2023-10-23 14:33:04.290 +07:00 [INF] 3/9 - ManagerCommand completed.                           | Duration: 43 ms.
2023-10-23 14:33:04.291 +07:00 [INF] 4/9 - AppServiceCommand started...
2023-10-23 14:33:06.958 +07:00 [INF] 4/9 - AppServiceCommand completed.                        | Duration: 2666 ms.
2023-10-23 14:33:06.958 +07:00 [INF] 5/9 - ProxyControllerCommand started...
2023-10-23 14:33:06.996 +07:00 [INF] 5/9 - ProxyControllerCommand completed.                   | Duration: 37 ms.
2023-10-23 14:33:06.996 +07:00 [INF] 6/9 - PermissionCommand started...
2023-10-23 14:33:07.043 +07:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

2023-10-23 14:33:07.050 +07:00 [ERR] After parsing a value an unexpected character was encountered: ". Path 'Texts', line 1480, position 2.
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'Texts', line 1480, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Services.LocalizationService.AddLocalizationsAsync(Dictionary`2 localizations, CrudPageCommandOptions options)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Commands.PermissionCommand.TUGkEeQld4()
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Commands.PermissionCommand.ExecuteAsync(CrudPageCommandOptions options)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.CommandManager.ExecuteAllAsync(CrudPageCommandOptions options)
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Commands.CrudPageGenerator.GenerateAsync(EntityModel entity, Solution solution)
   at Volo.Abp.Suite.Controllers.CrudPageGeneratorController.SaveAndGenerateEntityAsync(Guid solutionId, EntityModel entity)
   at lambda_method1987(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

When I generate code in ABP Suite, It's have error:
![bug](https://github.com/abpframework/abp/assets/91020638/8c14a0c8-1684-4508-894d-60b1cb1bb0dd)

Above is the log file of ABP Suite. Please help me.

**Comment by EngincanV** [comment]
Hi, we are not giving commercial support on GitHub. Please create a question at https://support.abp.io/QA/Questions, and then we can assist you with your problem and provide you a proper solution.
