### ISSUE TITLE
ViewComponent could not be found in Welcome_Page template test

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#1811]
Reproduction steps:
```
PS> dotnet tool install -g --version 0.21.0 Volo.Abp.Cli
PS> abp new Acme.BookStore
PS> dotnet test
```

> [xUnit.net 00:00:10.01]     Acme.BookStore.Pages.Index_Tests.Welcome_Page [FAIL]
  X Acme.BookStore.Pages.Index_Tests.Welcome_Page [8s 859ms]
  Error Message:
   System.InvalidOperationException : A view component named 'Volo.Abp.AspNetCore.Mvc.UI.Components.LayoutHook.LayoutHookViewComponent' could not be found. A view component must be a public non-abstract class, not contain any generic parameters, and either be decorated with 'ViewComponentAttribute' or have a class name ending with the 'ViewComponent' suffix. A view component must not be decorated with 'NonViewComponentAttribute'.
  Stack Trace:
     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.SelectComponent(Type componentType)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(Type componentType, Object arguments)
   at Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, Object arguments)
   at AspNetCore._Themes_Basic_Layouts_Application.<>c__DisplayClass14_0.<<ExecuteAsync>b__0>d.MoveNext() in /Themes/Basic/Layouts/Application.cshtml:line 36

**Comment by maliming** [comment]
Thanks for the feedback, I will test and fix it.
