### ISSUE TITLE
CLI -t app-nolayers option results in an file not found exception

### ISSUE THREAD

**Issue by espijk2** [abpframework/abp#18256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following the tutorial at https://docs.abp.io/en/abp/latest/Tutorials/Todo/Single-Layer/Index?UI=Blazor&DB=EF and executing the 

> abp new TodoApp -t app-nolayers -u blazor

 it results in a file not found exception.

### Reproduction Steps

Command line and execute

> abp new TodoApp -t app-nolayers -u blazor

### Expected behavior

Succesfull generated project

### Actual behavior

Using cached template: app-nolayers, version: 7.4.2
Theme: LeptonXLite
Could not find file: /aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json
System.ApplicationException: Could not find file: /aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildContextExtensions.GetFile(ProjectBuildContext context, String filePath) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildContextExtensions.cs:line 14
   at Volo.Abp.Cli.ProjectBuilding.Templates.App.AppTemplateChangeConsoleTestClientPortSettingsStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Templates\App\AppTemplateChangeConsoleTestClientPortSettingsStep.cs:line 23
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 135
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 97
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 169
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 77

### Version

version: 7.4.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

This issue also occurs with the latest RC 8

**Comment by maliming** [comment]
hi

This will be fixed in 7.4.3 and 8.0-rc2.

https://github.com/abpframework/abp/pull/18230
