### ISSUE TITLE
MicroserviceDemo: Exception on microservicedemo_auth-server_1 startup.

### ISSUE THREAD

**Issue by bdongus** [abpframework/abp#1831]
Hi.

I wanted to try the docker version on my macbook pro. At first glance everything seems to work. But there was an infinite loop trying to log in.

The auth server throws exception on startup:

> docker logs microservicedemo_auth-server_1
Application startup exception: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: One or more errors occurred. (Connection failed) ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 172.18.0.4:5672
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__272_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at RabbitMQ.Client.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, Int32 millisecondsTimeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at Volo.Abp.RabbitMQ.ConnectionPool.<>c__DisplayClass8_0.<Get>b__0() in /src/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/ConnectionPool.cs:line 30
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory) in /src/framework/src/Volo.Abp.Core/System/Collections/Generic/AbpDictionaryExtensions.cs:line 101
   at Volo.Abp.EventBus.RabbitMq.RabbitMqDistributedEventBus.PublishAsync(Type eventType, Object eventData) in /src/framework/src/Volo.Abp.EventBus.RabbitMQ/Volo/Abp/EventBus/RabbitMq/RabbitMqDistributedEventBus.cs:line 167
   at Volo.Abp.Uow.UnitOfWork.OnCompletedAsync() in /src/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWork.cs:line 242
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken) in /src/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWork.cs:line 135
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in /src/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo) in /src/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAbpInterceptorAdapter.cs:line 73
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context) in /src/framework/src/Volo.Abp.Data/Volo/Abp/Data/DataSeeder.cs:line 26
   at AuthServer.Host.AuthServerHostModule.<>c__DisplayClass1_0.<<OnApplicationInitialization>b__0>d.MoveNext() in /src/samples/MicroserviceDemo/applications/AuthServer.Host/AuthServerHostModule.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in /src/framework/src/Volo.Abp.Core/Volo/Abp/Modularity/ModuleManager.cs:line 39
   at Volo.Abp.AbpApplicationBase.InitializeModules() in /src/framework/src/Volo.Abp.Core/Volo/Abp/AbpApplicationBase.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Application is shutting down...
Hosting environment: Development
Content root path: /app
Now listening on: http://0.0.0.0:51511
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: /app
Now listening on: http://0.0.0.0:51511
Application started. Press Ctrl+C to shut down.
Application is shutting down...

Got no idea where to look or how to fix this. Sorry newbie with docker and ABP.

**Comment by acid12** [comment]
It seems like your host tries to conenct to RabbitMQ and fails
`Application startup exception: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: One or more errors occurred. (Connection failed) ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 172.18.0.4:5672`

check if RabbitMQ listens on provided ip:port, or if you're using docker, make sure RabbitMQ is started beforehand as it takes time to initialize

**Comment by bdongus** [comment]
I am using the docker version, following your instructions. I used the docker-compose up -d command to start the containers.

How would I have to start the containers, to make it work?

Sorry for asking this. I am a docker newbie who tries to get your demo up and running.

**Comment by acid12** [comment]
Just to verify, after you run the docker compose up command, kill all your containers, leaving the Rabbitmq running. Then execute the command once again after 30s.
Your container should be recreated and connect to the rabbit.

You may also inspect rabbitmq container logs to check that it is running correctly
