### ISSUE TITLE
Certificate Related issue "Access Denied"

### ISSUE THREAD

**Issue by Keertesh** [abpframework/abp#18370]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

Your CLI 7.3.1.
Angular
EF Core
Want to access application without the certificate on Azure using HTTP.
Azure logs:
2023-12-05 11:34:47.898 +00:00 [INF] Starting chhattisgarh.dbt.HttpApi.Host.
2023-12-05 11:34:49.771 +00:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictDomainModule, Volo.Abp.OpenIddict.Domain, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate(X500DistinguishedName subject)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate()
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.<PreConfigureServices>b__0_4(OpenIddictServerBuilder options) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 91
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action`1 configuration)
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.<PreConfigureServices>b__0_3(OpenIddictBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 89
   at Volo.Abp.Options.PreConfigureActionList`1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.AddOpenIddictCore(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35

**Comment by Keertesh** [comment]
@maliming

**Comment by kevinchalet** [comment]
Development certificates are not supported on Azure, as mentioned here: https://docs.abp.io/en/abp/latest/Deployment/Configuring-OpenIddict#development-environment.

To fix that, you can create your own certificates locally and attach them to your web app. See https://stackoverflow.com/questions/46114264/x509certificate2-on-azure-app-services-azure-websites-since-mid-2017 for more information.

**Comment by cgdif** [comment]
I'm using http and does not require any certificate, how to resolve the above error when deploying on azure @maliming.

**Comment by maliming** [comment]
@cgdif 

> AddDevelopmentEncryptionAndSigningCertificate cannot be used in applications deployed on IIS or Azure App Service: trying to use them on IIS or Azure App Service will result in an exception being thrown at runtime (unless the application pool is configured to load a user profile). To avoid that, consider creating self-signed certificates and storing them in the X.509 certificates store of the host machine(s). Please refer to: https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-development-certificate

https://docs.abp.io/en/abp/latest/Deployment/Configuring-OpenIddict#configuring-openiddict
