### ISSUE TITLE
Access Denied when not using the certificate.

### ISSUE THREAD

**Issue by cgdif** [abpframework/abp#18416]
I'm using http.

how to resolve below errors please check both the logs.

Your CLI 7.3.1.
Angular
EF Core
Want to access application without the certificate on Azure using HTTP.

when using 
 options.AddDevelopmentEncryptionCertificate()
               .AddDevelopmentSigningCertificate();

Azure logs 1:
2023-12-05 11:34:47.898 +00:00 [INF] Starting chhattisgarh.dbt.HttpApi.Host.
2023-12-05 11:34:49.771 +00:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictDomainModule, Volo.Abp.OpenIddict.Domain, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.
at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate(X500DistinguishedName subject)
at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate()
at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.b__0_4(OpenIddictServerBuilder options) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 91
at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action1 configuration) at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.<PreConfigureServices>b__0_3(OpenIddictBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 89 at Volo.Abp.Options.PreConfigureActionList1.Configure(TOptions options)
at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.AddOpenIddictCore(IServiceCollection services)
at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.ConfigureServices(ServiceConfigurationContext context)
at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
--- End of inner exception stack trace ---
at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action1 optionsAction) at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action1 optionsAction)
at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35

when using 
 PreConfigure<OpenIddictServerBuilder>(builder =>
 {
     builder.UseAspNetCore()
     .DisableTransportSecurityRequirement();
     builder.AddSigningCertificate(GetSigningCertificate(hostingEnvironment));
     builder.AddEncryptionCertificate(GetSigningCertificate(hostingEnvironment));

 });

log 2:
2023-12-08 09:09:28.536 +00:00 [INF] Starting chhattisgarh.dbt.HttpApi.Host.
2023-12-08 09:09:30.485 +00:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule, Volo.Abp.OpenIddict.AspNetCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at chhattisgarh.dbt.dbtHttpApiHostModule.GetSigningCertificate(IWebHostEnvironment hostingEnv) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 115
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c__DisplayClass0_0.<PreConfigureServices>b__2(OpenIddictServerBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 77
   at Volo.Abp.Options.PreConfigureActionList`1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.<>c__DisplayClass1_0.<AddOpenIddictServer>b__0(OpenIddictServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action`1 configuration)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.AddOpenIddictServer(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35

**Comment by cgdif** [comment]
I don't need https I want to test it using http only do I still need the certificate. @maliming

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/18370#issuecomment-1846828736

**Comment by cgdif** [comment]
@maliming 

logs.txt
<details><summary>Azure Logs</summary>
<p>
2023-12-08 09:27:55.451 +00:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule, Volo.Abp.OpenIddict.AspNetCore, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at chhattisgarh.dbt.dbtHttpApiHostModule.GetSigningCertificate(IWebHostEnvironment hostingEnv) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 84
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c__DisplayClass0_0.<PreConfigureServices>b__2(OpenIddictServerBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 74
   at Volo.Abp.Options.PreConfigureActionList`1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.<>c__DisplayClass1_0.<AddOpenIddictServer>b__0(OpenIddictServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action`1 configuration)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.AddOpenIddictServer(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictAspNetCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action`1 optionsAction)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35`



</p>
</details> 


used code 
```c#

``` public override void PreConfigureServices(ServiceConfigurationContext context)
{
    var hostingEnvironment = context.Services.GetHostingEnvironment();

    // Development environment
    if (hostingEnvironment.IsDevelopment())
    {
        PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
        {
            // This is default value, you can remove this line.
            options.AddDevelopmentEncryptionAndSigningCertificate = true;
        });
    }

    // Production or Staging environment
    if (!hostingEnvironment.IsDevelopment())
    {
        PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
        {
            options.AddDevelopmentEncryptionAndSigningCertificate = false;
        });

        PreConfigure<OpenIddictServerBuilder>(builder =>
        {
            builder.AddSigningCertificate(GetSigningCertificate(hostingEnvironment));
            builder.AddEncryptionCertificate(GetSigningCertificate(hostingEnvironment));

            //...
        });
    }
}

private X509Certificate2 GetSigningCertificate(IWebHostEnvironment hostingEnv)
{
    return new X509Certificate2(Path.Combine(hostingEnv.ContentRootPath, "authserver.pfx"), "password");
}
`

**Comment by cgdif** [comment]
---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.

**Comment by cgdif** [comment]
@jrocha

**Comment by cgdif** [comment]
logs for below code `Volo.Abp.AbpInitializationException: An error occurred during ConfigureServicesAsync phase of the module Volo.Abp.OpenIddict.AbpOpenIddictDomainModule, Volo.Abp.OpenIddict.Domain, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unspecified error
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan 1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c__DisplayClass0_0.<PreConfigureServices>b__4(OpenIddictServerBuilder options) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 84
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action 1 configuration)
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c__DisplayClass0_0.<PreConfigureServices>b__3(OpenIddictBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 82
   at Volo.Abp.Options.PreConfigureActionList 1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.AddOpenIddictCore(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action 1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action 1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action 1 optionsAction)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35`


code 
`public override void PreConfigureServices(ServiceConfigurationContext context)
{
    var hostingEnvironment = context.Services.GetHostingEnvironment();

    // Development environment
    if (hostingEnvironment.IsDevelopment())
    {
        PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
        {
            // This is default value, you can remove this line.
            options.AddDevelopmentEncryptionAndSigningCertificate = true;
        });
    }

    // Production or Staging environment
    if (!hostingEnvironment.IsDevelopment())
    {
        PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
        {
            options.AddDevelopmentEncryptionAndSigningCertificate = false;
        });

        PreConfigure<OpenIddictServerBuilder>(builder =>
        {
            builder.UseAspNetCore()
            .DisableTransportSecurityRequirement();
            // builder.AddSigningCertificate(GetSigningCertificate(hostingEnvironment));
            // builder.AddEncryptionCertificate(GetSigningCertificate(hostingEnvironment));
            //...
        });
        PreConfigure<OpenIddictBuilder>(builder =>
        {
            builder.AddServer(options =>
            {
                options.AddEncryptionCertificate(new X509Certificate2(hostingEnvironment.ContentRootPath, "password"))
            .AddSigningCertificate(new X509Certificate2(hostingEnvironment.ContentRootPath, "password"));
            });
            builder.AddValidation(options =>
            {
                options.AddAudiences("dbt");
                options.UseLocalServer();
                options.UseAspNetCore();
            });
        });
    }
}`

**Comment by cgdif** [comment]
@maliming please suggest.

**Comment by cgdif** [comment]
Log:

` ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate(X500DistinguishedName subject)
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddDevelopmentEncryptionCertificate()
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.<PreConfigureServices>b__0_4(OpenIddictServerBuilder options) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 84
   at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action 1 configuration)
   at chhattisgarh.dbt.dbtHttpApiHostModule.<>c.<PreConfigureServices>b__0_3(OpenIddictBuilder builder) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\dbtHttpApiHostModule.cs:line 82
   at Volo.Abp.Options.PreConfigureActionList 1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.AddOpenIddictCore(IServiceCollection services)
   at Volo.Abp.OpenIddict.AbpOpenIddictDomainModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.AbpModule.ConfigureServicesAsync(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServicesAsync()
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](IServiceCollection services, Action 1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplicationAsync[TStartupModule](IServiceCollection services, Action 1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.WebApplicationBuilderExtensions.AddApplicationAsync[TStartupModule](WebApplicationBuilder builder, Action 1 optionsAction)
   at chhattisgarh.dbt.Program.Main(String[] args) in K:\dbt\aspnet-core\src\chhattisgarh.dbt.HttpApi.Host\Program.cs:line 35`

Code:
` public override void PreConfigureServices(ServiceConfigurationContext context)
 {
     var hostingEnvironment = context.Services.GetHostingEnvironment();

     // Development environment
     if (hostingEnvironment.IsDevelopment())
     {
         PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
         {
             // This is default value, you can remove this line.
             options.AddDevelopmentEncryptionAndSigningCertificate = false;
         });
     }

     // Production or Staging environment
     if (!hostingEnvironment.IsDevelopment())
     {
         PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
         {
             options.AddDevelopmentEncryptionAndSigningCertificate = false;
         });

         PreConfigure<OpenIddictServerBuilder>(builder =>
         {
             builder.UseAspNetCore()
             .DisableTransportSecurityRequirement();
             // builder.AddSigningCertificate(GetSigningCertificate(hostingEnvironment));
             // builder.AddEncryptionCertificate(GetSigningCertificate(hostingEnvironment));
             //...
         });
         PreConfigure<OpenIddictBuilder>(builder =>
         {
             builder.AddServer(options =>
             {
                 options.AddDevelopmentEncryptionCertificate()
                        .AddDevelopmentSigningCertificate();
             });
             builder.AddValidation(options =>
             {
                 options.AddAudiences("dbt");
                 options.UseLocalServer();
                 options.UseAspNetCore();
             });
         });
     }
 }`

**Comment by JadynWong** [comment]
My solution (azure webapp or IIS)
```csharp
PreConfigure<OpenIddictServerBuilder>(builder =>
{
    builder.AddSigningCertificate(GetSigningCertificate(hostingEnvironment));
    builder.AddEncryptionCertificate(GetSigningCertificate(hostingEnvironment));
});

static X509Certificate2 GetSigningCertificate(IHostEnvironment hostingEnv)
{
    var bytes = File.ReadAllBytes(Path.Combine(hostingEnv.ContentRootPath, "authserver.pfx"));
    return new(bytes, "password",
        X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);
}
```

Better articles.
https://brianmeeker.me/2022/08/29/setting-up-abp-with-openiddict-on-azure-app-services/
https://community.abp.io/posts/deploying-abp.io-to-an-azure-appservice-ma8kukdp
https://support.abp.io/QA/Questions/3537/OpenIddict-WindowsCryptographicException-Access-is-denied
https://github.com/openiddict/openiddict-core/issues/976#issuecomment-643305644

**Comment by cgdif** [comment]
@JadynWong Thank you so much your solution worked.
