### ISSUE TITLE
【SignalR】Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints.

### ISSUE THREAD

**Issue by ZhaoYis** [abpframework/abp#18415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my source code like：
```c#
[HubRoute("/signalr-hubs/spider-app-notify")]
public class SpiderAppNotifyHub : AbpHub<ISpiderAppReceiveHub>, ISpiderAppNotifyHub
{
    public async Task SendToAllAsync(SpiderAppNotifyDto notify)
    {
        await Clients.All.ReceiveMessageAsync(new SpiderAppReceiveDto());
    }

    public override async Task OnConnectedAsync()
    {
        await Clients.All.ReceiveSystemMessageAsync(new SystemReceiveDto
        {
            Message = "hello，" + this.Clock.Now.ToString()
        });
        await base.OnConnectedAsync();
    }
}
```

```js
$(function () {
    var connection = new signalR.HubConnectionBuilder().withUrl("/signalr-hubs/spider-app-notify").build();

    connection.on("ReceiveMessage", function (res) {
        $('#MessageList').append('<li><strong><i class="fas fa-long-arrow-alt-right"></i> ' + res.message + '</strong></li>');
    });

    connection.on("ReceiveSystemMessage", function (res) {
        $('#MessageList').append('<li><strong>系统消息：<i class="fas fa-long-arrow-alt-right"></i> ' + res.message + '</strong></li>');
    });

    connection.start().then(function () {
        console.log("conn to signalR..")
    }).catch(function (err) {
        return console.error(err.toString());
    });

    $('#SendMessageButton').click(function (e) {
        e.preventDefault();
    });
});
```
run app：
```
[16:52:31 ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

/signalr-hubs/spider-app-notify/negotiate
/signalr-hubs/spider-app-notify/negotiate
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```
![image](https://github.com/abpframework/abp/assets/22954818/9221cbcf-3ca2-4fe4-9b62-10e4e37bb257)

### Version

8.0.0-rc.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by ZhaoYis** [comment]
if like this,app will be ok:
```c#
// [HubRoute("/signalr-hubs/spider-app-notify")]
[DisableConventionalRegistration]
public class SpiderAppNotifyHub : AbpHub<ISpiderAppReceiveHub>, ISpiderAppNotifyHub
{
    public async Task SendToAllAsync(SpiderAppNotifyDto notify)
    {
        await Clients.All.ReceiveMessageAsync(new SpiderAppReceiveDto());
    }

    /// <summary>
    /// Called when a new connection is established with the hub.
    /// </summary>
    public override async Task OnConnectedAsync()
    {
        await base.OnConnectedAsync();
        await Clients.All.ReceiveSystemMessageAsync(new SystemReceiveDto
        {
            Message = "hello，" + this.Clock.Now.ToString("s")
        });
    }
}
```

ConfigureServices like:
ps：the hub route cant be `/signalr-hubs/spider-app-notify`，any other routing is fine, as long as it doesn't duplicate the default one.
```c#
public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddTransient<SpiderAppNotifyHub>();

        Configure<AbpSignalROptions>(options =>
        {
            options.Hubs.Add(
                new HubConfig(
                    typeof(SpiderAppNotifyHub), //Hub type
                    "/signalr-hubs/spider-app-notify-1", //Hub route (URL)
                    hubOptions =>
                    {
                        //Additional options
                        hubOptions.LongPolling.PollTimeout = TimeSpan.FromSeconds(30);
                    }
                )
            );
        });
    }
```

```js
$(function () {
    var connection = new signalR.HubConnectionBuilder()
        .withUrl("/signalr-hubs/spider-app-notify-1")
        .withAutomaticReconnect()
        .configureLogging(signalR.LogLevel.Information)
        .build();

    connection.on("ReceiveMessageAsync", function (res) {
        $('#MessageList').append('<li><strong><i class="fas fa-long-arrow-alt-right"></i> ' + res.message + '</strong></li>');
    });

    connection.on("ReceiveSystemMessageAsync", function (res) {
        $('#MessageList').append('<li><strong>系统消息：<i class="fas fa-long-arrow-alt-right"></i> ' + res.message + '</strong></li>');
    });

    connection.start().then(function () {
        console.log("conn to signalR..")
    }).catch(function (err) {
        return console.error(err.toString());
    });

    $('#SendMessageButton').click(function (e) {
        e.preventDefault();
    });
});
```
![image](https://github.com/abpframework/abp/assets/22954818/3bad9b93-e333-4f21-ae0e-1a2f004b4e32)

**Comment by maliming** [comment]
Please share the source code of `ISpiderAppReceiveHub and ISpiderAppNotifyHub`.

**Comment by ZhaoYis** [comment]
Thank you for your reply,source code like:
@maliming 

[ISpiderAppReceiveHub.cs](https://github.com/ZhaoYis/Berry.Spider/blob/feature/SignalR-Integration/host/Berry.Spider.RealTime.Abstractions/Hubs/Apps/ISpiderAppReceiveHub.cs)
[ISpiderAppNotifyHub.cs](https://github.com/ZhaoYis/Berry.Spider/blob/feature/SignalR-Integration/host/Berry.Spider.RealTime.Abstractions/Hubs/Apps/ISpiderAppNotifyHub.cs)

**Comment by maliming** [comment]
Can you reproduce this in a new template project?

**Comment by ZhaoYis** [comment]
[SignalRDemo.zip](https://github.com/abpframework/abp/files/13644546/SignalRDemo.zip)
@maliming 

<img width="1440" alt="image" src="https://github.com/abpframework/abp/assets/22954818/8ec061b9-7ae9-4b7f-93dc-f538f89e37d1">

**Comment by maliming** [comment]
```
public override void PostConfigureServices(ServiceConfigurationContext context)
{
    context.Services.Configure<AbpSignalROptions>(options =>
    {
        var hubs = options.Hubs.DistinctBy(x => x.HubType).ToList();
        options.Hubs.Clear();
        options.Hubs.AddRange(hubs);
    });
}
```

**Comment by maliming** [comment]
We will fix this in the patch version.

**Comment by maliming** [comment]
another solution.

```cs
[ExposeServices(typeof(SpiderAppNotifyHub))]
public class SpiderAppNotifyHub : AbpHub<ISpiderAppReceiveHub>, ISpiderAppNotifyHub
```
