### ISSUE TITLE
OpenIddictTokens payload error on Oracle DB

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#18536]
Oracle version oracle-free 23.3. This occurs when to login is initiated on the AuthServer logs.

**"MVCORACLE"."OpenIddictTokens"."Payload" (actual: 3366, maximum: 2000)**

```txt
[00:32:23 INF] The authorization request was successfully validated.
[00:32:23 INF] Executing endpoint 'Volo.Abp.OpenIddict.Controllers.AuthorizeController.HandleAsync (Volo.Abp.OpenIddict.AspNetCore)'
[00:32:23 INF] Route matched with {action = "Handle", controller = "Authorize", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] HandleAsync() on controller Volo.Abp.OpenIddict.Controllers.AuthorizeController (Volo.Abp.OpenIddict.AspNetCore).
[00:32:23 INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
[00:32:23 INF] Executing SignInResult with authentication scheme (OpenIddict.Server.AspNetCore) and the following principal: System.Security.Claims.ClaimsPrincipal.
[00:32:23 ERR] 2023-12-21 00:32:23.558711 ThreadID:79  (ERROR)   OracleRelationalCommand.ExecuteReaderAsync() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12899: value too large for column "MVCORACLE"."OpenIddictTokens"."Payload" (actual: 3366, maximum: 2000)
ORA-06512: at line 7
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[00:32:23 ERR] Failed executing DbCommand (4ms) [Parameters=[:p5='?' (DbType = Binary), :p0='?' (Size = 40), :p6='?' (Size = 40), :p1='?' (DbType = DateTime), :p2='?' (DbType = Binary), :p3='?', :p4='?' (Size = 100), :cur0='?' (Direction = Output) (DbType = Object)], CommandType='Text', CommandTimeout='0']
DECLARE

v_RowCount INTEGER;

BEGIN

UPDATE "OpenIddictTokens" SET "ConcurrencyStamp" = :p0, "LastModificationTime" = :p1, "LastModifierId" = :p2, "Payload" = :p3, "ReferenceId" = :p4
WHERE "Id" = :p5 AND "ConcurrencyStamp" = :p6;
v_RowCount := SQL%ROWCOUNT;
OPEN :cur0 FOR SELECT v_RowCount FROM DUAL;

END;
[00:32:23 ERR] 2023-12-21 00:32:23.560829 ThreadID:79  (ERROR)   OracleExecutionStrategy.ExecuteAsync() :  Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12899: value too large for column "MVCORACLE"."OpenIddictTokens"."Payload" (actual: 3366, maximum: 2000)
ORA-06512: at line 7
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
```

This is the generated OpenIddictTokens migration:
```cs
 migrationBuilder.CreateTable(
                name: "OpenIddictTokens",
                columns: table => new
                {
                    ...
                    Payload = table.Column<string>(type: "NVARCHAR2(2000)", nullable: true),
                    ...
                },
```

@maliming Let me know if you need a reproducable environment for it.

**Comment by maliming** [comment]
I think this is an oracle problem, We can do nothing.

https://support.abp.io/QA/Questions/2913/How-to-Solve-AuditLogs---No-Log-Inserted-When-Size--2000#answer-95e46027-aa60-4bcf-412b-3a035e4e2f88

**Comment by gterdem** [comment]
Well, we need to document it somewhere though. 
The error image is not self-explanatory :)

![image](https://github.com/abpframework/abp/assets/25867/5341a8fb-b3c1-452e-b2a7-9d0b498873ac)

**Comment by maliming** [comment]
ok, I will update the document.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Oracle
