### ISSUE TITLE
[BUG] InitializeDynamicSettings not consider Migration

### ISSUE THREAD

**Issue by ohroy** [abpframework/abp#18798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

from the blog, we both use the new feature `migration` and `InitializeDynamicSettings`
https://github.com/abpframework/abp/blob/8a8d28a366a813f9fa6c06aea9adf6b01da86b6d/docs/en/Blog-Posts/2023-08-15%20v7_4_Preview/POST.md

but, Both the `InitializeDynamicSettings` and `CheckAndApplyDatabaseMigrationsAsync`  are running by `CheckAndApplyDatabaseMigrationsAsync`

https://github.com/abpframework/abp/blob/2f756de71f0f7495d5dfcb6ad2a402a2895e9e77/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/AbpSettingManagementDomainModule.cs#L51-L55

so, if `InitializeDynamicSettings`  fast than `CheckAndApplyDatabaseMigrationsAsync`, emmm, will cause

```
code-core-1  | [09:32:04 ERR] 42P01: relation "AbpSettingDefinitions" does not exist
code-core-1  |
code-core-1  | POSITION: 176
code-core-1  | Npgsql.PostgresException (0x80004005): 42P01: relation "AbpSettingDefinitions" does not exist
code-core-1  |
code-core-1  | POSITION: 176
code-core-1  |    at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
code-core-1  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
code-core-1  |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
code-core-1  |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
code-core-1  |    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
code-core-1  |    at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
code-core-1  |    at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
code-core-1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
code-core-1  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
code-core-1  |    at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
code-core-1  |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
code-core-1  |    at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
code-core-1  |    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
code-core-1  |    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
code-core-1  |    at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetListAsync(Boolean includeDetails, CancellationToken cancellationToken)
code-core-1  |    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
code-core-1  |    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
code-core-1  |    at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
code-core-1  |    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
code-core-1  |    at Volo.Abp.SettingManagement.StaticSettingSaver.UpdateChangedSettingsAsync(List`1 SettingRecords)
code-core-1  |    at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
code-core-1  |    at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
code-core-1  |    at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
code-core-1  |    at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
code-core-1  |    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
code-core-1  |    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
code-core-1  |    at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
code-core-1  |    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
code-core-1  |    at Volo.Abp.SettingManagement.AbpSettingManagementDomainModule.<>c__DisplayClass8_0.<<SaveStaticSettingsToDatabaseAsync>b__1>d.MoveNext()
code-core-1  | --- End of stack trace from previous location ---
code-core-1  |    at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
code-core-1  | --- End of stack trace from previous location ---
code-core-1  |    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
code-core-1  |   Exception data:
code-core-1  |     Severity: ERROR
code-core-1  |     SqlState: 42P01
code-core-1  |     MessageText: relation "AbpSettingDefinitions" does not exist
code-core-1  |     Position: 176
code-core-1  |     File: parse_relation.c
code-core-1  |     Line: 1381
code-core-1  |     Routine: parserOpenTable
```

then, the app will hang, and never migrate complete.

### Version

8.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by ohroy** [comment]
fixed by `OnPreApplicationInitializationAsync`
