### ISSUE TITLE
Cannot launch the published application

### ISSUE THREAD

**Issue by gaojianzhuang** [abpframework/abp#18816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run the application with debug mode, it works fine. But once I published with the release mode and deploy it in the IIS, the application cannot work.
The version: 5.3.2
Error Message:
[12:26:34 INF] Initialized all ABP modules.
[12:26:34 INF] Application started. Press Ctrl+C to shut down.
[12:26:34 INF] Hosting environment: Production
[12:26:34 INF] Content root path: D:\My.Test.Web\bin\Release\net6.0\publish
[12:26:34 INF] Request starting HTTP/1.1 GET http://localhost/zzhkg - -
[12:26:34 ERR] Connection ID "16861477058025357321", Request ID "8000000b-000c-ea00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
**System.ArgumentException: subpath can not be null or empty! (Parameter 'subpath')**
   at Volo.Abp.Check.NotNullOrEmpty(String value, String parameterName, Int32 maxLength, Int32 minLength)
   at Volo.Abp.AspNetCore.VirtualFileSystem.WebContentFileProvider.GetFileInfo(String subpath)
   at Microsoft.Extensions.FileProviders.CompositeFileProvider.GetFileInfo(String subpath)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.TryServeStaticFile(HttpContext context, String contentType, PathString subPath)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
[12:26:34 INF] Request finished HTTP/1.1 GET http://localhost/zzhkg - - - 500 - - 16.9433ms

### Version

5.3.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

Maybe some assets files missing after publish with release mode.

**Comment by maliming** [comment]
hi

You can try to override the `WebContentFileProvider` to `return new NotFoundFileInfo(subpath);` if `subpath` is `null`.

See https://github.com/abpframework/abp/pull/18822
