### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by ylmztalha** [abpframework/abp#18853]
I'm having trouble starting the application. First of all, the application runs on Docker Swarm. My applications are as follows
1) AuthServer
2) API
3)Blazor.
When starting the API server, I get the following error "The SSL connection could not be established, see inner exception.". After examining this error, I start the application by adding ""ASPNETCORE_ENVIRONMENT=Development"" and try again, but this time I get "ABP-LIC-ERROR - License check failed for 'Volo.Abp.Identity.Pro.HttpApi-v8.0.1.0". I get an error. I have no problems running the same application on my own computer.
Can you help with this issue?

Errors

**The SSL connection could not be established, see inner exception.** 

GetHealthReport threw an exception when trying to get report from https://*****/health-status configured with name Aizanoi Health Status.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HealthChecks.UI.Core.HostedService.HealthCheckReportCollector.GetHealthReportAsync(HealthCheckConfiguration configuration) in /_/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs:line 142
[10:56:55 INF] Notification is sent on same window time.

**ABP-LIC-ERROR - License check failed for 'Volo.Abp.Identity.Pro.HttpApi-v8.0.1.0**
ABP-LIC-ERROR - License check failed for 'Volo.Abp.Identity.Pro.HttpApi-v8.0.1.0'.
You need to log in using the command `abp login <username>`.
For more information, contact to license@abp.io.

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
