### ISSUE TITLE
in the standard abp multi-layer application, the auditlog error ignore of openid is not effective.

### ISSUE THREAD

**Issue by harvyh1985** [abpframework/abp#18931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i run this code to get userid for 3rd party login,its show me auditlog error
public async Task<WechatUserLoginDto> GetLoginAsync(UserDto login)
{
  var _openId = await Code2Info(login.Code);
  var _tenantId = Guid.Parse(_configuration["Project:TenantId"]);
   using (CurrentTenant.Change(_tenantId))
   {
        ...something...
      var _userEmail = login.email;
      var _tokenResponse = await GetTokenByOpenIdAsync(_userEmail, _openId);
      _result.Id = _userId;
      _result.Name = _name;
      _result.Avatar = _avatar;
      _result.Token = _tokenResponse.AccessToken;
   }
}

        private async Task<TokenResponse> GetTokenByOpenIdAsync(string userName, string openId)
        {
            var _authDisco = await new HttpClient().GetDiscoveryDocumentAsync(_configuration["AuthServer:Authority"]);
            using var _tokenClient = new HttpClient();
            _tokenClient.Timeout = new TimeSpan(0, 2, 0);
            _tokenClient.DefaultRequestHeaders.Add("__tenant", _configuration["Project:TenantId"]);
            var _tokenResponse = await _tokenClient.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = _authDisco.TokenEndpoint,
                ClientId = Identity_ClientId,
                UserName = userName,
                Password = openId,
                Scope = "Project"
            }, System.Threading.CancellationToken.None);
            return _tokenResponse;
        }

the function will return token but cause an error,so at last,openid will rollback the generated token and show a log like this:

2024-02-04 22:03:20.996 +08:00 [WRN] Could not save the audit log object: 
AUDIT LOG: [200: POST   ] /connect/token
- UserName - UserId                 :  - 
- ClientIpAddress        : ::1
- ExecutionDuration      : 1949
- Actions:
  - Volo.Abp.OpenIddict.Controllers.TokenController.HandleAsync (1539 ms.)
    {}

2024-02-04 22:03:20.996 +08:00 [ERR] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 390
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`3.FindAsync(TKey id, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.TenantManagement.TenantStore.GetCacheItemAsync(Nullable`1 id, String name)
   at Volo.Abp.TenantManagement.TenantStore.FindAsync(Guid id)
   at Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver.FindTenantConfigurationAsync(Guid tenantId)
   at Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver.ResolveAsync(String connectionStringName)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.ResolveConnectionStringAsync(String connectionStringName)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.InsertAsync(TEntity entity, Boolean autoSave, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.AuditLogging.AuditingStore.SaveLogAsync(AuditLogInfo auditInfo)
   at Volo.Abp.AuditLogging.AuditingStore.SaveAsync(AuditLogInfo auditInfo)

but i configure it at HttpApiHostModule:
    private void ConfigureAbpAuditingOption(ServiceConfigurationContext context)
    {
        context.Services.Configure<AbpAuditingOptions>(options =>
        {
            options.HideErrors = true;
        });
    }

I have tried the following code:
    private void ConfigureAbpAuditingOption(ServiceConfigurationContext context)
    {
        context.Services.Configure<AbpAuditingOptions>(options =>
        {
            options.HideErrors = true;
            options.IsEnabled = false;
        });
    }

It works and does not throw an exception, but I also need auditlog enabled, so what should I do?

### Version

8.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by harvyh1985** [comment]
This is an incorrect usage of "using", and the error is caused by prematurely closing the httpclient. Closing the auditlog will correct it because the auditlog write is still in progress when the close action is triggered.
