### ISSUE TITLE
Exception while trying to implement Module Entity Extensions in Blazor Server

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#19231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I tried to reproduce article
https://github.com/abpframework/abp/blob/8818b84e851640a162936aba4ed9de6f2e799e9b/docs/en/Community-Articles/2023-03-20-%20IdentityUser-Relationships/Post.md
On Blazor Service project
and Get Exception

### Reproduction Steps

1) Downloaded Latest version of abp-samples/BookStore-Blazor-EfCore
2) run the Acme.BookStore.DbMigrator project 
3) In Domain project and add the Department class from 
	https://github.com/onurpicakci/Abp-Identity-Relationship/tree/main/src/IdentityRelationship.Domain/Departments
4) In EntityFrameworkCore project, 
	in class BookStoreDbContext
	added:
    public DbSet<Department> Departments { get; set; }
5) In Domain.Shared project
	in class: BookStoreModuleExtensionConfigurator 
	 changed ConfigureExtraProperties 
	 to the same method ConfigureExtraProperties from:
	 https://github.com/onurpicakci/Abp-Identity-Relationship/blob/main/src/IdentityRelationship.Domain.Shared/IdentityRelationshipModuleExtensionConfigurator.cs
6)  In EntityFrameworkCore project 
   in class EntityFrameworkCore 
   changed Configure 
   to the same method Configure from 
   https://github.com/onurpicakci/Abp-Identity-Relationship/blob/main/src/IdentityRelationship.EntityFrameworkCore/EntityFrameworkCore/IdentityRelationshipEfCoreEntityExtensionMappings.cs
7) Created a new localization in  \Localization\BookStore\en.json file.	 
    "IdentificationNumber": "Identification Number",
    "DepartmentId": "Department"
8) Created new migration and run Migrator
9) In BookStore Db i see that the Department table has been added and DepartmentId has been added to AbpUsers table as written in article.
10) Before data Seeding i run Blazor in Visual studio
Open Users Menu Page
and get Exception
I understand that i did not made seeding but in any case exception must not occur
Here is part of Log
2024-03-07 10:02:03.848 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.848 +02:00 [DBG] Found in the cache: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.848 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.848 +02:00 [DBG] Found in the cache: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.853 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.853 +02:00 [DBG] Found in the cache: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.853 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.854 +02:00 [DBG] Found in the cache: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.858 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.858 +02:00 [DBG] Found in the cache: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.858 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.858 +02:00 [DBG] Found in the cache: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.863 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.863 +02:00 [DBG] Found in the cache: pn:U,pk:57725e09-5bff-882b-aac9-3a11256ccd70,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.863 +02:00 [DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.863 +02:00 [DBG] Found in the cache: pn:R,pk:admin,n:AbpIdentity.Users.Create
2024-03-07 10:02:03.886 +02:00 [WRN] Unhandled exception rendering component: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-07 10:02:03.892 +02:00 [ERR] Unhandled exception in circuit '82HYC_j-jyxhT-b7fBQKSp1zvdHP0OyYBBGNM_1q9VI'.
System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-07 10:02:03.909 +02:00 [INF] Executed endpoint '/_blazor'
2024-03-07 10:02:03.915 +02:00 [INF] Request finished HTTP/1.1 GET https://localhost:44380/_blazor?id=MX3nFeMKFOp93YdgCrdmVQ - - - 101 - - 7133.5738ms
2024-03-07 10:02:03.953 +02:00 [WRN] Unhandled exception rendering component: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-07 10:02:03.953 +02:00 [ERR] Unhandled exception in circuit '82HYC_j-jyxhT-b7fBQKSp1zvdHP0OyYBBGNM_1q9VI'.
System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Version

From repository

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Elencon** [comment]
Not taked into account differences between Blazor and Web

**Comment by Elencon** [comment]
Not taked into account differences between Blazor and Web
