### ISSUE TITLE
CosmosDb Integration

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#1935]
Is possible to integrate abp with CosmosDb?
Im doing like the code below:
```csharp
public class CosmosDbModule: AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<MyDbContext>(options =>
            {
                options.AddDefaultRepositories();
                options.AddRepository<Table1, Table1Repository>();
            });

            Configure<AbpDbContextOptions>(options =>
            {
                options.Configure(x =>
                {
                    x.DbContextOptions.UseCosmos("host", key, "database");
                });
            });
        }
    }
```

But when i try to do that:

```
// ITable1Repository _repository;
var data = _repository.GetList();
```

I got the following error: Value cannot be null. (Parameter 'stream')

Stacktrace:
```
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.DocumentEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetList(Boolean includeDetails)
   at Castle.Proxies.Invocations.IReadOnlyBasicRepository`1_GetList.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.Proceed()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.Intercept(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.InterceptSyncMethod(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IBasicRepository`1Proxy.GetList(Boolean includeDetails)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
```

Am I missing something? or maybe is a bug?

**Comment by maliming** [comment]
It seems like a problem with EF Core. Is there a similar problem when you use EF Core + Cosmos alone?
https://github.com/aspnet/EntityFrameworkCore/issues/15473
https://github.com/aspnet/EntityFrameworkCore/issues/17435

**Comment by lommez** [comment]
@maliming, If I call the Database.EnsureCreated() in the DbContext constructor everything works fine!
I don't know if is the best place to call it, do you have any suggestion?
thanks

**Comment by maliming** [comment]
This is a problem with EF Core. see https://github.com/aspnet/EntityFrameworkCore/issues/17435#issue-485492387

You can temporarily resolve it by calling `Database.EnsureCreated()`.
