### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by easyfast** [abpframework/abp#1937]
I update the CLI from 0.21.0 to 0.22.0:

C:\Windows\system32>dotnet tool update -g Volo.Abp.Cli
工具“volo.abp.cli”已成功从版本“0.21.0”更新到版本“0.22.0”。

Then I Create a new project:

PS D:\Work\LawfirmOA\New> abp new LawfirmOA -u angular
[17:01:57 INF] ABP CLI (https://abp.io)
[17:01:58 INF] Version 0.22.0 (Stable channel)
[17:01:58 INF] Creating your project...
[17:01:58 INF] Project name: LawfirmOA
[17:01:58 INF] UI Framework: Angular
[17:01:58 INF] Output folder: D:\Work\LawfirmOA\New
[17:02:00 INF] Downloading template: app, version: 0.22.0
[17:02:09 ERR] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\NewtonsoftJsonSerializer.cs:line 27
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 48
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 125
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 69
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

Then i rename the project   like this:

PS D:\Work\LawfirmOA\New> abp new JingShOnline.LawfirmOA -u angular
[17:02:38 INF] ABP CLI (https://abp.io)
[17:02:39 INF] Version 0.22.0 (Stable channel)
[17:02:39 INF] Creating your project...
[17:02:39 INF] Project name: JingShOnline.LawfirmOA
[17:02:39 INF] UI Framework: Angular
[17:02:39 INF] Output folder: D:\Work\LawfirmOA\New
[17:02:42 INF] Downloading template: app, version: 0.22.0
[17:02:54 ERR] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\NewtonsoftJsonSerializer.cs:line 27
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 48
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 125
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 69
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

**Comment by easyfast** [comment]
找到问题了，目录名不能包含项目名。
PS D:\Work\Study\New>  abp new LawfirmOA -u angular
[17:14:44 INF] ABP CLI (https://abp.io)
[17:14:44 INF] Version 0.22.0 (Stable channel)
[17:14:45 INF] Creating your project...
[17:14:45 INF] Project name: LawfirmOA
[17:14:45 INF] UI Framework: Angular
[17:14:45 INF] Output folder: D:\Work\Study\New
[17:14:46 INF] Downloading template: app, version: 0.22.0
[17:15:05 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[17:15:09 INF] 'LawfirmOA' has been successfully created to 'D:\Work\Study\New'
PS D:\Work\Study\New>

**Comment by gdlcf88** [comment]
```
PS D:\Work\LawfirmOA\New> abp new LawfirmOA -u angular
[13:12:11 INF] ABP CLI (https://abp.io)
[13:12:11 INF] Version 0.22.0 (Stable channel)
[13:12:12 INF] Creating your project...
[13:12:12 INF] Project name: LawfirmOA
[13:12:12 INF] UI Framework: Angular
[13:12:12 INF] Output folder: D:\Work\LawfirmOA\New
[13:12:15 INF] Using cached template: app, version: 0.22.0
[13:12:18 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[13:12:20 INF] 'LawfirmOA' has been successfully created to 'D:\Work\LawfirmOA\New'
PS D:\Work\LawfirmOA\New>
```

Cannot reproduce this problem.

**Comment by ildafon** [comment]
The same problem during creating new project.

F:\WebProjects>abp new Acme.BookStore -u angular -d mongodb
[05:46:19 INF] ABP CLI (https://abp.io)
[05:46:19 INF] Version 1.0.2 (Stable channel)
[05:46:20 INF] Creating your project...
[05:46:20 INF] Project name: Acme.BookStore
[05:46:20 INF] Database provider: MongoDb
[05:46:20 INF] UI Framework: Angular
[05:46:20 INF] Output folder: F:\WebProjects
[05:46:21 ERR] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\NewtonsoftJsonSerializer.cs:line 27
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 107
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

F:\WebProjects>

**Comment by maliming** [comment]
@ildafon see https://github.com/abpframework/abp/issues/2048#issuecomment-548174237
