### ISSUE TITLE
Blazorise BarItem NullReferenceException when updating to new Blazorise

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#19405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I updated my abp.io 8.0.5 (commercial) to use Blazorise 1.5.0 and everything looks fine until I click the top rigtht menubar to try to log off. Then I get this error and the dreaded yellow reload banner at the bottom.

```
[08:41:39 WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarItem.OnDropdownVisible()
   at Blazorise.BarDropdown.SetVisibleState(Boolean visible)
   at Blazorise.BarDropdown.Toggle(String dropdownToggleElementId)
   at Blazorise.BarDropdownToggle.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[08:41:39 ERR] Unhandled exception in circuit '6sbqpfDqqP9xp_Z7A6ngUUWehMBr6ndciy-f7msLTCw'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarItem.OnDropdownVisible()
   at Blazorise.BarDropdown.SetVisibleState(Boolean visible)
   at Blazorise.BarDropdown.Toggle(String dropdownToggleElementId)
   at Blazorise.BarDropdownToggle.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Reproduction Steps

Create new Blazor Server project and update to Blazorise 1.5.0

### Expected behavior

No error and being able to access all the menu items.

### Actual behavior

Error and yellow reload banner and not being able to log of

### Regression?

Yes

### Version

8.0.4

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by sturlath** [comment]
I would love to have a workaround for this if possible. Any idea what I could try out?

**Update:** I have created a new commercial **and** open source abp.io and updated them to use Blazorise 1.5.0 and they have no issues... but I cant figure out where the issue is... suggestions?

**Comment by realLiangshiwei** [comment]
https://github.com/Megabit/Blazorise/pull/5408
