### ISSUE TITLE
HTTP 500 Error while trying to download the source code of Volo.Abp.LeptonXTheme.Pro

### ISSUE THREAD

**Issue by chandralk** [abpframework/abp#19420]
I'm unable to download the source code for the latest version of `Volo.Abp.LeptonXTheme.Pro`. I am getting a HTTP 500 error message. I have logged in with commercial account.

* **ABP CLI version** : 8.0.5
* **User Interface**: MVC
* **Database provider**: EF Core
* **Stack trace**:
`ABP CLI 8.0.5
Downloading source code of Volo.Abp.LeptonXTheme.Pro (Latest)
Output folder: C:\Users\<username>\Desktop\Modules
Downloading module: Volo.Abp.LeptonXTheme.Pro, version: 3.0.5
Error occured while downloading source-code from https://abp.io/api/download/module/ : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Tue, 26 Mar 2024 11:23:25 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-cache,no-store
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.-6OvtTX3HwI=CfDJ8G-tnCm3u9lKrhYtPHu2TLpDN6xe3z3Q6zn0IzHmjo_VrYbJljYZaa1bFucOUrXEA5Z6nvv4maDjVIbxTUSQiVXVqh5p1nk-mWM7pWHnq0w2yZkZ5i_prliOjYDEOw7lOKnJBK3_VdgP7_8MkzOrp9o; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8G-tnCm3u9lKrhYtPHu2TLr4IiR6E1O5nkrQPi-Qins_FPppdj6xp09V6WrDeHjFMjI0ejJVoJxMwtJfiP8H8jmzg02-GanW4vC_Oy_nMS-mqMjhkzDOHN0SpGFPuH5-yPl7L-obYjZXt64p6XxS5uUxeJ3LRJTcz9uNxm4YnPjp0wF4LDjFKxYMYsqfAtYnYA; expires=Wed, 26 Mar 2025 11:23:25 GMT; path=/; secure; samesite=none
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: SAMEORIGIN
  x-correlation-id: a60c9031f5394f04b5f838d36d7ebb11
  CF-Cache-Status: DYNAMIC
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=B09Ci0WrxiMp6gsb1MyYe%2B9mK98f%2BYfG5Vq2M5AdOgo3QyVFlTjIcsUBmAAY%2FcGmooAA7FmlCE8FTJkugpIKFNpZb3hj2djjDb3DzBASILepWDVGZrjUQg%3D%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 86a6c4adbe5df44a-BOM
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
'<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan``1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter``1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter``1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan``1 utf8Json, JsonTypeInfo``1 jsonTypeInfo, Nullable``1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan``1 json, JsonTypeInfo``1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Json.SystemTextJson\Volo\Abp\Json\SystemTextJson\AbpSystemTextJsonSerializer.cs:line 25
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 258
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases, Boolean skipCache) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 123
   at Volo.Abp.Cli.ProjectBuilding.ModuleProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ModuleProjectBuilder.cs:line 48
   at Volo.Abp.Cli.Commands.Services.SourceCodeDownloadService.DownloadModuleAsync(String moduleName, String outputFolder, String version, String gitHubAbpLocalRepositoryPath, String gitHubVoloLocalRepositoryPath, AbpCommandLineOptions options) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\Services\SourceCodeDownloadService.cs:line 39
   at Volo.Abp.Cli.Commands.GetSourceCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\GetSourceCommand.cs:line 59
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 169
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 77`
* Steps needed to **reproduce** the problem: `abp get-source Volo.Abp.LeptonXTheme.Pro`

Please check and help.

**Comment by maliming** [comment]
Hi

The 500 error has been fixed. Can you try again?

**Comment by chandralk** [comment]
Resolved and I'm able to download.
Thanks!
