### ISSUE TITLE
Tenant Entity Extension

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#19430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use latest version of ABP SQL Server & Blazor Server

I created project with entity extensions exactly as described in https://onurpicakci.github.io/Identity-User-relationship/
with  method

```cs
  private static void ConfigureExtraProperties()
  {
      OneTimeRunner.Run(() =>
      {
          ObjectExtensionManager.Instance.Modules()
              .ConfigureIdentity(identity =>
              {
                  identity.ConfigureUser(user =>
                  {
                      user.AddOrUpdateProperty<int>(
                          "ClientId",
                          property =>
                          {
                              property.UI.Lookup.Url = "/api/app/client";
                              property.UI.Lookup.DisplayPropertyName = "name";
                          }
                      );
                  });
              });
      });
  }

```
in ModuleExtensionConfigurator class 

and method  
```cs
public static void Configure()
  {
      CsmsGlobalFeatureConfigurator.Configure();
      CsmsModuleExtensionConfigurator.Configure();

      ObjectExtensionManager.Instance
          .MapEfCoreProperty<IdentityUser, int>("ClientId");
}); 
}
```
in EfCoreEntityExtensionMappings

and everything works fine as documented
then , i tried to make extensions to Tenant only changing these methods to 

```cs
  private static void ConfigureExtraProperties()
  {
      OneTimeRunner.Run(() =>
      {
          ObjectExtensionManager.Instance.Modules()
              .ConfigureTenantManagement(tenantConfig =>
              {
                  tenantConfig.ConfigureTenant(tenant =>
                  {
                      tenant.AddOrUpdateProperty<int>(
                          "ClientId",
                          property =>
                          {
                              property.UI.Lookup.Url = "/api/app/client";
                              property.UI.Lookup.DisplayPropertyName = "Client";
                          }
                      );
                  });
              });

      });
  }
```
in ModuleExtensionConfigurator class 

and method  

```cs
public static void Configure()
{
    CsmsGlobalFeatureConfigurator.Configure();
    CsmsModuleExtensionConfigurator.Configure();

         OneTimeRunner.Run(() =>
        {
            ObjectExtensionManager.Instance
                .MapEfCoreProperty<Tenant, int>("ClientId");

        });
}
```
All migrations were made properly and tables an columns appear in DB

I get exception in Log
```cs
	System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-27 06:21:58.984 +02:00 [ERR] Unhandled exception in circuit 'm1Dp5mtMlOL0bT5tyca-kqqpz8Kthr6AGWmbOloimbA'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-27 06:21:58.994 +02:00 [INF] Executed endpoint '/_blazor'
2024-03-27 06:21:58.994 +02:00 [INF] Request finished HTTP/1.1 GET https://localhost:44329/_blazor?id=rYMoDbXVohx2T7jwGE6O2A - 101 null null 5551.3319ms
2024-03-27 06:21:59.105 +02:00 [WRN] Unhandled exception rendering component: The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-27 06:21:59.105 +02:00 [ERR] Unhandled exception in circuit 'm1Dp5mtMlOL0bT5tyca-kqqpz8Kthr6AGWmbOloimbA'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.GetLookupItemsAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.SearchFilterChangedAsync(String filter)
   at Volo.Abp.BlazoriseUI.Components.ObjectExtending.LookupExtensionProperty`2.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
   when i comment line
   property.UI.Lookup.Url = "/api/app/client";
   exception disappears but but also data in combo in Create Tenant

### Version

8.04

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

**Comment by maliming** [comment]
hi

You can check the source code of the sample first.

https://github.com/onurpicakci/Abp-Identity-Relationship

**Comment by Elencon** [comment]
Sorry . You are right it was my bug
