### ISSUE TITLE
Antiforgery token validation failed in ABP 8.2.0

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#20185]
Application error in 'Settings' page.
![1720492981697](https://github.com/abpframework/abp/assets/24971860/d0b8b157-ad15-445b-9884-4621f639ae7f)

Exceptions: 
```c#
[10:42:43 INF] Executing endpoint '/SettingManagement/Index'
[10:42:43 INF] Route matched with {page = "/SettingManagement/Index", action = "", controller = "", area = ""}. Executing page /SettingManagement/Index
[10:42:43 INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
[10:42:43 INF] Antiforgery token validation failed. The antiforgery token could not be decrypted.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.DeserializeTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet, AntiforgeryToken& cookieToken, AntiforgeryToken& requestToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
[10:42:43 INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
[10:42:43 INF] Executing StatusCodeResult, setting HTTP status code 400
[10:42:43 INF] Executed page /SettingManagement/Index in 1.5172ms
[10:42:43 INF] Executed endpoint '/SettingManagement/Index'
[10:42:43 INF] Request finished HTTP/1.1 POST http://localhost:5601/SettingManagement?handler=RenderView&id=Volo.Abp.EmailSetting - 400 0 null 10.3184ms
```

I download ABP 8.2.0 template app from official website. And modify start url from `https` to `http`, then start application. It works well until clicked the `Settings` page.

* ABP Version: 8.2.0
* Create project with: `abp new Acme.BookStore -dbms MySQL --tiered -csf  `

**Comment by maliming** [comment]
> And modify start url from https to HTTP

You have to handle the **samesite** cookies when using **http**.

https://learn.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-8.0

**Comment by weiwxg** [comment]
https://community.abp.io/posts/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n
