### ISSUE TITLE
After upgrading Ocelot 13.8.0, I found a new problem: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance

### ISSUE THREAD

**Issue by w21976169** [abpframework/abp#2028]
### code:
 `
 app.MapWhen(
                ctx =>
                    ctx.Request.Path.ToString().StartsWith("/api/abp/") ||
                    ctx.Request.Path.ToString().StartsWith("/Abp/") ||
                    ctx.Request.Path.ToString().StartsWith("/Test/"),
                app2 => { app2.UseMvcWithDefaultRouteAndArea(); }
            );
`

### message:
The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance. To use Endpoint Routing with 'Map(...)', make sure to call 'IApplicationBuilder.UseRouting' before 'IApplicationBuilder.UseEndpoints' for each branch of the middleware pipeline.

InvalidOperationException: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance. To use Endpoint Routing with 'Map(...)', make sure to call 'IApplicationBuilder.UseRouting' before 'IApplicationBuilder.UseEndpoints' for each branch of the middleware pipeline.
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.VerifyEndpointRoutingMiddlewareIsRegistered(IApplicationBuilder app, out DefaultEndpointRouteBuilder endpointRouteBuilder)
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
Microsoft.AspNetCore.Builder.AbpAspNetCoreMvcApplicationBuilderExtensions.UseMvcWithDefaultRouteAndArea(IApplicationBuilder app, Action<IEndpointRouteBuilder> additionalConfigurationAction) in AbpAspNetCoreMvcApplicationBuilderExtensions.cs
+
            return app.UseEndpoints(endpoints =>
InternalGateway.Host.InternalGatewayHostModule+<>c.<OnApplicationInitialization>b__1_2(IApplicationBuilder app2) in InternalGatewayHostModule.cs
+
                app2 => { app2.UseMvcWithDefaultRouteAndArea(); }
Microsoft.AspNetCore.Builder.MapWhenExtensions.MapWhen(IApplicationBuilder app, Func<HttpContext, bool> predicate, Action<IApplicationBuilder> configuration)
InternalGateway.Host.InternalGatewayHostModule.OnApplicationInitialization(ApplicationInitializationContext context) in InternalGatewayHostModule.cs
+
            app.MapWhen(
Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.Initialize(ApplicationInitializationContext context, IAbpModule module) in DefaultModuleLifecycleContributor.cs
+
            (module as IOnApplicationInitialization)?.OnApplicationInitialization(context);
Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in ModuleManager.cs
+
                    Contributor.Initialize(context, module.Instance);
Volo.Abp.AbpApplicationBase.InitializeModules() in AbpApplicationBase.cs
+
                scope.ServiceProvider
Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider) in AbpApplicationWithExternalServiceProvider.cs
+
            InitializeModules();
Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app) in AbpApplicationBuilderExtensions.cs
+
            app.ApplicationServices.GetRequiredService<IAbpApplicationWithExternalServiceProvider>().Initialize(app.ApplicationServices);
InternalGateway.Host.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
           app.InitializeApplication();
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

**Comment by maliming** [comment]
Try the following code, calling `app2.UseRouting` before calling `app2.UseMvcWithDefaultRouteAndArea`
```
app.MapWhen(
	ctx =>
		ctx.Request.Path.ToString().StartsWith("/api/abp/") ||
		ctx.Request.Path.ToString().StartsWith("/Abp/") ||
		ctx.Request.Path.ToString().StartsWith("/Test/"),
	app2 =>
	{
		app2.UseRouting();
		app2.UseMvcWithDefaultRouteAndArea();
	}
);

```

I will update the code for the microservices example.

**Comment by w21976169** [comment]
Thanks, this problem is solved, however, in applications.BackendAdmin.Host, I found a new problem:

Logs/log.txt:
`
2019-10-29 12:46:19.344 +08:00 [ERR] Connection id "0HLQS5BLAVA2S", Request id "0HLQS5BLAVA2S:00000003": An unhandled exception was thrown by the application.
Microsoft.Extensions.Options.OptionsValidationException: Cookie.Expiration is ignored, use ExpireTimeSpan instead.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Users\wynnyo\source\repos\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Tracing\AbpCorrelationIdMiddleware.cs:line 27
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-10-29 12:46:19.348 +08:00 [INF] Request finished in 26.0622ms 500 
`

**Comment by maliming** [comment]
@w21976169 https://github.com/abpframework/abp/pull/2027/commits/0ffbb514497f85ac7a6d8855544a6d0fd0dbface

**Comment by w21976169** [comment]
@maliming 
thanks，in the BackendAdminApp.Host.HomeController 

### code:
`
 public ActionResult Index()
        {
            return Redirect("/Identity/Users");
        }
`
### log
`
019-10-29 14:03:50.168 +08:00 [ERR] Connection id "0HLQS6F4E8UVU", Request id "0HLQS6F4E8UVU:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: Endpoint /Identity/Users/Index contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code. The call to app.UseAuthorization() must appear between app.UseRouting() and app.UseEndpoints(...).
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Users\wynnyo\source\repos\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\RequestLocalization\AbpRequestLocalizationMiddleware.cs:line 32
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Users\wynnyo\source\repos\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Tracing\AbpCorrelationIdMiddleware.cs:line 27
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-10-29 14:03:50.169 +08:00 [INF] Request finished in 43.2094ms 500 
`

**Comment by maliming** [comment]
Try adding `app.UseAuthorization()` after` app.UseAuthentication()`

![image](https://user-images.githubusercontent.com/6908465/67748552-26701a80-fa66-11e9-83b7-072bfdcafe82.png)

**Comment by qiang999** [comment]
adding app.UseAuthorization() after app.UseAuthentication()
loading without feedback  Authserver.Host
![image](https://user-images.githubusercontent.com/15817336/67750099-7d2b2380-fa69-11e9-8935-723decd73fbf.png)
logs:
[INF] Authorization failed.
[INF] AuthenticationScheme: oidc was challenged.

**Comment by w21976169** [comment]
@maliming 
Hi,  add `app.UseAuthorization()` , 

After adding `app.UseAuthorization()` , the browser automatically redirect to url:
`
http://localhost:51954/Account/AccessDenied?ReturnUrl=%2FIdentity%2FUsers  
`
### log
`
2019-10-29 17:03:58.634 +08:00 [INF] Authorization failed.
2019-10-29 17:03:58.635 +08:00 [INF] AuthenticationScheme: Cookies was forbidden.
2019-10-29 17:03:58.635 +08:00 [INF] AuthenticationScheme: oidc was forbidden.
2019-10-29 17:03:58.636 +08:00 [INF] Request finished in 1155.4987ms 302 
2019-10-29 17:03:58.659 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost:51954/Account/AccessDenied?ReturnUrl=%2FIdentity%2FUsers  
2019-10-29 17:03:58.663 +08:00 [INF] Request finished in 3.9639ms 404 
`

**Comment by maliming** [comment]
This may require @hikalkan to help.

**Comment by leeson0219** [comment]
In `AuthServerDataSeeder.cs`, `backend-admin-app-client` missing client permissions, just add `permissions: new[] { IdentityPermissions.Users.Default, "ProductManagement.Product" }` that can be resolved.
