### ISSUE TITLE
New APB Studio Cli errors out on Linux

### ISSUE THREAD

**Issue by rlavaud** [abpframework/abp#20398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the new studio cli on **Linux** to create new project I get an error about Volo.Abp.Studio.Extensions.StandardSolutionTemplates not found.

I installed the nugget package Volo.Abp.Studio.Extensions.StandardSolutionTemplates in a dummy project to force push the files in my nugget cache but still got the same error

Then I noticed a discrepancy in the naming of the dll:
Volo.Abp.Studio.Extensions.StandardSolutionTemplates.**CLI**.dll in the error Volo.Abp.Studio.Extensions.StandardSolutionTemplates.**Cli**.dll  in the nugget

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/home/rlavaud/.nuget/packages/volo.abp.studio.extensions.standardsolutiontemplates/0.7.4/lib/net8.0/Volo.Abp.Studio.Extensions.StandardSolutionTemplates.CLI.dll'. The system cannot find the file specified.

File name: '/home/rlavaud/.nuget/packages/volo.abp.studio.extensions.standardsolutiontemplates/0.7.4/lib/net8.0/Volo.Abp.Studio.Extensions.StandardSolutionTemplates.CLI.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyBinder, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Volo.Abp.Modularity.PlugIns.FilePlugInSource.oWyDcarYV0KjwPQw6sv(Object, Object)
   at Volo.Abp.Modularity.PlugIns.FilePlugInSource.GetModules()
   at Volo.Abp.Modularity.PlugIns.PlugInSourceExtensions.xeUE1wro479aX58CwsJ(Object)
   at Volo.Abp.Modularity.PlugIns.PlugInSourceExtensions.GetModulesWithAllDependencies(IPlugInSource plugInSource, ILogger logger)
   at Volo.Abp.Modularity.PlugIns.PlugInSourceList.<>c__DisplayClass0_0.HJlek2Babk(IPlugInSource pluginSource)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at Volo.Abp.Modularity.PlugIns.PlugInSourceList.GetAllModules(ILogger logger)
   at Volo.Abp.Modularity.ModuleLoader.FillModules(List`1 modules, IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources)
   at Volo.Abp.Modularity.ModuleLoader.xw9KSgOsJE(IServiceCollection  , Type  , PlugInSourceList  )
   at Volo.Abp.Modularity.ModuleLoader.LoadModules(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources)
   at Volo.Abp.AbpApplicationBase.LoadModules(IServiceCollection services, AbpApplicationCreationOptions options)
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithInternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithInternalServiceProvider..ctor(Type startupModuleType, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.CreateAsync[TStartupModule](Action`1 optionsAction)
   at Volo.Abp.Studio.Cli.Program.RtRr72CxI(Object  )
   at Volo.Abp.Studio.Cli.Program.<Main>(String[] args)
Aborted (core dumped)
`

### Reproduction Steps

Install the new abp cli
`dotnet tool install -g Volo.Abp.Studio.Cli`

Create new project
`abp new BookStore -t app -u blazor-webapp`

### Expected behavior

New project created

### Actual behavior

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/home/rlavaud/.nuget/packages/volo.abp.studio.extensions.standardsolutiontemplates/0.7.4/lib/net8.0/Volo.Abp.Studio.Extensions.StandardSolutionTemplates.CLI.dll'. The system cannot find the file specified.

### Version

8.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by berkansasmaz** [comment]
Hello, first of all, thank you for reporting the issue. We aim to resolve the issue as soon as possible. It will probably be fixed in the next CLI version. 

---

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
