### ISSUE TITLE
System.InvalidOperationException: 'Unable to resolve service for type 'Volo.Abp.EntityFrameworkCore.IDbContextProvider`1[XXXX.EntityFrameworkCore.IndoDbContext]' while attempting to activate 'EfCoreXXXXXXRepository'.'

### ISSUE THREAD

**Issue by abdoutech93** [abpframework/abp#20438]
`System.InvalidOperationException: 'Unable to resolve service for type 'Volo.Abp.EntityFrameworkCore.IDbContextProvider`1[XXXX.EntityFrameworkCore.IndoDbContext]' while attempting to activate 'EfCoreXXXXXXRepository'.'`

* Your **ABP Framework version** => 8.2.0
* Your **User Interface** type => WPF
* Your database provider => EF Core
* Exception message and **stack trace** 
`System.InvalidOperationException: 'Unable to resolve service for type 'Volo.Abp.EntityFrameworkCore.IDbContextProvider`1[XXXX.EntityFrameworkCore.AppDbContext]' while attempting to activate 'EfCoreXXXXXXRepository'.'`

PS: The same DbContext and Repository are used on the web version "MVC" and API version and Works fine, this error appears only on WPF.

**Comment by maliming** [comment]
hi

Please share the steps and code to reproduce the problem.

**Comment by abdoutech93** [comment]
it seems like the IDbContextProvider  is not registred. 
And I'm sure DbContext is registred. 

How can I register Volo.Abp.EntityFrameworkCore.IDbContextProvider ?

**Comment by abdoutech93** [comment]
```
2024-11-23 15:42:05.655 +00:00 [INF] Starting WPF host.
2024-11-23 15:42:07.464 +00:00 [INF] Loaded ABP modules:
2024-11-23 15:42:07.465 +00:00 [INF] - BuisenessAdvisorDesktop.BusinessAdvisorAppModule
2024-11-23 15:42:07.465 +00:00 [INF]   - Volo.Abp.Autofac.AbpAutofacModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.Castle.AbpCastleCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]   - Indo.IndoApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Indo.IndoDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Indo.IndoDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Validation.AbpValidationModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Validation.AbpValidationAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Localization.AbpLocalizationModule
2024-11-23 15:42:07.465 +00:00 [INF]               - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2024-11-23 15:42:07.465 +00:00 [INF]               - Volo.Abp.Settings.AbpSettingsModule
2024-11-23 15:42:07.465 +00:00 [INF]                 - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]                 - Volo.Abp.Security.AbpSecurityModule
2024-11-23 15:42:07.465 +00:00 [INF]                 - Volo.Abp.Data.AbpDataModule
2024-11-23 15:42:07.465 +00:00 [INF]                   - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2024-11-23 15:42:07.465 +00:00 [INF]                   - Volo.Abp.Uow.AbpUnitOfWorkModule
2024-11-23 15:42:07.465 +00:00 [INF]                   - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]               - Volo.Abp.Threading.AbpThreadingModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Json.SystemTextJson.AbpJsonSystemTextJsonModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Json.AbpJsonAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Timing.AbpTimingModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.Identity.AbpIdentityDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Users.AbpUsersDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Features.AbpFeaturesModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2024-11-23 15:42:07.465 +00:00 [INF]               - Volo.Abp.MultiTenancy.AbpMultiTenancyAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.Auditing.AbpAuditingModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Json.AbpJsonModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Auditing.AbpAuditingContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.Domain.AbpDddDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.EventBus.AbpEventBusModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Guids.AbpGuidsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Specifications.AbpSpecificationsModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Caching.AbpCachingModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Serialization.AbpSerializationModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Domain.AbpDddDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.AutoMapper.AbpAutoMapperModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.Identity.AbpIdentityDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.Users.AbpUsersDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Users.AbpUsersAbstractionModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Authorization.AbpAuthorizationModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.IdentityServer.AbpIdentityServerDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.PermissionManagement.IdentityServer.AbpPermissionManagementDomainIdentityServerModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.Emailing.AbpEmailingModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.TextTemplating.AbpTextTemplatingModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.TextTemplating.Scriban.AbpTextTemplatingScribanModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.TextTemplating.AbpTextTemplatingCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Indo.HRM.HRMDomainModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Indo.HRM.HRMDomainSharedModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.Account.AbpAccountApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.Account.AbpAccountApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Application.AbpDddApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.Identity.AbpIdentityApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]           - Volo.Abp.Application.AbpDddApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.Http.AbpHttpAbstractionsModule
2024-11-23 15:42:07.465 +00:00 [INF]             - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.UI.Navigation.AbpUiNavigationModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.UI.AbpUiModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Indo.IndoApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.SettingManagement.AbpSettingManagementApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Indo.HRM.HRMApplicationContractsModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.TenantManagement.AbpTenantManagementApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.SettingManagement.AbpSettingManagementApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Indo.HRM.HRMApplicationModule
2024-11-23 15:42:07.465 +00:00 [INF]   - Indo.EntityFrameworkCore.IndoEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]       - Volo.Abp.Users.EntityFrameworkCore.AbpUsersEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]         - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.IdentityServer.EntityFrameworkCore.AbpIdentityServerEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.EntityFrameworkCore.SqlServer.AbpEntityFrameworkCoreSqlServerModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Volo.Abp.FeatureManagement.EntityFrameworkCore.AbpFeatureManagementEntityFrameworkCoreModule
2024-11-23 15:42:07.465 +00:00 [INF]     - Indo.HRM.EntityFrameworkCore.HRMEntityFrameworkCoreModule
2024-11-23 15:42:07.517 +00:00 [INF] Initialized all ABP modules.
2024-11-23 15:42:07.933 +00:00 [ERR] An exception was thrown while activating Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext])' on type 'SettingManagementDbContext'.
 ---> System.TypeLoadException: Method 'GetDatabaseLock' in type 'Microsoft.EntityFrameworkCore.SqlServer.Migrations.Internal.SqlServerHistoryRepository' from assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at lambda_method125(Closure, Object[])
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass39_0.<OnActivated>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CoreEventMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextWithTransactionAsync(IUnitOfWork unitOfWork)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetDbSetAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetQueryableAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetListAsync(Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.SettingManagement.StaticSettingSaver.UpdateChangedSettingsAsync(List`1 SettingRecords)
   at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
   at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
   at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
   at Volo.Abp.SettingManagement.StaticSettingSaver.SaveAsync()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.SettingManagement.AbpSettingManagementDomainModule.<>c__DisplayClass8_0.<<SaveStaticSettingsToDatabaseAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
```

**Comment by maliming** [comment]
hi

You can share a simple project to reproduce.

**Comment by abdoutech93** [comment]
@maliming 
Solved the previous problem, now the appservice is injected but when calling the repository I get this error : 
System.NullReferenceException: 'Object reference not set to an instance of an object.'

 with this stacktrace : 

at Volo.Abp.Domain.Repositories.BasicRepositoryBase`1.get_CurrentTenant()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<GetDbSetAsync>d__10.MoveNext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<GetQueryableAsync>d__33.MoveNext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<GetListAsync>d__28.MoveNext()
   at Indo.Customers.CustomerAppService.<GetListAsync>d__22.MoveNext() in D:\Atechdz\BusinessAdvisor\BusinessAdvisor.Sales\src\Indo.Application\Customers\CustomerAppService.cs:line 107


![image](https://github.com/user-attachments/assets/401589bd-8638-4771-8363-3b96ae8c2367)

**Comment by maliming** [comment]
hi

You can share a simple project to reproduce.
