### ISSUE TITLE
Volo.Abp.AbpException: Undefined setting

### ISSUE THREAD

**Issue by hiwjcn** [abpframework/abp#2050]
# environment
.net core mvc 2.2
Mac OS catalina
abp `0.19.0`
visual studio for Mac latest version

# codes

## throw at this line
``` c#
app.UseAbpRequestLocalization();
```

## initialize modules
``` c#
    [DependsOn(typeof(AbpLocalizationModule))]
    public class LangModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            this.Configure<VirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<LangModule>();
            });

            this.Configure<AbpLocalizationOptions>(options =>
            {
                //Define a new localization resource (TestResource)
                options.Languages.Add(new LanguageInfo("en", "en", "English"));
                options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));

                options.Resources
                .Add<AccountLang>(defaultCultureName: "en")
                .AddVirtualJson("/Localization/Account");
//                .AddBaseTypes(typeof(AbpValidationResource));

            });
        }
    }
```

``` c#
    [DependsOn(
        typeof(LangModule),
        typeof(AbpAspNetCoreModule),
        typeof(AbpAspNetCoreMvcModule))]
    public class AdminModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            //
        }

        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            var app = context.GetApplicationBuilder();

            app.UseVirtualFiles();
            /*
            app.ApplicationServices.GetService<ISettingDefinitionManager>()
                .Get(LocalizationSettingNames.DefaultLanguage).DefaultValue= "en";
            app.UseAbpRequestLocalization();*/
//throw at this line
            app.UseAbpRequestLocalization();
        }
    }
```

# stack
```
Unhandled Exception: Volo.Abp.AbpException: Undefined setting: Abp.Localization.DefaultLanguage
   at Volo.Abp.Settings.SettingDefinitionManager.Get(String name) in D:\Github\abp\framework\src\Volo.Abp.Settings\Volo\Abp\Settings\SettingDefinitionManager.cs:line 37
   at Volo.Abp.Settings.SettingProvider.GetOrNullAsync(String name) in D:\Github\abp\framework\src\Volo.Abp.Settings\Volo\Abp\Settings\SettingProvider.cs:line 26
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.UseAbpRequestLocalization(IApplicationBuilder app, Action`1 optionsAction) in D:\Github\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\Builder\AbpApplicationBuilderExtensions.cs:line 56
   at BlueSky.Admin._Startup.AdminModule.OnApplicationInitialization(ApplicationInitializationContext context) in /Users/apple/Documents/code-folder/blue-admin/src/BlueSky.Admin/_Startup/AdminModule.cs:line 34
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleManager.cs:line 39
   at Volo.Abp.AbpApplicationBase.InitializeModules() in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 72
   at BlueSky.Admin._Startup.StartupHelper.__config_abp__(IApplicationBuilder app) in /Users/apple/Documents/code-folder/blue-admin/src/BlueSky.Admin/_Startup/StartupHelper.cs:line 146
   at BlueSky.Admin._Startup.StartupHelper.ConfigApp(IApplicationBuilder app, IConfiguration _config, IHostingEnvironment _env, IApplicationLifetime lifetime) in /Users/apple/Documents/code-folder/blue-admin/src/BlueSky.Admin/_Startup/StartupHelper.cs:line 177
   at BlueSky.Admin.Startup.Configure(IApplicationBuilder app, IApplicationLifetime lifetime) in /Users/apple/Documents/code-folder/blue-admin/src/BlueSky.Admin/Startup.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at BlueSky.Admin.Program.Main(String[] args) in /Users/apple/Documents/code-folder/blue-admin/src/BlueSky.Admin/Program.cs:line 17
The program '[1425] BlueSky.Admin.dll' has exited with code 0 (0x0).
```

**Comment by maliming** [comment]
Please provide a project to reproduce the problem, but the abp framework has been upgraded to version 1.x to support net core 3.0. You should upgrade your application to support net core 3.0.

**Comment by hiwjcn** [comment]
I create a new 2.2 .net core mvc project via visual studio for mac
then install Volo.abp.aspnetcore.mvc
add modules initialize code into startup 
then start project,
same exception shown

do I make any mistake in this demo?

# here is startup.cs
``` c#
using abplang.Localization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Volo.Abp;
using Volo.Abp.AspNetCore;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Localization;
using Volo.Abp.Modularity;
using Volo.Abp.VirtualFileSystem;

namespace abplang
{
    [DependsOn(typeof(AbpLocalizationModule))]
    public class LangModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            this.Configure<VirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<LangModule>();
            });

            this.Configure<AbpLocalizationOptions>(options =>
            {
                //Define a new localization resource (TestResource)
                options.Languages.Add(new LanguageInfo("en", "en", "English"));
                options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));

                options.Resources
                .Add<AccountLang>(defaultCultureName: "en")
                .AddVirtualJson("/Localization/Account");
                //                .AddBaseTypes(typeof(AbpValidationResource));

            });
        }
    }

    [DependsOn(
        typeof(LangModule),
        typeof(AbpAspNetCoreModule),
        typeof(AbpAspNetCoreMvcModule))]
    public class AdminModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            //
        }

        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            var app = context.GetApplicationBuilder();

            app.UseVirtualFiles();
            /*
            app.ApplicationServices.GetService<ISettingDefinitionManager>()
                .Get(LocalizationSettingNames.DefaultLanguage).DefaultValue= "en";
            app.UseAbpRequestLocalization();*/
            app.UseAbpRequestLocalization();
        }
    }
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddApplication<AdminModule>();

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.InitializeApplication();

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

```

**Comment by hiwjcn** [comment]
by the way,
why drop 2.2 support so quickly.
so many developer still work on 2.2 platform

**Comment by maliming** [comment]
Please refer to the template project of the 0.19.0 version.
https://github.com/abpframework/abp/tree/0.19.0/templates/app/aspnet-core

**Comment by hiwjcn** [comment]
I figured out how to fix the mistake,
just replace Microsoft di with Autofac.
------------
now abp framework build iserviceprovider for me.
which break my origin codes.
