### ISSUE TITLE
Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by serkancetintas** [abpframework/abp#2052]
Hello,
I'm using MongoDb integration. I got this error while updating a entity. All parameters are not null.

````csharp
[ERR] Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.TriggerDomainEventsAsync(Object entity)
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass15_0.<Run>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Threading.AsyncHelper.RunSync(Func`1 action)
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.Update(TEntity entity, Boolean autoSave)
   at Castle.Proxies.Invocations.IBasicRepository`1_Update_11.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.Proceed()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.Intercept(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.InterceptSyncMethod(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IBasicRepository`1Proxy_11.Update(Otel entity, Boolean autoSave)
````

**Comment by gdlcf88** [comment]
I am using MongoDb too, it works very well. How can I reproduce your problem?

**Comment by serkancetintas** [comment]
This is my entity.
 
```
public Otel(Guid? id, string title, string content)
        {
            if (id.HasValue)
            {
                Id = id.Value;
            }

            Title = title;
            Content = content;
        }

        public Otel(string title, string content)
        {
            Title = title;
            Content = content;
        }

        public string Title { get; set; }
        public string Content { get; set; }
        public List<Photo> Photos { get; set; }
        public List<Comment> Comments { get; set; }
        public List<Like> Likes { get; set; }
        public List<string> Tags { get; set; }
        public Budget Budget { get; set; }
    }
```

```
 public Guid Update([FromForm]CreateUpdateOtelDto otelDto)
        {
            var otel = _otelRepository.Get(otelDto.Id);

            if (otelDto.Budget != null)
            {
                var budget = new Budget
                {
                    Currency = otelDto.Budget.Currency,
                    Price = otelDto.Budget.Price
                };

                otel.Budget = budget;
            }

            if (otelDto.Tags != null)
            {
                otel.Tags = otelDto.Tags;
            }

            if (otelDto.Photos != null)
            {
                if (otel.Photos == null)
                {
                    otel.Photos = new System.Collections.Generic.List<Photo>();
                }

                ValidateFiles(otelDto.Photos);

                foreach (var photo in otelDto.Photos)
                {
                    if (photo.Length > 0)
                    {
                        var photoDto = _fileUploadService.UploadFile(photo);
                        otel.Photos.Add(new Photo
                        {
                            Name = photo.FileName,
                            FileName = photoDto.FileName,
                            FilePath = photoDto.FilePath
                        });
                    }
                }
            }


            var updatedOtel = _otelRepository.Update(otel);

            return updatedOtel.Id;
        }
```

**Comment by maliming** [comment]
@serkancetintas  
Please provide a project to reproduce the problem. You can create it using the CLI.

**Comment by hikalkan** [comment]
Does your entity inherits from AggregateRoot? If not, you should return a non-null value from GetLocalEvents and GetDistributedEvents methods.
