### ISSUE TITLE
New CLI Create Console Application Error: Sequence contains no matching element

### ISSUE THREAD

**Issue by myesn** [abpframework/abp#20685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://abp.io/docs/latest/get-started/console

abp cli version: 0.7.9

```bash
D:\dev>abp new Acme.MyConsoleApp -t console
[18:59:39 INF] You are running the second generation of the ABP CLI. If you're interested in the legacy CLI, see https://abp.io/new-cli
[18:59:39 INF] Creating your solution...
[18:59:39 INF] Using template: console
System.InvalidOperationException: Sequence contains no matching element
  at void System.Linq.ThrowHelper.ThrowNoMatchException()
  at async ValueTask<bool> Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.TryUseOldCommandAsync(string templateName,
     CommandLineArgs commandLineArgs)
  at async Task Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.ExecuteAsync(CommandLineArgs commandLineArgs)
  at async Task Volo.Abp.Studio.Cli.StudioCliService.RunInternalAsync(CommandLineArgs commandLineArgs)
  at async Task Volo.Abp.Studio.Cli.StudioCliService.RunAsync(string[] args)
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.TryUseOldCommandAsync(String templateName, CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.Commands.NewSolutionCommand.ExecuteAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunInternalAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.Program.m4FALs2Xf(Object  )
   at Volo.Abp.Studio.Cli.Program.<Main>(String[] args)
```

### Version

none

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Please see https://github.com/abpframework/abp/issues/20855#issuecomment-2382461040 and https://github.com/abpframework/abp/issues/20855#issuecomment-2383038054
