### ISSUE TITLE
How to find the theme Lepton layout view source?

### ISSUE THREAD

**Issue by JacksonWork2010** [abpframework/abp#20858]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

Please help me where is find the Lepton layout view(*.cshtml) source code?not LeptonX theme,thanks.

**Comment by aufwies** [comment]
If you are talking about the theme LeptonX lite. You can find it on nuget.

https://www.nuget.org/packages/Volo.Abp.LeptonXLiteTheme.SourceCode

**Comment by JacksonWork2010** [comment]
thanks,but i need Lepton module source code, not LeptonX!


see following commands,:
abp get-source Volo.LeptonTheme

ERROR:
C:\Windows\System32>abp get-source Volo.LeptonTheme
[21:23:58 INF] ABP CLI 0.7.3 (Beta)
[21:23:58 INF] You are running the second generation of the ABP CLI. If you're interested in the legacy CLI, see https://abp.io/new-cli
[21:23:58 WRN] A newer version of the ABP CLI is available: 0.8.2
[21:23:58 WRN] dotnet tool update -g Volo.Abp.Studio.Cli
[21:23:58 INF] Checking extensions...
[21:23:58 INF] Downloading source code of Volo.LeptonTheme (Latest)
[21:23:58 INF] Output folder: C:\Windows\System32
[21:23:58 ERR] Module not found: Volo.LeptonTheme
[21:23:58 WRN] Exception of type 'Volo.Abp.Studio.AbpStudioException' was thrown.
Volo.Abp.Studio.AbpStudioException: Exception of type 'Volo.Abp.Studio.AbpStudioException' was thrown.
   at Volo.Abp.Studio.Modules.Remote.StudioModuleInfoProvider.GetAsync(String name)
   at Volo.Abp.Studio.Cli.Commands.StudioGetSourceCommand.ExecuteAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunInternalAsync(CommandLineArgs commandLineArgs)
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
[21:23:58 WRN] Code:AbpStudio:RemoteModuleNotFound
[21:23:58 WRN] Details:
[21:23:58 WRN] ---------- Exception Data ----------
ModuleName = Volo.LeptonTheme

**Comment by JacksonWork2010** [comment]
@maliming take a look at it？ [](https://abp.io/support/questions/3264/Unable-to-download-source-code-of-VoloLeptonTheme-530)

**Comment by JacksonWork2010** [comment]
[https://abp.io/support/questions/3264/Unable-to-download-source-code-of-VoloLeptonTheme-530](url)

**Comment by EngincanV** [comment]
Hi, if you are using the new ABP Studio CLI, you can run the following command:

```bash
abp get-source Volo.Abp.LeptonTheme
```

![image](https://github.com/user-attachments/assets/dee27a15-9d2d-4522-a2c4-b0948093a5ae)

> Documentation is updated: https://github.com/abpframework/abp/pull/20897

**Comment by JacksonWork2010** [comment]
> Hi, if you are using the new ABP Studio CLI, you can run the following command:
> 
> ```shell
> abp get-source Volo.Abp.LeptonTheme
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43685404/371084741-dee27a15-9d2d-4522-a2c4-b0948093a5ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTg3MjQsIm5iZiI6MTcyNzY1ODQyNCwicGF0aCI6Ii80MzY4NTQwNC8zNzEwODQ3NDEtZGVlMjdhMTUtOWQyZC00NTIyLWEyYzQtYjA5NDgwOTNhNWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAxMDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTUxZjdmMWJmODUwNmE2YzQ0ZjViNjU1MDk1YzcyNDVhMGNkNWYyZmYzMDI1MDkzNTg3YjIyMjdiNzUyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2YZRiaeFqdOr0cCbUM25Ynlpa7JMoin83nqboxTHPzA)
> 
> > Documentation is updated: #20897


I use laster abp studio version，then get follow error，could you please send the attachments（Volo.Abp.LeptonTheme source） to me！thanks！！
![image](https://github.com/user-attachments/assets/4ec8bd7f-9f3f-405c-85d1-ca9ca43e92f9)
