### ISSUE TITLE
I tried to use MySQL database to show that the execution was successful, but I could not create the table

### ISSUE THREAD

**Issue by levin9** [abpframework/abp#2095]
I have some problems when i try to use mysql.
1.I create new projects withABP cli，and  install Volo.Abp.EntityFrameworkCore.MySQL ;
2.Volo.Abp.EntityFrameworkCore.SqlServer has been uninstall
3.modify LionEntityFrameworkCoreModule file;
4.delete DbMigrations file and rebuild the DbMigrations file.
5.run update-database command;

then 
i can get the new database with only __efmigrationshistory table, 

Migrations.file
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);;

**Comment by maliming** [comment]
Please share your modified abp mysql project.

**Comment by levin9** [comment]
after i try it again, Some errors have occurred.（Table 'demo.identityserverapiclaims' doesn't exist）
file ： https://github.com/levin9/AbpDemo

 My operation is as follows：
1. I manually delete the migration file
2. add-migration init；（The regenerated file does not contain a table with the ABP prefix.）
3.update-database



Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='demo' AND TABLE_NAME='__EFMigrationsHistory';
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='demo' AND TABLE_NAME='__EFMigrationsHistory';
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `MigrationId`, `ProductVersion`
FROM `__EFMigrationsHistory`
ORDER BY `MigrationId`;
Applying migration '20191106075355_Init'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `IdentityServerApiClaims` DROP FOREIGN KEY `FK_IdentityServerApiClaims_IdentityServerApiResources_ApiResourceId`;
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `IdentityServerApiClaims` DROP FOREIGN KEY `FK_IdentityServerApiClaims_IdentityServerApiResources_ApiResourceId`;
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'demo.identityserverapiclaims' doesn't exist
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'demo.identityserverapiclaims' doesn't exist
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Table 'demo.identityserverapiclaims' doesn't exist

**Comment by maliming** [comment]
You can remove the existing migration file and then change the database connection string to a new database name, such as demo2. Then add the migration again. This will solve the problem.

The IdentityServer module needs to be configured for mysql.
```
  builder.ConfigureIdentityServer(x => x.DatabaseProvider = EfCoreDatabaseProvider.MySql);
```

**Comment by levin9** [comment]
thanks，
Don't forget that remove all migration classes (including DbContextModelSnapshot)
