### ISSUE TITLE
Error when dispatching 'OnDisconnectedAsync' on hub

### ISSUE THREAD

**Issue by RobinGitHub** [abpframework/abp#21050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

` wpf client
Connection = new HubConnectionBuilder()
    .WithUrl($"http://127.0.0.1:44356/signalr-hubs/online", options =>
    {
        options.AccessTokenProvider = () =>
        {
            return Task.FromResult("Token");
        };
    })
    .WithAutomaticReconnect(new RetryPolicy())
    .Build();

await Connection.StartAsync();

await Connection.StopAsync();
`

when i invoke **await Connection.StopAsync();** show error

---

Request starting HTTP/1.1 GET http://localhost:44356/signalr-hubs/online?id=stN-PJzlmKvXIDYMrV4bZg - null null
[15:57:40 INF] Executing endpoint '/signalr-hubs/online'
[15:57:44 WRN] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.GetAsync(TCacheKey key, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)
[15:57:44 ERR] Error when dispatching 'OnDisconnectedAsync' on hub.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Volo.Abp.Threading.SemaphoreSlimExtensions.LockAsync(SemaphoreSlim semaphoreSlim, CancellationToken cancellationToken)
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)
   at Volo.Abp.Identity.IdentityDynamicClaimsPrincipalContributorCache.GetAsync(Guid userId, Nullable`1 tenantId)
   at Volo.Abp.Identity.IdentityDynamicClaimsPrincipalContributor.ContributeAsync(AbpClaimsPrincipalContributorContext context)
   at Volo.Abp.Security.Claims.AbpClaimsPrincipalFactory.InternalCreateAsync(AbpClaimsPrincipalFactoryOptions options, ClaimsPrincipal existsClaimsPrincipal, Boolean isDynamic)
   at Volo.Abp.Security.Claims.AbpClaimsPrincipalFactory.CreateDynamicAsync(ClaimsPrincipal existsClaimsPrincipal)
   at Volo.Abp.AspNetCore.SignalR.Authentication.AbpAuthenticationHubFilter.HandleDynamicClaimsPrincipalAsync(ClaimsPrincipal claimsPrincipal, IServiceProvider serviceProvider, HubCallerContext hubCallerContext, Boolean skipCheckDynamicClaimssInterval)
   at Volo.Abp.AspNetCore.SignalR.Authentication.AbpAuthenticationHubFilter.OnDisconnectedAsync(HubLifetimeContext context, Exception exception, Func`3 next)
   at Microsoft.AspNetCore.SignalR.Internal.HubFilterFactory.OnDisconnectedAsync(HubLifetimeContext context, Exception exception, Func`3 next)
   at Microsoft.AspNetCore.SignalR.Internal.HubFilterFactory.OnDisconnectedAsync(HubLifetimeContext context, Exception exception, Func`3 next)
   at Microsoft.AspNetCore.SignalR.Internal.HubFilterFactory.OnDisconnectedAsync(HubLifetimeContext context, Exception exception, Func`3 next)
   at Microsoft.AspNetCore.SignalR.Internal.HubFilterFactory.OnDisconnectedAsync(HubLifetimeContext context, Exception exception, Func`3 next)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.ExecuteApplication(ConnectionDelegate connectionDelegate)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully, HttpConnectionStopStatus status)

### Version

8.3.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by RobinGitHub** [comment]
![image](https://github.com/user-attachments/assets/39c56d2a-6811-4b1d-bf97-679645072cd2)

error => claimsPrincipal = await serviceProvider.GetRequiredService<IAbpClaimsPrincipalFactory>()
                .CreateDynamicAsync(claimsPrincipal);

**Comment by 9854626** [comment]
I also encountered the same problem, what is the cause of this?

**Comment by maliming** [comment]
hi

I think the `Connection.StopAsync();` will cancel the request.

I will handle this situation.

**Comment by maliming** [comment]
hi

You can try to remove the `AbpAuthenticationHubFilter` from `HubOptions` and add a new class coming from https://github.com/abpframework/abp/pull/21070

**Comment by RobertoFiocchiMCSI** [comment]
Hi @maliming,  is this a breaking change? 
Could https://github.com/abpframework/abp/issues/15926#issuecomment-1466189029 be helpful?

**Comment by maliming** [comment]
hi @RobertoFiocchiMCSI 
This is not a breaking change.

You can try with https://github.com/abpframework/abp/pull/21070

**Comment by maliming** [comment]
@RobinGitHub @wujb0727 

You can try to remove the AbpAuthenticationHubFilter from HubOptions and add a new class coming from https://github.com/abpframework/abp/pull/21070
