### ISSUE TITLE
Saving permissions exception while creating a new tentant

### ISSUE THREAD

**Issue by nacho-gonzalez** [abpframework/abp#21069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new tenant with ABP 8.3.1 raises an exception related with permission management. 
Logs available in section "Other information".
Screenshots:
![image](https://github.com/user-attachments/assets/e765048b-ffe8-4121-a54f-7fad9bed8f40)
![image](https://github.com/user-attachments/assets/c13294d4-6df8-43cf-a51b-4919c08a622e)

### Reproduction Steps

1. Create a new project layered project with Blazor server and Entity Framework. ABP version 8.3.1.
2. Create a new tenant.
3. After 30 seconds approx. the tenant is created, but the console/log shows an exception: 

> An exception occurred in the database while saving changes for context type 'Volo.Abp.PermissionManagement.EntityFrameworkCore.PermissionManagementDbContext'

### Expected behavior

No exceptions raised and tenant created "immediately"

### Actual behavior

Exception raised after 30 seconds approx.

### Regression?

It worked without issues in previous versions (not sure what is the exact version it started to happen)

### Version

8.3.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

Logs:
```
[23:20:35 DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpTenantManagement.Tenants.Create
[23:20:35 DBG] Found in the cache: pn:R,pk:admin,n:AbpTenantManagement.Tenants.Create
[23:21:08 ERR] Failed executing DbCommand (30,017ms) [Parameters=[@p0='?' (DbType = Guid), @p1='?' (Size = 128), @p2='?' (Size = 64), @p3='?' (Size = 64), @p4='?' (DbType = Guid), @p5='?' (DbType = Guid), @p6='?' (Size = 128), @p7='?' (Size = 64), @p8='?' (Size = 64), @p9='?' (DbType = Guid), @p10='?' (DbType = Guid), @p11='?' (Size = 128), @p12='?' (Size = 64), @p13='?' (Size = 64), @p14='?' (DbType = Guid), @p15='?' (DbType = Guid), @p16='?' (Size = 128), @p17='?' (Size = 64), @p18='?' (Size = 64), @p19='?' (DbType = Guid), @p20='?' (DbType = Guid), @p21='?' (Size = 128), @p22='?' (Size = 64), @p23='?' (Size = 64), @p24='?' (DbType = Guid), @p25='?' (DbType = Guid), @p26='?' (Size = 128), @p27='?' (Size = 64), @p28='?' (Size = 64), @p29='?' (DbType = Guid), @p30='?' (DbType = Guid), @p31='?' (Size = 128), @p32='?' (Size = 64), @p33='?' (Size = 64), @p34='?' (DbType = Guid), @p35='?' (DbType = Guid), @p36='?' (Size = 128), @p37='?' (Size = 64), @p38='?' (Size = 64), @p39='?' (DbType = Guid), @p40='?' (DbType = Guid), @p41='?' (Size = 128), @p42='?' (Size = 64), @p43='?' (Size = 64), @p44='?' (DbType = Guid), @p45='?' (DbType = Guid), @p46='?' (Size = 128), @p47='?' (Size = 64), @p48='?' (Size = 64), @p49='?' (DbType = Guid), @p50='?' (DbType = Guid), @p51='?' (Size = 128), @p52='?' (Size = 64), @p53='?' (Size = 64), @p54='?' (DbType = Guid), @p55='?' (DbType = Guid), @p56='?' (Size = 128), @p57='?' (Size = 64), @p58='?' (Size = 64), @p59='?' (DbType = Guid), @p60='?' (DbType = Guid), @p61='?' (Size = 128), @p62='?' (Size = 64), @p63='?' (Size = 64), @p64='?' (DbType = Guid), @p65='?' (DbType = Guid), @p66='?' (Size = 128), @p67='?' (Size = 64), @p68='?' (Size = 64), @p69='?' (DbType = Guid), @p70='?' (DbType = Guid), @p71='?' (Size = 128), @p72='?' (Size = 64), @p73='?' (Size = 64), @p74='?' (DbType = Guid), @p75='?' (DbType = Guid), @p76='?' (Size = 128), @p77='?' (Size = 64), @p78='?' (Size = 64), @p79='?' (DbType = Guid), @p80='?' (DbType = Guid), @p81='?' (Size = 128), @p82='?' (Size = 64), @p83='?' (Size = 64), @p84='?' (DbType = Guid), @p85='?' (DbType = Guid), @p86='?' (Size = 128), @p87='?' (Size = 64), @p88='?' (Size = 64), @p89='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
SET IMPLICIT_TRANSACTIONS OFF;
SET NOCOUNT ON;
INSERT INTO [AbpPermissionGrants] ([Id], [Name], [ProviderKey], [ProviderName], [TenantId])
VALUES (@p0, @p1, @p2, @p3, @p4),
(@p5, @p6, @p7, @p8, @p9),
(@p10, @p11, @p12, @p13, @p14),
(@p15, @p16, @p17, @p18, @p19),
(@p20, @p21, @p22, @p23, @p24),
(@p25, @p26, @p27, @p28, @p29),
(@p30, @p31, @p32, @p33, @p34),
(@p35, @p36, @p37, @p38, @p39),
(@p40, @p41, @p42, @p43, @p44),
(@p45, @p46, @p47, @p48, @p49),
(@p50, @p51, @p52, @p53, @p54),
(@p55, @p56, @p57, @p58, @p59),
(@p60, @p61, @p62, @p63, @p64),
(@p65, @p66, @p67, @p68, @p69),
(@p70, @p71, @p72, @p73, @p74),
(@p75, @p76, @p77, @p78, @p79),
(@p80, @p81, @p82, @p83, @p84),
(@p85, @p86, @p87, @p88, @p89);
[23:21:08 ERR] An exception occurred in the database while saving changes for context type 'Volo.Abp.PermissionManagement.EntityFrameworkCore.PermissionManagementDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9c221888-0ee2-45f6-8abc-48ada09c96e0
Error Number:-2,State:0,Class:11
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9c221888-0ee2-45f6-8abc-48ada09c96e0
Error Number:-2,State:0,Class:11
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.SaveChangesAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Driven2u.Auth.Data.AuthTenantDatabaseMigrationHandler.MigrateAndSeedForTenantAsync(Guid tenantId, String adminEmail, String adminPassword) in C:\Users\Nacho\Source\Repos\driven2u\test\Driven2u.Auth\src\Driven2u.Auth.Domain\Data\AuthTenantDatabaseMigrationHandler.cs:line 121
[23:21:08 ERR] An error occurred while saving the entity changes. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:9c221888-0ee2-45f6-8abc-48ada09c96e0
Error Number:-2,State:0,Class:11
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.SaveChangesAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Driven2u.Auth.Data.AuthTenantDatabaseMigrationHandler.MigrateAndSeedForTenantAsync(Guid tenantId, String adminEmail, String adminPassword) in C:\Users\Nacho\Source\Repos\driven2u\test\Driven2u.Auth\src\Driven2u.Auth.Domain\Data\AuthTenantDatabaseMigrationHandler.cs:line 121
[23:21:08 DBG] Remove dynamic claims cache for user: 5523d86b-58fa-2a80-1fe4-3a1599ee0141
[23:21:08 DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:70020be4-1784-944c-cb61-3a158fbb7f3c,n:AbpTenantManagement.Tenants
[23:21:08 DBG] Found in the cache: pn:U,pk:70020be4-1784-944c-cb61-3a158fbb7f3c,n:AbpTenantManagement.Tenants
[23:21:08 DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpTenantManagement.Tenants
[23:21:08 DBG] Found in the cache: pn:R,pk:admin,n:AbpTenantManagement.Tenants
[23:21:08 DBG] Get dynamic claims cache for user: 70020be4-1784-944c-cb61-3a158fbb7f3c
[23:21:08 DBG] PermissionStore.GetCacheItemAsync: pn:U,pk:70020be4-1784-944c-cb61-3a158fbb7f3c,n:AbpTenantManagement.Tenants.Create
[23:21:08 DBG] Found in the cache: pn:U,pk:70020be4-1784-944c-cb61-3a158fbb7f3c,n:AbpTenantManagement.Tenants.Create
[23:21:08 DBG] PermissionStore.GetCacheItemAsync: pn:R,pk:admin,n:AbpTenantManagement.Tenants.Create
[23:21:08 DBG] Found in the cache: pn:R,pk:admin,n:AbpTenantManagement.Tenants.Create
[23:21:09 INF] Request starting HTTP/2 GET https://localhost:44397/_content/Blazorise/dropdown.js?v=1.5.2.0 - null null
[23:21:09 INF] Sending file. Request path: '/_content/Blazorise/dropdown.js'. Physical path: 'C:\Users\Nacho\.nuget\packages\blazorise\1.5.2\staticwebassets\dropdown.js'
[23:21:09 INF] Request finished HTTP/2 GET https://localhost:44397/_content/Blazorise/dropdown.js?v=1.5.2.0 - 200 1372 application/javascript 7.1832ms
[23:21:09 INF] Request starting HTTP/2 GET https://localhost:44397/_content/Blazorise/floatingUi.js?v=1.5.2.0 - null null
[23:21:09 INF] Sending file. Request path: '/_content/Blazorise/floatingUi.js'. Physical path: 'C:\Users\Nacho\.nuget\packages\blazorise\1.5.2\staticwebassets\floatingUi.js'
[23:21:09 INF] Request finished HTTP/2 GET https://localhost:44397/_content/Blazorise/floatingUi.js?v=1.5.2.0 - 200 1681 application/javascript 5.9756ms
[23:21:09 INF] Request starting HTTP/2 GET https://localhost:44397/_content/Blazorise/vendors/floating-ui.js?v=1.5.2.0 - null null
[23:21:09 INF] Sending file. Request path: '/_content/Blazorise/vendors/floating-ui.js'. Physical path: 'C:\Users\Nacho\.nuget\packages\blazorise\1.5.2\staticwebassets\vendors\floating-ui.js'
[23:21:09 INF] Request finished HTTP/2 GET https://localhost:44397/_content/Blazorise/vendors/floating-ui.js?v=1.5.2.0 - 200 10628 application/javascript 7.5915ms
[23:21:09 INF] Request starting HTTP/2 GET https://localhost:44397/_content/Blazorise/vendors/floating-ui-core.js - null null
[23:21:09 INF] Sending file. Request path: '/_content/Blazorise/vendors/floating-ui-core.js'. Physical path: 'C:\Users\Nacho\.nuget\packages\blazorise\1.5.2\staticwebassets\vendors\floating-ui-core.js'
[23:21:09 INF] Request finished HTTP/2 GET https://localhost:44397/_content/Blazorise/vendors/floating-ui-core.js - 200 15103 application/javascript 6.913ms
[23:21:14 DBG] Get dynamic claims cache for user: 70020be4-1784-944c-cb61-3a158fbb7f3c
[23:27:13 DBG] Get dynamic claims cache for user: 70020be4-1784-944c-cb61-3a158fbb7f3c
```

**Comment by maliming** [comment]
hi

Can you share your test project?

**Comment by nacho-gonzalez** [comment]
> hi
> 
> Can you share your test project?

Sure! here you have it: https://github.com/nacho-gonzalez/test

**Comment by maliming** [comment]
hi @nacho-gonzalez 

Try to remove the `IDistributedEventHandler<TenantCreatedEto>`


![image](https://github.com/user-attachments/assets/6e0f4221-1eba-47b7-8aeb-1c126ad468df)

**Comment by nacho-gonzalez** [comment]
Hi @maliming I worked. Thank you!

I could not find that DatabaseMigrationHanlder in the 8.3.1 templates and I have not created them. Maybe it's using another source for the templates or I am not searching in the right place:
![image](https://github.com/user-attachments/assets/ecb3a062-c8b1-4a9e-9f24-6dad8385b2c5)
