### ISSUE TITLE
ClientIpAddress must be a string or array type with a maximum length of '64'

### ISSUE THREAD

**Issue by linguation** [abpframework/abp#21093]
During Login, some users started to get this error lately: The field ClientIpAddress must be a string or array type with a maximum length of '64'.

SaveLoginAttempt seems to create the issue. A ClientIpAddress which causes the issue is as below, which is longer then 64: 
2a02:586:b903:6f59:15fb:ac99:4877:3e8d,2a02:586:b903:6f59:15fb:ac99:4877:3e8d

However the question is, why did this not happen before? And how can I fix that? I cant seem to change the [MaxLength(64)] for ClientIpAddress.

**Comment by maliming** [comment]
hi

- Your ABP Framework version.
- Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI
- Your database provider(EF Core/MongoDB)
- Exception message and stack trace if available (check the logs).
- Please share the steps and code to reproduce the problem.

**Comment by linguation** [comment]
- v4.0.30319
- AngularJs
- EF Core
- Login page at https://.../Account/Login. User fills email and password, clicks login, gets the error mentioned.
- SaveLoginAttempt throws DbEntityValidationException: **A ClientIpAddress which causes the issue is as below, which is longer then 64.**

Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
STACK TRACE: at x.Web.Controllers.AccountController.<GetLoginResultAsync>d__21.MoveNext() in C:\x.Web\Controllers\AccountController.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at x.Web.Controllers.AccountController.<Login>d__20.MoveNext() in C:\x.Web\Controllers\AccountController.cs:line 132
 --- End of stack trace from previous location where exception was thrown ---  
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__11_0()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__3()
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult)

The ClientInfoProvider.ClientIpAddress returns the same IP address twice, with a comma in between like here:
2a02:586:b903:6f59:15fb:ac99:4877:3e8d,2a02:586:b903:6f59:15fb:ac99:4877:3e8d

and this causes the issue. Should it not just be one ip address?

**Comment by linguation** [comment]
I will simply update the whole solution: https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6863

**Comment by maliming** [comment]
hi @linguation 

Are you using a reverse proxy? if so, you can configure `Forwarded headers`.

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0

https://abp.io/support/questions/1950/How-to-use-a-custom-HTTP-header-to-get-the-client-remote-IP-address
