### ISSUE TITLE
Castle.Proxies.SchemeAppServiceProxy Exception

### ISSUE THREAD

**Issue by Keertesh** [abpframework/abp#21190]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests, and other discussions about the framework.

If you're creating a bug/problem report, please include the followings:

* **ABP 7.3.1**.
* **Angular**
* Database EF Core
* Exception message and **stack trace** `{
  "code": null,
  "message": "An exception was thrown while activating Castle.Proxies.SchemeAppServiceProxy -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null]].",
  "details": "DependencyResolutionException: An exception was thrown while activating Castle.Proxies.SchemeAppServiceProxy -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null]].\r\nSTACK TRACE:    at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)\r\n   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\nDependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Volo.Abp.BlobStoring.IBlobContainerFactory)' on type 'BlobContainer`1'.\r\nSTACK TRACE:    at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass12_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\nAbpException: No BLOB Storage provider was used! At least one provider must be configured to be able to use the BLOB Storing System.\r\nSTACK TRACE:    at Volo.Abp.BlobStoring.DefaultBlobProviderSelector.Get(String containerName)\r\n   at Volo.Abp.BlobStoring.BlobContainerFactory.Create(String name)\r\n   at lambda_method5461(Closure , Object[] )\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n",
  "data": null,
  "validationErrors": null
}

2024-10-25 14:08:32.933 +05:30 [ERR] An exception was thrown while activating Castle.Proxies.SchemeAppServiceProxy -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null]].
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.SchemeAppServiceProxy -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null]].
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Volo.Abp.BlobStoring.IBlobContainerFactory)' on type 'BlobContainer`1'.
 ---> Volo.Abp.AbpException: No BLOB Storage provider was used! At least one provider must be configured to be able to use the BLOB Storing System.
   at Volo.Abp.BlobStoring.DefaultBlobProviderSelector.Get(String containerName)
   at Volo.Abp.BlobStoring.BlobContainerFactory.Create(String name)
   at lambda_method5461(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass12_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-10-25 14:08:32.933 +05:30 [ERR] ---------- Exception Data ----------
ActivatorChain = Castle.Proxies.SchemeAppServiceProxy -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null]]

2024-10-25 14:08:32.933 +05:30 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2024-10-25 14:08:32.933 +05:30 [INF] Executed action abcd.xyz.Schemes.SchemeAppService.CreateAsync (abcd.xyz.Application) in 3.0748ms
2024-10-25 14:08:32.933 +05:30 [INF] Executed endpoint 'abcd.xyz.Schemes.SchemeAppService.CreateAsync (abcd.xyz.Application)'`

**Comment by Keertesh** [comment]
@maliming
