### ISSUE TITLE
Could not find file '/Pages/Books/Index.js' in docker container

### ISSUE THREAD

**Issue by ddzsy** [abpframework/abp#21295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can't find the index.js file，while in the container's app folder, the file exists in the rgiht path: Pages/Books/index.js
I build an image and run it in docker-desktop container, login successfully,but failed on click the [Books] menu.
> 2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/Books - null null
2024-11-07 14:33:07 [06:33:07 INF] Executing endpoint '/Books/Index'
2024-11-07 14:33:07 [06:33:07 INF] Route matched with {page = "/Books/Index", area = "", action = "", controller = ""}. Executing page /Books/Index
2024-11-07 14:33:07 [06:33:07 INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2024-11-07 14:33:07 [06:33:07 INF] Executing handler method Sanbuy.Pages.Books.IndexModel.OnGet - ModelState is Valid
2024-11-07 14:33:07 [06:33:07 INF] Executed handler method OnGet, returned result .
2024-11-07 14:33:07 [06:33:07 INF] Executing an implicit handler method - ModelState is Valid
2024-11-07 14:33:07 [06:33:07 INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2024-11-07 14:33:07 [06:33:07 INF] Bundling __bundles/Pages.Books.Index.8F288EDDBB7D4D90CA331110358E7363.js (1 files)
2024-11-07 14:33:07 [06:33:07 INF] Executed page /Books/Index in 6.6228ms
2024-11-07 14:33:07 [06:33:07 INF] Executed endpoint '/Books/Index'
2024-11-07 14:33:07 [06:33:07 ERR] An unhandled exception has occurred while executing the request.
2024-11-07 14:33:07 Volo.Abp.AbpException: Could not find file '/Pages/Books/Index.js'
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetFileInfo(IBundlerContext context, String file)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetAndMinifyFileContent(IBundlerContext context, String fileName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetFileContentConsideringMinification(IBundlerContext context, String fileName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.AddFileToBundle(IBundlerContext context, StringBuilder bundleContentBuilder, String fileName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.Bundle(IBundlerContext context)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.<>c__DisplayClass17_0.<AddToBundleCache>b__0()
2024-11-07 14:33:07    at System.Collections.Generic.AbpDictionaryExtensions.<>c__DisplayClass7_0`2.<GetOrAdd>b__0(TKey k)
2024-11-07 14:33:07    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleCache.GetOrAdd(String bundleName, Func`1 factory)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.AddToBundleCache(String bundleName, IBundler bundler, List`1 bundleFiles)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetBundleFilesAsync(BundleConfigurationCollection bundles, String bundleName, IBundler bundler)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetScriptBundleFilesAsync(String bundleName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperScriptService.GetBundleFilesAsync(String bundleName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleItemTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
2024-11-07 14:33:07    at AspNetCoreGeneratedDocument.Pages_Books_Index.<ExecuteAsync>b__20_0()
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSectionAsyncCore(String sectionName, Boolean required)
2024-11-07 14:33:07    at AspNetCoreGeneratedDocument.Themes_LeptonXLite_Layouts_Application.<>c__DisplayClass18_0.<<ExecuteAsync>b__1>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
2024-11-07 14:33:07    at AspNetCoreGeneratedDocument.Themes_LeptonXLite_Layouts_Application.ExecuteAsync()
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2024-11-07 14:33:07    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Security.Claims.AbpDynamicClaimsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpOpenIddictMiddlewareExtension.<>c__DisplayClass0_0.<<UseAbpOpenIddictValidation>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Security.AbpSecurityHeadersMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.Studio.Client.AspNetCore.AbpStudioMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Volo.Abp.Studio.Client.AspNetCore.AbpStudioMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2024-11-07 14:33:07    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
2024-11-07 14:33:07 --- End of stack trace from previous location ---
2024-11-07 14:33:07    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-11-07 14:33:07 [06:33:07 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2024-11-07 14:33:07 [06:33:07 INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
2024-11-07 14:33:07 [06:33:07 INF] Executing ViewResult, running view ~/Views/Error/Default.cshtml.
2024-11-07 14:33:07 [06:33:07 INF] Executed ViewResult - view ~/Views/Error/Default.cshtml executed in 3.4803ms.
2024-11-07 14:33:07 [06:33:07 INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 4.3ms
2024-11-07 14:33:07 [06:33:07 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/Books - 500 null text/html; charset=utf-8 42.4801ms
2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/__bundles/LeptonXLite.Global.990E1D9D56F35BC96DF720644CF93F6F.css?_v=638665579586476611 - null null
2024-11-07 14:33:07 [06:33:07 INF] The file /__bundles/LeptonXLite.Global.990E1D9D56F35BC96DF720644CF93F6F.css was not modified
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/__bundles/LeptonXLite.Global.990E1D9D56F35BC96DF720644CF93F6F.css?_v=638665579586476611 - 304 null text/css 0.3816ms
2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/Abp/ApplicationConfigurationScript - null null
2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/__bundles/LeptonXLite.Global.993DF265FB5BB6C0144C890B27487FAF.js?_v=638665579590183815 - null null
2024-11-07 14:33:07 [06:33:07 INF] The file /__bundles/LeptonXLite.Global.993DF265FB5BB6C0144C890B27487FAF.js was not modified
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/__bundles/LeptonXLite.Global.993DF265FB5BB6C0144C890B27487FAF.js?_v=638665579590183815 - 304 null application/javascript 0.355ms
2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/Abp/ApplicationLocalizationScript?cultureName=zh-Hans - null null
2024-11-07 14:33:07 [06:33:07 INF] Request starting HTTP/1.1 GET http://localhost:44301/Abp/ServiceProxyScript - null null
2024-11-07 14:33:07 [06:33:07 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Route matched with {area = "Abp", action = "Get", controller = "AbpApplicationConfigurationScript", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController (Volo.Abp.AspNetCore.Mvc).
2024-11-07 14:33:07 [06:33:07 INF] Route matched with {area = "Abp", action = "GetAll", controller = "AbpServiceProxyScript", page = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult GetAll(Volo.Abp.AspNetCore.Mvc.ProxyScripting.ServiceProxyGenerationModel) on controller Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController (Volo.Abp.AspNetCore.Mvc).
2024-11-07 14:33:07 [06:33:07 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.Localization.AbpApplicationLocalizationScriptController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Route matched with {area = "Abp", action = "Get", controller = "AbpApplicationLocalizationScript", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] GetAsync(Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationLocalizationRequestDto) on controller Volo.Abp.AspNetCore.Mvc.Localization.AbpApplicationLocalizationScriptController (Volo.Abp.AspNetCore.Mvc).
2024-11-07 14:33:07 [06:33:07 INF] Executing ContentResult with HTTP Response ContentType of application/javascript
2024-11-07 14:33:07 [06:33:07 INF] Executed action Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc) in 0.9719ms
2024-11-07 14:33:07 [06:33:07 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/Abp/ServiceProxyScript - 200 1009 application/javascript 3.8758ms
2024-11-07 14:33:07 [06:33:07 INF] Executing ContentResult with HTTP Response ContentType of application/javascript
2024-11-07 14:33:07 [06:33:07 INF] Executed action Volo.Abp.AspNetCore.Mvc.Localization.AbpApplicationLocalizationScriptController.GetAsync (Volo.Abp.AspNetCore.Mvc) in 2.7624ms
2024-11-07 14:33:07 [06:33:07 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.Localization.AbpApplicationLocalizationScriptController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/Abp/ApplicationLocalizationScript?cultureName=zh-Hans - 200 30737 application/javascript 6.5469ms
2024-11-07 14:33:07 [06:33:07 WRN] The cookie 'XSRF-TOKEN' has set 'SameSite=None' and must also set 'Secure'.
2024-11-07 14:33:07 [06:33:07 INF] Executing ContentResult with HTTP Response ContentType of application/javascript
2024-11-07 14:33:07 [06:33:07 INF] Executed action Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc) in 5.0683ms
2024-11-07 14:33:07 [06:33:07 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc)'
2024-11-07 14:33:07 [06:33:07 INF] Request finished HTTP/1.1 GET http://localhost:44301/Abp/ApplicationConfigurationScript - 200 5656 application/javascript 8.5464ms

### Version

8.3.3

### User Interface

MVC

### Database Provider

None/Others

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please share the csproj file of your web project.

See the sample project.

https://github.com/abpframework/abp-samples/blob/master/BookStore-Mvc-EfCore/src/Acme.BookStore.Web/Acme.BookStore.Web.csproj#L28-L35

**Comment by JoelLeach** [comment]
To anyone else running into this, it is a case-sensitivity issue in the Books sample when running on Linux (including containers).  Index.cshtml references `<abp-script src="/Pages/Books/Index.js" />` but the filename is `index.js` (lower-case) on disk.  Make the case match in either place to resolve.
