### ISSUE TITLE
Single Page Application Angular & .NET Core project run X-XSRF-TOKEN Issue 

### ISSUE THREAD

**Issue by mchauhan-phyrem** [abpframework/abp#21335]
### GitHub Issues

GitHub issues are for bug reports, feature requests, and other discussions about the framework.

If you're creating a bug/problem report, please include the followings:

* Your **ABP Framework version**. 9.1.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
    Angular
* Your database provider(EF Core/MongoDB)
* EF Core

* Steps needed to **reproduce** the problem.

Angular & .Net core project run in same website URL
domain../Ui/Login used as Back end Swagger 
domain../Account/Login angular project 

When I login into  /Ui/Login & then in new tab I try to login frontend ui /Account/Login  getting error related [X-XSRF-TOKEN]

my end goal is it should run both at same time without any conflict Cookie & token issue.

**Comment by mchauhan-phyrem** [comment]
@ismcagdas For single page application .net core & angular run in same URL is it possible to differentiated  X-XSRF-TOKEN
from ?
![Back-End-Login](https://github.com/user-attachments/assets/e98d5099-19db-4d0a-a737-842742c5280c)
![Front-End_login](https://github.com/user-attachments/assets/393b1f6b-aa21-4bc4-a7c5-cea42e4182bc)


if we login into same browser into back-end login then that token is not create CreateJwtClaims Token but is browser side 
it cookies
![image](https://github.com/user-attachments/assets/5efb123a-f251-4812-b9d3-4ca90cc1b659)

after that I refresh my account/login page it's some api work fine and some not and raise error like this
**The required antiforgery header value "X-XSRF-TOKEN" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "X-XSRF-TOKEN" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Abp.AspNetCore.Mvc.Antiforgery.AbpValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
ERROR 2024-11-15 14:54:26,733 [orker] idateAntiforgeryTokenAuthorizationFilter - The required antiforgery header value "X-XSRF-TOKEN" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "X-XSRF-TOKEN" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Abp.AspNetCore.Mvc.Antiforgery.AbpValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)**
