### ISSUE TITLE
 The latest version of ABP is not user-friendly and reports an error

### ISSUE THREAD

**Issue by shilme** [abpframework/abp#21502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

error info ：An exception was thrown while activating Volo.Abp.FeatureManagement.EntityFrameworkCore.FeatureManagementDbContext.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.FeatureManagement.EntityFrameworkCore.FeatureManagementDbContext.
---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions1[Volo.Abp.FeatureManagement.EntityFrameworkCore.FeatureManagementDbContext])' on type 'FeatureManagementDbContext'.  ---> System.TypeLoadException: Method 'get_LockReleaseBehavior' in type 'Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlHistoryRepository' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=9.0.0.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.    at Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)    at Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension.ApplyServices(IServiceCollection services)    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple2 arguments)
at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple2 tuples)    at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd[TArg](TKey key, Func3 valueFactory, TArg factoryArgument)    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)    at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)    at lambda_method1062(Closure, Object[])    at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()    --- End of inner exception stack trace ---    at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()    at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action1 next)
at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action1 next)    at Autofac.Builder.RegistrationBuilder3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext context, Action1 next)    at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action1 next)
--- End of inner exception stack trace ---
at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action1 next)    at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action1 next)
at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action1 next)    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)    at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)    at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider1.CreateDbContextWithTransactionAsync(IUnitOfWork unitOfWork)
at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider1.CreateDbContextAsync(IUnitOfWork unitOfWork)    at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider1.CreateDbContextAsync(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider1.GetDbContextAsync()    at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository2.GetDbSetAsync()
at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository2.GetQueryableAsync()    at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository2.GetListAsync(Boolean includeDetails, CancellationToken cancellationToken)
at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue1.ProceedAsync()    at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func3 proceed)    at Volo.Abp.FeatureManagement.StaticFeatureSaver.UpdateChangedFeatureGroupsAsync(IEnumerable1 featureGroupRecords)
at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
at Volo.Abp.FeatureManagement.StaticFeatureSaver.SaveAsync()
at Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule.<>c__DisplayClass8_0.<<SaveStaticFeaturesToDatabaseAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.AsyncPolicy.<>c__DisplayClass44_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func3 action, Context context, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates1 shouldRetryResultPredicates, Func5 onRetryAsync, CancellationToken cancellationToken, Int32 permittedRetryCount, IEnumerable1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext) 

How to resolve this error message?
My analysis is that the above problem
Version incompatibility:
The Pomelo you are using The version of Entity Framework Core. MySQL may not be compatible with other dependencies such as Entity Framework Core or Volo. Abp. The version of Pomelo. Entity Framework Core. MySQL 9. x seems to have issues with incomplete implementation of certain methods, particularly the get_LockRelease Behavior method.
Upgrade or downgrade package:
If you have recently upgraded Pomelo The version of Entity Framework Core. MySQL may cause this issue. Try to use Pomelo The Entity Framework Core. MySQL is downgraded to an earlier stable version (such as 5. x or 6. x), which is typically compatible with Entity Framework Core and ABP frameworks.
Package version lock:
It may be necessary to check the version of the VNet package used in the project to ensure that all related dependency packages are compatible with each other. especially:
Pomelo.EntityFrameworkCore.MySql
Microsoft.EntityFrameworkCore
Volo.Abp.BackgroundJobs.EntityFrameworkCore
It's just that the package is incompatible

### Reproduction Steps

1

### Version

9.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

none

**Comment by EngincanV** [comment]
Hi, this is a known issue and related to the `Pomelo.EntityFrameworkCore.MySql` package version _9.0.0-preview.1_ and we already updated the related package, and it will be available with v9.0.3. Until v9.0.3 is released, you can manually override this package version in your *.EntityFrameworkCore project:

```xml
<PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.2.efcore.9.0.0" />
```
