### ISSUE TITLE
CLI broken again, cannot use abp new command

### ISSUE THREAD

**Issue by jricks-minolusa** [abpframework/abp#2154]
Appears to be related to #2049 and #1779 

This issue appears to still exist, albeit getting a slightly different error message now:

```
abp new Acme.BookStore 
[16:36:48 INF] ABP CLI (https://abp.io)
[16:36:48 INF] Version 1.0.2 (Stable channel)
[16:36:48 WRN] Unable to retrieve the latest version
[16:36:48 WRN] Object reference not set to an instance of an object.
[16:36:48 INF] Creating your project...
[16:36:48 INF] Project name: Acme.BookStore
[16:36:48 INF] Output folder: C:\Dev\FromAbel\abp
[16:36:48 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 91
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55
```

Is there anything we as community contributors can do to prevent this issue from occuring? Considering that the issue is related to an API call being made to the abp.io website, I'm wondering if we could modify the command to pull the latest release from GitHub instead of depending on the website. I'm sure that the re-occurence of this kind of issue is an annoyance and pulls development time away from the project itself.

I will explore this route in the meantime but I wanted to bring this issue to your attention. Please let me know if you need any additional information to diagnose and resolve the issue. Thanks!

**Comment by maliming** [comment]
You can try a few more times or download a new project from abp.io.
