### ISSUE TITLE
Angular 8.0.2 to 9.0.2

### ISSUE THREAD

**Issue by gvassao** [abpframework/abp#21693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to update angular 8.0.2 packages to 9.0.2 with abp cli fails with error message:

```
PS > abp update
[00:35:33 INF] You are running the second generation of the ABP CLI. If you're interested in the legacy CLI, see https://abp.io/new-cli
Unhandled exception. System.InvalidOperationException: Could not find color or style 'options'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 29
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117
   at Spectre.Console.AnsiConsole.MarkupLine(String value) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 81
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.Program.W13UKfInd(Object  )
   at Volo.Abp.Studio.Cli.Program.<Main>(String[] args)
```

Should I just update all the packages manually in the package,json? Is that all that's needed?

### Reproduction Steps

Run abp update on a abp 8.0.2 that is using Angular UI

### Expected behavior

Application is updated sucessfully

### Actual behavior

Throws an error:

```
PS > abp update
[00:35:33 INF] You are running the second generation of the ABP CLI. If you're interested in the legacy CLI, see https://abp.io/new-cli
Unhandled exception. System.InvalidOperationException: Could not find color or style 'options'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 29
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117
   at Spectre.Console.AnsiConsole.MarkupLine(String value) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 81
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.StudioCliService.RunAsync(String[] args)
   at Volo.Abp.Studio.Cli.Program.W13UKfInd(Object  )
   at Volo.Abp.Studio.Cli.Program.<Main>(String[] args)
```

### Version

8.0.2 to 9.0.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
> Should I just update all the packages manually in the package,json? Is that all that's needed?

Normally, you don't need to do this. ABP CLI should update all package versions to v9.0.2. In fact, when I tried it just now, it successfully updated my project packages to v9.0.4:

![Image](https://github.com/user-attachments/assets/f5098503-b54f-43a7-9532-d89263d232f1)

What is your ABP Studio CLI version?

**Comment by gvassao** [comment]
At the time I wrote this post it was the latest. I have had to update since then and haven't seen the error again. Maybe it was because I was coming from ABP 8 or something 🤷‍♂
