### ISSUE TITLE
Abp 4.10.1 project published and deploy on windows server 2012 r2,run error!

### ISSUE THREAD

**Issue by XbCore** [abpframework/abp#2179]
I deploy my abp project(refer to: [aspnetboilerplate/modular-todo-app](https://github.com/aspnetboilerplate/modular-todo-app)) on Windows Server 2012 R2.
It can run normally on my development environment (Win10 with VS2019), but when I deploy on Windows Server 2012 R2, it run into error, the logs are as follows:
```
ERROR 2019-11-15 15:56:03,750 [14   ] e.Diagnostics.ExceptionHandlerMiddleware - An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
wearhmf1.51l(4,55): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
wearhmf1.51l(5,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
wearhmf1.51l(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
wearhmf1.51l(4,123): error CS0518: Predefined type 'System.String' is not defined or imported
wearhmf1.51l(4,140): error CS0518: Predefined type 'System.String' is not defined or imported
wearhmf1.51l(4,12): error CS0518: Predefined type 'System.Void' is not defined or imported
wearhmf1.51l(5,81): error CS0518: Predefined type 'System.String' is not defined or imported
wearhmf1.51l(5,113): error CS0518: Predefined type 'System.Type' is not defined or imported
......
/Views/Account/Login.cshtml(24,14): error CS0518: Predefined type 'System.String' is not defined or imported
/Views/Account/Login.cshtml(24,25): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
/Views/Account/Login.cshtml(24,25): error CS0518: Predefined type 'System.Object' is not defined or imported
/Views/Account/Login.cshtml(24,27): error CS0518: Predefined type 'System.String' is not defined or imported
/Views/Account/Login.cshtml(24,25): error CS0518: Predefined type 'System.String' is not defined or imported
/Views/Account/Login.cshtml(72,49): error CS0518: Predefined type 'System.Void' is not defined or imported
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at XbCore.Base.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext() in E:\XbTeck\XbCore.Adp\ASP.NET Boilerplate\XbCore.Adp\src\Modules\Base\XbCore.Base.Web.Core\Authentication\JwtBearer\JwtTokenMiddleware.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

And the Browser display:
```
An error occurred while processing your request.

Request ID: 0HLR9KHFMP8HI:00000002 

Development Mode

Swapping to Development environment will display more detailed information about the error that occurred. 

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application. 
```

What's wrong? Anyone can help me?

**Comment by maliming** [comment]
Maybe related to this(https://github.com/aspnet/Mvc/issues/7910#issuecomment-397360780).
I suggest you use the latest 2.x version.

**Comment by XbCore** [comment]
@maliming Thank you very much.
With your suggestion, I have successfully solved the problem. 
The steps are as follows:
1. Change the Modular project csproj file's Sdk to 'Microsoft.NET.Sdk.Razor' which contain *.cshtml files;
2. Remove the follow content from the same csproj file:
```
<ItemGroup>
    <EmbeddedResource Include="Views\**\*.*" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
```
3. Add the follow content to the same csproj file, to support *.css/*.js files:
<ItemGroup>
```
    <EmbeddedResource Include="Views\**\*.css;Views\**\*.js" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
```
