### ISSUE TITLE
NullReferenceException on IdentityDbContext.SaveChangesAsync/Insert

### ISSUE THREAD

**Issue by EpsilonRepo** [abpframework/abp#2182]
Hi,

I'm trying to use the Oracle EF Core provider from Devart and I get NullReferenceExceptions when inserting data. Reading works well.

I get this error when inserting seed data from the dbMigrator project (same problem when trying to register a new user on the identity server).

The Problem seem to be related to the type mapping of the Id Property to an OracleCursor.
Here is the stack trace, maybe you can help me out.

Thank you

---

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.OnAnnotationSet(String name, IConventionAnnotation annotation, IConventionAnnotation oldAnnotation) in /_/src/EFCore/Metadata/Internal/Property.cs:line 564
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ConventionAnnotatable.OnAnnotationSet(String name, Annotation annotation, Annotation oldAnnotation) in /_/src/EFCore/Metadata/Internal/ConventionAnnotatable.cs:line 69
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.SetAnnotation(String name, Annotation annotation, Annotation oldAnnotation) in /_/src/EFCore/Infrastructure/Annotatable.cs:line 104
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.AddAnnotation(String name, Annotation annotation) in /_/src/EFCore/Infrastructure/Annotatable.cs:line 61
   at Microsoft.EntityFrameworkCore.Infrastructure.Annotatable.AddAnnotation(String name, Object value) in /_/src/EFCore/Infrastructure/Annotatable.cs:line 45
   at Devart.Data.Oracle.Entity.ai..ctor(IPropertyBase A_0)
   at Devart.Data.Oracle.Entity.ag.a(StringBuilder A_0, ModificationCommand A_1, String A_2, w A_3)
   at Devart.Data.Oracle.Entity.ag.AppendInsertOperation(StringBuilder commandText, ModificationCommand command, Int32 commandPosition)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.UpdateCachedCommandText(Int32 commandPosition) in /_/src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs:line 157
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.GetCommandText() in /_/src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs:line 139
   at Devart.Common.Entity.cp.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext() in /_/src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs:line 271
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext() in /_/src/EFCore.Relational/Update/Internal/BatchExecutor.cs:line 155
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by EpsilonRepo** [comment]
Hi,

Starting from the template, I added referenced to the devart libraries in the EntityFrameworkCore project.
After that I needed to replace the varchar(max) properties with nclob type because the generated Oracle script needs a max length for nvarchar columns.

Then I ran the DbMigrator project
Tables are created without errors.
Reading from the tables seems to work.

DbMigrator the fails inserting initial seed.
I also tried the /api/account/register endpoint and get the same error.

**Comment by maliming** [comment]
Can you share a project that reproduces the problem?


The Insert code is very simple and directly calls the EF Core API.
You can also try to insert the same type of entity directly using EF Core without using the abp framework?

https://github.com/abpframework/abp/blob/decad8e30f6186be87db8c5743bf55d530514bb9/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L56

**Comment by EpsilonRepo** [comment]
It looks like the problem only happens on some tables AbpUsers or IdentityServerClients for instance.
I did not try all tables, but inserting into AbpSetting or AbpAuditLogs works.

**Comment by maliming** [comment]
Can you share a project that reproduces the problem? I can install orace in docker and test it.

**Comment by EpsilonRepo** [comment]
Here is the solution.
[OracleAbp.zip](https://github.com/abpframework/abp/files/3862869/OracleAbp.zip)


You'll need to download the trial version on Devart dotConnect for Oracle and set the license in the connection string : [https://www.devart.com/dotconnect/oracle/docs/LicensingStandard.html](https://www.devart.com/dotconnect/oracle/docs/LicensingStandard.html)

I hope this helps, thank you

**Comment by EpsilonRepo** [comment]
Hi, could you run the test project? Any idea concerning the problem?

**Comment by maliming** [comment]
I haven't had time to try it yet, I will check it as soon as possible.

**Comment by maliming** [comment]
I tried it. Due to my lack of oracle experience and no successful installation, maybe friends from the community can help to check this problem.

**Comment by EpsilonRepo** [comment]
@maliming maybe I can help you out with Oracle, what's your Problem with the installation?

**Comment by EpsilonRepo** [comment]
Issue can be closed.
Devart + Oracle is working now.
