### ISSUE TITLE
How to make sure we get the same DbContext across different repositories in one project 

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#2199]
I installed the `tenant-management` module into my exsiting project, so this module is not a independent microservice like it used to be.

When I try to do some complex join query like 
(TenantInfo is defined in my own project)
```
private readonly IRepository<Tenant, Guid> _tenantRepository;
private readonly IRepository<TenantInfo, Guid> _tenantInfoRepository;

/* ... */

 var q=from tenant in _tenantRepository 
                join tenantInfo in _tenantInfoRepository on tenant.Id equals  tenantInfo.Id
``` 

error occurs
```
 Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter Cannot use multiple DbContext instances within a single query execution. Ensure the query uses a single context instance.
System.InvalidOperationException: Cannot use multiple DbContext instances within a single query execution. Ensure the query uses a single context instance.
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExtractParameters(Expression query, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, Boolean parameterize, Boolean generateContextAccessors)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)

```

Which means I should get the same DbContext object accross repositories

After deeping into the `UnitOfWorkDbContextProvider`, dbContext is cached by key
```
var dbContextKey = $"{typeof(TDbContext).FullName}_{connectionString}";
```

Which means ` IRepository<Tenant, Guid>` will always be resovled with key contains `ITenantManagementDbContext`.

Even if I config `MyDbContext` to replace `ITenantManagementDbContext`
```
 context.Services.AddAbpDbContext<MyDbContext>(options =>
            {
                options.AddDefaultRepositories(true);
                options.ReplaceDbContext<ITenantManagementDbContext>();
                
            });
```
The repositories will get the same type of DbContext which is `MyDbContext`, but different objects due to the cache key.

**Comment by Goxiaoy** [comment]
I find a way out 

```
[DependsOn(
        typeof(AbpTenantManagementEntityFrameworkCoreModule)
    )]
    public class MyEntityFrameworkCoreModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<MyDbContext>(options =>
            {
                options.AddDefaultRepositories(true);
            });
        }
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<MyDbContext>(options =>
            {
                options.ReplaceDbContext<ITenantManagementDbContext>();
            });
        }
    }
```

```
public class MyDbContext : AbpDbContext<MyDbContext>,ITenantManagementDbContext{

}
```

`AddDefaultRepositories` on `PreConfigureServices` will register all relative repositories before `AbpTenantManagementEntityFrameworkCoreModule` do.

**Comment by tky753** [comment]
Genius, you are!

**Comment by Goxiaoy** [comment]
@tky753 
Make sure your `  options.AddDefaultRepositories(true);` runs before any other built-in `AddAbpDbContext` would work

1. Add ` options.AddDefaultRepositories(true);`  on `PreConfigureServices`

2. Load your 'EntityFrameworkModule' after built-in 'EntityFrameworkModule' like `PermissionManagementEntityFrameworkModule`
