### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json

### ISSUE THREAD

**Issue by lucky51** [abpframework/abp#2221]
InternalGateway.Host  run logs in microservicedemo project：

System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Ocelot.DependencyInjection.OcelotBuilder..ctor(IServiceCollection services, IConfiguration configurationRoot)
   at Ocelot.DependencyInjection.ServiceCollectionExtensions.AddOcelot(IServiceCollection services, IConfiguration configuration)
   at InternalGateway.Host.InternalGatewayHostModule.ConfigureServices(ServiceConfigurationContext context) in F:\abp\abp-master\samples\MicroserviceDemo\gateways\InternalGateway.Host\InternalGatewayHostModule.cs:line 61
   at Volo.Abp.Modularity.ModuleLoader.ConfigureServices(List`1 modules, IServiceCollection services) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleLoader.cs:line 122
   at Volo.Abp.Modularity.ModuleLoader.LoadModules(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleLoader.cs:line 23
   at Volo.Abp.AbpApplicationBase.LoadModules(IServiceCollection services, AbpApplicationCreationOptions options) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 80
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 44
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationWithExternalServiceProvider.cs:line 13
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationFactory.cs:line 37
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationFactory.cs:line 29
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction) in F:\abp\abp-master\framework\src\Volo.Abp.Core\Microsoft\Extensions\DependencyInjection\ServiceCollectionApplicationExtensions.cs:line 15
   at InternalGateway.Host.Startup.ConfigureServices(IServiceCollection services) in F:\abp\abp-master\samples\MicroserviceDemo\gateways\InternalGateway.Host\Startup.cs:line 14
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by qiang999** [comment]
I think it might be a package conflict.
or maybe
https://github.com/abpframework/abp/issues/2124

**Comment by lucky51** [comment]
Pull the latest branch code(Ocelot ->13.8.0)
