### ISSUE TITLE
Authorize Attribute Not work in Custom AppService

### ISSUE THREAD

**Issue by cqgis** [abpframework/abp#2262]
when I use [Authorize] on custom app service ,it's not work 

``` c#
    public class DepartmentAppService
        : CrudAppService<
            Department,
            DepartmentDto,
            Guid,
            PagedAndSortedResultRequestDto,
            CreateUpdateDepartmentDto,
            CreateUpdateDepartmentDto>, IDepartmentAppService
    {
        public DepartmentAppService(IRepository<Department, Guid> repository) : base(repository)
        {
        }


        [Authorize(Permissions.OAPermissions.OAManager_EditDepartment)]
        public override async Task<PagedResultDto<DepartmentDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return await base.GetListAsync(input);
        }
    }
```
the result is  404
```
 content-length: 0 
 date: Wed, 27 Nov 2019 06:26:02 GMT 
 server: Kestrel 
 status: 404 
 x-correlation-id: 3939fa89a1ea4c9b8cb194ea7621fb9d 
```

the log is 
```
[14:26:03 INF] Request starting HTTP/2 GET https://localhost:44350/api/app/department
[14:26:03 INF] Authorization failed.
[14:26:03 INF] AuthenticationScheme: Identity.Application was forbidden.
[14:26:03 INF] Request finished in 17.7088ms 302
[14:26:03 INF] Request starting HTTP/2 GET https://localhost:44350/Account/AccessDenied?ReturnUrl=%2Fapi%2Fapp%2Fdepartment
[14:26:03 INF] Request finished in 55.3922ms 404
```

---
If I check policy in method , it's work well 

``` c#
       public override async Task<PagedResultDto<DepartmentDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            await this.CheckGetListPolicyAsync();
            return await base.GetListAsync(input);
        }
        protected override string GetListPolicyName => nameof(Permissions.OAPermissions.OAManager_EditDepartment);
```

get result:
``` json
{
  "code": null,
  "message": "Authorization failed! Given policy has not granted: OAManager_EditDepartment",
  "details": null,
  "validationErrors": null
}
```
and log is 
```
[14:17:09 INF] Request starting HTTP/2 GET https://localhost:44350/api/app/department
[14:17:09 INF] Authorization was successful.
[14:17:09 INF] Executing endpoint 'CQ.OA.Services.DepartmentAppService.GetListAsync (CQ.OA.Application)'
[14:17:09 INF] Route matched with {action = "GetList", controller = "Department", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[CQ.OA.Departments.DepartmentDto]] GetListAsync(Volo.Abp.Application.Dtos.PagedAndSortedResultRequestDto) on controller CQ.OA.Services.DepartmentAppService (CQ.OA.Application).
[14:17:09 INF] Authorization failed.
[14:17:11 WRN] ---------- RemoteServiceErrorInfo ----------
[14:17:11 WRN] {
  "code": null,
  "message": "Authorization failed! Given policy has not granted: OAManager_EditDepartment",
  "details": null,
  "validationErrors": null
}
[14:17:11 WRN] Authorization failed! Given policy has not granted: OAManager_EditDepartment
Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! Given policy has not granted: OAManager_EditDepartment
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, String policyName)
   at Volo.Abp.Application.Services.ApplicationService.CheckPolicyAsync(String policyName)
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Application.Services.CrudAppService`7.CheckGetListPolicyAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithoutReturnValueAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at CQ.OA.Services.DepartmentAppService.GetListAsync(PagedAndSortedResultRequestDto input) in D:\web\OA\src\CQ.OA.Application\Services\DepartmentAppService.cs:line 33
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

it's seem like #1670

my abp version is 1.0.2

**Comment by maliming** [comment]
Please share the project of your question.

**Comment by cqgis** [comment]
> Please share the project of your question.

I upload the project about my question  https://github.com/cqgis/abpvnextdemo

**Comment by maliming** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/6908465/69703853-5118c600-112d-11ea-9914-772961b551bc.png)

**Comment by cqgis** [comment]
> Can't reproduce.
> 
> ![image](https://user-images.githubusercontent.com/6908465/69703853-5118c600-112d-11ea-9914-772961b551bc.png)

you login with admin , has all permission , of course get right result!
do not login in  and visit

**Comment by maliming** [comment]
This is because **CheckPolicyAsync** will throw an exception. The exception will be handled by abp.

The **Authorize** attribute will perform the authentication scheme. Cookie authentication scheme is redirected to the login page.

**Comment by cqgis** [comment]
> perform

when I want  show json result, is that  I should use CheckPolicyAsync in application service  , but not authorize?

**Comment by maliming** [comment]
Need to throw AbpAuthorizationException.

https://github.com/abpframework/abp/blob/e026dfd985d11eecbd16906fa24d07e651e63311/framework/src/Volo.Abp.Authorization/Microsoft/AspNetCore/Authorization/AbpAuthorizationServiceExtensions.cs#L96
