### ISSUE TITLE
DistributedCache.GetOrAddAsync cause problem “SemaphoreSlim.WaitUntilCountOrTimeoutAsync”

### ISSUE THREAD

**Issue by Lflying-NRSoft** [abpframework/abp#2284]
The specific error log is as follows:
2019-11-26 13:16:32.575 +08:00 [ERR] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nito.AsyncEx.SemaphoreSlimExtensions.DoLockAsync(SemaphoreSlim this, CancellationToken cancellationToken)
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
   at Domain.BSCaches.BSCacheManager.GetDataTableAsync(String tableName, String id)
   at HttpApi.Host.Controllers.BSCacheController.GetAsync(String tableName, String[] ids, String[] fields)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2019-11-26 13:16:32.577 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2019-11-26 13:16:32.577 +08:00 [INF] Executed action ProductService.HttpApi.Host.Controllers.BSCacheController.GetAsync (ProductService.HttpApi.Host) in 10004.7813ms
2019-11-26 13:16:32.578 +08:00 [INF] Executed endpoint 'ProductService.HttpApi.Host.Controllers.BSCacheController.GetAsync (ProductService.HttpApi.Host)'
2019-11-26 13:16:32.578 +08:00 [INF] Request finished in 10006.3138ms 500 application/json; charset=utf-8

Read cache response time is getting longer and longer

I wrote a test program in a compressed package. There is the log of my pressure test. At the end of the log, you can see that the request response time is getting longer and longer.

The test code is placed on the following link
[https://gitee.com/Lflying/ABPDistributedCache](url)

**Comment by Lflying-NRSoft** [comment]
I used the pressure test tool to test. The overwhelming address is: http://localhost:56976/weatherforecast

**Comment by maliming** [comment]
Can you share the project code on github?

**Comment by Lflying-NRSoft** [comment]
[https://github.com/Lflying-NRSoft/ABPDistributedCache](url)

**Comment by maliming** [comment]
I cannot reproduce your problem.

You can try using the synchronized method `distributedCache.GetOrAdd`

![image](https://user-images.githubusercontent.com/6908465/69914765-f790fe00-1482-11ea-8180-4cbddfb526fd.png)

**Comment by Lflying-NRSoft** [comment]
Please use jmeter pressure measurement tool.
I have listed the logs on it, and there are also log files on github
postman can't simulate 50 concurrent or 200 concurrent well

**Comment by maliming** [comment]
Do you still get exceptions when you use the synchronization method? `distributedCache.GetOrAdd`

**Comment by Lflying-NRSoft** [comment]
There is no problem with the synchronous method. I have submitted the code, and the pressure test tool HttpLoad has also been uploaded.
Why doesn't the asynchronous method work?
[https://github.com/Lflying-NRSoft/ABPDistributedCache/tree/master/DistributedCache_GetOrAdd_ErrorDemo/HttpLoad](https://github.com/Lflying-NRSoft/ABPDistributedCache/tree/master/DistributedCache_GetOrAdd_ErrorDemo/HttpLoad)

**Comment by Lflying-NRSoft** [comment]
Whether asynchronous locks cannot use this method？ SemaphoreSlim.LockAsync

**Comment by maliming** [comment]
I believe this problem is not related to ABP, it may be that your tool caused the request to be aborted(`HttpContext.RequestAborted`).

Test code:
```
[HttpGet("TestCancellationToken")]
public string TestCancellationToken(CancellationToken cancellationToken)
{
	for (var i = 0; i < 10; i++)
	{
		cancellationToken.ThrowIfCancellationRequested();
		Thread.Sleep(100);
	}

	return "ok";
}
```

Error logs:
```
2019-12-02 08:56:05.076 +08:00 [ERR] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at DistributedCache_GetOrAdd_ErrorDemo.Controllers.WeatherForecastController.TestCancellationToken(CancellationToken cancellationToken) in C:\Users\maliming\Desktop\ABPDistributedCache-master\DistributedCache_GetOrAdd_ErrorDemo\Controllers\WeatherForecastController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2019-12-02 08:56:05.076 +08:00 [ERR] The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at DistributedCache_GetOrAdd_ErrorDemo.Controllers.WeatherForecastController.TestCancellationToken(CancellationToken cancellationToken) in C:\Users\maliming\Desktop\ABPDistributedCache-master\DistributedCache_GetOrAdd_ErrorDemo\Controllers\WeatherForecastController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by Lflying-NRSoft** [comment]
这个问题已解决，请升级到 V 2.0.0. 版本
