### ISSUE TITLE
how can I override the the IdentityServerOptions

### ISSUE THREAD

**Issue by zredb** [abpframework/abp#2289]
MyIdentityServerModule id dependon AbpAccountWebIdentityServerModule, when i want to set IdentityServerOptions using 
```
            context.Services.AddIdentityServer(option =>
            {
                option.UserInteraction.LogoutUrl = "/Idp/Logout";
            });
```
 to set the logout interaction address , but I will get a runtime error:
```
System.InvalidOperationException: Decorator already registered for type: IAuthenticationService.
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCore.AddDecorator[TService](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCore.AddTransientDecorator[TService,TImplementation](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCore.AddCookieAuthentication(IIdentityServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.IdentityServerServiceCollectionExtensions.AddIdentityServer(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerServiceCollectionExtensions.AddIdentityServer(IServiceCollection services, Action`1 setupAction)
   at Meteodyn.Msp.MspIdentityServerModule.ConfigureServices(ServiceConfigurationContext context) in C:\code\MspWeb\src\Meteodyn.Msp.IdentityServer\MspIdentityServerModule.cs:line 122
   at Volo.Abp.Modularity.ModuleLoader.ConfigureServices(List`1 modules, IServiceCollection services)
   at Volo.Abp.Modularity.ModuleLoader.LoadModules(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources)
   at Volo.Abp.AbpApplicationBase.LoadModules(IServiceCollection services, AbpApplicationCreationOptions options)
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Meteodyn.Msp.Startup.ConfigureServices(IServiceCollection services) in C:\code\MspWeb\src\Meteodyn.Msp.IdentityServer\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Meteodyn.Msp.Program.Main(String[] args) in 
C:\code\MspWeb\src\Meteodyn.Msp.IdentityServer\Program.cs:line 27
```
How can I solve this problem？

**Comment by maliming** [comment]
Try
```
services.PostConfigure<IdentityServerOptions>(option =>
{
	option.UserInteraction.LogoutUrl = "/Idp/Logout";
});
```

**Comment by zredb** [comment]
@maliming this solved my problem, thank you!
