### ISSUE TITLE
An exception was thrown while activating

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2298]
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while activating Platform.OrganizeController -> Platform.BaseOrganizeAppService.
  Source=Autofac
  StackTrace:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType) in E:\develop\湖南伟胜\微服务架构\abp\framework\src\Volo.Abp.Autofac\Autofac\Extensions\DependencyInjection\AutofacServiceProvider.cs:line 69
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

内部异常 1:
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Platform.BaseOrganizeAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[Platform.BaseOrganize,System.Guid] repository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[Platform.BaseOrganize,System.Guid])'.

![image](https://user-images.githubusercontent.com/22017199/70040892-3647c500-15f7-11ea-8f47-68e23916af1d.png)

![image](https://user-images.githubusercontent.com/22017199/70040820-16b09c80-15f7-11ea-8164-7ffaa1f36fef.png)

I can go into OrganizeController, keep going down and report an error.

**Comment by maliming** [comment]
Is `BaseOrganize `an aggregate root or an entity?

**Comment by 344089386** [comment]
![image](https://user-images.githubusercontent.com/22017199/70103054-f6bfbe00-1674-11ea-82b6-7e8027931afe.png)

**Comment by 344089386** [comment]
![image](https://user-images.githubusercontent.com/22017199/70103277-a6952b80-1675-11ea-8172-4903e0675310.png)
Neither of the two methods you give will solve my problem.
I am the architecture of microservices.

**Comment by 344089386** [comment]
options.AddDefaultRepositories(includeAllEntities: true);

That's the problem, but shouldn't this have a default value?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/2108#issuecomment-551124211
