### ISSUE TITLE
CLI : "abp new MyProject.BackEnd" failed

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2353]
Hi,

I start this command :
  
  abp new MyProject.BackEnd

And I got an error:

[21:25:55 INF] ABP CLI (https://abp.io)
[21:25:59 INF] Version 1.1.0-dev (Development channel)
[21:25:59 INF] Creating your project...
[21:25:59 INF] Project name: MyProject.BackEnd
[21:25:59 INF] Output folder: C:\Dev
[21:26:00 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 91
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 90
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/issues/2325
