### ISSUE TITLE
ef core migration command fails to seed database initial user

### ISSUE THREAD

**Issue by hades200082** [abpframework/abp#2354]
After creating a project with your CLI and running the initial migrations via the dotnet ef migrations command and updating the database the AspNet Users table is still empty.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/blob/dev/docs/en/Getting-Started-AspNetCore-MVC-Template.md#using-the-dbmigrator-application

**Comment by hades200082** [comment]
Using dbmigrator with a regular SQL Server connection string results in the following exception...

```
Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Game.Data.GameDb
MigrationService -> Game.EntityFrameworkCore.EntityFrameworkCoreGameDbSchemaMigrator -> Game.EntityFrameworkCore.GameMigra
tionsDbContext -> ?:Microsoft.EntityFrameworkCore.DbContextOptions`1[[Game.EntityFrameworkCore.GameMigrationsDbContext, Ga
me.EntityFrameworkCore.DbMigrations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilde
r, String connectionString, Action`1 sqlServerOptionsAction)
   at Volo.Abp.EntityFrameworkCore.AbpDbContextConfigurationContextSqlServerExtensions.UseSqlServer(AbpDbContextConfigurat
ionContext context, Action`1 sqlServerOptionsAction)
   at Volo.Abp.EntityFrameworkCore.AbpDbContextOptionsSqlServerExtensions.<>c__DisplayClass0_0.<UseSqlServer>b__0(AbpDbCon
textConfigurationContext context)
   at Volo.Abp.EntityFrameworkCore.DependencyInjection.DbContextOptionsFactory.Configure[TDbContext](AbpDbContextOptions o
ptions, AbpDbContextConfigurationContext`1 context)
   at Volo.Abp.EntityFrameworkCore.DependencyInjection.DbContextOptionsFactory.Create[TDbContext](IServiceProvider service
Provider)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass2_0.<Register>b__0(IComponentContext con
text, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 paramet
ers)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentR
egistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 paramete
rs)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters,
 Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provid
er, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider pro
vider)
   at Game.DbMigrator.Program.<>c__DisplayClass0_0.<Main>b__1() in D:\Projects\Personal\Gitlab\game\src\Game.DbMigrator\Pr
ogram.cs:line 26
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object st
ate)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object st
ate)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass15_0.<Run>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object st
ate)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object st
ate)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Threading.AsyncHelper.RunSync(Func`1 action)
   at Game.DbMigrator.Program.Main(String[] args) in D:\Projects\Personal\Gitlab\game\src\Game.DbMigrator\Program.cs:line
25

Process finished with exit code -532,462,766.
```

**Comment by maliming** [comment]
Can you reproduce the above problem using a project created by cli?
If possible, please provide steps.

**Comment by hades200082** [comment]
The project referenced above was created using the cli

**Comment by maliming** [comment]
Can you provide steps to reproduce the problem?

**Comment by hades200082** [comment]
1. Install abp cli
2. Create new project through abp cli
3. Set connection string to local instance of SQL Server 2019 Development Edition using a connection string like `Server=localhost;Database=myDataBase;Trusted_Connection=True;`
4. Run dbmigrator and get the exception above

**Comment by hikalkan** [comment]
@yekalkan can you try this.
@hades200082 try remove the migrations and re-create the initial one for now.

**Comment by hades200082** [comment]
@hikalkan I tried deleting the migrations and recreating them as you suggested but the recreated ones were empty. 

Since I'm not that far into anything yet I've ditched the whole solution and restarted it again from the CLI, this time starting off with the dbmigrator (last time I'd already tried to run the ef database update tool).

It worked fine this time and created all the tables and seeded data. I noticed too that the table names are different to what the ef migration tool created... that just seemed to create the default .Net Identity Framework tables.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/70582050-241be700-1bf4-11ea-9b03-1d942e2382bf.png)

![image](https://user-images.githubusercontent.com/6908465/70582149-7826cb80-1bf4-11ea-8af6-c24dff2c40e6.png)

**Comment by Loongle** [comment]
maybe you need to check the version of the template?

**Comment by Loongle** [comment]
One day I encountered a situation similar to yours, I updated the cli to the latest and it did not appear
