### ISSUE TITLE
version 1.1.0  CLI ERROR

### ISSUE THREAD

**Issue by heweigeng1** [abpframework/abp#2373]
PS D:\DEMOABP> abp new demoA
[17:39:16 INF] ABP CLI (https://abp.io)
[17:39:16 INF] Version 1.1.0 (Stable channel)
[17:39:16 WRN] Unable to retrieve the latest version
[17:39:16 WRN] Object reference not set to an instance of an object.
[17:39:16 INF] Creating your project...
[17:39:16 INF] Project name: demoA
[17:39:16 INF] Output folder: D:\DEMOABP\demoA
[17:39:16 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 91
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 90
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2325

**Comment by heweigeng1** [comment]
Thank you
