### ISSUE TITLE
version1.1.1 Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.1.0.0

### ISSUE THREAD

**Issue by nonepassby** [abpframework/abp#2384]
when i update abp from 1.0.2 to 1.1.1，it's ok on my devlop env( windows 10, vs2019), but when i publish it to a Linux server, i got an error in Log/logs.txt:
```
2019-12-13 11:01:04.284 +08:00 [INF] Starting web host.
2019-12-13 11:01:05.273 +08:00 [FTL] Host terminated unexpectedly!
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.EntityFrameworkCore, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.Modularity.ModuleLoader.ConfigureServices(List`1 modules, IServiceCollection services)
   at Volo.Abp.Modularity.ModuleLoader.LoadModules(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources)
   at Volo.Abp.AbpApplicationBase.LoadModules(IServiceCollection services, AbpApplicationCreationOptions options)
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Top.Wiz.CIPlatform.Web.Startup.ConfigureServices(IServiceCollection services) in /data/jenkins/workspace/pipeline_dotnetcore/wiz_ciplatform/src/Top.Wiz.CIPlatform.Web/Startup.cs:line 11
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Top.Wiz.CIPlatform.Web.Program.Main(String[] args) in /data/jenkins/workspace/pipeline_dotnetcore/wiz_ciplatform/src/Top.Wiz.CIPlatform.Web/Program.cs:line 27
```
My Linux server env:
os: CentOS 7.6 core minimal
runtime: aspnetcore-runtime-3.1，dotnet --info:
```
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by maliming** [comment]
I think this is a centos environmental issue, and has nothing to do with abp.

**Comment by nonepassby** [comment]
> I think this is a centos environmental issue, and has nothing to do with abp.

I have tested it on 2 centos7 server, but get the same error msg

**Comment by maliming** [comment]
You can create a simple project using net core 3.1 + ef core 3.1 and then try publishing to centos to see the results.

**Comment by nonepassby** [comment]
> You can create a simple project using net core 3.1 + ef core 3.1 and then try publishing to centos to you are right，when i publish project in dev mathine and copy to linux server,  all things run. thank you very much.

I have use a jenkins slave(CentOS7.6 with dotnet-sdk-3.1) publish dotnetcore project，and then copy it to Linux web server. the publish command is:
`dotnet publish -c Release -o /data/publish/app/site01`
 it looks like is jenkins slave's problem.
