### ISSUE TITLE
A Install  Error 

### ISSUE THREAD

**Issue by zengxinle** [abpframework/abp#2393]
**A Error**   in win10/win2012

:  ****[18:01:01 ERR] Unexpected character encountered while parsing value**:** <. Path '', line 0, position 0.
========================================

D:\ABPCore_Test\AbpMvc>abp new HPCorp
[17:59:16 INF] ABP CLI (https://abp.io)
[17:59:16 INF] Version 1.1.2 (Stable channel)
[17:59:17 INF] Creating your project...
[17:59:17 INF] Project name: HPCorp
[17:59:17 INF] Output folder: D:\ABPCore_Test\AbpMvc\HPCorp
[17:59:19 INF] Downloading template: app, version: 1.1.2
[18:01:01 ERR] Unexpected character encountered while parsing value <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position
0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean
 checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\Githu
b\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\NewtonsoftJsonSerializer.cs:line 27
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage respo
nseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.
cs:line 48
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage r
esponseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHand
ler.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input)
 in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 125
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version) in D:\Github\
abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 69
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\s
rc\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo
.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 90
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliS
ervice.cs:line 55

**Comment by hikalkan** [comment]
I suppose this happens when server returns an error (and it returns HTML in an error case, instead of JSON). We should check the error and the error response.
Thanks for reporting.

I suppose this happens rarely. Alternatively you can direct download templates from the web site: https://abp.io/get-started

**Comment by ebicoglu** [comment]
this issue has been already fixed in #2387
