### ISSUE TITLE
Template - PII is hidden

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2394]
Hi,

I'm a newbie to abp and so, I have create a new template online with MongoDB and tiered.

When I run it, it start, but when I try to login I got the following error:

```
   System.InvalidOperationException: 'IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.'
   
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
```

Any idea of the problem ?

Thanks a lot

PS: I'm on a local machine and have desactivated the firewall.

**Comment by hikalkan** [comment]
Are you sure that IdentityServer application is running?

Also, if you are new, are you sure that you need to a Tiered solution which is advanced and not needed in many scenarios.

**Comment by vd3d** [comment]
Yes, I'm sure it is running, I start it and it open the web browser on https://localhost:44395 and a login page appear for it. What is strange is that I don't see any 'identity' collection in the mongodb database (Yes, the connection string is correct and I have disabled the firewall).

Yes I need tiered for external services.

**Comment by hikalkan** [comment]
However, redis is important in the tiered template, otherwise two applications will use in memory cache which will cause inconsistent cache values.

**Comment by vd3d** [comment]
DistributedCache is only important for multiples server (ie. if we have a lot of load), for a simple app, it is not necessary (If my understanding is correct). If we only have one server we should have can use "MemoryCache" (not sure how it support multi-tenancy and multiples modules) or SQLServer / NCache / MongoDB. But yes, for scaling, anyway Redis is the better solution.

**Comment by hikalkan** [comment]
>DistributedCache is only important for multiples server

In the tiered case, there will be 3 applications (Web UI, Identity Server and HttpApi.Host) and they should use a single distributed cache instance.

Use regular (no tiering) template for a single instance application.
