### ISSUE TITLE
request route missing run in production environment with Kestrel Server ,help needed. The view '~/Pages/Error/Default.cshtml' was not found

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2396]
it's ridiculous when i debug the web project with  visual studio 2019 ,everything works well.
however when i start the below code to run the project ,

```
dotnet XXXX.WEB.dll
```
the program showed the route missing, and turned into 500 status ,the log

>  This page isn’t working
> localhost is currently unable to handle this request.
> HTTP ERROR 500
 
 

```
[13:41:17 INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
[13:41:17 INF] Identity.Application was not authenticated. Failure message: Unprotect ticket failed
[13:41:17 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
[13:41:17 INF] Route matched with {action = "Index", controller = "Error", area = "", page = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index(Int32) on controller Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared).
[13:41:17 INF] Executing ViewResult, running view ~/Pages/Error/Default.cshtml.
[13:41:17 ERR] The view '~/Pages/Error/Default.cshtml' was not found. Searched locations: ["~/Pages/Error/Default.cshtml"]
[13:41:17 INF] Executed action Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared) in 14.9916ms
[13:41:17 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController.Index (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)'
[13:41:17 ERR] An exception was thrown attempting to execute the error handler.
System.InvalidOperationException: The view '~/Pages/Error/Default.cshtml' was not found. The following locations were searched:
~/Pages/Error/Default.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
```

Really honestly to hear from anyone to help me. it puzzled me for a long term.

**Comment by johnnba** [comment]
i has try my best to release all the below files in folders, however it still couldn't indicate missing the request view such as "/Pages/Error/Default.cshtml"

Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.dll
Volo.Abp.AspNetCore.Mvc.UI.Bundling.dll
Volo.Abp.AspNetCore.Mvc.UI.dll
Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.dll
Volo.Abp.AspNetCore.Mvc.UI.Packages.dll
Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.dll
Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.dll
Volo.Abp.AspNetCore.Mvc.UI.Widgets.dll
Microsoft.AspNetCore.Diagnostics.dll

**Comment by johnnba** [comment]
finally, i solved it. 
the question is that i forgot to create my customize error page. when i create my error page , everything works  well.
the simple sample for your refference can be like this:
 
```


@using System.Linq
@using System.Collections.Generic
@using Localization.Resources.AbpUi
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Views.Error
@model AbpErrorViewModel
@inject IHtmlLocalizer<AbpUiResource> L
@{
    var errorMessage = Model.ErrorInfo.Message;
    var errorDetails = Model.ErrorInfo.Details;
    if (errorDetails.IsNullOrEmpty())
    {
        errorDetails = errorMessage;
        errorMessage = L["Error"].Value + "!";
    }
}

<h1>
    [@Model.HttpStatusCode] @errorMessage
</h1>

<div>
    <p>
        @errorDetails
    </p>
    <p>
        @if (!Model.ErrorInfo.ValidationErrors.IsNullOrEmpty())
        {
            foreach (var validationError in Model.ErrorInfo.ValidationErrors)
            {
                <text>* </text>@(validationError.Message)
                if (validationError.Members != null && validationError.Members.Any())
                {
                    <text>(@string.Join(", ", validationError.Members))</text>
                }
                <br />
            }
        }
    </p>
</div>

```
