### ISSUE TITLE
Autofac.Core.DependencyResolutionException: An exception was thrown while activating 

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2541]
Autofac.Core.DependencyResolutionException: An exception was thrown while activating HR.SelfService.D365Integrations.SyncBookEntriesSync -> BookTypeAppService.

**Comment by acjh** [comment]
Show the stack trace.

**Comment by dicksonkimeu** [comment]
@maliming @acjh essentially, from the new module I created, I can't activate it because it has class that uses Application Service Module.

**Comment by acjh** [comment]
Did you `[DependsOn(typeof(YourApplicationModule))]`?

**Comment by dicksonkimeu** [comment]
Have added all depedancy modules.

It's worked.

**Comment by Tashaa78** [comment]
I keep getting this  `Autofac.Core.DependencyResolutionException` with new modules. I don't know what I am doing wrong. Below is my stack trace-:
```
Executing endpoint 'Volo.DayOff.DayOffTypesController.CreateAsync (Volo.Abp.Dayoff.HttpApi)'
2020-03-12 17:39:22.108 +02:00 [INF] Route matched with {action = "Create", controller = "DayOffTypes", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.DayOff.EventTypes.Dtos.DayOffTypeDto] CreateAsync(Volo.DayOff.EventTypes.Dtos.CreateDayOffTypeDto) on controller Volo.DayOff.DayOffTypesController (Volo.Abp.Dayoff.HttpApi).
2020-03-12 17:39:22.139 +02:00 [ERR] ---------- RemoteServiceErrorInfo ----------
2020-03-12 17:39:22.166 +02:00 [ERR] {
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "validationErrors": null
}
2020-03-12 17:39:22.166 +02:00 [ERR] An exception was thrown while activating Volo.DayOff.DayOffTypesController.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.DayOff.DayOffTypesController.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.DayOff.DayOffTypesController' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.DayOff.EventTypes.IDayOffTypeAppService appService' of constructor 'Void .ctor(Volo.DayOff.EventTypes.IDayOffTypeAppService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType) in C:\Data\XKode\workspaces\xkode-abp\framework\src\Volo.Abp.Autofac\Autofac\Extensions\DependencyInjection\AutofacServiceProvider.cs:line 71
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-03-12 17:39:22.204 +02:00 [ERR] ---------- Exception Data ----------
2020-03-12 17:39:22.204 +02:00 [ERR] ActivatorChain = Volo.DayOff.DayOffTypesController
2020-03-12 17:39:22.208 +02:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2020-03-12 17:39:22.221 +02:00 [INF] Executed action Volo.DayOff.DayOffTypesController.CreateAsync (Volo.Abp.Dayoff.HttpApi) in 113.53ms
2020-03-12 17:39:22.221 +02:00 [INF] Executed endpoint 'Volo.DayOff.DayOffTypesController.CreateAsync (Volo.Abp.Dayoff.HttpApi)'
```

**AppService Interface**
```
using System;
using System.Collections.Generic;
using System.Text;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.DayOff.Events.Dtos;
using Volo.DayOff.EventTypes.Dtos;
using Volo.DayOff.Services;

namespace Volo.DayOff
{
    public interface IDayOffTypeAppService :
        ICrudAppService< //Defines CRUD methods
            DayOffTypeDto, //Used to show entities
            Guid, //Primary key of the entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting on getting a list of entities
            CreateDayOffTypeDto, //Used to create a new entity
            UpdateDayOffTypeDto> //Used to update a entity
    {
    }
}
```
**AppService Implementation**
```
using System;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Volo.DayOff.EventTypes;
using Volo.DayOff.EventTypes.Dtos;

namespace Volo.DayOff.Types
{
    public class TypesAppService :
        CrudAppService<DayOffType, DayOffTypeDto, Guid, PagedAndSortedResultRequestDto, CreateDayOffTypeDto,
            UpdateDayOffTypeDto>, IDayOffTypeAppService
    {
        private readonly IRepository<DayOffType, Guid> _repository;

        public TypesAppService(IRepository<DayOffType, Guid> repository) : base(repository)
        {
            _repository = repository;
        }
    }
}
```
**Controller**

```
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.DayOff.EventTypes;
using Volo.DayOff.EventTypes.Dtos;

namespace Volo.DayOff
{
    [RemoteService]
    [Route("api/day-off/types")]
    public class DayOffTypesController : DayOffBaseController, IDayOffTypeAppService
    {
        private readonly IDayOffTypeAppService _appService;

        public DayOffTypesController(IDayOffTypeAppService appService)
        {
            _appService = appService;
        }
        [HttpGet("{id}")]
        public async Task<DayOffTypeDto> GetAsync([FromRoute]Guid id)
        {
            return await _appService.GetAsync(id);
        }
        [HttpPost]
        public async Task<DayOffTypeDto> CreateAsync([FromBody]CreateDayOffTypeDto input)
        {
            return await _appService.CreateAsync(input);
        }
    }
}
```

**Comment by maliming** [comment]
hi @Tashaa78 

Both your `DayOffTypesController `and `TypesAppService  `services implement the `IDayOffTypeAppService `interface.

And you try to inject `IDayOffTypeAppService `in `DayOffTypesController `.  : )

**Comment by Tashaa78** [comment]
forgive my confusion, am still a newbie but isn't it the norm? Trying to follow the `BloggingModule`

We have the `IBlogAppService`

```
public interface IBlogAppService : IApplicationService
    {
        Task<ListResultDto<BlogDto>> GetListAsync();

        Task<BlogDto> GetByShortNameAsync(string shortName);

        Task<BlogDto> GetAsync(Guid id);
        
        Task<BlogDto> Create(CreateBlogDto input);

        Task<BlogDto> Update(Guid id, UpdateBlogDto input);

        Task Delete(Guid id);
    }
```

which is implemented by the `BlogAppService`

```
namespace Volo.Blogging.Blogs
{
    public class BlogAppService : BloggingAppServiceBase, IBlogAppService
    {
        private readonly IBlogRepository _blogRepository;

        public BlogAppService(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }
        ...
    }
}
```

and also implemented by the `BlogsController` and injected into the `BlogsController`

```
namespace Volo.Blogging
{
    [RemoteService]
    [Area("blogging")]
    [Route("api/blogging/blogs")]
    public class BlogsController : AbpController, IBlogAppService
    {
        private readonly IBlogAppService _blogAppService;

        public BlogsController(IBlogAppService blogAppService)
        {
            _blogAppService = blogAppService;
        }
        ...
    }
}

```
