### ISSUE TITLE
BackgroundJob execute by hangfire server throw Authorization failed

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#2631]
I have define a BackgroundJob which execute by hangfire server.Then job execute method call an custom appService.When the job execute,it throw  Authorization failed!
My question is how can i pass the authentication info to appService when hangfire server execute this job.
```
public class MyCustomJob : IBackgroundJob<MyCustomJobArgs>, ITransientDependency
{
        private readonly IMyCustomAppService _myCustomerService;
        public MyCustomJob (IMyCustomAppService myCustomerService) {
            _myCustomerService= myCustomerService;
        }
        public void Execute(MyCustomJobArgs args)
        {
             //thow authorization failed
            var list= AsyncHelper.RunSync(()=>_myCustomerService.GetListAsync...); 
        }
}

---> Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! Given policy has not granted: XXXManagement.XXX
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, String policyName)
   at Volo.Abp.Application.Services.ApplicationService.CheckPolicyAsync(String policyName)
   at Volo.Abp.Application.Services.CrudAppService`7.CheckGetListPolicyAsync()
   at Volo.Abp.Application.Services.CrudAppService`7.GetListAsync(TGetListInput input)
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass16_0`1.<Run>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at Volo.Abp.Threading.AsyncHelper.RunSync[TResult](Func`1 func)
```

**Comment by maliming** [comment]
You can refer to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1107#issuecomment-226714736

**Comment by mehmetuken** [comment]
And this https://github.com/abpframework/abp/issues/1837#issuecomment-538677739
