### ISSUE TITLE
ABP CLI new command not work

### ISSUE THREAD

**Issue by amarmechai** [abpframework/abp#2651]
When I run **"abp new Acme.BookStore -u angular**" I have this error

[08:01:39 ERR] Cannot convert null value to System.DateTime. Path 'licenseEndTime', line 1, position 104.
Newtonsoft.Json.JsonSerializationException: Cannot convert null value to System.DateTime. Path 'licenseEndTime', line 1, position 104.
   at Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Volo.Abp.Json.Newtonsoft.AbpJsonIsoDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\AbpJsonIsoDateTimeConverter.cs:line 36
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\Newtonsoft\NewtonsoftJsonSerializer.cs:line 27
   at Volo.Abp.Cli.Licensing.AbpIoApiKeyService.GetApiKeyOrNullAsync() in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Licensing\AbpIoApiKeyService.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 56
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

**Comment by maliming** [comment]
Please upgrade your abp cli to 2.0 first.

https://www.nuget.org/packages/Volo.Abp.Cli/2.0.0

**Comment by amarmechai** [comment]
@maliming it works after upgrading to 2.0.0
Thank you!
