### ISSUE TITLE
"The reader is closed" error on calling Efcore repository's DeleteAsync method

### ISSUE THREAD

**Issue by inamvar** [abpframework/abp#2686]
I have a Repository that derived from **EfCoreRepository** class. I Injected that repository in a **DomainService**. When  I call **DeleteAsync** method from injected repository object, I'll get **The reader is closed** error. If I call a method from another repository before that, It works properly but without it, will get that error.  Can you please help me to find out where is the problem?

- Abp version: 2.0.0
- .Net Core version: 3.1
- Database: PostgreSQL 11

``` C#
 public class ReservationManager : DomainService, IReservationManager
    {
        private readonly IReservationRepository _repository;
        private readonly IReservationRequestRepository _requestRepository;

        public ReservationManager(
                             IReservationRepository repository,
                             IReservationRequestRepository requestRespository)
        {
            this._repository = repository;
            this._requestRepository = requestRespository;
        }


        public async Task CancelRequest(string concurrencyStamp)
        {
       
            // If I call this before the delete action it works properly.
            // await _repository.GetCountAsync();

            // At this line I get "The reader is closed" error
            await _requestRepository.DeleteAsync(x => x.ConcurrencyStamp == concurrencyStamp, autoSave: true);
           
        }
}

```

And  here is the stack trace:

```
   at Npgsql.NpgsqlDataReader.CheckClosed()
   at Npgsql.NpgsqlDataReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<DeleteAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.<ProceedAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dariksoft.PmsCloud.DomainServices.ReservationManager.<CancelRequest>d__3.MoveNext() in C:\codes\pms-cloud\aspnet-core\src\Dariksoft.PmsCloud.Domain\DomainServices\ReservationManager.cs:line 27
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dariksoft.PmsCloud.AppServices.ReservationService.<PostCancelRequest>d__4.MoveNext() in C:\codes\pms-cloud\aspnet-core\src\Dariksoft.PmsCloud.Application\AppServices\ReservationService.cs:line 51
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() 
```

**Comment by maliming** [comment]
Can you try sql server localdb? Does it work fine?

**Comment by inamvar** [comment]
> Can you try sql server localdb? Does it work fine?

I tested on **localdb** and the error message changed to : **A DbContext can only be created inside a unit of work!**

**Comment by maliming** [comment]
When you call the `CancelRequest `method, are you using the `IReservationManager `interface or the `ReservationManager `class?

**Comment by inamvar** [comment]
Im calling the **CancelRequest** method from a **CrudAppService** that use IReservationManager and inject it in constructor method.

``` C#
 [Authorize(Permissions.PmsCloudPermissions.Reservations.Default)]
    public class ReservationService : PmsCloudExtendedCrudService<
        Reservation,
        ReservationDto,
        int,
        PagedAndSortedResultRequestDto,
        ReservationCreateDto,
        ReservationUpdateDto>,
        IReservationService
    {
        private readonly ISettingManager _settingManager;
        private readonly IReservationManager _reservationManager;
        public ReservationService(IReservationRepository repository, ISettingManager settingManager, IReservationManager reservationManager) : base(repository)
        {
            this._settingManager = settingManager;
            this._reservationManager = reservationManager;
        }
     
    [Authorize(Permissions.PmsCloudPermissions.Reservations.Create)]
        public async void PostCancelRequest(string concurrencyStamp)
        {
          
           await this._reservationManager.CancelRequest(concurrencyStamp);
        }

}
```

**Comment by maliming** [comment]
Use `Task` instead of `void` as the return value of the `PostCancelRequest` asynchronous method.

**Comment by inamvar** [comment]
> Use `Task` instead of `void` as the return value of the `PostCancelRequest` asynchronous method.

Error has gone 👍  It works properly both on **LocalDB** and **postgreSQL**. 
Thank you very much. 
and thanks to amazing Abp team!
