### ISSUE TITLE
AbpStringLocalizerFactory in "Volo.Abp.Localization" namespace sometimes cause issue

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2736]
When I start to debug the Microservice project, the project sometimes cause issue.Please see the screenshot below:
<img width="684" alt="11" src="https://user-images.githubusercontent.com/57399417/73592513-49fba300-4536-11ea-962a-efa2e5228f9c.png">

**Comment by hikalkan** [comment]
I will check the code if there is any possibility to cause this exception.

**Comment by maliming** [comment]
This error happened very accidentally when I started multiple projects at the same time.

```

An unhandled exception occurred while processing the request.
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.List<T>+Enumerator.MoveNext()

DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Localization.IStringLocalizerFactory)' on type 'StringLocalizer`1'.
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

DependencyResolutionException: An exception was thrown while activating Microsoft.Extensions.Localization.StringLocalizer`1[[Volo.Abp.UI.Navigation.Localization.Resource.AbpUiNavigationResource, Volo.Abp.UI.Navigation, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null]].
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters, out object decoratorTarget)
```
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Volo.Abp.Localization.AbpStringLocalizerFactory.CreateStringLocalizerCacheItem(LocalizationResource resource) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 58
   at Volo.Abp.Localization.AbpStringLocalizerFactory.<>c__DisplayClass5_0.<Create>b__0(Type _) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 43
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Volo.Abp.Localization.AbpStringLocalizerFactory.Create(Type resourceType) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 41
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Localization.IStringLocalizerFactory)' on type 'StringLocalizer`1'.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Volo.Abp.Localization.AbpStringLocalizerFactory.CreateStringLocalizerCacheItem(LocalizationResource resource) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 58
   at Volo.Abp.Localization.AbpStringLocalizerFactory.<>c__DisplayClass5_0.<Create>b__0(Type _) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 43
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Volo.Abp.Localization.AbpStringLocalizerFactory.Create(Type resourceType) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 41
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)



Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.Extensions.Localization.StringLocalizer`1[[Volo.Abp.UI.Navigation.Localization.Resource.AbpUiNavigationResource, Volo.Abp.UI.Navigation, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null]].
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Localization.IStringLocalizerFactory)' on type 'StringLocalizer`1'.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Volo.Abp.Localization.AbpStringLocalizerFactory.CreateStringLocalizerCacheItem(LocalizationResource resource) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 58
   at Volo.Abp.Localization.AbpStringLocalizerFactory.<>c__DisplayClass5_0.<Create>b__0(Type _) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 43
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Volo.Abp.Localization.AbpStringLocalizerFactory.Create(Type resourceType) in D:\Github\volo\abp\framework\src\Volo.Abp.Localization\Volo\Abp\Localization\AbpStringLocalizerFactory.cs:line 41
   at Microsoft.Extensions.Localization.StringLocalizer`1..ctor(IStringLocalizerFactory factory)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType) in d:\Github\volo\abp\framework\src\Volo.Abp.Autofac\Autofac\Extensions\DependencyInjection\AutofacServiceProvider.cs:line 71
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Volo.Abp.UI.Navigation.DefaultMenuContributor.Configure(MenuConfigurationContext context) in D:\Github\volo\abp\framework\src\Volo.Abp.UI.Navigation\Volo\Abp\Ui\Navigation\DefaultMenuContributor.cs:line 19
   at Volo.Abp.UI.Navigation.DefaultMenuContributor.ConfigureMenuAsync(MenuConfigurationContext context) in D:\Github\volo\abp\framework\src\Volo.Abp.UI.Navigation\Volo\Abp\Ui\Navigation\DefaultMenuContributor.cs:line 13
   at Volo.Abp.UI.Navigation.MenuManager.GetAsync(String name) in D:\Github\volo\abp\framework\src\Volo.Abp.UI.Navigation\Volo\Abp\Ui\Navigation\MenuManager.cs:line 33
   at Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton.Themes.Lepton.Components.Toolbar.UserMenu.UserMenuViewComponent.InvokeAsync() in d:\Github\volo\volo\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Themes\Lepton\Components\Toolbar\UserMenu\UserMenuViewComponent.cs:line 18
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, Object arguments) in d:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Widgets\Volo\Abp\AspNetCore\Mvc\UI\Widgets\AbpViewComponentHelper.cs:line 47
   at AspNetCore._Themes_Lepton_Components_Header_ToolBar_Default.ExecuteAsync() in D:\Github\volo\volo\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Themes\Lepton\Components\Header\ToolBar\Default.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, Object arguments) in d:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Widgets\Volo\Abp\AspNetCore\Mvc\UI\Widgets\AbpViewComponentHelper.cs:line 47
   at AspNetCore._Themes_Lepton_Components_Header_Default.ExecuteAsync() in D:\Github\volo\volo\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Themes\Lepton\Components\Header\Default.cshtml:line 21
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, Object arguments) in d:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Widgets\Volo\Abp\AspNetCore\Mvc\UI\Widgets\AbpViewComponentHelper.cs:line 47
   at AspNetCore._Themes_Lepton_Layouts_Application_Default.<ExecuteAsync>b__14_1() in D:\Github\volo\volo\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Themes\Lepton\Layouts\Application\Default.cshtml:line 78
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore._Themes_Lepton_Layouts_Application_Default.ExecuteAsync() in D:\Github\volo\volo\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Themes\Lepton\Layouts\Application\Default.cshtml:line 67
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Auditing\AbpAuditingMiddleware.cs:line 33
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\RequestLocalization\AbpRequestLocalizationMiddleware.cs:line 34
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\Github\volo\abp\framework\src\Volo.Abp.AspNetCore.MultiTenancy\Volo\Abp\AspNetCore\MultiTenancy\MultiTenancyMiddleware.cs:line 48
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by hikalkan** [comment]
Fixed this. It seems it is related to implementation of the ConcurrentDictionary: https://github.com/dotnet/runtime/issues/33221
