### ISSUE TITLE
IHttpClientProxy Authorization failed! User has not logged in error

### ISSUE THREAD

**Issue by Alexbits** [abpframework/abp#2934]
Hi there,

I'm trying to use IHttpClientProxy<IProfileAppService> in default not tiered MVC template. I get the Authorization failed! User has not logged in error. The user is authenticated using default (from the template) IdentityServer configuration and I can successfully use HttpClient to call Profile endpoint. I understand that something is going on with IdentityServer configuration. Is it possible to use IHttpClientProxy in not tiered architecture? I know I can use app service directly but I want to make UI more future proof and be able to move to tiered later without rewriting this code.

```
[16:38:16 INF] Executing handler method F460.Web.Pages.IndexModel.OnGet - ModelState is Valid
[16:38:16 INF] Start processing HTTP request GET https://localhost:44356/api/abp/api-definition
[16:38:16 INF] Sending HTTP request GET https://localhost:44356/api/abp/api-definition
[16:38:16 INF] Executed handler method OnGet, returned result .
[16:38:16 INF] Executing an implicit handler method - ModelState is Valid
[16:38:16 INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
[16:38:16 INF] Request starting HTTP/1.1 GET https://localhost:44356/api/abp/api-definition
[16:38:16 DBG] AuthenticationScheme: Bearer was not authenticated.
[16:38:16 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController.Get (Volo.Abp.AspNetCore.Mvc)'
[16:38:16 INF] Route matched with {action = "Get", controller = "AbpApiDefinition", area = "", page = ""}. Executing controller action with signature Volo.Abp.Http.Modeling.ApplicationApiDescriptionModel Get() on controller Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController (Volo.Abp.AspNetCore.Mvc).
[16:38:16 DBG] ActionApiDescriptionModel.Create: Test.GetAsync
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpServiceProxyScript.GetAllByModel
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpLanguages.SwitchByCultureAndUiCultureAndReturnUrl
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpApplicationConfigurationScript.Get
[16:38:16 DBG] ActionApiDescriptionModel.Create: Account.RegisterAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Account.LoginByLogin
[16:38:16 DBG] ActionApiDescriptionModel.Create: Account.Logout
[16:38:16 DBG] ActionApiDescriptionModel.Create: Account.CheckPasswordByLogin
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpApplicationConfiguration.GetAsync
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpApiDefinition.Get
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpTenant.FindTenantByNameAsyncByName
[16:38:16 DBG] ActionApiDescriptionModel.Create: AbpTenant.FindTenantByIdAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: Features.GetAsyncByProviderNameAndProviderKey
[16:38:16 DBG] ActionApiDescriptionModel.Create: Features.UpdateAsyncByProviderNameAndProviderKeyAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityRole.GetListAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityRole.GetAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityRole.CreateAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityRole.UpdateAsyncByIdAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityRole.DeleteAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.GetAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.GetListAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.CreateAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.UpdateAsyncByIdAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.DeleteAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.GetRolesAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.UpdateRolesAsyncByIdAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.FindByUsernameAsyncByUsername
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUser.FindByEmailAsyncByEmail
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUserLookup.FindByIdAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: IdentityUserLookup.FindByUserNameAsyncByUserName
[16:38:16 DBG] ActionApiDescriptionModel.Create: Profile.GetAsync
[16:38:16 DBG] ActionApiDescriptionModel.Create: Profile.UpdateAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Profile.ChangePasswordAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Permissions.GetAsyncByProviderNameAndProviderKey
[16:38:16 DBG] ActionApiDescriptionModel.Create: Permissions.UpdateAsyncByProviderNameAndProviderKeyAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.GetAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.GetListAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.CreateAsyncByInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.UpdateAsyncByIdAndInput
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.DeleteAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.GetDefaultConnectionStringAsyncById
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.UpdateDefaultConnectionStringAsyncByIdAndDefaultConnectionString
[16:38:16 DBG] ActionApiDescriptionModel.Create: Tenant.DeleteDefaultConnectionStringAsyncById
[16:38:16 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.Modeling.ApplicationApiDescriptionModel'.
[16:38:17 INF] Executed action Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController.Get (Volo.Abp.AspNetCore.Mvc) in 362.3097ms
[16:38:17 INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController.Get (Volo.Abp.AspNetCore.Mvc)'
[16:38:17 INF] Received HTTP response after 667.7812ms - OK
[16:38:17 INF] End processing HTTP request after 698.4369ms - OK
[16:38:17 INF] Request finished in 473.2386ms 200 application/json; charset=utf-8
[16:38:17 INF] Start processing HTTP request GET https://localhost:44356/api/identity/my-profile?api-version=1.0
[16:38:17 INF] Sending HTTP request GET https://localhost:44356/api/identity/my-profile?api-version=1.0
[16:38:17 INF] Request starting HTTP/1.1 GET https://localhost:44356/api/identity/my-profile?api-version=1.0
[16:38:17 DBG] AuthenticationScheme: Bearer was not authenticated.
[16:38:17 INF] Executing endpoint 'Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi)'
[16:38:17 INF] Route matched with {area = "identity", controller = "Profile", action = "Get", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.ProfileDto] GetAsync() on controller Volo.Abp.Identity.ProfileController (Volo.Abp.Identity.HttpApi).
[16:38:20 WRN] ---------- RemoteServiceErrorInfo ----------
[16:38:20 INF] Entity Framework Core 3.1.0 initialized 'BackgroundJobsDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
[16:38:20 WRN] {
  "code": null,
  "message": "Authorization failed! User has not logged in.",
  "details": null,
  "validationErrors": null
}
[16:38:20 INF] Executed DbCommand (7ms) [Parameters=[@__p_1='?' (DbType = Int32), @__now_0='?' (DbType = DateTime2)], CommandType='Text', CommandTimeout='30']
SELECT TOP(@__p_1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[ExtraProperties], [a].[IsAbandoned], [a].[JobArgs], [a].[JobName], [a].[LastTryTime], [a].[NextTryTime], [a].[Priority], [a].[TryCount]
FROM [AbpBackgroundJobs] AS [a]
WHERE ([a].[IsAbandoned] <> CAST(1 AS bit)) AND ([a].[NextTryTime] <= @__now_0)
ORDER BY [a].[Priority] DESC, [a].[TryCount], [a].[NextTryTime]
[16:38:20 WRN] Authorization failed! User has not logged in.
Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! User has not logged in.
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(IAuthorizeData authorizationAttribute)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[16:38:20 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[16:38:20 INF] Executed action Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi) in 2971.6268ms
[16:38:20 INF] Received HTTP response after 3033.8172ms - Unauthorized
[16:38:20 INF] Executed endpoint 'Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi)'
[16:38:20 INF] Request finished in 3019.5605ms 401 application/json; charset=utf-8
[16:38:20 INF] End processing HTTP request after 3069.1865ms - Unauthorize
```

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by Alexbits** [comment]
Hi @maliming,

1. Get the default not tiered MVC project 
2. Reference {ProjectName}.HttpApi.Client in {ProjectName}.Web project
3. Add the depenecy to {ProjectName}HttpApiClientModule in {ProjectName}.Web project module
```c#
[DependsOn(
        typeof({ProjectName}HttpApiModule),
        typeof({ProjectName}HttpApiClientModule),
        typeof({ProjectName}ApplicationModule),
        typeof({ProjectName}EntityFrameworkCoreDbMigrationsModule),
        typeof(AbpAutofacModule),
        typeof(AbpIdentityWebModule),
        typeof(AbpAccountWebIdentityServerModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAspNetCoreAuthenticationJwtBearerModule),
        typeof(AbpTenantManagementWebModule),
        typeof(AbpAspNetCoreSerilogModule)
        )]
```
4. Add RemoteService configuration to appsettings.json in {ProjectName}.Web project
```json  "RemoteServices": {
    "Default": {
      "BaseUrl": "https://localhost:44356/"
    }
  }
```
5. Add code below to Index.cshtml.cs in {ProjectName}.Web project
```c#
public class IndexModel : {ProjectName}PageModel
    {
        private readonly IHttpClientProxy<IProfileAppService> _profileService;

        public IndexModel(IHttpClientProxy<IProfileAppService> profileService)
        {
            _profileService = profileService;
        }
        public async Task OnGetAsync()
        {
            if (CurrentUser.IsAuthenticated)
            {
                var profile = await _profileService.Service.GetAsync();

                Console.WriteLine(profile);
            }
        }
    }
```
6. Register user and log in

I forgot to mention I can successfully call my own implementation of app service with IHttpClientProxy located in {ProjectName}.Application/{ProjectName}.Application.Contracts and registered by AddHttpClientProxies in {ProjectName}.HttpApi.Client.

Thank you

**Comment by maliming** [comment]
hi @Alexbits 

Why would you use [Dynamic C# API Clients](https://docs.abp.io/en/abp/latest/AspNetCore/Dynamic-CSharp-API-Clients) in a monolithic application?

**Comment by Alexbits** [comment]
Hey @maliming  I would like to split it later. I read the docs and as far as I understand it, I can use an app service interface directly and it will be injected as IHttpClientProxy when in tiered architecture. 
But I wanted to test the dynamic proxy functionality explicitly to understand how well it works.

Also, I use server side Blazor for UI and I get problems with a service utilizing a SignInManager. When I call it directly I get the issue described here [https://github.com/dotnet/aspnetcore/issues/13601]. But it works when I call it with IHttpClientProxy so it's useful in this case.

**Comment by maliming** [comment]
The principle of `Dynamic C # API Clients` is to intercept the invocation of the application service interface method, send the http request according to the convention of the interface method, and process the http response as the method return Dto.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client/Microsoft/Extensions/DependencyInjection/ServiceCollectionDynamicHttpClientProxyExtensions.cs#L167

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs#L119

**Comment by Alexbits** [comment]
Yes, I understand this. I'm not sure why I get the "Not Logged In" error when I call ABP's IProfileAppService and I don't get this exception when calling my own app service. The exception comes from [MethodInvocationAuthorizationService](https://github.com/abpframework/abp/blob/1a622bc50fbd9b554f61078d5eeafa9def3216e3/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/MethodInvocationAuthorizationService.cs)
```c#
protected async Task CheckAsync(IAuthorizeData authorizationAttribute)
        {
            if (authorizationAttribute.Policy == null)
            {
                //TODO: Can we find a better, unified, way of checking if current request has been authenticated
                if (!_currentUser.IsAuthenticated && !_currentClient.IsAuthenticated)
                {
                    throw new AbpAuthorizationException("Authorization failed! User has not logged in.");
                }
            }
            else
            {
                await _authorizationService.CheckAsync(authorizationAttribute.Policy);
            }

            //TODO: What about roles and other props?
        }
```

And from  ```c# (!_currentUser.IsAuthenticated && !_currentClient.IsAuthenticated)``` it looks like both of them are false. But in my case in ICurrentUser.IsAuthenticated is ```true``` in the page context in same time.
