### ISSUE TITLE
Error running commercial edition in docker

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#2966]
Hi. I'm trying new ABP project in docker.

1. I have downoladed clean project with included indentity service, build it and test it locally without troubles.
2. Then i create docker image for it and deploy it into docker container.
3. Container starter without errors and i can access swagger page.

On client side i use angular. 

4. When log in, client send requests for openid-configuration, jwks and token. Token is returned without error.
5. Then client application sends request for application-configuration. Token is in header.
6. In result there are empty grantedpolicies and currentUser.isAuthenticated is false.
Of course there is no items in menu.

So i look into server loq. There is an error:

```
2020-03-03 11:59:32.955 +00:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Did not 
match: validationParameters.ValidIssuer: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' or validationParameters.ValidIssuers: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateIssuer(String issuer, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

```
I think webAPI cannot connect to "identity service".
Probably i need to make changes in appsettings.json file, but don't know how.

Please advice.

Regards.

Edvin

**Comment by hikalkan** [comment]
Can you move your question to https://support.abp.io

We don't want to make open source followers busy with the commercial side questions :)
Thank you for your understanding.

**Comment by sebitsi** [comment]
@hikalkan 
Basically this is not only commercial edition problem.
Your link points me to right direction. 
After enabling PII visibility i noticed that i must change server configuration (value of AuthServer/Auhority key).

Thanks
