### ISSUE TITLE
Background worker Autofac instance issue

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2998]
https://github.com/abpframework/abp/pull/2973#issuecomment-595636740

What is still missing, that DI cannot inject business logic class code (which derives from ITransientDependency)?

**Comment by liangshiw** [comment]
@leonkosak  Please provide a complete error log

**Comment by leonkosak** [comment]
xxxDomainModule.cs code:

```
[DependsOn(
        typeof(DeviceDataImportProcessingDomainSharedModule),

        typeof(Database.Postgres.DeviceDataImport.DeviceDataImportDomainModule),
        typeof(Database.Postgres.Common.CommonDomainModule),
        typeof(Database.Postgres.CommonCache.CommonCacheDomainModule),

        typeof(AbpBackgroundWorkersModule)
        )]
    public class DeviceDataImportProcessingDomainModule : AbpModule
    {
        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            context.ServiceProvider
                .GetRequiredService<IBackgroundWorkerManager>()
                .Add(
                    context.ServiceProvider.GetRequiredService<AcceptedMessageProcessingStatusCreatorBackgroundWorker>()
                );
        }
    }
```

Worker code:

```
public class AcceptedMessageProcessingStatusCreatorBackgroundWorker : AsyncPeriodicBackgroundWorkerBase, ITransientDependency
    {
        private readonly AcceptedMessageImportLogic _acceptedMessageImportLogic;

        public AcceptedMessageProcessingStatusCreatorBackgroundWorker(
            AbpTimer timer, IServiceScopeFactory serviceScopeFactory,
            AcceptedMessageImportLogic acceptedMessageImportLogic) : base(timer, serviceScopeFactory)
        {
            timer.Period = 3000;
            _acceptedMessageImportLogic = acceptedMessageImportLogic;
        }

        protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
        {
            await _acceptedMessageImportLogic.StartImportAcceptedMessages();
        }
    }
```

Code logic class (part - constructor, entrance)

```
public class AcceptedMessageImportLogic : ITransientDependency
    {
        private readonly IUnitOfWorkManager _unitOfWorkManager;

        private readonly ITenantRepository _tenantRepository;
        private readonly ICurrentTenant _currentTenant;

        private readonly IRepository<AcceptedMessage> _acceptedMessageRepository;
        private readonly IRepository<AcceptedMessageProcessingStatus> _acceptedMessageProcessingStatusRepository;

        public AcceptedMessageImportLogic(
            IUnitOfWorkManager unitOfWorkManager,
            ITenantRepository tenantRepository,
            ICurrentTenant currentTenant,
            IRepository<AcceptedMessage> acceptedMessageRepository,
            IRepository<AcceptedMessageProcessingStatus> acceptedMessageProcessingStatusRepository)
        {
            _unitOfWorkManager = unitOfWorkManager;
            _tenantRepository = tenantRepository;
            _currentTenant = currentTenant;
            _acceptedMessageRepository = acceptedMessageRepository;
            _acceptedMessageProcessingStatusRepository = acceptedMessageProcessingStatusRepository;
        }

        [UnitOfWork(IsDisabled = true)]
        public async Task StartImportAcceptedMessages()
        {
            var tenants = await _tenantRepository.GetListAsync();

            foreach (var tenant in tenants)
            {
                using (var uow = _unitOfWorkManager.Begin(requiresNew: true))
                {
                    await StartImportAcceptedMessagesForTenant(tenant);
                    await uow.CompleteAsync();
                }
            }
        }
```

**Comment by leonkosak** [comment]
abp v2.2.0

An exception was thrown while activating Thynkr.Postgres.DeviceDataImportProcessing.ImportProcessing.AcceptedMessageProcessingStatusCreatorBackgroundWorker -> Castle.Proxies.AcceptedMessageImportLogicProxy.

   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Thynkr.Postgres.DeviceDataImportProcessing.DeviceDataImportProcessingDomainModule.OnApplicationInitialization(ApplicationInitializationContext context) in C:\_MTGS\Thynkr.IO\Modules\DeviceDataImportProcessingPostgres\src\Thynkr.Postgres.DeviceDataImportProcessing.Domain\DeviceDataImportProcessingDomainModule.cs:line 22
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.Initialize(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app)
   at Thynkr.Postgres.DeviceDataImportProcessing.Startup.Configure(IApplicationBuilder app) in C:\_MTGS\Thynkr.IO\Modules\DeviceDataImportProcessingPostgres\host\Thynkr.Postgres.DeviceDataImportProcessing.Web.Unified\Startup.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.AcceptedMessageImportLogicProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.TenantManagement.ITenantRepository tenantRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Uow.IUnitOfWorkManager, Volo.Abp.TenantManagement.ITenantRepository, Volo.Abp.MultiTenancy.ICurrentTenant, Volo.Abp.Domain.Repositories.IRepository`1[Thynkr.Database.Postgres.DeviceDataImport.Models.AcceptedMessage], Volo.Abp.Domain.Repositories.IRepository`1[Thynkr.Database.Postgres.DeviceDataImport.Models.AcceptedMessageProcessingStatus])'.

**Comment by leonkosak** [comment]
The worker is currently started from "host" (business logic of worker is in a module) with a project .Web.Unified.

**Comment by liangshiw** [comment]
I'm trying to reproduce it

**Comment by liangshiw** [comment]
```public class AcceptedMessageProcessingStatusCreatorBackgroundWorker : AsyncPeriodicBackgroundWorkerBase, ITransientDependency```

Remove `ITransientDependency` Background worker should be singleton.  Then it will work

**Comment by leonkosak** [comment]
Still...

None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.AcceptedMessageImportLogicProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.TenantManagement.ITenantRepository tenantRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Uow.IUnitOfWorkManager, Volo.Abp.TenantManagement.ITenantRepository, Volo.Abp.MultiTenancy.ICurrentTenant, Volo.Abp.Domain.Repositories.IRepository`1[Thynkr.Database.Postgres.DeviceDataImport.Models.AcceptedMessage], Volo.Abp.Domain.Repositories.IRepository`1[Thynkr.Database.Postgres.DeviceDataImport.Models.AcceptedMessageProcessingStatus])'.

**Comment by liangshiw** [comment]
**Cannot resolve parameter 'Volo.Abp.TenantManagement.ITenantRepository tenantRepository**
Try add `typeof(AbpTenantManagementDomainModule)` to your module class

**Comment by leonkosak** [comment]
I tried, but the error remains the same.

**Comment by liangshiw** [comment]
I can't reproduce this issue.
Create project using CLI to reproduce this issue and upload to github repository

**Comment by leonkosak** [comment]
Sent via WeTransfer on your @outlook.com email address.

**Comment by leonkosak** [comment]
I can confirm, that only ITenantRepository is problematic (and ITenantManager also). Without this repository/manager, the background worker starts without problems.
But I need all tenants (that bg worker goes through all tenant databases). Is maybe another approach on how to get all tenants?

**Comment by liangshiw** [comment]
Add `AbpFeatureManagementEntityFrameworkCoreModule` dependency to the module class of the `.EntityFrameworkCore` project.
Since you need to acquire tenants, why remove the dependency on the tenant management module in the solution project  : )

**Comment by leonkosak** [comment]
I didn't remove anything from references (just adding). :)
The module vas generated vial CLI (v2.1.1) with parameter _-t module-pro_.

Now, it works. :)

P.S.: I added Abp**Tenant**ManagementEntityFrameworkCoreModule (not FeatureManagement module).
