### ISSUE TITLE
CLI template creation versioning problem

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3013]
CLI should get the versions of the NuGet packages from common.props while replacing local references by NuGet packages while creating a new template.

If already working like that, we should understand the reason behind https://github.com/abpframework/abp/issues/3011

**Comment by mlwxxx** [comment]
```
PS > abp new Acme.BookStore -u angular
[16:58:50 INF] ABP CLI (https://abp.io)
[16:58:51 INF] Version 2.2.1 (Stable channel)
[16:58:52 INF] Creating your project...
[16:58:52 INF] Project name: Acme.BookStore
[16:58:52 INF] UI Framework: Angular
[16:58:52 INF] Mobile App: ReactNative
[16:58:52 INF] Output folder: 
[16:58:56 ERR] Remote server returns '500-Internal Server Error'. Message: An internal error occurred during your request!
System.Exception: Remote server returns '500-Internal Server Error'. Message: An internal error occurred during your request!
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 44
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 111
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 51
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 102
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55
```
wating....come on!
cheer for you!
