### ISSUE TITLE
Cannot create new application with `abp` cli

### ISSUE THREAD

**Issue by joshes** [abpframework/abp#3014]
I'm unable to create a new application with `abp` cli.

Example:

```
$ abp new AbpExample --tiered
[12:41:56 INF] ABP CLI (https://abp.io)
[12:41:56 INF] Version 2.2.1 (Stable channel)
[12:41:57 INF] Creating your project...
[12:41:57 INF] Project name: AbpExample
[12:41:57 INF] Mobile App: ReactNative
[12:41:57 INF] Output folder: /Users/josh/Work/weltel/AbpExample
[12:41:58 ERR] Remote server returns '500-Internal Server Error'. Message: An internal error occurred during your request!
System.Exception: Remote server returns '500-Internal Server Error'. Message: An internal error occurred during your request!
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 44
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 111
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 51
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 102
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55
```

The backend API servers appear offline or misconfigured as I cannot create an application via the UI either. 

I've seen this often over the last couple of days, it may be interesting to see about adding an offline option if at all possible.

**Comment by cotur** [comment]
Hi @joshes, 

I just tried that and works on me. 
Do you still get 500 Internal Server Err?

**Comment by joshes** [comment]
Hi @cotur. It does seem resolved now, but have noticed the docs/api have been very slow over the last few days with entire times where nothing but 500's are returning.

Happy to close the issue, but would like to raise the issue of the docs/api being unstable which is a bit out of band for tracking here I suppose.

**Comment by joshes** [comment]
Just to put a timestamp on it, the docs are offline presently with intermittent 500's
