### ISSUE TITLE
currentUser.Id != null

### ISSUE THREAD

**Issue by Maple512** [abpframework/abp#3165]
when i run `IProfileAppService.GetAsync()` in `ConsoleClientDemo.ClientDemoService.cs`,i get 'currentUser.Id != null'

**Comment by Maple512** [comment]
or not in this way?

**Comment by hikalkan** [comment]
Please write the full stack trace and other details.

IProfileAppService.GetAsync should be called only if the user has been authenticated.

**Comment by Maple512** [comment]
2020-03-17 21:32:28.294 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost:63568/api/identity/my-profile?api-version=1.0  0
2020-03-17 21:32:28.297 +08:00 [INF] Successfully validated the token.
2020-03-17 21:32:28.297 +08:00 [DBG] AuthenticationScheme: Bearer was successfully authenticated.
2020-03-17 21:32:28.299 +08:00 [INF] Executing endpoint 'Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi)'
2020-03-17 21:32:28.300 +08:00 [INF] Route matched with {area = "identity", controller = "Profile", action = "Get"}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.ProfileDto] GetAsync() on controller Volo.Abp.Identity.ProfileController (Volo.Abp.Identity.HttpApi).
2020-03-17 21:32:30.761 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
2020-03-17 21:32:30.761 +08:00 [ERR] {
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "validationErrors": null
}
2020-03-17 21:32:30.761 +08:00 [ERR] Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Volo.Abp.Users.CurrentUserExtensions.GetId(ICurrentUser currentUser) in F:\Documents\Git\abp\framework\src\Volo.Abp.Security\Volo\Abp\Users\CurrentUserExtensions.cs:line 31
   at Volo.Abp.Identity.ProfileAppService.GetAsync() in F:\Documents\Git\abp\modules\identity\src\Volo.Abp.Identity.Application\Volo\Abp\Identity\ProfileAppService.cs:line 22
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 24
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in F:\Documents\Git\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ValidationInterceptor.cs:line 19
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAsyncAbpInterceptorAdapter.cs:line 29
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 24
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in F:\Documents\Git\abp\framework\src\Volo.Abp.Authorization\Volo\Abp\Authorization\AuthorizationInterceptor.cs:line 19
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAsyncAbpInterceptorAdapter.cs:line 29
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 24
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in F:\Documents\Git\abp\framework\src\Volo.Abp.Auditing\Volo\Abp\Auditing\AuditingInterceptor.cs:line 33
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAsyncAbpInterceptorAdapter.cs:line 29
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 24
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in F:\Documents\Git\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 31
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in F:\Documents\Git\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAsyncAbpInterceptorAdapter.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-03-17 21:32:30.763 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2020-03-17 21:32:30.763 +08:00 [INF] Executed action Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi) in 2463.4153ms
2020-03-17 21:32:30.764 +08:00 [INF] Executed endpoint 'Volo.Abp.Identity.ProfileController.GetAsync (Volo.Abp.Identity.HttpApi)'

![code](https://user-images.githubusercontent.com/34236341/76861645-e1734600-6897-11ea-9552-9223a035b3bc.png)

**Comment by Maple512** [comment]
Demo: `abp.samples.MicroserviceDemo.ConsoleClientDemo.ClientDemoService`

**Comment by hikalkan** [comment]
@maliming can you test this?

**Comment by maliming** [comment]
ok I will test it.

**Comment by maliming** [comment]
hi @Maple512 

Try changing the configuration of `IdentityClients`.
https://github.com/abpframework/abp/blob/ca246162efed31c5df93f931c1030873aebe8a1c/samples/MicroserviceDemo/applications/ConsoleClientDemo/appsettings.json#L7-L14

```json
  "IdentityClients": {
    "Default": {
      "GrantType": "password",
      "ClientId": "console-client-demo",
      "ClientSecret": "1q2w3e*",
      "Authority": "http://localhost:64999",
      "Scope": "InternalGateway IdentityService ProductService TenantManagementService",
      "UserName": "admin",
      "UserPassword": "1q2w3E*"
    }
```

**Comment by Maple512** [comment]
ok, thanks, i'll try it
