### ISSUE TITLE
Cli use of local templates crash while fail to access abp.io site 

### ISSUE THREAD

**Issue by sam0817** [abpframework/abp#3323]
I have trouble creating template while abp.io is NOT available to access. so i create a local source template. still not working while abp.io unavailable.

here is error message
```
System.Exception: Remote server returns '502-Bad Gateway'. 
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 44
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetLatestSourceCodeVersionAsync(String name, String type) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 113
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 51
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 50
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 102
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\ABP_Framework_Release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55
```

if it is possible to work without abp.io access while using local template?

thanks

**Comment by liangshiw** [comment]
The CLI checks the CLI version before using the command. So keeping abp.io always online is the best way

**Comment by zhk0603** [comment]
I cannot access abp.io
Error 502 Bad gateway

**Comment by maliming** [comment]
@zhk0603  We're checking abp.io problems.

**Comment by sam0817** [comment]
> The CLI checks the CLI version before using the command. So keeping abp.io always online is the best way

Or if it is possible to skip the check while abp.io is not available. Somehow abp.io crash many times.
Maybe while abp.io is not available, then using cli version as default.

thanks for your input.

**Comment by liangshiw** [comment]
@maliming I will try to implement it
