### ISSUE TITLE
DbMigrator gives table doesn't exist for lowercase table name

### ISSUE THREAD

**Issue by ocelikk** [abpframework/abp#3583]
I followed the instruction given [here](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL) to use mysql. Then made table names lowercase with the code below in OnModelCreating method of MyDbContext. 

`
foreach (var entityType in builder.Model.GetEntityTypes().ToList())
            {
                var tableName = entityType.GetTableName();
                entityType.SetTableName(tableName.ToLower());
            }
` 
Migrations are ok!
But .DbMigrator project still queries for abptables with its first letter in uppercase. I couldn't find anything about how to make table names lower case so asking here. Is there anything i am missing to do? 

2020-04-10 17:45:24.720 +03:00 [INF] Started database migrations...
2020-04-10 17:45:24.744 +03:00 [INF] Migrating host database schema...
2020-04-10 17:45:29.949 +03:00 [INF] Executing host database seed...
2020-04-10 17:45:34.382 +03:00 [ERR] Failed executing DbCommand (31ms) [Parameters=[@__name_0='?' (Size = 128), @__providerName_1='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT `s`.`Id`, `s`.`Name`, `s`.`ProviderKey`, `s`.`ProviderName`, `s`.`Value`
FROM `Settings` AS `s`
WHERE ((`s`.`Name` = @__name_0) AND (`s`.`ProviderName` = @__providerName_1)) AND `s`.`ProviderKey` IS NULL
LIMIT 1
2020-04-10 17:45:34.461 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext'.
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Mydb.Settings' doesn't exist
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Mydb.Settings' doesn't exist
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 774
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

**Comment by liangshiw** [comment]
Hi @ocelikk  Try to add to the `Configure<YourProject>` method of the `<YourProject>DbContextModelCreatingExtensions` class.

**Comment by ocelikk** [comment]
` 
public static class MyDbContextModelCreatingExtensions
{
public static void ConfigureMy(this ModelBuilder builder)
{
            Check.NotNull(builder, nameof(builder));
            /* Configure your own tables/entities inside here */
            // it didnt matter moving lower case making loop here.
}
}
`

And  dbcontext;

`
public class MyMigrationsDbContext : AbpDbContext<MyMigrationsDbContext>
{
         public MyMigrationsDbContext(DbContextOptions<MyMigrationsDbContext> options) : base(options)
         {    }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            /* Include modules to your migration db context */

            builder.ConfigurePermissionManagement();
            builder.ConfigureSettingManagement();
            builder.ConfigureBackgroundJobs();
            builder.ConfigureAuditLogging();
            builder.ConfigureIdentity();
            builder.ConfigureIdentityServer(options =>
            {
                options.DatabaseProvider = EfCoreDatabaseProvider.MySql;
            });
            builder.ConfigureFeatureManagement();
            builder.ConfigureTenantManagement();

            //builder.ConfigureCasinoOnline();
            foreach (var entityType in builder.Model.GetEntityTypes().ToList())
            {
                var tableName = entityType.GetTableName();
                entityType.SetTableName(tableName.ToLower());
            }
        }
}
`

**Comment by liangshiw** [comment]
It works for me.

![image](https://user-images.githubusercontent.com/16813853/79123347-8cf6b400-7dcc-11ea-883f-f5d55f11cd5a.png)

Do you mean that the table name in the generated SQL is still uppercase? Translating expressions to SQL is a feature of ef core, it has nothing to do with ABP. For different drivers, EF Core will generate different SQL.

**Comment by liangshiw** [comment]
Unfortunately, that will not work. See https://github.com/abpframework/abp/issues/2131#issuecomment-563354065

Maybe you can consider another way: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
