### ISSUE TITLE
Autofac.Core.Registration.ComponentNotRegisteredException

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#3687]
**Autofac.Core.Registration.ComponentNotRegisteredException**: The requested service '**Elsa.Dashboard.Areas.Elsa.Controllers.HomeController**' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by maliming** [comment]
Please provide the abp version and steps to reproduce the problem.
