### ISSUE TITLE
Cannot find module '@volo/abp.ng.text-template-management'

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#3865]
***abp version:2.7.0***
***Steps 1***
1. Create a new project:`abp new ProName -t app --ui angular`
2. run angular pro
```
yarn & yarn start
```
***Error 1***
```
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:65165:24)
    at D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (D:\git\Demo\Demo.Abp\angular\node_modules\typescript\lib\typescript.js:98688:20)
```
![image](https://user-images.githubusercontent.com/8120385/81364739-0017ef80-9119-11ea-9ec2-c38b261c5cc8.png)

***Steps 2***
1. Create a new project:`abp new ProName -t app-pro --ui angular`
2. run angular pro
```
yarn & yarn start
```
***Error 2***
```
ERROR in src/app/app-routing.module.ts:56:14 - error TS2307: Cannot find module '@volo/abp.ng.text-template-management'.

56       import('@volo/abp.ng.text-template-management').then((m) => m.TextTemplateManagementModule),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:15:52 - error TS2307: Cannot find module '@volo/abp.ng.text-template-management.config'.

15 import { TextTemplateManagementConfigModule } from '@volo/abp.ng.text-template-management.config';
```
![image](https://user-images.githubusercontent.com/8120385/81364874-4b320280-9119-11ea-95b8-288a8088dbbc.png)

**Comment by ninomartini** [comment]
I resolved the same issue by adding the missing package.

`yarn add @volo/abp.ng.text-template-management --tilde`

**Comment by SmallShrimp** [comment]
Thank you for your reply @ninomartini .
I executed the command `yarn add @volo/abp.ng.text-template-management --tilde`  , then i get the error info:
`ERROR in TypeError: Cannot read property 'flags' of undefined`.

**Comment by leonkosak** [comment]
@SmallShrimp, You'll have to wait till v2.7.1, because I had the same issue not too long ago.
Probably they forgot publish some packages (dependencies).

**Comment by SmallShrimp** [comment]
thanks

**Comment by mlwxxx** [comment]
I had the same issue too

**Comment by mlwxxx** [comment]
I got the same error message!!!

**Comment by AkinSabriCam** [comment]
you need to fallow this steps.
Need to fallow this steps

**1**. Add this into package.json:
>   "resolutions": {
>     "@angular/animations": "9.1.4",
>     "@angular/common": "9.1.4",
>     "@angular/compiler": "9.1.4",
>     "@angular/core": "9.1.4",
>     "@angular/forms": "9.1.4",
>     "@angular/platform-browser": "9.1.4",
>     "@angular/platform-browser-dynamic": "9.1.4",
>     "@angular/router": "9.1.4",
>     "@angular/cli": "9.1.4",
>     "@angular/compiler-cli": "9.1.4",
>     "@angular/language-service": "9.1.4"
>   }
>

**2**. Delete yarn.lock or package-lock.json

**3**.  run `yarn` command in terminal
