### ISSUE TITLE
[question]how to add api to Package References Module

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#3871]
I am using the `Volo.Abp.Identity` Module with  Package References 

There are a few interfaces provided by him. I want to add some by myself

I do some thing like below

``` Csharp
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserController))]
    public class AppUserController : IdentityUserController, IUserAppService
    {
        private IUserAppService _userAppService;

        public AppUserController(IIdentityUserAppService userAppService) : base(userAppService)
        {
            IUserAppService
               _userAppService = userAppService as IUserAppService;
        }

        [HttpPost]
        [Route("getListByIds")]
        public virtual async Task<List<IdentityUserDto>> GetListByIdAsync(IEnumerable<Guid> ids)
        {
            return await _userAppService.GetListByIdAsync(ids);
        }
    }
```

but it can not works. 

is there anyway to reuse this  api Controller  `IdentityUserController`?

**Comment by hikalkan** [comment]
AppUserController can not replace both IIdentityUserAppService and IdentityUserController. If you do that, it injects itself by `IIdentityUserAppService userAppService` injection.

Replace them independently. See:

* https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-an-application-service
* https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#overriding-other-classes

**Comment by xyfy** [comment]
thank you for your answer,but i still can not make it works.

I want to add more  API into `IdentityUserController`.

Do you mean that I should re-implement the `IIdentityUserAppService` and `IdentityUserController` 
independently?

or `IdentityUserAppService` and `IdentityUserController` 

Is there any example code  if I want add a api called `GetListByIdAsync`  to `IdentityUserController`?

I try the code below ,but it not works.

``` C#
    public interface IUserAppService: IApplicationService
    {
        Task<List<IdentityUserDto>> GetListByIdAsync(IEnumerable<Guid> ids);
    }
```
```  C#
 [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserAppService))]
    public class UserAppService : IdentityUserAppService, IUserAppService
    {
        public UserAppService(IdentityUserManager userManager, IIdentityUserRepository userRepository) 
            : base(userManager, userRepository)
        {
......
        }

        public async Task<List<IdentityUserDto>> GetListByIdAsync(IEnumerable<Guid> ids)
        {
         ......
        }
```
``` c#
 [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IdentityUserController))]
    public class AppUserController : IdentityUserController
    {
        private IUserAppService _userAppService;

        public AppUserController(IIdentityUserAppService userAppService) : base(userAppService)
        {
            _userAppService = userAppService as IUserAppService;
        }

        [HttpPost]
        [Route("getListByIds")]
        public virtual async Task<List<IdentityUserDto>> GetListByIdAsync(IEnumerable<Guid> ids)
        {
            return await _userAppService.GetListByIdAsync(ids);
        }
    }
```

I just got an error info 

Conflicting method/path combination "GET api/identity/users/{id}" for actions - Yun.IdentityService.AppUserController.GetAsync (Yun.IdentityService.Host),Volo.Abp.Identity.IdentityUserController.GetAsync (Volo.Abp.Identity.HttpApi). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround

**Comment by liangshiw** [comment]
@xyfy 

Add there attributes to your AppUserController.

```csharp
[RemoteService(Name = IdentityRemoteServiceConsts.RemoteServiceName)]
[Area("identity")]
[ControllerName("User")]
[Route("api/identity/users")]
```

**Comment by xyfy** [comment]
Whether or not I remove the code below,  add the attributes to `AppUserController` has no effect
``` C#
 [Dependency(ReplaceServices = true)]
 [ExposeServices(typeof(IdentityUserController))]
```
It got the same error

**Comment by xyfy** [comment]
Looks interesting， I am using the microservice ,  the `gateway` don't get this err.but only found in `XXX.Host`

**Comment by xyfy** [comment]
it is the swagger's error
and it can be fixed by two way
- just use one 
``` c#
   context.Services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo { Title = "Yun.Identity Service API", Version = "v1" });
                options.DocInclusionPredicate((docName, description) => true);
                options.CustomSchemaIds(type => type.FullName);
                options.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());//or comment this line and uncomment the region `Override` in AppUserController
            });
```

- override all api and change the route add #blash
``` c#
   //#region Override
        //[HttpGet]
        //[Route("{id}#blash1")]
        //public override Task<IdentityUserDto> GetAsync(Guid id)
        //{
        //    return base.GetAsync(id);
        //}
        //[HttpPost]
        //[Route("#blash1")]
        //public override Task<IdentityUserDto> CreateAsync(IdentityUserCreateDto input)
        //{
        //    return base.CreateAsync(input);
        //}

        //[HttpGet]
        //[Route("#blash1")]
        //public override Task<PagedResultDto<IdentityUserDto>> GetListAsync(GetIdentityUsersInput input)
        //{
        //    return base.GetListAsync(input);
        //}
        //[HttpDelete]
        //[Route("{id}#blash1")]
        //public override Task DeleteAsync(Guid id)
        //{
        //    return base.DeleteAsync(id);
        //}
        //[HttpGet]
        //[Route("{id}/roles#blash1")]
        //public override Task<ListResultDto<IdentityRoleDto>> GetRolesAsync(Guid id)
        //{
        //    return base.GetRolesAsync(id);
        //}
        //[HttpPut]
        //[Route("{id}#blash1")]
        //public override Task<IdentityUserDto> UpdateAsync(Guid id, IdentityUserUpdateDto input)
        //{
        //    return base.UpdateAsync(id, input);
        //}
        //[HttpPut]
        //[Route("{id}/roles#blash1")]
        //public override Task UpdateRolesAsync(Guid id, IdentityUserUpdateRolesDto input)
        //{
        //    return base.UpdateRolesAsync(id, input);
        //}
        //[HttpGet]
        //[Route("by-email/{email}#blash1")]
        //public override Task<IdentityUserDto> FindByEmailAsync(string email)
        //{
        //    return base.FindByEmailAsync(email);
        //}
        //[HttpGet]
        //[Route("by-username/{userName}#blash1")]
        //public override Task<IdentityUserDto> FindByUsernameAsync(string username)
        //{
        //    return base.FindByUsernameAsync(username);
        //}
        //#endregion
```

**Comment by xyfy** [comment]
I got a new error when I try to call this added api 
```c#
[14:29:15 INF] Executing endpoint 'Yun.Module.Identity.AppUserController.GetListByIdAsync (Yun.Module.Identity.HttpApi)'[14:29:15 INF] Route matched with {area = "identity", controller = "User", action = "GetListById"}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Collections.Generic.List`1[Volo.Abp.Identity.IdentityUserDto]] GetListByIdAsync(System.Collections.Generic.IEnumerable`1[System.Guid]) on controller Yun.Module.Identity.AppUserController (Yun.Module.Identity.HttpApi).
[14:29:15 ERR] ---------- RemoteServiceErrorInfo ----------
[14:29:15 ERR] {
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "validationErrors": null
}
[14:29:15 ERR] The requested service 'Yun.Module.Identity.AppUserController' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Yun.Module.Identity.AppUserController' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[14:29:15 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[14:29:15 INF] Executed action Yun.Module.Identity.AppUserController.GetListByIdAsync (Yun.Module.Identity.HttpApi) in 71.2229ms
[14:29:15 INF] Executed endpoint 'Yun.Module.Identity.AppUserController.GetListByIdAsync (Yun.Module.Identity.HttpApi)'
[14:29:15 DBG] Added 0 entity changes to the current audit log
[14:29:15 DBG] Added 0 entity changes to the current audit log
[14:29:15 INF] Request finished in 436.7986ms 500 application/json; charset=utf-8
```

**Comment by xyfy** [comment]
@hikalkan can you help me ?

**Comment by maliming** [comment]
> The requested service 'Yun.Module.Identity.AppUserController' has not been registered.

**Comment by xyfy** [comment]
it would not&nbsp;registered auto ?&nbsp; I use it to override the `IdentityUserController`




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "maliming"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 下午3:11
收件人: "abpframework/abp"<abp@noreply.github.com&gt;; 
抄送: "哈哈"<benguahao@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [abpframework/abp] [question]how to add api to Package References Module (#3871)





  
The requested service 'Yun.Module.Identity.AppUserController' has not been registered.
  
&mdash;

**Comment by xyfy** [comment]
Can anyone show the codes to add a new api to `Volo.Abp.Identity.IdentityUserController`,What is the problem of [my code](https://github.com/abpframework/abp/issues/3871#issuecomment-626433366)

**Comment by xyfy** [comment]
Maybe the controller of `HTTP.API` is not suitable for adding its own implementation. I gave up and directly added a new controller instead of override it, and got the correct response.

if any one can override it to add new api action ,please let me how to do it.
