### ISSUE TITLE
Can't access the url http://127.0.0.1:8988/Docs/Admin/Projects after publish

### ISSUE THREAD

**Issue by freeradius-xx** [abpframework/abp#3894]
Can't access the url http://127.0.0.1:8988/Docs/Admin/Projects after publish.

Below is the log message.

[16:16:16 INF] Request starting HTTP/1.1 GET http://127.0.0.1:8988/Docs/Admin/Projects
[16:16:17 ERR] Connection id "0HLVJU4I80GIM", Request id "0HLVJU4I80GIM:00000002": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
/Pages/Docs/Admin/Projects/Index.cshtml(33,28): error CS1705: 标识为“Volo.Abp.Authorization, Version=2.7.0.0, Culture=neutral, PublicKeyToken=null”的程序集“Volo.Abp.Authorization”所使用的“Microsoft.AspNetCore.Authorization, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”版本高于所引用的标识为“Microsoft.AspNetCore.Authorization, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”的程序集“Microsoft.AspNetCore.Authorization”
/Pages/Docs/Admin/Projects/Index.cshtml(42,28): error CS1705: 标识为“Volo.Abp.Authorization, Version=2.7.0.0, Culture=neutral, PublicKeyToken=null”的程序集“Volo.Abp.Authorization”所使用的“Microsoft.AspNetCore.Authorization, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”版本高于所引用的标识为“Microsoft.AspNetCore.Authorization, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”的程序集“Microsoft.AspNetCore.Authorization”
at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageLoader.LoadAsyncCore(PageActionDescriptor actionDescriptor, EndpointMetadataCollection endpointMetadata)
at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageLoaderMatcherPolicy.ApplyAsyncAwaited(CandidateSet candidates, Task1 actionDescriptorTask, Int32 index) at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet) at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.&lt;Invoke&gt;g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
[16:16:17 INF] Request finished in 618.5964ms 500

**Comment by maliming** [comment]
https://stackoverflow.com/questions/9219832/error-cs1705-which-has-a-higher-version-than-referenced-assembly
