### ISSUE TITLE
v2.8 create db error

### ISSUE THREAD

**Issue by heyuquan** [abpframework/abp#4068]
[20:38:03 INF] Started database migrations...
[20:38:03 INF] Migrating schema for host database...
[20:38:05 INF] Executing host database seed...
[20:38:08 INF] Successfully completed host database migrations.
[20:38:09 ERR] Failed executing DbCommand (5ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [t].[ConcurrencyStamp], [t].[CreationTime], [t].[CreatorId], [t].[DeleterId], [t].[DeletionTime], [t].[ExtraProperties], [t].[IsDeleted], [t].[LastModificationTime], [t].[LastModifierId], [t].[Name], [a0].[TenantId], [a0].[Name], [a0].[Value]
FROM (
    SELECT [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[CreatorId], [a].[DeleterId], [a].[DeletionTime], [a].[ExtraProperties], [a].[IsDeleted], [a].[LastModificationTime], [a].[LastModifierId], [a].[Name]
    FROM [AbpTenants] AS [a]
    WHERE (@__ef_filter__p_0 = CAST(1 AS bit)) OR ([a].[IsDeleted] <> CAST(1 AS bit))
    ORDER BY [a].[Name]
    OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
) AS [t]
LEFT JOIN [AbpTenantConnectionStrings] AS [a0] ON [t].[Id] = [a0].[TenantId]
ORDER BY [t].[Name], [t].[Id], [a0].[TenantId], [a0].[Name]
[20:38:09 ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.TenantManagement.EntityFrameworkCore.TenantManagementDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): **Incorrect syntax near 'OFFSET'.**
Invalid usage of the option NEXT in the FETCH statement.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)### ###

**Comment by liangshiw** [comment]
Please search the Internet first: https://stackoverflow.com/questions/53349099/incorrect-syntax-near-offset-invalid-usage-of-the-option-next-in-the-fetch-st

**Comment by maliming** [comment]
EF Core 3.x no longer supports `UseRowNumberForPaging`.
