### ISSUE TITLE
Got OperationCanceledException on DistributedCache

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4272]
Somehow the SemaphoreSlim was locked, it waits 300sec then throws OperationCanceledException.

Stacktrace:
````
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nito.AsyncEx.SemaphoreSlimExtensions.DoLockAsync(SemaphoreSlim this, CancellationToken cancellationToken)
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Caching/Volo/Abp/Caching/DistributedCache.cs:line 281
   at Volo.AbpIo.Templates.GitHub.GitHubSourceCodeContentStore.GetReleasesAsync(GithubRepository githubRepo) in /var/lib/jenkins/workspace/abp.io_Build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/GitHub/GitHubSourceCodeContentStore.cs:line 136
   at Volo.AbpIo.Templates.GitHub.GitHubSourceCodeContentStore.GetLatestVersionAsync(IHaveDownloadableSourceCode template) in /var/lib/jenkins/workspace/abp.io_Build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/GitHub/GitHubSourceCodeContentStore.cs:line 97
   at Volo.AbpIo.Www.Templates.TemplateDownloadAppService.GetLatestTemplateVersionAsync(GetLatestTemplateVersionDto input) in /var/lib/jenkins/workspace/abp.io_Build/volo/abp/abp_io/src/Volo.AbpIo.Www.Application/Templates/TemplateDownloadAppService.cs:line 73
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 25
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingInterceptor.cs:line 46
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAsyncAbpInterceptorAdapter.cs:line 34
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 25
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/ValidationInterceptor.cs:line 20
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAsyncAbpInterceptorAdapter.cs:line 34
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy/CastleAbpMethodInvocationAdapterWithReturnValue.cs:line 25
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in /var/lib/jenkins/workspace/abp.io_Build/abp/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs:line 34
   at Volo.Abp.Cast
````

We can reduce timeout value and use `Wait` instead of `Lock`. However, we need to fully understand the problem. This is first time we got such a problem after months of usage.

**Comment by zhutoutou** [comment]
Is there any update about which trigger the canceltoken cancel. I have reviewed AsyncEx code and found it's implement is similar with abp's new implement.
