### ISSUE TITLE
ORA-00932: inconsistent datatypes: expected - got NCLOB because of UNION

### ISSUE THREAD

**Issue by abxeps** [abpframework/abp#4314]
Hi,

After 2.9.0 update I'm unable to edit a user. AuditLog shows an error when calling
`/api/identity/users/687c96c4-7da8-9af0-4a4e-39f5b485a309/roles`

* **ABP Framework version** : 2.9.0
* **User Interface** type : Angular

It seems to be related to the genrated SQL query that makes a `UNION` between user and organization unit roles. Oracle cannot handle union with CLOB fields.
Oracle supports `UNION ALL` instead.

* Exception message and **stack trace**

```
2020-06-11 13:17:52.280 +02:00 [INF] Entity Framework Core 3.1.4 initialized 'IdentityDbContext' using provider 'Devart.Data.Oracle.Entity.EFCore' with options: None
2020-06-11 13:17:53.094 +02:00 [ERR] Failed executing DbCommand (811ms) [Parameters=[p__ef_filter__p_2='?' (DbType = Decimal), p__ef_filter__p_0='?' (DbType = Decimal), p__id_0='?' (DbType = Binary), p__ef_filter__p_4='?' (DbType = Decimal), p__ef_filter__p_8='?' (DbType = Decimal), p__ef_filter__p_9='?' (DbType = Decimal), p__ef_filter__p_6='?' (DbType = Decimal)], CommandType='"Text"', CommandTimeout='0']
SELECT t.Id, t.ConcurrencyStamp, t.ExtraProperties, t.IsDefault, t.IsPublic, t.IsStatic, t.Name, t.NormalizedName, t.TenantId
FROM AbpUserRoles a
INNER JOIN (
    SELECT a0.Id, a0.ConcurrencyStamp, a0.ExtraProperties, a0.IsDefault, a0.IsPublic, a0.IsStatic, a0.Name, a0.NormalizedName, a0.TenantId
    FROM AbpRoles a0
    WHERE (:p__ef_filter__p_2 = 1) OR a0.TenantId IS NULL
) t ON a.RoleId = t.Id
WHERE ((:p__ef_filter__p_0 = 1) OR a.TenantId IS NULL) AND (a.UserId = :p__id_0)
UNION
SELECT a1.Id, a1.ConcurrencyStamp, a1.ExtraProperties, a1.IsDefault, a1.IsPublic, a1.IsStatic, a1.Name, a1.NormalizedName, a1.TenantId
FROM AbpRoles a1
WHERE ((:p__ef_filter__p_2 = 1) OR a1.TenantId IS NULL) AND a1.Id IN (
    SELECT a2.RoleId
    FROM AbpOrganizationUnitRoles a2
    WHERE ((:p__ef_filter__p_4 = 1) OR a2.TenantId IS NULL) AND a2.OrganizationUnitId IN (
        SELECT t0.Id
        FROM AbpUserOrganizationUnits a3
        INNER JOIN (
            SELECT a4.Id, a4.Code, a4.ConcurrencyStamp, a4.CreationTime, a4.CreatorId, a4.DeleterId, a4.DeletionTime, a4.DisplayName, a4.ExtraProperties, a4.IsDeleted, a4.LastModificationTime, a4.LastModifierId, a4.ParentId, a4.TenantId
            FROM AbpOrganizationUnits a4
            WHERE ((:p__ef_filter__p_8 = 1) OR (a4.IsDeleted = 0)) AND ((:p__ef_filter__p_9 = 1) OR a4.TenantId IS NULL)
        ) t0 ON a3.OrganizationUnitId = t0.Id
        WHERE ((:p__ef_filter__p_6 = 1) OR a3.TenantId IS NULL) AND (a3.UserId = :p__id_0)
    )

)
2020-06-11 13:17:53.432 +02:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.Identity.EntityFrameworkCore.IdentityDbContext'.
Devart.Data.Oracle.OracleException (0x80004005): ORA-00932: inconsistent datatypes: expected - got NCLOB
   at Devart.Data.Oracle.dl.a(au A_0, Int32 A_1)
   at Devart.Data.Oracle.dl.a(Int32 A_0, bt A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.Entity.aj.a(CommandBehavior A_0)
   at Devart.Common.Entity.cu.d(CommandBehavior A_0)
   at Devart.Data.Oracle.Entity.aj.b(CommandBehavior A_0)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Devart.Data.Oracle.OracleException (0x80004005): ORA-00932: inconsistent datatypes: expected - got NCLOB
   at Devart.Data.Oracle.dl.a(au A_0, Int32 A_1)
   at Devart.Data.Oracle.dl.a(Int32 A_0, bt A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.Entity.aj.a(CommandBehavior A_0)
   at Devart.Common.Entity.cu.d(CommandBehavior A_0)
   at Devart.Data.Oracle.Entity.aj.b(CommandBehavior A_0)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2020-06-11 13:17:55.495 +02:00 [ERR] ---------- RemoteServiceErrorInfo ----------
2020-06-11 13:17:55.495 +02:00 [ERR] {
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "validationErrors": null
}
2020-06-11 13:17:55.495 +02:00 [ERR] ORA-00932: inconsistent datatypes: expected - got NCLOB
Devart.Data.Oracle.OracleException (0x80004005): ORA-00932: inconsistent datatypes: expected - got NCLOB
   at Devart.Data.Oracle.dl.a(au A_0, Int32 A_1)
   at Devart.Data.Oracle.dl.a(Int32 A_0, bt A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.Entity.aj.a(CommandBehavior A_0)
   at Devart.Common.Entity.cu.d(CommandBehavior A_0)
   at Devart.Data.Oracle.Entity.aj.b(CommandBehavior A_0)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.GetRolesAsync(Guid id, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Identity.IdentityUserAppService.GetRolesAsync(Guid id)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

* Steps needed to **reproduce** the problem
try to edit a user from the `Identity Management / Users` page

**Comment by maliming** [comment]
hi 

Did you search for `Devart Oracle` related content, this seems to be a compatibility issue with EF CORE providers.

**Comment by abxeps** [comment]
I found nothing that can help on the Devart forum. It seems that only rewriting the queries can solve such issues...

**Comment by maliming** [comment]
The code is standard linq. It can work normally in sql server, mysql, etc., so I don't think the code should be change.

**Comment by abxeps** [comment]
Devart is looking at it: https://forums.devart.com/viewtopic.php?f=1&t=40942

> Hello Alain,
> 
> Thank you for the test project.
> We have reproduced the error. We will investigate the issue and notify you about the result.
> 
> Best regards,
> Helen
> Devart Team
