### ISSUE TITLE
DynamicHttpProxyInterceptor<TService> will discard IFormFile  params

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4369]
* I am using Abp 2.8.0.
* Using the microservices sample 

I have a `upload` api in my `microservice`  , When I try to upload file throght `PublicWebSite.Host` to `gateway`,  it got `IFormFile file`  value well in razorpage backend. but can not found in `microservice`.

When I just call the api from gateway ,it works fine.

I think the `DynamicHttpProxyInterceptor<TService>` discard the   `IFormFile file` params

How can I make the the call correctly?   may I send a byte[] to service?
```
[13:52:11 INF] Executing handler method Yun.PublicWebSite.Host.Pages.File.IndexModel.OnPostUploadFileAsync - ModelState is Valid
[13:52:11 INF] Start processing HTTP request POST http://localhost:64897/api/Common/sitefile/upload?isFromWX=False&userName=admin&api-version=1.0
[13:52:11 INF] Sending HTTP request POST http://localhost:64897/api/Common/sitefile/upload?isFromWX=False&userName=admin&api-version=1.0
[13:52:11 INF] Received HTTP response after 189.6801ms - InternalServerError
[13:52:13 INF] Sending HTTP request POST http://localhost:64897/api/Common/sitefile/upload?isFromWX=False&userName=admin&api-version=1.0
[13:52:13 INF] Received HTTP response after 95.8111ms - InternalServerError
[13:52:17 INF] Sending HTTP request POST http://localhost:64897/api/Common/sitefile/upload?isFromWX=False&userName=admin&api-version=1.0
[13:52:17 INF] Received HTTP response after 75.2894ms - InternalServerError
[13:52:25 INF] Sending HTTP request POST http://localhost:64897/api/Common/sitefile/upload?isFromWX=False&userName=admin&api-version=1.0
[13:52:25 INF] Received HTTP response after 74.4604ms - InternalServerError
[13:52:25 INF] End processing HTTP request after 14461.5275ms - InternalServerError
[13:52:25 ERR] ---------- RemoteServiceErrorInfo ----------
[13:52:25 ERR] {
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "validationErrors": null
}
[13:52:25 ERR] 对不起,在处理你的请求期间,产生了一个服务器内部错误!
Volo.Abp.Http.Client.AbpRemoteCallException: 对不起,在处理你的请求期间,产生了一个服务器内部错误!
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Yun.PublicWebSite.Host.Pages.File.IndexModel.OnPostUploadFileAsync(IFormFile file) in D:\source\repos\YbMicroServices\applications\Yun.PublicWebSite.Host\Pages\File\Index.cshtml.cs:line 37
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
``

**Comment by xyfy** [comment]
Api Define

```
        [HttpPost]
        [Route("upload")]
        [RequestSizeLimit(1024 * 1024 * 100)]
        public Task<UploadFileOutDto> UploadFileAsync(IFormFile file, bool isFromWX = false, string userName = null)
        {
            Check.NotNull(file, nameof(file));
            userName = userName.IsNullOrEmpty() ? CurrentUser?.UserName : userName;
            return _innerSiteFileAppService.UploadFileAsync(file, IsFromWx, userName);
        }
```

**Comment by xyfy** [comment]
Razor page behinde 
```
        public async Task<JsonResult> OnPostUploadFileAsync(IFormFile file)
        {
            if (file == null)
            {
                throw new UserFriendlyException("aaaa");
            }
            var result = await _siteFileAppService.UploadFileAsync(file, isFromWX: false, userName: CurrentUser.UserName);
            return new JsonResult(result);
        }
```

**Comment by liangshiw** [comment]
Dynamic HTTP API Client currently only supports `JSON` and `XWwwFormUrlencoded`. You need to manually write the HTTP request.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/RequestPayloadBuilder.cs#L15

**Comment by xyfy** [comment]
I add a api define without IFormFIle ,and upload it in `Host` project.  pass the uploaded info to api

Resolved it.
