### ISSUE TITLE
No IUserTwoFactorTokenProvider<TUser> named 'Phone' is registered.

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4531]
HI,

I have a 3 tiers ABP application, I try to implement the "Phone number" validation (ie. enter a phone number, we send a SMS with a code, the user enter the code to validate the phone number is correct).

So, I use the following method:

`_identityManager.GenerateChangePhoneNumberTokenAsync`

But I got an exception : 

`No IUserTwoFactorTokenProvider<TUser> named 'Phone' is registered.`

The problem seems related to this article:
https://mattferderer.com/NotSupportedException-No-IUserTwoFactorTokenProvider-tuser-named-default-registered

You have not added the default token providers, maybe just adding this to AbpIdentityServiceCollectionExtensions can fix the problem ?

**Comment by vd3d** [comment]
Here is how I fixed it :

```
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            base.PreConfigureServices(context);

            // We customize the claims
            PreConfigure<Microsoft.AspNetCore.Identity.IdentityBuilder>(builder =>
            {
                builder.AddDefaultTokenProviders();
            });
        }
```


```
    public static class IdentityBuilderExt
    {
        public static Microsoft.AspNetCore.Identity.IdentityBuilder AddDefaultTokenProviders(this IdentityBuilder builder)
        {
            var phoneNumberProviderType = typeof(Microsoft.AspNetCore.Identity.PhoneNumberTokenProvider<>).MakeGenericType(typeof(Volo.Abp.Identity.IdentityUser));
            
            return AddTokenProvider(builder, Microsoft.AspNetCore.Identity.TokenOptions.DefaultPhoneProvider, phoneNumberProviderType);
        }

        public static Microsoft.AspNetCore.Identity.IdentityBuilder AddTokenProvider(this IdentityBuilder builder, string providerName, Type provider)
        {
            builder.Services.Configure<Microsoft.AspNetCore.Identity.IdentityOptions>(options =>
            {
                options.Tokens.ProviderMap[providerName] = new TokenProviderDescriptor(provider);
            });

            builder.Services.AddTransient(provider);
            return builder;
        }
    }
```

**Comment by maliming** [comment]
Does your project use `AbpIdentityAspNetCoreModule`?

**Comment by gdlcf88** [comment]
EasyAbp has released a new related module https://easyabp.io/modules/Abp.VerificationCode

**Comment by CAH-FlyChen** [comment]
got semilar issues     


public async Task ResetPassword(ResetPasswordInput data)
        {
            var t = await UserRepository.GetAsync(data.UserId);
            string token = await UserManager.GeneratePasswordResetTokenAsync(t);
            await UserManager.ResetPasswordAsync(t, token, data.Password);
        }
 
        2021-05-13 02:24:36.011 [ERR] [Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
   at Microsoft.AspNetCore.Identity.UserManager`1.GenerateUserTokenAsync(TUser user, String tokenProvider, String purpose)
   at Castle.Proxies.IdentityUserManagerProxy.GenerateUserTokenAsync_callback(IdentityUser user, String tokenProvider, String purpose)
   at Castle.Proxies.Invocations.UserManager`1_GenerateUserTokenAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
`

**Comment by git102347501** [comment]
> EasyAbp has released a new related module https://easyabp.io/modules/Abp.VerificationCode

For me, the implementation of easy team is a good example
