### ISSUE TITLE
How can I make AbpAuthorizationException return 401 or other code but not 500

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4560]
How can I make AbpAuthorizationException return 401 or other code but not 500?

I am using abp 2.8.0, and the `microservice` 

when user is not login or have no permission in `microservice module`  , it caught `AbpAuthorizationException` ,but the httpstatuscode is 500,it hard to do some logic to custom,such as re-login,or alerts?

**Comment by xyfy** [comment]
should I override method  `CreateErrorInfoWithoutCode` in `Volo.Abp.AspNetCore.ExceptionHandling.DefaultExceptionToErrorInfoConverter`  to do this?

**Comment by xyfy** [comment]
when the `microservice module` call  api ,why I can not got the expect erro code
![1](https://user-images.githubusercontent.com/7838147/86233263-c074fd80-bbc7-11ea-942a-c6a9186ec64c.jpg)

**Comment by xyfy** [comment]
Is it due to `DynamicHttpProxyInterceptor`?

**Comment by realZhangChi** [comment]
Did you use something like a reverse proxy? I used nginx and encountered the same problem, this problem is caused by nginx.

**Comment by xyfy** [comment]
no，can&nbsp; reproduce&nbsp; in&nbsp; local



---Original---

**Comment by xyfy** [comment]
it got correct response 401 in gateway & microservice,but got 500 from the `publicwebsite.Host`. I think it may be due to `DynamicHttpProxyInterceptor`

module log
```
[08:57:07 INF] Authorization failed.
[08:57:07 WRN] ---------- RemoteServiceErrorInfo ----------
[08:57:07 WRN] {
  "code": null,
  "message": "Authorization failed! Given policy has not granted.",
  "details": null,
  "validationErrors": null
}
[08:57:07 WRN] Authorization failed! Given policy has not granted.
Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! Given policy has not granted.
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync(ConsumerOrderQueryRequestInputDto inputDto, Boolean includingDetails) in D:\source\repos\YbMicroServices\modules\Yun.Module.Order\src\Yun.Module.Order.HttpApi\Orders\Public\PublicOrderController.cs:line 70
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:57:08 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[08:57:08 INF] Executed action Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync (Yun.Module.Order.HttpApi) in 547.0161ms
[08:57:08 INF] Executed endpoint 'Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync (Yun.Module.Order.HttpApi)'
[08:57:09 DBG] Added 0 entity changes to the current audit log
[08:57:09 DBG] Added 0 entity changes to the current audit log
[08:57:09 INF] Request finished in 2352.8831ms 401 application/json; charset=utf-8
```
 gateway log

```
[08:57:06 INF] Request starting HTTP/1.1 POST http://localhost:64897/api/Order/publicOrder/getOrders?includingDetails=True&api-version=1.0 application/json; charset=utf-8 122
[08:57:06 DBG] AuthenticationScheme: Bearer was not authenticated.
[08:57:06 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
[08:57:06 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: Upstream url path is /api/Order/publicOrder/getOrders
[08:57:06 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: downstream templates are /api/Order/{everything}
[08:57:06 INF] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/Order/{everything}
[08:57:06 INF] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: No authentication needed for /api/Order/publicOrder/getOrders
[08:57:06 INF] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: /api/Order/{everything} route does not require user to be authorised
[08:57:06 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: Downstream url is http://localhost:55566/api/Order/publicOrder/getOrders?includingDetails=True&api-version=1.0
[08:57:08 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: setting http response message
[08:57:08 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: no pipeline errors, setting and returning completed response
[08:57:08 DBG] requestId: 0HM0U4BB9SMCF:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished
[08:57:08 INF] Request finished in 1193.78ms 401 application/json; charset=utf-8
```
publicwebsite.host log
```
[08:57:06 INF] Sending HTTP request POST http://localhost:64897/api/Order/publicOrder/getOrders?includingDetails=True&api-version=1.0
[08:57:08 INF] Received HTTP response after 1194.6471ms - Unauthorized
[08:57:08 INF] End processing HTTP request after 1201.0608ms - Unauthorized
[08:57:08 ERR] ---------- RemoteServiceErrorInfo ----------
[08:57:08 ERR] {
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "validationErrors": null
}
[08:57:08 ERR] Authorization failed! Given policy has not granted.
Volo.Abp.Http.Client.AbpRemoteCallException: Authorization failed! Given policy has not granted.
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync(ConsumerOrderQueryRequestInputDto inputDto, Boolean includingDetails) in D:\source\repos\YbMicroServices\modules\Yun.Module.Order\src\Yun.Module.Order.HttpApi\Orders\Public\PublicOrderController.cs:line 70
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:57:08 ERR] Code:
[08:57:08 ERR] Details:
[08:57:08 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[08:57:08 INF] Executed action Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync (Yun.Module.Order.HttpApi) in 1531.3312ms
[08:57:08 INF] Executed endpoint 'Yun.Module.Order.Orders.PublicOrderController.GetOrdersAsync (Yun.Module.Order.HttpApi)'
[08:57:08 INF] Request finished in 3537.4134ms 500 application/json; charset=utf-8

```

**Comment by xyfy** [comment]
I debug it 
the `DynamicHttpProxyInterceptor` will throw an `AbpRemoteCallException` not rethrow the exception.
```
        private async Task ThrowExceptionForResponseAsync(HttpResponseMessage response)
        {
            if (response.Headers.Contains(AbpHttpConsts.AbpErrorFormat))
            {
                var errorResponse = JsonSerializer.Deserialize<RemoteServiceErrorResponse>(
                    await response.Content.ReadAsStringAsync()
                );

                throw new AbpRemoteCallException(errorResponse.Error);
            }

            throw new AbpException($"Remote service returns error! HttpStatusCode: {response.StatusCode}, ReasonPhrase: {response.ReasonPhrase}");
        }
```

**Comment by xyfy** [comment]
I think it should deal with the built-in exception ,not directly throw an new exception.

what do you think ? @maliming @hikalkan

**Comment by xyfy** [comment]
but the RemoteServiceErrorInfo do not contain the exception type only exception info.

**Comment by xyfy** [comment]
I want to override the  DynamicHttpProxyInterceptor<TService> ,  How can I do it?

**Comment by xyfy** [comment]
#4572
