### ISSUE TITLE
No BLOB Storage provider was registered!

### ISSUE THREAD

**Issue by realZhangChi** [abpframework/abp#4561]
I try to use BLOB storing in my project. As described in the documentation, I add Nuget `Volo.Abp.BlobStoring` and `Volo.Abp.BlobStoring.FileSystem` to my `HttpApiHost` project, and add `[DependsOn(typeof(AbpBlobStoringModule))]` to `AbpModule` of my `HttpApiHost` project. Also I have configure the Container in my `HttpApiHost` project like this:

```
 Configure<AbpBlobStoringOptions>(options =>
            {
                options.Containers.ConfigureDefault(container =>
                {
                    container.IsMultiTenant = false;
                    container.UseFileSystem(fileSystem =>
                    {
                        fileSystem.BasePath = configuration["Blob:BasePath"];
                    });
                });
            });
```
`AppService` and `Controller` like this:

```
public class SubjectIconAppService : ApplicationService, ISubjectIconAppService
    {
        private readonly IBlobContainer _subjectIconContainer;

        public SubjectIconAppService(IBlobContainer subjectIconContainer)
        {
            _subjectIconContainer = subjectIconContainer;
        }

        public async Task<byte[]> GetAsync(string name)
        {
            return await _subjectIconContainer.GetAllBytesAsync(name);
        }
    }
```

```
[Route("api/subject")]
    [Authorize]
    public class SubjectController : AbpController
    {
        private readonly ISubjectIconAppService _subjectIconService;


        public SubjectController(
            ISubjectIconAppService subjectIconService)
        {
            _subjectIconService = subjectIconService;
        }

        [HttpGet]
        [Route("icon")]
        [AllowAnonymous]    
        public async Task<byte[]> GetIconAsync(string name)
        {
            return await _subjectIconService.GetAsync(name);
        }
    }
``` 
When I call this action in swagger, I have error 500.

This is the log content:

> [ERR] An exception was thrown while activating GetRich.Bill.SubjectController -> GetRich.Bill.SubjectIconAppService -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null]].
Autofac.Core.DependencyResolutionException: An exception was thrown while activating GetRich.Bill.SubjectController -> GetRich.Bill.SubjectIconAppService -> λ:Volo.Abp.BlobStoring.IBlobContainer -> Volo.Abp.BlobStoring.BlobContainer`1[[Volo.Abp.BlobStoring.DefaultContainer, Volo.Abp.BlobStoring, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null]].
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Volo.Abp.BlobStoring.IBlobContainerFactory)' on type 'BlobContainer`1'.
 ---> Volo.Abp.AbpException: No BLOB Storage provider was registered! At least one provider must be registered to be able to use the Blog Storing System.
   at Volo.Abp.BlobStoring.DefaultBlobProviderSelector.Get(String containerName)
   at Volo.Abp.BlobStoring.BlobContainerFactory.Create(String name, CancellationToken cancellationToken)
   at Volo.Abp.BlobStoring.BlobContainerFactoryExtensions.Create[TContainer](IBlobContainerFactory blobContainerFactory, CancellationToken cancellationToken)
   at Volo.Abp.BlobStoring.BlobContainer`1..ctor(IBlobContainerFactory blobContainerFactory)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

Sorry about that I am working hard on my English. I'll appreciate it very much if you could help me.

**Comment by liangshiw** [comment]
Try add

```csharp
[DependsOn(typeof(AbpBlobStoringFileSystemModule))]
```
