### ISSUE TITLE
How can I use the jwtbearer before the gateway

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4579]
I am using abp 2.8.0, the microservice sample

I have a mvc client , it use the cookie auth,

I want it can support jwt auth

I add below code in `XXXModule.cs`
``` C#
services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
                {
                    options.LoginPath = new PathString("/Account/Login");
                    options.AccessDeniedPath = new PathString("/Account/Login");
                    options.LogoutPath = new PathString("/Account/Logout");
                    options.ExpireTimeSpan = TimeSpan.FromHours(12);
                })
                .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
.......

            services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.ApiName = configuration["AuthServer:ApiName"];
                    options.RequireHttpsMetadata = false;
                });
```
And I created a base class for Razor pageModel,all Page model inherit this class
``` C#
    [Authorize(AuthenticationSchemes = "Cookies,Bearer")]
    public abstract class BasePageModel : AbpPageModel
    {}
```

It works on login 

but when I called log out

it got an exception

```
[16:58:28 INF] Request starting HTTP/1.1 GET http://localhost:53435/Account/Logout  
[16:58:28 DBG] AuthenticationScheme: Bearer was not authenticated.
[16:58:28 INF] Executing endpoint 'Yun.PublicWebSite.Host.Controllers.AccountController.Logout (Yun.PublicWebSite.Host)'
[16:58:28 INF] Route matched with {action = "Logout", controller = "Account", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Logout(System.String, System.String) on controller Yun.PublicWebSite.Host.Controllers.AccountController (Yun.PublicWebSite.Host).
[16:58:28 INF] Executed action Yun.PublicWebSite.Host.Controllers.AccountController.Logout (Yun.PublicWebSite.Host) in 4.1098ms
[16:58:28 INF] Executed endpoint 'Yun.PublicWebSite.Host.Controllers.AccountController.Logout (Yun.PublicWebSite.Host)'
[16:58:28 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The authentication handler registered for scheme 'Bearer' is 'IdentityServerAuthenticationHandler' which cannot be used for SignOutAsync. The registered sign-out schemes are: Cookies, OpenIdConnect.
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Volo.Abp.AspNetCore.Mvc.Authentication.ChallengeAccountController.Logout(String returnUrl, String returnUrlHash)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

**Comment by gterdem** [comment]
Hello @xyfy,

I think you want to use Jwt for **Authorization** not **Authentication**.

Problem is with this;
```
services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
```

You are setting JwtBearer as default for everything such as signin, signout etc. Jwt doesn't have anything to do with signin or or signout. Leave the authentication as either oidc or cookies.

Here is some documentation about how to [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1).

I hope it was helpful.

**Comment by xyfy** [comment]
No,the documentatoin you prefer is not works in `Abp`

I can not use ` services.AddAuthentication()AddJwtBearer(....`

it got an err, says `JwtBearer` has already added.

**Comment by xyfy** [comment]
I had try it 
```
    services.AddAuthentication()
        .AddCookie(options => {
            options.LoginPath = "/Account/Unauthorized/";
            options.AccessDeniedPath = "/Account/Forbidden/";
        })
        .AddJwtBearer(options => {
            options.Audience = "http://localhost:5001/";
            options.Authority = "http://localhost:5000/";
        });
```

which will get an error

**Comment by xyfy** [comment]
I want to use `JwtBearer` to check if the user login ,or has authorize to do some action

**Comment by gterdem** [comment]
@xyfy is there any public repository that you can share and i can check to understand better?

**Comment by xyfy** [comment]
I will create a demo project to share for you~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Galip Tolga Erdem"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 晚上7:44
收件人: "abpframework/abp"<abp@noreply.github.com&gt;; 
抄送: "哈哈"<benguahao@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [abpframework/abp] How can I use the jwtbearer before the gateway (#4579)





 
@xyfy is there any public repository that you can share and i can check to understand better?
 
&mdash;

**Comment by xyfy** [comment]
@GerryGe 

https://github.com/xyfy/demo/tree/demo

https://github.com/xyfy/demo/tree/demo2

I want call the `module api` though `public website`  not `gateway`  using `jwt token`

**Comment by xyfy** [comment]
It is not resolved  directly

but I use directly `gateway` not `public website` to resolved it

**Comment by xyfy** [comment]
I still can not found a way to  use the two auth way  both  **jwt** and **cookie**

**Comment by xyfy** [comment]
I still can not found a way to use the two auth way both jwt and cookie
