### ISSUE TITLE
Method not found: Volo.Abp.EventBus.Distributed.EtoMappingDictionary

### ISSUE THREAD

**Issue by maxrizwork** [abpframework/abp#4623]
I just updated an existing application ( ASP.NET Core app ) from ver2.9.0 to ver3.0.2. 
I'm not using Abp nuget packages. My app is directly linked to Abp source code. 
In these cases I'm used to:
- check changes applied to abp aspnet core app template,
- update the existing database adding a new migration

During the boot of my web project I'm getting this exception:
System.MissingMethodException

"Method not found: 'Volo.Abp.EventBus.Distributed.EtoMappingDictionary  Volo.Abp.EventBus.Distributed.AbpDistributedEventBusOptions.get_EtoMappings()'."}	

inside the class 
Volo.Abp.EventBus.Distributed.LocalDistributedEventBus

I understood from release notes here:
https://github.com/abpframework/abp/releases/tag/3.0.0
that there are breaking changes regarding this topic but... are there instructions on how to update an existing application?

Thanks

Here the entire stacktrace:
![stacktrace](https://user-images.githubusercontent.com/10518283/86513592-b7746e00-be0b-11ea-9ad1-9c723b75c25f.PNG)

and this: 

   at Volo.Abp.IdentityServer.AbpIdentityServerDomainModule.<>c.<ConfigureServices>b__0_1(AbpDistributedEventBusOptions options) in C:\Proj\abp\modules\identityserver\src\Volo.Abp.IdentityServer.Domain\Volo\Abp\IdentityServer\AbpIdentityServerDomainModule.cs:line 50
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Volo.Abp.EventBus.Distributed.LocalDistributedEventBus..ctor(ILocalEventBus localEventBus, IServiceScopeFactory serviceScopeFactory, IOptions`1 distributedEventBusOptions) in C:\Proj\abp\framework\src\Volo.Abp.EventBus\Volo\Abp\EventBus\Distributed\LocalDistributedEventBus.cs:line 29
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by maxrizwork** [comment]
My fault guys. 
I forgot to run the buil-all.ps1 ( and test-all.ps1 as well ) before to run any other dependant project.
With buil-all script I resolved.

Sorry about that.
