### ISSUE TITLE
ValidationInterceptorRegistrar errors when adding Volo.Abp.EventBus.RabbitMQ to a solution

### ISSUE THREAD

**Issue by feanz** [abpframework/abp#4640]
I have an asp.net boilerplate application running the latest Volo.Abp framework. I am trying to setup DistributedEventBus with RabbitMQ but adding the package causes an error. I have added the Volo.Abp.EventBus.RabbitMQ nuget package to my host and made no other changes at all. Running the host app now causes the host to terminate with this error:

`System.MissingMethodException: Method not found: 'Void Volo.Abp.Collections.ITypeList`1.TryAdd()'.
   at Volo.Abp.Validation.ValidationInterceptorRegistrar.RegisterIfNeeded(IOnServiceRegistredContext context)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.InvokeRegistrationActions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, ServiceRegistrationActionList registrationActionList, Type serviceType, Type implementationType)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.ConfigureAbpConventions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, IModuleContainer moduleContainer, ServiceRegistrationActionList registrationActionList)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Register(ContainerBuilder builder, IServiceCollection services)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(ContainerBuilder builder, IServiceCollection services)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()`

 have not added the Module as a dependency of my module or done any custom configuration of the event bus setup just added the nuget package. It looks like ValidationInterceptorRegistrar.RegisterIfNeeded method is wrapping classes in dynamic proxies to do some validation and that it may be picking up some classes from the EventBus package and its causing an issue. Has anyone seen this on ABP before?

These are the packages and version from ABP I am using

` <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.Account.Web.IdentityServer" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.EventBus.RabbitMQ" Version="3.0.2" />
    <PackageReference Include="Volo.Abp.Identity.Web" Version="2.9.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Web" Version="2.9.0" />`

Adding the `Volo.Abp.EventBus.RabbitMQ` is the only change I make to get this error.  No other code changes at all.

**Comment by maliming** [comment]
The version of `Volo.Abp.*` related packages should be consistent.

**Comment by feanz** [comment]
Thanks yes standardising version level fixed this issue
