### ISSUE TITLE
add new Abp module to my solution

### ISSUE THREAD

**Issue by mohammed-hussein** [abpframework/abp#4679]
Hello,

I have created a new project for infrastructure under ABP solution which will contain integration with external APIs, in this project I have created new module class inherit from ABPModule and another class for a custom repository to communicate with external APIs but ABP framework not loading my project 'Infrastructure' while booted and not finding my custom repo as well.

Here my module code

 ```
namespace STCS.Framework.Infrastructure
{
    [DependsOn(
        typeof(FrameworkDomainModule),
        typeof(AbpAutofacModule),
        typeof(AbpAutoMapperModule)
        )]
    public class FrameworkInfrastructureModule: AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddApplication<FrameworkInfrastructureModule>(options =>{
                options.UseAutofac();
            });

            context.Services.AddTransient(typeof(TaskRepository), typeof(ITaskRepository));

            context.Services.AddAutoMapperObjectMapper<FrameworkInfrastructureModule>();
            Configure<AbpAutoMapperOptions>(options => {
                options.AddMaps<FrameworkInfrastructureModule>();
                //options.AddProfile<FrameworkInfrastructureAutoMapperProfile>(validate: true);
            });
        }
    }
}
```

* I'm using ABP Framework version 2.8
* Exception message and stack trace
```
An exception was thrown while activating Castle.Proxies.TasksAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.TasksAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.TasksAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'STCS.Framework.Repositories.ITaskRepository repository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], STCS.Framework.Repositories.ITaskRepository)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by iyilm4z** [comment]
@mohammed-hussein hi, you most probably forget to add your custom module to one of existing module’s dependson attribute. Try to add it to host module.

**Comment by iyilm4z** [comment]
@mohammed-hussein helped?

**Comment by mohammed-hussein** [comment]
@iyilm4z thanks, yes it helps to load my project but I have an issue with autofac

Host terminated unexpectedly!
System.Exception: An object accessor is registered before for type: Autofac.ContainerBuilder, Autofac, Version=4.9.4.0, Culture=neutral, PublicKeyToken=17863af14b0044da
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionObjectAccessorExtensions.AddObjectAccessor[T](IServiceCollection services, ObjectAccessor`1 accessor)

**Comment by iyilm4z** [comment]
@mohammed-hussein if it's possible, please share the solution reproduces the issue.

**Comment by mohammed-hussein** [comment]
@maliming , it's a huge solution to share with you, I follow steps on documentation [Autofac](https://docs.abp.io/en/abp/latest/Autofac-Integration) and get this issue

**Comment by maliming** [comment]
hi @mohammed-hussein 

You can share a simple project to reproduce the problem. 

https://abp.io/get-started

**Comment by mohammed-hussein** [comment]
hi @iyilm4z & @maliming ,

thanks for your support,

sure I will create a new project and share it with you later but I have a question as in my issue description above, 

I created new Abp Module (infrastructure project from type class library[.net core]) which contain an implementation 'MycustomRepository ' of interface IcustomRepository<Book, Guid> and this interface located in domain module and inject this interface in application module but Autofac can't find MycustomRepository which inside infrastructure module and got an exception in stack trace above, so the question is how to enforce application module to inject an actual implementation of IcustomRepository in runtime, what I miss in this process, another note I reference 'infrastructure module' in dependencies client.Host module

**Comment by mohammed-hussein** [comment]
Hi,

you can find simple code [here](https://github.com/mohammed-hussein/BookStore)

**Comment by maliming** [comment]
> you can find simple code here

hi @mohammed-hussein Please provide steps?

**Comment by mohammed-hussein** [comment]
Hi @maliming , run code and try to navigate to api  '/api/app/tasks/myTasks'
[](https://localhost:44359/api/app/tasks/myTasks?UserName=test)

**Comment by mohammed-hussein** [comment]
Hi @maliming , did you check?

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/88000975-8eedb300-cb31-11ea-9f33-4ada9c3955a2.png)

**Comment by mohammed-hussein** [comment]
Hi @maliming, please check it again.

**Comment by mohammed-hussein** [comment]
Hi @maliming any updates?

**Comment by maliming** [comment]
hi  @mohammed-hussein

I can't understand your solution and codes, Have you read the document of the repository? Because your code does not follow the documentation recommendations.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core

**Comment by mohammed-hussein** [comment]
Hi @maliming ,
yes i read documentation.

simply I need to reference and interface in Application service and implementation of this interface in a different project called 'infrastructure' and added depends on web.host project but application service throw this expectation what missing to enable autofac to register implementation in runtime


An exception was thrown while activating Castle.Proxies.TasksAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.TasksAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.TasksAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'STCS.Framework.Repositories.ITaskRepository repository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], STCS.Framework.Repositories.ITaskRepository)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---

**Comment by maliming** [comment]
your application module has not been dependent on the FrameworkInfrastructureModule.


![image](https://user-images.githubusercontent.com/6908465/88612248-62034800-d0bd-11ea-9489-842ce79e208b.png)


```cs
    [Dependency(ServiceLifetime.Transient,ReplaceServices = true)]
    [ExposeServices(typeof(ITaskRepository))]
    public class TaskRepository : ITaskRepository
```

**Comment by iyilm4z** [comment]
@maliming As i see, my first comment was the solution to this issue, right?:)

**Comment by mohammed-hussein** [comment]
Hi @maliming your solution doesn't work and still the same issue and I have push updates on the repo you can check, also I think your proposed solution break DDD design as application service shouldn't depend on the infrastructure layer,
please advise 

@iyilm4z , thanks man for your support your comment helped me to load the project in Abp but still have the same issue as I mentioned before.

Thanks

**Comment by minitoma** [comment]
@mohammed-hussein did you try replacing your interface manually in the module code, see [abpdoc](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services)

```
context.Services.Replace(
    ServiceDescriptor.Transient<IIdentityUserAppService, MyIdentityUserAppService>()
);
```

You can write this inside the ConfigureServices method of your module.

i had the same problem as you and manage to get it worked this way without breaking DDD design

**Comment by mohammed-hussein** [comment]
@minitoma  Thanks so much it solved my problem without breaking DDD , appreciated your help :)

I added  below code inside ConfigureServices method
`context.Services.AddTransient<ITaskRepository, TaskRepository>();`
