### ISSUE TITLE
Getting issue while registering user

### ISSUE THREAD

**Issue by HiteshAnshani** [abpframework/abp#4718]
Hello,

I have integrated modules in my project login is working fine but while registering user I am getting the error
Please check the logs and kindly guide me.

I can see in database user is added successfully but in UI I am getting error and also in logs I am getting error.

```
2020-07-10 18:15:53.831 +05:30 [DBG] Added 0 entity changes to the current audit log
2020-07-10 18:15:53.831 +05:30 [DBG] Added 0 entity changes to the current audit log
2020-07-10 18:15:53.844 +05:30 [INF] Executed action method Volo.Abp.Account.AccountController.RegisterAsync (Volo.Abp.Account.HttpApi), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 3408.6854ms.
2020-07-10 18:15:53.844 +05:30 [DBG] Added 0 entity changes to the current audit log
2020-07-10 18:15:53.860 +05:30 [ERR] ---------- RemoteServiceErrorInfo ----------
2020-07-10 18:15:53.863 +05:30 [ERR] {
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "validationErrors": null
}
2020-07-10 18:15:53.864 +05:30 [ERR] An exception was thrown while activating Volo.Blogging.Users.BlogUserSynchronizer.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Blogging.Users.BlogUserSynchronizer.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.Blogging.Users.BlogUserSynchronizer' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Blogging.Users.IBlogUserRepository userRepository' of constructor 'Void .ctor(Volo.Blogging.Users.IBlogUserRepository, Volo.Blogging.Users.IBlogUserLookupService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.EventBus.IocEventHandlerFactory.GetHandler()
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions)
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlersAsync(Type eventType, Object eventData, List`1 exceptions)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(Type eventType, Object eventData)
   at Volo.Abp.Uow.UnitOfWork.OnCompletedAsync()
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Mvc.Uow.AbpUowActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-10 18:15:53.865 +05:30 [ERR] ---------- Exception Data ----------
2020-07-10 18:15:53.866 +05:30 [ERR] ActivatorChain = Volo.Blogging.Users.BlogUserSynchronizer
2020-07-10 18:15:53.876 +05:30 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2020-07-10 18:15:53.912 +05:30 [INF] Executed action Volo.Abp.Account.AccountController.RegisterAsync (Volo.Abp.Account.HttpApi) in 3837.8813ms
2020-07-10 18:15:53.913 +05:30 [INF] Executed endpoint 'Volo.Abp.Account.AccountController.RegisterAsync (Volo.Abp.Account.HttpApi)'
2020-07-10 18:15:53.972 +05:30 [INF] Entity Framework Core 3.1.4 initialized 'AbpAuditLoggingDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-07-10 18:15:54.025 +05:30 [INF] Executed DbCommand (14ms) [Parameters=[@p0='?' (DbType = Guid), @p1='?' (Size = 96), @p2='?' (Size = 512), @p3='?' (Size = 64), @p4='?' (Size = 64), @p5='?' (Size = 128), @p6='?' (Size = 256), @p7='?' (Size = 4000), @p8='?' (Size = 64), @p9='?' (Size = 4000), @p10='?' (DbType = Int32), @p11='?' (DbType = DateTime2), @p12='?' (Size = 4000), @p13='?' (Size = 16), @p14='?' (DbType = Int32), @p15='?' (DbType = Guid), @p16='?' (DbType = Guid), @p17='?' (DbType = Guid), @p18='?' (Size = 4000), @p19='?' (Size = 256), @p20='?' (DbType = Guid), @p21='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
```

Thanks in advance.

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by HiteshAnshani** [comment]
Hi @maliming,
Thanks for replying.
**Abp version 2.9.0**

I don't think the problem is in UI because when I am trying from swagger the same error I am getting.
"Internal server error"
I can see the user is also added in the database but in swagger and in UI I am getting this error "Internal server error"

**Please check the log file.**

I have manually added modules in my project for debugging purpose but after adding that I am getting this error suddenly.

[logs.txt](https://github.com/abpframework/abp/files/4903749/logs.txt)

**Comment by maliming** [comment]
* Steps needed to reproduce the problem.

Does your application depend on **BloggingEntityFrameworkCoreModule**

**Comment by HiteshAnshani** [comment]
Hello @maliming,
I have removed the dependency of NuGet packages and added project reference over there and then trying to add the user.
I am not able to find  **BloggingEntityFrameworkCoreModule** dependency on any of my project.

Steps:
Remove NuGet packages from each project and added the reference to each module manually and then try to run.
