### ISSUE TITLE
Blog module: Editing a blog throws `Object reference not set to an instance of an object` exception.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#475]
Exception message:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form.AbpDynamicFormTagHelperService.GetModels(TagHelperContext context, TagHelperOutput output) in E:\Github\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Bootstrap\TagHelpers\Form\AbpDynamicformTagHelperService.cs:line 200
   at Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form.AbpDynamicFormTagHelperService.ProcessFields(TagHelperContext context, TagHelperOutput output) in E:\Github\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Bootstrap\TagHelpers\Form\AbpDynamicformTagHelperService.cs:line 130
   at Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form.AbpDynamicFormTagHelperService.ProcessAsync(TagHelperContext context, TagHelperOutput output) in E:\Github\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Bootstrap\TagHelpers\Form\AbpDynamicformTagHelperService.cs:line 43
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore._Pages_Admin_Blogs_Edit.ExecuteAsync() in E:\Github\abp\modules\blogging\src\Volo.Blogging.Web\Pages\Admin\Blogs\Edit.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I guess it's related to this line:
https://github.com/abpframework/abp/blob/04ab3b592cb6021bfb06a2c1adace7d9714361af/modules/blogging/src/Volo.Blogging.Web/Pages/Admin/Blogs/Edit.cshtml#L11

Missing `abp-model="Blog"` ?

**Comment by yekalkan** [comment]
Thanks you.
