### ISSUE TITLE
How to use Hangfire in a console Application

### ISSUE THREAD

**Issue by Enissay** [abpframework/abp#4799]
Hi,

I am trying to use Hangfire in a **console application** and following your doc [HERE](https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire).

But, the below doesn't seem to be available for a console application as it returns null:

`var app = context.GetApplicationBuilder();`

I found a previously closed ticket with a similar problem https://github.com/abpframework/abp/issues/4102 but the solution is not clear. Would someone please help further with this ?

* **ABP Framework version** 3.0.4

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/tree/dev/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.HangFire

**Comment by Enissay** [comment]
@liangshiw 
I tried to run that example as is before even adapting it for my needs, and yet it is giving me a similar error as I was getting before. Please advise what am I missing :

> Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnPostApplicationInitializationModuleLifecycleContributor phase of the module DemoApp.Shared.DemoAppSharedModule, DemoApp.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: Background job creation failed. See inner exception for details.. See the inner exception for details.
 ---> Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 42P01: **relation "hangfire.job" does not exist**
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1079
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 721
   at Hangfire.PostgreSql.PostgreSqlConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__2(Int32 _)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
--- End of stack trace from previous location where exception was thrown ---
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()
   at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "hangfire.job" does not exist
    Position: 15
    File: parse_relation.c
    Line: 1173

**Comment by liangshiw** [comment]
It works fine.

![image](https://user-images.githubusercontent.com/16813853/87870699-1a096480-c9dd-11ea-9149-fb9bf88de762.png)

**Comment by xirius** [comment]
@liangshiw How do you make it work with PostgreSQL ?

**Comment by liangshiw** [comment]
Yes, It works.

![image](https://user-images.githubusercontent.com/16813853/87912587-391cfa80-caa0-11ea-8441-097975339c42.png)

If you have problem, please provide steps to reproduce.

**Comment by xirius** [comment]
@liangshiw I try to include hangfire job using this [console template ](https://github.com/abpframework/abp/tree/dev/templates/console).
But I cannot figure it out why it doesn't work.

**Comment by liangshiw** [comment]
Can you provide steps to reproduce. Thanks.

**Comment by Enissay** [comment]
> It works fine.
> 
> ![image](https://user-images.githubusercontent.com/16813853/87870699-1a096480-c9dd-11ea-9149-fb9bf88de762.png)

Hi @liangshiw ,

I've actually tried to execute that demo and I keep getting this error: `Npgsql.PostgresException (0x80004005): 42P01: relation "hangfire.job" does not exist`.

I have shared here the project with you so you see when exactly I am using:  (it is unzipped so you can see it contains nothing harmful)
https://drive.google.com/drive/folders/1xLPLSBe0kVSU4dup6hq32G-icCDPvEYs?usp=sharing

Please advise as I really can't see what's missing :-/

**Comment by liangshiw** [comment]
I used the project you provided and it works fine. 
Please check your database server.

![image](https://user-images.githubusercontent.com/16813853/88678399-ff439800-d120-11ea-89cd-de3d003eebc5.png)
