### ISSUE TITLE
CLI - creating a new project error

### ISSUE THREAD

**Issue by SimaWB** [abpframework/abp#4974]
When I want to create a new project via CLI command like:
`Acme.BookStore`

I get an error message:

[09:55:37 INF] ABP CLI (https://abp.io)
[09:55:38 INF] Version 3.0.5 (Stable channel)
[09:55:40 INF] Creating your project...
[09:55:40 INF] Project name: Acme.BookStore
[09:55:40 INF] Mobile App: ReactNative
[09:55:40 INF] Output folder: C:\Users\veli.bozatli\Documents\FFE\Acme.BookStore
[09:55:42 INF] Using cached template: app, version: 3.0.5
[09:55:42 ERR] Wrong Local header signature: 0x4F44213C
ICSharpCode.SharpZipLib.Zip.ZipException: Wrong Local header signature: 0x4F44213C
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.FileEntryListReadStep.GetEntriesFromZipFile(Byte[] fileBytes) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\FileEntryListReadStep.cs:line 25
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.FileEntryListReadStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\FileEntryListReadStep.cs:line 14
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 113
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 128
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55`

**Comment by maliming** [comment]
Hi

Try to remove the cached zip project.


`C:\Users\username\.abp\templates`

![image](https://user-images.githubusercontent.com/6908465/89501285-aa291580-d7f5-11ea-9603-4a05cd55a42c.png)

**Comment by SimaWB** [comment]
Thanks @maliming, deleting temporary files solved my problem
