### ISSUE TITLE
[ERR] Method not found: 'System.__Canon AutoMapper.IMapper.Map(System.Object)'

### ISSUE THREAD

**Issue by jack-gaojz-zz** [abpframework/abp#5030]
**Error message:**

2020-08-12 07:59:57.380 +08:00 [INF] Entity Framework Core 3.1.7 initialized 'BackgroundJobsDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using lazy-loading proxies 
2020-08-12 07:59:57.383 +08:00 [INF] Executed DbCommand (2ms) [Parameters=[@__p_1='?' (DbType = Int32), @__now_0='?' (DbType = DateTime2)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[ExtraProperties], [a].[IsAbandoned], [a].[JobArgs], [a].[JobName], [a].[LastTryTime], [a].[NextTryTime], [a].[Priority], [a].[TryCount]
FROM [AbpBackgroundJobs] AS [a]
WHERE ([a].[IsAbandoned] <> CAST(1 AS bit)) AND ([a].[NextTryTime] <= @__now_0)
ORDER BY [a].[Priority] DESC, [a].[TryCount], [a].[NextTryTime]
2020-08-12 07:59:57.386 +08:00 **[ERR] Method not found: 'System.__Canon AutoMapper.IMapper.Map(System.Object)'.
System.MissingMethodException: Method not found: 'System.__Canon AutoMapper.IMapper.Map(System.Object)'.**
   at Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider.Map[TSource,TDestination](Object source)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.Map[TSource,TDestination](TSource source)
   at Volo.Abp.BackgroundJobs.BackgroundJobStore.GetWaitingJobsAsync(Int32 maxResultCount)
   at Volo.Abp.BackgroundJobs.BackgroundJobWorker.DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.BackgroundWorkers.AsyncPeriodicBackgroundWorkerBase.Timer_Elapsed(Object sender, EventArgs e)

**ABP Framework version: 3.0.5
Automapper: 10.0.0**

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by hikalkan** [comment]
I suppose you've upgraded to AutoMapper 10, but ABP modules are still using AutoMapper 9.
I suggest you to use AutoMapper 9 until we release ABP Framework 3.1 which uses AutoMapper 10.

**Comment by jack-gaojz-zz** [comment]
@hikalkan Thanks so much. :)
