### ISSUE TITLE
DynamicStringLengthAttribute throws NullReferenceException during AutoMapper initialization

### ISSUE THREAD

**Issue by Shtong** [abpframework/abp#5056]
**ABP Framework Version**: 3.0.5
**User interface**: MVC

**Summary**:
We are in the process of updating our app to ABP 3.0.5. We encountered a problem while updating our Dtos to use `DynamicStringLengthAttribute` instead of `StringLengthAttribute`: when two Dtos are mapped together (with AutoMapper), and one of these classes use `DynamicStringLengthAttribute`, then the attribute constructor will throw a `NullReferenceException`.

**Exception details**:
```
Volo.Abp.AbpInitializationException
  HResult=0x80131500
  Message=An error occurred during the initialize Volo.Abp.Modularity.OnPreApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.AutoMapper.AbpAutoMapperModule, Volo.Abp.AutoMapper, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null: Object reference not set to an instance of an object.. See the inner exception for details.
  Source=Volo.Abp.Core
  StackTrace:
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app)
   at Acme.BookStore.Web.Startup.Configure(IApplicationBuilder app) in C:\Users\xavier.rm\source\repos\abp-samples\BookStore-Mvc-EfCore\src\Acme.BookStore.Web\Startup.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

  This exception was originally thrown at this call stack:
    Volo.Abp.Validation.DynamicStringLengthAttribute.DynamicStringLengthAttribute(System.Type, string, string)
    System.Reflection.CustomAttribute.CreateCaObject(System.Reflection.RuntimeModule, System.RuntimeType, System.IRuntimeMethodInfo, ref System.IntPtr, System.IntPtr, out int)
    System.Reflection.CustomAttribute.AddCustomAttributes(ref System.RuntimeType.ListBuilder<object>, System.Reflection.RuntimeModule, int, System.RuntimeType, bool, System.RuntimeType.ListBuilder<object>)
    System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, int, int, System.RuntimeType)
    System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimePropertyInfo, System.RuntimeType)
    System.Reflection.RuntimePropertyInfo.GetCustomAttributes(bool)
    AutoMapper.Configuration.MappingExpressionBase.Configure(AutoMapper.TypeMap)
    AutoMapper.ProfileMap.BuildTypeMap(AutoMapper.IConfigurationProvider, AutoMapper.Configuration.ITypeMapConfiguration)
    AutoMapper.ProfileMap.Register(AutoMapper.IConfigurationProvider)
    AutoMapper.MapperConfiguration.Seal()
    ...
    [Call Stack Truncated]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

**Repro steps**:
- Clone the ABP Samples repo, and open the `BookStore-Mvc-EfCore` sample solution.
- Start the web project of the solution. You should see an error message saying that the app cannot connect to the database (if you didn't previously prepare the database for this sample), which is expected.
- Create a new class in the project `Acme.Bookstore.Domain.Shared`:
```cs
namespace Acme.BookStore.Books
{
    public static class BookConsts
    {
        public static readonly int MaxNameLength = 128;
    }
}
```
- Update the existing `CreateUpdateBookDto` class to use `DynamicStringLength` instead of `StringLength`:
```diff
--- a/BookStore-Mvc-EfCore/src/Acme.BookStore.Application.Contracts/Books/CreateUpdateBookDto.cs
+++ b/BookStore-Mvc-EfCore/src/Acme.BookStore.Application.Contracts/Books/CreateUpdateBookDto.cs
@@ -1,5 +1,6 @@
 ﻿using System;
 using System.ComponentModel.DataAnnotations;
+using Volo.Abp.Validation;

 namespace Acme.BookStore.Books
 {
@@ -8,7 +9,7 @@ namespace Acme.BookStore.Books
         public Guid AuthorId { get; set; }

         [Required]
-        [StringLength(128)]
+        [DynamicStringLength(typeof(BookConsts), nameof(BookConsts.MaxNameLength))]
         public string Name { get; set; }

         [Required]
```
- Start the application. The application should crash with a `NullReferenceException`, before it can show the connection error page

**Comment by maliming** [comment]
Try

```cs

public static class BookConsts
{
    public static int MaxNameLength { get; set; } = 128;
}
```
