### ISSUE TITLE
Failed to validate project name. Should not rename a project downloaded from aspnetzero.com. You can contact to info@aspnetzero.com if you are using a licensed product.

### ISSUE THREAD

**Issue by onestow** [abpframework/abp#5064]
> FATAL 2020-08-15 15:58:13,135 [3    ] oCore.Licensing.AspNetZeroLicenseChecker - Failed to validate project name. Should not rename a project downloaded from aspnetzero.com. You can contact to info@aspnetzero.com if you are using a licensed product.
StartIndex cannot be less than zero.
Parameter name: startIndex
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Abp.AspNetZeroCore.Licensing.AspNetZeroLicenseChecker.iKo1Uonp7ETVIZw1Xo(Object , Int32 , Int32 )
   at Abp.AspNetZeroCore.Licensing.AspNetZeroLicenseChecker.GetHashedProjectName()
   at Abp.AspNetZeroCore.Licensing.AspNetZeroLicenseChecker.IsProjectNameValid()
   at Abp.AspNetZeroCore.Licensing.AspNetZeroLicenseChecker.CheckInternal()

help! my project name follow:
![批注 2020-08-15 161106](https://user-images.githubusercontent.com/8585183/90308436-113f7c00-df12-11ea-9660-788a66f5f6c6.png)

**Comment by onestow** [comment]
I didn't rename the project name
