### ISSUE TITLE
use ioc error in BackgroundWorker,error dbcontext is dispose

### ISSUE THREAD

**Issue by heyuquan** [abpframework/abp#5115]
use ioc error in BackgroundWorker. 
 i use inject repository in BackgroundWorker,but use this repository throw dispoed dbcontext error
like this:

System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'DemoBDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mk.DemoB.BackgroundJobs.Job.CaptureExechangeRateJob.DoWorkAsync(PeriodicBackgroundWorkerContext workerContext) in F:\Code\myself\Leopard.Abp\Mk.DemoB\src\Mk.DemoB.BackgroundJobs\Job\CaptureExechangeRateJob.cs:line 47
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass15_0.<Run>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Threading.AsyncHelper.RunSync(Func`1 action)
   at Volo.Abp.BackgroundWorkers.AsyncPeriodicBackgroundWorkerBase.Timer_Elapsed(Object sender, EventArgs e)

can you  help me handle this issue

step1:download git https://github.com/heyuquan/Leopard.Abp
step2:run Mk.DemoB.HttpApi.Host
step3:break point in Mk.DemoB.BackgroundJobs\CaptureExechangeRateJob.cs  .  code line 48

**Comment by real-zony** [comment]
Hi @heyuquan,
You only need to add UnitOfWork Attribute. 
```csharp
        [UnitOfWork]
        protected override async Task DoWorkAsync(
                PeriodicBackgroundWorkerContext workerContext)
        {
            var exchangeRateCaptureBatchRepository = workerContext
                .ServiceProvider
                .GetRequiredService<IRepository<ExchangeRateCaptureBatch, Guid>>();
          // Other Code
        }
```
If you have any questions, you can refer to my blog: [https://www.cnblogs.com/myzony/p/11647030.html](https://www.cnblogs.com/myzony/p/11647030.html)

**Comment by heyuquan** [comment]
@GameBelial 
thank you.。
