### ISSUE TITLE
Overriding a Service Class and request has not been registered

### ISSUE THREAD

**Issue by jonny-xhl** [abpframework/abp#5178]
I overrided  `IdentityUserAppService`  to throw an exception when I requested it .

error:(**The requested service 'ExaminationSample.TestExposeService.MyIdentityUserAppService' has not been registered**).

The code is same to [docs](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by jonny-xhl** [comment]
- ABP Version:3.0.5.
- I overrided the **IdentityUserAppService** is in the Application layer.
- **My code:**
```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserAppService))]
public class MyIdentityUserAppService : IdentityUserAppService{
       ...
}
```
- **Stack trace:**
```
2020-08-26 19:04:03.326 +08:00 [ERR] The requested service 'ExaminationSample.TestExposeService.MyIdentityUserAppService' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'ExaminationSample.TestExposeService.MyIdentityUserAppService' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by maliming** [comment]
Try `[ExposeServices(typeof(MyIdentityUserAppService), typeof(IIdentityUserAppService), typeof(IdentityUserAppService))]`

**Comment by jonny-xhl** [comment]
It's ok.
- Does the [document](https://docs.abp.io/zh-Hans/abp/latest/Customizing-Application-Modules-Overriding-Services) need to be updated?
- I'm not using it correctly?

**Comment by maliming** [comment]
> Does the document need to be updated?

Maybe, I will check it.

**Comment by jonny-xhl** [comment]
Ok,thks!
