### ISSUE TITLE
Docs Module standalone http 500 error on default page after setup

### ISSUE THREAD

**Issue by nischalsanghal** [abpframework/abp#5187]
Hello
I followed the steps here: https://docs.abp.io/en/abp/latest/Apps/VoloDocs  to create a standalone document project. I was able to run the VoloDocs.Web.exe and define a new project. But when I navigate to /documents it is throwing 500 error. 
Any suggestions what to look for. I tried public/private repos with the appropriate access token as documented but no luck.

Will appreciate any kind of pointer.

Thanks
Nischal

**Comment by maliming** [comment]
>  it is throwing 500 error.

Please check your application logs.

**Comment by nischalsanghal** [comment]
2020-08-26 23:16:49.142 -07:00 [INF] Downloading content from Github (DownloadWebContentAsStringAsync): https://raw.githubusercontent.com/chiropad/docs/README.md
2020-08-26 23:16:49.142 -07:00 [INF] Start processing HTTP request GET "https://raw.githubusercontent.com/chiropad/docs/README.md"
2020-08-26 23:16:49.142 -07:00 [INF] Sending HTTP request GET "https://raw.githubusercontent.com/chiropad/docs/README.md"
2020-08-26 23:16:49.228 -07:00 [INF] Received HTTP response after 85.5749ms - "BadRequest"
2020-08-26 23:16:49.228 -07:00 [INF] End processing HTTP request after 85.80810000000001ms - "BadRequest"
2020-08-26 23:16:49.228 -07:00 [WRN] Response status code does not indicate success: 400 (Bad Request).
2020-08-26 23:16:49.229 -07:00 [INF] Executed page /Documents/Project/Index in 99.30810000000001ms
2020-08-26 23:16:49.230 -07:00 [ERR] Connection id "0HM2AA10OIMBL", Request id "0HM2AA10OIMBL:00000008": An unhandled exception was thrown by the application.
Volo.Docs.DocumentNotFoundException: Exception of type 'Volo.Docs.DocumentNotFoundException' was thrown.
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.DownloadWebContentAsStringAsync(String rawUrl, String token, String userAgent) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 152
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.GetDocumentAsync(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 49
   at Volo.Docs.Documents.DocumentAppService.<>c__DisplayClass13_0.<<GetDocumentWithDetailsDto>g__GetDocumentAsync|0>d.MoveNext() in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.Caching.DistributedCache`1.GetOrAddAsync(String key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
   at Volo.Docs.Documents.DocumentAppService.GetDocumentWithDetailsDto(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 116
   at Volo.Docs.Documents.DocumentAppService.GetAsync(GetDocumentInput input) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 36
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ValidationInterceptor.cs:line 43
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Auditing\Volo\Abp\Auditing\AuditingInterceptor.cs:line 52
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Docs.Pages.Documents.Project.IndexModel.SetDocumentAsync() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 202
   at Volo.Docs.Pages.Documents.Project.IndexModel.OnGetAsync() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 59
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()

**Comment by maliming** [comment]
hi

What's your project information that uses GitHub source?



https://docs.abp.io/en/abp/latest/Apps/VoloDocs#an-example-project-definition

**Comment by nischalsanghal** [comment]
It's a private repo and I gave full control to the access token

![image](https://user-images.githubusercontent.com/43482899/91471508-11f9db80-e84b-11ea-9f89-99159cc6dbfd.png)

**Comment by maliming** [comment]
Can you follow the example of the document.

https://docs.abp.io/en/abp/latest/Apps/VoloDocs#an-example-project-definition

**Comment by nischalsanghal** [comment]
I left the access token and user agent parameters blank.  It's showing the same exception.

2020-08-27 20:26:46.622 -07:00 [INF] Executing handler method Volo.Docs.Pages.Documents.Project.IndexModel.OnGetAsync with arguments (null) - ModelState is "Valid"
2020-08-27 20:26:47.621 -07:00 [INF] Not found in the cache. Requesting Index.md from the store...
2020-08-27 20:26:47.621 -07:00 [INF] Downloading content from Github (DownloadWebContentAsStringAsync): https://raw.githubusercontent.com/abpframework/abp/master/docs/en/Index.md
2020-08-27 20:26:47.622 -07:00 [WRN] The format of value '' is invalid.
2020-08-27 20:26:47.625 -07:00 [INF] Executed page /Documents/Project/Index in 1005.4919000000001ms
2020-08-27 20:26:47.626 -07:00 [ERR] Connection id "0HM2AA10OIMCN", Request id "0HM2AA10OIMCN:00000003": An unhandled exception was thrown by the application.
Volo.Docs.DocumentNotFoundException: Exception of type 'Volo.Docs.DocumentNotFoundException' was thrown.
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.DownloadWebContentAsStringAsync(String rawUrl, String token, String userAgent) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 152
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.GetDocumentAsync(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 49
   at Volo.Docs.Documents.DocumentAppService.<>c__DisplayClass13_0.<<GetDocumentWithDetailsDto>g__GetDocumentAsync|0>d.MoveNext() in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.Caching.DistributedCache`1.GetOrAddAsync(String key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
   at Volo.Docs.Documents.DocumentAppService.GetDocumentWithDetailsDto(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 116
   at Volo.Docs.Documents.DocumentAppService.GetAsync(GetDocumentInput input) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 36
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ValidationInterceptor.cs:line 43
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47

**Comment by maliming** [comment]
Please refer to below configuration .

![image](https://user-images.githubusercontent.com/6908465/91649772-03f5c600-eaaa-11ea-8b48-f906ca89b521.png)

**Comment by nischalsanghal** [comment]
Ok followed exactly as in the doc, still ran into 500


2020-08-29 23:09:16.158 -07:00 [INF] Sending HTTP request GET "https://raw.githubusercontent.com/abpframework/abp/master/docs/en/Index.md"
2020-08-29 23:09:16.571 -07:00 [INF] Received HTTP response after 411.4931ms - "NotFound"
2020-08-29 23:09:16.573 -07:00 [INF] End processing HTTP request after 420.60560000000004ms - "NotFound"
2020-08-29 23:09:16.579 -07:00 [WRN] Response status code does not indicate success: 404 (Not Found).
2020-08-29 23:09:16.583 -07:00 [INF] Executed page /Documents/Project/Index in 448.9349ms
2020-08-29 23:09:16.583 -07:00 [ERR] Connection id "0HM2CLAQ3E5H3", Request id "0HM2CLAQ3E5H3:00000002": An unhandled exception was thrown by the application.
Volo.Docs.DocumentNotFoundException: Exception of type 'Volo.Docs.DocumentNotFoundException' was thrown.
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.DownloadWebContentAsStringAsync(String rawUrl, String token, String userAgent) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 152
   at Volo.Docs.GitHub.Documents.GithubDocumentStore.GetDocumentAsync(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Domain\Volo\Docs\GitHub\Documents\GithubDocumentStore.cs:line 49
   at Volo.Docs.Documents.DocumentAppService.<>c__DisplayClass13_0.<<GetDocumentWithDetailsDto>g__GetDocumentAsync|0>d.MoveNext() in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.Caching.DistributedCache`1.GetOrAddAsync(String key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
   at Volo.Docs.Documents.DocumentAppService.GetDocumentWithDetailsDto(Project project, String documentName, String version) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 116
   at Volo.Docs.Documents.DocumentAppService.GetAsync(GetDocumentInput input) in D:\Github\abp\modules\docs\src\Volo.Docs.Application\Volo\Docs\Documents\DocumentAppService.cs:line 36

**Comment by yekalkan** [comment]
> 2020-08-29 23:09:16.158 -07:00 [INF] Sending HTTP request GET "https://raw.githubusercontent.com/abpframework/abp/master/docs/en/Index.md"

A branch named "master" doesn't exist anymore. So, 404 error is normal.

Can you share your full configuration like the screenshot below?

![image](https://user-images.githubusercontent.com/5793291/91694746-c2cae800-eb75-11ea-8456-90f76b2d0ba6.png)

**Comment by nischalsanghal** [comment]
Ok that helps. I had master in the url. If I replace it with dev it works for ABP Framework. But the issue is still there for my repo

I have a private repo and the raw url has a token at the end:
https://raw.githubusercontent.com/chiropad/docs/master/README.md?token=AKLX6E7S2CGIJ57OZW4MVX27JVBO4

So I am putting this as the root url in the setup: https://github.com/chiropad/docs/master/
![image](https://user-images.githubusercontent.com/43482899/91755200-90be8380-eb7f-11ea-9c3a-a3a3622c52ea.png)

And here's the error, probably because the token is mising. Need some help to figure out how to properly configure the url.

2020-08-31 11:35:38.239 -07:00 [INF] Sending HTTP request GET "https://raw.githubusercontent.com/chiropad/docs/master/README.md"
2020-08-31 11:35:38.447 -07:00 [INF] Received HTTP response after 208.1455ms - "NotFound"
2020-08-31 11:35:38.447 -07:00 [INF] End processing HTTP request after 208.3264ms - "NotFound"
2020-08-31 11:35:38.448 -07:00 [WRN] Response status code does not indicate success: 404 (Not Found).
2020-08-31 11:35:38.448 -07:00 [INF] Executed page /Documents/Project/Index in 225.33190000000002ms
2020-08-31 11:35:38.449 -07:00 [ERR] Connection id "0HM2CLAQ3E5I6", Request id "0HM2CLAQ3E5I6:00000004": An unhandled exception was thrown by the application.
Volo.Docs.DocumentNotFoundException: Exception of type 'Volo.Docs.DocumentNotFoundException' was thrown.

**Comment by yekalkan** [comment]
root url for abp docs: `https://github.com/abpframework/abp/tree/{version}/docs/`

I can't see your repository, so you have to set root url for your project yourself. It shouldn't be hard.

**Comment by nischalsanghal** [comment]
It is a private repository. 
If I do a curl with github access token, like below, it pulls the file, so the root url is correct:
curl -H "Authorization: token mygithubaccesstoken" https://raw.githubusercontent.com/chiropad/docs/master/README.md

It appears that the access token is not getting passed correctly. By the way, single quote around Authorization: token.... did not work.

**Comment by nischalsanghal** [comment]
Any thoughts or suggestions. Did you guys try with a private repository to see the behavior with latest code?
