### ISSUE TITLE
Exception when using IIdentityUserRepository or IdentityUserManager 

### ISSUE THREAD

**Issue by leandro-almeida** [abpframework/abp#5495]
Hi, first of all, this framework is awesome. I think the .net community is lacking some good frameworks like Abp. We need frameworks like Spring in Java.

So I'm trying to execute the following code in my **ApplicationService**:
```csharp
public class UsuarioAppService : ApplicationService
    {
        private readonly IIdentityUserRepository _identityUserRepository;

        public UsuarioAppService(IIdentityUserRepository identityUserRepository)
        {
            _identityUserRepository = identityUserRepository;
        }

        public async Task<IList<IdentityUser>> ObterUsuariosDoPerfilAsync(string perfil)
        {
            Check.NotNullOrWhiteSpace(perfil, nameof(perfil));
            return await _identityUserRepository.GetListByNormalizedRoleNameAsync(perfil.ToUpper()); // exception here
        }
    }
```

**Exception:	{"A DbContext can only be created inside a unit of work!"}	Volo.Abp.AbpException**

I dont know if this is not permited. I've tried referencing also `Volo.Abp.Identity.IdentityUserManager` and calling the method `_identityUserManager.GetUsersInRoleAsync()` but got the same exception.

Also tried another approach in Razor Page Model with IdentityUserManager:

```csharp
private readonly IdentityUserManager _identityUserManager;

        public EditModalModel(IMinisterioAppService ministerioAppService, IdentityUserManager identityUserManager)
        {
            _ministerioAppService = ministerioAppService;
            _identityUserManager = identityUserManager;
        }

        public async void OnGetAsync(Guid id)
        {
            Ministerio = ObjectMapper.Map<MinisterioDto, CreateUpdateMinisterioDto>(
                await _ministerioAppService.GetAsync(id)
            );

            IdMinisterio = id;

            var usuariosMembros = await _identityUserManager.GetUsersInRoleAsync(CelebraRoles.Membro); // same exception here
            Usuarios = usuariosMembros
                .Select(x => new SelectListItem(x.ObterNomeCompleto(), x.Id.ToString()))
                .ToList();
        }
```

BUT, what is more strange is that sometimes i dont receive the exception, and it works, without changing a line of code.

Please, am i doing something wrong?

* ABP Framework version: 3.1.2
* Stacktrace:
```
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider1.GetDbContext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository2.get_DbContext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository2.get_DbSet()
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.<GetListByNormalizedRoleNameAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__141.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue1.<ProceedAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter1.<InterceptAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at EternaSoft.Celebra.UserApp.UsuarioAppService.<ObterUsuariosDoPerfilAsync>d__2.MoveNext() in D:\GITLAB\EternaSoft\Celebra\src\EternaSoft.Celebra.Application\UserApp\UsuarioAppService.cs:line 21
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at EternaSoft.Celebra.Web.Pages.Ministerios.CreateModalModel.<OnGetAsync>d__11.MoveNext() in D:\GITLAB\EternaSoft\Celebra\src\EternaSoft.Celebra.Web\Pages\Ministerios\CreateModal.cshtml.cs:line 31
```

![image](https://user-images.githubusercontent.com/1966285/93653502-92959d00-f9ef-11ea-9bce-008459540768.png)

**Comment by leandro-almeida** [comment]
I forgot to mention that i'm using PostgreSQL 12.

**Comment by maliming** [comment]
hi

Try make `ObterUsuariosDoPerfilAsync` method **virtual**.
```cs
public virtual async Task<IList<IdentityUser>> ObterUsuariosDoPerfilAsync(string perfil)
```


By the way, Don't use `void` as an async method return type.

**Comment by leandro-almeida** [comment]
> 
> 
> hi
> 
> Try make `ObterUsuariosDoPerfilAsync` method **virtual**.
> 
> ```cs
> public virtual async Task<IList<IdentityUser>> ObterUsuariosDoPerfilAsync(string perfil)
> ```
> 
> By the way, Don't use `void` as an async method return type.

Hi @maliming! Thank you for fast replying!
It worked, both cases. Also i've changed to `Task` the returning type in `void` methods, thanks!
I think i will sticky to the solution that references the `UsuarioAppService` inside the PageModel, instead of `IdentityUserManager`, it is the recommended way right?

**Comment by maliming** [comment]
hi @leandro-almeida 

You should use an interface instead of a class.

Please refer to https://docs.abp.io/en/abp/latest/Best-Practices/Module-Architecture

**Comment by leandro-almeida** [comment]
Hi @maliming thanks for your support! 
I have already extracted the interface. Much better now. Thanks!

```csharp
    public interface IUsuarioAppService : IApplicationService
    {
        Task<IList<UserData>> ObterUsuariosDoPerfilAsync(string perfil);
    }
```
