### ISSUE TITLE
Authorization failed! Given policy has not granted

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#5572]
Hi !

I have same problem error as @ertucaglar in #5220 .
I'm using ABP 3.1.1. 

When backend is starting in Visual studio on local machine i can loggin using /account/login and after that executin f.e. editions get method.

But if i deploy to ISS on application in sub folter for example http://some.domain.si/vspi/api i can 

- login on http://some.domain.si/vspi/api/account/login
- execute method without athentication in swagger

but cannon executed autheticated method like get editions.

In log there is only two types of error:

**1. When starting service:**

```
2020-09-22 14:13:51.120 +02:00 [ERR] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {21f162b8-cd2c-48e7-9775-17d54da6ac1a} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

```

**2. When executing get editions method:**

2020-09-22 14:11:32.422 +02:00 [INF] Request starting HTTP/1.1 GET http://demo.sebit.si/vspi/api/api/saas/editions  
2020-09-22 14:11:32.433 +02:00 [INF] Executing endpoint 'Volo.Saas.Host.EditionController.GetListAsync (Volo.Saas.Host.HttpApi)'
2020-09-22 14:11:32.434 +02:00 [INF] Route matched with {area = "saas", controller = "Edition", action = "GetList", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[Volo.Saas.Host.Dtos.EditionDto]] GetListAsync(Volo.Saas.Host.Dtos.GetEditionsInput) on controller Volo.Saas.Host.EditionController (Volo.Saas.Host.HttpApi).
2020-09-22 14:11:32.451 +02:00 [INF] Authorization failed.
2020-09-22 14:11:32.452 +02:00 [WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "Authorization failed! Given policy has not granted.",
  "details": null,
  "validationErrors": null
}

```
2020-09-22 14:11:32.452 +02:00 [WRN] Authorization failed! Given policy has not granted.
Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! Given policy has not granted.
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)

```

I noticed that there is a lot of info messages like 

```
2020-09-22 14:14:00.259 +02:00 [INF] Route matched with {area = "Abp", action = "Get", controller = "AbpApplicationConfigurationScript", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController (Volo.Abp.AspNetCore.Mvc).
2020-09-22 14:14:00.391 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.

```

Should i configure something special for that kind of deployement ?

My appsettings.json (part of it) is:

```
  "pathBase": "vspi/api",
  "App": {
    "SelfUrl": "http://some.domain.si/vspi/api",
    "ClientUrl": "http://localhost:4200",
    "CorsOrigins": "http://some.domain.si"
  },
  "ConnectionStrings": {
    "Default": "Server=......",
  },
  "AuthServer": {
    "Authority": "http://some.domain.si/vspi/api"
  },

```
IdentityServer and API are in same service.

Please advice, because i don't know where to start. 

P.S: There was no broblems with 3.0.x version.

**Comment by sebitsi** [comment]
Hi. After some digging and searching i found that my problem is related to #5138 and [SameSite Cookie Changes](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/). 
All this is explained in [How to fix the Chrome login issue for the IdentityServer4](https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n) . :(

I suggest to put some warnings in ABP documentation. 

But still.

After implementing this fix there are still two errors in log:

**1. When starting service:**
```

2020-09-22 14:13:51.120 +02:00 [ERR] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {21f162b8-cd2c-48e7-9775-17d54da6ac1a} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
and 

**2. info messages:**

```
2020-09-22 14:14:00.259 +02:00 [INF] Route matched with {area = "Abp", action = "Get", controller = "AbpApplicationConfigurationScript", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController (Volo.Abp.AspNetCore.Mvc).
2020-09-22 14:14:00.391 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.
2020-09-22 14:14:00.392 +02:00 [INF] Authorization failed.

```

Can you explain what that errors and infos are.

**Comment by leonkosak** [comment]
After upgrading abp from v3.0.4 to v3.1.2 (Angular GUI, **non-separated** Identity Server), I have the login issue to:

![image](https://user-images.githubusercontent.com/39346964/93974040-84d87280-fd75-11ea-8c9a-d8a6612d81b7.png)

Log:

```
2020-09-23 08:12:07.322 +02:00 [INF] Request starting HTTP/1.1 GET http://xxxx/api/abp/application-configuration  
2020-09-23 08:12:07.328 +02:00 [INF] CORS policy execution successful.
2020-09-23 08:12:07.330 +02:00 [INF] No CORS policy found for the specified request.
2020-09-23 08:12:07.332 +02:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2020-09-23 08:12:07.333 +02:00 [INF] Route matched with {area = "abp", action = "Get", controller = "AbpApplicationConfiguration", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto] GetAsync() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController (Volo.Abp.AspNetCore.Mvc).
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.336 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.337 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.338 +02:00 [INF] Authorization failed.
2020-09-23 08:12:07.347 +02:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto'.
2020-09-23 08:12:07.365 +02:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc) in 31.5414ms
2020-09-23 08:12:07.365 +02:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2020-09-23 08:12:07.365 +02:00 [INF] Request finished in 43.3781ms 200 application/json; charset=utf-8
```

**Comment by sebitsi** [comment]
@leonkosak 
I suggest you to try login on server first (.../api/account/login). 
If it works then you have problems on angular site. If not this is api (server) side problem.

As you can see errors in your log is in mine too. But app still works. 
I think this info messages is not reasons for your error.

**Comment by leonkosak** [comment]
Crap, I had to change requireHttps property in Angular environment configuration to false.
![image](https://user-images.githubusercontent.com/39346964/93988609-3634d380-fd89-11ea-9a03-387c6d29bdec.png)

I don't know how this worked in previous versions....
