### ISSUE TITLE
Duplicate type with name 'VoloAbpIdentityServerDomainShared_ProcessedByFody' in assembly 'Volo.Abp.IdentityServer.Domain.Shared

### ISSUE THREAD

**Issue by maxrizwork** [abpframework/abp#5577]
I'm using abp ver3.0.5 with an MVC app based on standard template.
Everything was working perfectly and most probably (not 100% sure) after a publish on Azure I started to have this fatal error during the 
`CreateHostBuilder(args).Build().Run();`
inside the program.cs on my .Web project. 

Precisely the error is:
Duplicate type with name 'VoloAbpIdentityServerDomainShared_ProcessedByFody' in assembly 'Volo.Abp.IdentityServer.Domain.Shared, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null'.

and the stacktrace is
`at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo element)
   at Volo.Abp.Modularity.AbpModuleHelper.FindDependedModuleTypes(Type moduleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 23
   at Volo.Abp.Modularity.AbpModuleHelper.AddModuleAndDependenciesResursively(List`1 moduleTypes, Type moduleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 49
   at Volo.Abp.Modularity.AbpModuleHelper.AddModuleAndDependenciesResursively(List`1 moduleTypes, Type moduleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 51
   at Volo.Abp.Modularity.AbpModuleHelper.AddModuleAndDependenciesResursively(List`1 moduleTypes, Type moduleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 51
   at Volo.Abp.Modularity.AbpModuleHelper.AddModuleAndDependenciesResursively(List`1 moduleTypes, Type moduleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 51
   at Volo.Abp.Modularity.AbpModuleHelper.FindAllModuleTypes(Type startupModuleType) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\AbpModuleHelper.cs:line 13
   at Volo.Abp.Modularity.ModuleLoader.FillModules(List`1 modules, IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleLoader.cs:line 47
   at Volo.Abp.Modularity.ModuleLoader.GetDescriptors(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleLoader.cs:line 34
   at Volo.Abp.Modularity.ModuleLoader.LoadModules(IServiceCollection services, Type startupModuleType, PlugInSourceList plugInSources) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleLoader.cs:line 20
   at Volo.Abp.AbpApplicationBase.LoadModules(IServiceCollection services, AbpApplicationCreationOptions options) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 82
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 45
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationWithExternalServiceProvider.cs:line 13
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationFactory.cs:line 37
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationFactory.cs:line 29
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction) in C:\Proj\XYZ\YYY.abp\framework\src\Volo.Abp.Core\Microsoft\Extensions\DependencyInjection\ServiceCollectionApplicationExtensions.cs:line 15
   at XYZ.YYY.XYZ.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Proj\XYZ\YYY.Customers\XYZ\src\XYZ.YYY.XYZ.Web\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at XYZ.YYY.XYZ.Web.Program.Main(String[] args) in C:\Proj\XYZ\YYY.Customers\XYZ\src\XYZ.YYY.XYZ.Web\Program.cs:line 31`

**Comment by maxrizwork** [comment]
I solved it cleaning completely \obj and \bin folders.
Then first I recompiled abp using build-all.ps1
Then I passed to my solution doing the same.

In this way disappeard.
I hope this will help someone in the future with the same problem.
