### ISSUE TITLE
ABP Samples: Microservice Demo Solution in docker

### ISSUE THREAD

**Issue by iwaitu** [abpframework/abp#5612]
I can not login in AuthServer if I deploy this AuthServer.Host in docker. But it work fine when I just run it on vs2019. 
this is log in docker

`
07:05:15.887
Executing endpoint '"Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc)"'
07:05:15.888
Route matched with "{area = \"Abp\", action = \"Get\", controller = \"AbpApplicationConfigurationScript\", page = \"\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get()" on controller "Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController" ("Volo.Abp.AspNetCore.Mvc").
07:05:15.890
Executing AbpApplicationConfigurationAppService.GetAsync()...
07:05:15.891
Authorization failed.
07:05:15.891
Request starting HTTP/1.1 GET http://id.ivilson.com/Abp/ServiceProxyScript  
07:05:15.891
Authorization failed.
07:05:15.892
Authorization failed.
07:05:15.892
Authorization failed.
07:05:15.892
Authorization failed.
07:05:15.892
Authorization failed.
07:05:15.893
Authorization failed.
07:05:15.893
Authorization failed.
07:05:15.893
Authorization failed.
07:05:15.893
Authorization failed.
07:05:15.894
Authorization failed.
07:05:15.894
Executing endpoint '"Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc)"'
07:05:15.894
Authorization failed.
07:05:15.894
Authorization failed.
07:05:15.895
Authorization failed.
07:05:15.895
Authorization failed.
07:05:15.895
Authorization failed.
07:05:15.896
Authorization failed.
07:05:15.896
Route matched with "{area = \"Abp\", action = \"GetAll\", controller = \"AbpServiceProxyScript\", page = \"\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.ActionResult GetAll(Volo.Abp.AspNetCore.Mvc.ProxyScripting.ServiceProxyGenerationModel)" on controller "Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController" ("Volo.Abp.AspNetCore.Mvc").
07:05:15.903
Executing ContentResult with HTTP Response ContentType of "application/javascript"
07:05:15.904
Executed action "Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc)" in 7.3338ms
07:05:15.904
Executed endpoint '"Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll (Volo.Abp.AspNetCore.Mvc)"'
07:05:15.923
Executed AbpApplicationConfigurationAppService.GetAsync().
07:05:15.929
Executing ContentResult with HTTP Response ContentType of "application/javascript"
07:05:15.930
Executed action "Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc)" in 40.9375ms
07:05:15.930
Executed endpoint '"Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController.Get (Volo.Abp.AspNetCore.Mvc)"'
07:05:15.933
Added 0 entity changes to the current audit log
07:05:15.933
Added 0 entity changes to the current audit log
07:05:15.934
Request finished in 42.2748ms 200 application/javascript
07:05:15.969
Added 0 entity changes to the current audit log
07:05:15.969
Added 0 entity changes to the current audit log
07:05:15.970
Request finished in 86.8447ms 200 application/javascript
`

**Comment by iwaitu** [comment]
I found the problem is ICurrentUser is null if I ran it in docker and login admin account,  but it can work by ran in console or in iis express .

**Comment by fmpfmp** [comment]
check  docker container's network

**Comment by iwaitu** [comment]
```=[09:57:17 INF] Creating key {3e9d313d-e3d6-4526-963b-dee094df222a} with creation date 2020-09-27 09:57:17Z, activation date 2020-09-27 09:57:17Z, and expiration date 2020-12-26 09:57:17Z.
[09:57:17 WRN] No XML encryptor configured. Key {3e9d313d-e3d6-4526-963b-dee094df222a} may be persisted to storage in unencrypted form.
[09:57:17 INF] Loaded ABP modules:
[09:57:17 INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
[09:57:17 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
[09:57:17 INF] - Volo.Abp.Validation.AbpValidationAbstractionsModule
[09:57:17 INF] - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
[09:57:17 INF] - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
[09:57:17 INF] - Volo.Abp.Security.AbpSecurityModule
[09:57:17 INF] - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
[09:57:17 INF] - Volo.Abp.Uow.AbpUnitOfWorkModule
[09:57:17 INF] - Volo.Abp.Data.AbpDataModule
[09:57:17 INF] - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
[09:57:17 INF] - Volo.Abp.Settings.AbpSettingsModule
[09:57:17 INF] - Volo.Abp.Localization.AbpLocalizationModule
[09:57:17 INF] - Volo.Abp.Validation.AbpValidationModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
[09:57:17 INF] - Volo.Abp.Users.AbpUsersDomainSharedModule
[09:57:17 INF] - Volo.Abp.Identity.AbpIdentityDomainSharedModule
[09:57:17 INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
[09:57:17 INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
[09:57:17 INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
[09:57:17 INF] - authservice.authserviceDomainSharedModule
[09:57:17 INF] - Volo.Abp.EventBus.AbpEventBusModule
[09:57:17 INF] - Volo.Abp.Users.AbpUsersAbstractionModule
[09:57:17 INF] - Volo.Abp.Authorization.AbpAuthorizationModule
[09:57:17 INF] - Volo.Abp.Timing.AbpTimingModule
[09:57:17 INF] - Volo.Abp.Json.AbpJsonModule
[09:57:17 INF] - Volo.Abp.Threading.AbpThreadingModule
[09:57:17 INF] - Volo.Abp.Auditing.AbpAuditingModule
[09:57:17 INF] - Volo.Abp.Guids.AbpGuidsModule
[09:57:17 INF] - Volo.Abp.ObjectMapping.AbpObjectMappingModule
[09:57:17 INF] - Volo.Abp.Domain.AbpDddDomainModule
[09:57:17 INF] - Volo.Abp.Application.AbpDddApplicationContractsModule
[09:57:17 INF] - Volo.Abp.Http.AbpHttpAbstractionsModule
[09:57:17 INF] - Volo.Abp.Features.AbpFeaturesModule
[09:57:17 INF] - Volo.Abp.Application.AbpDddApplicationModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
[09:57:17 INF] - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
[09:57:17 INF] - Volo.Abp.Account.AbpAccountApplicationContractsModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
[09:57:17 INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
[09:57:17 INF] - authservice.authserviceApplicationContractsModule
[09:57:17 INF] - Volo.Abp.Minify.AbpMinifyModule
[09:57:17 INF] - Volo.Abp.Http.AbpHttpModule
[09:57:17 INF] - Volo.Abp.UI.AbpUiModule
[09:57:17 INF] - Volo.Abp.AspNetCore.AbpAspNetCoreModule
[09:57:17 INF] - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
[09:57:17 INF] - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
[09:57:17 INF] - Volo.Abp.Identity.AbpIdentityHttpApiModule
[09:57:17 INF] - Volo.Abp.Account.AbpAccountHttpApiModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.HttpApi.AbpPermissionManagementHttpApiModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiModule
[09:57:17 INF] - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiModule
[09:57:17 INF] - authservice.authserviceHttpApiModule
[09:57:17 INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
[09:57:17 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
[09:57:17 INF] - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
[09:57:17 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
[09:57:17 INF] - Volo.Abp.AutoMapper.AbpAutoMapperModule
[09:57:17 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
[09:57:17 INF] - Volo.Abp.Serialization.AbpSerializationModule
[09:57:17 INF] - Volo.Abp.Caching.AbpCachingModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule
[09:57:17 INF] - Volo.Abp.Users.AbpUsersDomainModule
[09:57:17 INF] - Volo.Abp.Identity.AbpIdentityDomainModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
[09:57:17 INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.IdentityServer.AbpPermissionManagementDomainIdentityServerModule
[09:57:17 INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
[09:57:17 INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
[09:57:17 INF] - Volo.Abp.TextTemplating.AbpTextTemplatingModule
[09:57:17 INF] - Volo.Abp.Emailing.AbpEmailingModule
[09:57:17 INF] - authservice.authserviceDomainModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationModule
[09:57:17 INF] - Volo.Abp.Identity.AbpIdentityApplicationModule
[09:57:17 INF] - Volo.Abp.UI.Navigation.AbpUiNavigationModule
[09:57:17 INF] - Volo.Abp.Account.AbpAccountApplicationModule
[09:57:17 INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationModule
[09:57:17 INF] - authservice.authserviceApplicationModule
[09:57:17 INF] - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.Users.EntityFrameworkCore.AbpUsersEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.IdentityServer.EntityFrameworkCore.AbpIdentityServerEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.EntityFrameworkCore.AbpFeatureManagementEntityFrameworkCoreModule
[09:57:17 INF] - authservice.EntityFrameworkCore.authserviceEntityFrameworkCoreModule
[09:57:17 INF] - authservice.EntityFrameworkCore.authserviceEntityFrameworkCoreDbMigrationsModule
[09:57:17 INF] - Volo.Abp.Castle.AbpCastleCoreModule
[09:57:17 INF] - Volo.Abp.Autofac.AbpAutofacModule
[09:57:17 INF] - Volo.Abp.RabbitMQ.AbpRabbitMqModule
[09:57:17 INF] - Volo.Abp.EventBus.RabbitMq.AbpEventBusRabbitMqModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.AbpAspNetCoreMvcUiModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.AbpAspNetCoreMvcUiBootstrapModule
[09:57:17 INF] - Volo.Abp.PermissionManagement.Web.AbpPermissionManagementWebModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Packages.AbpAspNetCoreMvcUiPackagesModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpAspNetCoreMvcUiWidgetsModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.AbpAspNetCoreMvcUiThemeSharedModule
[09:57:17 INF] - Volo.Abp.Identity.Web.AbpIdentityWebModule
[09:57:17 INF] - Volo.Abp.Identity.AspNetCore.AbpIdentityAspNetCoreModule
[09:57:17 INF] - Volo.Abp.Account.Web.AbpAccountWebModule
[09:57:17 INF] - Volo.Abp.Account.Web.AbpAccountWebIdentityServerModule
[09:57:17 INF] - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.AbpAspNetCoreMvcUiBasicThemeModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Authentication.JwtBearer.AbpAspNetCoreAuthenticationJwtBearerModule
[09:57:17 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementWebModule
[09:57:17 INF] - Volo.Abp.TenantManagement.Web.AbpTenantManagementWebModule
[09:57:17 INF] - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
[09:57:17 INF] - authservice.Web.authserviceWebModule
[09:57:18 INF] Starting IdentityServer4 version 3.1.3.0
[09:57:18 INF] Using the default authentication scheme Identity.Application for IdentityServer
[09:57:18 INF] Initialized all ABP modules.
[09:57:18 INF] Now listening on: http://[::]:80
[09:57:18 INF] Application started. Press Ctrl+C to shut down.
[09:57:18 INF] Hosting environment: Production
[09:57:18 INF] Content root path: /app
[09:57:39 INF] Request starting HTTP/1.1 GET http://id.ivilson.com/
[09:57:39 INF] Executing endpoint '/Index'
[09:57:39 INF] Route matched with {page = "/Index", area = "", action = "", controller = ""}. Executing page /Index
[09:57:39 INF] Executing handler method authservice.Web.Pages.IndexModel.OnGet - ModelState is Valid
[09:57:39 INF] Executed handler method OnGet, returned result .
[09:57:39 INF] Executing an implicit handler method - ModelState is Valid
[09:57:39 INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
[09:57:39 ERR] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
---> System.Security.Cryptography.CryptographicException: The key {a1a365db-7a28-4a48-a475-ae5147280f41} was not found in the key ring.
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
--- End of inner exception stack trace ---
at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)```



I found the problem, it started to create a key {3e9d313d-e3d6-4526-963b-dee094df222a} and stored it in redis. However, according to the log, the cause of the last error was The key {a1a365db-7a28-4a48-a475-ae5147280f41 } was not found in the key ring.
 Why are the two key ids different?

**Comment by GotzeWong** [comment]
Same issues. Are there any solutions?

**Comment by GotzeWong** [comment]
> I found the problem, it started to create a key {3e9d313d-e3d6-4526-963b-dee094df222a} and stored it in redis. However, according to the log, the cause of the last error was The key {a1a365db-7a28-4a48-a475-ae5147280f41 } was not found in the key ring.  Why are the two key ids different?

Same issues. Are there any solutions?
