### ISSUE TITLE
Exception in Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver.Resolve(String connectionStringName)  when use  async foreach

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#5649]
### Code
 var list = new List<int>() { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
list.ForEach(async (item) => 
{
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
                await optionRepository.GetMongoQueryable().FirstOrDefaultAsync();
});

// use foreach(var item in list){}   work well  ，but use list.ForEach(async (item) =>{}) will  throw exception
//MultiTenancy is enable

### Exception

Unhandled exception. System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(IServiceProvider provider)
   at Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver.Resolve(String connectionStringName)
   at Volo.Abp.Data.ConnectionStringResolverExtensions.Resolve[T](IConnectionStringResolver resolver)
   at Volo.Abp.Uow.MongoDB.UnitOfWorkMongoDbContextProvider`1.GetDbContext()
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.get_DbContext()
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.get_Collection()
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.GetMongoQueryable()
   at Castle.Proxies.Invocations.IMongoDbRepository`1_GetMongoQueryable_1.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedSynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.Rethrow(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowInnerIfAggregate(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowIfFaulted(Task task)
   at Castle.DynamicProxy.AsyncInterceptorBase.InterceptSynchronousResult[TResult](AsyncInterceptorBase me, IInvocation invocation)
   at Castle.DynamicProxy.AsyncInterceptorBase.Castle.DynamicProxy.IAsyncInterceptor.InterceptSynchronous(IInvocation invocation)
   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IBasicRepository`1Proxy_1.GetMongoQueryable()
   at Volo.Abp.Domain.Repositories.MongoDbCoreRepositoryExtensions.GetMongoQueryable[TEntity,TKey](IBasicRepository`2 repository)
   at X.Owl.Service.OwlService.<GetProjects>b__84_0(Int32 item) in \Service\OwlService.Project.cs:line 94
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by realLiangshiwei** [comment]
Use `async foreach` https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/async-streams
