### ISSUE TITLE
IPermissionManager throws exception when using extension SetForUserAsync on a system with MutliTenants

### ISSUE THREAD

**Issue by GoodfellowMunro1981** [abpframework/abp#5669]
ABP Framework version: 3.2.0

'FeatureManagement.ManageHostFeatures' has multitenancy side 'Host' which is not compatible with the current multitenancy side 'Tenant''

await _permissionManager.SetForUserAsync(existingUser.Id, permission.Name, true);

namespace Volo.Abp.PermissionManagement
{
    public static class UserPermissionManagerExtensions
    {
        public static Task SetForUserAsync(this IPermissionManager permissionManager, Guid userId, string name, bool isGranted);
    }
}

Call Stack
at Volo.Abp.PermissionManagement.PermissionManager.<SetAsync>d__21.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at PeopleDynamix.HCL.Application.DataSeedContributor.<AddAdminPermissionGrants>d__24.MoveNext() 

Using the code from the 3.2 documentation for a site with Multi-Tenancy
https://docs.abp.io/en/abp/latest/Authorization

Permission Management

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.
