### ISSUE TITLE
MapEfCoreProperty requires IEntity which IdentityUser or IdentityRole is not

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#5684]
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core

https://github.com/abpframework/abp/blob/a9b228a2dd7cf6eaa0529a7273991019d55918ab/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/ObjectExtending/EfCoreObjectExtensionManagerExtensions.cs#L80-L92

Focus line 84, it requires an entity type that inherited `IEntity`.
So I can't use the method to extend `IdentityUser` or `IdentityRole`.

**Comment by PMExtra** [comment]
When I called `MapEfCoreProperty(typeof(IdentityUser), typeof(string), nameof(AppUser.Sth))`, I got:

```
System.ArgumentException: type (type of Microsoft.AspNetCore.Identity.IdentityUser, Microsoft.Extensions.Identity.Stores, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) should be assignable to the Volo.Abp.Data.IHasExtraProperties, Volo.Abp.ObjectExtending!
   at Volo.Abp.Check.AssignableTo[TBaseType](Type type, String parameterName)
   at Volo.Abp.ObjectExtending.ObjectExtensionManager.AddOrUpdate(Type type, Action`1 configureAction)
   at Volo.Abp.ObjectExtending.ObjectExtensionManagerExtensions.AddOrUpdateProperty(ObjectExtensionManager objectExtensionManager, Type objectType, Type propertyType, String propertyName, Action`1 configureAction)
   at Volo.Abp.ObjectExtending.EfCoreObjectExtensionManagerExtensions.MapEfCoreProperty(ObjectExtensionManager objectExtensionManager, Type entityType, Type propertyType, String propertyName)
   at Djet.Aota.EntityFrameworkCore.AotaEfCoreEntityExtensionMappings.<>c.<Configure>b__1_0() in C:\Users\HakunaMatata\Documents\Projects\Djet.Aota\New\aspnet-core\src\Djet.Aota.EntityFrameworkCore\EntityFrameworkCore\AotaEfCoreEntityExtensionMappings.cs:line 44
   at Volo.Abp.Threading.OneTimeRunner.Run(Action action)
   at Djet.Aota.EntityFrameworkCore.AotaEfCoreEntityExtensionMappings.Configure() in C:\Users\HakunaMatata\Documents\Projects\Djet.Aota\New\aspnet-core\src\Djet.Aota.EntityFrameworkCore\EntityFrameworkCore\AotaEfCoreEntityExtensionMappings.cs:line 18
   at Djet.Aota.EntityFrameworkCore.AotaMigrationsDbContextFactory.CreateDbContext(String[] args) in C:\Users\HakunaMatata\Documents\Projects\Djet.Aota\New\aspnet-core\src\Djet.Aota.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\AotaMigrationsDbContextFactory.cs:line 14
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass15_0.<FindContextFactory>b__1()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
type (type of Microsoft.AspNetCore.Identity.IdentityUser, Microsoft.Extensions.Identity.Stores, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) should be assignable to the Volo.Abp.Data.IHasExtraProperties, Volo.Abp.ObjectExtending!
```

**Comment by realLiangshiwei** [comment]
System.ArgumentException: type (type of **Microsoft.AspNetCore.Identity.IdentityUser**, Microsoft.Extensions.Identity.Stores

You should use [`Volo.Abp.Identity.IdentityUser`](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUser.cs)

**Comment by PMExtra** [comment]
@realLiangshiwei  Thank you for saving my day. I'm so sorry for the low-level mistake.
