### ISSUE TITLE
Can't deserialize object 'ExtraProperties'

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#5686]
ABP v3.1.0, MySql (MariaDB 10.4) 

I am trying to store a `[Serializable]` class instance in the `ExtraProperties` of an AggregateRoot entity. It is serializing to JSON in the database perfectly, but getting it back out of the database is not working as expected. I also followed [your guide](https://docs.abp.io/en/abp/latest/Object-Extensions) but couldn't find anything that helped.

I expected to be able to cast the object back in the same form that it was added to the ExtraProperties dictionary but this won't work. I have to convert the object to a string before deserializing it. I looked at the [source code](https://github.com/abpframework/abp/blob/e65f5bfd7378ddb691b57f130a896797a3d183ac/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/ValueConverters/ExtraPropertiesValueConverter.cs) and found you are using Newtonsoft to serialize/deserialize so I use the same in the example class below..

```csharp
public class ApiConfig : FullAuditedAggregateRoot<Guid>//, IHasExtraProperties
{
    public void SetCustomObjects(List<CustomObject> fields)
    {
        if (fields == null || fields.Count == 0)
        {
            ExtraProperties.Remove(ApiConfigConsts.ExtraPropertyNames.CustomObject);
        }
        else
        {
            if (ExtraProperties.ContainsKey(ApiConfigConsts.ExtraPropertyNames.CustomObject))
            {
                ExtraProperties[ApiConfigConsts.ExtraPropertyNames.CustomObject] = fields;
            }
            else
            {
                ExtraProperties.Add(ApiConfigConsts.ExtraPropertyNames.CustomObject, fields);
            }
        }
    }

    public List<FreshdeskTicketField> GetCustomObjects()
    {
        ExtraProperties.TryGetValue(ApiConfigConsts.ExtraPropertyNames.CustomObject, out object fieldObject);

        // This DOESNT work..
        // return fieldObject as List<CustomObject>;

        // This DOES work - but why do we have to convert to a string first?
        return Newtonsoft.Json.JsonConvert.DeserializeObject<List<CustomObject>>(
            fieldObject.ToString());
    }
}

[Serializable]
public class CustomObject
{
    public string StringProp { get; set; }

    // This also needs converting to a string and deserializing otherwise it is also a 'JObject'/'JArray'
    public object ObjectProp { get; set; }
}
```

Stacktrace:
```
[ERR][45][Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Collections.Generic.List`1[MyProject.CustomObject]'.
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'System.Collections.Generic.List`1[MyProject.CustomObject]'.
   at MyProject.ApiConfig.GetCustomObject() in C:\Projects\MyProject\ApiConfig.cs:line 91
   at MyProject.ApiConfigAppService.GetCustomObjectAsync(Nullable`1 id) in C:\Projects\MyProject\MyProject.Application\ApiConfigAppService.cs:line 90
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by maliming** [comment]
I think this is a json serialize/deserialize problem and has nothing to do with abp.

You can try to serialize your dto to string using json.net, and then try to deserialize it from string to dto, I think this will also have problems.
