### ISSUE TITLE
ABP Blazor Sample: Tenant not found error

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5691]
To reproduce:

1) download the sample blazor app (https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore)
2) run the migration project
3) run the host project

gives an error:

>Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by 274188A** [comment]
### Log

>2020-10-03 11:35:22.381 +08:00 [INF] Starting Acme.BookStore.HttpApi.Host.
2020-10-03 11:35:26.945 +08:00 [INF] User profile is available. Using 'C:\Users\274188A\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2020-10-03 11:35:27.006 +08:00 [INF] Loaded ABP modules:
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Validation.AbpValidationAbstractionsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Security.AbpSecurityModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Uow.AbpUnitOfWorkModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Data.AbpDataModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Settings.AbpSettingsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Localization.AbpLocalizationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Validation.AbpValidationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Users.AbpUsersDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Features.AbpFeaturesModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AbpIdentityDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreDomainSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.EventBus.AbpEventBusModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Users.AbpUsersAbstractionModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Authorization.AbpAuthorizationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Timing.AbpTimingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Json.AbpJsonModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Threading.AbpThreadingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Auditing.AbpAuditingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Guids.AbpGuidsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Domain.AbpDddDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Application.AbpDddApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Http.AbpHttpAbstractionsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Application.AbpDddApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Account.AbpAccountApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreApplicationContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Minify.AbpMinifyModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Http.AbpHttpModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.UI.AbpUiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.AbpAspNetCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AbpIdentityHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Account.AbpAccountHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.HttpApi.AbpPermissionManagementHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreHttpApiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Castle.AbpCastleCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Autofac.AbpAutofacModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AutoMapper.AbpAutoMapperModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Serialization.AbpSerializationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Caching.AbpCachingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Users.AbpUsersDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AbpIdentityDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.IdentityServer.AbpPermissionManagementDomainIdentityServerModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TextTemplating.AbpTextTemplatingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Emailing.AbpEmailingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreDomainModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AbpIdentityApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.UI.Navigation.AbpUiNavigationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Account.AbpAccountApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreApplicationModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Users.EntityFrameworkCore.AbpUsersEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.IdentityServer.EntityFrameworkCore.AbpIdentityServerEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.EntityFrameworkCore.SqlServer.AbpEntityFrameworkCoreSqlServerModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.FeatureManagement.EntityFrameworkCore.AbpFeatureManagementEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.EntityFrameworkCore.BookStoreEntityFrameworkCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.EntityFrameworkCore.BookStoreEntityFrameworkCoreDbMigrationsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.AbpAspNetCoreMvcUiModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.AbpAspNetCoreMvcUiBootstrapModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Packages.AbpAspNetCoreMvcUiPackagesModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpAspNetCoreMvcUiWidgetsModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.AbpAspNetCoreMvcUiThemeSharedModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.AbpAspNetCoreMvcUiBasicThemeModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Authentication.JwtBearer.AbpAspNetCoreAuthenticationJwtBearerModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Identity.AspNetCore.AbpIdentityAspNetCoreModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Account.Web.AbpAccountWebModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.Account.Web.AbpAccountWebIdentityServerModule
2020-10-03 11:35:27.006 +08:00 [INF] - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
2020-10-03 11:35:27.006 +08:00 [INF] - Acme.BookStore.BookStoreHttpApiHostModule
2020-10-03 11:35:27.297 +08:00 [DBG] Started background worker: Volo.Abp.BackgroundJobs.BackgroundJobWorker
2020-10-03 11:35:27.300 +08:00 [DBG] Started background worker: Volo.Abp.IdentityServer.Tokens.TokenCleanupBackgroundWorker
2020-10-03 11:35:29.959 +08:00 [INF] Starting IdentityServer4 version 3.1.3.0
2020-10-03 11:35:30.357 +08:00 [INF] Using the default authentication scheme Identity.Application for IdentityServer
2020-10-03 11:35:30.357 +08:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for authentication
2020-10-03 11:35:30.357 +08:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-in
2020-10-03 11:35:30.357 +08:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-out
2020-10-03 11:35:30.357 +08:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for challenge
2020-10-03 11:35:30.357 +08:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for forbid
2020-10-03 11:35:30.621 +08:00 [INF] Initialized all ABP modules.
2020-10-03 11:35:30.638 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2020-10-03 11:35:30.638 +08:00 [INF] Hosting environment: Development
2020-10-03 11:35:30.638 +08:00 [INF] Content root path: C:\Users\274188A\source\repos\abp-samples\BookStore-Blazor-EfCore\src\Acme.BookStore.HttpApi.Host
2020-10-03 11:35:30.691 +08:00 [INF] Request starting HTTP/2.0 GET https://localhost:44381/  
2020-10-03 11:35:31.328 +08:00 [INF] Entity Framework Core 3.1.6 initialized 'SettingManagementDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-10-03 11:35:31.797 +08:00 [INF] Executed DbCommand (53ms) [Parameters=[@__providerName_0='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT [a].[Id], [a].[Name], [a].[ProviderKey], [a].[ProviderName], [a].[Value]
FROM [AbpSettings] AS [a]
WHERE ([a].[ProviderName] = @__providerName_0) AND [a].[ProviderKey] IS NULL
2020-10-03 11:35:31.914 +08:00 [INF] Entity Framework Core 3.1.6 initialized 'SettingManagementDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-10-03 11:35:31.924 +08:00 [INF] Executed DbCommand (3ms) [Parameters=[@__providerName_0='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT [a].[Id], [a].[Name], [a].[ProviderKey], [a].[ProviderName], [a].[Value]
FROM [AbpSettings] AS [a]
WHERE ([a].[ProviderName] = @__providerName_0) AND [a].[ProviderKey] IS NULL
2020-10-03 11:35:31.980 +08:00 [DBG] Login Url: /Account/Login
2020-10-03 11:35:31.980 +08:00 [DBG] Login Return Url Parameter: ReturnUrl
2020-10-03 11:35:31.980 +08:00 [DBG] Logout Url: /Account/Logout
2020-10-03 11:35:31.980 +08:00 [DBG] ConsentUrl Url: /Consent
2020-10-03 11:35:31.980 +08:00 [DBG] Consent Return Url Parameter: returnUrl
2020-10-03 11:35:31.980 +08:00 [DBG] Error Url: /Account/Error
2020-10-03 11:35:31.980 +08:00 [DBG] Error Id Parameter: errorId
2020-10-03 11:35:32.246 +08:00 [INF] Entity Framework Core 3.1.6 initialized 'TenantManagementDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-10-03 11:35:32.316 +08:00 [INF] Executed DbCommand (4ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__id_0='?' (DbType = Guid)], CommandType='"Text"', CommandTimeout='30']
SELECT [t].[Id], [t].[ConcurrencyStamp], [t].[CreationTime], [t].[CreatorId], [t].[DeleterId], [t].[DeletionTime], [t].[ExtraProperties], [t].[IsDeleted], [t].[LastModificationTime], [t].[LastModifierId], [t].[Name], [a0].[TenantId], [a0].[Name], [a0].[Value]
FROM (
    SELECT TOP(1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[CreatorId], [a].[DeleterId], [a].[DeletionTime], [a].[ExtraProperties], [a].[IsDeleted], [a].[LastModificationTime], [a].[LastModifierId], [a].[Name]
    FROM [AbpTenants] AS [a]
    WHERE ((@__ef_filter__p_0 = CAST(1 AS bit)) OR ([a].[IsDeleted] <> CAST(1 AS bit))) AND ([a].[Id] = @__id_0)
) AS [t]
LEFT JOIN [AbpTenantConnectionStrings] AS [a0] ON [t].[Id] = [a0].[TenantId]
ORDER BY [t].[Id], [a0].[TenantId], [a0].[Name]
2020-10-03 11:35:32.339 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-03 11:35:32.426 +08:00 [INF] Request finished in 1736.602ms 500 text/html; charset=utf-8
2020-10-03 11:35:32.449 +08:00 [INF] Entity Framework Core 3.1.6 initialized 'BackgroundJobsDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-10-03 11:35:32.468 +08:00 [INF] Executed DbCommand (9ms) [Parameters=[@__p_1='?' (DbType = Int32), @__now_0='?' (DbType = DateTime2)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[ExtraProperties], [a].[IsAbandoned], [a].[JobArgs], [a].[JobName], [a].[LastTryTime], [a].[NextTryTime], [a].[Priority], [a].[TryCount]
FROM [AbpBackgroundJobs] AS [a]
WHERE ([a].[IsAbandoned] <> CAST(1 AS bit)) AND ([a].[NextTryTime] <= @__now_0)
ORDER BY [a].[Priority] DESC, [a].[TryCount], [a].[NextTryTime]
2020-10-03 11:35:32.587 +08:00 [INF] Request starting HTTP/2.0 GET https://localhost:44381/favicon.ico  
2020-10-03 11:35:32.592 +08:00 [INF] Entity Framework Core 3.1.6 initialized 'TenantManagementDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2020-10-03 11:35:32.597 +08:00 [INF] Executed DbCommand (3ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__id_0='?' (DbType = Guid)], CommandType='"Text"', CommandTimeout='30']
SELECT [t].[Id], [t].[ConcurrencyStamp], [t].[CreationTime], [t].[CreatorId], [t].[DeleterId], [t].[DeletionTime], [t].[ExtraProperties], [t].[IsDeleted], [t].[LastModificationTime], [t].[LastModifierId], [t].[Name], [a0].[TenantId], [a0].[Name], [a0].[Value]
FROM (
    SELECT TOP(1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[CreatorId], [a].[DeleterId], [a].[DeletionTime], [a].[ExtraProperties], [a].[IsDeleted], [a].[LastModificationTime], [a].[LastModifierId], [a].[Name]
    FROM [AbpTenants] AS [a]
    WHERE ((@__ef_filter__p_0 = CAST(1 AS bit)) OR ([a].[IsDeleted] <> CAST(1 AS bit))) AND ([a].[Id] = @__id_0)
) AS [t]
LEFT JOIN [AbpTenantConnectionStrings] AS [a0] ON [t].[Id] = [a0].[TenantId]
ORDER BY [t].[Id], [a0].[TenantId], [a0].[Name]
2020-10-03 11:35:32.602 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-03 11:35:32.609 +08:00 [INF] Request finished in 22.2271ms 500 text/plain

**Comment by 274188A** [comment]
the SQL run in the scenario where there are no Tenants set up and or no Tenant connection strings set up fails - assumes we already have a Tenant possibly:

```
SELECT [t].[Id], [t].[ConcurrencyStamp], [t].[CreationTime], [t].[CreatorId], [t].[DeleterId], [t].[DeletionTime], [t].[ExtraProperties], [t].[IsDeleted], [t].[LastModificationTime], [t].[LastModifierId], [t].[Name], [a0].[TenantId], [a0].[Name], [a0].[Value]
FROM (
SELECT TOP(1) [a].[Id], [a].[ConcurrencyStamp], [a].[CreationTime], [a].[CreatorId], [a].[DeleterId], [a].[DeletionTime], [a].[ExtraProperties], [a].[IsDeleted], [a].[LastModificationTime], [a].[LastModifierId], [a].[Name]
FROM [AbpTenants] AS [a]
WHERE ((@__ef_filter__p_0 = CAST(1 AS bit)) OR ([a].[IsDeleted] <> CAST(1 AS bit))) AND ([a].[Id] = @__id_0)
) AS [t]
LEFT JOIN [AbpTenantConnectionStrings] AS [a0] ON [t].[Id] = [a0].[TenantId]
ORDER BY [t].[Id], [a0].[TenantId], [a0].[Name]

```

**Comment by rlavaud** [comment]
You most likely had another project with a tenant created while your new project does not. Clear your Browser cache and browser storage. You have to clear the browser storage because blazor stores the dll and session in the browser storage. I had the same issues and this solved it for me.
