### ISSUE TITLE
Error when trying to create the database using migrations

### ISSUE THREAD

**Issue by robertosistemas** [abpframework/abp#5745]
Firebird Version 3

problaly cause:
  http://www.firebirdfaq.org/faq212/
  http://www.firebirdfaq.org/faq211/
  https://www.firebirdsql.org/pdfrefdocs/Firebird-2.1-ErrorCodes.pdf

FirebirdSql.Data.FirebirdClient.FbException: 'unsuccessful metadata update
CREATE TABLE IdentityServerApiSecrets failed
No message for error code 336068726 found.'

Inner Excepiton:
IscException: unsuccessful metadata update
CREATE TABLE IdentityServerApiSecrets failed
No message for error code 336068726 found.

   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Acme.BookStore.EntityFrameworkCore.EntityFrameworkCoreBookStoreDbSchemaMigrator.MigrateAsync() in C:\Desenv\abp\Acme\BookStoreFb\src\Acme.BookStore.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\EntityFrameworkCoreBookStoreDbSchemaMigrator.cs:line 29
   at Acme.BookStore.Data.BookStoreDbMigrationService.MigrateDatabaseSchemaAsync(Tenant tenant) in C:\Desenv\abp\Acme\BookStoreFb\src\Acme.BookStore.Domain\Data\BookStoreDbMigrationService.cs:line 82
   at Acme.BookStore.Data.BookStoreDbMigrationService.MigrateAsync() in C:\Desenv\abp\Acme\BookStoreFb\src\Acme.BookStore.Domain\Data\BookStoreDbMigrationService.cs:line 40
   at Acme.BookStore.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in C:\Desenv\abp\Acme\BookStoreFb\src\Acme.BookStore.DbMigrator\DbMigratorHostedService.cs:line 30
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Acme.BookStore.DbMigrator.Program.Main(String[] args) in C:\Desenv\abp\Acme\BookStoreFb\src\Acme.BookStore.DbMigrator\Program.cs:lin
![evidency](https://user-images.githubusercontent.com/10108804/95504780-a6477a00-0983-11eb-870a-84e73808ede8.png)
e 29
[ErroEvidency.zip](https://github.com/abpframework/abp/files/5350933/ErroEvidency.zip)

**Comment by maliming** [comment]
Did you recreate the migration file?

* Steps needed to **reproduce** the problem.

**Comment by robertosistemas** [comment]
Yes, I recreated the migration files.
I also put in the attached file "Evidency.zip" the complete project with the source code so that you can reproduce the error.
To play, you will have to download and install Firebird 3.06 32-bit version for windows.
Use the ABPFB.sql script that is also inside the zipped file to create the database.
Open the Acme.BookStore.sln solution and run the Acme.BookStore.DbMigrator project.

I was following the steps in the tutorials below when I ran into this problem.

https://docs.abp.io/en/abp/latest/Getting-Started?UI=MVC&DB=EF&Tiered=No

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL

**Comment by robertosistemas** [comment]
The probable cause would be the combination of fields that form the primary key of the IdentityServerApiSecrets table, which exceeds the maximum size allowed for the single index. Couldn't they use an Int, Long or a Guid to define that primary key?

**Comment by robertosistemas** [comment]
If you do not want to create the database from the ABPFB.sql script, you can use the database already created: ABPFB.FDB, both are inside the Evidency.zip file together with the project.

**Comment by robertosistemas** [comment]
Objects with identify bigger than 31 charactes "IdentityServerClientIdPRestrictions" is not allowed to Firebird 3. The same with field names.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/1920

**Comment by Mohamed1973** [comment]
CREATE TABLE PARAMETRES_LIBEXIGENCES
(
  ID integer NOT null,
  LIBELLE varchar(5000),
  CONSTRAINT PK_DOCLIBELLE PRIMARY KEY (ID),
  CONSTRAINT UQ_DOCLIBELLE UNIQUE (LIBELLE)
);

unsuccessful metadata update
CREATE TABLE PARAMETRES_LIBEXIGENCES failed
unknown ISC error 336068726
