### ISSUE TITLE
InternalGateway,  Tenant not found, when Remote request userinfo

### ISSUE THREAD

**Issue by buxueke** [abpframework/abp#5850]
when __tenantId is null , no problem
demo service:
`using(_currentTenant.Change(eventData.Entity.TenantId))` 
 `{`
             `var user = await UserRepository.FindAsync(eventData.Entity.Id);` 
              ` if (user == null)
                {
                    user = await UserLookupService.FindByIdAsync(eventData.Entity.Id);
                    if (user == null)
                    {
                        return;
                    }
                }`

             if (user.Update(eventData.Entity))
                {
                    await UserRepository.UpdateAsync(user);
                }
}

InternalGatewayHost Logs:

2020-10-19 14:44:49.657 +08:00 [INF] Request finished in 6.1015ms 500 
2020-10-19 14:44:57.671 +08:00 [INF] Request starting HTTP/1.1 GET http://localhost:44329/api/appuser/userLookup/5ac0cc2c-8259-d051-f14c-39f85100779a?api-version=1.0  
2020-10-19 14:44:57.679 +08:00 [INF] Successfully validated the token.
2020-10-19 14:44:57.680 +08:00 [DBG] AuthenticationScheme: Bearer was successfully authenticated.
2020-10-19 14:44:57.688 +08:00 [ERR] Connection ID "18158513712053354505", Request ID "8000000f-0003-fc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Volo.Abp.AspNetCore.Security.Claims.AbpClaimsMapMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by buxueke** [comment]
current Identity token no tenantid
