### ISSUE TITLE
Problem to update solution in Abp v.3.3.0

### ISSUE THREAD

**Issue by EugeniZaplatin** [abpframework/abp#5969]
C:\projects\01_Rostelecom\SSKI>abp update C:\projects\SSKI\Sski.IdentityServer.sln
[11:03:26 INF] ABP CLI (https://abp.io)
[11:03:27 INF] Version 3.3.0 (Stable)
[11:04:02 ERR] Unable to get latest preview version.
[11:04:02 ERR] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Volo.Abp.Cli.ProjectModification.MyGetPackageListFinder.GetPackagesAsync() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\MyGetPackageListFinder.cs:line 38
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.GetLatestVersionFromMyGet(String packageId) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 184
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.UpdateSolutionAsync(String solutionPath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, Boolean checkAll) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 40
   at Volo.Abp.Cli.Commands.UpdateCommand.UpdateNugetPackages(CommandLineArgs commandLineArgs, String directory) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 71
   at Volo.Abp.Cli.Commands.UpdateCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 43
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

C:\projects\01_Rostelecom\SSKI>

**Comment by realLiangshiwei** [comment]
`Unable to get latest preview version`

May you need to switch to stable : https://docs.abp.io/en/abp/latest/CLI#switch-to-stable

**Comment by EugeniZaplatin** [comment]
I did it.
All the same:

C:\projects\\SSKI>abp switch-to-stable
[13:16:48 INF] ABP CLI (https://abp.io)
[13:16:48 INF] Version 3.3.0 (Stable)
[13:17:23 ERR] Unable to get latest preview version.
[13:17:23 ERR] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Volo.Abp.Cli.ProjectModification.MyGetPackageListFinder.GetPackagesAsync() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\MyGetPackageListFinder.cs:line 38
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.GetLatestVersionFromMyGet(String packageId) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 184
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.UpdateSolutionAsync(String solutionPath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, Boolean checkAll) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 40
   at Volo.Abp.Cli.ProjectModification.PackagePreviewSwitcher.SwitchToStable(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\PackagePreviewSwitcher.cs:line 98
   at Volo.Abp.Cli.Commands.SwitchToStableCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\SwitchToStableCommand.cs:line 20
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by EugeniZaplatin** [comment]
My current version 3.2.1 stable

**Comment by hikalkan** [comment]
@realLiangshiwei please try to upgrade a sample to test it.

**Comment by realLiangshiwei** [comment]
I tested, it works. I think there is no problem with CLI @EugeniZaplatin Could you provide the steps to reproduce?

![image](https://user-images.githubusercontent.com/16813853/97434339-d74f1500-1959-11eb-9432-a7127394e54f.png)

**Comment by EugeniZaplatin** [comment]
Indeed, I have no problem with the newly created project.
The problem is only in my real business project. I have already gone through several versions and there were no problems. The first time I faced the difficulty of updating.

**Comment by realLiangshiwei** [comment]
I think it nothing to do with the version.  This is related to the server's response. you can download the CLI source code and use the `update` command to debug and you can write the server response result here.

![image](https://user-images.githubusercontent.com/16813853/97561453-2ad56780-1a1b-11eb-926e-0aa7d4e418eb.png)

**Comment by EugeniZaplatin** [comment]
![image](https://user-images.githubusercontent.com/11317749/97617596-879f4500-1a50-11eb-8fad-37e2c6555fad.png)
While testing the update against source code, I see a strange basic URL.

**Comment by EugeniZaplatin** [comment]
![image](https://user-images.githubusercontent.com/11317749/97618062-21ff8880-1a51-11eb-9190-44a1beb2dd7b.png)
May be fogot to replace it in production?

**Comment by EugeniZaplatin** [comment]
I checked my network and found a problem with accessing the abp.io domain.
After fixing this issue and successfully updated the solution.
I'm sorry to bother you.

Thank you for your participation!!!
