### ISSUE TITLE
Can I extend repository like IIdentityUserRepository ?

### ISSUE THREAD

**Issue by tkezyo** [abpframework/abp#5995]
I want get user names by user ids.

this module depend on Volo.Abp.Identity , I defind new Repository
but can't find this repository in DI

What is the best practice？

```
    public interface ITDIdentityRoleRepository : IBasicRepository<IdentityRole, Guid>,ITransientDependency
    {
        Task<List<NameValue<Guid>>> GetNamesAsync(List<Guid> ids);
    }


    public class EfCoreIdentityRoleRepository : EfCoreRepository<IIdentityDbContext, IdentityRole, Guid>, ITDIdentityRoleRepository
    {
        public EfCoreIdentityRoleRepository(IDbContextProvider<IIdentityDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
        public async Task<List<NameValue<Guid>>> GetNamesAsync(List<Guid> ids)
        {
            return await DbSet.Where(c => ids.Contains(c.Id)).Select(c => new NameValue<Guid>(c.Name, c.Id)).ToListAsync();
        }
    }


//EF module
      context.Services.AddAbpDbContext<Volo.Abp.Identity.EntityFrameworkCore.IdentityDbContext>(options =>
            {
                options.AddRepository<IdentityUser, EfCoreIdentityUserRepository>();
            });


//Application
         public IdentityLookupAppService(
            IIdentityUserRepository identityUserRepository,
            IIdentityRoleRepository identityRoleRepository,
            IOrganizationUnitRepository organizationUnitRepository,
            ITDIdentityUserRepository tdidentityUserRepository
         
            )
        {
            _tdidentityUserRepository = tdidentityUserRepository;
            _identityUserRepository = identityUserRepository;
            _identityRoleRepository = identityRoleRepository;
            _organizationUnitRepository = organizationUnitRepository;
        }
```

```
 [ERR] An exception was thrown while activating TD.Identity.Identity.IdentityLookupController -> TD.Identity.IdentityLookupAppService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating TD.Identity.Identity.IdentityLookupController -> TD.Identity.IdentityLookupAppService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'TD.Identity.IdentityLookupAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'TD.Identity.ITDIdentityUserRepository tdidentityUserRepository' of constructor 'Void .ctor(Volo.Abp.Identity.IIdentityUserRepository, Volo.Abp.Identity.IIdentityRoleRepository, Volo.Abp.Identity.IOrganizationUnitRepository, TD.Identity.ITDIdentityUserRepository)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(ConstructorInfo[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
```

**Comment by maliming** [comment]
Please check the official documentation before asking questions: https://docs.abp.io


https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide

**Comment by tkezyo** [comment]
I have checked this document，but I didn't find what I wanted.
I just want to add some data reading function， please help me.

**Comment by tkezyo** [comment]
I finally used `IReadOnlyRepository<IdentityUser, Guid>` in the application layer
