### ISSUE TITLE
RouteCreationException

### ISSUE THREAD

**Issue by SlowLogicBoy** [abpframework/abp#600]
I'm trying out Conventional Controllers (controller from ApplicationService)
Created a simple [`AppService`](https://github.com/SlowLogicBoy/AbpRouteTemplateException/blob/master/AppService.cs) and added:
[`options.ConventionalControllers.Create(typeof(AppModule).Assembly);`](https://github.com/SlowLogicBoy/AbpRouteTemplateException/blob/master/AppModule.cs#L20) to [`AppModule.ConfigureServices`](https://github.com/SlowLogicBoy/AbpRouteTemplateException/blob/master/AppModule.cs#L16)

If I try to access any path I get exception:
```csharp
Microsoft.AspNetCore.Routing.RouteCreationException: The following errors occurred with attribute routing information:

For action: 'MakoFxAbp.AppService.GetStuff (MakoFxAbp)'
Error: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
Parameter name: routeTemplate
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetRouteInfos(IReadOnlyList`1 actions)
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.AddEntries(TreeRouteBuilder builder, ActionDescriptorCollection actions)
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

[Source Project](https://github.com/SlowLogicBoy/AbpRouteTemplateException)
Edit: 
`Microsoft.AspNetCore.App` package is `2.1.5` version.
dotnet sdk:  `2.1.403`

**Comment by SlowLogicBoy** [comment]
Looks like `AppService` is a convention and gets cut off. 
After I changed it to `MyAppService` it started working. 
`MyAppService` was converted to `My` and `GetStuff` to `Stuff`, according to `http://localhost:5000/api/abp/api-definition`. 
So at the end path to `GetStuff` method became `http://localhost:5000/api/app/my/stuff`. 
Ether I missed somewhere that this was a convetion, or documentation does not mention that yet.
