### ISSUE TITLE
Tiered App with IdentityServer QuickUI  ( Method 'GetAllAsync' in type 'Volo.Abp.IdentityServer.Grants.PersistedGrantStore'  does not have an implementation.)

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6077]
Hello,

I'm traying to use IdentityServer QuickUI (https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) with my App (Tiered)
when i run my App the IDP  MyApp.IdentityServer i got the error below : 

```cs
Starting IIS Express ...
Successfully registered URL "https://localhost:44355/" for site "Test.App.IdentityServer" application "/"
Registration completed for site "Test.App.IdentityServer"
IIS Express is running.
[19:20:16 INF] Starting Test.App.IdentityServer.
[19:20:37 FTL] Test.App.IdentityServer terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.TypeLoadException: Method 'GetAllAsync' in type 'Volo.Abp.IdentityServer.Grants.PersistedGrantStore' from assembly 'Volo.Abp.IdentityServer.Domain, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Volo.Abp.IdentityServer.IdentityServerBuilderExtensions.AddAbpStores(IIdentityServerBuilder builder)
   at Volo.Abp.IdentityServer.EntityFrameworkCore.AbpIdentityServerEntityFrameworkCoreModule.<>c.<PreConfigureServices>b__0_0(IIdentityServerBuilder builder)
   at Volo.Abp.Options.PreConfigureActionList`1.Configure(TOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionPreConfigureExtensions.ExecutePreConfiguredActions[TOptions](IServiceCollection services, TOptions options)
   at Volo.Abp.IdentityServer.AbpIdentityServerDomainModule.AddIdentityServer(IServiceCollection services)
   at Volo.Abp.IdentityServer.AbpIdentityServerDomainModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Test.App.Startup.ConfigureServices(IServiceCollection services) in C:\Users\aelhadi\source\repos\Test\src\Test.App.IdentityServer\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Test.App.Program.Main(String[] args) in C:\Users\aelhadi\source\repos\Test\src\Test.App.IdentityServer\Program.cs:line 31

```

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by aelhadi** [comment]
Steps :
-Create new **Tiered** ABP solution (version 3.3.1)
-Copy (https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) the folder to Test.App.IdentityServer (my IDP from tiered App)

-install IdentityServer4 nuget (last) to my Test.App.IdentityServer

lunch App

Best Regards

**Comment by maliming** [comment]
> -install IdentityServer4 nuget (last) to my Test.App.IdentityServer

Abp 3.3.1 is using Identity Server package v3.1.3. so I think it can't compatible with IdentityServer4's latest version.

https://github.com/abpframework/abp/blob/rel-3.3/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo.Abp.IdentityServer.Domain.csproj#L28

**Comment by aelhadi** [comment]
Thanks...
Working fine 👍 

By the way... why you don't upgrade Abp to IdentityServer4's latest version ?

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/4578
