### ISSUE TITLE
Running First Application

### ISSUE THREAD

**Issue by gfo2007** [abpframework/abp#6107]
Hi,
I am new to abp framework. I am following the Getting Started Tutorial and when I tried to run the Acme.BookStore.Web project as my start-up project, the browser displayed the error in the image below. Please help.
![abp framework app error](https://user-images.githubusercontent.com/14317420/98441527-db67f900-20f6-11eb-8b21-59ea4a8c878a.PNG)

**Comment by maliming** [comment]
hi

Are you create a tiered project? if so you need run `IdenttiyServer` and `Api.Host` first.

**Comment by gfo2007** [comment]
@maliming thanks for the response. Yes I am creating a tiered project and I did run the IdentityServer and Api.Host projects before the Web project. It is showing the error below.

**An unhandled exception occurred while processing the request.
TaskCanceledException: The operation was canceled.
`System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)`**

What else could be causing the error?

**Comment by leonkosak** [comment]
Please provide error logs for each project (ids, httpapi, web).

**Comment by gfo2007** [comment]
@leonkosak please below is the log found in vscode-chrome debug.txt

**2020-11-9, 15:29:23.843 UTC
[15:29:23.844 UTC] OS: win32 x64
[15:29:23.844 UTC] Adapter node: v12.16.3 x64
[15:29:23.844 UTC] vscode-chrome-debug-core: 6.8.9
[15:29:23.844 UTC] debugger-for-chrome: 4.12.8
[15:29:23.844 UTC] From client: initialize({"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"chrome","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"supportsHandshakeRequest":true,"supportsVsCustomMessages":true,"supportsMapURLToFilePathRequest":true,"supportsLaunchUnelevatedProcessRequest":true})
[15:29:23.844 UTC] To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsBreakpointLocationsRequest":true,"supportsRestartRequest":true,"supportsSetExpression":true,"supportsLogPoints":true}}
[15:29:23.844 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/initialize","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","successful":"true","timeTakenInMilliseconds":"2.6393","requestType":"request"}}}
[15:29:23.844 UTC] From client: launch({"name":"Attach to Chrome program from Visual Studio","type":"chrome","request":"launch","breakOnLoad":true,"breakOnLoadStrategy":"instrument","_clientOverlayPausedMessage":"Paused in Visual Studio","trace":"info","sourceMaps":true,"showAsyncStacks":true,"smartStep":false,"url":"https://localhost:44387/","runtimeExecutable":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","userDataDir":"C:\\Users\\gotoo\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_c241ccd9\\WebTools\\B1BEBFE6_316DB045","webRoot":"C:\\Users\\gotoo\\Documents\\Visual Studio Projects\\Acme.BookStore\\src\\Acme.BookStore.Web\\wwwroot","shouldLaunchChromeUnelevated":true,"port":55107})
[15:29:23.844 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","request":"launch","args":["name","type","request","breakOnLoad","breakOnLoadStrategy","_clientOverlayPausedMessage","trace","sourceMaps","showAsyncStacks","smartStep","url","runtimeExecutable","userDataDir","webRoot","shouldLaunchChromeUnelevated","port","pathMapping","sourceMapPathOverrides","skipFileRegExps","targetFilter"]}}}
[15:29:23.844 UTC] To client: "launchUnelevated"({"process":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","args":["--remote-debugging-port=55107","--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\gotoo\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_c241ccd9\\WebTools\\B1BEBFE6_316DB045","about:blank"]}), timeout: 10000
[15:29:24.066 UTC] Getting browser and debug protocol version via http://127.0.0.1:55107/json/version
[15:29:24.089 UTC] Discovering targets via http://127.0.0.1:55107/json/list
[15:29:25.105 UTC] Got browser version: Chrome/86.0.4240.183
[15:29:25.105 UTC] Got debug protocol version: 1.3
[15:29:25.105 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"targetDebugProtocolVersion","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8"}}}
[15:29:25.108 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"targetCount","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","numTargets":3}}}
[15:29:25.110 UTC] Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=localhost/devtools/page/AC975E934371ED30A924487D164F3D3E","id":"AC975E934371ED30A924487D164F3D3E","title":"","type":"page","url":"about:blank","webSocketDebuggerUrl":"ws://127.0.0.1:55107/devtools/page/AC975E934371ED30A924487D164F3D3E","version":{}}
[15:29:25.110 UTC] WebSocket Url: ws://127.0.0.1:55107/devtools/page/AC975E934371ED30A924487D164F3D3E
[15:29:25.132 UTC] → To target: "{\"id\":1,\"method\":\"Console.enable\"}"
[15:29:25.133 UTC] → To target: "{\"id\":2,\"method\":\"Debugger.enable\"}"
[15:29:25.134 UTC] → To target: "{\"id\":3,\"method\":\"Runtime.enable\"}"
[15:29:25.134 UTC] → To target: "{\"id\":4,\"method\":\"Log.enable\"}"
[15:29:25.134 UTC] → To target: "{\"id\":5,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
[15:29:25.134 UTC] → To target: "{\"id\":6,\"method\":\"Runtime.run\"}"
[15:29:25.134 UTC] → To target: "{\"id\":7,\"method\":\"Page.enable\"}"
[15:29:25.134 UTC] → To target: "{\"id\":8,\"method\":\"Network.enable\",\"params\":{}}"
[15:29:25.289 UTC] ← From target: {"id":1,"result":{}}
[15:29:25.291 UTC] ← From target: {"id":2,"result":{"debuggerId":"-8900977728496628055.2162136011623500170"}}
[15:29:25.293 UTC] ← From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","auxData":{"isDefault":true,"type":"default","frameId":"AC975E934371ED30A924487D164F3D3E"}}}}
[15:29:25.293 UTC] ← From target: {"id":3,"result":{}}
[15:29:25.293 UTC] ← From target: {"id":4,"result":{}}
[15:29:25.294 UTC] ← From target: {"id":5,"result":{}}
[15:29:25.296 UTC] ← From target: {"id":6,"error":{"code":-32601,"message":"'Runtime.run' wasn't found"}}
[15:29:25.302 UTC] ← From target: {"id":7,"result":{}}
[15:29:25.307 UTC] ← From target: {"id":8,"result":{}}
[15:29:25.307 UTC] → To target: "{\"id\":9,\"method\":\"Debugger.setBlackboxPatterns\",\"params\":{\"patterns\":[\"^chrome-extension:.*\"]}}"
[15:29:25.308 UTC] → To target: "{\"id\":10,\"method\":\"Schema.getDomains\"}"
[15:29:25.308 UTC] ← From target: {"id":10,"result":{"domains":[{"name":"Inspector","version":"1.2"},{"name":"Memory","version":"1.2"},{"name":"Page","version":"1.2"},{"name":"Emulation","version":"1.2"},{"name":"Security","version":"1.2"},{"name":"Network","version":"1.2"},{"name":"Database","version":"1.2"},{"name":"IndexedDB","version":"1.2"},{"name":"CacheStorage","version":"1.2"},{"name":"DOMStorage","version":"1.2"},{"name":"CSS","version":"1.2"},{"name":"ApplicationCache","version":"1.2"},{"name":"DOM","version":"1.2"},{"name":"IO","version":"1.2"},{"name":"DOMDebugger","version":"1.2"},{"name":"DOMSnapshot","version":"1.2"},{"name":"ServiceWorker","version":"1.2"},{"name":"Input","version":"1.2"},{"name":"LayerTree","version":"1.2"},{"name":"DeviceOrientation","version":"1.2"},{"name":"Tracing","version":"1.2"},{"name":"Animation","version":"1.2"},{"name":"Accessibility","version":"1.2"},{"name":"Storage","version":"1.2"},{"name":"Log","version":"1.2"},{"name":"Runtime","version":"1.2"},{"name":"Debugger","version":"1.2"},{"name":"Profiler","version":"1.2"},{"name":"HeapProfiler","version":"1.2"},{"name":"Schema","version":"1.2"},{"name":"Target","version":"1.2"},{"name":"Overlay","version":"1.2"},{"name":"Performance","version":"1.2"},{"name":"Audits","version":"1.2"},{"name":"HeadlessExperimental","version":"1.2"}]}}
[15:29:25.309 UTC] → To target: "{\"id\":11,\"method\":\"Debugger.setAsyncCallStackDepth\",\"params\":{\"maxDepth\":4}}"
[15:29:25.315 UTC] ← From target: {"method":"Page.frameResized","params":{}}
[15:29:25.320 UTC] ← From target: {"id":9,"result":{}}
[15:29:25.320 UTC] ← From target: {"id":11,"result":{}}
[15:29:25.321 UTC] → To target: "{\"id\":12,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"navigator.userAgent\",\"silent\":true}}"
[15:29:25.321 UTC] → To target: "{\"id\":13,\"method\":\"Browser.getVersion\"}"
[15:29:25.321 UTC] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
[15:29:25.322 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/launch","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","successful":"true","timeTakenInMilliseconds":"1486.096401","requestType":"request","shouldLaunchChromeUnelevated":"true","doesHostSupportLaunchUnelevated":"true"}}}
[15:29:25.323 UTC] ← From target: {"id":13,"result":{"protocolVersion":"1.3","product":"Chrome/86.0.4240.183","revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","jsVersion":"8.6.395.23"}}
[15:29:25.323 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"target-version","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183"}}}
[15:29:25.330 UTC] ← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"5","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":19,"executionContextId":1,"hash":"3a6f8cb8708878331cc2be2ec90de0ab25738855","executionContextAuxData":{"isDefault":true,"type":"default","frameId":"AC975E934371ED30A924487D164F3D3E"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":19,"scriptLanguage":"JavaScript","embedderName":""}}
[15:29:25.334 UTC] → To target: "{\"id\":14,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"5\",\"lineNumber\":0,\"columnNumber\":0},\"end\":{\"scriptId\":\"5\",\"lineNumber\":1,\"columnNumber\":0},\"restrictToFunction\":false}}"
[15:29:25.336 UTC] ← From target: {"id":12,"result":{"result":{"type":"string","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"}}}
[15:29:25.337 UTC] Target userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
[15:29:25.337 UTC] → To target: "{\"id\":15,\"method\":\"Network.setCacheDisabled\",\"params\":{\"cacheDisabled\":true}}"
[15:29:25.337 UTC] ← From target: {"id":14,"result":{"locations":[{"scriptId":"5","lineNumber":0,"columnNumber":0}]}}
[15:29:25.337 UTC] To client: {"seq":0,"type":"event","event":"initialized"}
[15:29:25.340 UTC] ← From target: {"id":15,"result":{}}
[15:29:25.341 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"VM5","path":"<eval>/VM5","sourceReference":1000}}}
[15:29:25.350 UTC] From client: setExceptionBreakpoints({"filters":[]})
[15:29:25.351 UTC] → To target: "{\"id\":16,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"none\"}}"
[15:29:25.352 UTC] ← From target: {"id":16,"result":{}}
[15:29:25.352 UTC] To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
[15:29:25.352 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/setExceptionBreakpoints","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183","successful":"true","timeTakenInMilliseconds":"1.977001","requestType":"request"}}}
[15:29:25.354 UTC] From client: configurationDone({})
[15:29:25.354 UTC] → To target: "{\"id\":17,\"method\":\"Page.navigate\",\"params\":{\"url\":\"https://localhost:44387/\"}}"
[15:29:25.354 UTC] To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
[15:29:25.354 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/configurationDone","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183","successful":"true","timeTakenInMilliseconds":"0.739001","requestType":"request"}}}
[15:29:33.753 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"target/notification/onScriptParsed","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183","aggregated.startTime":"[\"1604935765331\"]","aggregated.successful":"[\"true\"]","aggregated.timeTakenInMilliseconds":"[\"5.4398\"]"}}}
[15:31:38.511 UTC] ← From target: {"id":17,"result":{"frameId":"AC975E934371ED30A924487D164F3D3E","loaderId":"0127B960C1651C9ACC2A6CA35B764431"}}
[15:31:38.517 UTC] ← From target: {"method":"Page.frameStartedLoading","params":{"frameId":"AC975E934371ED30A924487D164F3D3E"}}
[15:31:38.526 UTC] ← From target: {"method":"Runtime.executionContextDestroyed","params":{"executionContextId":1}}
[15:31:38.528 UTC] ← From target: {"method":"Runtime.executionContextsCleared","params":{}}
[15:31:38.530 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"removed","source":{"name":"VM5","path":"<eval>/VM5","sourceReference":1000}}}
[15:31:38.530 UTC] ← From target: {"method":"Page.frameNavigated","params":{"frame":{"id":"AC975E934371ED30A924487D164F3D3E","loaderId":"0127B960C1651C9ACC2A6CA35B764431","url":"https://localhost:44387/","domainAndRegistry":"","securityOrigin":"https://localhost:44387","mimeType":"text/html","adFrameType":"none","secureContextType":"SecureLocalhost","crossOriginIsolatedContextType":"NotIsolated"}}}
[15:31:38.531 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"report-start-up-timings","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183","RequestedContentWasDetected":"true","Steps":"[\"BeforeFirstStep\",\"ClientRequest/initialize\",\"ClientRequest/launch\",\"LaunchTarget.LaunchExe\",\"Attach\",\"Attach.RequestDebuggerTargetsInformation\",\"Attach.ProcessDebuggerTargetsInformation\",\"Attach.AttachToTargetDebuggerWebsocket\",\"Attach.ConfigureDebuggingSession.Internal\",\"Attach.ConfigureDebuggingSession.Target\",\"Attach.ConfigureDebuggingSession.End\"]","All":"134782.700799","Request.ClientRequest/setExceptionBreakpoints.startTime":"[1604935765350]","Request.ClientRequest/setExceptionBreakpoints.timeTakenInMilliseconds":"[1.977001]","Request.ClientRequest/configurationDone.startTime":"[1604935765354]","Request.ClientRequest/configurationDone.timeTakenInMilliseconds":"[0.739001]","BeforeFirstStep":"[10.8669]","WaitingAfter.ClientRequest/initialize":"[13.4339]","ClientRequest/initialize":"[77.296]","ClientRequest/launch":"[3.9077]","LaunchTarget.LaunchExe":"[223.4471]","Attach":"[25.915301]","Attach.RequestDebuggerTargetsInformation":"[1018.4339]","Attach.ProcessDebuggerTargetsInformation":"[2.512501]","Attach.AttachToTargetDebuggerWebsocket":"[7.480899]","Attach.ConfigureDebuggingSession.Internal":"[0.8747]","Attach.ConfigureDebuggingSession.Target":"[202.4605]","WaitingAfter.ClientRequest/launch":"[1574.281799]","WaitingAfter.NotifyInitialized":"[1589.97]","RequestedNavigateToUserPage":"[134762.950899]","Attach.ConfigureDebuggingSession.End":"[133209.1428]"}}}
[15:31:38.532 UTC] ← From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"https://localhost:44387","name":"","auxData":{"isDefault":true,"type":"default","frameId":"AC975E934371ED30A924487D164F3D3E"}}}}
[15:31:38.532 UTC] ← From target: {"method":"Log.entryAdded","params":{"entry":{"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 500 ()","timestamp":1.604935898525337e+12,"url":"https://localhost:44387/","networkRequestId":"0127B960C1651C9ACC2A6CA35B764431"}}}
[15:31:38.533 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"Failed to load resource: the server responded with a status of 500 () [https://localhost:44387/]\n"}}
[15:31:38.551 UTC] ← From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":3,"origin":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln","name":"Softomotive Automation","auxData":{"isDefault":false,"type":"isolated","frameId":"AC975E934371ED30A924487D164F3D3E"}}}}
[15:31:38.551 UTC] ← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"6","url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js","startLine":0,"startColumn":0,"endLine":63,"endColumn":0,"executionContextId":3,"hash":"067278a757c2d8ce1b4d0edc4374d2363cc0009f","executionContextAuxData":{"isDefault":false,"type":"isolated","frameId":"AC975E934371ED30A924487D164F3D3E"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":2755,"scriptLanguage":"JavaScript","embedderName":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js"}}
[15:31:38.553 UTC] To client: "mapURLToFilePath"({"url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js"}), timeout: 500
[15:31:38.553 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"msgport.js","path":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js","sourceReference":1001}}}
[15:31:38.553 UTC] ← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"7","url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js","startLine":0,"startColumn":0,"endLine":108,"endColumn":0,"executionContextId":3,"hash":"1f53c4696e4a27b27b74935660b941a53a4c2bf9","executionContextAuxData":{"isDefault":false,"type":"isolated","frameId":"AC975E934371ED30A924487D164F3D3E"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":4170,"scriptLanguage":"JavaScript","embedderName":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js"}}
[15:31:38.554 UTC] To client: "mapURLToFilePath"({"url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js"}), timeout: 500
[15:31:38.554 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"content.js","path":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js","sourceReference":1002}}}
[15:31:38.554 UTC] ← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"{\"notify\":\"init_tab\"}","url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js","line":59,"column":17}}}
[15:31:38.554 UTC] ← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"{\"notify\":\"init_tab\"}"}],"executionContextId":3,"timestamp":1.604935898550365e+12,"stackTrace":{"callFrames":[{"functionName":"MessageHostCommunicator.post","scriptId":"6","url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js","lineNumber":58,"columnNumber":16},{"functionName":"","scriptId":"7","url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js","lineNumber":103,"columnNumber":17}]}}}
[15:31:38.555 UTC] To client: "mapURLToFilePath"({"url":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js"}), timeout: 500
[15:31:38.563 UTC] The client responded that the url "chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js" maps to the file path "null"
[15:31:38.563 UTC] The client responded that the url "chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js" maps to the file path "null"
[15:31:38.563 UTC] Paths.scriptParsed: could not resolve chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js to a file with pathMapping/webRoot: {"/":"c:\\users\\gotoo\\documents\\visual studio projects\\acme.bookstore\\src\\acme.bookstore.web\\wwwroot"}. It may be external or served directly from the server's memory (and that's OK).
[15:31:38.565 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"{\"notify\":\"init_tab\"}\n","source":{"name":"msgport.js","path":"chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/msgport.js","sourceReference":1001},"line":59,"column":17}}
[15:31:38.614 UTC] The client responded that the url "chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js" maps to the file path "null"
[15:31:38.614 UTC] Paths.scriptParsed: could not resolve chrome-extension://pkpoicdhlhooickgibfkpebpfpfkhgln/content.js to a file with pathMapping/webRoot: {"/":"c:\\users\\gotoo\\documents\\visual studio projects\\acme.bookstore\\src\\acme.bookstore.web\\wwwroot"}. It may be external or served directly from the server's memory (and that's OK).
[15:31:38.658 UTC] ← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"8","url":"https://localhost:44387/","startLine":510,"startColumn":16,"endLine":705,"endColumn":8,"executionContextId":2,"hash":"00aaf1698526d03e587e30160fe0e3790bad1023","executionContextAuxData":{"isDefault":true,"type":"default","frameId":"AC975E934371ED30A924487D164F3D3E"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":5446,"scriptLanguage":"JavaScript","embedderName":"https://localhost:44387/"}}
[15:31:38.659 UTC] To client: "mapURLToFilePath"({"url":"https://localhost:44387/"}), timeout: 500
[15:31:38.659 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"localhost:44387","path":"https://localhost:44387","sourceReference":1003}}}
[15:31:38.659 UTC] ← From target: {"method":"Page.loadEventFired","params":{"timestamp":207849.09716}}
[15:31:38.660 UTC] ← From target: {"method":"Page.frameStoppedLoading","params":{"frameId":"AC975E934371ED30A924487D164F3D3E"}}
[15:31:38.661 UTC] ← From target: {"method":"Page.domContentEventFired","params":{"timestamp":207849.188197}}
[15:31:38.665 UTC] The client responded that the url "https://localhost:44387/" maps to the file path "null"
[15:31:38.665 UTC] Paths.scriptParsed: could not resolve https://localhost:44387/ to a file with pathMapping/webRoot: {"/":"c:\\users\\gotoo\\documents\\visual studio projects\\acme.bookstore\\src\\acme.bookstore.web\\wwwroot"}. It may be external or served directly from the server's memory (and that's OK).
[15:31:43.760 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"target/notification/onScriptParsed","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.12.8","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@0b568b034b8f7994697cb341eeca5979b84151cc","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","Versions.Target.V8":"8.6.395.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"86.0.4240.183","aggregated.startTime":"[\"1604935898551\",\"1604935898553\",\"1604935898658\"]","aggregated.successful":"[\"true\",\"true\",\"true\"]","aggregated.timeTakenInMilliseconds":"[\"13.3962\",\"61.2615\",\"6.7542\"]"}}}
[15:33:27.205 UTC] From client: disconnect({"terminateDebuggee":true})**

**Comment by leonkosak** [comment]
In each project, which is launched, there is "Logs" folder created. Please refer these logs.

**Comment by gfo2007** [comment]
@leonkosak sorry for the late reply. I was on an assignment in a remote area where internet was extremely poor.

Please the logs have been attached in the order:
1. Web
2. Identity Server
3. Api Host

[logs.txt](https://github.com/abpframework/abp/files/5535300/logs.txt)

[logs.txt](https://github.com/abpframework/abp/files/5535304/logs.txt)

[logs.txt](https://github.com/abpframework/abp/files/5535306/logs.txt)

**Comment by gfo2007** [comment]
@leonkosak please what us the Reddis Server in the error below?

**2020-11-09 09:04:02.962 +00:00 [WRN] It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.0.593.37019
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.0.593.37019
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(Object configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 825
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.ConnectAsync(CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.GetAsync(TCacheKey key, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)**

**Comment by DenverSearle** [comment]
Hi - I had the same issue when creating a new project with a "Separate Identity Server" - see my issue and fix here: https://github.com/abpframework/abp/issues/6174

**Comment by Neeil** [comment]
You need to setup a redis in your pc/server.

**Comment by Neeil** [comment]
I use docker to host redis/db so to make the implementation simpler.
