### ISSUE TITLE
EnumConverter violates the constraint of type 'T'

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#6152]
In ABP Framework v4.0, the following exception is thrown when it's trying to map to a `nullable enum`.

```
'System.Nullable`1[MyCompanyName.MyProjectName.CarType]', on 'System.Text.Json.Serialization.Converters.EnumConverter`1[T]' violates the constraint of type 'T'.
System.ArgumentException: GenericArguments[0], 'System.Nullable`1[MyCompanyName.MyProjectName.CarType]', on 'System.Text.Json.Serialization.Converters.EnumConverter`1[T]' violates the constraint of type 'T'.
 ---> System.TypeLoadException: GenericArguments[0], 'System.Nullable`1[MyCompanyName.MyProjectName.CarType]', on 'System.Text.Json.Serialization.Converters.EnumConverter`1[T]' violates the constraint of type parameter 'T'.
   at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.Serialization.JsonStringEnumConverter.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.JsonConverters.AbpStringToEnumConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\Github\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\SystemTextJson\JsonConverters\AbpStringToEnumConverter.cs:line 30
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
```

To reproduce it;

- Create an input DTO and enum

 ```
public class CarCreateDto
    {
        public string Name { get; set; }
        public CarType? CarType { get; set; }
    }
```

 ```
public enum CarType
    {
         GoodCar = 1,
         BadCar = 2
    }
```

- Then write an application to service and a new action method to get `CarCreateDto`

![image](https://user-images.githubusercontent.com/9526587/98799750-927ab200-2420-11eb-8c4f-4b2706f0ee26.png)

It throws the exception here https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Json/Volo/Abp/Json/SystemTextJson/JsonConverters/AbpStringToEnumConverter.cs#L30

Besides, we can check if the type is convertable in `AbpStringToEnumConverter.Read()` method. [See  the CanCovert method in .NET5](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter.canconvert?view=net-5.0)

You can also use ABP Suite to create a new entity called "Car". In my test, I used the ABP Suite in the `app-pro` template.

**Comment by maliming** [comment]
Already resolved by https://github.com/abpframework/abp/pull/6146
