### ISSUE TITLE
4.0.0-rc.1 api host startup fails

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6180]
* Create a new project with `abp new Acme.BookStore -u blazor --preview`
* Run database migrations (delete the old database if exists)
* Run HttpApi.Host

````
System.NullReferenceException: Object reference not set to an instance of an object.

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.get_IsCompleted()

   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync()

   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
````

**Comment by hikalkan** [comment]
Same for an MVC project too.

**Comment by maliming** [comment]
I get an error when I use Rider run `Api.Host`, but everything is working when I debug `Api.Host`. 

------
Problem code line is:
https://github.com/abpframework/abp/blob/c9ce1809c61abc48029913bb05b798ee67a7d395/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/RequestLocalization/DefaultAbpRequestLocalizationOptionsProvider.cs#L50
------

Temporary patch: Copy **MyDefaultAbpRequestLocalizationOptionsProvider** to your project

```cs
[Dependency(ReplaceServices = true)]
public class MyDefaultAbpRequestLocalizationOptionsProvider : IAbpRequestLocalizationOptionsProvider, ISingletonDependency
{
      private readonly IServiceScopeFactory _serviceProviderFactory;
      private readonly SemaphoreSlim _syncSemaphore;
      private Action<RequestLocalizationOptions> _optionsAction;
      private RequestLocalizationOptions _requestLocalizationOptions;

      public MyDefaultAbpRequestLocalizationOptionsProvider(IServiceScopeFactory serviceProviderFactory)
      {
            _serviceProviderFactory = serviceProviderFactory;
            _syncSemaphore = new SemaphoreSlim(1, 1);
      }

      public void InitLocalizationOptions(Action<RequestLocalizationOptions> optionsAction = null)
      {
            _optionsAction = optionsAction;
      }

      public RequestLocalizationOptions GetLocalizationOptions()
      {
            if (_requestLocalizationOptions != null)
            {
                  return _requestLocalizationOptions;
            }

            return AsyncHelper.RunSync(GetLocalizationOptionsAsync);
      }

      public async Task<RequestLocalizationOptions> GetLocalizationOptionsAsync()
      {
            if (_requestLocalizationOptions == null)
            {
                  using (await _syncSemaphore.LockAsync())
                  {
                        if (_requestLocalizationOptions == null)
                        {
                              using (var serviceScope = _serviceProviderFactory.CreateScope())
                              {
                                    var languageProvider = serviceScope.ServiceProvider.GetRequiredService<ILanguageProvider>();
                                    var settingProvider = serviceScope.ServiceProvider.GetRequiredService<ISettingProvider>();

                                    var languages = await languageProvider.GetLanguagesAsync();
                                    var defaultLanguage = await settingProvider.GetOrNullAsync(LocalizationSettingNames.DefaultLanguage);

                                    var options = !languages.Any()
                                          ? new RequestLocalizationOptions()
                                          : new RequestLocalizationOptions
                                          {
                                                DefaultRequestCulture = DefaultGetRequestCulture(defaultLanguage, languages),

                                                SupportedCultures = languages
                                                      .Select(l => l.CultureName)
                                                      .Distinct()
                                                      .Select(c => new CultureInfo(c))
                                                      .ToArray(),

                                                SupportedUICultures = languages
                                                      .Select(l => l.UiCultureName)
                                                      .Distinct()
                                                      .Select(c => new CultureInfo(c))
                                                      .ToArray()
                                          };

                                    _optionsAction?.Invoke(options);
                                    _requestLocalizationOptions = options;
                              }
                        }
                  }
            }

            return _requestLocalizationOptions;
      }

      private static RequestCulture DefaultGetRequestCulture(string defaultLanguage, IReadOnlyList<LanguageInfo> languages)
      {
            if (defaultLanguage == null)
            {
                  var firstLanguage = languages.First();
                  return new RequestCulture(firstLanguage.CultureName, firstLanguage.UiCultureName);
            }

            var (cultureName, uiCultureName) = LocalizationSettingHelper.ParseLanguageSetting(defaultLanguage);
            return new RequestCulture(cultureName, uiCultureName);
      }
}

```

**Comment by 274188A** [comment]
+1 - except I cannot get past the above mentioned error.  i'm using:

```
Abp new [myproj] --ui blazor --preview

```

when you say "update the CLI" - what version of the CLI is the latest/best to use with `4.0.0-rc.1`?

I tried to update the CLI with:

```
dotnet tool update -g Volo.Abp.Cli
```
which gives me 
```
Tool 'volo.abp.cli' was reinstalled with the latest stable version (version '3.3.1').
```

**Comment by maliming** [comment]
@274188A 
```
dotnet tool uninstall --global Volo.Abp.Cli 
dotnet tool install --global Volo.Abp.Cli --version 4.0.0-rc.1
```

**Comment by 274188A** [comment]
still no luck...re-created proj with latest CLI and get this still:

>System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.get_IsCompleted()
   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync()
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by maliming** [comment]
@274188A Can you try `dotnet clean & dotnet build & dotnet run` commands in `Api.Host` project.

**Comment by 274188A** [comment]
ok tried that and even cleaned out all obj, bin files, restored, rebuild, dotnet run -> same error...

**Comment by 274188A** [comment]
>PM> dotnet watch run
watch : Started
[10:08:17 INF] Starting Gp.HttpApi.Host.
[10:08:18 INF] User profile is available. Using 'C:\Users\xxxx\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[10:08:18 INF] Loaded ABP modules:
[10:08:18 INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
[10:08:18 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
[10:08:18 INF] - Volo.Abp.Validation.AbpValidationAbstractionsModule
[10:08:18 INF] - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
[10:08:18 INF] - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
[10:08:18 INF] - Volo.Abp.Security.AbpSecurityModule
[10:08:18 INF] - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
[10:08:18 INF] - Volo.Abp.Uow.AbpUnitOfWorkModule
[10:08:18 INF] - Volo.Abp.Data.AbpDataModule
[10:08:18 INF] - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
[10:08:18 INF] - Volo.Abp.Settings.AbpSettingsModule
[10:08:18 INF] - Volo.Abp.Localization.AbpLocalizationModule
[10:08:18 INF] - Volo.Abp.Validation.AbpValidationModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
[10:08:18 INF] - Volo.Abp.Users.AbpUsersDomainSharedModule
[10:08:18 INF] - Volo.Abp.Features.AbpFeaturesModule
[10:08:18 INF] - Volo.Abp.Identity.AbpIdentityDomainSharedModule
[10:08:18 INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
[10:08:18 INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
[10:08:18 INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
[10:08:18 INF] - Gp.GpDomainSharedModule
[10:08:18 INF] - Volo.Abp.EventBus.AbpEventBusModule
[10:08:18 INF] - Volo.Abp.Users.AbpUsersAbstractionModule
[10:08:18 INF] - Volo.Abp.Authorization.AbpAuthorizationModule
[10:08:18 INF] - Volo.Abp.Timing.AbpTimingModule
[10:08:18 INF] - Volo.Abp.Json.AbpJsonModule
[10:08:18 INF] - Volo.Abp.Threading.AbpThreadingModule
[10:08:18 INF] - Volo.Abp.Auditing.AbpAuditingModule
[10:08:18 INF] - Volo.Abp.Guids.AbpGuidsModule
[10:08:18 INF] - Volo.Abp.ObjectMapping.AbpObjectMappingModule
[10:08:18 INF] - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
[10:08:18 INF] - Volo.Abp.Specifications.AbpSpecificationsModule
[10:08:18 INF] - Volo.Abp.Domain.AbpDddDomainModule
[10:08:18 INF] - Volo.Abp.Application.AbpDddApplicationContractsModule
[10:08:18 INF] - Volo.Abp.Http.AbpHttpAbstractionsModule
[10:08:18 INF] - Volo.Abp.Application.AbpDddApplicationModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
[10:08:18 INF] - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
[10:08:18 INF] - Volo.Abp.Account.AbpAccountApplicationContractsModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
[10:08:18 INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
[10:08:18 INF] - Gp.GpApplicationContractsModule
[10:08:18 INF] - Volo.Abp.Minify.AbpMinifyModule
[10:08:18 INF] - Volo.Abp.Http.AbpHttpModule
[10:08:18 INF] - Volo.Abp.AspNetCore.AbpAspNetCoreModule
[10:08:18 INF] - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
[10:08:18 INF] - Volo.Abp.UI.AbpUiModule
[10:08:18 INF] - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
[10:08:18 INF] - Volo.Abp.Identity.AbpIdentityHttpApiModule
[10:08:18 INF] - Volo.Abp.Account.AbpAccountHttpApiModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.HttpApi.AbpPermissionManagementHttpApiModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiModule
[10:08:18 INF] - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiModule
[10:08:18 INF] - Gp.GpHttpApiModule
[10:08:18 INF] - Volo.Abp.Castle.AbpCastleCoreModule
[10:08:18 INF] - Volo.Abp.Autofac.AbpAutofacModule
[10:08:18 INF] - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
[10:08:18 INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
[10:08:18 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsAbstractionsModule
[10:08:18 INF] - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
[10:08:18 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsModule
[10:08:18 INF] - Volo.Abp.AutoMapper.AbpAutoMapperModule
[10:08:18 INF] - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainModule
[10:08:18 INF] - Volo.Abp.Serialization.AbpSerializationModule
[10:08:18 INF] - Volo.Abp.Caching.AbpCachingModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainModule
[10:08:18 INF] - Volo.Abp.Users.AbpUsersDomainModule
[10:08:18 INF] - Volo.Abp.Identity.AbpIdentityDomainModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.Identity.AbpPermissionManagementDomainIdentityModule
[10:08:18 INF] - Volo.Abp.IdentityServer.AbpIdentityServerDomainModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.IdentityServer.AbpPermissionManagementDomainIdentityServerModule
[10:08:18 INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
[10:08:18 INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
[10:08:18 INF] - Volo.Abp.TextTemplating.AbpTextTemplatingModule
[10:08:18 INF] - Volo.Abp.Emailing.AbpEmailingModule
[10:08:18 INF] - Gp.GpDomainModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationModule
[10:08:18 INF] - Volo.Abp.Identity.AbpIdentityApplicationModule
[10:08:18 INF] - Volo.Abp.UI.Navigation.AbpUiNavigationModule
[10:08:18 INF] - Volo.Abp.Account.AbpAccountApplicationModule
[10:08:18 INF] - Volo.Abp.TenantManagement.AbpTenantManagementApplicationModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationModule
[10:08:18 INF] - Gp.GpApplicationModule
[10:08:18 INF] - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.Users.EntityFrameworkCore.AbpUsersEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.IdentityServer.EntityFrameworkCore.AbpIdentityServerEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.EntityFrameworkCore.SqlServer.AbpEntityFrameworkCoreSqlServerModule
[10:08:18 INF] - Volo.Abp.BackgroundJobs.EntityFrameworkCore.AbpBackgroundJobsEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
[10:08:18 INF] - Volo.Abp.FeatureManagement.EntityFrameworkCore.AbpFeatureManagementEntityFrameworkCoreModule
[10:08:18 INF] - Gp.EntityFrameworkCore.GpEntityFrameworkCoreModule
[10:08:18 INF] - Gp.EntityFrameworkCore.GpEntityFrameworkCoreDbMigrationsModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.AbpAspNetCoreMvcUiModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.AbpAspNetCoreMvcUiBootstrapModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Bundling.AbpAspNetCoreMvcUiBundlingModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Packages.AbpAspNetCoreMvcUiPackagesModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpAspNetCoreMvcUiWidgetsModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.AbpAspNetCoreMvcUiThemeSharedModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.AbpAspNetCoreMvcUiMultiTenancyModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.AbpAspNetCoreMvcUiBasicThemeModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Authentication.JwtBearer.AbpAspNetCoreAuthenticationJwtBearerModule
[10:08:18 INF] - Volo.Abp.Identity.AspNetCore.AbpIdentityAspNetCoreModule
[10:08:18 INF] - Volo.Abp.Account.Web.AbpAccountWebModule
[10:08:18 INF] - Volo.Abp.Account.Web.AbpAccountWebIdentityServerModule
[10:08:18 INF] - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
[10:08:18 INF] - Volo.Abp.Swashbuckle.AbpSwashbuckleModule
[10:08:18 INF] - Gp.GpHttpApiHostModule
[10:08:18 DBG] Started background worker: Volo.Abp.BackgroundJobs.BackgroundJobWorker
[10:08:18 DBG] Started background worker: Volo.Abp.IdentityServer.Tokens.TokenCleanupBackgroundWorker
[10:08:18 INF] Starting IdentityServer4 version 4.1.1+cebd52f5bc61bdefc262fd20739d4d087c6f961f
[10:08:18 INF] Using the default authentication scheme Identity.Application for IdentityServer
[10:08:18 DBG] Using Identity.Application as default ASP.NET Core scheme for authentication
[10:08:18 DBG] Using Identity.External as default ASP.NET Core scheme for sign-in
[10:08:18 DBG] Using Identity.External as default ASP.NET Core scheme for sign-out
[10:08:18 DBG] Using Identity.Application as default ASP.NET Core scheme for challenge
[10:08:18 DBG] Using Identity.Application as default ASP.NET Core scheme for forbid
[10:08:18 INF] Initialized all ABP modules.
[10:08:18 INF] Now listening on: https://localhost:44353
[10:08:18 INF] Application started. Press Ctrl+C to shut down.
[10:08:18 INF] Hosting environment: Development
[10:08:18 INF] Content root path: C:\Abp Compares\Abp .NET 5.0\aspnet-core\src\Gp.HttpApi.Host
[10:08:37 INF] Request starting HTTP/2 GET https://localhost:44353/ - -
[10:08:37 ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.get_IsCompleted()
   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync()
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[10:08:37 INF] Request finished HTTP/2 GET https://localhost:44353/ - - - 500 - text/html;+charset=utf-8 33.7210ms
[10:08:37 INF] Request starting HTTP/2 GET https://localhost:44353/favicon.ico - -
[10:08:37 ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.get_IsCompleted()
   at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptionsAsync()
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[10:08:37 INF] Request finished HTTP/2 GET https://localhost:44353/favicon.ico - - - 500 - text/plain 2.0391ms

**Comment by maliming** [comment]
@274188A https://github.com/abpframework/abp/issues/6180#issuecomment-726442950

I will investigate this.

**Comment by 274188A** [comment]
>Temporary patch: Copy MyDefaultAbpRequestLocalizationOptionsProvider to your project

Could you be more specific with the description "your project" - ie which project?
thanks (i'm assuming you mean the host but assumptions can be dangerous :-)

**Comment by maliming** [comment]
> Could you be more specific with the description "your project" - ie which project?

`XXX.HttpApi.Host`

**Comment by 274188A** [comment]
yup all good now

**Comment by maliming** [comment]
We need to republish all packages to resolve.

**Comment by OldKing-lion** [comment]
ok wait the stable version
