### ISSUE TITLE
Upgrade ABP from 3.0.5 to 3.3.1, the application cannot launch.

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#6226]
My application works fine with ABP 3.0.5, but after I have upgraded to 3.3.1. It cannot launch.

ABP 3.0.5 -> ABP 3.3.1
My application used the Razor Pages framework. The error message shows the " ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.". But cannot find the "Microsoft.Bcl.AsyncInterfaces" package in the NuGet manager.

The error message detail as below:
```
2020-11-17 13:35:32.292 +08:00 [INF] Starting web host.
2020-11-17 13:35:37.832 +08:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule, Volo.Abp.Identity.EntityFrameworkCore, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule.<>c.<ConfigureServices>b__0_0(IAbpDbContextRegistrationOptionsBuilder options)
   at Microsoft.Extensions.DependencyInjection.AbpEfCoreServiceCollectionExtensions.AddAbpDbContext[TDbContext](IServiceCollection services, Action`1 optionsBuilder)
   at Volo.Abp.Identity.EntityFrameworkCore.AbpIdentityEntityFrameworkCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()


   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Dxp.Gms.Web.Startup.ConfigureServices(IServiceCollection services) in E:\Workspaces\DXP\x-zhengzhou-hkg\src\web\Dxp.Gms.Web\Startup.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Dxp.Gms.Web.Program.Main(String[] args) in E:\Workspaces\DXP\x-zhengzhou-hkg\src\web\Dxp.Gms.Web\Program.cs:line 30
```

Use **abp** tag in your questions.

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by jack-gaojz** [comment]
> * Steps needed to **reproduce** the problem.

Reproduce steps:
1. Go to the project folder and launch the CMD.
2. Execute the "ABP UPDATE".
3. After the update, start the application failed.

**Comment by leonkosak** [comment]
Do you make new migration (EF Core) for database (or at least check if Up and Down methods for new migration include changes)?

**Comment by dht6903** [comment]
After I updated my nuget packages from 2.7.0 to 3.3.1, I also ran into this issue

**Comment by maliming** [comment]
We need detailed steps to reproduce.

**Comment by jack-gaojz** [comment]
> We need detailed steps to reproduce.

We have customized some logic in our projects, we need to check it for more detail. Sorry for the delay provides the detailed steps.

**Comment by dht6903** [comment]
> After I updated my nuget packages from 2.7.0 to 3.3.1, I also ran into this issue

1. open my solution which abp version is 2.7.0 using VS2019
2. open Nuget manager for the entire solution
3. select update tab
4. select all Volo.Abp packages
5. update
6. after update to the latest version 3.3.1, build the solution and start the main project
7. got the error from the log file

**Comment by jack-gaojz** [comment]
> > After I updated my nuget packages from 2.7.0 to 3.3.1, I also ran into this issue
> 
> 1. open my solution which abp version is 2.7.0 using VS2019
> 2. open Nuget manager for the entire solution
> 3. select update tab
> 4. select all Volo.Abp packages
> 5. update
> 6. after update to the latest version 3.3.1, build the solution and start the main project
> 7. got the error from the log file

Suggestion: please use the ABP CLI tool to upgrade the ABP version, that will better than this way. FYI.

**Comment by jack-gaojz** [comment]
> We need detailed steps to reproduce.

I have fixed this issue. Some packages version not matched ABP 3.3.1, I have checked them one by one and set the specified version, it works fines. Thanks.
