### ISSUE TITLE
Sample MongoDB Ng - error on EF migration, error on SwaggerUI

### ISSUE THREAD

**Issue by OzBob** [abpframework/abp#6248]
* **ABP Framework version** 3.2.1
* **User Interface** Angular 10

After running all the steps in https://github.com/OzBob/abp-samples/pull/1

1
https://localhost:44308/swagger/index.html
GET https://localhost:44308/api/app/author
returns
Volo.Abp.AbpException: Could not find the bundle file '/libs/abp/luxon/abp.luxon.js' from IWebContentFileProvider
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Themes_Basic_Layouts_Account.<>c__DisplayClass17_0.<<ExecuteAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Themes_Basic_Layouts_Account.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

but Angular UI API calls do return data.

2
λ dotnet run Acme.BookStore.DbMigrator.csproj
[13:19:04 INF] Started database migrations...
[13:19:04 INF] Migrating schema for host database...
[13:19:04 INF] Executing host database seed...
Unhandled exception. MongoDB.Driver.MongoCommandException: Command aggregate failed: Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1605676745, 1). Collection minimum is Timestamp(1605676752, 1).
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.ExecuteAsync[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.AggregateAsync[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.AsyncCursorHelper.FirstOrDefaultAsync[T](Task`1 cursorTask, CancellationToken cancellationToken)
   at Volo.Abp.PermissionManagement.MongoDB.MongoPermissionGrantRepository.FindAsync(String name, String providerName, String providerKey, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.PermissionManagement.PermissionDataSeeder.SeedAsync(String providerName, String providerKey, IEnumerable`1 grantedPermissions, Nullable`1 tenantId)
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Acme.BookStore.Data.BookStoreDbMigrationService.SeedDataAsync(Tenant tenant) in D:\dev\s\OzBob\abp-samples\BookStore-Angular-MongoDb\aspnet-core\src\Acme.BookStore.Domain\Data\BookStoreDbMigrationService.cs:line 92
   at Acme.BookStore.Data.BookStoreDbMigrationService.MigrateAsync() in D:\dev\s\OzBob\abp-samples\BookStore-Angular-MongoDb\aspnet-core\src\Acme.BookStore.Domain\Data\BookStoreDbMigrationService.cs:line 41
   at Acme.BookStore.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in D:\dev\s\OzBob\abp-samples\BookStore-Angular-MongoDb\aspnet-core\src\Acme.BookStore.DbMigrator\DbMigratorHostedService.cs:line 30
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Acme.BookStore.DbMigrator.Program.Main(String[] args) in D:\dev\s\OzBob\abp-samples\BookStore-Angular-MongoDb\aspnet-core\src\Acme.BookStore.DbMigrator\Program.cs:line 29
   at Acme.BookStore.DbMigrator.Program.<Main>(String[] args)

Check MongoDB and tables have been created successfully!

Edit 
.\BookStore-Angular-MongoDb\aspnet-core\src\Acme.BookStore.Domain\Data\BookStoreDbMigrationService.cs
Comment out line 40 //await MigrateDatabaseSchemaAsync();

λ dotnet run Acme.BookStore.DbMigrator.csproj
again
All OK.

3
yarn test
results in 
BookComponent > should create
NullInjectorError: R3InjectorError(DynamicTestModule)[BookService -> RestService -> InjectionToken CORE_OPTIONS -> InjectionToken CORE_OPTIONS]:  NullInjectorError: No provider for InjectionToken CORE_OPTIONS!

4
yarn e2e
results in

WARNING in .\angular\node_modules\@abp\ng.theme.shared\__ivy_ngcc__\fesm2015\abp-ng.theme.shared.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
...
: Compiled successfully.
[14:19:53] I/launcher - Running 1 instances of WebDriver
[14:19:53] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:56381/devtools/browser/...
[14:19:55] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 86.0.4240.198 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
...
    at Object.checkLegacyResponse 
...

**Comment by maliming** [comment]
> Could not find the bundle file '/libs/abp/luxon/abp.luxon.js' from IWebContentFileProvider

You can try to update the `ABP's packages` in  `package.json` then run `yarn` and `gulp`.

**Comment by OzBob** [comment]
updated NPM packages in :
$abp-samples\BookStore-Angular-MongoDb\angular
updated nuget packages in:
$abp-samples\BookStore-Angular-MongoDb\aspnet-core

ran yarn in both OK

but gulp had no effect.
```
λ gulp
[15:44:36] Local modules not found in
```

Is there a gulp task file missing from the sample folder?

I'd like to help get this sample working for a new user, but at the moment it's missing an uptodate tutorial and/or readme.md

**Comment by maliming** [comment]
The https://github.com/abpframework/abp-samples has been upgraded recentlly.

**Comment by OzBob** [comment]
Thank you,  I tested with the latest code...

The site works, but only after I fork it and then make these changes:

https://github.com/OzBob/abp-samples/blob/master/README.md

then run your 'Yarn, Gulp' suggestion.

5
Testing the /api/app/author end point without doing 'login' first displays a HTML login page instead of an API 401 result.

At least now I have the basics working to trial the ABP + Ng project.
