### ISSUE TITLE
Can't load ServiceProxyScript if use a base class for Controllers

### ISSUE THREAD

**Issue by trgiangvp3** [abpframework/abp#6276]
I need to make the ValidateIP check into common, so I decided to create a base controller class.
But when I do that, get the following isssue.
I've already made the base controller abstract as mentioned at #5972 but nothing changes, the issue still there.
How could I fix this?

**1. ABP Framework version**
> 3.3.1 (Stable)

**2. User Interface:**
> MVC

**3. Exception message (as showing in Chrome Dev Tool)**
>       GET https://localhost:44388/Abp/ServiceProxyScript net::ERR_ABORTED 500
>   
> ![image](https://user-images.githubusercontent.com/48433917/99661751-e0ce2780-2a96-11eb-9a84-872ac7560eff.png)

**4. Steps needed to reproduce the problem**

4.1. Create the base Controller as below
```csharp
    public abstract class ToolMgrController : AbpController
    {
        protected readonly IAclRuleValidateService _aclValidateService;

        protected ToolMgrController(IAclRuleValidateService aclValidateService)
        {
            LocalizationResource = typeof(ToolMgrResource);
            _aclValidateService = aclValidateService;
        }

        protected async Task ValidateIPAsync()
        {
            await _aclValidateService.ValidateAccessIP(Request.HttpContext.Connection.RemoteIpAddress);
        }
    }
```

4.2. Let all other controller inherits from the base controller
```csharp
    [RemoteService(Name = ToolMgrHttpApiModule.RemoteServiceName)]
    [Route("api/lumiRequests")]
    public class LumiRequestsController : ToolMgrController, ILumiRequestAppService
    {
        private readonly ILumiRequestAppService _lumiRequestAppService;

        public LumiRequestsController(
            IAclRuleValidateService aclValidateService,
            ILumiRequestAppService lumiRequestAppService) 
            : base(aclValidateService)
        {
            _lumiRequestAppService = lumiRequestAppService;
        }
        // other code
    }
```

**5. Stack trace (as showing in log file)**
>    2020-11-19 18:22:44.535 +07:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null. (Parameter 'httpMethod')
   at Volo.Abp.Check.NotNull[T](T value, String parameterName)
   at Volo.Abp.Http.Modeling.ActionApiDescriptionModel.Create(String uniqueName, MethodInfo method, String url, String httpMethod, IList'1 supportedVersions)
   at Volo.Abp.AspNetCore.Mvc.AspNetCoreApiDescriptionModelProvider.AddApiDescriptionToModel(ApiDescription apiDescription, ApplicationApiDescriptionModel applicationModel, ApplicationApiDescriptionModelRequestDto input)
   at Volo.Abp.AspNetCore.Mvc.AspNetCoreApiDescriptionModelProvider.CreateApiModel(ApplicationApiDescriptionModelRequestDto input)
   at Volo.Abp.Http.ProxyScripting.ProxyScriptManager.CreateScript(ProxyScriptingModel scriptingModel)
   at Volo.Abp.Http.ProxyScripting.ProxyScriptManager.<>c__DisplayClass6_0.<GetScript>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary'2 dictionary, TKey key, Func'2 factory)
   at Volo.Abp.Http.ProxyScripting.ProxyScriptManagerCache.GetOrAdd(String key, Func'1 factory)
   at Volo.Abp.Http.ProxyScripting.ProxyScriptManager.GetScript(ProxyScriptingModel scriptingModel)
   at Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController.GetAll(ServiceProxyGenerationModel model)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by trgiangvp3** [comment]
I'm sorry. My bad.
There is something wrong in my newly added controller that causes the issue.
There is no problem with the base controller.
I will update the cause if I could find it later.

**Comment by maliming** [comment]
The reason is https://github.com/abpframework/abp/pull/6249

**Comment by trgiangvp3** [comment]
> The reason is #6249

Thank you.
The reason is I created a new Controller without specifying HttpMethod to each Action method.
I fixed the problem as below

```csharp
        public LumiRequestsController(
            IAclRuleValidateService aclValidateService,
            ILumiRequestAppService lumiRequestAppService) 
            : base(aclValidateService)
        {
            _lumiRequestAppService = lumiRequestAppService;
            //_aclValidateService = aclValidateService;

        }

        [HttpGet] // add this line to fix the problem
        [Route("{id}")]
        public async Task<LumiRequestDto> GetAsync(long id)
        {
            throw new System.NotImplementedException();
        }

        [HttpGet] // add this line to fix the problem
        public async Task<PagedResultDto<LumiRequestDto>> GetListAsync(LumiRequestFilterDto input)
        {
            throw new System.NotImplementedException();
        }

        [HttpPost] // add this line to fix the problem
        [Route("log")]
        public async Task<int> LogRequest(CreateUpdateLumiRequestDto lumiRequest)
        {
            await ValidateIPAsync();
            return await _lumiRequestAppService.LogRequest(lumiRequest);
        }
```
