### ISSUE TITLE
Search in documents not working on https://docs.abp.io

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#6284]
"Search in documents" action is not working whatever I search it doesn't response anything on https://docs.abp.io.

![search in docs-abp-io](https://user-images.githubusercontent.com/13360669/99681068-cee88680-2a8e-11eb-8216-5ec259ad5ed5.PNG)

**Comment by wakuflair** [comment]
I have the same issue.

**Comment by maliming** [comment]
hi @erolarkat 
Can you help to check the elasticsearch server status?

```cs
2020-11-20 06:17:11.794 +00:00 [Error] An error occurred in the elastic search api call.
System.Net.Http.HttpRequestException: Connection refused (elasticsearch-master:9200)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
```

**Comment by AdemAygun** [comment]
@erolarkat did you check?

**Comment by maliming** [comment]
hi @AdemAygun  We are working on it.

**Comment by maliming** [comment]
It's working now.

**Comment by AdemAygun** [comment]
thank you 👍  , I thought you were Turk and your name was Mehmet Ali  :)
