### ISSUE TITLE
abp identityserver4 pressure test /connect/token super slow!

### ISSUE THREAD

**Issue by redcatH** [abpframework/abp#6351]
### Documentation

my with services:
AuthServer.Host
MallService.Host

AuthServer.Host
```c#
            context.Services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = configuration["Redis:Configuration"];
            });

            //context.Services.AddClientStoreCache
            // Configure<AbpAuditingOptions>(options =>
            // {
            //     options.IsEnabledForGetRequests = true;
            //     options.ApplicationName = "AuthServer";
            // });

            //TODO: ConnectionMultiplexer.Connect call has problem since redis may not be ready when this service has started!
            var redis = ConnectionMultiplexer.Connect(configuration["Redis:Configuration"]);
            context.Services.AddDataProtection()
                .PersistKeysToStackExchangeRedis(redis, "MsDemo-DataProtection-Keys");
```
MallService.Host
```c#
        private async Task<JwtDto> GetToken(IdentityUser abpUser, T_Sys_User user)
        {
            

            // var disco = await serverClient.GetDiscoveryDocumentAsync(Configuration["AuthServer:Authority"]);
            var tokenEndpoint = await _ids4ClientCacheService.GetAsync();
            var serverClient = HttpClientFactory.CreateClient();
            var result = await serverClient.RequestTokenAsync(
                new TokenRequest
                {
                    Address = tokenEndpoint,
                    GrantType = "MallUser",
                    ClientId = Configuration["AuthServer:ClientId"],
                    ClientSecret = Configuration["AuthServer:ClientSecret"],
                    Parameters =
                    {
                        {"user_id", $"{abpUser.Id}"},
                        {"mall_UserId", $"{user.FUserID}"},
                        {
                            "mall_UserName", $"{user.FUserName}"
                        },
                        {
                            "scope", "MallService offline_access"
                        }
                    }
                });
            var token = result.AccessToken;
            if (token.IsNullOrWhiteSpace()) throw new UserFriendlyException(result.Error);
            return new JwtDto
            {
                AccessToken = token,
                RefreshToken = result.RefreshToken
            };
        }
```
no batch request
![qq1](https://user-images.githubusercontent.com/30196697/100235558-8ab22600-2f67-11eb-887a-ba9fe8c79463.png)

ues web api benchmarks ,batch request
![qq](https://user-images.githubusercontent.com/30196697/100234942-b8e33600-2f66-11eb-8cef-59663879176e.png)

@hikalkan 
The problem is very anxious, I suggest that the company use ABP, if it can not be solved, I may lose my job! Help me thanks！

From what I understand, there are others who have encountered the same problem.

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by redcatH** [comment]
abp version:3.3.1
download:https://abp.io/get-started 
```c#
CompanyAndProjectName=ids4test
ProjectType=app
UiFramework=angular
DatabaseProvider=EntityFrameworkCore
Mobile=None
IncludeUi=true
Tiered=false
SeparateIdentityServer=false
Preview=false
IncludeUi=false
```
url: http://192.168.201.103:44346/connect/token
jmteter
setting
![jem](https://user-images.githubusercontent.com/30196697/100308203-bf16f800-2fe2-11eb-9790-dd82765493fb.png)
![request](https://user-images.githubusercontent.com/30196697/100308255-e66dc500-2fe2-11eb-92fd-e0e195883889.png)
summary report
![report](https://user-images.githubusercontent.com/30196697/100308332-1a48ea80-2fe3-11eb-9e6b-7065b76fca47.png)
view results tree
![view results tree](https://user-images.githubusercontent.com/30196697/100308417-51b79700-2fe3-11eb-9c34-62b4d75a241d.png)
response time graph
![response time graph](https://user-images.githubusercontent.com/30196697/100308499-83306280-2fe3-11eb-8ab8-06f1ae6617b5.png)



During this period I also tried PostMan
![postman](https://user-images.githubusercontent.com/30196697/100308608-c7236780-2fe3-11eb-94f3-6a9acfca5109.png)
postman response context
```c#
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextWithTransaction(IUnitOfWork unitOfWork)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContext(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.<>c__DisplayClass3_0.
<GetDbContext>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.get_DbSet()
   at Volo.Abp.IdentityServer.Clients.ClientRepository.FindByCliendIdAsync(String clientId, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.IdentityServer.Clients.ClientStore.FindClientByIdAsync(String clientId)
   at IdentityServer4.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId)
   at IdentityServer4.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<
    <UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<
        <UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<
            <UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<
                <UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: jenkins-timestamper-offset=-28800000
Host: 192.168.201.103:44346
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Origin: chrome-extension://coohjcphdfgbiolnekdpbcijmhambjff
Content-Length: 111
X-Correlation-Id: 9e2f41c538fd49d9bf6796371c51bc9a
```

**Comment by redcatH** [comment]
two test
Modify the connection string Add Max Pool Size=5000
Server=192.168.201.16,1433; Database=IdentityTest; User=sa; Password=123; Max Pool Size=5000;Min Pool Size=0

jmeter setting unchanging
![2](https://user-images.githubusercontent.com/30196697/100311985-0786e380-2fec-11eb-9c91-8a97639469a3.png)
![3](https://user-images.githubusercontent.com/30196697/100311995-0bb30100-2fec-11eb-96cf-0d3ef6c38bb7.png)
![微信图片_20201126133252](https://user-images.githubusercontent.com/30196697/100311999-0ce42e00-2fec-11eb-8fcf-e96048174b52.png)

response time  30000!

**Comment by redcatH** [comment]
@maliming

**Comment by maliming** [comment]
You can test the application of Identity Server4(include Identity & EF Core)

https://identityserver4.readthedocs.io/en/latest/quickstarts/5_entityframework.html
https://identityserver4.readthedocs.io/en/latest/quickstarts/6_aspnet_identity.html

**Comment by zhjmao** [comment]
i encountered the same problem。
abp version:4.0.0

https://localhost:44357/connect/token

![image](https://user-images.githubusercontent.com/50391373/101125088-56a7c680-3633-11eb-9ee2-b124b667c774.png)

**Comment by Alexbits** [comment]
> i encountered the same problem。
> abp version:4.0.0
> 
> https://localhost:44357/connect/token

Hi @zhjmao Did you solve this problem?

**Comment by zhjmao** [comment]
> > i encountered the same problem。
> > abp version:4.0.0
> > https://localhost:44357/connect/token
> 
> Hi @zhjmao Did you solve this problem?

after update to version 4.1，it works fine

**Comment by Alexbits** [comment]
> after update to version 4.1，it works fine

Thanks @zhjmao I get >400ms on token,login-callback,authorize
