### ISSUE TITLE
AbpTypeExtensions.IsAssignableTo throw exception ,when we try to invoke a httpContext in a log middleware.

### ISSUE THREAD

**Issue by compass-yan** [abpframework/abp#6488]
#### Basic Info
abp vnext version:3.3.1
webapi
#### stack trace
`
System.ArgumentNullException: Value cannot be null. (Parameter 'type')
   at Volo.Abp.Check.NotNull[T](T value, String parameterName)
   at System.AbpTypeExtensions.IsAssignableTo[TTarget](Type type)
   at Volo.Abp.AspNetCore.Mvc.ModelBinding.AbpExtraPropertiesDictionaryModelBinderProvider.GetBinder(ModelBinderProviderContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, Object token)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.CreateBinderDelegate(ParameterBinder parameterBinder, IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SSService.Middleware.Jump404Middleware.Invoke(HttpContext context) in 
项目路径\Middleware\Jump404Middleware.cs:line 27
   at SSService.Middleware.LogMiddleware.Invoke(HttpContext httpContext) in 
项目路径\Middleware\LogMiddleware.cs:line 32
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`
##### Startup.cs
- ConfigureServices
`
public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplication<SSServiceModule>();
            services.AddMemoryCache();
            services.AddControllers();
            services.AddHttpClient("whois", client =>
            {
                client.BaseAddress = new Uri("省略");//设置这个HttpClient要请求地址的Base路径
            }); // httpclient第三方接口调用
            services.AddHttpClient("webhook", client =>
            {
                client.BaseAddress = new Uri("省略");//设置这个HttpClient要请求地址的Base路径
            });
            services.AddSingleton<Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Http.HttpContextAccessor>(); // 用于获取IP
            services.AddControllers().AddNewtonsoftJson(option =>
            {
                //配置序列化时时间格式为yyyy-MM-dd HH:mm:ss
                option.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
            });
            // 配置Cors授权策略
            services.AddCors(optios =>
            {
                optios.AddPolicy(_corsPolicyName,
                    builder =>
                    {
                       builder.WithOrigins(CORS)
                      .AllowAnyHeader()
                      .AllowAnyMethod();
                    });
            });
            services.AddMvc(options =>
            {
                options.Filters.Add(new LoginFilter());
                options.Filters.Add(new JurisdictionFilter());
            }
            ).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
            // Register the Swagger services
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo() { Title = " API", Version = "v1" });
                options.DocInclusionPredicate((docName, description) => true);
                options.CustomSchemaIds(s => s.FullName);
                // Define the BearerAuth scheme that's in use
                options.AddSecurityDefinition("bearerAuth", new OpenApiSecurityScheme()
                {
                    Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.ApiKey
                });
            });
        }
`
- Configure
`
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.InitializeApplication();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            // Enable middleware to serve generated Swagger as a JSON endpoint
            app.UseSwagger();
            // Enable middleware to serve swagger-ui assets (HTML, JS, CSS etc.)
            app.UseSwaggerUI(options =>
            {
                options.SwaggerEndpoint("/swagger/v1/swagger.json", " API V1");
                options.RoutePrefix = string.Empty;
            }); // URL: /swagger
            app.UseMiddleware<LogMiddleware>();
            // 跳转404 error页面
            app.UseMiddleware<Jump404Middleware>();
            app.UseRouting();
            // 允许跨越请求访问
            app.UseCors(_corsPolicyName);
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            // 此中间件需放到靠后的位置，否则会影响跨域的配置
            app.UseHttpsRedirection();
        }
`
##### My Module——SSServiceModule
- ConfigureServices
`
 context.Services.AddAbpDbContext<CapTableDbContext>(options =>
            {
                options.AddDefaultRepositories(includeAllEntities: true);
            });
`
- OnApplicationInitialization
None
- DependsOn Attribute
`
  typeof(CapitalisationDomainModule),
       typeof(CapTableApplicationModule),
        typeof(CapTableEntityFrameworkCoreModule),
        //typeof(CapTableHttpApiModule),
        typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
        typeof(AbpAutofacModule),
        //typeof(AbpCachingStackExchangeRedisModule),
        typeof(AbpEntityFrameworkCoreSqlServerModule),
        //typeof(AbpAuditLoggingEntityFrameworkCoreModule),
        //typeof(AbpPermissionManagementEntityFrameworkCoreModule),
        //typeof(AbpSettingManagementEntityFrameworkCoreModule),
        typeof(AbpAspNetCoreSerilogModule)
`

##### Jump404Middleware
`
 private readonly RequestDelegate next;

        public Jump404Middleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task Invoke(
            Microsoft.AspNetCore.Http.HttpContext context)
        {
            await next.Invoke(context);

            var response = context.Response;

           ...
        }
`

**That's All.Please Help Me.Thx**

**Comment by maliming** [comment]
You should provide detailed code instead of some screenshots.

If you can use the template project to reproduce the problem, please provide the steps.

**Comment by compass-yan** [comment]
@maliming Ok,I haven use detailed code instead of these screenshots.And I try to reproduce in the template project ,It don't have this problem.So I think maybe there is wrong in  my setting .

**Comment by compass-yan** [comment]
I had solve this issue.And pull  request.So close it.I add about that argument nullable judge
