### ISSUE TITLE
Quartz.Serialization.Json (3.2.3) not working with latest release 4.0.0

### ISSUE THREAD

**Issue by wade712vn** [abpframework/abp#6542]
With latest release of abp 4.0.0 using .NET 5.0. Whenever I add the package Quartz.Serialization.Json (3.2.3) and set AbpBackgroundJobsQuartzModule as a dependency for my module 

`[DependsOn(
        ...
        typeof(AbpBackgroundJobsQuartzModule)
        )]
    public class BookStoreApplicationModule : AbpModule`

I get this error at startup

```
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.Quartz.AbpQuartzModule, Volo.Abp.Quartz, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'Void Quartz.IPropertyConfigurer.SetProperty(System.String, System.String)'.
   at Quartz.TimeZonePluginConfigurationExtensions.UseTimeZoneConverter[T](T schedulerBuilder)
   at Volo.Abp.Quartz.AbpQuartzModule.<>c__DisplayClass1_0.<ConfigureServices>b__0(IServiceCollectionQuartzConfigurator build)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, NameValueCollection properties, Action`1 configure)
   at Volo.Abp.Quartz.AbpQuartzModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Acme.BookStore.Web.Startup.ConfigureServices(IServiceCollection services) in G:\Giang\src\Acme.BookStore.Web\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()`
```
Does anyone have the same issue?
Thanks

**Comment by maliming** [comment]
Please use version 3.0.7

https://github.com/abpframework/abp/blob/rel-4.0/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.Quartz/Volo.Abp.BackgroundJobs.DemoApp.Quartz.csproj#L9

**Comment by maliming** [comment]
Follow this issue: https://github.com/abpframework/abp/pull/6460
