### ISSUE TITLE
Cannot access a disposed context instance

### ISSUE THREAD

**Issue by ihoeysun** [abpframework/abp#6552]
hello,

my abp version is 4.0.0, 
when i  call grpc throw exception  with dbcontext  is disposed.

exception message:
```
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'TransactionDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Grace.Shop.Transaction.GrpcServices.UserWealthGrpcServiceImpl.QueryUserBalance(QueryBalanceRequest request, ServerCallContext context) in D:\company\code\server-lab\Grace.Shop\modules\transaction\src\Grace.Shop.Transaction.Application\GrpcServices\UserWealthGrpcServiceImpl.cs:line 89
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```
code:
```
 [UnitOfWork]
        public override  async Task<QueryBalanceResult> QueryUserBalance(QueryBalanceRequest request, ServerCallContext context)
        {
            var wealth = await _userWealthRepository.Where(x => x.UserId == Guid.Parse(request.UserId)).FirstOrDefaultAsync();

            if (wealth is null)
            {
                return new QueryBalanceResult() { ArtistBalance = 0, Coin = 0, Points = 0 };
            }

            return new QueryBalanceResult() { ArtistBalance = 99, Coin = 0, Points = 0 };

            //return new QueryBalanceResult() { ArtistBalance = (double)wealth.ArtistBalance, Coin = wealth.Coin, Points = wealth.Points };
        }
```
How to solve?
thanks

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Unit-Of-Work#unitofworkattribute

**Comment by rygar08** [comment]
Did you find a answer to this issue?

**Comment by stonestecnologia** [comment]
Hi !
Did you find a answer to this issue?
Please.
