### ISSUE TITLE
SettingManagement causes SettingProvider to fail to obtain data。

### ISSUE THREAD

**Issue by lfzm** [abpframework/abp#6553]
My Abp version ：v4.0.0
My User Interface： No，Is Webapi
My use database : Mysql 8.0.17

【**Business**】
Use Volo.Abp.Emailing to send mail, and obtain configuration from Mysql database through `Volo.Abp.Settings GlobalSettingValueProvider`.
The configuration is as follows，The **ProviderKey** value in the database is **Null**.

![image](https://user-images.githubusercontent.com/28291464/101620635-be08b080-3a4f-11eb-93b9-94420df03c91.png)

execute  
```  
var setting = await settingProvider.GetAllAsync();
```
An unexpected error occurred，Same problem with abp version  v3.2.2 

**Stack trace**:
```  
   One of the identified items was in an invalid format.

   at MySqlConnector.Core.TextRow.GetValueCore(ReadOnlySpan`1 data, ColumnDefinitionPayload columnDefinition) in /_/src/MySqlConnector/Core/TextRow.cs:line 58
   at MySqlConnector.Core.Row.GetValue(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 38
   at MySqlConnector.Core.Row.GetGuid(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 165
   at MySqlConnector.MySqlDataReader.GetGuid(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 232
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadGuid(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.<InitializeAsync>d__90.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   .....
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ......
   at Volo.Abp.SettingManagement.SettingManagementStore.<SetCacheItemsAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.SettingManagement.SettingManagementStore.<GetCacheItemAsync>d__17.MoveNext()
   ......
   at AbpMail.EmailService.<Send>d__0.MoveNext() in D:\Desktop\ABP Email\AbpMail\AbpMail\Services\EmailService.cs:line 24
```

Check the source code and find that there may be bugs here.

https://github.com/abpframework/abp/blob/dd208f156c2395595839027ba1625c311a0a5cfd/modules/setting-management/src/Volo.Abp.SettingManagement.EntityFrameworkCore/Volo/Abp/SettingManagement/EntityFrameworkCore/SettingManagementDbContextModelBuilderExtensions.cs#L51

I modified the data in the database。The **ProviderKey** value in the database is **1**.
![image](https://user-images.githubusercontent.com/28291464/101620739-de386f80-3a4f-11eb-857c-381dbac48b20.png)

execute   `var setting = await settingProvider.GetAllAsync();` , No unexpected error occurred, but no data 。

View source code discovery，The `GlobalSettingValueProvider.GetOrNullAsync` method passes the value of the ProviderKey parameter to Null, so the data in the database is definitely not available.

https://github.com/abpframework/abp/blob/dd208f156c2395595839027ba1625c311a0a5cfd/framework/src/Volo.Abp.Settings/Volo/Abp/Settings/GlobalSettingValueProvider.cs#L20

**Issue**：

Migrating the database through `SettingManagement`, using `GlobalSettingValueProvider` cannot get the data in the Mysql database, and there should be problems with other data

**Suggest change into**：
https://github.com/abpframework/abp/blob/dd208f156c2395595839027ba1625c311a0a5cfd/modules/setting-management/src/Volo.Abp.SettingManagement.EntityFrameworkCore/Volo/Abp/SettingManagement/EntityFrameworkCore/SettingManagementDbContextModelBuilderExtensions.cs#L51

```
 b.HasIndex(x => new {x.Name, x.ProviderName}); 
```

**Comment by realLiangshiwei** [comment]
The id type **should be GUID**. I think it has nothing to do with ABP.

![image](https://user-images.githubusercontent.com/16813853/103327636-52cf5e80-4a90-11eb-938c-f43f627fa222.png)

**Comment by yel-best** [comment]
@lfzm  hi~ lfzm,
I would like to ask how you write the Settings into the DB Settings table, I don't know if you remember the question. thank you
