### ISSUE TITLE
Domain Tenant Resolver not able to resolve domain with predefined subdomain

### ISSUE THREAD

**Issue by Znow** [abpframework/abp#6562]
Hi there

Have been using the DomainTenantResolver with luck for quite some time, with the following structure:

```
options.AddDomainTenantResolver("{0}.somedomain.com");
```

But I want to use the below structure aswell:
```
options.AddDomainTenantResolver("something.{0}.com");
```

Where {0} is a regular domain, which should resolve to an existing tenant with the same name - but I keep getting http 500 error with the below from logs:

```
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.MultiTenancy.TenantConfigurationProvider.GetAsync(Boolean saveResolveResult)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2020-12-09 22:22:51.923 +00:00 [ERR] Connection ID "15852670689954769120", Request ID "800028e1-0000-dc00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.MultiTenancy.TenantConfigurationProvider.GetAsync(Boolean saveResolveResult)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

```

How could this be fixed? Or is it perhaps not fully supported

Thanks in advance

Regards

**Comment by maliming** [comment]
What's the request URL when got the error log?

**Comment by vnetonline** [comment]
The format you want to use is not subdomain it is top level domain i dont think it is support

Vineet
LearnABPFramework.com

**Comment by Znow** [comment]
> maliming
> What's the request URL when got the error log?

@maliming 

I have the following domain "insight.preact.dk", which is setup as an A record, pointing to my Azure App.
"preact" resolves to a existing tenant, and in my code I have:

```
options.AddDomainTenantResolver("insight.{0}.dk");
```


> The format you want to use is not subdomain it is top level domain i dont think it is support
> 
> Vineet
> LearnABPFramework.com

No, a top level domain, or TLD is .com, .net, .org etc.

**Comment by vnetonline** [comment]
You are right I think only sub domains are supported 

Like this options.AddDomainTenantResolver("{TENANT_NAME}.yourdomainname.dk");
