### ISSUE TITLE
Error on add new module to solution

### ISSUE THREAD

**Issue by EugeniZaplatin** [abpframework/abp#6832]
C:\projects\00_Zefslab\MyExchange.Framework\TradingStrategies>abp add-module LowRiskStrategy --new  -v 4.0.2
[15:35:10 INF] ABP CLI (https://abp.io)
[15:35:10 INF] Version 4.0.2 (Stable)
[15:35:11 INF] Installing module 'LowRiskStrategy' to the solution 'MyExchange.TradingStrategies'
[15:35:11 INF] Creating your project...
[15:35:11 INF] Project name: LowRiskStrategy
[15:35:11 INF] Template: module
[15:35:11 INF] Version: 4.0.2
[15:35:11 INF] Create Solution Folder: no
[15:35:11 INF] Output folder: C:\projects\00_Zefslab\MyExchange.Framework\TradingStrategies\modules\LowRiskStrategy
[15:36:52 INF] Downloading template: module, version: 4.0.2
Error occured while downloading source-code from https://abp.io/api/download/template/ : '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[15:38:33 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)

**Comment by hikalkan** [comment]
Currently, there is a problem with the server. We are working on. Thanks for reporting.

**Comment by vnetonline** [comment]
Yup getting the following again 

![image](https://user-images.githubusercontent.com/15242923/103172821-5f925d80-48aa-11eb-9722-83f742adac57.png)

**Comment by hikalkan** [comment]
Should be fixed now. Thanks and sorry.
