### ISSUE TITLE
OrganizationUnit in entity

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#6896]
Hello, just found an issue for use the OrganizationUnit in entity.
for any entity, if I add these properties, 
 public Guid? OrganizationUnitId { get; set; }
 public OrganizationUnit OrganizationUnit { get; set; }

I'll get this error message,  what's the correct way to use OrganizatoinUnit?

```
System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.Initialize(AbpEfCoreDbContextInitializationContext initializationContext)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContext(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.<>c__DisplayClass3_0.<GetDbContext>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at Volo.Abp.Uow.UnitOfWork.GetOrAddDatabaseApi(String key, Func`1 factory)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.get_DbContext()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.get_DbSet()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetQueryable()
   at Volo.Abp.Domain.Repositories.RepositoryBase`1.get_Provider()
   at Castle.Proxies.Invocations.IQueryable_get_Provider.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedSynchronous[TResult](IInvocation invocation, IInvocationProceedInfo
````

 I tried 4.0.2 and 4.1.0-rc2, MVC, EF Core。

Thanks!

**Comment by maliming** [comment]
Can you share some code to reproduce the problem?

**Comment by juchunwei** [comment]
> Can you share some code to reproduce the problem?

For example,

I added these 2 lines in the AppUser entity or any entity I did,  I just did one entity and one page, very simple, the error occurs when I open the page, but the Roles and Users pages no problem. but it works if I comment the public OrganizationUnit OrganizationUnit { get; set; } line.

and the error occurs when I run the add-migration in the EntityFrameworkCore project. 

 public Guid? OrganizationUnitId { get; set; }
        public OrganizationUnit OrganizationUnit { get; set; }

**Comment by ThreeLambs** [comment]
> > Can you share some code to reproduce the problem?
> 
> For example,
> 
> I added these 2 lines in the AppUser entity or any entity I did, I just did one entity and one page, very simple, the error occurs when I open the page, but the Roles and Users pages no problem. but it works if I comment the public OrganizationUnit OrganizationUnit { get; set; } line.
> 
> and the error occurs when I run the add-migration in the EntityFrameworkCore project.
> 
> public Guid? OrganizationUnitId { get; set; }
> public OrganizationUnit OrganizationUnit { get; set; }
You can refer to my OrganizationUnit  demo, although there are still some bugs.
 https://github.com/abpframework/abp/issues/6882#issue-776154355

**Comment by maliming** [comment]
@juchunwei Can you share a demo project?

**Comment by juchunwei** [comment]
> @juchunwei Can you share a demo project?

Hi mailming, here's the link for the demo. it works  if you comment the line public OrganizationUnit OrganizationUnit { get; set; } in AppUser

https://www.dropbox.com/s/yt3qczkhjg94mhw/Exam4.0.2.zip?dl=0

**Comment by maliming** [comment]
The problem cannot be reproduced.

**Comment by juchunwei** [comment]
> The problem cannot be reproduced.

that's wired. I got the same issue just now.

**Comment by juchunwei** [comment]
> The problem cannot be reproduced.

Have you tried to open the link on the menu? the Questions menu.

**Comment by zhjmao** [comment]
i'm in the same situation。

 this is not a issue in my opinion .

OrganizationUnit  using a different DbContext。

mabe we should do samething like the appuser entity ，to share the OrganizationUnit   entity in different DbContext。but i dont konw how to do。any one can help?

**Comment by sgalcheung** [comment]
Just simply call _organizationUnitManager.FindChildrenAsync(organizationUnit.Id);
This problem will arise because he calls GetChildrenAsync(), which uses queryable.Include(x => x.Roles); to query OrganizationUnitRole

**Comment by sgalcheung** [comment]
Just simply call _organizationUnitManager.FindChildrenAsync(organizationUnit.Id);
This problem will arise because he calls GetChildrenAsync(), which uses queryable.Include(x => x.Roles); to query OrganizationUnitRole
