### ISSUE TITLE
Swashbuckle error

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#6900]
abp v4.0.2
Tiered
Blazor UI

This error apperas only in production (Docker):

```
[11:44:29 ERR] An unhandled exception has occurred while executing the request.


Autofac.Core.DependencyResolutionException: An exception was thrown while activating Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator -> λ:Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions -> Microsoft.Extensions.Options.OptionsManager`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]][] -> Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.


 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions], System.IServiceProvider, Microsoft.AspNetCore.Hosting.IWebHostEnvironment)' on type 'ConfigureSwaggerGeneratorOptions'.


 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.


   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)


   at System.Uri..ctor(String uriString)


   at Microsoft.Extensions.DependencyInjection.AbpSwaggerGenServiceCollectionExtensions.<>c__DisplayClass0_0.<AddAbpSwaggerGenWithOAuth>b__0(SwaggerGenOptions options)


   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)


   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)


   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()


   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)


   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)


   at System.Lazy`1.CreateValue()


   at lambda_method765(Closure , Object[] )


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   --- End of inner exception stack trace ---


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   --- End of inner exception stack trace ---


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.Execute()


   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)


   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)


   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)


   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)


   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)


   at lambda_method360(Closure , Object , HttpContext , IServiceProvider )


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<UseMiddleware>b__2(HttpContext context)


   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)


[11:44:29 ERR] An exception was thrown attempting to execute the error handler.


Autofac.Core.DependencyResolutionException: An exception was thrown while activating Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator -> λ:Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions -> Microsoft.Extensions.Options.OptionsManager`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]][] -> Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.


 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions], System.IServiceProvider, Microsoft.AspNetCore.Hosting.IWebHostEnvironment)' on type 'ConfigureSwaggerGeneratorOptions'.


 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.


   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)


   at System.Uri..ctor(String uriString)


   at Microsoft.Extensions.DependencyInjection.AbpSwaggerGenServiceCollectionExtensions.<>c__DisplayClass0_0.<AddAbpSwaggerGenWithOAuth>b__0(SwaggerGenOptions options)


   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)


   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)


   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()


   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)


--- End of stack trace from previous location ---


   at System.Lazy`1.CreateValue()


   at lambda_method765(Closure , Object[] )


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   --- End of inner exception stack trace ---


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   --- End of inner exception stack trace ---


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.Execute()


   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)


   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)


   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)


   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)


   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)


   at lambda_method360(Closure , Object , HttpContext , IServiceProvider )


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<UseMiddleware>b__2(HttpContext context)


   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)


[11:44:29 ERR] Connection id "0HM5CN121U18H", Request id "0HM5CN121U18H:00000002": An unhandled exception was thrown by the application.


Autofac.Core.DependencyResolutionException: An exception was thrown while activating Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator -> λ:Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions -> Microsoft.Extensions.Options.OptionsManager`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]][] -> Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.


 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions], System.IServiceProvider, Microsoft.AspNetCore.Hosting.IWebHostEnvironment)' on type 'ConfigureSwaggerGeneratorOptions'.


 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.


   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)


   at System.Uri..ctor(String uriString)


   at Microsoft.Extensions.DependencyInjection.AbpSwaggerGenServiceCollectionExtensions.<>c__DisplayClass0_0.<AddAbpSwaggerGenWithOAuth>b__0(SwaggerGenOptions options)


   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)


   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)


   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()


   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)


--- End of stack trace from previous location ---


   at System.Lazy`1.CreateValue()


   at lambda_method765(Closure , Object[] )


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   --- End of inner exception stack trace ---


   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()


   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   --- End of inner exception stack trace ---


   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)


   at Autofac.Core.Resolving.InstanceLookup.Execute()


   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)


   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)


   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)


   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)


   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)


   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)


   at lambda_method360(Closure , Object , HttpContext , IServiceProvider )


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<UseMiddleware>b__2(HttpContext context)


   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)


   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()


--- End of stack trace from previous location ---


   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)


[11:44:29 INF] Request finished HTTP/1.1 GET http://172.20.0.103/ - - - 500 0 - 612.2073ms
```

**Comment by realLiangshiwei** [comment]
**Invalid URI: The format of the URI could not be determined.**

Seems related to your configuration

**Comment by leonkosak** [comment]
It's true! :)
