### ISSUE TITLE
Volo.Abp.BackgroundJobs.DemoApp.RabbitMq miss appsettings.json

### ISSUE THREAD

**Issue by niufwshd** [abpframework/abp#6955]
- apb 4.0  project Volo.Abp.BackgroundJobs.DemoApp.RabbitMq
-issue 
Unhandled exception. Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.BackgroundJobs.RabbitMQ.AbpBackgroundJobsRabbitMqModule, Volo.Abp.BackgroundJobs.RabbitMQ, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null: **None of the specified endpoints were reachable**. See the inner exception for details.
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Connection failed)
 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at Volo.Abp.RabbitMQ.ConnectionPool.<>c__DisplayClass8_0.<Get>b__0() in E:\code\abp\abp\framework\src\Volo.Abp.RabbitMQ\Volo\Abp\RabbitMQ\ConnectionPool.cs:line 30
   at System.Collections.Generic.AbpDictionaryExtensions.<>c__DisplayClass6_0`2.<GetOrAdd>b__0(TKey k) in E:\code\abp\abp\framework\src\Volo.Abp.Core\System\Collections\Generic\AbpDictionaryExtensions.cs:line 115
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory) in E:\code\abp\abp\framework\src\Volo.Abp.Core\System\Collections\Generic\AbpDictionaryExtensions.cs:line 101
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 factory) in E:\code\abp\abp\framework\src\Volo.Abp.Core\System\Collections\Generic\AbpDictionaryExtensions.cs:line 115
   at Volo.Abp.RabbitMQ.ConnectionPool.Get(String connectionName) in E:\code\abp\abp\framework\src\Volo.Abp.RabbitMQ\Volo\Abp\RabbitMQ\ConnectionPool.cs:line 28
   at Volo.Abp.RabbitMQ.ChannelPool.CreateChannel(String channelName, String connectionName) in E:\code\abp\abp\framework\src\Volo.Abp.RabbitMQ\Volo\Abp\RabbitMQ\ChannelPool.cs:line 54
   at Volo.Abp.RabbitMQ.ChannelPool.<>c__DisplayClass19_0.<Acquire>b__0(String _) in E:\code\abp\abp\framework\src\Volo.Abp.RabbitMQ\Volo\Abp\RabbitMQ\ChannelPool.cs:line 40
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Volo.Abp.RabbitMQ.ChannelPool.Acquire(String channelName, String connectionName) in E:\code\abp\abp\framework\src\Volo.Abp.RabbitMQ\Volo\Abp\RabbitMQ\ChannelPool.cs:line 38
   at Volo.Abp.BackgroundJobs.RabbitMQ.JobQueue`1.EnsureInitializedAsync() in E:\code\abp\abp\framework\src\Volo.Abp.BackgroundJobs.RabbitMQ\Volo\Abp\BackgroundJobs\RabbitMQ\JobQueue.cs:line 128
   at Volo.Abp.BackgroundJobs.RabbitMQ.JobQueue`1.StartAsync(CancellationToken cancellationToken) in E:\code\abp\abp\framework\src\Volo.Abp.BackgroundJobs.RabbitMQ\Volo\Abp\BackgroundJobs\RabbitMQ\JobQueue.cs:line 99
   at Volo.Abp.BackgroundJobs.RabbitMQ.JobQueueManager.StartAsync(CancellationToken cancellationToken) in E:\code\abp\abp\framework\src\Volo.Abp.BackgroundJobs.RabbitMQ\Volo\Abp\BackgroundJobs\RabbitMQ\JobQueueManager.cs:line 42
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass15_0.<Run>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Threading.AsyncHelper.RunSync(Func`1 action) in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\AsyncHelper.cs:line 74
   at Volo.Abp.BackgroundJobs.RabbitMQ.AbpBackgroundJobsRabbitMqModule.StartJobQueueManager(ApplicationInitializationContext context) in E:\code\abp\abp\framework\src\Volo.Abp.BackgroundJobs.RabbitMQ\Volo\Abp\BackgroundJobs\RabbitMQ\AbpBackgroundJobsRabbitMqModule.cs:line 32
   at Volo.Abp.BackgroundJobs.RabbitMQ.AbpBackgroundJobsRabbitMqModule.OnApplicationInitialization(ApplicationInitializationContext context) in E:\code\abp\abp\framework\src\Volo.Abp.BackgroundJobs.RabbitMQ\Volo\Abp\BackgroundJobs\RabbitMQ\AbpBackgroundJobsRabbitMqModule.cs:line 22
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.Initialize(ApplicationInitializationContext context, IAbpModule module) in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\DefaultModuleLifecycleContributor.cs:line 7
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleManager.cs:line 43
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleManager.cs:line 47
   at Volo.Abp.AbpApplicationBase.InitializeModules() in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 74
   at Volo.Abp.AbpApplicationWithInternalServiceProvider.Initialize() in E:\code\abp\abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationWithInternalServiceProvider.cs:line 39
   at Volo.Abp.BackgroundJobs.DemoApp.RabbitMq.Program.Main(String[] args) in E:\code\abp\abp\modules\background-jobs\app\Volo.Abp.BackgroundJobs.DemoApp.RabbitMq\Program.cs:line 14

It is a little missing. I created a appsettings.json and and `{
  "RabbitMQ": {
    "Connections": {
      "Default": {
        "HostName": "192.168.121.128"
      }
    }
  }
}`
and it was runinng.

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/Background-Jobs-RabbitMq#default-configuration
