### ISSUE TITLE
[Identity Module] 'AbpReadonlyInputType' does not contain a definition for '' "

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#700]
In:
`Pages> Identity> Shared> MySettingModal.cshtml`

> 'AbpReadonlyInputType'does not contain a definition for ''false"

`Pages> Identity> Roles> EditModal.cshtml`
> 'AbpReadonlyInputType'does not contain a definition for ''true"

**Comment by hitaspdotnet** [comment]
log:

> 
> [ERR] An unhandled exception has occurred while executing the request.
> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(22,169): error CS1001: Identifier expected
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(22,169): error CS1002: ; expected
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(33,169): error CS1001: Identifier expected
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(33,169): error CS1002: ; expected
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(22,169): error CS0117: 'AbpReadonlyInputType' does not contain a definition for ''
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(22,169): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(33,169): error CS0117: 'AbpReadonlyInputType' does not contain a definition for ''
> D:\Github\HitaspDotNet\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Shared\PersonalSettingsModal.cshtml(33,169): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
>    at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.Invoke(HttpContext httpContext) in D:\Github\HitaspDotNet\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Auditing\AbpAuditingMiddleware.cs:line 35
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
