### ISSUE TITLE
 Common Language Runtime detected an invalid program.     System.InvalidProgramException: Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by yaoyuansheng** [abpframework/abp#7051]
I got a problem，but I don't know why and how to solve it

![image](https://user-images.githubusercontent.com/13847155/103754018-c18b5980-5046-11eb-83ae-e0cfb43f49af.png)

![image](https://user-images.githubusercontent.com/13847155/103754656-98b79400-5047-11eb-9a74-111911650279.png)

[17:37:49 INF] Executing endpoint 'Boss.AuthCenter.Account.AccountController.UserSyncAsync (Boss.AuthCenter.HttpApi.App)'
[17:37:49 INF] Route matched with {action = "UserSync", controller = "Account", area = ""}. Executing controller action with signature System.Threading.Tasks.Task UserSyncAsync(Boss.AuthCenter.Account.Commands.UserSyncCommand) on controller Boss.AuthCenter.Account.AccountController (Boss.AuthCenter.HttpApi.App).
[17:37:51 INF] Executing action method Boss.AuthCenter.Account.AccountController.UserSyncAsync (Boss.AuthCenter.HttpApi.App) - Validation state: Valid
[17:38:03 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

[17:38:03 ERR] Common Language Runtime detected an invalid program.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at Castle.Proxies.Invocations.IAccountExternalAppService_UserSyncAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Boss.AuthCenter.Account.AccountController.UserSyncAsync(UserSyncCommand input) in D:\projects\ami\Boss.AuthCenter\src\Boss.AuthCenter.HttpApi.App\Account\AccountController.cs:line 25
   at lambda_method844(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:38:03 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[17:38:03 INF] Executed action Boss.AuthCenter.Account.AccountController.UserSyncAsync (Boss.AuthCenter.HttpApi.App) in 14439.2136ms
[17:38:03 INF] Executed endpoint 'Boss.AuthCenter.Account.AccountController.UserSyncAsync (Boss.AuthCenter.HttpApi.App)'[17:38:03 INF] AUDIT LOG: [500: POST   ] /api/app/account/user-sync
- UserName - UserId                 :  -
- ClientIpAddress        : ::1
- ExecutionDuration      : 14582
- Actions:
  - Boss.AuthCenter.Account.AccountExternalAppService.get_AppliedCrossCuttingConcerns (0 ms.)
    {}
  - Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync (398 ms.)
    {"input":{"id":0,"name":"string","surname":"string","userName":"string","emailAddress":"string","phoneNumber":"string","passwordHash":"string","creationTime":"2021-01-06T09:37:48.039Z","userLoginProviders":[{"loginProvider":"string","providerKey":"string"}]}
  - Boss.AuthCenter.Account.AccountController.UserSyncAsync (11801 ms.)
    {"input":{"id":0,"name":"string","surname":"string","userName":"string","emailAddress":"string","phoneNumber":"string","passwordHash":"string","creationTime":"2021-01-06T09:37:48.039Z","userLoginProviders":[{"loginProvider":"string","providerKey":"string"}]}
- Exceptions:
  - Common Language Runtime detected an invalid program.
    System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at Castle.Proxies.Invocations.IAccountExternalAppService_UserSyncAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Boss.AuthCenter.Account.AccountController.UserSyncAsync(UserSyncCommand input) in D:\projects\ami\Boss.AuthCenter\src\Boss.AuthCenter.HttpApi.App\Account\AccountController.cs:line 25
   at lambda_method844(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  - Common Language Runtime detected an invalid program.
    System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Boss.AuthCenter.Account.AccountExternalAppService.UserSyncAsync(UserSyncCommand input)
   at Castle.Proxies.Invocations.IAccountExternalAppService_UserSyncAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Boss.AuthCenter.Account.AccountController.UserSyncAsync(UserSyncCommand input) in D:\projects\ami\Boss.AuthCenter\src\Boss.AuthCenter.HttpApi.App\Account\AccountController.cs:line 25
   at lambda_method844(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by yaoyuansheng** [comment]
ABP Framework version : 4.0.1 ,
Database Provider :EF Core , 
I fixed it now  ，When I modify the code for the application layer


await UnitOfWorkManager.Current?.SaveChangesAsync(); =>await  UnitOfWorkManager?.Current?.SaveChangesAsync();
OR =>await CurrentUnitOfWork.SaveChangesAsync();
