### ISSUE TITLE
Just tired to run DBMigrator and got an error with 4.1 release

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#7068]
* Your **ABP Framework version**. 4.1
* Your **User Interface** MVC
* Your database provider EF Core
* Exception message and **stack trace** 

```
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while activating Acme.Software.SimpleTask.SimpleTaskDataSeederContributor.
  Source=Autofac
  StackTrace:
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.InvokePipeline(ResolveRequest request, DefaultResolveRequestContext requestContext)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.Data.DataSeeder.<SeedAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.<ProceedAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.<InterceptAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Acme.Software.SimpleTask.Data.SimpleTaskDbMigrationService.<SeedDataAsync>d__11.MoveNext() in C:\Amazing\LearnABP\Projects\Acme.Software.SimpleTask\src\Acme.Software.SimpleTask.Domain\Data\SimpleTaskDbMigrationService.cs:line 90
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Acme.Software.SimpleTask.Data.SimpleTaskDbMigrationService.<MigrateAsync>d__9.MoveNext() in C:\Amazing\LearnABP\Projects\Acme.Software.SimpleTask\src\Acme.Software.SimpleTask.Domain\Data\SimpleTaskDbMigrationService.cs:line 41
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Acme.Software.SimpleTask.DbMigrator.DbMigratorHostedService.<StartAsync>d__2.MoveNext() in C:\Amazing\LearnABP\Projects\Acme.Software.SimpleTask\src\Acme.Software.SimpleTask.DbMigrator\DbMigratorHostedService.cs:line 30
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Acme.Software.SimpleTask.DbMigrator.Program.<Main>d__0.MoveNext() in C:\Amazing\LearnABP\Projects\Acme.Software.SimpleTask\src\Acme.Software.SimpleTask.DbMigrator\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Acme.Software.SimpleTask.SimpleTaskDataSeederContributor' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[Acme.Software.SimpleTask.Tasks.Task,System.Guid] taskRepository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[Acme.Software.SimpleTask.Tasks.Task,System.Guid], Volo.Abp.Timing.IClock)'.
```

* Steps needed to **reproduce** the problem.
1. Create new solution using "abp new Acme.Software.SimpleTask -csf"
2. Create SimpleTaskDataSeededContributor with the following code 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Data;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Domain.Repositories;
using Acme.Software.SimpleTask.Tasks;
using Volo.Abp.Timing;

namespace Acme.Software.SimpleTask
{
    public class SimpleTaskDataSeederContributor : IDataSeedContributor, ITransientDependency
    {
        private readonly IRepository<Tasks.Task, Guid> _taskRepository;
        private readonly IClock _clock;

        public SimpleTaskDataSeederContributor(IRepository<Tasks.Task, Guid> taskRepository, IClock clock)
        {
            _taskRepository = taskRepository;
            _clock = clock;
        }

        public async System.Threading.Tasks.Task SeedAsync(DataSeedContext context)
        {
            if (await _taskRepository.GetCountAsync() <= 0)
            {
                await _taskRepository.InsertAsync(
                    new Tasks.Task()
                    {
                        Title = "Buy some milk",
                        Description = "Busy some milk today on the way home",
                        CreationTime = _clock.Now,
                        State = TaskState.Open
                    },
                    autoSave: true
                );

                await _taskRepository.InsertAsync(
                    new Tasks.Task
                    {
                        Title = "Watch StartTrek Discovery",
                        Description = "Watch the latest episode of StarTrek",
                        CreationTime = _clock.Now.AddDays(-2),
                        State = TaskState.Completed
                    },
                    autoSave: true
                );
            }
        }
    }
}
```
3. Run DbMigrator and get the below error 

```
[17:09:27 INF] Started database migrations...
[17:09:27 INF] Migrating schema for host database...
[17:09:29 INF] Executing host database seed...
[17:09:30 WRN] Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the code which triggers this warning, call 'ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'.
[17:09:30 WRN] Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the code which triggers this warning, call 'ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'.
[17:09:31 WRN] Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the code which triggers this warning, call 'ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'.
```

**Comment by maliming** [comment]
Have you add `Tasks.Task` to your DbContext？ `DbSet<Tasks.Task>`

> Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled

https://github.com/abpframework/abp/pull/6912

**Comment by vnetonline** [comment]
Yes I have and run the update-database command ... it has created the table but no data

**Comment by maliming** [comment]
Can you share your project?

**Comment by vnetonline** [comment]
> Can you share your project?

How would you like me to share it ??

**Comment by maliming** [comment]
You can create a Github repo.

**Comment by vnetonline** [comment]
> 
> 
> You can create a Github repo.

here is the link to repo

https://github.com/vnetonline/Acme.Software.SimpleTask

**Comment by vnetonline** [comment]
Sorry my mistake i had 

public DbSet<Task> Tasks { get; set; }

instead of public 

DbSet<Tasks.Task> Tasks { get; set; }
