### ISSUE TITLE
EmailSend Exception

### ISSUE THREAD

**Issue by zfeihong** [abpframework/abp#7097]
```
String api_user = "abp_sendcloud";
String api_key = "efb159ba4b7ad6cf57eda0eaf2d9d968";

String to = "41696811@qq.com";

MailMessage mailMsg = new MailMessage();
mailMsg.To.Add(new MailAddress(to));
mailMsg.From = new MailAddress("392890835@qq.com", "jacky");

mailMsg.Subject = "Smtp C# Smtp Example";
string text = "Welcome SendCloud";
string html = @"Welcome<a href=""http://sendcloud.sohu.com"">SendCloud</a>";
mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(text, null, MediaTypeNames.Text.Plain));
mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(html, null, MediaTypeNames.Text.Html));

SmtpClient smtpClient = new SmtpClient("smtp.sendcloud.net", Convert.ToInt32(25));
System.Net.NetworkCredential credentials = new System.Net.NetworkCredential(api_user, api_key);
smtpClient.Credentials = credentials;
smtpClient.Send(mailMsg);
```

The above methods can be sent successfully，Why Settings fail，As shown below

```
"Settings": {
    "Abp.Mailing.Smtp.Host": "smtp.sendcloud.net",
    "Abp.Mailing.Smtp.Port": "25",
    "Abp.Mailing.Smtp.UserName": "abp_sendcloud",
    "Abp.Mailing.Smtp.Password": "efb159ba4b7ad6cf57eda0eaf2d9d968",  
    "Abp.Mailing.Smtp.Domain": "",
    "Abp.Mailing.Smtp.EnableSsl": "false",
    "Abp.Mailing.Smtp.UseDefaultCredentials": "false",
    "Abp.Mailing.DefaultFromAddress": "392890835@qq.com",
    "Abp.Mailing.DefaultFromDisplayName": "ABP application"
  }
```

**Comment by maliming** [comment]
You should test with [MailKit](https://docs.abp.io/en/abp/latest/MailKit)

**Comment by zfeihong** [comment]
```
  private readonly IMailKitSmtpEmailSender _emailSender;
        public ProductService(IMailKitSmtpEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        public async Task<IEnumerable<ProductDto>> GetListAsync(ProductQueryDto query)
        {
            await _emailSender.SendAsync(
              "41696823@qq.com",     // target email address
              "Email subject",         // subject
              "This is email body..."  // email body
            );
}
```
I use MailKit test Fail as shown below:
```
 An exception was thrown while activating Castle.Proxies.ProductServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.ProductServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.ProductServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.MailKit.IMailKitSmtpEmailSender emailSender' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.MailKit.IMailKitSmtpEmailSender)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(ConstructorInfo[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
```
doc It's not very detailed

**Comment by maliming** [comment]
You can test with plain `SmtpEmailSender ` and `mailkit` then try to integrate abp.

**Comment by zfeihong** [comment]
Still not,The commercial version can't send text messages all the time, nor can I do it according to the documents. I'm going to cry

**Comment by maliming** [comment]
hi See https://github.com/abpframework/abp/issues/7097#issuecomment-758327814

**Comment by rong736** [comment]
you need add Depends
[DependsOn(
        _typeof(Volo.Abp.MailKit.AbpMailKitModule)_
    )]
