### ISSUE TITLE
AbpValidationException thrown for ModelState errors on Razor pages

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#7119]
I have noticed this error when attempting to use the 'reset forgot password' functionality (/Account/ResetPassword) on the basic template created via the ABP CLI. If you type mismatching passwords in the `Password` and `Confirm password` fields, a 500 error is thrown. I would have expected it to throw a 400 error or 'passwords do not match' alert (I would prefer this). According to the ABP docs [here](https://docs.abp.io/en/abp/latest/Exception-Handling#http-status-code-mapping) and [here](https://docs.abp.io/en/abp/latest/Validation#abpvalidationexception) - AbpValidationException should be a 400 error. I can see it _should_ be handled (see [here](https://github.com/abpframework/abp/blob/66cadb34ccd8467317541863b58ca57dd837639d/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/ExceptionHandling/DefaultHttpExceptionStatusCodeFinder.cs#L49-L52) and [here](https://github.com/abpframework/abp/blob/bf066efb36ca7badf13e3ea359d1749267da625d/framework/src/Volo.Abp.ExceptionHandling/Volo/Abp/AspNetCore/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs#L218-L225)).

Also, the exception is not helpful as it doesn't log the validation errors on the exception page, audit logs or log file.
The standard module 'Use' methods are included in my app:
```csharp
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseAbpRequestLocalization();

if (!env.IsDevelopment())
{
    app.UseErrorPage();
}

//...

app.UseAuditing();
app.UseAbpSerilogEnrichers();

//...

// I also tried including these...
//app.UseAbpExceptionHandling();
//context.Services.Configure<Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingOptions>(options =>
//{
//    options.SendExceptionsDetailsToClients = true;
//});
```

**Version**: v4.1.0
**UI**: Angular
**Exception**:
```log
2021-01-10T18:56:09.251+00:00 [ERR][5][Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware] An unhandled exception has occurred while executing the request.
Volo.Abp.Validation.AbpValidationException: ModelState is not valid! See ValidationErrors for details.
   at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)
   at Volo.Abp.AspNetCore.Mvc.UI.RazorPages.AbpPageModel.ValidateModel()
   at Volo.Abp.Account.Web.Pages.Account.ResetPasswordModel.ValidateModel()
   at Volo.Abp.Account.Web.Pages.Account.ResetPasswordModel.OnPostAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by maliming** [comment]
Abp did not handle this exception because it was an exception of the page. It return a **page** instead of an **object**.

We can also add an exception message to **Alerts**, but it cannot cover all situations. For example, the return value of a page action is `NoContent`

**Comment by real-zony** [comment]
So you can implement the IHttpExceptionStatusCodeFinder interface and replace the default implementation.

**Comment by olicooper** [comment]
So throwing a 500 error code is intended behaviour when a user types mismatching passwords in to the forgot password form?
The [exception handling doc](https://docs.abp.io/en/abp/4.0/Exception-Handling#validation-errors) suggests that the `AbpValidationException` should be handled with a 400 error. 

I have overridden the `DefaultHttpExceptionStatusCodeFinder` but the `GetStatusCode` method is never called. The last step in the exception stack is `ModelStateValidator.Validate`. The code breaks at this point and doesn't seem to be handled by any middleware as I would expect.
https://github.com/abpframework/abp/blob/8d43ce0b084d133e8be99d0d6ea4ec9d82b040c5/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Validation/ModelStateValidator.cs#L19-L22

I have also tried putting breakpoints on `AbpExceptionPageFilter` ShouldHandleException/HandleAndWrapException methods but these aren't called either.

Maybe I am misunderstanding something because I am new to razor pages but a 500 error doesn't seem right for a user input issue?

How do I handle this exception and simply display an error message/alert to the user?

Thanks for your help 😄 👍

**Comment by mtozlu** [comment]
ModelStateValidator [throws](https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Validation/ModelStateValidator.cs#L19) `AbpValidationException` when modelstate is not valid. This method is used in Register, ForgotPassword, etc pages. 

Any validation error that gets past client side validation in my register form was producing 500 error too :) 
This is how i solved it;
I handled the exception in Register.cshtml.cs pages' `OnPost` method and turned the validation error messages to an alert box.
```csharp
public virtual async Task<IActionResult> OnPostAsync()
{
	try
	{
		// Register logic ...
	}
	catch (AbpValidationException e)
	{
		Alerts.Danger(string.Join(",", e.ValidationErrors.Select(a => a.ErrorMessage).ToList()));
		return Page();
	}
}
```

**Comment by olicooper** [comment]
Thanks for the snippet @mtozlu - I may have to use this.

Why are we not integrating with Microsoft's [PageModel.TryValidateModel](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razorpages.pagemodel.tryvalidatemodel?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_RazorPages_PageModel_TryValidateModel_System_Object_System_String_)?

Microsoft handle ModelState validation errors [like this](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#rerun-validation) - returning the page to the user with a 200 status code. The model errors are automatically populated when I implement it this way (see image below).
![image](https://user-images.githubusercontent.com/22296715/104958806-9e5a9580-59c8-11eb-86de-ec819b793341.png)

The current ABP implementation means we have to add a try catch block to all pages that use `AbpPageModel.ValidateAsync` and `AbpController.ValidateAsync` to replicate how Microsoft expects us to do it.

**Comment by olicooper** [comment]
I have found a way to generically override the functionality but I'm not happy with this solution.
The idea is to intercept the request after model binding but before the post method is called. I have found that the `Volo.Abp.AspNetCore.Mvc.Validation.AbpValidationActionFilter` is being applied to all requests which makes it difficult to intercept but this works.
```csharp
public class ValidationPageFilter : IAsyncPageFilter
{
    public Task OnPageHandlerExecutionAsync(PageHandlerExecutingContext context, PageHandlerExecutionDelegate next)
    {
        if (context.ModelState.Count == 0
            || context.HandlerMethod.HttpMethod != "Post"
            || !context.ActionDescriptor.HandlerTypeInfo.IsSubclassOf(
                   typeof(Volo.Abp.AspNetCore.Mvc.UI.RazorPages.AbpPageModel)))
        {
            return next.Invoke();
        }

        var pageModel = (Volo.Abp.AspNetCore.Mvc.UI.RazorPages.AbpPageModel)context.HandlerInstance;

        try
        {
            // Invoke 'ValidateModel' private method (so we use the overridden method instead of directly calling IModelStateValidator.Validate)
            MethodInfo validateMethod = pageModel.GetType().GetMethod("ValidateModel", BindingFlags.NonPublic | BindingFlags.Instance);
            if (validateMethod != null) validateMethod.Invoke(pageModel, Array.Empty<object>());

            //context.HttpContext.RequestServices.GetRequiredService<IModelStateValidator>().Validate(context.ModelState);
        }
        catch (TargetInvocationException tie)
        {
            if (!(tie.InnerException is AbpValidationException)) throw tie.InnerException;

            // return page with model errors
            context.Result = pageModel.Page();
            return Task.CompletedTask;
        }
        return next.Invoke();
    }

    public Task OnPageHandlerSelectionAsync(PageHandlerSelectedContext context)
    {
        return Task.CompletedTask;
    }
}
```
Then in your module `ConfigureServcies`
```csharp
context.Services.AddRazorPages().AddMvcOptions(options =>
{
    options.Filters.Add(new ValidationPageFilter());
});
```

@mtozlu this may be useful to you?
@maliming it doesn't return a __page__ result (like it should for `ModelState` errors), the exception is unhandled and displayed to the user with no explanation for the error which is unhelpful to the user (who simply typed in the wrong data).

**Comment by real-zony** [comment]
@olicooper 
Your approach is to ignore the AbpValidationException exception. If there is an object in the Application Service that implements `IValidatableObject` or throws an exception manually, this is not a good way.
@hikalkan  what do you think?

**Comment by mtozlu** [comment]
@olicooper I only need to override this functionality in Register form, so i modified Register.cshtml page. 
I think modifying the behaviour applicationwise would cause unknown side effects. Because all API inputs use it and angular app catches these errors and shows messageboxes, etc.

**Comment by olicooper** [comment]
@GameBelial ModelState errors are caught by the form when the page is returned and displayed to the user so this is more helpful than showing the user a 500 error with no explanation of how to fix the problem and loosing the data that the user typed in too. I think AbpValidationException's are only thrown for ModelState errors? But you are saying that developers could use AbpValidationException in their own code too? I hadn't thought about that! Is there a way to display an Alert message for non-ModelState errors (400 & 404) that align with [the docs](https://docs.abp.io/en/abp/latest/Exception-Handling#http-status-code-mapping)?
I wouldn't consider doing this for anything else besides user input/data validation errors as that would be the equivalent of having an empty catch block. I agree any server errors should be thrown.

@mtozlu Yeah that okay 😃 This override will only effect razor pages (IPageFilter) so it is safe. It hasn't changed how errors behave in my angular application during my testing because errors from controllers are handled by the remote exception handler instead.

**Comment by hikalkan** [comment]
I made a small change (handled the exception and returning the same page). The result is:

![image](https://user-images.githubusercontent.com/1210527/121856383-1c636400-ccfd-11eb-9ad8-c6a2861bb83b.png)

I think this is what you expect? @realLiangshiwei I assigned the PR to you. Can you please check if we should make similar change for other pages of the account module?
