### ISSUE TITLE
Error adding new module to solution using CLI

### ISSUE THREAD

**Issue by clinically-au** [abpframework/abp#7225]
* ABP v4.1.1
* Blazor UI
* EF Core

Adding module to existing solution using command:
`abp add-module Acme.NewModule --new --add-to-solution-file`

Throws the following exception:

[22:51:23 INF] ABP CLI (https://abp.io)
[22:51:23 INF] Version 4.1.1 (Stable)
[22:51:26 INF] Installing module 'Acme.NewModule' to the solution 'Acme'
[22:51:26 INF] Installing 'Acme.NewModule.Application' package to the project 'Acme.Application'...
[22:51:26 INF] Successfully installed.
[22:51:26 INF] Installing 'Acme.NewModule.Application.Contracts' package to the project 'Acme.Application.Contracts'...
[22:51:26 INF] Successfully installed.
[22:51:26 INF] Installing 'Acme.NewModule.Blazor' package to the project 'Acme.Blazor'...
[22:51:26 ERR] The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.Cli.Configuration.ConfigReader.Read(String directory) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Configuration\ConfigReader.cs:line 33
   at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 43
   at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 43
   at Volo.Abp.Cli.ProjectModification.ProjectNugetPackageAdder.RunBundleForBlazorAsync(String projectFile) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs:line 204
   at Volo.Abp.Cli.ProjectModification.ProjectNugetPackageAdder.AddAsync(String projectFile, NugetPackageInfo package, String version, Boolean useDotnetCliToInstall) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs:line 106
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddNugetAndNpmReferences(ModuleWithMastersInfo module, String[] projectFiles, Boolean useDotnetCliToInstall) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 392
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddAsync(String solutionFile, String moduleName, String startupProject, String version, Boolean skipDbMigrations, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 95
   at Volo.Abp.Cli.Commands.AddModuleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\AddModuleCommand.cs:line 59
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

If I immediately run the command again, it gets further, but throws the following exception:

[22:55:11 INF] ABP CLI (https://abp.io)
[22:55:11 INF] Version 4.1.1 (Stable)
[22:55:13 INF] Installing module 'Acme.NewModule' to the solution 'Acme'
[22:55:14 INF] Installing 'Acme.NewModule.Domain' package to the project 'Acme.Domain'...
[22:55:14 INF] Successfully installed.
[22:55:14 INF] Installing 'Acme.NewModule.Domain.Shared' package to the project 'Acme.Domain.Shared'...
[22:55:14 INF] Successfully installed.
[22:55:14 INF] Installing 'Acme.NewModule.EntityFrameworkCore' package to the project 'Acme.EntityFrameworkCore'...
[22:55:14 INF] Successfully installed.
[22:55:14 INF] Installing 'Acme.NewModule.HttpApi' package to the project 'Acme.HttpApi'...
[22:55:14 INF] Successfully installed.
[22:55:14 INF] Installing 'Acme.NewModule.HttpApi.Client' package to the project 'Acme.HttpApi.Client'...
[22:55:14 INF] Successfully installed.
[22:55:14 INF] Creating your project...
[22:55:14 INF] Project name: Acme.NewModule
[22:55:14 INF] Template: module
[22:55:14 INF] Version: 4.1.1
[22:55:14 INF] Create Solution Folder: no
[22:55:14 INF] Output folder: /Users/wojt/Code/Acme/aspnet-core/modules/Acme.NewModule
[22:55:14 INF] Using cached template: module, version: 4.1.1
[22:55:17 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Module
[22:55:18 INF] 'Acme.NewModule' has been successfully created to '/Users/wojt/Code/Acme/aspnet-core/modules/Acme.NewModule'
[22:55:18 ERR] The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Volo.Abp.Cli.Configuration.ConfigReader.Read(String directory) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Configuration\ConfigReader.cs:line 33
   at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 43
   at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 43
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.RunBundleForBlazorAsync(String[] projectFiles, ModuleWithMastersInfo module) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 144
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddAsync(String solutionFile, String moduleName, String startupProject, String version, Boolean skipDbMigrations, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 125
   at Volo.Abp.Cli.Commands.AddModuleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\AddModuleCommand.cs:line 59
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by KennyMuffins** [comment]
Yes, having this same error, references are added, but module not created

**Comment by ilkayilknur** [comment]
Does your Blazor project contain related bundling settings inside `wwwroot/appsettings.json`? @wojtj @KennyMuffins  `appsettings.json` file should contain bundling settings like this https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Blazor/wwwroot/appsettings.json

**Comment by KennyMuffins** [comment]
hi @ilkayilknur , are u referring to the portion inside the AbpCli? i dont believe i have that portion, will try it now, thanks!

**Comment by ilkayilknur** [comment]
Yes @KennyMuffins, Can you add that section and try again, please?

**Comment by KennyMuffins** [comment]
Nope,still having an error, i realize my error is slightly different though

Error occured while downloading source-code from https://abp.io/api/download/template/ : '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[22:57:09 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

Probably there is an issue with the add-module template just like this morning for the new abp project generation

abp add-module ContentManagement --new --add-to-solution-file -sp ..\Acme.BookStore.Web\Acme.BookStore.Web.csproj --output-folder D:\DotNet\abp-samples\BookStore-Modular\modules\content-management

**Comment by ilkayilknur** [comment]
@yekalkan, can you take look at this, please?

**Comment by clinically-au** [comment]
> Does your Blazor project contain related bundling settings inside `wwwroot/appsettings.json`? 
Thanks, it did not have that section (I think I initially created the project with the 4.0 ABP Suite)

It now gets further, but still throws up (different) errors. During the first build for Acme.Blazor here:
[06:45:41 INF] ABP CLI (https://abp.io)
[06:45:41 INF] Version 4.1.1 (Stable)
[06:45:43 INF] Installing module 'Acme.NewModule' to the solution 'Acme'
[06:45:44 INF] Installing 'Acme.NewModule.Application' package to the project 'Acme.Application'...
[06:45:44 INF] Successfully installed.
[06:45:44 INF] Installing 'Acme.NewModule.Application.Contracts' package to the project 'Acme.Application.Contracts'...
[06:45:44 INF] Successfully installed.
[06:45:44 INF] Installing 'Acme.NewModule.Blazor' package to the project 'Acme.Blazor'...
Building....:  (1/1)/Users/wojt/Code/Acme/aspnet-core/src/Acme.Blazor/Acme.Blazor.csproj
Executing...: dotnet build /Users/wojt/Code/Acme/aspnet-core/src/Acme.Blazor/Acme.Blazor.csproj '

It fails to restore the new module projects as it can't find them:
error NU1101: Unable to find package Acme.NewModule.Application.Contracts. No packages exist with this id in source(s): ABP Commercial NuGet Source, BlazoriseMyGet, nuget.org

[one error for each package]

Build failed for :/Users/wojt/Code/Acme/aspnet-core/src/Acme.Blazor/Acme.Blazor.csproj
System.Exception: Build failed!
   at Volo.Abp.Cli.Build.DefaultDotNetProjectBuilder.BuildInternal(DotNetProjectInfo project, String arguments, ConcurrentBag`1 builtProjects) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Build\DefaultDotNetProjectBuilder.cs:line 85
   at Volo.Abp.Cli.Build.DefaultDotNetProjectBuilder.BuildProjects(List`1 projects, String arguments) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Build\DefaultDotNetProjectBuilder.cs:line 34

The second build works fine:

[06:45:57 WRN] Unable to minify the file: blazorise.js. Adding file to the bundle without minification.
[06:45:57 WRN] Unable to minify the file: AuthenticationService.js. Adding file to the bundle without minification.
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Installing 'Acme.NewModule.Domain' package to the project 'Acme.Domain'...
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Installing 'Acme.NewModule.Domain.Shared' package to the project 'Acme.Domain.Shared'...
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Installing 'Acme.NewModule.EntityFrameworkCore' package to the project 'Acme.EntityFrameworkCore'...
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Installing 'Acme.NewModule.HttpApi' package to the project 'Acme.HttpApi'...
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Installing 'Acme.NewModule.HttpApi.Client' package to the project 'Acme.HttpApi.Client'...
[06:45:57 INF] Successfully installed.
[06:45:57 INF] Creating your project...
[06:45:57 INF] Project name: Acme.NewModule
[06:45:57 INF] Template: module
[06:45:57 INF] Version: 4.1.1
[06:45:57 INF] Create Solution Folder: no
[06:45:57 INF] Output folder: /Users/wojt/Code/Acme/aspnet-core/modules/Acme.NewModule
[06:45:58 INF] Using cached template: module, version: 4.1.1
[06:46:01 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Module
[06:46:03 INF] 'Acme.NewModule' has been successfully created to '/Users/wojt/Code/Acme/aspnet-core/modules/Acme.NewModule'
Building....:  (1/1)/Users/wojt/Code/Acme/aspnet-core/src/Acme.Blazor/Acme.Blazor.csproj
 [all good]

But an error is then reported: 

[06:46:25 ERR] Could not load file or assembly '�������\r
                                                         �����, Version=6718.6765.6774.6806, Culture=�������\r
                                                                                                              �����, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

System.BadImageFormatException: Could not load file or assembly '�������\r
                                                                          �����, Version=6718.6765.6774.6806, Culture=�������\r
                                                                                                                               �����, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: '�������\r
                     �����, Version=6718.6765.6774.6806, Culture=�������\r
                                                                          �����, PublicKeyToken=null' ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Volo.Abp.Cli.Bundling.BundlingService.GetStartupModule(String assemblyPath) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 272
   at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 64
   at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 43
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.RunBundleForBlazorAsync(String[] projectFiles, ModuleWithMastersInfo module) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 144
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddAsync(String solutionFile, String moduleName, String startupProject, String version, Boolean skipDbMigrations, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 125
   at Volo.Abp.Cli.Commands.AddModuleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\AddModuleCommand.cs:line 59
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by yekalkan** [comment]
Hi @wojtj

I couldn't reproduce this issue. 

When i run `abp add-module Acme.NewModule --new --add-to-solution-file` for first time, it throws exception. I'll check it.
But then i run it again and it works fine.

**Comment by xyfy** [comment]
#7130 I report another bug result of it
