### ISSUE TITLE
BUG: Exception while using CLI to create a new project with --database-management-system Postgres Abp 4.2.0-rc.1 

### ISSUE THREAD

**Issue by MAlshehri** [abpframework/abp#7270]
I get this exception while trying to create a new project

command: `abp new TestApp-t app -u angular -dbms PostgreSQL -v 4.2.0-rc.1`

    Deleting migrations...
    [17:44:20 ERR] Could not find a part of the path 'C:\Dev\aspnet- 
    core\src\TestApp.EntityFrameworkCore.DbMigrations\Migrations'.
    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Dev\aspnet- 
    core\src\TestApp.EntityFrameworkCore.DbMigrations\Migrations'.
    at System.IO.FileSystem.GetFindData(String fullPath, WIN32_FIND_DATA& findData)
    at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
    at System.IO.Directory.Delete(String path, Boolean recursive)
    at Volo.Abp.Cli.ProjectModification.EfCoreMigrationManager.RemoveAllMigrations(String solutionFolder) in 
    D:\ci\Jenkins\workspace\abp-framework- 
    release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\EfCoreMigrationManager.cs:line 44
    at Volo.Abp.Cli.Commands.NewCommand.DeleteMigrationsIfNeeded(DatabaseProvider databaseProvider, 
    DatabaseManagementSystem databaseManagementSystem, String outputFolder) in D:\ci\Jenkins\workspace\abp-framework- 
    release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 273
    at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in
    D:\ci\Jenkins\workspace\abp-framework- 
    release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 229
    at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework- 
    release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by hikalkan** [comment]
Thanks for reporting this. Resolved by #7277
We will publish 4.2.0-rc.2 on Monday or Tuesday.
