### ISSUE TITLE
Which service to use to list available tenants on Angular page.

### ISSUE THREAD

**Issue by andre-artus** [abpframework/abp#7348]
I wish to list all the tenants on my [Angular] home page when logged in on the HOST tenant.
Which service do I use to return the list of tenants? I tried `MultiTenancyService`, but it seems not to be the correct one.

**Comment by davidzwa** [comment]
You need to choose:
- use the @abp/ng.tenant-management package with the permission for listing tenants (module import is not *required* to make use of the service):
> `AbpTenantManagement`, `AbpTenantManagement.Tenants`
- implement a controller/service or proxy service which lets you filter for the right tenants (by f.e. adding nice metadata properties with ExtraProperties) so your users get the right set of tenants for them. This way you can query the API with a special permission structure as you like (as the tenancy service(s) by ABP have their policy fixed, see the link below why)

https://github.com/abpframework/abp/blob/badad8d59f02bb0ccba433b49a7fc24ee7bf3b5a/modules/tenant-management/src/Volo.Abp.TenantManagement.Application/Volo/Abp/TenantManagement/TenantAppService.cs#L11

Of course, know that you need a separate user entity per tenant, but you might know that already.

**Comment by andre-artus** [comment]
@davidzwa , thank you. I'll give this a try. 

Is  @abp/ng.tenant-management a package that needs to be installed (i.e. not part of default template)?

I'll likely ultimately go for option 2, but I'll try 1 out first.

**Comment by davidzwa** [comment]
Yes the package is a separate yarn/npm install. Option 1 would give your users lookup access to all tenants, no questions asked. Might be risky or chaotic depending on your situation if you're making the permission default granted.

**Comment by andre-artus** [comment]
@davidzwa ,

Thanks, I ran `yarn add @abp/ng.tenant-management` and it seems to have installed fine. 

When I go to import `AbpTenantManagement` to my home.component.ts it automatically adds it to `from '@abp/ng.core';` but then indicates that it cannot be found, what am I missing?

**Comment by andre-artus** [comment]
Having installed the package mentioned above  I now get errors when it tries to recompile:

```
[WDS] App updated. Recompiling...
 (webpack)-dev-server/client
[WDS] App updated. Recompiling...
 (webpack)-dev-server/client
[WDS] Errors while compiling. Reload prevented.
 (webpack)-dev-server/client
./node_modules/@abp/ng.identity/__ivy_ngcc__/fesm2015/abp-ng.identity.js
Module build failed: Error: ENOENT: no such file or directory, open '[project path]\angular\node_modules\@abp\ng.identity\__ivy_ngcc__\fesm2015\abp-ng.identity.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Storage.provideSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Object.read ([project path]\angular\node_modules\@ngtools\webpack\src\webpack-input-host.js:25:42)
    at [project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:24:45
    at Observable._subscribe ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:14:25)
    at Observable._trySubscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:25:20)
    at SyncDelegateHost.read ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:48:21)
    at WebpackCompilerHost.readFileBuffer ([project path]\angular\node_modules\@ngtools\webpack\src\compiler_host.js:166:44)
    at VirtualFileSystemDecorator.readFile ([project path]\angular\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:44:54)
    at processResource ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
 (webpack)-dev-server/client
./node_modules/@abp/ng.setting-management/__ivy_ngcc__/fesm2015/abp-ng.setting-management.js
Module build failed: Error: ENOENT: no such file or directory, open '[project path]\angular\node_modules\@abp\ng.setting-management\__ivy_ngcc__\fesm2015\abp-ng.setting-management.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Storage.provideSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Object.read ([project path]\angular\node_modules\@ngtools\webpack\src\webpack-input-host.js:25:42)
    at [project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:24:45
    at Observable._subscribe ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:14:25)
    at Observable._trySubscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:25:20)
    at SyncDelegateHost.read ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:48:21)
    at WebpackCompilerHost.readFileBuffer ([project path]\angular\node_modules\@ngtools\webpack\src\compiler_host.js:166:44)
    at VirtualFileSystemDecorator.readFile ([project path]\angular\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:44:54)
    at processResource ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
 (webpack)-dev-server/client
./node_modules/@abp/ng.tenant-management/__ivy_ngcc__/fesm2015/abp-ng.tenant-management.js
Module build failed: Error: ENOENT: no such file or directory, open '[project path]\angular\node_modules\@abp\ng.tenant-management\__ivy_ngcc__\fesm2015\abp-ng.tenant-management.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Storage.provideSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync ([project path]\angular\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Object.read ([project path]\angular\node_modules\@ngtools\webpack\src\webpack-input-host.js:25:42)
    at [project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:24:45
    at Observable._subscribe ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\create.js:14:25)
    at Observable._trySubscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe ([project path]\angular\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:25:20)
    at SyncDelegateHost.read ([project path]\angular\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:48:21)
    at WebpackCompilerHost.readFileBuffer ([project path]\angular\node_modules\@ngtools\webpack\src\compiler_host.js:166:44)
    at VirtualFileSystemDecorator.readFile ([project path]\angular\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:44:54)
    at processResource ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders ([project path]\angular\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
 (webpack)-dev-server/client

```

**Comment by andre-artus** [comment]
The compilation issue seems to have disappeared after I shut the running instance down and restarted it.

**Comment by davidzwa** [comment]
Hmm lot's of things could be inconsistent here. The following is not meant to be patronizing, just bear with me 👍🏼 The next tips are of course assuming you'd follow option 1

- Always restart ng serve (or alternatives) after installing a new package - I'll assume you did
- Dont import (?) AbpTenantManagement (?) in a component, but make sure to inject TenantService (`private tenantService: TenantService`). No modules need to be imported for this to work.
- Make sure the import folder is the tenant management package. There is no service/proxy availabe in ng-core for **listing** tenants, only for getting a tenant by name/id specifically (which you dont want).
- Use the startup templates by Abp to have a good basis.

Let me know if you run into troubles.

**Comment by andre-artus** [comment]
> Hmm lot's of things could be inconsistent here. The following is not meant to be patronizing, just bear with me 👍🏼 The next tips are of course assuming you'd follow option 1

Please, @davidzwa, be as patronizing as you need to be. I'm new to ABP, so everything about it is a mystery to me.

> 
>     * Always restart ng serve (or alternatives) after installing a new package - I'll assume you did
I actually did not, initially.

Your information helped me get what I need, thank you very much.

**Comment by davidzwa** [comment]
Explaining this helps me understand the layers. Thanks to you as well! Learned a lot.
