### ISSUE TITLE
Arabic character with Facebook login

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#7364]
### GitHub Issues

I use IdentityServer with ABP to manage the authentication, I also use the facebook login for fast auth.
I have a user, he has an Arabic user name, but ABP throw an exception because of this.
Here is the call stack:

An unhandled exception has occurred while executing the request.
Volo.Abp.UserFriendlyException: Operation failed: [InvalidUserName] User name 'شان_محمد_123015' is invalid, can only contain letters or digits.
   at Volo.Abp.Account.Web.Pages.Account.AccountPageModel.CheckIdentityErrors(IdentityResult identityResult)
   at SmartPixel.SoCloze.IdentityServer.Web.Pages.Account.LoginModel.SignInExternalUserAsync(ClaimsPrincipal externalUser, String loginProvider, String externalUserId, String displayName, String emailAddress)

So, do you know how I can handle such case? Facebook gives me the user name, I don't!

**Comment by maliming** [comment]
```
Configure<IdentityOptions>(options =>
{
    options.User.AllowedUserNameCharacters = null;
});
```
