### ISSUE TITLE
Can't get datetime from the reader!

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#7365]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Version: **4.1.0**
* UI: Angular.
* database provider **EF Core**
* Exception ：
```
ModelState is not valid! See ValidationErrors for details.
Volo.Abp.Validation.AbpValidationException: ModelState is not valid! See ValidationErrors for details.
   at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)
   at Volo.Abp.AspNetCore.Mvc.Validation.AbpValidationActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-01-21 09:12:59.662 +08:00 [WRN] There are 1 validation errors:
Can't get datetime from the reader! ($.start)
```
 * Json Params
 ```
 {
   "start": "2021-01-13 10:30:02",
    "end": "2021-01-20 10:30:02"
}
```
why! ***This problem occurred after upgrade 4.1.0.***

**Comment by maliming** [comment]
You can try this in net 5 without abp first.

**Comment by SmallShrimp** [comment]
Yes, the same question! Include a string value, and if I pass an int it will also get an error! Is there a solution? There are too many APIs involved

**Comment by SmallShrimp** [comment]
I find a solution, 
 Install-Package `Microsoft.AspNetCore.Mvc.NewtonsoftJson` 
`services.AddControllers() .AddNewtonsoftJson();`
but how to do in abp

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/4.0/Migration-Guides/Abp-4_0#moved-to-system-text-json
