### ISSUE TITLE
"''0xC2' is an invalid start of a property'" error for  non-breaking space(194 160) character in json (using System.Text.Json)

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#7492]
* **ABP Framework version** 4.1.2.
* Database provider(EF Core)
* Exception message and **stack trace** if available (check the logs).
```
{
  "code": null,
  "message": "Your request is not valid!",
  "details": "The following errors were detected during validation.\r\n - \u00270xC2\u0027 is an invalid start of a property name. Expected a \u0027\u0022\u0027. Path: $ | LineNumber: 1 | BytePositionInLine: 0.\r\n",
  "data": {},
  "validationErrors": [
    {
      "message": "\u00270xC2\u0027 is an invalid start of a property name. Expected a \u0027\u0022\u0027. Path: $ | LineNumber: 1 | BytePositionInLine: 0.",
      "members": [
        "$"
      ]
    }
  ]
}

2021-01-27 23:24:58.258 +03:00 [WRN] ModelState is not valid! See ValidationErrors for details.
Volo.Abp.Validation.AbpValidationException: ModelState is not valid! See ValidationErrors for details.
   at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)
   at Volo.Abp.AspNetCore.Mvc.Validation.AbpValidationActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-01-27 23:24:58.260 +03:00 [WRN] There are 1 validation errors:
'0xC2' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 1 | BytePositionInLine: 0. ($)

```
I started to get above error after upgrading from 3.3.2 to 4.1.2 in the request which we earlier copied example value(schema) from swagger.If I try web api with new swagger example values doesn't cause this problem but the request which I copied from previous swagger cause this error. We realized old swagger was padding left side with non-breaking spaces this is the root cause of the problem.

(I try web api in postman)

if I switch back to Newtonsoft.Json then it worked:
```
PreConfigure<AbpJsonOptions>(options =>
{
    options.UseHybridSerializer = false;
});
```

**Comment by maliming** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding
```cs
Configure<AbpSystemTextJsonSerializerOptions>(options =>
{
      options.JsonSerializerOptions.
});
```
