### ISSUE TITLE
HttpPost  RemoteService  Appear  Volo.Abp.Http.Client.AbpRemoteCallException: Unsupported Media Type

### ISSUE THREAD

**Issue by foxeveral** [abpframework/abp#7513]
- Unsupported Media Type
    Volo.Abp.Http.Client.AbpRemoteCallException: Unsupported Media Type
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)

This is abnormal information, how can I solve it

————————————————————————————————————————————————————————

This is the information defined in the RemoteService api-definition

 "SendByRequest": {
              "uniqueName": "SendByRequest",
              "name": "Send",
              "httpMethod": "POST",
              "url": "api/app/send",
              "supportedVersions": [],
              "parametersOnMethod": [
                {
                  "name": "request",
                  "typeAsString": "Application.Contracts.SendRequest, Application.Contracts",
                  "type": "Application.Contracts.PdTask.SendRequest",
                  "typeSimple": "Application.Contracts.SendRequest",
                  "isOptional": false,
                  "defaultValue": null
                }
              ],
              "parameters": [
                {
                  "nameOnMethod": "request",
                  "name": "request",
                  "type": "Application.Contracts.SendRequest",
                  "typeSimple": "Application.Contracts.SendRequest",
                  "isOptional": false,
                  "defaultValue": null,
                  "constraintTypes": null,
                  "bindingSourceId": "Body",
                  "descriptorName": ""
                }
              ],
              "returnValue": {
                "type": "Domain.Shared.ApiResult<Application.Contracts.SendResult>",
                "typeSimple": "Domain.Shared.ApiResult<Application.Contracts.SendResult>"
              }
            }
          }

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Steps needed to **reproduce** the problem.

**Comment by foxeveral** [comment]
ABP Framework version ： 4.1.2
User Interface ： Vue
database provider ： EF Core

**Comment by davidzwa** [comment]
Reproduction? What are you putting in the request body for example? How are your requesting it? (Postman, browser, service proxy, console...)

Unsupported Media Type means that you are supplying something like Form data to a JSON endpoint, or something similar. Please check your request Content-Type header and provide us that information. 

Similar example
https://stackoverflow.com/a/64629641/2733437
