### ISSUE TITLE
Open start mvc template in some Social Apps like QQ, after login occrued 400 error

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#7517]
Abp version: v4.1.2, v4.2.0
User Interface: MVC
Database provider: EF Core

* Exception message and **stack trace** if available (check the logs).
[logs.txt](https://github.com/abpframework/abp/files/5892008/logs.txt)

2021-01-29 11:20:23.395 +08:00 [ERR] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {5068c692-046f-43a5-9edf-471be8e68e94} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

* Steps needed to **reproduce** the problem.
1. abp new DyCompanyName.DyProjectName
2. deploy to IIS (you can try to test via https://dychar.com)
3. Should open link in QQ chat box, then occurred 400 error. I have tested in WeChat and Alipay, Both are OK, only QQ occurred error.

By the way, I have tested to login [abp.io](abp.io) official website via clicking the link in QQ chat box, it occurred the same error.
![image](https://user-images.githubusercontent.com/6952917/106241642-585fc600-6241-11eb-9b1f-89f1d8a8cae4.png)

Another issue:
![image](https://user-images.githubusercontent.com/6952917/106241711-75949480-6241-11eb-8365-b1310d99de5c.png)

**Comment by maliming** [comment]
This is related to **Social Apps** instead of abp. 
You can try to use plain asp net core and **Antiforgery** feature.

**Comment by gerryge** [comment]
@maliming 

I have reread the [CSRF-Anti-Forgery](https://docs.abp.io/en/abp/4.2/CSRF-Anti-Forgery) doc, I found below:

>All your clients, including non-browser clients, should care about obtaining and sending the antiforgery token in every request. In fact, non-browser clients has no CSRF risk and should not care about this.

As QQ is a non-browser clients, why this error happen and how to fix this issue, can you give some advice?
WeChat, Alipay are both OK.

Have you checked the other logs, there are some other useful information:

2021-01-29 11:20:51.989 +08:00 [INF] Request starting HTTP/2 POST https://dychar.com/Account/Login application/x-www-form-urlencoded 0
2021-01-29 11:20:51.996 +08:00 [INF] No CORS policy found for the specified request.
2021-01-29 11:20:51.998 +08:00 [INF] Executing endpoint '/Account/Login'
2021-01-29 11:20:51.998 +08:00 [INF] Route matched with {page = "/Account/Login", area = "", action = "", controller = ""}. Executing page /Account/Login
2021-01-29 11:20:51.998 +08:00 [INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2021-01-29 11:20:51.999 +08:00 [INF] Antiforgery token validation failed. The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
2021-01-29 11:20:52.000 +08:00 [INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
2021-01-29 11:20:52.003 +08:00 [INF] Executing HttpStatusCodeResult, setting HTTP status code 400
2021-01-29 11:20:52.003 +08:00 [INF] Executed page /Account/Login in 5.4286ms
2021-01-29 11:20:52.003 +08:00 [INF] Executed endpoint '/Account/Login'

**Comment by maliming** [comment]
> WeChat, Alipay are both OK.

You can try to use plain asp net core and Antiforgery feature.
