### ISSUE TITLE
Volo.Abp.Minify Problem

### ISSUE THREAD

**Issue by wgodfrey-pernix** [abpframework/abp#7667]
###Issue

 **ABP Framework version:** 4.2.0
**User Interface:** MVC 
**Stack trace:** 
```
2021-02-09 05:32:33.270 +00:00 [ERR] An unhandled exception has occurred while executing the request.
Volo.Abp.Minify.NUglify.NUglifyException: There are some errors on uglifying the given source code! Original file: /Pages/Components/FooterChatWidget/Default.js
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(21,42-43): run-time error JS1004: Expected ';': )
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(21,42-43): run-time error JS1195: Expected expression: )
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(21,42-43): run-time error JS1004: Expected ';': )
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(66,37-38): run-time error JS1004: Expected ';': )
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(66,37-38): run-time error JS1195: Expected expression: )
__bundles/48D2B289FDB65A0650A1ECFFE4A0D982.078D5BCCF4B3D04876FF14CFA47A375D.js(66,37-38): run-time error JS1004: Expected ';': )
   at Volo.Abp.Minify.NUglify.NUglifyMinifierBase.CheckErrors(UglifyResult result, String originalFileName)
   at Volo.Abp.Minify.NUglify.NUglifyMinifierBase.Minify(String source, String fileName, String originalFileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetAndMinifyFileContent(IBundlerContext context, String fileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetFileContentConsideringMinification(IBundlerContext context, String fileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.Bundle(IBundlerContext context)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.<>c__DisplayClass17_0.<GetBundleFilesAsync>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.<>c__DisplayClass6_0`2.<GetOrAdd>b__0(TKey k)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleCache.GetOrAdd(String bundleName, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetBundleFilesAsync(BundleConfigurationCollection bundles, String bundleName, IBundler bundler)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetScriptBundleFilesAsync(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperScriptService.GetBundleFilesAsync(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Volo_Abp_AspNetCore_Mvc_UI_Widgets_Components_WidgetScripts_Default.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at Volo.Abp.AspNetCore.Mvc.UI.Widgets.AbpViewComponentHelper.InvokeAsync(Type componentType, Object arguments)
   at AspNetCore.Themes_Lepton_Layouts_Application_Default.<>c__DisplayClass28_0.<<ExecuteAsync>b__1>d.MoveNext()
```

**reproduce:** 
Hi ABP,

I recently Upgraded to 4.2 and when I finished upgrading, my app built and functioned as expected on my local machine. However, when I deployed the app, I was unable to access the website. This was due to the exception above. After a lot of digging, I discovered the issue corresponded to a javascript file of a Volo.Abp.AspNetCore.Mvc.UI.Widgets.

Specifically, the exception thrown referred to the lines which contain javascript for-of loops.
e.g 
```
for (contact of this.contacts) {
        total += contact.conversation.missedCounter;
}
```
The issue was fixed by returning to a tried and test for loop
e.g.
 ```
for (i = 0; i < this.contacts.length; i++) {
       total += this.contacts[i].conversation.missedCounter;            
}
```
This issue only occurred on the Azure instance.
The only real difference I could find between my computer and Azure was that my computer was using the HTTP/2.0 protocol
and the Azure instance HTTP/1.1

Hopefully this helps find the issue :)

**Comment by maliming** [comment]
This problem also occurs when you change the environment to **production** locally.

https://github.com/trullock/NUglify may not support some js syntax.

You can try to use the higher version of the package. We will upgrade it.

```cs
<PackageReference Include="NUglify" Version="1.13.2" />
```
