### ISSUE TITLE
Request error after authorization with Swagger API

### ISSUE THREAD

**Issue by yerz** [abpframework/abp#7670]
My environment:

- abp3.0 upgrade to abp 4.2
- No UI
- Tiered IdentityServer
- Independent deployment  IdentityServer

---

I have a problem, **production environment** 

**IdentityServer** will cause the following error

**[16:05:02 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration**

After the **swagger API** is authorized , request API  The following error occurred

**[16:05:02 ERR] Connection id "0HM6CQ4CP451T", Request id "0HM6CQ4CP451T:00000002": An unhandled exception was thrown by the application.**

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.

   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)

   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)

   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

---

I don't know what the reason is.  but I need to solve this problem;

thanks

**Comment by yerz** [comment]
I have found the problem. It is the configuration of the Nginx reverse proxy. I am trying to fix the problem

thanks :)

**Comment by git102347501** [comment]
@yerz Excuse me, how is this problem solved?

**Comment by ugurozturk** [comment]
@yerz Having the same error, how did you solve this
