### ISSUE TITLE
Rabbitmq and Backgroundjobs in a other microservice

### ISSUE THREAD

**Issue by rafaelgfirmino** [abpframework/abp#7713]
I have a doubt about rabbitmq

I have a application  where I need to process an event in Knime (Etl Platform) and this process can be costly and take a long time to execute. So I can cancel this event at any time. 

I m using the RabbitMq for dispatch an event for start the process an other for kill process in same queue for both. Because I create an EventBus using the ABP documentation and not so clear for me.
I using a Microservice for dispatch an event (start the process and kill the process) and other Microservices pro listen to this event using handles.

I tried using background jobs but it's not worked. I Follow tutorial in the documentation 

Add a rabbitmqModule 
```cs
[DependsOn(typeof(AbpBackgroundJobsRabbitMqModule))]
```
```cs
Configure<AbpRabbitMqBackgroundJobOptions>(options =>
{
    options.DefaultQueueNamePrefix = "my_app_jobs.";
    options.JobQueues[typeof(EmailSendingArgs)] =
        new JobQueueConfiguration(
            typeof(EmailSendingArgs),
            queueName: "my_app_jobs.emails",
            connectionName: "SecondConnection"
        );
});
```
```cs
private readonly IBackgroundJobManager _backgroundJobManager;

    public RegistrationService(IBackgroundJobManager backgroundJobManager)
    {
        _backgroundJobManager = backgroundJobManager;
    }

    public async Task RegisterAsync(string userName, string emailAddress, string password)
    {
        //TODO: Create new user in the database...

        await _backgroundJobManager.EnqueueAsync(
            new EmailSendingArgs
            {
                EmailAddress = emailAddress,
                Subject = "You've successfully registered!",
                Body = "..."
            }
        );
    }
```

I' not create a background job here because this background job live in a nother microservice

I put this configuration in my module 
```cs
 Configure<AbpBackgroundJobOptions>(options =>
        {
            options.IsJobExecutionEnabled = false; //Disables job execution
        });

Configure<AbpRabbitMqBackgroundJobOptions>(options =>
{
    options.DefaultQueueNamePrefix = "my_app_jobs.";
    options.JobQueues[typeof(EmailSendingArgs)] =
        new JobQueueConfiguration(
            typeof(EmailSendingArgs),
            queueName: "my_app_jobs.emails",
            connectionName: "SecondConnection"
        );
});
```

But if I do not create a Job in my dispatch microservice this error occurred
```log
[02:10:37 ERR] Caught an exception while publishing the event 'Volo.Abp.Domain.Entities.Events.EntityCreatedEventData`1[[Example.Queue.Etl.Jobs.Job, Example.Queue.Etl.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the entity '[ENTITY: Job] Id = 572c6fc7-f78e-96b2-f8c4-39fab11f609d'
[02:10:37 ERR] Undefined background job for the job args type: Example.Queue.Etl.Jobs.EmailSendingArgs, Example.Queue.Etl.Domain.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Volo.Abp.AbpException: Undefined background job for the job args type: Example.Queue.Etl.Jobs.EmailSendingArgs, Example.Queue.Etl.Domain.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobOptions.GetJob(Type argsType)
   at Volo.Abp.BackgroundJobs.RabbitMQ.JobQueueManager.GetAsync[TArgs]()
   at Volo.Abp.BackgroundJobs.RabbitMQ.RabbitMqBackgroundJobManager.EnqueueAsync[TArgs](TArgs args, BackgroundJobPriority priority, Nullable`1 delay)
   at Example.Queue.Etl.Jobs.Events.NewJobLocalHandler.HandleEventAsync(EntityCreatedEventData`1 eventData) in /home/rafa/Example/Queue/modules/etl/src/Example.Queue.Etl.Domain/Jobs/Events/NewJobLocalHandler.cs:line 40
   at Volo.Abp.EventBus.EventBusBase.TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType, Object eventData, List`1 exceptions)
   at System.AbpExceptionExtensions.ReThrow(Exception exception)
   at Volo.Abp.EventBus.Local.LocalEventBus.PublishAsync(Type eventType, Object eventData)
   at Volo.Abp.Domain.Entities.Events.EntityChangeEventHelper.<>c__DisplayClass34_0.<<TriggerEventWithEntity>b__0>d.MoveNext()
[02:10:37 INF] Executing ObjectResult, writing value of type 'Example.Queue.Etl.Jobs.JobDto'.
[02:10:37 INF] Executed action Example.Queue.Etl.Jobs.JobsAppService.CreateAsync (Example.Queue.Etl.Application) in 6919.34ms
[02:10:37 INF] Executed endpoint 'Example.Queue.Etl.Jobs.JobsAppService.CreateAsync (Example.Queue.Etl.Application)'
[02:10:37 INF] Request finished HTTP/1.1 POST http://localhost:44300/api/etlRunner/jobs application/json 53 - 200 - application/json;+charset=utf-8 7229.1134ms

```

**Comment by real-zony** [comment]
@rafaelgfirmino Hi, Can you provide a demo project?

**Comment by rafaelgfirmino** [comment]
@GameBelial I can contour this problem.

I needed multiple queues in the same microservices, but ABP did not implement this functionality #5231. 

So, I subscribe AbpRabbitMqModule 

1º - I create a Module identical the Volo.Abp.EventBus.RabbitMq

2º I create a new Interface IEventRabbitMqProvider

```cs
//IEventRabbitMqProvider.cs
 public interface IEventRabbitMqProvider
    {
        string GetName(Type eventType);
        string GetQueue(Type eventType);
    }
```
3º I Create A new Attribute class RabbitMqEventAttribute

```cs
using System;
using System.Linq;
using JetBrains.Annotations;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using Volo.Abp;
using Volo.Abp.EventBus;

namespace Example.Core.RabbitMQ
{
    [AttributeUsage(AttributeTargets.Class)]

    public class RabbitMqEventAttribute : Attribute, IEventRabbitMqProvider
    {
        public virtual string Queue { get; set; }
        public virtual string Name { get; }

        public RabbitMqEventAttribute([CanBeNull]string name)
        {
            Name = Check.NotNullOrWhiteSpace(name, nameof(name));
        }
        
        public static string GetQueueOrDefault([NotNull] Type eventType)
        {
            Check.NotNull(eventType, nameof(eventType));

            return eventType
                .GetCustomAttributes(true)
                .OfType<IEventRabbitMqProvider>()
                .FirstOrDefault()
                ?.GetQueue(eventType);
        }

        public static string GetNameOrDefault<TEvent>()
        {
            return GetNameOrDefault(typeof(TEvent));
        }

        public static string GetNameOrDefault([NotNull] Type eventType)
        {
            Check.NotNull(eventType, nameof(eventType));

            return eventType
                       .GetCustomAttributes(true)
                       .OfType<IEventRabbitMqProvider>()
                       .FirstOrDefault()
                       ?.GetName(eventType)
                   ?? eventType.FullName;
        }

        public string GetName(Type eventType)
        {
            return Name;
            
        }

        public string GetQueue(Type eventType)
        {
            return Queue;
        }
    }
}
```

5º I Change the RabbitMqDistributedEventBus
```cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using Volo.Abp;
using Volo.Abp.DependencyInjection;
using Volo.Abp.EventBus;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.EventBus.RabbitMq;
using Volo.Abp.MultiTenancy;
using Volo.Abp.RabbitMQ;
using Volo.Abp.Threading;

namespace Example.Dhp.Core.RabbitMQ
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IDistributedEventBus), typeof(RabbitMqDistributedEventBus))]
    public class RabbitMqDistributedEventBus : EventBusBase, IDistributedEventBus, ISingletonDependency
    {
        protected AbpRabbitMqEventBusOptions AbpRabbitMqEventBusOptions { get; }
        protected AbpDistributedEventBusOptions AbpDistributedEventBusOptions { get; }
        protected IConnectionPool ConnectionPool { get; }
        protected IRabbitMqSerializer Serializer { get; }

        //TODO: Accessing to the List<IEventHandlerFactory> may not be thread-safe!
        protected ConcurrentDictionary<Type, List<IEventHandlerFactory>> HandlerFactories { get; }
        protected ConcurrentDictionary<string, Type> EventTypes { get; }
        protected IRabbitMqMessageConsumerFactory MessageConsumerFactory { get; }
        protected Dictionary<string,IRabbitMqMessageConsumer> Consumer { get; private set; }
        protected ExchangeDeclareConfiguration DefaultExchangeDeclareConfiguration;
        public RabbitMqDistributedEventBus(
            IOptions<AbpRabbitMqEventBusOptions> options,
            IConnectionPool connectionPool,
            IRabbitMqSerializer serializer,
            IServiceScopeFactory serviceScopeFactory,
            IOptions<AbpDistributedEventBusOptions> distributedEventBusOptions,
            IRabbitMqMessageConsumerFactory messageConsumerFactory,
            ICurrentTenant currentTenant)
            : base(serviceScopeFactory, currentTenant)
        {
            ConnectionPool = connectionPool;
            Serializer = serializer;
            MessageConsumerFactory = messageConsumerFactory;
            AbpDistributedEventBusOptions = distributedEventBusOptions.Value;
            AbpRabbitMqEventBusOptions = options.Value;

            HandlerFactories = new ConcurrentDictionary<Type, List<IEventHandlerFactory>>();
            EventTypes = new ConcurrentDictionary<string, Type>();
        }

        public void Initialize()
        {
            DefaultExchangeDeclareConfiguration =  new ExchangeDeclareConfiguration(
                AbpRabbitMqEventBusOptions.ExchangeName,
                type: "direct",
                durable: true
            );
            
            SubscribeHandlers(AbpDistributedEventBusOptions.Handlers);
        }
        
        
        private async Task ProcessEventAsync(IModel channel, BasicDeliverEventArgs ea)
        {
            var eventName = ea.RoutingKey;
            var eventType = EventTypes.GetOrDefault(eventName);
            if (eventType == null)
            {
                return;
            }

            var eventData = Serializer.Deserialize(ea.Body.ToArray(), eventType);

            await TriggerHandlersAsync(eventType, eventData);
        }

        public IDisposable Subscribe<TEvent>(IDistributedEventHandler<TEvent> handler) where TEvent : class
        {

            return Subscribe(typeof(TEvent), handler);
        }

        public override IDisposable Subscribe(Type eventType, IEventHandlerFactory factory)
        {
            var handlerFactories = GetOrCreateHandlerFactories(eventType);

            if (factory.IsInFactories(handlerFactories))
            {
                return NullDisposable.Instance;
            }

            handlerFactories.Add(factory);

            if (handlerFactories.Count == 1) //TODO: Multi-threading!
            {
                //Todo: Colocar o nome do clientid se a queue for nula
                //Todo: Verificar a fila em cluster
                var queue =  RabbitMqEventAttribute.GetQueueOrDefault(eventType);
                var bindkey =  RabbitMqEventAttribute.GetNameOrDefault(eventType);

                var consumer  = MessageConsumerFactory.Create(
                    DefaultExchangeDeclareConfiguration,
                    new QueueDeclareConfiguration(
                        queue ?? AbpRabbitMqEventBusOptions.ClientName,
                        durable: true,
                        exclusive: false,
                        autoDelete: false
                    ),
                    AbpRabbitMqEventBusOptions.ConnectionName
                );
                consumer.OnMessageReceived(ProcessEventAsync);

                consumer.BindAsync(bindkey);
            }

            return new EventHandlerFactoryUnregistrar(this, eventType, factory);
        }

        /// <inheritdoc/>
        public override void Unsubscribe<TEvent>(Func<TEvent, Task> action)
        {
            Check.NotNull(action, nameof(action));

            GetOrCreateHandlerFactories(typeof(TEvent))
                .Locking(factories =>
                {
                    factories.RemoveAll(
                        factory =>
                        {
                            var singleInstanceFactory = factory as SingleInstanceHandlerFactory;
                            if (singleInstanceFactory == null)
                            {
                                return false;
                            }

                            var actionHandler = singleInstanceFactory.HandlerInstance as ActionEventHandler<TEvent>;
                            if (actionHandler == null)
                            {
                                return false;
                            }

                            return actionHandler.Action == action;
                        });
                });
        }

        /// <inheritdoc/>
        public override void Unsubscribe(Type eventType, IEventHandler handler)
        {
            GetOrCreateHandlerFactories(eventType)
                .Locking(factories =>
                {
                    factories.RemoveAll(
                        factory =>
                            factory is SingleInstanceHandlerFactory &&
                            (factory as SingleInstanceHandlerFactory).HandlerInstance == handler
                    );
                });
        }

        /// <inheritdoc/>
        public override void Unsubscribe(Type eventType, IEventHandlerFactory factory)
        {
            GetOrCreateHandlerFactories(eventType).Locking(factories => factories.Remove(factory));
        }

        /// <inheritdoc/>
        public override void UnsubscribeAll(Type eventType)
        {
            GetOrCreateHandlerFactories(eventType).Locking(factories => factories.Clear());
        }

        public override Task PublishAsync(Type eventType, object eventData)
        {
            var bindKeyOrDefault = RabbitMqEventAttribute.GetNameOrDefault(eventType);
            var body = Serializer.Serialize(eventData);

            using (var channel = ConnectionPool.Get(AbpRabbitMqEventBusOptions.ConnectionName).CreateModel())
            {
                channel.ExchangeDeclare(
                    AbpRabbitMqEventBusOptions.ExchangeName,
                    "direct",
                    durable: true
                );

                var properties = channel.CreateBasicProperties();
                properties.DeliveryMode = RabbitMqConsts.DeliveryModes.Persistent;

                channel.BasicPublish(
                    exchange: AbpRabbitMqEventBusOptions.ExchangeName,
                    routingKey: bindKeyOrDefault,
                    mandatory: true,
                    basicProperties: properties,
                    body: body
                );
            }

            return Task.CompletedTask;
        }

        private List<IEventHandlerFactory> GetOrCreateHandlerFactories(Type eventType)
        {
            return HandlerFactories.GetOrAdd(
                eventType,
                type =>
                {
                    var eventName = RabbitMqEventAttribute.GetNameOrDefault(eventType);
                    EventTypes[eventName] = type;
                    return new List<IEventHandlerFactory>();
                }
            );
        }

        protected override IEnumerable<EventTypeWithEventHandlerFactories> GetHandlerFactories(Type eventType)
        {
            var handlerFactoryList = new List<EventTypeWithEventHandlerFactories>();

            foreach (var handlerFactory in HandlerFactories.Where(hf =>
                ShouldTriggerEventForHandler(eventType, hf.Key)))
            {
                handlerFactoryList.Add(
                    new EventTypeWithEventHandlerFactories(handlerFactory.Key, handlerFactory.Value));
            }

            return handlerFactoryList.ToArray();
        }

        private static bool ShouldTriggerEventForHandler(Type targetEventType, Type handlerEventType)
        {
            //Should trigger same type
            if (handlerEventType == targetEventType)
            {
                return true;
            }

            //TODO: Support inheritance? But it does not support on subscription to RabbitMq!
            //Should trigger for inherited types
            if (handlerEventType.IsAssignableFrom(targetEventType))
            {
                return true;
            }

            return false;
        }
    }
}
```

6º I add an attribute in each Eto 

```cs
   
    [RabbitMqEvent("EtlRunner.Process.Start", Queue = "QueueNamed")]
    public class ExampleEto
    {
        string name {get; set;}
```
    
7º Instead of using AbpRabbitMqModule Im use My Module ExampleRabbitMqModule

```cs
    [DependsOn(
    .....
    typeof(ExampleRabbitMqModule)
    )]
```
