### ISSUE TITLE
ABP CLI Tool: switch-to-preview Error

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#7739]
*  **ABP Framework version**: 4.2.1.
* **User Interface**:  Blazor 
* **Database provider **: EF Core

**Steps needed to **reproduce** the problem.**
 
Run the CLI Tool with command :

```
ABP switch-to-preview

```

* Exception message and **stack trace** if available (check the logs).
>PS C:\Users\xxx\source\repos\BlazorGp5.0\aspnet-core> abp switch-to-preview
[10:37:39 INF] ABP CLI (https://abp.io)
[10:37:40 INF] Version 4.2.1 (Stable)
[10:37:44 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.GetLatestVersionFromMyGet(String packageId) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 222
   at Volo.Abp.Cli.ProjectModification.VoloNugetPackagesVersionUpdater.UpdateSolutionAsync(String solutionPath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, Boolean checkAll, String version) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\VoloNugetPackagesVersionUpdater.cs:line 40
   at Volo.Abp.Cli.ProjectModification.PackagePreviewSwitcher.SwitchToPreview(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\PackagePreviewSwitcher.cs:line 36
   at Volo.Abp.Cli.Commands.SwitchToPreviewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\SwitchToPreviewCommand.cs:line 20
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59
PS C:\Users\274188A\source\repos\BlazorGp5.0\aspnet-core>

**Comment by KevinFarrow** [comment]
This also happens with **switch-to-nightly**

![image](https://user-images.githubusercontent.com/1365851/108039163-a5aaa880-7033-11eb-909c-5ee4825aa607.png)

**Comment by yekalkan** [comment]
@274188A @KevinFarrow 

It is working now.
