### ISSUE TITLE
Issues with 4.2.1

### ISSUE THREAD

**Issue by EdmundHerbert** [abpframework/abp#7780]
08:16:16 INF] Creating initial migration...
[08:16:17 INF] ABP CLI (https://abp.io)
[08:16:18 INF] Version 4.2.1 (Stable)
[08:16:22 ERR] Migrations failed: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
System.Exception: Migrations failed: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
   at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigrator.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigrator.cs:line 37
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

C:\Work2020\IOT_Dashboard_2021\Iot_Dashboard_2021\src\IOT_Dashboard.DbMigrator\bin\Debug\net5.0\IOT_Dashboard.DbMigrator.exe (process 14688) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

Hi i am having following issue when running migrations in MVC and Blazor

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/7506#issuecomment-770144009
