### ISSUE TITLE
Navigation property 'Tokens' on entity of type 'User' cannot be loaded because the entity is not being tracked. 

### ISSUE THREAD

**Issue by matthew-qin1** [abpframework/abp#7817]
Hi,
I am receiving the following error when logging in to my application when using multiple tenant (multiple databases) :

> Mvc.ExceptionHandling.AbpExceptionFilter - Navigation property 'Tokens' on entity of type 'User' cannot be loaded because the entity is not being tracked. Navigation properties can only be loaded for tracked entities.
System.InvalidOperationException: Navigation property 'Tokens' on entity of type 'User' cannot be loaded because the entity is not being tracked. Navigation properties can only be loaded for tracked entities.
   at Aon.ChinaDigitalBenefits.Authorization.Users.UserManager.AddTokenValidityKeyAsync(User user, String tokenValidityKey, DateTime expireDate, CancellationToken cancellationToken) in C:\GIT\CDB\src\Aon.ChinaDigitalBenefits.Core\Authorization\Users\UserManager.cs:line 245
   at Abp.Domain.Uow.UnitOfWorkInterceptor.InternalInterceptAsynchronous(IInvocation invocation)
   at Aon.ChinaDigitalBenefits.Web.Controllers.TokenAuthController.CreateJwtClaims(ClaimsIdentity identity, User user, Nullable`1 expiration, TokenType tokenType) in C:\GIT\CDB\src\Aon.ChinaDigitalBenefits.Web.Core\Controllers\TokenAuthController.cs:line 778
   at Aon.ChinaDigitalBenefits.Web.Controllers.TokenAuthController.Authenticate(AuthenticateModel model) in C:\GIT\CDB\src\Aon.ChinaDigitalBenefits.Web.Core\Controllers\TokenAuthController.cs:line 206
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

In this case, no user token will be created. 
> AddTokenValidityKeyAsync
>UserRepository.EnsureCollectionLoadedAsync
>await repo.EnsureCollectionLoadedAsync(entity, collectionExpression, cancellationToken);

throw this exception

I've checked the IdentityBuilder but I guess it's not the reason :
``` c#   
public static IdentityBuilder Register(IServiceCollection services)
        {
            services.AddLogging();

            return services.AddAbpIdentity<Tenant, User, Role>(options =>
                {
                    options.Tokens.ProviderMap[GoogleAuthenticatorProvider.Name] = new TokenProviderDescriptor(typeof(GoogleAuthenticatorProvider));
                })
                .AddAbpTenantManager<TenantManager>()
                .AddAbpUserManager<UserManager>()
                .AddAbpRoleManager<RoleManager>()
                .AddAbpEditionManager<EditionManager>()
                .AddAbpUserStore<UserStore>()
                .AddAbpRoleStore<RoleStore>()
                .AddAbpSignInManager<SignInManager>()
                .AddAbpUserClaimsPrincipalFactory<UserClaimsPrincipalFactory>()
                .AddAbpSecurityStampValidator<SecurityStampValidator>()
                .AddPermissionChecker<PermissionChecker>()
                .AddDefaultTokenProviders();
        }
```

**Comment by maliming** [comment]
You are using [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate/). 

Please get help at https://github.com/aspnetboilerplate/aspnetboilerplate/issues/new

**Comment by matthew-qin1** [comment]
@maliming  thank you.

Add link: https://github.com/aspnetboilerplate/aspnetboilerplate/issues
