### ISSUE TITLE
NullReferenceException after abp app deployment with no "clear" source in logs

### ISSUE THREAD

**Issue by loca1-host** [abpframework/abp#7936]
ABP Framework version : 4.1.0
User Interface: MVC
Database provider: EF Core

[logs.txt](https://github.com/abpframework/abp/files/6082578/logs.txt)

The app runs fine locally but once you try to deploy and run it, you get a blank page and the logs contain some NullReferenceExceptions. 

The Swagger page works fine. Though I have a feeling some of the schemas aren't represented right.

404 pages are displayed for non existing pages but no styles or scripts are applied. 

These NullReferenceExceptions don't seem to have a 'source' as far as my knowledge of reviewing the log file.

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by loca1-host** [comment]
> 
> 
>     * Steps needed to **reproduce** the problem.



Besides providing you with my repository source so you can try to deploy it on you side, I honestly have no clue.

Am using a database and a bunch or components which are basically crud modals plus <abp-script> tags to call js files wherever need be - just trying to point out stuff that could probably help to find the root problem basing on the issues I've read here thus far.

**Comment by maliming** [comment]
This is like a `NUglifyJavascriptMinifier` problem.
We need steps to reproduce the problem

```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseVarDecl(JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseVariableStatement()
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseFunctionBody(BlockStatement body)
   at NUglify.JavaScript.JSParser.ParseFunction(FunctionType functionType, SourceContext fncCtx)
   at NUglify.JavaScript.JSParser.ParseClassElement()
   at NUglify.JavaScript.JSParser.ParseClassNode(ClassType classType)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseFunctionBody(BlockStatement body)
   at NUglify.JavaScript.JSParser.ParseFunction(FunctionType functionType, SourceContext fncCtx)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseArrayLiteral(Boolean isBindingPattern)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionList(JSToken terminator)
   at NUglify.JavaScript.JSParser.ParseMemberExpression_LeftParenthesis(AstNode& expression, List`1 newContexts, Boolean optionalChaining)
   at NUglify.JavaScript.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpression(Boolean single, JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseReturnStatement()
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseFunctionBody(BlockStatement body)
   at NUglify.JavaScript.JSParser.ParseFunction(FunctionType functionType, SourceContext fncCtx)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionList(JSToken terminator)
   at NUglify.JavaScript.JSParser.ParseMemberExpression_LeftParenthesis(AstNode& expression, List`1 newContexts, Boolean optionalChaining)
   at NUglify.JavaScript.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext, CodeSettings settings)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at Volo.Abp.Minify.NUglify.NUglifyJavascriptMinifier.UglifySource(String source, String fileName)
   at Volo.Abp.Minify.NUglify.NUglifyMinifierBase.Minify(String source, String fileName, String originalFileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetAndMinifyFileContent(IBundlerContext context, String fileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetFileContentConsideringMinification(IBundlerContext context, String fileName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.Bundle(IBundlerContext context)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.<>c__DisplayClass17_0.<GetBundleFilesAsync>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.<>c__DisplayClass6_0`2.<GetOrAdd>b__0(TKey k)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleCache.GetOrAdd(String bundleName, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetBundleFilesAsync(BundleConfigurationCollection bundles, String bundleName, IBundler bundler)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetScriptBundleFilesAsync(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperScriptService.GetBundleFilesAsync(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`2.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Themes_Basic_Layouts_Application.<>c__DisplayClass13_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\Users\Mark Ahugari\source\repos\NcheSite\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic\Themes\Basic\Layouts\Application.cshtml:line 69
```

**Comment by loca1-host** [comment]
> 
> 
> This is like a `NUglifyJavascriptMinifier` problem.
> We need steps to reproduce the problem
> 


Since you mention Javascript. I hope this helps. 
Reference or call your js files before the body of your .cshtml pages like this:
`@section scripts{
    <abp-script-bundle>
        <abp-script src="/yourparentfolder/yourfolder/yourfolder/index.js" />
    </abp-script-bundle>
}`

Have a couple of these with basic js code. Don't add the js files to your ConfigureBundle module method.

If it looks like a 'NUglifyJavascriptMinifier' problem is it possible to stop the 'minification' and see if it solves something?

**Comment by loca1-host** [comment]
UPDATE: Since you mentioned Javascript and 'minifier'. With a few searches I got to learn about a way to control minification. So I disabled it entirely. Application starts up nicely now. All thanks to you @maliming!

**Comment by maliming** [comment]
You should find the cause of the problem, not disable a feature.

**Comment by loca1-host** [comment]
> 
> 
> You should find the cause of the problem, not disable a feature.

I found the problem. 

Ckeditor js files. So I removed them from a bundle and served them as is (.min). Then restored the feature.

Thanks again @maliming
