### ISSUE TITLE
permission list ui got error

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#799]
2019-02-13 10:25:35.894 +08:00 [ERR] No policy defined to get/set permissions for the provider ''. Use PermissionManagementOptions to map the policy.
Volo.Abp.AbpException: No policy defined to get/set permissions for the provider ''. Use PermissionManagementOptions to map the policy.
   at Volo.Abp.PermissionManagement.PermissionAppService.CheckProviderPolicy(String providerName) in D:\Github\abp\modules\permission-management\src\Volo.Abp.PermissionManagement.Application\Volo\Abp\PermissionManagement\PermissionAppService.cs:line 102
   at Volo.Abp.PermissionManagement.PermissionAppService.GetAsync(String providerName, String providerKey) in D:\Github\abp\modules\permission-management\src\Volo.Abp.PermissionManagement.Application\Volo\Abp\PermissionManagement\PermissionAppService.cs:line 37
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.DynamicProxy.AbpInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\DynamicProxy\AbpInterceptor.cs:line 11
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.InterceptAsyncMethod(IInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 40
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync() in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapter.cs:line 53
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Authorization\Volo\Abp\Authorization\AuthorizationInterceptor.cs:line 39
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Auditing\Volo\Abp\Auditing\AuditingInterceptor.cs:line 52
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Volo.Abp.PermissionManagement.Web.Pages.AbpPermissionManagement.PermissionManagementModal.OnGetAsync() in D:\Github\abp\modules\permission-management\src\Volo.Abp.PermissionManagement.Web\Pages\AbpPermissionManagement\PermissionManagementModal.cshtml.cs:line 39
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
2019-02-13 10:25:35.974 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2019-02-13 10:25:35.976 +08:00 [INF] Executed page /AbpPermissionManagement/PermissionManagementModal in 1524.7302ms
2019-02-13 10:25:35.976 +08:00 [INF] Request finished in 1941.6681ms 500 application/json; charset=utf-8

**Comment by CAH-FlyChen** [comment]
sorry my code error.  when create project use new template online .every thing is ok.
