### ISSUE TITLE
Issue regarding accessing public repos of document pages

### ISSUE THREAD

**Issue by SnehalP1992** [abpframework/abp#8072]
Hello Team, 

We have followed all the steps given for setting up documentation using volodocs documentation (https://docs.abp.io/en/abp/2.9/Apps/VoloDocs). But whenever we tried to access public repository, we are not able to do so. It just displays you don't have any public repo with error code 500.

I would really appreciate, if you can assist us to get this issue resolved at the earliest for our urgent release. Awaiting your response.

**Comment by maliming** [comment]
hi

You can try to follow the latest document https://docs.abp.io/en/abp/latest/Apps/VoloDocs

> with error code 500.

Please check your application logs.

**Comment by SnehalP1992** [comment]
Hello,
Yes, we followed the same document. But still we are not able to see added repositories, do we need to have some other settings? In the logs, we can just encounter this error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Docs.Pages.Documents.Project.IndexModel.GetSpecificVersionOrLatest() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 174
   at Volo.Docs.Pages.Documents.Project.IndexModel.ConvertDocumentContentToHtml() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 223
   at Volo.Docs.Pages.Documents.Project.IndexModel.SetDocumentAsync() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 218
   at Volo.Docs.Pages.Documents.Project.IndexModel.OnGetAsync() in D:\Github\abp\modules\docs\src\Volo.Docs.Web\Pages\Documents\Project\Index.cshtml.cs:line 59
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Can you guide us more on that.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/111399193-d1d34b00-86ff-11eb-982f-eb4af04f23de.png)
![image](https://user-images.githubusercontent.com/6908465/111399207-d8fa5900-86ff-11eb-8825-b84ffdfcfc1c.png)
