### ISSUE TITLE
Migration issue : Failed to authenticate HTTPS connection

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#8086]
Hi,

I have just completed my 3 tier application migration, but after installing it on production I got the following error message:

```
2021-03-16 20:26:33.299 +00:00 [DBG] Connection "0HM7890UQIFHF" established using the following protocol: "Tls13"
2021-03-16 20:26:33.300 +00:00 [DBG] Connection id "0HM7890UQIFHF" disconnecting.
2021-03-16 20:26:33.300 +00:00 [DBG] Connection id "0HM7890UQIFHF" stopped.
2021-03-16 20:26:33.300 +00:00 [DBG] Connection id "0HM7890UQIFHF" reset.
2021-03-16 20:26:33.300 +00:00 [DBG] Connection id "0HM7890UQIFHF" reset.
2021-03-16 20:26:33.300 +00:00 [DBG] Connection id "0HM7890UQIFHF" sending FIN because: "Broken pipe"
2021-03-16 20:26:35.301 +00:00 [DBG] Connection id "0HM7890UQIFHG" accepted.
2021-03-16 20:26:35.303 +00:00 [DBG] Connection id "0HM7890UQIFHG" started.
2021-03-16 20:26:35.309 +00:00 [DBG] Connection id "0HM7890UQIFHG" reset.
2021-03-16 20:26:35.320 +00:00 [DBG] Failed to authenticate HTTPS connection.
2021-03-16 20:26:35.320 +00:00 [DBG] Failed to authenticate HTTPS connection.
Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)

```
I didn't see any change related to this in the migration guide, right ?

So, do you have any idea of the possible problem?

**Comment by maliming** [comment]
I think this has nothing to do with abp but `Kestrel`
