### ISSUE TITLE
BookStore  Blazorise

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#8149]
I updated in sample app Blazorise
from 
Version="0.9.3-preview6" 
to
Version="0.9.3.1"

and get exception
System.TypeLoadException: Could not resolve type with token 0100009e from typeref (expected class 'Blazorise.ModalBackdrop' in assembly 'Blazorise, Version=0.9.3.0, Culture=neutral, PublicKeyToken=null')
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.Bootstrap.Modal.<BuildRenderTree>b__0_1(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1[[Blazorise.States.ModalState, Blazorise, Version=0.9.3.1, Culture=neutral, PublicKeyToken=null]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

I'm playng with BookStore-Blazor-EfCore

with Version="0.9.3-preview6"  everything is running Ok

**Comment by Gosha24** [comment]
It looks like this exception is connected to tight couple between Host and Blazor projects. I can not change and run Blazor project without recompiling and rerunning Host project

**Comment by 274188A** [comment]
I hit the same problem:  #7997
short answer - stick with the version that the CLI uses until they fix things
