### ISSUE TITLE
Automapper throws missing type map configuration even if it is configured

### ISSUE THREAD

**Issue by ocodista** [abpframework/abp#8208]
### GitHub Issues

* Your **ABP Framework version** : 4.2.2
* Your **User Interface**: Blazor
* Your database provider: EF Core
* Exception message and **stack trace** if available (check the logs).
Exception:
Missing type map configuration or unsupported mapping.

Mapping types:
Object -> UserDto
System.Object -> X.Authorization.Users.UserDto

StackTrace:
   at lambda_method1723(Closure , Object , UserDto , ResolutionContext )
   at Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider.Map[TSource,TDestination](Object source)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.AutoMap[TSource,TDestination](Object source)
   at Volo.Abp.ObjectMapping.DefaultObjectMapper.Map[TSource,TDestination](TSource source)
   at Volo.Abp.Application.Services.AbstractKeyReadOnlyAppService`5.MapToGetOutputDto(TEntity entity)
   at Castle.Proxies.UserAppServiceProxy.MapToGetOutputDto_callback(IdentityUser entity)
   at Castle.Proxies.Invocations.AbstractKeyReadOnlyAppService`5_MapToGetOutputDto.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedSynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
--- End of stack trace from previous location ---
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.Rethrow(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowInnerIfAggregate(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowIfFaulted(Task task)
   at Castle.DynamicProxy.AsyncInterceptorBase.InterceptSynchronousResult[TResult](AsyncInterceptorBase me, IInvocation invocation)
   at Castle.DynamicProxy.AsyncInterceptorBase.Castle.DynamicProxy.IAsyncInterceptor.InterceptSynchronous(IInvocation invocation)
   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedSynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
--- End of stack trace from previous location ---
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.Rethrow(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowInnerIfAggregate(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowIfFaulted(Task task)
   at Castle.DynamicProxy.AsyncInterceptorBase.InterceptSynchronousResult[TResult](AsyncInterceptorBase me, IInvocation invocation)
   at Castle.DynamicProxy.AsyncInterceptorBase.Castle.DynamicProxy.IAsyncInterceptor.InterceptSynchronous(IInvocation invocation)
   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedSynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
--- End of stack trace from previous location ---
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.Rethrow(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowInnerIfAggregate(Exception exception)
   at Castle.DynamicProxy.NoCoverage.RethrowHelper.RethrowIfFaulted(Task task)
   at Castle.DynamicProxy.AsyncInterceptorBase.InterceptSynchronousResult[TResult](AsyncInterceptorBase me, IInvocation invocation)
   at Castle.DynamicProxy.AsyncInterceptorBase.Castle.DynamicProxy.IAsyncInterceptor.InterceptSynchronous(IInvocation invocation)
   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.UserAppServiceProxy.MapToGetOutputDto(IdentityUser entity)
   at UserAppService.CreateAsync(CreateUserDto input) in 
 UserAppService.cs:line 50

* Steps needed to **reproduce** the problem.
I'm trying to call the function MapToGetOutputDto() passing an IdentityUser as parameter, and using a UserDto class that its like this :
```
public class UserDto : ExtensibleEntityDto<Guid>
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }

        public List<string> Roles { get; set; }
    }

```
I have a class called ApplicationAutoMapperProfile that is like this: 
```
public class XApplicationAutoMapperProfile : Profile
    {
        public XApplicationAutoMapperProfile()
        {
            /* You can configure your AutoMapper mapping configuration here.
             * Alternatively, you can split your mapping configurations
             * into multiple profile classes for a better organization. */


            // User mappings
            this.CreateMap<User, UserDto>();
            this.CreateMap<UserDto, User>();
            this.CreateMap<IdentityUser, UserDto>();
            this.CreateMap<UserDto, IdentityUser>();

            // Roles mappings
            this.CreateMap<IdentityRole, RoleDto>();
            this.CreateMap<RoleDto, IdentityRole>();
            this.CreateMap<RoleAndPermissions, RoleDto>();
            this.CreateMap<RoleDto, RoleAndPermissions>();

            // Permissions mappings
            this.CreateMap<PermissionWithGrantedProviders, PermissionDto>();
            this.CreateMap<PermissionDto, PermissionWithGrantedProviders>();

        }
    }


```
But its not working, always throw that exception and I don't know where else to look to fix it.

**Comment by scottiemc7** [comment]
What was the solution to this issue? I am currently running into it.
