### ISSUE TITLE
Mongo tests fail in the sample application

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8497]
https://github.com/abpframework/abp-samples/tree/master/TodoApp/BlazorServer-Mongo

Run unit tests to get the following exception:

````
TodoApp.Samples.SampleAppServiceTests.Initial_Data_Should_Contain_Admin_User

System.TypeInitializationException: The type initializer for 'TodoApp.MongoDB.TodoAppMongoDbFixture' threw an exception.

System.TypeInitializationException
The type initializer for 'TodoApp.MongoDB.TodoAppMongoDbFixture' threw an exception.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Xunit.Sdk.XunitTestCollectionRunner.<>c__DisplayClass11_0.<CreateCollectionFixture>b__3() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCollectionRunner.cs:line 103
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73

MongoDB.Driver.MongoCommandException
Command replSetInitiate failed: already initialized.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAttempt(RetryableReadContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperation[T](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](IClientSessionHandle session, Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.<>c__DisplayClass46_0`1.<RunCommand>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
   at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean doNotKill, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at TodoApp.MongoDB.TodoAppMongoDbFixture..cctor() in D:\Github\abp-samples\TodoApp\BlazorServer-Mongo\test\TodoApp.MongoDB.Tests\MongoDb\TodoAppMongoDbFixture.cs:line 13
````

We should fix if there is a problem with mongodb test setup in the startup templates.

**Comment by realLiangshiwei** [comment]
The problem related to rider and mongo2go, When using rider for concurrent testing, mongo2go uses the same port to start the mongo server.

![image](https://user-images.githubusercontent.com/16813853/113961883-545fae00-9859-11eb-84f1-869dcf0af82a.png)

If we change assemblies count to 1 in parallel, it will works fine.


![image](https://user-images.githubusercontent.com/16813853/113962194-c6d08e00-9859-11eb-9623-fe32b88d1932.png)

**Comment by realLiangshiwei** [comment]
https://github.com/Mongo2Go/Mongo2Go/issues/115

I will send a PR to mongo2go, we can ignore this error for now.

**Comment by realLiangshiwei** [comment]
https://github.com/Mongo2Go/Mongo2Go/pull/116
