### ISSUE TITLE
Method may only be called on a Type for which Type.IsGenericParameter is true

### ISSUE THREAD

**Issue by yilezhu** [abpframework/abp#860]
When I use Expression in a custom method, I report the above error. The code is as follows：
```C#
 public async Task<List<JobInfoDto>> GetJobInfoDtosAsync(Expression<Func<JobInfo, bool>> where)
        {
            var result = await _repository.GetJobInfoDtosAsync(where);
            return ObjectMapper.Map<List<JobInfo>,List<JobInfoDto>>(result);
        }
```

Error Message:
Property accessor 'DeclaringMethod' on object 'System.RuntimeType' threw the following exception:'Method may only be called on a Type for which Type.IsGenericParameter is true.'
![image](https://user-images.githubusercontent.com/18655233/53779455-25b8d000-3f3b-11e9-9078-54f7d0a80b20.png)

> StackTrace message  like below

```C#
   at System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component)
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 107
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 77
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 100
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 100
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 100
   at Volo.Abp.Validation.ObjectValidator.ValidateObjectRecursively(List`1 errors, Object validatingObject, Int32 currentDepth) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 100
   at Volo.Abp.Validation.ObjectValidator.GetErrors(Object validatingObject, String name, Boolean allowNull) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ObjectValidator.cs:line 55
   at Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(IAbpValidationResult context, ParameterInfo parameterInfo, Object parameterValue) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\MethodInvocationValidator.cs:line 99
   at Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(MethodInvocationValidationContext context) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\MethodInvocationValidator.cs:line 87
   at Volo.Abp.Validation.MethodInvocationValidator.Validate(MethodInvocationValidationContext context) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\MethodInvocationValidator.cs:line 49
   at Volo.Abp.Validation.ValidationInterceptor.Intercept(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Validation\Volo\Abp\Validation\ValidationInterceptor.cs:line 26
   at Volo.Abp.DynamicProxy.AbpInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\DynamicProxy\AbpInterceptor.cs:line 11
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.InterceptAsyncMethod(IInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 40
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync() in D:\Github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpMethodInvocationAdapter.cs:line 53
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Authorization\Volo\Abp\Authorization\AuthorizationInterceptor.cs:line 39
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\Github\abp\framework\src\Volo.Abp.Auditing\Volo\Abp\Auditing\AuditingInterceptor.cs:line 52
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction) in D:\Github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Threading\InternalAsyncHelper.cs:line 149
   at Czar.AbpDemo.Startup.<>c__DisplayClass1_0.<<Configure>b__0>d.MoveNext() in E:\workspace\vs2017\AbpQuartzDemo\src\Czar.AbpDemo.Web\Startup.cs:line 42
```

**Comment by maliming** [comment]
It is best to use DTO instead of complex types in the input and output types of the application service layer method.

**Comment by yilezhu** [comment]
> It is best to use DTO instead of complex types in the input and output types of the application service layer method.

thank you,I get it!

**Comment by alexandis** [comment]
Nevertheless, would be great to have possibility to pass Expression<Action> into app layer. Let's say I have background worker (Hangfire) and there could be numerous types of background job body, which I want to pass, using Expression<Action>. How do I do that? Meanwhile, I bumped into the same error as topic starter.

**Comment by wensaint** [comment]
@yilezhu  我遇到相同的问题，请问你是怎么解决的

**Comment by wensaint** [comment]
finaly succeed: ADD **DisableValidationAttribute** to your class or method, then you can use Expression in your application layer.
