### ISSUE TITLE
abp (4.3.0-rc.2) new Acme.BookStoreBlazor -u blazor -d mongodb --separate-identity-server error

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#8666]
* **ABP Framework 4.3.0-rc.2**.
*  **User Interface** type (Blazor)
* Database provider(MongoDB)
* Exception message and **stack trace** if available (check the logs):
[22:31:40 INF] ABP CLI (https://abp.io)
[22:31:40 INF] Version 4.3.0-rc.2 (Prerelease)
[22:31:42 INF] Creating your project...
[22:31:42 INF] Project name: Acme.BookStoreBlazor
[22:31:42 INF] Database provider: MongoDb
[22:31:42 INF] UI Framework: Blazor
[22:31:42 INF] Output folder: D:\SourceCode\BookStoreBlazor
[22:31:48 INF] Using cached template: app, version: 4.2.2
[22:31:49 ERR] Could not find file: /aspnet-core/src/MyCompanyName.MyProjectName.Blazor.Server/MyCompanyName.MyProjectName.Blazor.Server.csproj
System.ApplicationException: Could not find file: /aspnet-core/src/MyCompanyName.MyProjectName.Blazor.Server/MyCompanyName.MyProjectName.Blazor.Server.csproj
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildContextExtensions.GetFile(ProjectBuildContext context, String filePath) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildContextExtensions.cs:line 14
   at Volo.Abp.Cli.ProjectBuilding.Templates.App.AppTemplateSwitchEntityFrameworkCoreToMongoDbStep.ChangeProjectReference(ProjectBuildContext context, String targetProjectFilePath, String oldReference, String newReference) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Templates\App\AppTemplateSwitchEntityFrameworkCoreToMongoDbStep.cs:line 204
   at Volo.Abp.Cli.ProjectBuilding.Templates.App.AppTemplateSwitchEntityFrameworkCoreToMongoDbStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Templates\App\AppTemplateSwitchEntityFrameworkCoreToMongoDbStep.cs:line 81
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 114   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 192
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

https://abp.io/api/download/template/get-version/ -->   [405] Error! An internal error occurred during your request! .So the CLI try to use the cached template.

* Steps needed to **reproduce** the problem:
* dotnet tool install --global Volo.Abp.Cli --version 4.3.0-rc.2
* abp new Acme.BookStoreBlazor -u blazor -d mongodb --separate-identity-server

**Comment by maliming** [comment]
You need to use ` --preview`.

`abp new Acme.BookStoreBlazor -u blazor -d mongodb --separate-identity-server --preview`
