### ISSUE TITLE
Login Button not redirect to login page

### ISSUE THREAD

**Issue by alaawahbah** [abpframework/abp#8768]
I am using angular community abp
I host the backend on host Public, and connect to it from local machine,
When i click the login button  it doesn't redirect to login page or to check page.
I try it on local iis it doesn't work
I try it on public host for backend and public host for front end it doesn't work.
Please advise me to solve this issue
the host is WWW.smarterasp.net
Thanks in advance.

**Comment by maliming** [comment]
Please check your application logs and browser console.

**Comment by alaawahbah** [comment]
Good morning :
this is the log 

```
2021-04-24 03:01:31.985 -07:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2021-04-24 03:01:31.989 -07:00 [INF] Bearer was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
2021-04-24 03:01:31.994 -07:00 [INF] No CORS policy found for the specified request.
2021-04-24 03:01:32.042 -07:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2021-04-24 03:01:32.087 -07:00 [INF] Route matched with {area = "abp", action = "Get", controller = "AbpApplicationConfiguration", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto] GetAsync() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController (Volo.Abp.AspNetCore.Mvc).
2021-04-24 03:01:32.132 -07:00 [WRN] The cookie 'XSRF-TOKEN' has set 'SameSite=None' and must also set 'Secure'.
2021-04-24 03:01:34.086 -07:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto'.
2021-04-24 03:01:34.204 -07:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc) in 2105.6717ms
2021-04-24 03:01:34.205 -07:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2021-04-24 03:01:34.218 -07:00 [INF] Request finished HTTP/1.1 GET http://alaawahbah-001-site1.dtempurl.com/api/abp/application-configuration - - - 200 - application/json;+charset=utf-8 15755.6130ms
2021-04-24 03:01:34.378 -07:00 [INF] Request starting HTTP/1.1 GET http://alaawahbah-001-site1.dtempurl.com/api/abp/application-configuration - -
2021-04-24 03:01:34.378 -07:00 [INF] CORS policy execution successful.
2021-04-24 03:01:34.383 -07:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2021-04-24 03:01:34.383 -07:00 [INF] Bearer was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
2021-04-24 03:01:34.383 -07:00 [INF] No CORS policy found for the specified request.
2021-04-24 03:01:34.386 -07:00 [INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2021-04-24 03:01:34.386 -07:00 [INF] Route matched with {area = "abp", action = "Get", controller = "AbpApplicationConfiguration", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto] GetAsync() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController (Volo.Abp.AspNetCore.Mvc).
2021-04-24 03:01:34.389 -07:00 [WRN] The cookie 'XSRF-TOKEN' has set 'SameSite=None' and must also set 'Secure'.
2021-04-24 03:01:34.437 -07:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto'.
2021-04-24 03:01:34.440 -07:00 [INF] Executed action Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc) in 53.264ms
2021-04-24 03:01:34.440 -07:00 [INF] Executed endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
2021-04-24 03:01:34.440 -07:00 [INF] Request finished HTTP/1.1 GET http://alaawahbah-001-site1.dtempurl.com/api/abp/application-configuration - - - 200 - application/json;+charset=utf-8 62.6898ms
2021-04-24 03:04:34.184 -07:00 [INF] Application is shutting down...
```

**Comment by maliming** [comment]
There is some error in your log. Please check one by one.

**Comment by alaawahbah** [comment]
Hi I solve all bugs, i publish the code on different ports on same server the login button don't redirect to backend to do login

constructor(
    private authService: AuthService,
    private oAuthService: OAuthService  ) {}
this.authService
      .login({
        username: 'admin',
        password: '1q2w3E*',
       // rememberMe: true,
        //redirectUrl:environment.application.baseUrl + this.router.url
      })
      .subscribe(s=>{
        console.log("s")
        console.log(s)
      },err=>{
        console.log(err)
      });
      
this code is work in visual studio and angular dev server and it redirect to login page. I try multiple scenario like publish back end on local machine on http://localhost:8000 and front on default dev angular server http://localhost:4200 it work.
I certain add ips in table IdentityServerClientCorsOrigins
<HTML>
<BODY>
<TABLE><TR><TD>https://localhost:44322</TD></TR><TR><TD>http://192.168.1.103:8001</TD></TR><TR><TD>http://localhost:4200</TD></TR><TR><TD>http://192.168.1.103:8000</TD></TR><TR><TD>http://35***:44390</TD></TR><TR><TD>https://localhost:44390</TD></TR></TABLE>

</BODY>
</HTML>

The published on publish ip or local network doesn't work , only work local host, I think it is silly reason but id cant discover it 

there is no network request when it doesn't work
the this.oAuthService.loginUrl in this state is null

**Comment by maliming** [comment]
> The published on publish ip or local network doesn't work , only work local host,

The application will use different configurations in production and development environments, can you confirm?

**Comment by alaawahbah** [comment]
> > The published on publish ip or local network doesn't work , only work local host,
> 
> The application will use different configurations in production and development environments, can you confirm?


I have congiguration in appsettings.json and the other fils of config are empty
{
  "App": {
    "SelfUrl": "http://35.2**9:44390",
    "CorsOrigins": "https://*.ISO.com,http://localhost:4200,http://35.2***47.199,http://localhost,http://35.2****9:44390",
    "RedirectAllowedUrls": "http://localhost:4200,https://localhost:44307,http://35.224.247.199,http://35***9:44390"
  },
  "ConnectionStrings": {
    "Default": "Data Source=***;Initial Catalog=ISOD***;User Id=sddsf;Password=*****"
  },
  "AuthServer": {
    "Authority": "http://35.2***.199:44390",
    "RequireHttpsMetadata": "false",
    "SwaggerClientId": "ISO_Swagger",
    "SwaggerClientSecret": "***"
  },
  "StringEncryption": {
    "DefaultPassPhrase": "****"
  },
  "Settings": {
    "Abp.Mailing.Smtp.Host": "127.0.0.1",
    "Abp.Mailing.Smtp.Port": "25",
    "Abp.Mailing.Smtp.UserName": "",
    "Abp.Mailing.Smtp.Password": "",
    "Abp.Mailing.Smtp.Domain": "",
    "Abp.Mailing.Smtp.EnableSsl": "false",
    "Abp.Mailing.Smtp.UseDefaultCredentials": "true",
    "Abp.Mailing.DefaultFromAddress": "noreply@abp.io",
    "Abp.Mailing.DefaultFromDisplayName": "ABP application"
  }
}

in enviroment.prod.ts

import { Environment } from '@abp/ng.core';

const baseUrl = 'http://35.22***199';

export const environment = {
  production: true,
  application: {
    baseUrl,
    name: 'ISO',
    logoUrl: '',
  },
  oAuthConfig: {
    issuer: 'http://35.224***4390',
    redirectUri: baseUrl,
    clientId: 'ISO_App',
    responseType: 'code',
    scope: 'offline_access ISO',
  },
  apis: {
    default: {
      url: 'http://35.2***9:44390',
      rootNamespace: 'RMG.ISO',
    },
  },
  localization: {
    defaultResourceName: 'ISO',
  }

  
} as Environment;

**Comment by alaawahbah** [comment]
I  download the last version and I published on new ports with bellow configuration


angular environment Prod 

![image](https://user-images.githubusercontent.com/12495983/118461060-8e945900-b6fd-11eb-8ecc-58e90eb52f72.png)

iis appsetting.json

![image](https://user-images.githubusercontent.com/12495983/118461739-46296b00-b6fe-11eb-9d68-5addd2790e84.png)


DB
![image](https://user-images.githubusercontent.com/12495983/118460713-3eb59200-b6fd-11eb-82a6-396979e6c078.png)

appsettings.json of PublishingTest.DbMigrator

![image](https://user-images.githubusercontent.com/12495983/118463031-97862a00-b6ff-11eb-8fbf-614321520599.png)

I have the same error the angular don't redirect to  the server to login
do you have any advice ?
do you see any error in my config?
It is my critical issue for about one month.
I have some friends having the paid version they don't have this error.

**Comment by alaawahbah** [comment]
I  download the last version and I published on new ports with bellow configuration


angular environment Prod 

![image](https://user-images.githubusercontent.com/12495983/118467712-52182b80-b704-11eb-9e31-4986cb9d006c.png)


iis appsetting.json

![image](https://user-images.githubusercontent.com/12495983/118467791-69571900-b704-11eb-8f09-0c9045188c3f.png)


DB

![image](https://user-images.githubusercontent.com/12495983/118467870-7c69e900-b704-11eb-9465-2caa33037d8b.png)

appsettings.json of PublishingTest.DbMigrator

![image](https://user-images.githubusercontent.com/12495983/118467945-8b509b80-b704-11eb-9309-28be20fed083.png)

if url is localhost it works fine

**Comment by maliming** [comment]
hi

What's the error now? Can you share the details?

**Comment by alaawahbah** [comment]
When I publish the back end and Front end and set the IP or domains instead of local host the login redirect not happen.

![image](https://user-images.githubusercontent.com/12495983/118617462-f496e400-b7c2-11eb-9e9f-0a176a157d79.png)


Now i am publish my local iis site  the ngrok same issue

**Comment by alaawahbah** [comment]
Can you descripe publish backend and frontend (angular) step by step and what is the configuration is  in back and front?

**Comment by maliming** [comment]
Can you try to set the **skipIssuerCheck** property in Angular?

https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#skipIssuerCheck

**Comment by alaawahbah** [comment]
@maliming  Thank your effort for support,
we solve this issue by running it on https for back and front
thanks
