### ISSUE TITLE
CLI template creation with version 3.3 

### ISSUE THREAD

**Issue by ThuanNP** [abpframework/abp#8777]
I have to create new solution with .net core version 3.1. So, I use ABP CLI to create new app but alway fail with this report.

❯ abp new Btv.SouthernVendingMachine -t app -dbms MySQL --version 3.3.1

[01:00:36 INF] ABP CLI (https://abp.io)
[01:00:37 INF] Version 3.3.1 (Stable)
[01:00:41 WRN] ABP CLI has a newer stable version 4.3.0, please update to get the latest features and fixes.
[01:00:41 WRN]
[01:00:41 WRN] Update Command:
[01:00:41 WRN] dotnet tool update -g Volo.Abp.Cli
[01:00:41 WRN]
[01:00:41 INF] Creating your project...
[01:00:41 INF] Project name: Btv.SouthernVendingMachine
[01:00:41 INF] Template: app
[01:00:41 INF] Version: 3.3.1
[01:00:41 INF] Create Solution Folder: no
[01:00:41 INF] Output folder: ~/btv-svm
[01:00:46 INF] Downloading template: app, version: 3.3.1
Error occured while downloading source-code from https://abp.io/api/download/template/ : Remote server returns '500-Internal Server Error'.
[01:00:48 ERR] Remote server returns '500-Internal Server Error'.
System.Exception: Remote server returns '500-Internal Server Error'.
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 44
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 222
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 108
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 56
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 134
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by maliming** [comment]
hi @ismcagdas 

Here is the error stack info.

```cs
ICSharpCode.SharpZipLib.Zip.ZipException: EOF in header
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputBuffer.ReadLeByte()
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputBuffer.ReadLeInt()
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at Volo.AbpIo.Templates.ZipFileHelper.GetEntriesFromZipFileAsync(IRemoteStreamContent remoteStreamContent, Func`2 predicate) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/ZipFileHelper.cs:line 48
   at Volo.AbpIo.Templates.ZipFileHelper.GetEntriesFromZipFileAsync(IRemoteStreamContent remoteStreamContent, Func`2 predicate) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/ZipFileHelper.cs:line 30
   at Volo.AbpIo.Templates.GitHub.GitHubSourceCodeContentStore.ExtractTemplateFile(String templateRootBasePath, String gitHubRepoRootPath, IRemoteStreamContent repositoryFileContent, List`1 extraFolders, Boolean addDirectoryBuildProps) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/GitHub/GitHubSourceCodeContentStore.cs:line 337
   at Volo.AbpIo.Templates.GitHub.GitHubSourceCodeContentStore.GetTemplateFileAsync(IHaveDownloadableSourceCode template, String version, GithubRepository githubRepo, List`1 extraFolders, Boolean addDirectoryBuildProps) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/GitHub/GitHubSourceCodeContentStore.cs:line 268
   at Volo.AbpIo.Templates.GitHub.GitHubSourceCodeContentStore.GetAsync(IHaveDownloadableSourceCode template, List`1 extraFolders, String version, Boolean includePreReleases, Boolean addDirectoryBuildProps) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Domain/Templates/GitHub/GitHubSourceCodeContentStore.cs:line 99
   at Volo.AbpIo.Www.Templates.TemplateDownloadAppService.DownloadAsync(TemplateDownloadInputDto input) in /var/lib/jenkins/workspace/abp.io-build/volo/abp/abp_io/src/Volo.AbpIo.Www.Application/Templates/TemplateDownloadAppService.cs:line 78
   
```

**Comment by ismcagdas** [comment]
@ThuanNP it should be working now, can you try again ?

**Comment by ThuanNP** [comment]
> @ThuanNP it should be working now, can you try again ?

It worked. Thank you, @ismcagdas!
