### ISSUE TITLE
oData or GraphQL Support on ABP.io Framework

### ISSUE THREAD

**Issue by sachindratomer** [abpframework/abp#8907]
We are exploring ABP.IO framework to utilize it for new development. There is a requirement that leverage oData or GraphQL capabilities. We have found previous framework ABPboilerplate has capabilities for oData but ABP.IO we didn't any reference for oData. We have a couple of questions on the same.

1.	Do you have any plan to provide oData or GraphQL support in the near future, if yes what’s the expected timeline
2.	We tried to implement it manually utilize Microsoft.AspNetCore.OData But unable to utilize it properly. Mainly Observed below issues
a.	As we do not have AbpODataEntityController hence  API controller can’t be inherited from oDataController
b.	Manually added EDM information, It does expose metadata link but breaks when try to access it 
c.	oData works on IEnumerable and OData Option like select, filter, etc are working fine 
d.	IQueryable is not working as Autofac disposes of the DB Context, even though I tried to change lifetime to scoped of the repository.
i.	[Dependency(ServiceLifetime.Scoped, ReplaceServices = true)]

An alternate would be to look at the Internal flow of ABP and tweak the code, apply the workaround which is not best solution. If you have an implementation sample please share

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/4132

**Comment by sachindratomer** [comment]
@realLiangshiwei  - Thanks for sharing the link, Above example does not demonstrate IQueryable instead it's based on IEnumerable. when you replace IEnumerable with IQueryable you will get error mentioned in 2.d as DBContext is disposed of before oData options applies on it.

if you can reply to my questions it will be helpful.

**Comment by realLiangshiwei** [comment]
See https://support.abp.io/QA/Questions/799/PowerBI#answer-ec6114b3-66e2-55eb-c64c-39fa2fd53ea1

**Comment by sachindratomer** [comment]
@realLiangshiwei - In your sample returning IQueryable is not an issue (pls refer below code). I am getting below error message - DBContext has been closed, Any suggestion?
ex, 
![image](https://user-images.githubusercontent.com/40390988/117285974-43b94c80-ae86-11eb-8f12-e5b108cd3296.png)

Error:
System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ClaimManagementoDataDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

**If i can get the reference of the example that would be great,**
private readonly IDimAssetClassRepository _dimAssetClassRepository;

public DimAssetClassController(IDimAssetClassRepository dimAssetClassRepository)
{
    _dimAssetClassRepository = dimAssetClassRepository;
}

[EnableQuery]
public IQueryable<DimAssetClass> Get()
{
    **return _dimAssetClassRepository.GetDbSet().AsQueryable();**
}

**Comment by realLiangshiwei** [comment]
I have updated the example project: https://github.com/realLiangshiwei/AbpOdataDemo/commit/6cf03b6cce608818679d03a00d40541036c66cf7

![image](https://user-images.githubusercontent.com/16813853/117295459-75daa680-aea6-11eb-9e97-1ba9203c39ca.png)

**Comment by sachindratomer** [comment]
@realLiangshiwei - Thanks for your efforts, It seems your project reference an older version of ABP.IO as inheriting it from oDataController remove it from the Swagger list. though i tried to register it via Dependndency (Pls refer below). 
I downgraded my oData version to same as yours still issues persist. Can you please validate issues with the latest version of ABP?  
as it seems ABP version is causing this issue. 

{
    [RemoteService]
    [Dependency(ServiceLifetime.Transient, ReplaceServices = true)]
    [ExposeServices(typeof(AbpController))]
    [Route("api/ClaimManagementoData/claims2")]
    public class ClaimController2 : ODataController, IClaim2AppService

**Comment by gdlcf88** [comment]
Please see: https://github.com/abpframework/abp/issues/86#issuecomment-1001041045
