### ISSUE TITLE
Can i use efcore and mongodb on a project?

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#8937]
now i use efcore and mongodb on a project,but when i use mongodb have error;
- Exceptions:
  - Standalone servers do not support transactions.
    System.NotSupportedException: Standalone servers do not support transactions.
   at MongoDB.Driver.Core.Bindings.CoreSession.EnsureTransactionsAreSupported()
   at MongoDB.Driver.Core.Bindings.CoreSession.EnsureStartTransactionCanBeCalled()
   at MongoDB.Driver.Core.Bindings.CoreSession.StartTransaction(TransactionOptions transactionOptions)
   at MongoDB.Driver.Core.Bindings.WrappingCoreSession.StartTransaction(TransactionOptions transactionOptions)
   at MongoDB.Driver.Core.Bindings.WrappingCoreSession.StartTransaction(TransactionOptions transactionOptions)
   at MongoDB.Driver.ClientSessionHandle.StartTransaction(TransactionOptions transactionOptions)

**Comment by maliming** [comment]
You can't use MongoDB and ef core in a project at the same time, but can use they in two separate modules

**Comment by sofm13** [comment]
now i have two moudule,efcore project and mongodb project,but use on a repository

**Comment by maliming** [comment]
Start from document.
https://docs.abp.io/en/abp/latest/Data-Access
https://docs.abp.io/en/abp/latest/Module-Development-Basics
