### ISSUE TITLE
No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#9009]
* Your **ABP Framework version**.
* 4.3.0
* Steps needed to **reproduce** the problem.
* use AbpIdentityAspNetCoreModule
        public async Task ResetPassword(ResetPasswordInput data)
        {
            var t = await UserRepository.GetAsync(data.UserId);
            string token = await UserManager.GeneratePasswordResetTokenAsync(t);
            await UserManager.ResetPasswordAsync(t, token, data.Password);
        }

got exception

2021-05-13 02:24:36.011 [ERR] [Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
   at Microsoft.AspNetCore.Identity.UserManager`1.GenerateUserTokenAsync(TUser user, String tokenProvider, String purpose)
   at Castle.Proxies.IdentityUserManagerProxy.GenerateUserTokenAsync_callback(IdentityUser user, String tokenProvider, String purpose)
   at Castle.Proxies.Invocations.UserManager`1_GenerateUserTokenAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Zion.ERP.OverridedServices.ZionIdentityUserAppService.ResetPassword(ResetPasswordInput data) in /src/src/Zion.ERP.Application/OverridedServices/ZionIdentityUserAppService.cs:line 70
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method3140(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

the default account controller got the same error.

**Comment by aelhadi** [comment]
the same problem : 



```csharp
 public override async Task<IdentityUserDto> RegisterAsync(RegisterDto input)
        {
            var userDto = await base.RegisterAsync(
              new RegisterDto
              {
                  AppName = "French Coders",
                  EmailAddress = input.EmailAddress,
                  Password = input.Password,
                  UserName = input.UserName
              }
             );

            // Send user an email to confirm email address
            _abpIdentityUser = await UserManager.GetByIdAsync(userDto.Id);
            await SendEmailToAskForEmailConfirmationAsync(_abpIdentityUser);

            return userDto;
        }
```





[15:19:22 ERR] No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
   at Microsoft.AspNetCore.Identity.UserManager`1.GenerateUserTokenAsync(TUser user, String tokenProvider, String purpose)
   at Castle.Proxies.IdentityUserManagerProxy.GenerateUserTokenAsync_callback(IdentityUser user, String tokenProvider, String purpose)
   at Castle.Proxies.Invocations.UserManager`1_GenerateUserTokenAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at FrenchCoders.FrontendAccountAppService.SendEmailToAskForEmailConfirmationAsync(IdentityUser user) in C:\Users\elhad\source\repos\French-Coders-Org\BackEnd\NetCore\src\FrenchCoders.Application\Overrides\FCAccountAppService.cs:line 82
   at FrenchCoders.FrontendAccountAppService.RegisterAsync(RegisterDto input) in C:\Users\elhad\source\repos\French-Coders-Org\BackEnd\NetCore\src\FrenchCoders.Application\Overrides\FCAccountAppService.cs:line 58
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1580(Closure , Object )

**Comment by aelhadi** [comment]
I think we have to configure identity options:

```csharp
private void ConfigureIdentityOptions(ServiceConfigurationContext context)
{
    context.Services.Configure<IdentityOptions>(options =>
    {
      options.SignIn.RequireConfirmedAccount = true;
      options.SignIn.RequireConfirmedEmail = true;
      options.SignIn.RequireConfirmedPhoneNumber = false;
    });
}
```

**Comment by maliming** [comment]
Full steps needed to reproduce the problem.

**Comment by aelhadi** [comment]
Hello,

Override AccountAppService as : 

```csharp
using Volo.Abp.Emailing;
using Volo.Abp.Identity;
using Volo.Abp.ObjectExtending;
using Volo.Abp.Settings;
using System.Text.Encodings.Web;
using Volo.Abp;

namespace MyApp
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IAccountAppService), typeof(AccountAppService), typeof(FrontendAccountAppService))]
    public class FrontendAccountAppService : AccountAppService
    {
        private readonly IEmailSender _emailSender;
        private Volo.Abp.Identity.IdentityUser _abpIdentityUser;
        private readonly IdentityUserManager _userManager;


        public FrontendAccountAppService(
            IdentityUserManager userManager,
            IIdentityRoleRepository roleRepository,
            IAccountEmailer accountEmailer,
            IdentitySecurityLogManager identitySecurityLogManager,
            IOptions<IdentityOptions> identityOptions, IEmailSender emailSender) : base (userManager,roleRepository,accountEmailer,identitySecurityLogManager,identityOptions)
        {
            _emailSender = emailSender;
            _userManager = userManager;
        }

        
        public override async Task<IdentityUserDto> RegisterAsync(RegisterDto input)
        {
            await CheckSelfRegistrationAsync();

            await IdentityOptions.SetAsync();

            var userDto = await base.RegisterAsync(
              new RegisterDto
              {
                  AppName = "MyApp",
                  EmailAddress = input.EmailAddress,
                  Password = input.Password,
                  UserName = input.UserName
              }
             );

            // Send user an email to confirm email address
            _abpIdentityUser = await UserManager.GetByIdAsync(userDto.Id);
            await SendEmailToAskForEmailConfirmationAsync(_abpIdentityUser);

            return userDto;
        }
        

        public async Task<IdentityResult> ConfirmeEmail(string userEmail, string code)
        {
            var user = await _userManager.FindByEmailAsync(userEmail);

            if (user == null)
            {

                throw new AbpException("ResourceSet values of Identity is empty.");
               
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            return await _userManager.ConfirmEmailAsync(user, code);
        }

        public async Task SendEmailToAskForEmailConfirmationAsync(Volo.Abp.Identity.IdentityUser user)
        {
            
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));

            // var callbackUrl = "Url.Page("/Account/ConfirmEmail", pageHandler: null, values: new { userId = user.Id, code = code }, protocol: Request.Scheme)";

            var callbackUrl = "";

            // TODO use EmailService instead of using IEmailSender directly
            await _emailSender.SendAsync(user.Email, "Confirm your email",
                $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
        }
    }
}
```
 try to call the overrided RegisterAsync from Postman to test it : 

![image](https://user-images.githubusercontent.com/5918026/118234425-98b31f00-b493-11eb-90fd-bd97e78207ad.png)


the occured error is  : 






```
[09:07:16 INF] Request starting HTTP/1.1 POST https://localhost:44313/api/app/frontend-account/register application/json 124
[09:07:16 INF] Executing endpoint 'FrenchCoders.FrontendAccountAppService.RegisterAsync (FrenchCoders.Application)'
[09:07:16 INF] Route matched with {action = "Register", controller = "FrontendAccount", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.IdentityUserDto] RegisterAsync(Volo.Abp.Account.RegisterDto) on controller FrenchCoders.FrontendAccountAppService (FrenchCoders.Application).
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}
[09:07:25 ERR] No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
   at Microsoft.AspNetCore.Identity.UserManager`1.GenerateUserTokenAsync(TUser user, String tokenProvider, String purpose)
   at Castle.Proxies.IdentityUserManagerProxy.GenerateUserTokenAsync_callback(IdentityUser user, String tokenProvider, String purpose)
   at Castle.Proxies.Invocations.UserManager`1_GenerateUserTokenAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.ProceedInfo.Invoke()
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at FrenchCoders.FrontendAccountAppService.SendEmailToAskForEmailConfirmationAsync(IdentityUser user) in C:\Users\elhad\source\repos\French-Coders-Org\BackEnd\NetCore\src\FrenchCoders.Application\Overrides\FCAccountAppService.cs:line 86
   at FrenchCoders.FrontendAccountAppService.RegisterAsync(RegisterDto input) in C:\Users\elhad\source\repos\French-Coders-Org\BackEnd\NetCore\src\FrenchCoders.Application\Overrides\FCAccountAppService.cs:line 62
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1507(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[09:07:25 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[09:07:25 INF] Executed action FrenchCoders.FrontendAccountAppService.RegisterAsync (FrenchCoders.Application) in 8944.7971ms
[09:07:25 INF] Executed endpoint 'FrenchCoders.FrontendAccountAppService.RegisterAsync (FrenchCoders.Application)'
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 DBG] Added 0 entity changes to the current audit log
[09:07:25 INF] Request finished HTTP/1.1 POST https://localhost:44313/api/app/frontend-account/register application/json 124 - 500 - application/json;+charset=utf-8 8966.3180ms
```

**Comment by maliming** [comment]
Is this an MVC project create by CLI?

**Comment by aelhadi** [comment]
Angular project with separate Identity (tiered)

generated from abp.io not CLI.

I just try to add AddDefaultTokenProviders() to my IDP but it's not working : 

```csharp
 public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var hostingEnvironment = context.Services.GetHostingEnvironment();
            var configuration = context.Services.GetConfiguration();

            context.Services
                .GetObject<IdentityBuilder>()
                .AddDefaultTokenProviders()
                ;
```

**Comment by maliming** [comment]
Try to depend on `AbpIdentityAspNetCoreModule` in your `HttpApi.Host` project.

Or

```cs
 public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IdentityBuilder>(builder =>
    {
        builder.AddDefaultTokenProviders()
    });
}
```

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpIdentityAspNetCoreModule.cs

**Comment by Omar-Javanshirli** [comment]
services.AddIdentity<User, Role>(commonIdentityOptions)
                .AddTokenProvider<DataProtectorTokenProvider<User>>(TokenOptions.DefaultProvider)
                .AddSignInManager<SignInManager<User>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddUserManager<UserManager<User>>();

            services.AddIdentityCore<BoardOfDirector>(commonIdentityOptions)
                .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<BoardOfDirector, Role>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddTokenProvider<DataProtectorTokenProvider<BoardOfDirector>>(TokenOptions.DefaultAuthenticatorProvider)
                .AddSignInManager<SignInManager<BoardOfDirector>>()
                .AddUserManager<UserManager<BoardOfDirector>>();
                
                
                I get this error "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
         at Microsoft.AspNetCore.Identity.UserManager`1.GenerateUserTokenAsync(TUser user, String tokenProvider, String purpose)
         at GreenPay.AuthenticationServer.Service.Services.AuthenticationServices.BoardOfDirectorAuthenticationService.ForgetPasswordAsync(ForgetPasswordRequest request) in /Users/javanshilir/RiderProjects/GreenPay/AuthenticationServer/GreenPay.AuthenticationServer.Service/Services/AuthenticationServices/BoardOfDirectorAuthenticationService.cs:line 230
"  

if anyone know solution please can help me? I can't find solution

**Comment by Omar-Javanshirli** [comment]
services.AddIdentity<User, Role>(commonIdentityOptions)
                .AddTokenProvider<DataProtectorTokenProvider<User>>(TokenOptions.DefaultProvider)
                .AddSignInManager<SignInManager<User>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddUserManager<UserManager<User>>();

            services.AddIdentityCore<BoardOfDirector>(commonIdentityOptions)
                .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<BoardOfDirector, Role>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddTokenProvider<DataProtectorTokenProvider<BoardOfDirector>>(TokenOptions.DefaultAuthenticatorProvider)
                .AddSignInManager<SignInManager<BoardOfDirector>>()
                .AddUserManager<UserManager<BoardOfDirector>>();
<img width="1321" alt="Screenshot 2023-11-27 at 01 45 00" src="https://github.com/abpframework/abp/assets/86188463/62759dd9-ede1-440f-99cb-d39f06594f1a">
<img width="1321" alt="Screenshot 2023-11-27 at 01 45 00" src="https://github.com/abpframework/abp/assets/86188463/80c4b728-cf91-494a-856e-bee7f7cb92b6">

**Comment by Omar-Javanshirli** [comment]
services.AddIdentity<User, Role>(commonIdentityOptions)
                .AddTokenProvider<DataProtectorTokenProvider<User>>(TokenOptions.DefaultProvider)
                .AddSignInManager<SignInManager<User>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddUserManager<UserManager<User>>();

            services.AddIdentityCore<BoardOfDirector>(commonIdentityOptions)
                .AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<BoardOfDirector, Role>>()
                .AddEntityFrameworkStores<AuthenticationDbContext>()
                .AddTokenProvider<DataProtectorTokenProvider<BoardOfDirector>>(TokenOptions.DefaultAuthenticatorProvider)
                .AddSignInManager<SignInManager<BoardOfDirector>>()
                .AddUserManager<UserManager<BoardOfDirector>>();
                
                if anyone know solution please can help me? I can't find solution
@
<img width="1321" alt="Screenshot 2023-11-27 at 01 45 00" src="https://github.com/abpframework/abp/assets/86188463/bf8f61f1-3374-42b1-b018-d22f3f990360">
