### ISSUE TITLE
An error on dynamic C# API Client call when upgraded 4.3.0

### ISSUE THREAD

**Issue by Rwing** [abpframework/abp#9076]
> 2021-05-18 16:58:54.589 +08:00 [FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Foo.FooHttpApiClientModule, Foo.HttpApi.Client, Version=0.0.6.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider' from assembly 'Volo.Abp.Authorization, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionDynamicHttpClientProxyExtensions.AddHttpClientProxies(IServiceCollection services, Assembly assembly, String remoteServiceConfigurationName, Boolean asDefaultServices)
   at Foo.FooHttpApiClientModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
System.TypeLoadException: Could not load type 'Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider' from assembly 'Volo.Abp.Authorization, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null'.
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Bar.Startup.ConfigureServices(IServiceCollection services) in Startup.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bar.Program.Main(String[] args) in Program.cs:line 47

The module Foo is based abp v4.0.0.
And the module Bar is based abp v4.3.0, when I downgrade to 4.2.2, everything is ok.

**Comment by enisn** [comment]
Your all codebase must use the same version, otherwise, you always may face a compatibility problem.

If you can share some code it's better to determine what was wrong.

**Comment by Rwing** [comment]
@enisn Hi, I created a repo to reproduce this issue 
https://github.com/Rwing/DynamicClientError

**Comment by enisn** [comment]
There may be breaking changes between versions. 
So we can't guarantee compatibility between different versions.

I highly recommend upgrading your older versions.
[Migration Guides](https://docs.abp.io/en/abp/latest/Migration-Guides/Index) might help you while upgrading

**Comment by Rwing** [comment]
@enisn Thank you for the clarification.
But I think this is a general problem and at least compatibility should be maintained between minor versions.
For some resons, it is not always possible to upgrade all microservices to the latest version.
