### ISSUE TITLE
Could not load type 'Volo.Abp.Authorization.AbpAuthorizationException' 

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#910]
![image](https://user-images.githubusercontent.com/16735741/54915389-ec6bf280-4f31-11e9-9609-546acd8d33f0.png)

System.TypeLoadException: Could not load type 'Volo.Abp.Authorization.AbpAuthorizationException' from assembly 'Volo.Abp.Authorization, Version=0.15.0.0, Culture=neutral, PublicKeyToken=null'.
   at Volo.Abp.AspNetCore.Mvc.ExceptionHandling.DefaultHttpExceptionStatusCodeFinder.GetStatusCode(HttpContext httpContext, Exception exception)
   at Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter.HandleAndWrapException(ExceptionContext context) in D:\Github\abp\framework\src\Volo.Abp.AspNetCore.Mvc\Volo\Abp\AspNetCore\Mvc\ExceptionHandling\AbpExceptionFilter.cs:line 71
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by hikalkan** [comment]
Please write more details.

**Comment by sortjiajun** [comment]
This is a version issue.I just upgraded the version to 0.15.0, the problem is solved.
