### ISSUE TITLE
Blazor server project error occurs when published. Authorization failed! Given policy has not granted. and no user name

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#9136]
* Your **ABP Framework version** : 4.3.1
* Your **User Interface** type : Blazor Server
* Your database provider(EF Core/MongoDB), EF Core
* Exception message and **stack trace** if available (check the logs).

Just created a new Blazor Server project, nothing changed and publish it,  there's no user name showing after login, no Administration menu, the Account/Manage page works, and the error occurs when open the Roles page
Authorization failed! Given policy has not granted.

**Comment by maliming** [comment]
Please check your logs.

**Comment by juchunwei** [comment]
@maliming

2021-05-23 10:55:56.397 +08:00 [INF] Authorization failed. These requirements were not met:
PermissionRequirement: AbpIdentity.Users
2021-05-23 10:55:56.401 +08:00 [INF] Authorization failed. These requirements were not met:
PermissionRequirement: AbpIdentity.Users.Create
2021-05-23 10:55:56.403 +08:00 [WRN] Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
Volo.Abp.Authorization.AbpAuthorizationException: Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.BlazoriseUI.AbpCrudPageBase`10.GetEntitiesAsync()
2021-05-23 10:55:56.403 +08:00 [WRN] Code:Volo.Authorization:010001
2021-05-23 10:55:56.405 +08:00 [INF] Authorization failed. These requirements were not met:
PermissionRequirement: AbpIdentity.Users.Create
2021-05-23 10:55:56.406 +08:00 [INF] Authorization failed. These requirements were not met:
PermissionRequirement: AbpIdentity.Users.Create
2021-05-23 10:55:56.406 +08:00 [INF] Authorization failed. These requirements were not met:
PermissionRequirement: AbpIdentity.Users.Create

**Comment by juchunwei** [comment]
@maliming ,

Hello maliming, 

this error seems since 4.3.0, I just finished my project, but couldn't publish it. Could you please give me any idea how to fix it? I think the reason is CurrentPrincipalAccessor couldn't get the current user information. 
And it has no problem when I'm using VS to debug it. I'm so sad now. 

Thanks!

**Comment by maliming** [comment]
You can change the **ASPNETCORE_ENVIRONMENT** environment to debug the application.

**Comment by leonkosak** [comment]
Tiered solution? Check Redis and configuration in appsettings.json.

**Comment by juchunwei** [comment]
@leonkosak ,

Not tiered solution.  nothing changed in the appsettings.json. I just create a new project and publish it.

Here's the link for the website. https://app.keyapp.com.cn/

Maybe I have to rewrite everything with MVC if it can't be solved.  :(

this issue since 4.3.0 preview.

**Comment by juchunwei** [comment]
@leonkosak 

I believe the reason is the CurrentPrincipalAccessor couldn't get the principal when it validate the permissions.
But it works when debug it in VS.

**Comment by maliming** [comment]
@juchunwei 

You are not enabled **WebSocket** in your web server.
