### ISSUE TITLE
Use Repository in Middleware.  Error occured like "Cannot access a disposed context instance..."

### ISSUE THREAD

**Issue by NetChenQian** [abpframework/abp#9225]
When use a repository in middleware，some error was occured.

The full error message is

```
Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'TestDbContext'.

   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Volo.Abp.EntityFrameworkCore.EfCoreAsyncQueryableProvider.CanExecute[T](IQueryable`1 queryable)
   at Volo.Abp.Linq.AsyncQueryableExecuter.<>c__DisplayClass4_0`1.<FindProvider>b__0(IAsyncQueryableProvider p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Volo.Abp.Linq.AsyncQueryableExecuter.FindProvider[T](IQueryable`1 queryable)
   at Volo.Abp.Linq.AsyncQueryableExecuter.FirstOrDefaultAsync[T](IQueryable`1 queryable, Expression`1 predicate, CancellationToken cancellationToken)
   at Volo.Abp.Domain.Repositories.RepositoryAsyncExtensions.<FirstOrDefaultAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Middlewares.TestMiddleware.<Invoke>d__4.MoveNext() in Middlewares\TestMiddleware.cs:line 51
```

The full code is

```
public class TestMiddleware
{
    private readonly Dictionary<string, StringValues> paths;

    private readonly RequestDelegate next;

    private readonly ITerminalRepository repository;

    public TestMiddleware(
        Dictionary<string, StringValues> paths,
        RequestDelegate next,
        ITerminalRepository repository)
    {
        this.paths = paths;
        this.next = next;
        this.repository = repository;
    }

    public async Task Invoke(HttpContext context)
    {
        StringValues methods;
        if (!paths.TryGetValue(context.Request.Path, out methods) || !methods.Contains(context.Request.Method))
        {
            await next.Invoke(context);
            return;
        }

        var logger = context.RequestServices.GetRequiredService<ILogger<TestMiddleware>>();


        var request = context.Request;
        var identifier = request.Query["Identifier"];
        if (!string.IsNullOrEmpty(identifier))
        {
            try
            {
                var result = await repository.FirstOrDefaultAsync(p => p.Identifier == identifier);
                if (result == default)
                {
                    throw new BusinessException(code: "TA0001", message: "get request identifier faild！");
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Parse {identifier} request faild！");
                throw new BusinessException(code: "TA0009", message: "Parse request faild！");
            }
        }
       
        await next.Invoke(context);
    }
}
```

please tell what should I do? thanks

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/search?q=Cannot+access+a+disposed+context+instance.&type=issues
