### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by ahmadmasoum** [abpframework/abp#9255]
Your ABP Framework version 4.3.
Your User Interface Angular
Your database providerEF Core
Exception message and stack trace if available (check the logs).

* Your **ABP Framework version**. 4.3.
* Your **User Interface** Angular
* Your database provider EF Core
* Exception message and **stack trace** if available (check the logs).

```
Access to XMLHttpRequest at 'https://localhost:44350/api/app/halda-transaction/import-halda-transaction' from origin 
'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
 header is present on the requested resource.
```
`No errors in log file`

* Steps needed to **reproduce** the problem.

Im trying to send a string from angular it works when i send few words but if its long text it gives me cors error

my endpoint 
```
 public async Task ImportHaldaTransaction(string text)
        {
            var haldaTransactions = _parserHelper.HaldaParser(text);
            await _haldaTransactionsRepository.InsertManyAsync(haldaTransactions);
        }
```
I've tried adding `[FromBody]` so it sends text in body insted of params and it gave me the same error no matter how short is the text

The endpoint generated by proxy
```
  importHaldaTransactionByText = (text: string) =>
    this.restService.request<any, void>({
      method: 'POST',
      url: '/api/app/halda-transaction/import-halda-transaction',
      params: { text },
    },
    { apiName: this.apiName });
```

appsettings.jeson file
```
  "App": {
    "SelfUrl": "https://localhost:44350",
    "CorsOrigins": "https://*.TMS.com,http://localhost:4200,https://localhost:44307,https://localhost:44398"
  },
```

**Comment by maliming** [comment]
> No errors in log file

Can you share the detailed logs of your request? also check the network panel of your browser to check the HTTP request info.

I think the problem is that your query string is too long.

**Comment by ahmadmasoum** [comment]
For some reason removing 
```
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
        <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
```
from `web.config` worked for me

and yes the string im sending is too long to send in params

i added `[FromBody]` to send it in body insted of params 

```
        public async Task ImportHaldaTransaction([FromBody] string text)
        {
            var haldaTransactions = _parserHelper.HaldaParser(text);
            await _haldaTransactionsRepository.InsertManyAsync(haldaTransactions);
        }
```

and the genarated proxy 

```
  importHaldaTransactionByText = (text: string) =>
    this.restService.request<any, void>({
      method: 'POST',
      url: '/api/app/halda-transaction/import-halda-transaction',
      body: text,
    },
    { apiName: this.apiName });
```

but its giving me error 415 now 
`Http failure response for https://localhost:44350/api/app/halda-transaction/import-halda-transaction: 415 OK`

and its working on swagger

**Comment by maliming** [comment]
The `body` content should be JSON. I think the method that generated is wrong.

Maybe:
```ts
  importHaldaTransactionByText = (text: string) =>
    this.restService.request<any, void>({
      method: 'POST',
      url: '/api/app/halda-transaction/import-halda-transaction',
      body: {"text": text},
    },
    { apiName: this.apiName });
```

**Comment by ahmadmasoum** [comment]
Didnt work 
```
{
2021-06-08 14:21:35.160 +03:00 [WRN] ModelState is not valid! See ValidationErrors for details.
Volo.Abp.Validation.AbpValidationException: ModelState is not valid! See ValidationErrors for details.
   at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)
   at Volo.Abp.AspNetCore.Mvc.Validation.AbpValidationActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-06-08 14:21:35.160 +03:00 [WRN] There are 1 validation errors:
Unexpected character encountered while parsing value: {. Path '', line 1, position 1. ()
```

**Comment by maliming** [comment]
How about?

```ts
  importHaldaTransactionByText = (text: string) =>
    this.restService.request<any, void>({
      method: 'POST',
      url: '/api/app/halda-transaction/import-halda-transaction',
      body: JSON.stringify(text),
    },
    { apiName: this.apiName });
```

And can you share the full HTTP request info of your API call?

**Comment by ahmadmasoum** [comment]
still giving me error 415 

```
  openDialog(): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.width = '750px';

    const dialogRef = this.dialog.open(ImportTransactionComponent, dialogConfig);

    dialogRef.afterClosed().subscribe(data => {
      this.haldaTransactionSvc.importHaldaTransactionByText(data).subscribe(res => {
        console.log(res);
      });
    });
  }
```

**Comment by maliming** [comment]
What's the HTTP request in the chrome's network panel?

**Comment by ahmadmasoum** [comment]
```
:authority: localhost:44350
:method: POST
:path: /api/app/halda-transaction/import-halda-transaction
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkFBNjYzRUQyNjFENjM2NzRCMzQxQzBBRDRCMEI0MTEwIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MTgwNjA1ODAsImV4cCI6MTY0OTU5NjU4MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTAiLCJhdWQiOiJUTVMiLCJjbGllbnRfaWQiOiJUTVNfQXBwIiwic3ViIjoiOGFjN2YzZmUtMzZkNS04M2YwLTE4ZGQtMzlmOWE1MDA3M2EwIiwiYXV0aF90aW1lIjoxNjE4MDYwNTc5LCJpZHAiOiJsb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImFkbWluIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOiJGYWxzZSIsImVtYWlsIjoiYWRtaW5AYWJwLmlvIiwiZW1haWxfdmVyaWZpZWQiOiJGYWxzZSIsIm5hbWUiOiJhZG1pbiIsInNpZCI6IkI0NzVERjAxNTFCMDY1MThGMzAxMjQ0ODg1REU4OTY3IiwiaWF0IjoxNjE4MDYwNTgwLCJzY29wZSI6WyJvcGVuaWQiLCJUTVMiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicHdkIl19.JnRFwGi9PBnJiMy1XUnXhmizMDw8anajhiX7ZZJOegpu8lvcyNbsHn0xlThIr92dl7o8And0bvOdx23y1p-CFnEH-GBE2Lk1Xpo00cisusa08iKzP8d9CsTG0QA1Y6RS1r00Jf3Dlkn39HYDSoGULQQGMLQ8dIti_LjnnpZT2gpdfQMbueHT8LDIgi6b18zbe-6B0MusQ2LebDbyvkEfsidbxMPNFHuqds5GW5MDiir1zerMOJZOSWUcNDarg06XrHN9caWLhjPr_8vSanVN986SMW5b9OIDeT7Qdcz0Ov4EFTlnmkoZ2RMa5-4nn4s0GFxw_-Z3xqQV9b5UveCpCA
content-length: 13
content-type: text/plain
origin: http://localhost:4200
referer: http://localhost:4200/
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
```

**Comment by maliming** [comment]
What's the body?

`content-type: text/plain`

I think it should be `content-type: application/json`

**Comment by ahmadmasoum** [comment]
Yeah making `content-type: application/json` worked 
but I have to make custom request right
there's no way to make proxy generate it for me ?

**Comment by maliming** [comment]
You can try to create DTO class.

```cs

class MyTextInput
{
   public string Text {get;set;}
|

public async Task ImportHaldaTransaction(MyTextInput text)
```

**Comment by ahmadmasoum** [comment]
Thanks man!
