### ISSUE TITLE
Skip Authorization from HttpApi Controller to Application Service

### ISSUE THREAD

**Issue by tarikdevapp** [abpframework/abp#9322]
Hello,
I'm using your sample bookstore https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore
Latest version, I just cloned it yestarday. 

I added a controller in HttpApi and injected IAuthorAppService to it and then created a method which I decorated with         [AllowAnonymous]. 
I called the GetListAsync (which is an authorized method in application service) from within the controller's method.
When I try to get the list of authors, I get an execption thrown. 
Mind you, that I'm able to access authorized methods from a method that has an [AllowAnonymous] when using it from an application service to a different application service or when using it from a controller to a controller but not from a controller to an application service.

In other words, we have two application services, one is called author and the other called book. I can access the authorized functions from author using an [AllowAnonymous] method on the book application service and vice versa but I can't use an [AllowAnonymous]  method from a controller to access the authorized function from an application service.
Is there a way to bypass authorization of the application service fucntion when using the controller method?

I hope you understand, best regards!

This is the Execption that I get:
`Volo.Abp.Authorization.AbpAuthorizationException: Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.

   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Acme.BookStore.Controllers.MyBookController.GetListCon() in C:\Users\dell\Desktop\BookStore-Mvc-EfCore\src\Acme.BookStore.HttpApi\Controllers\MyBookController.cs:line 29
   at lambda_method1819(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by ebicoglu** [comment]
see https://support.abp.io/QA/Questions/1054/Question-How-to-bypass--permission-check-in-some-method-in-AppService-for-a-Commercial-module

**Comment by tarikdevapp** [comment]
> see https://support.abp.io/QA/Questions/1054/Question-How-to-bypass--permission-check-in-some-method-in-AppService-for-a-Commercial-module

Thank you for the respond, I appreciate it!
It worked as expected, however, another problem came up to the surface, now when I use your TenantAppService and do the same to it so I can override its CreateAsync method which uses the base.CreateAsync(), everything starts acting weird.
Let me walk you through it:


    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(ITenantAppService), typeof(SubTenantAppService), typeof(TenantAppService))]
    public class SubTenantAppService : TenantAppService
    {
        private readonly ITenantRepository tenantRepository;
        private readonly ITenantManager tenantManager;
        private readonly IDataSeeder dataSeeder;

        public SubTenantAppService(ITenantRepository tenantRepository, ITenantManager tenantManager, IDataSeeder dataSeeder)
            : base(tenantRepository, tenantManager, dataSeeder)
        {
            this.tenantRepository = tenantRepository;
            this.tenantManager = tenantManager;
            this.dataSeeder = dataSeeder;
        }
        [AllowAnonymous]
        public override async Task<TenantDto> CreateAsync(TenantCreateDto input)
        {
            return await base.CreateAsync(input);

        }

    }
`
Now,  when I use Tenant on swagger (api/multi-tenancy/tenants) it is not supposed to let me create a tenant due to the fact that it has the authorized attribute.
The problem is when I execute the multi-tenancy/tenants/_CreateAsync_ it uses the overriden method  on my subTenantAppService instead of using its own method.
On the other hand, this doesn't happen when I use the AuthorAppService. When I execute an Authorized method i.e GetListAsync it throws an Authorization execption  since the request uses the authorized method and not the override one that is on my SubAuthorAppSerivce

`    [Authorize]
              public class AuthorAppService : BookStoreAppService, IAuthorAppService
              {
                private readonly IAuthorRepository _authorRepository;
                private readonly AuthorManager _authorManager;
                private readonly IAuthorizationService authorizationService;
                private readonly ITenantAppService tenantAppService;
          
                public AuthorAppService(
          
                    IAuthorRepository authorRepository,
                    AuthorManager authorManager, IAuthorizationService authorizationService,
                    ITenantAppService tenantAppService
          )
                {
                    _authorRepository = authorRepository;
                    _authorManager = authorManager;
                    this.authorizationService = authorizationService;
                    this.tenantAppService = tenantAppService;
                }

        public async Task<AuthorDto> GetAsync(Guid id)
        {
            var author = await _authorRepository.GetAsync(id);
          
            return ObjectMapper.Map<Author, AuthorDto>(author);
        }

        //[AllowAnonymous]
        [HttpGet("TestList")]
        public async virtual Task<PagedResultDto<AuthorDto>> GetListAsync(GetAuthorListDto input)
        {


            if (input.Sorting.IsNullOrWhiteSpace())
            {
                input.Sorting = nameof(Author.Name);
            }

            var authors = await _authorRepository.GetListAsync(
                input.SkipCount,
                input.MaxResultCount,
                input.Sorting,
                input.Filter
            );

            var totalCount = input.Filter == null
                ? await _authorRepository.CountAsync()
                : await _authorRepository.CountAsync(author => author.Name.Contains(input.Filter));

            return new PagedResultDto<AuthorDto>(
                totalCount,
                ObjectMapper.Map<List<Author>, List<AuthorDto>>(authors)
            );
        }

        //[Authorize(BookStorePermissions.Authors.Create)]
        public async virtual Task<AuthorDto> CreateAsync(CreateAuthorDto input)
        {

            var author = await _authorManager.CreateAsync(
                input.Name,
                DateTime.Now,
                input.ShortBio
            );

            await _authorRepository.InsertAsync(author);

            return ObjectMapper.Map<Author, AuthorDto>(author);
        }

        [Authorize(BookStorePermissions.Authors.Edit)]
        public async Task UpdateAsync(Guid id, UpdateAuthorDto input)
        {
            var author = await _authorRepository.GetAsync(id);

            if (author.Name != input.Name)
            {
                await _authorManager.ChangeNameAsync(author, input.Name);
            }

            author.BirthDate = input.BirthDate;
            author.ShortBio = input.ShortBio;

            await _authorRepository.UpdateAsync(author);
        }

        [Authorize(BookStorePermissions.Authors.Delete)]
        public async Task DeleteAsync(Guid id)
        {
            await _authorRepository.DeleteAsync(id);
        }
    }






    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IAuthorAppService), typeof(AuthorAppService), typeof(SubAuthorAppService))]
    public class SubAuthorAppService : AuthorAppService
    {
        private readonly IAuthorRepository authorRepository;
        private readonly AuthorManager authorManager;
        private readonly IAuthorizationService authorizationService;
        private readonly ITenantAppService tenantAppService;

        public SubAuthorAppService(IAuthorRepository authorRepository, AuthorManager authorManager,
            IAuthorizationService authorizationService, ITenantAppService tenantAppService) : base(authorRepository, authorManager, authorizationService, tenantAppService)
        {
            this.authorRepository = authorRepository;
            this.authorManager = authorManager;
            this.authorizationService = authorizationService;
            this.tenantAppService = tenantAppService;
        }
     [AllowAnonymous]
        public async override Task<PagedResultDto<AuthorDto>> GetListAsync(GetAuthorListDto input)
        {

            return await base.GetListAsync(input);
        }`

When I remove the ITenantAppSerivce from the attribute ExposeService that lives on top of the SubTenantAppService just then it uses its own method but when it is exposed it uses the SubTenantAppSerice Create method.

**Comment by tarikdevapp** [comment]
.

**Comment by tarikdevapp** [comment]
For future reference, I got around this by extending the services btw.
