### ISSUE TITLE
Identity issue changing dbms provider in encore

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#9331]
ABP Framework version: 4.3.2
User Interface : Blazor WASM
Your database provider: EFCore (using cosmos efcore provider)

Using the instructions in the documentation I changed from sqlserver to CosmosDB in efcore for my project. There are some issues - to be expected - in that initializing or migrating schema doesn't really make sense for cosmos, and I have worked through most of those (as long as the database and collection(s) are in place things seem to be ok). 
I am still running into some issues seeding data, however - such as creating the default admin user. 

The first issue I had on this process was the cosmos provider for efcore indicating that only etag concurrency is supported for the entities. That turned out to be pretty straightforward to address in the model extensions like this: 

builder.Entity<IdentityClaimType>(e=>
            {
                e.Property(p => p.ConcurrencyStamp).IsETagConcurrency();
            });

 and that got the process to move along. I see in my cosmos database that some entries were created for the permissions managementcontext (about 20 documents created for that) and an empty collection was created for settingmanagementdbcontext. However, when the migrator process gets to seeding identity data I get the following exception:

System.InvalidOperationException: The entity type 'IdentityClaimType' has property 'ConcurrencyStamp' as its concurrency token, but only '_etag' is supported. Consider using 'EntityTypeBuilder.UseETagConcurrency'.
   at Microsoft.EntityFrameworkCore.Cosmos.Internal.CosmosModelValidator

Which is strange, because I already have the code I referenced above (setting the concurrency stamp as etag concurrency) in place. If I remove that code I receive this exception earlier in the process - prior to where it seeds the permission and setting data - and if I leave it in place it gets through permissions and settings, but then fails with the same error on the identity data. It is almost like the process of seeding the identity data is not going through my main application efcore context, so the settings for etag concurrency aren't being applied.

**Comment by maliming** [comment]
hi

Maybe you can try to override the default configure of the `ConcurrencyStamp` property.

https://github.com/abpframework/abp/blob/2a22ebdd343cdeff094968c6e554086a5b602d65/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L43-L45

**Comment by jhulbertpmn** [comment]
> hi
> 
> 
> 
> Maybe you can try to override the default configure of the `ConcurrencyStamp` property.
> 
> 
> 
> https://github.com/abpframework/abp/blob/2a22ebdd343cdeff094968c6e554086a5b602d65/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L43-L45

Thanks. Sorry if I'm missing something which should be obvious but is there a step to overriding the handling of that property more than 

builder.Entity(e=>
{
e.Property(p => p.ConcurrencyStamp).IsETagConcurrency();
});

Which I did Already?

**Comment by maliming** [comment]
```cs
protected override void OnModelCreating(ModelBuilder builder)
{
	base.OnModelCreating(builder);

	/* Include modules to your migration db context */

	builder.ConfigurePermissionManagement();
	builder.ConfigureSettingManagement();
	builder.ConfigureBackgroundJobs();
	builder.ConfigureAuditLogging();
	builder.ConfigureIdentityPro();
	builder.ConfigureIdentityServer();
	builder.ConfigureFeatureManagement();
	builder.ConfigureLanguageManagement();
	builder.ConfigureSaas();
	builder.ConfigureTextTemplateManagement();
	builder.ConfigureBlobStoring();

	/* Configure your own tables/entities inside the ConfigureBookStore method */

	builder.ConfigureBookStore();

	foreach (var entityType in builder.Model.GetEntityTypes())
	{
		ConfigureConcurrencyStampPropertiesMethodInfo
			.MakeGenericMethod(entityType.ClrType)
			.Invoke(this, new object[] { builder, entityType });
	}
}

private static readonly MethodInfo ConfigureConcurrencyStampPropertiesMethodInfo
	= typeof(BookStoreMigrationsDbContext)
		.GetMethod(
			nameof(ConfigureConcurrencyStampProperties),
			BindingFlags.Instance | BindingFlags.NonPublic
		);

protected virtual void ConfigureConcurrencyStampProperties<TEntity>(ModelBuilder modelBuilder, IMutableEntityType mutableEntityType)
	where TEntity : class
{
	if (modelBuilder.Entity<TEntity>().Metadata.ClrType.IsAssignableTo<IHasConcurrencyStamp>())
	{
		modelBuilder.Entity<TEntity>().Property(nameof(IHasConcurrencyStamp.ConcurrencyStamp))
			.IsETagConcurrency()
			.HasMaxLength(ConcurrencyStampConsts.MaxLength)
			.HasColumnName(nameof(IHasConcurrencyStamp.ConcurrencyStamp));
	}
}
```

**Comment by jhulbertpmn** [comment]
Interesting, thanks. I tried this and received the same error (again, making it through the permissions and settings, but failing for identity). I stepped through it in debug and I do see that it is running the ConfigureConcurrencyStampProperties method for the IdentityClaimType entity


```cs
System.InvalidOperationException: The entity type 'IdentityClaimType' has property 'ConcurrencyStamp' as its concurrency token, but only '_etag' is supported. Consider using 'EntityTypeBuilder.UseETagConcurrency'.
   at Microsoft.EntityFrameworkCore.Cosmos.Internal.CosmosModelValidator.ValidateOnlyETagConcurrencyToken(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Cosmos.Internal.CosmosModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.Initialize(AbpEfCoreDbContextInitializationContext initializationContext)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.CreateDbContextAsync(IUnitOfWork unitOfWork, String connectionStringName, String connectionString)
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.GetDbContextAsync()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.GetDbSetAsync()
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.FindByNormalizedUserNameAsync(String normalizedUserName, Boolean includeDetails, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Identity.IdentityDataSeeder.SeedAsync(String adminEmail, String adminPassword, Nullable`1 tenantId)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at AbpIoCosmos.Data.AbpIoCosmosDbMigrationService.SeedDataAsync(Tenant tenant) in C:\Users\Administrator\Downloads\AbpIoCosmos\src\AbpIoCosmos.Domain\Data\AbpIoCosmosDbMigrationService.cs:line 103
   at AbpIoCosmos.Data.AbpIoCosmosDbMigrationService.MigrateAsync() in C:\Users\Administrator\Downloads\AbpIoCosmos\src\AbpIoCosmos.Domain\Data\AbpIoCosmosDbMigrationService.cs:line 53
   at AbpIoCosmos.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in C:\Users\Administrator\Downloads\AbpIoCosmos\src\AbpIoCosmos.DbMigrator\DbMigratorHostedService.cs:line 30
```

**Comment by maliming** [comment]
hi jhulbertpmn

You can try it without abp framework. Just use EF Core to test and debug.
