### ISSUE TITLE
run project microservicedemo on container has exception occurred 

### ISSUE THREAD

**Issue by bmzhe** [abpframework/abp#936]
When I tried a lot, the service public-website and backend-admin-app couldn't start.
I like learning through ABP vnext, but now I don't know what to do? I need help, thanks.

exception:
`
PS C:\Users\bmzhe> docker logs -f microservicedemo_backend-admin-app_1
Application startup exception: System.ArgumentException: The value cannot be null or empty.
Parameter name: value
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.StringWithQualityHeaderValue..ctor(String value)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.AddHeaders(IAbpMethodInvocation invocation, ActionApiDescriptionModel action, HttpRequestMessage requestMessage, ApiVersionInfo apiVersion) in /src/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs:line 217
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation) in /src/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs:line 141
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation) in /src/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs:line 114
   at Volo.Abp.Threading.InternalAsyncHelper.AwaitTaskWithPreActionAndPostActionAndFinallyAndGetResult[T](Func`1 actualReturnValue, Func`1 preAction, Func`1 postAction, Action`1 finalAction)
   at Volo.Abp.AspNetCore.Mvc.Client.CachedApplicationConfigurationClient.<GetAsync>b__14_0() in /src/framework/src/Volo.Abp.AspNetCore.Mvc.Client/Volo/Abp/AspNetCore/Mvc/Client/CachedApplicationConfigurationClient.cs:line 46
   at Volo.Abp.Caching.DistributedCache`1.GetOrAddAsync(String key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
   at Volo.Abp.AspNetCore.Mvc.Client.CachedApplicationConfigurationClient.GetAsync() in /src/framework/src/Volo.Abp.AspNetCore.Mvc.Client/Volo/Abp/AspNetCore/Mvc/Client/CachedApplicationConfigurationClient.cs:line 44
   at Volo.Abp.AspNetCore.Mvc.Client.RemoteLanguageProvider.GetLanguagesAsync() in /src/framework/src/Volo.Abp.AspNetCore.Mvc.Client/Volo/Abp/AspNetCore/Mvc/Client/RemoteLanguageProvider.cs:line 19
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.UseAbpRequestLocalization(IApplicationBuilder app) in /src/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/Builder/AbpApplicationBuilderExtensions.cs:line 55
   at BackendAdminApp.Host.BackendAdminAppHostModule.OnApplicationInitialization(ApplicationInitializationContext context) in /src/samples/MicroserviceDemo/applications/BackendAdminApp.Host/BackendAdminAppHostModule.cs:line 101
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in /src/framework/src/Volo.Abp.Core/Volo/Abp/Modularity/ModuleManager.cs:line 39
   at Volo.Abp.AbpApplicationBase.InitializeModules() in /src/framework/src/Volo.Abp.Core/Volo/Abp/AbpApplicationBase.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Application is shutting down...
`

**Comment by bmzhe** [comment]
step 1. pull the last code source.
step 2. run docker-compose -f ... build
step 3. run docker-compose -f ... run restore-database
step 4. run docker-compose -f ... up

view log：docker logs -f microservicedemo_backend-admin-app_1
