### ISSUE TITLE
Unable to Create New Project ( #2364 )

### ISSUE THREAD

**Issue by aliahmedaspose** [abpframework/abp#9368]
I am unable to create a new project. I tried it with the DIRECT DOWNLOAD method and site is throwing Internal Server Error 500. Please see the attached screenshot. 
![Screenshot_208](https://user-images.githubusercontent.com/18484776/122430254-e0eec100-cfac-11eb-8e76-9446e48cd960.png)

I also tried it with the CLI method. I am getting the following error while doing it. 

Error occured while downloading source-code from https://abp.io/api/download/template/ : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Thu, 17 Jun 2021 15:35:09 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-store, no-cache
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfDJ8MlWsm75C4ZFp4VKTshpYKW16VRP47zZOnXkvD7zjV-AyFgzT4-A6dkJamUgCen30cSKVmfLydCAdXgO8PPJdLu836RM7Dnpw7j0ppuvywcXfqlv_fosFAcA0mBkBGuID5QCf5Z9zb9_v4JRZ_37cE8; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8MlWsm75C4ZFp4VKTshpYKU4-Fk5S5CGd11UbsSApkPChd8o6GG5HC7ayEg1g2_8PvFeW3WO_i3RLoLKNUSpbRmpQDqkYx_pLcpriwwL6hgl62NvjJakeMkMXzL3wk7b1pAIR0A1SKL8phQFyghDm5s; expires=Sun, 15 Jun 2031 15:35:09 GMT; path=/; samesite=none
  X-Frame-Options: SAMEORIGIN
  X-Powered-By: ARR/3.0
  X-Powered-By: ASP.NET
  CF-Cache-Status: DYNAMIC
  cf-request-id: 0abc35b29d0000ca786eb57000000001
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=iXLv94%2BXa68YiKCuIs%2Fb%2BT%2F1p%2B5MfhXABr3YlEK0GTwVI5CgAJhz0WxGONBH9tvsHCpvlCK0akc7HMz%2BtoqbLSRdiU2rGXLpyDNblGTHJfc4xQw%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 660d58976d56ca78-LHE
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[20:35:09 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializerProvider.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\SystemTextJson\AbpSystemTextJsonSerializerProvider.cs:line 34
   at Volo.Abp.Json.AbpHybridJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\AbpHybridJsonSerializer.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 220
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 112
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 56
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 192
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by aliahmedaspose** [comment]
Similar issue was reported here #2364  : https://github.com/abpframework/abp/issues/2364

**Comment by mrcarl79** [comment]
Same error on the website for me also.

**Comment by ebicoglu** [comment]
the release is still in progress, I'll notify you once we complete the release.

**Comment by ebicoglu** [comment]
you can download now

**Comment by mugambiwarwema** [comment]
Thanks, now it's working...

**Comment by DanzigGLT** [comment]
👍

**Comment by aliahmedaspose** [comment]
Thanks. It's working now.

**Comment by silambarasan-ilango** [comment]
Same issue throws from ABP CLI : 7.3.1

![image](https://github.com/abpframework/abp/assets/28433279/84c3c830-0638-468c-a363-7c1be40de83e)

**Comment by lethienbao99** [comment]
Same issue throws from ABP CLI : 7.3.1 with me, How do fix it?

**Comment by Navagashan** [comment]
I am also facing the same issue from ABP CLI:7.3.1. could you please help to resolve this?

![ABP Error](https://github.com/abpframework/abp/assets/140782290/73d1ce55-1808-497f-8854-e4ed337d0897)
