### ISSUE TITLE
Subdomain Tenant Resolver does't work fine with angular ui

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#9376]
* Your **ABP Framework version**.
4.3.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Angular
* Your database provider(EF Core/MongoDB)
EF Core 
* Steps needed to **reproduce** the problem.

create a app by `abp new teanatdemo -t app -u angular`

1. Just follow Abp Docs in [Multi-Tenancy](https://docs.abp.io/en/abp/latest/Multi-Tenancy) and [Multi-Tenancy in Angular UI](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/docs/en/UI/Angular/Multi-Tenancy.md)
```csharp
            if (!hostingEnvironment.IsDevelopment())
            {
                Configure<AbpTenantResolveOptions>(options =>
                {
                    options.AddDomainTenantResolver("{0}.demo.furthersoftware.com.tw");
                });
            }
```
```javascript
import { Environment } from '@abp/ng.core';

export const environment = {
  production: true,
  application: {
    baseUrl:'http://{0}.demo.furthersoftware.com.tw',
    name: 'tenantdemo',
  },
  oAuthConfig: {
    issuer: 'http://{0}.demo.furthersoftware.com.tw',
    tokenEndpoint:'http://{0}.demo.furthersoftware.com.tw',
    requireHttps:false,
    redirectUri: 'http://{0}.demo.furthersoftware.com.tw',
    clientId: 'tenantdemo_App',
    responseType: 'password',
    scope: 'offline_access tenantdemo',
  },
  apis: {
    default: {
      url: 'http://{0}.demo.furthersoftware.com.tw',
    },
  },
} as Environment;

```
2.Build `angular` app and `HttpApi.Host` , deploy to `IIS`
3.Create a new tenant 'test'
4.Log in with http://test.demo.furthersoftware.com.tw/ and got token successfully
![image](https://user-images.githubusercontent.com/16490084/122638413-8bd6ba80-d126-11eb-902b-f742288f99e5.png)
5.But when angular call api  with this token ,backend will return not authenticated
![image](https://user-images.githubusercontent.com/16490084/122638507-00a9f480-d127-11eb-89e0-04da238012ea.png)
![image](https://user-images.githubusercontent.com/16490084/122638515-10c1d400-d127-11eb-9212-950ff7411065.png)

I don't know is  this issue same with #2438. Could you check it pls ?thanks

**Comment by yinchang0626** [comment]
I think maybe related with Issuser:
```text
2021-06-20 21:43:14.819 +08:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'System.String'. Did not match: validationParameters.ValidIssuer: 'System.String' or validationParameters.ValidIssuers: 'System.String'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateIssuer(String issuer, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2021-06-20 21:43:14.819 +08:00 [INF] Bearer was not authenticated. Failure message: IDX10205: Issuer validation failed. Issuer: 'System.String'. Did not match: validationParameters.ValidIssuer: 'System.String' or validationParameters.ValidIssuers: 'System.String'.
```

**Comment by yinchang0626** [comment]
@maliming :
 I found the solution at your [sample](https://github.com/abpframework/abp-samples/blob/master/DomainTenantResolver/NG/angular/src/environments/environment.ts),Thank you.
1.angular environment.ts 
```javascript
import { Environment } from '@abp/ng.core';

const baseUrl = 'https://{0}.ng.getabp.net:4200';

export const environment = {
  production: false,
  application: {
    baseUrl,
    name: 'BookStore',
    logoUrl: '',
  },
  oAuthConfig: {
    issuer: 'https://{0}.api.getabp.net:44301',
    redirectUri: baseUrl,
    clientId: 'BookStore_App',
    skipIssuerCheck: true,
    responseType: 'code',
    scope: 'offline_access openid profile role email phone BookStore',
  },
  apis: {
    default: {
      url: 'https://{0}.api.getabp.net:44301',
      rootNamespace: 'BookStore',
    },
  },
} as Environment
```
2.aspnet-core appsettings.json
``` json
{
  "App": {
    "SelfUrl": "https://api.getabp.net:44301",
    "CorsOrigins": "https://*.ng.getabp.net:4200,https://ng.getabp.net:4200/"
  },
  "ConnectionStrings": {
    "Default": "Server=(LocalDb)\\MSSQLLocalDB;Database=BookStore_NG;Trusted_Connection=True"
  },
  "AuthServer": {
    "Authority": "https://api.getabp.net:44301",
    "RequireHttpsMetadata": "false",
    "SwaggerClientId": "BookStore_Swagger",
    "SwaggerClientSecret": "1q2w3e*"
  },
  "StringEncryption": {
    "DefaultPassPhrase": "wehMovc9vVyTBL9z"
  }
}
```
```csharp
	     Configure<AbpTenantResolveOptions>(options =>
            {
                options.AddDomainTenantResolver("{0}.api.getabp.net:44301");
            });

            Configure<IdentityServerOptions>(options =>
            {
                options.IssuerUri = configuration["App:SelfUrl"];
            });
```

**Comment by ChangYinShung** [comment]
Dotnet forget to add  those service in ConfigureServices

``` csharp
context.Services.AddAbpStrictRedirectUriValidator();
context.Services.AddAbpClientConfigurationValidator();
context.Services.AddAbpWildcardSubdomainCorsPolicyService();
```
