### ISSUE TITLE
Tenant Not Found Error (Http 500)

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#9417]
4.3.3
Blazor Server (Not Tired)
Mongo DB

Scenario, create tenant with name is X (seed data) after login with this tenant, close windows. Delete database, create database and create tenant with name is X (seed data). After open browser. It will throw http 500 error. Its try to find tenant from previous token. Instead of throw error its should ignore it..

Error log:

2021-06-23 13:06:24.653 +03:00 [ERR] An unhandled exception has occurred while executing the request.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.MultiTenancy.TenantConfigurationProvider.GetAsync(Boolean saveResolveResult)
   at Volo.Abp.Account.Public.Web.ExternalProviders.AccountExternalProviderOptionsManager`1.OverrideOptionsAsync(String name, TOptions options)
   at Volo.Abp.Account.Public.Web.ExternalProviders.AbpAccountAuthenticationRequestHandler`2.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at IdentityServer4.Hosting.FederatedSignOut.FederatedSignoutAuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-06-23 13:06:24.663 +03:00 [ERR] An exception was thrown attempting to execute the error handler.
Volo.Abp.BusinessException: Tenant not found!
   at Volo.Abp.MultiTenancy.TenantConfigurationProvider.GetAsync(Boolean saveResolveResult)
   at Volo.Abp.Account.Public.Web.ExternalProviders.AccountExternalProviderOptionsManager`1.OverrideOptionsAsync(String name, TOptions options)
   at Volo.Abp.Account.Public.Web.ExternalProviders.AbpAccountAuthenticationRequestHandler`2.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at IdentityServer4.Hosting.FederatedSignOut.FederatedSignoutAuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2021-06-23 13:06:24.669 +03:00 [ERR] Connection ID "17365880242060657035", Request ID "8000018c-0012-f100-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Volo.Abp.BusinessException: Tenant not found!

**Comment by Coolioyang** [comment]
Yes, Same problem as mine.
Currently,  my workaround (not best solution) is to clear the old data of cookies and localStorage when App booting. By the way, I use Angular SPA

in main.ts:
```ts
platformBrowserDynamic()
  .bootstrapModule(AppModule, {
    defaultEncapsulation: ViewEncapsulation.Emulated,
    preserveWhitespaces: false,
  })
  .then((res) => {
    const win = window as NzSafeAny;
    if (win && win.appBootstrap) {
      win.appBootstrap();
    }
    return res;
  })
  .catch((err) => {
    if (err instanceof HttpErrorResponse) {
      let errMsg = err.error as string;
      if (errMsg.indexOf('Tenant not found!')) {    //catch tenant not foud error here. not best way.
        //window.location.href = environment.oAuthConfig.issuer + '/account/logout';
        document.cookie = '__tenant=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
        localStorage.removeItem('abpSession');
        window.alert(`The server data has changed and the web page needs to be reloaded.`);
        window.location.reload();  
      }
    }
  });
```

**Comment by realLiangshiwei** [comment]
There is no problem throw an exception when the tenant does not exist.

You can replace the `ITenantConfigurationProvider` for your case.

**Comment by muratyuceer** [comment]
Okey,  for some reason i deleted my tenant and create with same name (he was login before) but because of this problem he cant open site, he must clear cookies
