### ISSUE TITLE
abp cli error

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#9458]
C:\Users\gerry_ge>abp get-source Volo.Blogging
[12:10:33 INF] ABP CLI (https://abp.io)
[12:10:33 INF] Version 4.4.0-rc.1 (Prerelease)
[12:10:36 INF] Output folder: C:\Users\gerry_ge
[12:10:36 INF] Downloading source code of Volo.Blogging
[12:10:36 INF] Version:
[12:10:36 INF] Output folder: C:\Users\gerry_ge
[12:10:38 INF] Using cached module: Volo.Blogging, version: 4.3.3
[12:10:39 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.CreateAppSettingsSecretsStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\CreateAppSettingsSecretsStep.cs:line 15
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.ModuleProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ModuleProjectBuilder.cs:line 76
   at Volo.Abp.Cli.Commands.Services.SourceCodeDownloadService.DownloadModuleAsync(String moduleName, String outputFolder, String version, String gitHubAbpLocalRepositoryPath, String gitHubVoloLocalRepositoryPath, AbpCommandLineOptions options) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\Services\SourceCodeDownloadService.cs:line 40
   at Volo.Abp.Cli.Commands.GetSourceCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\GetSourceCommand.cs:line 62
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 158
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 66

![image](https://user-images.githubusercontent.com/6952917/123900763-432bc680-d99c-11eb-86ba-0d3f543c858a.png)

![image](https://user-images.githubusercontent.com/6952917/123900814-59398700-d99c-11eb-8e3b-d79673ed361e.png)

**Comment by mugambiwarwema** [comment]
@maliming  This issue has occurred again just now. Is there a workaround?

**Comment by maliming** [comment]
hi

We are releasing the new rc version. You can try again later.

**Comment by XP-HKhalFaoui** [comment]
HI
Is there a solution? , it's still the same problem.

**Comment by XP-HKhalFaoui** [comment]
![image](https://user-images.githubusercontent.com/93482580/218785367-a997ffc3-d1f7-4991-9332-cc56af3ee8f9.png)

**Comment by maliming** [comment]
Please update your cli to latest
