### ISSUE TITLE
Error 500 creating new pre-release project

### ISSUE THREAD

**Issue by cld0815** [abpframework/abp#9574]
Create new project form the Getting Started page

Project name: Testing
Project type: Application
UI Framework: Blazor Server
Database Provider: Entity Framework Core
Database management system: **PostgreSQL**

Select "Uses latest pre-release version (4.4.0-rc.2)."

![image](https://user-images.githubusercontent.com/30192550/125289239-9c5b0900-e351-11eb-9931-83ce6bb650af.png)

**Comment by cld0815** [comment]
PS C:\Windows\system32> abp new test --ui blazor-server -dbms postgresql  --no-random-port --preview
[20:47:11 INF] ABP CLI (https://abp.io)
[20:47:12 INF] Version 4.4.0-rc.2 (Prerelease)
[20:47:13 INF] Creating your project...
[20:47:13 INF] Project name: test
[20:47:13 INF] Preview: yes
[20:47:13 INF] DBMS: PostgreSQL
[20:47:13 INF] UI Framework: BlazorServer
[20:47:13 INF] Output folder: C:\Windows\system32
[20:47:16 INF] Using cached template: app, version: 4.4.0-rc.2
[20:47:17 ERR] Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.DatabaseManagementSystemChangeStep.ChangeUseSqlServer(ProjectBuildContext context, String newUseMethodForEfModule, String newUseMethodForDbContext) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\DatabaseManagementSystemChangeStep.cs:line 104
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.DatabaseManagementSystemChangeStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\DatabaseManagementSystemChangeStep.cs:line 33
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 120
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 197
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 158
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 66

**Comment by EngincanV** [comment]
Hi @cld0815, I've tried to download a new startup template with v4.4.0-rc.2 (pre-release) and I've successfully able to do that. It could be a temporary problem, can you try to create a new project again?

**Comment by maliming** [comment]
Related https://github.com/abpframework/abp/pull/9563

**Comment by cld0815** [comment]
@EngincanV Creating a template with the default configuration is fine, but this error occurs when using **PostgreSQL** database
