### ISSUE TITLE
ABP CLI: Unable to download old version of template

### ISSUE THREAD

**Issue by safi-huss** [abpframework/abp#9610]
Referencing the closed issue below
ABP CLI: Unable to download old version of template #7356

I am trying to create a version of the template project supporting .NET Core 3.1 (because of my target deployment environment). I am using the CLI new command in the following manner:

`abp new BookStore -t app -v 3.3.0`

OR

`abp new BookStore -v 3.3.0`

I receive the following output:

```
[22:51:02 INF] ABP CLI (https://abp.io)
[22:51:02 INF] Version 4.3.3 (Stable)
[22:51:04 INF] Creating your project...
[22:51:04 INF] Project name: BookStore
[22:51:04 INF] Template: app
[22:51:04 INF] Version: 3.3.0
[22:51:04 INF] Output folder: E:\Users\safiu\source\repos\testabp
[22:51:05 INF] Downloading template: app, version: 3.3.0
Error occured while downloading source-code from https://abp.io/api/download/template/ : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Fri, 16 Jul 2021 17:51:07 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-store, no-cache
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfDJ8MlWsm75C4ZFp4VKTshpYKU1ZY6TWO6aIIFSTagIe7FEZOfA8NQ7wKW6jDASYakl9vm3ZvfQkxKImq3qNnNZvf6FizHQOzNFIhevbGx5jWQljx_SV96qyfC8m8yTZZ_mlwnpPcHlYqkH-SywtzBtLCk; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8MlWsm75C4ZFp4VKTshpYKVF1_jBdyDdll_qc2mVTtR_7z6Sr4Vyfx6W2qNKiaoVdg3Bwgh_IW1hC4fhlrLVVokkrbBE36ryTXAgDASb0ZfP-f3xddunXvQueWSv6ct-sjz5TLG_RYbXQGgJNb-fHyU; expires=Mon, 14 Jul 2031 17:51:07 GMT; path=/; samesite=none
  X-Frame-Options: SAMEORIGIN
  X-Powered-By: ARR/3.0
  X-Powered-By: ASP.NET
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=kzBNEad6iOfGaK9eMK7TJ4tL6J6K6BhqbxhkfgGkNeMnMVBjT8l7qJbj%2FXh0cKxJTuusmqeUrtDzGW39WcGT0MZYnD1%2FNUbdgE%2FgWCNlDrgl32b1JIMDlg%3D%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 66fd13a10d571744-SIN
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[22:51:07 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializerProvider.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\SystemTextJson\AbpSystemTextJsonSerializerProvider.cs:line 34
   at Volo.Abp.Json.AbpHybridJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\AbpHybridJsonSerializer.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 220
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 112
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 56
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 192
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59`

```

**Comment by ismcagdas** [comment]
@safi-huss could you try again ? It should work now.

**Comment by realLiangshiwei** [comment]
It works fine.

![image](https://user-images.githubusercontent.com/16813853/126417303-5fe15d7a-f341-489d-8e3d-d6e81b3dd0dc.png)

**Comment by safi-huss** [comment]
Yup, works! Thanks!
