### ISSUE TITLE
Volo.Abp.Autofac.AbpAutofacConstructorFinder - Breaking change?

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#9659]
I have a Blazor WASM Project that once upgraded to Version="4.4.0-rc.2" throws these AutoFac error

Is there a work-around for this?

Thanks,

John

**Error**
None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Castle.Proxies.GenderAppServiceProxy' can be invoked with the available services and parameters

 **Sample App Service**
```

using Gp.Entities;
using Gp.Genders;
using Gp.Permissions;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using Gp.IRepositories;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Data;
using Volo.Abp.Domain.Repositories;

namespace Gp.AppServices
{
    [Authorize(GpPermissions.Genders.Default)]
    public class GenderAppService : CrudAppService<Gender, GenderDto, Guid, PagedAndSortedResultRequestDto, CreateUpdateGenderDto>, IGenderAppService
    {
        private readonly IGenderRepository _genderRepository;
        
      
        public GenderAppService(IRepository<Gender, Guid> repository, IGenderRepository genderRepository) : base(repository)
        {
            _genderRepository = genderRepository;
        }


        public async Task<PagedResultDto<GenderLookupDto>> GetLookUpListAsync(PagedAndSortedResultRequestDto input)
        {
            var readOnlyCollection = new ReadOnlyCollection<GenderLookupDto>(ObjectMapper.Map<IList<Gender>, IList<GenderLookupDto>>(await _genderRepository.GetLookupListAsync()));

            return new PagedResultDto<GenderLookupDto>(readOnlyCollection.Count, readOnlyCollection);

        }
    }
}

```

**Error Log**

```
2021-07-27 14:59:14.630 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.GenderAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.GenderAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Castle.Proxies.GenderAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Gp.IRepositories.IGenderRepository genderRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Domain.Repositories.IRepository`2[Gp.Entities.Gender,System.Guid], Gp.IRepositories.IGenderRepository)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

```

**Comment by enisn** [comment]
It seems, can't resolve `IGenderRepository`, have you registered it?

**Comment by 274188A** [comment]
Checking now...

**Comment by 274188A** [comment]
I have not had to manually do that before - I am following the same pattern as found in the sample: https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore


![image](https://user-images.githubusercontent.com/40014477/127114745-1f6fd615-c236-4d04-a31c-3489cbd74b6d.png)

**Comment by 274188A** [comment]
I found there was an issue with my folder structure - closing
