### ISSUE TITLE
how to save after response

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#9660]
```
public void CreateLoginRecord(LoginRecord info)
        {
            Task.Factory.StartNew(async () =>
            {
                using (var uow = _unitOfWorkManager.Begin(requiresNew: true, isTransactional: false))
                {
                    try
                    {
                        if (info.TerminalNo.IsNullOrWhiteSpace()) info.SetTerminalNo("0");
                        var data = await _loginRep.FindAsync(p => p.LoginNo.Equals(info.LoginNo) && p.TerminalNo.Equals(info.TerminalNo));
                        if (data == null)
                        {
                            info.SetLoginTime();
                            await _loginRep.InsertAsync(info);
                        }
                        else
                        {
                            data.SetLoginTime();
                            await _loginRep.UpdateAsync(data);
                        }
                        await uow.SaveChangesAsync();
                        await uow.CompleteAsync();
                    }
                    catch (Exception ex)
                    {
                        await uow.RollbackAsync();
                    }
                }
            });
        }
```
throw a exception :Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

**Comment by berkansasmaz** [comment]
Could you share the following information with us so that we can respond faster?

- Your ABP Framework version.
- Stack trace (check the logs).

**Comment by wingqing1314** [comment]
> Could you share the following information with us so that we can respond faster?
> 
> * Your ABP Framework version.
> * Stack trace (check the logs).

ABP 2.7.0
```
09:57:47.747 [ERR] Microsoft.EntityFrameworkCore.Database.Command
Failed executing DbCommand ("0"ms) [Parameters=["@__info_LoginNo_0='?' (Size = 11), @__info_TerminalNo_1='?' (Size = 11)"], CommandType='Text', CommandTimeout='60']"\n""SELECT `u`.`id`, `u`.`concurrency_stamp`, `u`.`extra_properties`, `u`.`login_no`, `u`.`login_time`, `u`.`login_type`, `u`.`logout_time`, `u`.`terminal_no`\nFROM `us_login_record` AS `u`\nWHERE (`u`.`login_no` = @__info_LoginNo_0) AND (`u`.`terminal_no` = @__info_TerminalNo_1)\nLIMIT 2"
09:57:47.748 [ERR] Microsoft.EntityFrameworkCore.Query
An exception occurred while iterating over the results of a query for context type '"Sino.User.EntityFrameworkCore.UserDbContext"'."\n""System.ObjectDisposedException: Cannot access a disposed object.\nObject name: 'MySqlConnection'.\n   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlConnection.cs:line 707\n   at MySql.Data.MySqlClient.MySqlConnection.get_Session() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlConnection.cs:line 480\n   at MySqlConnector.Core.ICancellableCommandExtensions.ResetCommandTimeout(ICancellableCommand command) in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\Core\\ICancellableCommand.cs:line 42\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlCommand.cs:line 261\n   at System.Data.Common.DbCommand.ExecuteReaderAsync(CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\n   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()"
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlConnection'.
   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 707
   at MySql.Data.MySqlClient.MySqlConnection.get_Session() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 480
   at MySqlConnector.Core.ICancellableCommandExtensions.ResetCommandTimeout(ICancellableCommand command) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ICancellableCommand.cs:line 42
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReaderAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```
Thank you

**Comment by wingqing1314** [comment]
I have solved it by event bus，inject a DBContext in there.

But I wonder if this requirement can be implemented at the domain?

**Comment by berkansasmaz** [comment]
In my opinion, you shouldn't do that. I tried to reproduce to solve your error but I couldn't reproduce the error. Please can you try[ your code in the template project and share it](https://stackoverflow.com/help/minimal-reproducible-example)?

You can also check [here](https://github.com/abpframework/abp/issues/2603)

**Comment by wingqing1314** [comment]
> In my opinion, you shouldn't do that. I tried to reproduce to solve your error but I couldn't reproduce the error. Please can you try[ your code in the template project and share it](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> You can also check [here](https://github.com/abpframework/abp/issues/2603)

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Uow;


namespace Sino.User
{
    public class TestAppService : ApplicationService
    {
        private readonly IRepository<LoginRecord, int> _rep;

        public TestAppService(
            IRepository<LoginRecord, int> rep
            )
        {
            _rep = rep;
        }

        public async Task<int> CreateAsync()
        {
            var t = Task.Factory.StartNew(async () =>
              {
                  using (var uow = UnitOfWorkManager.Begin(requiresNew: true, isTransactional: false))
                  {
                      try
                      {
                          Thread.Sleep(5000);
                          await _rep.InsertAsync(new LoginRecord("111", LoginType.AdminWeb));

                          await uow.SaveChangesAsync();
                          await uow.CompleteAsync();
                          Console.WriteLine("Insert#####################");
                      }
                      catch (Exception ex)
                      {
                          await uow.RollbackAsync();
                      }
                  }
              });
            await _rep.InsertAsync(new LoginRecord("222", LoginType.AdminWeb));
            Console.WriteLine("End#####################");
            return 0;
        }
    }
}
```
Just add this AppService and try it out, replace LoginRecord with your AggregateRoot.

**Comment by berkansasmaz** [comment]
Unfortunately, I still haven't been able to reproduce the error. Here are my steps:

1. `abp new Test -v 2.7.0` (my database provider `MsSQL`)
2. I created the necessary entities
3. I created the `ApplicationService` you said as in the picture below

<img width="928" alt="Screen Shot 2021-07-29 at 11 27 38" src="https://user-images.githubusercontent.com/31216880/127459244-497acfb0-0881-4416-959c-d2056bfcd7c1.png">


When I tested it via Swagger, I observed that the records were added successfully.

**Comment by maliming** [comment]
Please create a separate DI scope in the thread.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkManager.cs#L105-L128

**Comment by wingqing1314** [comment]
> Please create a separate DI scope in the thread.
> 
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkManager.cs#L105-L128

The perfect solution  ,but I don't understand what's the difference here:

create a separate DI scope & use UnitOfWorkManager.Begin(requiresNew: true, isTransactional: false) function

The code is basically the same
