### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException: 'Invalid object name 'dbo.AppBooks'.'

### ISSUE THREAD

**Issue by msh2050** [abpframework/abp#9766]
ABP Framework version:  4.4
User Interface: blazor
database provider:EF Core

Exception message:
```
ERR] Failed executing DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT_BIG(*)
FROM [dbo].[AppBooks] AS [a]
[16:27:52 ERR] An exception occurred while iterating over the results of a query for context type 'Acme.BookStore.EntityFrameworkCore.BookStoreDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.AppBooks'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:38b1fccc-f7f5-43d5-8ea0-f88c4c0faad9
Error Number:208,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.AppBooks'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
ClientConnectionId:38b1fccc-f7f5-43d5-8ea0-f88c4c0faad9
Error Number:208,State:1,Class:16`
```

* Steps needed to **reproduce** the problem.
just following the tutorial of the book store (ef with blazer UI without Tiered 
after adding book entity and seeder the DbContext .... dotnet ef migrations add Created_Book_Entity ... then add seeder

the error will happen when I try to run (Acme.BookStore.DbMigrator)

**Comment by msh2050** [comment]
![devenv_z71T4K2tmB](https://user-images.githubusercontent.com/9201213/128523850-5ec9e7ee-849c-4481-b57a-de2669199090.png)

**Comment by maliming** [comment]
Please share a project. Thanks

**Comment by msh2050** [comment]
[the project](https://github.com/msh2050/Acme.BookStore) link.
 @maliming thanks in advance

**Comment by msh2050** [comment]
![Screenshot 2021-08-06 191102](https://user-images.githubusercontent.com/9201213/128540189-085aceeb-1815-48ea-bdf4-70ba8ee21a8f.png)

I think the error in the migration step (dotnet ef migrations add Created_Book_Entity
)
it great a file but with no code

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/128584388-28e063ba-37a5-4d6f-a9bd-011290e13f38.png)

**Comment by msh2050** [comment]
can you run Acme.BookStore.DbMigrator?!
