### ISSUE TITLE
This resource is already added before: Volo.Abp.Timing.Localization.Resources.AbpTiming.AbpTimingResource,

### ISSUE THREAD

**Issue by muzizongheng** [abpframework/abp#9776]
**ABP Framework version** : Version=4.1.0.0
**User Interface** : console
* Exception message and **stack trace** : 
>This resource is already added before: Volo.Abp.Timing.Localization.Resources.AbpTiming.AbpTimingResource, Volo.Abp.Timing, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null

>Autofac.Core.DependencyResolutionException: 'An exception was thrown while activating Castle.Proxies.XXXXLocalEventHandleProxy -> MyCompany.MyDomainService -> Microsoft.Extensions.Localization.StringLocalizer`1[[MyCompany.Localization.MyResource, MyCompany.Domain.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Localization.AbpStringLocalizerFactory.'

* Steps to **reproduce** the problem.
1. create a console used by abp cli
2. create a asp.net mvc core ddd project used by abp cli
3. add dependencies by  ddd project of step 2, like ApplicationService.Contract、EFCore。
4.  use localEventBus to notify 
5. start console of step 1  , not HttpApi.Host program.
6.  Find XXXDomainSharedModule run 2 times AddResource code.
>     options.Resources .Add<MyResource>("en")
first： xxxAbpModule's ConfigureServices
second: _localEventBus.PublishAsync();
6. it throws a exception ： 
```Csharp
 public LocalizationResource Add(Type resourceType, [CanBeNull] string defaultCultureName = null)
        {
            if (ContainsKey(resourceType))
            {
                throw new AbpException("This resource is already added before: " + resourceType.AssemblyQualifiedName);
            }

            return this[resourceType] = new LocalizationResource(resourceType, defaultCultureName);
        }

```

**Comment by maliming** [comment]
Please share the applications that your mentions.

**Comment by muzizongheng** [comment]
**InnerException**

Message: 
```charp
This resource is already added before: Volo.Abp.Timing.Localization.Resources.AbpTiming.AbpTimingResource, Volo.Abp.Timing, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null
```
StackTrace:

```Csharp
   at Volo.Abp.Localization.LocalizationResourceDictionary.Add(Type resourceType, String defaultCultureName)
   at Volo.Abp.Localization.LocalizationResourceDictionary.Add[TResouce](String defaultCultureName)
   at Volo.Abp.Timing.AbpTimingModule.<>c.<ConfigureServices>b__0_1(AbpLocalizationOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Volo.Abp.Localization.AbpStringLocalizerFactory..ctor(ResourceManagerStringLocalizerFactory innerFactory, IOptions`1 abpLocalizationOptions, IServiceProvider serviceProvider)
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
```

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/9776#issuecomment-895057018

**Comment by muzizongheng** [comment]
**TopLayer Exception**
Message:
```csharp
An exception was thrown while activating Castle.Proxies.XXXXLocalEventHandleProxy -> MyCompany.MyDomainService -> Microsoft.Extensions.Localization.StringLocalizer`1[[MyCompany.Localization.MyResource, MyCompany.Domain.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Localization.AbpStringLocalizerFactory.'
```

StackTrace:
```csharp
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass35_0.<OnPreparing>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CoreEventMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Volo.Abp.EventBus.IocEventHandlerFactory.GetHandler()
   at Volo.Abp.EventBus.EventBusBase.<TriggerHandlerAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Volo.Abp.EventBus.EventBusBase.<TriggerHandlersAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.EventBus.Local.LocalEventBus.<PublishAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ```

**Comment by muzizongheng** [comment]
> [#9776 (comment)](https://github.com/abpframework/abp/issues/9776#issuecomment-895057018)

I will create a simple reproduce demo. Currently code env is very complex.
