### ISSUE TITLE
Unable to run Samples

### ISSUE THREAD

**Issue by sudhashbahu** [abpframework/abp#9816]
Downloaded Samples code as ZIP from https://github.com/abpframework/abp-samples

After Unzip, opened DashboardDemo.sln.

Set the Web project as Startup and ran it.

Exception thrown in ConfigureVirtualFileSystem method of DashboardDemoWebModule.cs as per details below.

if the Samples require some kind of setup/configuration to run, it is not properly documented.

System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=C:\Users\ada-258\Downloads\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared\
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Volo.Abp.VirtualFileSystem.VirtualFileSetListExtensions.ReplaceEmbeddedByPhysical[T](VirtualFileSetList fileSets, String physicalPath)
   at DashboardDemo.Web.DashboardDemoWebModule.<>c__DisplayClass5_0.<ConfigureVirtualFileSystem>b__0(AbpVirtualFileSystemOptions options) in C:\Users\ada-258\Downloads\abp-samples-master\DashboardDemo\src\DashboardDemo.Web\DashboardDemoWebModule.cs:line 120
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp-samples/pull/101

**Comment by sudhashbahu** [comment]
Thank you for the prompt fix
