### ISSUE TITLE
Cannot update a nullable ExtraProperty back to null

### ISSUE THREAD

**Issue by jeroen-min** [abpframework/abp#9847]
ABP Framework version  4.4.0 (Commercial)
Angular / EF Core

After following the steps in the [Removing the EF Core Migrations Project](https://community.abp.io/articles/unifying-dbcontexts-for-ef-core-removing-the-ef-core-migrations-project-nsyhrtna) i wanted to add a nullable property (int) to the `IdentityUser`: SurveyorNumber  
The steps provided in the documentation worked like a charm, however, when i want to set the property back to null, i get an error. It only happens when i want to remove a previously added value.

    System.FormatException: Input string was not in a correct format.
       at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
       at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
       at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
       at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
       at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.HandleExtraPropertiesOnSave(EntityEntry entry)
       at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ApplyAbpConcepts(EntityEntry entry, EntityChangeReport changeReport)
       at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ApplyAbpConcepts()
       at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.UpdateAsync(TEntity entity, Boolean autoSave, CancellationToken cancellationToken)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Volo.Abp.Identity.IdentityUserStore.UpdateAsync(IdentityUser user, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Volo.Abp.Identity.IdentityUserAppService.UpdateAsync(Guid id, IdentityUserUpdateDto input)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
       at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
       at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
       at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
       at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
       at lambda_method4102(Closure , Object )
       at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

This is the object that is being sent to the backend:

    {
    "tenantId": null,
    "userName": "Username",
    "email": "User@name.nl",
    "name": "User name",
    "surname": null,
    "emailConfirmed": false,
    "phoneNumber": null,
    "phoneNumberConfirmed": false,
    "supportTwoFactor": true,
    "lockoutEnabled": true,
    "isLockedOut": false,
    "concurrencyStamp": "4b3934ed6a874940b1399cbe4e01a305",
    "extraProperties": {
        "SurveyorNumber": "" 
        },
    "roleNames": ["Administrator", "Employee"],
    "organizationUnitIds": []
    }

**Comment by maliming** [comment]
Please share your code to **reproduce** the problem.

**Comment by jeroen-min** [comment]
Not sure what you need, but these are the relevant changes. I created a fresh solution. The error occured there aswell. One thing i didnt mention in the opening post. I am saving the value to its own column in the DB instead of the ExtraProperties column.

In `...ModuleExtensionConfigurator.cs`:  

    private static void ConfigureExtraProperties()
    {
        /* You can configure extra properties for the
            * entities defined in the modules used by your application.
            *
            * This class can be used to define these extra properties
            * with a high level, easy to use API.
            *
            * Example: Add a new property to the user entity of the identity module */
    
            ObjectExtensionManager.Instance.Modules()
                .ConfigureIdentity(identity =>
                {
                    identity.ConfigureUser(user =>
                    {
                        user.AddOrUpdateProperty<int?>(nameof(IEmployee.SurveyorNumber),
                            property =>
                            {
                                property.UI.OnTable.IsVisible = false;
                            }
                        );
                    });
                });
    
            /* See the documentation for more:
            * https://docs.abp.io/en/abp/latest/Module-Entity-Extensions
            */
    }

in `...EfCoreEntityExtensionMappings,cs`

    public static void Configure()
    {
        ExtraPropertiesGlobalFeatureConfigurator.Configure();
        ExtraPropertiesModuleExtensionConfigurator.Configure();
    
        OneTimeRunner.Run(() =>
        {
            /* You can configure extra properties for the
                * entities defined in the modules used by your application.
                *
                * This class can be used to map these extra properties to table fields in the database.
                *
                * USE THIS CLASS ONLY TO CONFIGURE EF CORE RELATED MAPPING.
                * USE ExtraPropertiesModuleExtensionConfigurator CLASS (in the Domain.Shared project)
                * FOR A HIGH LEVEL API TO DEFINE EXTRA PROPERTIES TO ENTITIES OF THE USED MODULES
                *
                * Example: Map a property to a table field:*/
    
                    ObjectExtensionManager.Instance
                        .MapEfCoreProperty<IdentityUser, int?>(
                            nameof(IEmployee.SurveyorNumber),
                            (entityBuilder, propertyBuilder) =>
                            {
    
                            }
                        );
    
            /* See the documentation for more:
            * https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities
            */
        });
    }

My IEmployee interface:

    public interface IEmployee
    {
        public int? SurveyorNumber { get; set; }
    }

The migration:

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<int>(
            name: "SurveyorNumber",
            table: "AbpUsers",
            type: "int",
            nullable: true);
    }

Steps to reproduce
* Change the surveyor property to any desired value. And save it:
![image](https://user-images.githubusercontent.com/86959073/129914817-ba4fc8fe-e833-4e05-9832-0fc5c63ac3cb.png)
* Set the value empty:
![image](https://user-images.githubusercontent.com/86959073/129914928-d0f53f5e-c11d-4d37-86e5-e94b7b89942d.png)

**Comment by hitaspdotnet** [comment]
the `""` isn't null. it's empty string, you need to convert that to `null` from client and send back to host.

```json
{
"tenantId": null,
"userName": "Username",
"email": "User@name.nl",
"name": "User name",
"surname": null,
"emailConfirmed": false,
"phoneNumber": null,
"phoneNumberConfirmed": false,
"supportTwoFactor": true,
"lockoutEnabled": true,
"isLockedOut": false,
"concurrencyStamp": "4b3934ed6a874940b1399cbe4e01a305",
"extraProperties": {
    "SurveyorNumber": null <- change ->
    },
"roleNames": ["Administrator", "Employee"],
"organizationUnitIds": []
}

```

**Comment by jeroen-min** [comment]
That should do the trick @hitaspdotnet , however it is generated code, so nothing i can do besides reporting it here.

**Comment by maliming** [comment]
@hitaspdotnet is right, We should use `null` for `SurveyorNumber`.
