### ISSUE TITLE
A DbContext can only be created inside a unit of work

### ISSUE THREAD

**Issue by litiansky** [abpframework/abp#9867]
### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* **ABP Framework version** : 4.4.0.
* **User Interface** : WPF+Stylet
* database provider(EF Core)

**I created a WPF project that referenced the ABP VNEXT framework and used stylet's MVVM framework. When I injected all the dependencies of ABP and injected them into the Stylet framework, the project ran and the appService classes were injected, but the execution of the call to the database method was incorrect**

Example here is a website, I transformed, GlobalVars. ServiceCollection is a global variable, when performing below I deposited in the stylet into use this variable to behind

`private IHost CreateHostBuilder()
        {
            return Host
                .CreateDefaultBuilder(null)
                .UseAutofac()
                .UseSerilog()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddApplication<PharmacyUIModule>();
                    GlobalVars.serviceCollection = services;
                }).Build();
        }`

* Exception message and **stack trace** if available (check the logs).

`
Volo.Abp.AbpException
  HResult=0x80131500
  Message=A DbContext can only be created inside a unit of work!
  Source=Volo.Abp.EntityFrameworkCore
  StackTrace:
   at Volo.Abp.Uow.EntityFrameworkCore.UnitOfWorkDbContextProvider`1.<GetDbContextAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Domain.Repositories.EntityFrameworkCore.EfCoreRepository`2.<GetDbSetAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Volo.Abp.Identity.EntityFrameworkCore.EfCoreIdentityUserRepository.<FindByNormalizedUserNameAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<FindByNameAsync>d__77.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InvoicingSys.Pharmacy.Users.LoginAppService.<Login>d__3.MoveNext() in C:\Development_Avecto\Sky\Work\InvoicingSys.Pharmacy\src\InvoicingSys.Pharmacy.Application\Users\LoginAppService.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InvoicingSys.Pharmacy.UI.Pages.ShellViewModel.<SayHello>d__6.MoveNext() in C:\Development_Avecto\Sky\Work\InvoicingSys.Pharmacy\src\InvoicingSys.Pharmacy.UI\Pages\ShellViewModel.cs:line 24
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stylet.Xaml.ActionBase.<<InvokeTargetMethod>g__AwaitTask|26_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at InvoicingSys.Pharmacy.UI.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
    InvoicingSys.Pharmacy.Users.LoginAppService.Login(string, string) in LoginAppService.cs
    [External Code]
    InvoicingSys.Pharmacy.UI.Pages.ShellViewModel.SayHello() in ShellViewModel.cs
    [External Code]
`

**Comment by JadynWong** [comment]
You need to read the [Unit-Of-Work](https://docs.abp.io/en/abp/latest/Unit-Of-Work#unitofworkattribute) docs.

Try add the `[UnitOfWork]` attribute to the `LoginAppService` and make method as `virtual`.
