### ISSUE TITLE
Dynamic C# API Client Proxies failing.

### ISSUE THREAD

**Issue by agustinsilvano** [abpframework/abp#9923]
## Context
* ABP Version : 4.3.3
* DB Provider : EF Core

## Report
I was trying to use dynamic API client proxies documented [here](https://docs.abp.io/en/abp/4.3/API/Dynamic-CSharp-API-Clients).
I have two solutions: the server solution, and the client solution.

### Server perspective
I've created an _IApplicationService_ (who inherits _IRemoteService_) as shown below:
```C#
namespace Interfaces
{
    public interface IOfficeAppService: IApplicationService
    {
        Task<bool> GetByName(string officeName); 
    }
}
```

And the implementation of this service is:
```C#
namespace Services
{
    public class OfficeAppService: ApplicationService, IOfficeAppService
    {
        private readonly IRepository<Office, Guid> _repository;

        public OfficeAppService(IRepository<Office, Guid> repository)
        {
            _repository = repository;
        }

        public async Task<bool> GetByName(string officeName)
        {
            return await _repository.CountAsync(o => o.Name == officeName)> 0;
        }
    }
}
```

Finally, configure CORS policies to accept client calls.

### Client perspective
I've created an _IApplicationService_ (who inherits _IRemoteService_) as shown below:
```C#
namespace Interfaces.Client
{
    public interface IOfficeAppService: IApplicationService
    {
        Task<bool> GetByName(string officeName); 
    }
}
```
Then, in the Application project, I've installed and added the _AbpHttpClientModule_ as a dependency of the module.
In the _ConfigureServices_ method added:
```C#
context.Services.AddHttpClientProxies(
                typeof(DataScienceApplicationContractsModule).Assembly,
                remoteServiceConfigurationName: "RemoteServiceNameAPI"
            );
```

In the appsettings of the _HttpApi.Host_ project, I've added a section like the following:
```JSON
"RemoteServices": {
    "RemoteServiceNameAPI": {
      "BaseUrl": "https://localhost:44355/"
    }
  }
```

Finally, I've injected the interface reference as usual in the service of the client.
```C#
namespace Services.Client
{
    public class SampleAppService: ApplicationService, ISampleAppService 
    {
        private readonly IRepository<Entity, Guid> _repository;
        private readonly IOfficeAppService  _officeService;

        public SampleAppService (IRepository<VisitData, Guid> repository, IOfficeAppService officeService)
        {
            _repository = repository;
            _officeService = officeService;
        }

        public async Task<bool> DoSomething()
        {
            bool exist = await _officeService.GetByName("LATAM Office");

            return exist ;
        }
    }
}
```

### The Error
When the client calls the remote method the API throws a 500 Internal Server Error. The logs of the solution show:
```log
2021-08-30 12:47:15.395 -03:00 [INF] Request starting HTTP/2 POST https://localhost:44304/api/app/do-something/do-something multipart/form-data;+boundary=----WebKitFormBoundary9bdahcImeJQDtroy 141233
2021-08-30 12:47:15.403 -03:00 [INF] CORS policy execution successful.
2021-08-30 12:47:15.441 -03:00 [INF] Executing endpoint 'Services.DoSomethingAppService.DoSomething (Application)'
2021-08-30 12:47:15.456 -03:00 [INF] Route matched with {action = "DoSomething", controller = "DoSomething", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Boolean] DoSomething() on controller Services.DoSomethingAppService(Application).
2021-08-30 12:47:18.844 -03:00 [INF] Start processing HTTP request GET "https://localhost:44355/api/abp/api-definition"
2021-08-30 12:47:18.845 -03:00 [INF] Sending HTTP request GET "https://localhost:44355/api/abp/api-definition"
2021-08-30 12:47:19.068 -03:00 [INF] Received HTTP response headers after 219.9092ms - 200
2021-08-30 12:47:19.069 -03:00 [INF] End processing HTTP request after 228.0993ms - 200
2021-08-30 12:47:19.376 -03:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

2021-08-30 12:47:19.376 -03:00 [ERR] Could not found remote action for method: System.Threading.Tasks.Task`1[System.Boolean] GetByName(System.String) on the URL: https://localhost:44355/
Volo.Abp.AbpException: Could not found remote action for method: System.Threading.Tasks.Task`1[System.Boolean] GetByName(System.String) on the URL: https://localhost:44355/
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.FindActionAsync(HttpClient client, String baseUrl, Type serviceType, MethodInfo method)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at   Services.DoSomethingAppService.DoSomething(IFormFile file) in XXX\src\Application\Services\DoSomethingAppService.cs:line 34
   at lambda_method1524(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-08-30 12:47:19.382 -03:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2021-08-30 12:47:19.395 -03:00 [INF] Executed action  Services.DoSomethingAppService.DoSomething (Application) in 3939.0113ms
2021-08-30 12:47:19.395 -03:00 [INF] Executed endpoint 'Services.DoSomethingAppService.DoSomething (Application)'
```

And the definition of the API for the desired method is:
```JSON
 "GetByNameByOfficeName": {
                            "uniqueName": "GetByNameByOfficeName",
                            "name": "GetByName",
                            "httpMethod": "GET",
                            "url": "api/app/office/by-name",
                            "supportedVersions": [],
                            "parametersOnMethod": [
                                {
                                    "name": "officeName",
                                    "typeAsString": "System.String, System.Private.CoreLib",
                                    "type": "System.String",
                                    "typeSimple": "string",
                                    "isOptional": false,
                                    "defaultValue": null
                                }
                            ],
                            "parameters": [
                                {
                                    "nameOnMethod": "officeName",
                                    "name": "officeName",
                                    "jsonName": null,
                                    "type": "System.String",
                                    "typeSimple": "string",
                                    "isOptional": false,
                                    "defaultValue": null,
                                    "constraintTypes": null,
                                    "bindingSourceId": "ModelBinding",
                                    "descriptorName": ""
                                }
                            ],
                            "returnValue": {
                                "type": "System.Boolean",
                                "typeSimple": "boolean"
                            }
                        }
```

I've tried removing the Task of the result of the client interface to match directly as bool result but this is incorrect and anyway it fails in the same way.

As I understood, I'm not missing any config from the doc.

Can anyone help me with this issue?

Thanks. 

Agustín.

**Comment by maliming** [comment]
hi

Can you share a project?

**Comment by hitaspdotnet** [comment]
May you have 2 application service in same namespace which isn't accepted.
`DoSomethingAppService.DoSomething(IFormFile file) in XXX\src\Application\Services\DoSomethingAppService.cs:line 34`

**Comment by agustinsilvano** [comment]
@maliming Not this project. But I can build the same structure and config in another and share it with you. Give me some time.

@hitaspdotnet This is a mistake. I was "hiding" sensitive data from the logs and I forgot to delete this parameter. In fact, the real application service receives an IFromFile as a parameter but isn't related to the reported issue. There isn't any conflict name.

**Comment by hitaspdotnet** [comment]
Conflict name is different with what I said, 
If you have a application service (e.x BookApplicationService) in the namespace `MyCompanyName.Namespace.Books` where the service name contain namespace then you cant add another application service `CategoryApplicationService` in that namespace. I don't know this a bug or a framework rule. 

Another suggestion DONOT use IFormFile in application service, give it in Http layer and send bytes to application

**Comment by agustinsilvano** [comment]
I have all the services in the same namespace `Company.Services`. Then, when the services are built, the `Service` at the end of the name has gone and keeps `Books` or `Category` and there isn't a match between the final service name and the namespace name.

This rule/bug is applied before or after of the "Service" removal from the service name?

Thanks for the suggestion, I'll change that.

**Comment by hitaspdotnet** [comment]
I think this is related to your configuration, please share a project. As I see in your log, your request sent to root.
```System.Threading.Tasks.Task`1[System.Boolean] GetByName(System.String) on the URL: https://localhost:44355/``` which must be 
`https://localhost:44355/api/app/office/by-name`.
This is not related to the framework.

**Comment by agustinsilvano** [comment]
Where should the path '/api/app/office/by-name' be defined? I set up the base URL (https://localhost:44355) but I assume that the framework builds the URL with the interface definition. Should I set up the relative path to the endpoint somewhere? As I saw in the doc, isn't needed.

**Comment by agustinsilvano** [comment]
@hitaspdotnet @maliming [here ](https://we.tl/t-rxA7R8k8nZ) is the zip file with the setup that I did for both solutions. I'm facing the same issue that I had reported with the original project with those new projects.

Thanks.

**Comment by maliming** [comment]
Please share the steps to reproduce.

**Comment by agustinsilvano** [comment]
@maliming 

From the server perspective:

1. Create the service and interface inheriting of ApplicationService and IApplicationService.

From the client perspective:

1. Install AbpHttpClientModule
2. Add the interface to the `Application.Contracts` project (`ClientAppApplicationContractsModule` module).
3. Add to the ApplicationModule the settings that the doc says.
```
 context.Services.AddHttpClientProxies(
               typeof(ClientAppApplicationContractsModule).Assembly
           );
``` 
4. Add the config to the `appsettings.json` of the `HttpApi.Host`.
```
"RemoteServices": {
    "Default": {
      "BaseUrl": "https://localhost:44316/"
    }
  }
```
5. Create a service, inject the interface reference and call the method inside of the service.


Then, running both solutions  I fall into the reported error.

**Comment by agustinsilvano** [comment]
@hitaspdotnet what I'm doing wrong?

**Comment by agustinsilvano** [comment]
@hitaspdotnet @maliming any updates?

Thanks!

**Comment by xyfy** [comment]
> @hitaspdotnet @maliming any updates?
> 
> Thanks!

you  can  share  a demo project which can reproduce  this issue.

**Comment by LGinC** [comment]
Maybe your controller is not  implement `IOfficeAppService`   or not attribute `RemoteService` in your controller
```Csharp
[RemoteService]
[Route("api/xxx")]
public class OfficeAppController : XXXManagementController, IOfficeAppService
{
}
```
