### ISSUE TITLE
System.FormatException: Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#993]
![image](https://user-images.githubusercontent.com/16735741/55869160-8b425100-5bb8-11e9-88ad-54cf7e0a5d3e.png)

````csharp
2019-04-10 17:33:11.402 +08:00 [ERR] Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
   at System.Guid.Parse(ReadOnlySpan`1 input)
   at System.Guid.Parse(String input)
   at System.Security.Principal.AbpClaimsIdentityExtensions.FindUserId(ClaimsPrincipal principal) in D:\Github\abp\framework\src\Volo.Abp.Security\System\Security\Principal\AbpClaimsIdentityExtensions.cs:line 21
   at Volo.Abp.Users.CurrentUser.get_Id() in D:\Github\abp\framework\src\Volo.Abp.Security\Volo\Abp\Users\CurrentUser.cs:line 16
   at Volo.Abp.Auditing.AuditPropertySetter.SetCreatorId(Object targetObject) in D:\Github\abp\framework\src\Volo.Abp.Auditing\Volo\Abp\Auditing\AuditPropertySetter.cs:line 57
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ApplyAbpConceptsForAddedEntity(EntityEntry entry, EntityChangeReport changeReport) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 192
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ApplyAbpConcepts(EntityEntry entry, EntityChangeReport changeReport) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 175
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.ApplyAbpConcepts() in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 162
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) in D:\Github\abp\framework\src\Volo.Abp.EntityFrameworkCore\Volo\Abp\EntityFrameworkCore\AbpDbContext.cs:line 133
   at Volo.Abp.Uow.UnitOfWork.SaveChangesAsync(CancellationToken cancellationToken) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 87
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken) in D:\Github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWork.cs:line 133
   at Volo.Abp.AspNetCore.Mvc.Uow.AbpUowActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in D:\Github\abp\framework\src\Volo.Abp.AspNetCore.Mvc\Volo\Abp\AspNetCore\Mvc\Uow\AbpUowActionFilter.cs:line 66
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
2019-04-10 17:33:11.462 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
2019-04-10 17:33:11.468 +08:00 [INF] Executed action OneCode.BaoLu.WebApi.Controllers.UserController.CreateFinanceUser (OneCode.BaoLu.Web) in 995.34390000000008ms
2019-04-10 17:33:11.470 +08:00 [INF] Request finished in 1084.9376ms 500 application/json; charset=utf-8
````

Problem restoration
1.
![image](https://user-images.githubusercontent.com/16735741/55869294-d2c8dd00-5bb8-11e9-9379-a3755c952896.png)
2.
![image](https://user-images.githubusercontent.com/16735741/55869381-f855e680-5bb8-11e9-8463-994ad17e0b97.png)

**Comment by maliming** [comment]
Please share the relevant code of JWT.

**Comment by sortjiajun** [comment]
> Please share the relevant code of JWT.
> For example, how do you generate a token?
now, I use this. 
![image](https://user-images.githubusercontent.com/16735741/55871304-f8f07c00-5bbc-11e9-861a-cbe79a467157.png)

berfore, I use this.
![image](https://user-images.githubusercontent.com/16735741/55871453-35bc7300-5bbd-11e9-81c9-71ca9b5cfff6.png)

**Comment by maliming** [comment]
Abp uses the Guid type as the **UserId**.
It looks like your **UserId** is of type int.

**Comment by sortjiajun** [comment]
> Abp uses the Guid type as the **UserId**.
> It looks like your **UserId** is of type int.

Uh..


I mean I didn't use the 'Volo.Abp.Auditing' module, why does the abp framework execute these code about  'Volo.Abp.Auditing'?

**Comment by maliming** [comment]
Maybe you depend on this module indirectly.

**Comment by hikalkan** [comment]
I am closing this since UserId is Guid in ABP framework, it is not configurable.
You can try to replace IAuditPropertySetter with your own implementation, but you will have other problems if you continue to use int for your user PK.
