### ISSUE TITLE
My background worker method can not be executed after integrating BackgroundWorkers Quartz

### ISSUE THREAD

**Issue by dym0080** [abpframework/abp#9972]
ABP version: 4.4.2
Quartz version: 3.3.0

I integrate BackgroundWorkers Quartz according to the official documentation. Below are my steps:
1. Add the Volo.Abp.BackgroundWorkers.Quartz NuGet package to my new ConsoleApp project.
2. Add code to ConsoleAppModule.

```cs
[DependsOn(
        typeof(AbpAutofacModule),
        // typeof(AbpBackgroundJobsQuartzModule),
        typeof(AbpBackgroundWorkersQuartzModule)
        //typeof(LIMSDomainModule),
        //typeof(LIMSEntityFrameworkCoreModule)
    )]
    public class ConsoleAppModule : AbpModule
    {
        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            context.AddBackgroundWorker<MyLogWorker>();
        }

        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();
            PreConfigure<AbpQuartzOptions>(options =>
            {
                options.Configurator = configure =>
                {
                    configure.UsePersistentStore(storeOptions =>
                    {
                        storeOptions.UseProperties = true;
                        storeOptions.UseOracle(configuration.GetConnectionString("Default"));
                        storeOptions.UseClustering(t =>
                        {
                            t.CheckinMisfireThreshold = TimeSpan.FromSeconds(20);
                            t.CheckinInterval = TimeSpan.FromSeconds(10);
                        });
                        storeOptions.UseJsonSerializer();
                    });
                };
            });

        }

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();
            var hostEnvironment = context.Services.GetSingletonInstance<IHostEnvironment>();

            Configure<AbpBackgroundWorkerQuartzOptions>(options =>
            {
                options.IsAutoRegisterEnabled = true;
            });

            //context.Services.AddHostedService<ConsoleAppHostedService>();
        }

        
    }
```
3. Create HelloWorldService.cs

```cs
public class HelloWorldService : ITransientDependency
    {
        public void SayHello()
        {
            Console.WriteLine("\tHello World!");
        }
    }
```

4. Create MyLogWorker.cs.

```cs
public class MyLogWorker : QuartzBackgroundWorkerBase
    {
        private readonly HelloWorldService _helloWorldService;

        public MyLogWorker(HelloWorldService helloWorldService)
        {
            _helloWorldService = helloWorldService;
            JobDetail = JobBuilder.Create<MyLogWorker>().WithIdentity(nameof(MyLogWorker)).Build();

            Trigger = TriggerBuilder.Create()
                .WithIdentity(nameof(MyLogWorker)).WithSimpleSchedule(
                s => s.WithIntervalInMinutes(1).RepeatForever().WithMisfireHandlingInstructionIgnoreMisfires())
                .Build();

            ScheduleJob = async scheduler =>
            {
                if (!await scheduler.CheckExists(JobDetail.Key))
                {
                    await scheduler.ScheduleJob(JobDetail, Trigger);
                }
            };
        }

        public override  Task Execute(IJobExecutionContext context)
        {
           _helloWorldService.SayHello();
            Logger.LogInformation("Executed MyLogWorker..!");
            return Task.CompletedTask;
        }
    }
```

5. Program code:

```cs
public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
#if DEBUG
                .MinimumLevel.Debug()
#else
                .MinimumLevel.Information()
#endif
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Async(c => c.File("Logs/logs.txt"))
                .WriteTo.Async(c => c.Console())
                .CreateLogger();

            try
            {
                Log.Information("Starting console host.");
                await CreateHostBuilder(args).RunConsoleAsync();
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly!");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }

        }

        internal static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseAutofac()
                .UseSerilog()
                .ConfigureAppConfiguration((context, config) =>
                {
                    //setup your additional configuration sources
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddApplication<ConsoleAppModule>();
                });
    }
```
Then I debug this ConsoleApp, execute method  in the MyLogWorker class can not be executed. so "Hello World!" can not be output.

I checked all issues related to Quatz in ABP issues, but I still don't know where the problem is.

**Comment by maliming** [comment]
hi

Can you share a project?

**Comment by dym0080** [comment]
@maliming 
Yes, the project is here.  https://github.com/dym0080/ABPstudy/tree/master/BookStore-Mvc-EfCore

Please use Acme.BookStore.ConsoleApp as the startup project

**Comment by maliming** [comment]
Please share a minimum project. Thanks

**Comment by dym0080** [comment]
@maliming 
The minimum project is here. https://github.com/dym0080/AbpBackgroundWorkersQuartzDemo

**Comment by maliming** [comment]
Uncomment this line.

https://github.com/dym0080/AbpBackgroundWorkersQuartzDemo/blob/1e35934a0bc19cc34ba04d9e0ef5b33e64e9c945/src/Acme.ConsoleApp/ConsoleAppModule.cs#L60

**Comment by dym0080** [comment]
Otherwise, if I upgrade Quartz.Serialization.Json package to v3.3.0, there will be an error as below:
```
[17:00:40 INF] Starting console host.
[17:00:40 FTL] Host terminated unexpectedly!
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.Quartz.AbpQuartzModule, Volo.Abp.Quartz, Version=4.4.2.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'Void Quartz.SchedulerBuilder.UseJobFactory()'.
   at Quartz.ServiceCollectionQuartzConfigurator.UseJobFactory[T](Action`1 configure)
   at Quartz.ServiceCollectionQuartzConfigurator.UseMicrosoftDependencyInjectionScopedJobFactory(Action`1 configure)
   at Volo.Abp.Quartz.AbpQuartzModule.<>c__DisplayClass1_0.<ConfigureServices>b__0(IServiceCollectionQuartzConfigurator build)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, NameValueCollection properties, Action`1 configure)
   at Volo.Abp.Quartz.AbpQuartzModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Acme.ConsoleApp.Program.<>c.<CreateHostBuilder>b__1_1(HostBuilderContext hostContext, IServiceCollection services) in D:\mygit\AbpBackgroundWorkersQuartzDemo\src\Acme.ConsoleApp\Program.cs:line 55
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
   at Acme.ConsoleApp.Program.Main(String[] args) in D:\mygit\AbpBackgroundWorkersQuartzDemo\src\Acme.ConsoleApp\Program.cs:line 30
```

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/4.4.2/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.Quartz/Volo.Abp.BackgroundJobs.DemoApp.Quartz.csproj#L9

**Comment by dym0080** [comment]
I got it. Thanks for your help!
