### ISSUE TITLE
Incompatibility between versions

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#9973]
I am using a microservice approach and some new services are using abp 4.4.0. So when I try to using 4.4.0 service with 4.3.x service in aggregating services the error occurs.
`Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule, Volo.Abp.AspNetCore.Mvc, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Volo.Abp.Domain.Entities.IHasConcurrencyStamp' from assembly 'Volo.Abp.Ddd.Domain, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
`

Does that mean I have to update all my microservices to 4.4.0

**Comment by realLiangshiwei** [comment]
Yes, you needed.
